### ISSUE TITLE
[Bug] The app closes as soon as it is downloaded list

### ISSUE THREAD

**Issue by Halerick-slash** [YTVanced/Vanced#1001]
Sorry me for my English, I'm from Russia. So, The app just closes, sometimes even without downloads, the error screen does not fly out. I tried to reinstall YTVansed, Manager, same. By the way, this is not the first time, but then the bug disappeared after the Permutations. Now I don't can open this app. 

**Root**
Non-Root

**Vanced version**
16.20.35

**Android version**
10.0.0.250

**Device**
Honor 10 lite

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2. Downloaded list
3. App close

**Expected behavior**
The app will work without errors, as beforeThe application will work without errors as before. 

Here's a video link that can help:
https://drive.google.com/file/d/1MmirO4GIEUHSTZXCQmQ76KBLS8DPTlgc/view?usp=drivesdk

**Comment by milindgoel15** [comment]
Attach logcat. We cannot help you otherwise

**Comment by Halerick-slash** [comment]
Good evening
Sorry, i don't know exactly which of these files, I bad understand "logcat"

*** command 'lshal debug -E ***@***.***::IAtraceDevice/default' failed: exit code 128

*** command 'lshal debug -E ***@***.***::ISensorManager/default' failed: exit code 128

*** command 'lshal debug -E ***@***.***::IDisplayService/default' failed: exit code 128

*** command 'lshal debug -E ***@***.***::ISchedulingPolicyService/default' failed: exit code 128

*** command 'lshal debug -E ***@***.***::ICameraService/default' failed: exit code 128

*** command 'lshal debug -E ***@***.***::IDevicesFactory/default' failed: exit code 128

*** command 'lshal debug -E ***@***.***::IStats/default' failed: exit code 128

*** command 'lshal debug -E ***@***.***::IEffectsFactory/default' failed: exit code 128

**Comment by milindgoel15** [comment]
None of above are vanced related stacktrace. Please try reinstalling vanced from start and see if it crashes again
