### ISSUE TITLE
App closes automatically when try to play live stream videos

### ISSUE THREAD

**Issue by saur143** [YTVanced/Vanced#1004]
Whenever I try to play live stream videos , app crashes automatically.
OS version: Android 10
Phone : Realme narzo 30a

**Comment by mirzadikami** [comment]
That's right
the same thing happens to me (since today)

Device : Samsung Galaxy A30S 
Android 10

**Comment by milindgoel15** [comment]
Attach logcat of your crash. We can't help you otherwise

**Comment by saur143** [comment]
[Solved] Problem  solved after installing vanced microG.
Earlier I was using YouTube vanced without vanced microG.
