### ISSUE TITLE
About age restricted videos

### ISSUE THREAD

**Issue by astankov84** [YTVanced/Vanced#1005]
Here in Europe Youtube started asking to confirm our age to be able to watch age restricted videos. Requires us to show our credit card or valid ID with clearly visible picture or driving license. I personally don't wan't to share this sensitive personal information with Google or whatever online service just to be able to watch this kind of content. Is it possible this to be bypassed in Vanced? In another third party Youtube client called NewPipe is possible to be bypassed that is why I ask here. 

Have a nice day!

**Comment by milindgoel15** [comment]
Duplicate

**Comment by astankov84** [comment]
OK I searched but did not found similar thing that's why I asked. Delete this please

Thankyou!
