### ISSUE TITLE
[Bug] Brightness issue for horizontal mode isn't fixed? 

### ISSUE THREAD

**Issue by Harmonie666** [YTVanced/Vanced#1009]
I'm using the latest Version 16.20.35 with Android 10. The brightness for videos in horizontal mode doesn't follow system brightness, and still gets brighter on it's own. Not as much as before, but still doesn't follow system brightness for some reason. I have HDR max brightness turned off.

**Comment by milindgoel15** [comment]
This is related to how swipe controls work.

- If swipe controls are on, Vanced brightness ≠ system brightness. They become independent from each other
- If swipe controls are off, vanced brightness will follow with system brightness.

So if you don't want to see vanced increasing brightness and follow the system one instead, turning swipe controls for brightness.

**Comment by Harmonie666** [comment]
Gotchu. 
If I remember correctly this used to work before, independently from swipe controls.

But I guess your right. Does it mean it can in no way be adjusted by devs, that swipe controls follow system brightness? Just for clarification.

**Comment by milindgoel15** [comment]
No
