### ISSUE TITLE
[Idea] Repeat button in notification tab

### ISSUE THREAD

**Issue by LMarius** [YTVanced/Vanced#1010]
**Description**
When u open a video on yt vanced and put it in the background and a notification will appear to control the video and get to next song etc. it should be better if a repeat button appears to turn it on/off

![Screenshot_20210625-013906_Chrome](https://user-images.githubusercontent.com/85368976/123341393-8e864500-d556-11eb-9b9a-c6e3cc2ba22e.jpg)

I think spotify has that feature,but idk,i do not use spotify anymore.

**Comment by milindgoel15** [comment]
The notification even now has enough number of quick controls. Adding one more will make notification worse. That's why we only see max 6 controls in every app.
