### ISSUE TITLE
[Bug] Only video is shown

### ISSUE THREAD

**Issue by Mimicthis** [YTVanced/Vanced#1011]
**Bug description**
Even when reset, the comment section and suggested videos go away, only video playing stays. 

**Variant**
Non-Root

**Vanced version**
16.20.35

**Android version**
Android 11 

**Device**
Samsung Galaxy S10 Plus

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2. Click on video
3. Stay on it 
4. Go to other app and come back 

![Screenshot_20210625-053538](https://user-images.githubusercontent.com/29215437/123365999-a91ce600-d577-11eb-8f28-0b7bc95ee009.jpg)

How to attach log cat? Error logs?

**Comment by Sher1ocks** [comment]
me too. it is critical issue for me.
i have to close vanced app and open it again.

**Comment by milindgoel15** [comment]
Check if this happens on stock yt

**Comment by Mimicthis** [comment]
It's not happening on stock YouTube, thank you.

**Comment by milindgoel15** [comment]
We can't really reproduce this here. Do you have better approach for reproducing such issue. The current listed steps gives no issues as such.

**Comment by Sher1ocks** [comment]
![Screenshot_20210627-112232](https://user-images.githubusercontent.com/2107738/123530841-0791c200-d73a-11eb-950b-91f396f59323.jpg)
everytime happen.. i want to see comments

**Comment by Mimicthis** [comment]
Thanks for taking me seriously this time at least.

**Comment by milindgoel15** [comment]
Nah we just knew about this bug even before v16.20 got released to public. But no one could reproduce it.

**Comment by Mimicthis** [comment]
So you don't take me seriously. 😢
