### ISSUE TITLE
[Idea] Please find a way to disable age restriction completely.

### ISSUE THREAD

**Issue by DAMAGEBEATS** [YTVanced/Vanced#1014]
**Description**
Being forced into sharing your private credit card details should be illegal.

_Attach images/videos if possible. Also add any links to possible other applications with the said feature already implemented._

**Comment by milindgoel15** [comment]
Complain to google if it sounds illegal to you

**Comment by TrianguloY** [comment]
Note: I use a very old Vanced version on a tablet with android 4 (where newer versions are not supported) and the age restriction popup is not shown, age restricted videos can be played there without any problem. Maybe that can be simulated?

**Comment by Fusseldieb** [comment]
> Note: I use a very old Vanced version on a tablet with android 4 (where newer versions are not supported) and the age restriction popup is not shown, age restricted videos can be played there without any problem. Maybe that can be simulated?

Seems like he just doesn't want to fix this... 

Not much that we can do then.

**Comment by kineci** [comment]
> Complain to google if it sounds illegal to you

Wow, really helpful
