### ISSUE TITLE
[Bug] Youtube eventually replaces Vanced.

### ISSUE THREAD

**Issue by romanze87** [YTVanced/Vanced#1015]
**Bug description**
After successful use, eventually stock youtube app replaces vanced. Then eventually youtube app crashes when opening. The only fix is to reinstall vanced again. This has happened over 10 times in a row.

**Variant**
Root

**Vanced version**
v16.24.33

**Android version**
Android 12

**Device**
Pixel3

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the youtube

**Expected behavior**
Vances should open

_Attach images or videos or logcats in case of crashes if possible. These can be helpful in solving the issue._

**Comment by milindgoel15** [comment]
Not bug. Disable auto updates in play store and you will be fine. If still happens, use detach or switch to Non-Root

**Comment by romanze87** [comment]
Thank you, I searched everywhere for that solution. I must of missed it.

**Comment by romanze87** [comment]
Hello, so update, that definitely fixed the return to stock youtube app, but after about 3 days the app crashes when trying to open and theres nothing i can do to start it. I have tried closing all apps and rebooting phone. Force stopping and erasing cache and storage. Nothing works.

**Comment by milindgoel15** [comment]
It got updated again. Just switch to Non-Root version

**Comment by mcfisch** [comment]
I'm on clean install of DotOS 5.1.1 (Android 11) on a OnePlus 6T and have the same problem. The app gets installed and works, updates in Play Store are disabled for YouTube, but the after a day or less suddenly the original YouTube is there again.

What's also weird is that on some other Android 11 ROMs before there were no issues at all - but they also wouldn't show the app in Play Store at all, at least those which won't come with YT included. And those that did would respect the dont-auto-update setting.
