### ISSUE TITLE
[Idea] Block a channel completely 

### ISSUE THREAD

**Issue by leodoi3** [YTVanced/Vanced#1016]
**Description**
I'm tired of seeing videos from click-bait channels appearing in search and recommended.  I want an option to completely hide these channels from the app.

_Attach images/videos if possible. Also add any links to possible other applications with the said feature already implemented._
[Blocktube](https://github.com/amitbl/blocktube) is a webextension that has this feature 
![image](https://user-images.githubusercontent.com/46114199/123531337-8c3bfc00-d6b8-11eb-8300-ca3dcca20e09.png)

**Comment by milindgoel15** [comment]
Without the API, it's almost close to impossible to implement any extension. If you find some, then you can suggest them. (or contribute by coding this extension on the youtube app, for this, you need to decompile the official YT app, apply your code, recompile and test it.)

**Comment by leodoi3** [comment]
> Without the API, it's almost close to impossible to implement any extension. If you find some, then you can suggest them. (or contribute by coding this extension on the youtube app, for this, you need to decompile the official YT app, apply your code, recompile and test it.)
> 
> Until then, this issue is closed.

This would be no different than blocking ads. You'd just have to filter which channels show up.  Check out his repo to see how he does it.

**Comment by milindgoel15** [comment]
> This would be no different than blocking ads. You'd just have to filter which channels show up. Check out his repo to see how he does it.

Why don't you try coding it?
