### ISSUE TITLE
When I tried to install the app it says "Stopped for an unknown reason" I can't install app [Bug] replaceme

### ISSUE THREAD

**Issue by SprIvyFOREVER** [YTVanced/Vanced#1022]
**Bug description**
Replace me with a clear and detailed description of the bug.

**v16.16.38

**Android version**
Android 9

**Device**
Honor 8s 

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
3. ....

**Expected behavior**
Replace me with a description of what you expected should happen and what happened instead.

_Attach images or videos or logcats in case of crashes if possible. These can be helpful in solving the issue._

**Comment by milindgoel15** [comment]
Such nice useful information. If you decide to provide a better information, we will help you then. Otherwise feel free to use stock youtube if you can't bother providing information.
