### ISSUE TITLE
Videos pausing randomly

### ISSUE THREAD

**Issue by GKid94** [YTVanced/Vanced#1024]
YouTube Vanced keeps pausing videos randomly when playing

**Comment by milindgoel15** [comment]
Very useful piece of information

**Comment by GKid94** [comment]
@milindgoel15 ?

**Comment by milindgoel15** [comment]
Do we have to come to your house to see why your phone is pausing videos randomly? You didn't even bother to provide detailed report. How do you expect us to help you?

**Comment by milindgoel15** [comment]
Start doing all this

> A bit of help, start with basic troubleshooting and see if it helps you. Start from clearing app data then reinstallation. If not, check phone settings if you changed anything unusual.
