### ISSUE TITLE
Cashe memory 

### ISSUE THREAD

**Issue by SORAxSHIRO** [YTVanced/Vanced#1025]
![IMG_20210628_201359](https://user-images.githubusercontent.com/76656461/123684351-a3f8b900-d84d-11eb-844d-1e294a37b5b3.jpg)
Is this a bug or something?

**Comment by milindgoel15** [comment]
No it's not bug. Every app can have cache files. The cache files are simply thumbnails and local database at most. They are fine to clear it out.
