### ISSUE TITLE
[Idea] A video queuing functionality 

### ISSUE THREAD

**Issue by GeniusNerd695** [YTVanced/Vanced#1026]
**Description**
A video queque feature like in the desktop youtube website where you can create a temporary collection of videos you want to watch with an option of converting the queque into a permanent playlist

**Comment by Nishit-Dua** [comment]
I really like this, really hope they implement this

**Comment by CHIUNDA** [comment]
Wish Queuing on Android was available

**Comment by hafizmuhmmadismail** [comment]
I sometime use another app for Android but that app is total bulshit except add queuing option. I really appreciate if someone add this feature in vanced app

**Comment by milindgoel15** [comment]
Duplicate of #333
