### ISSUE TITLE
[Bug] Looping not working in pop-up view / background player

### ISSUE THREAD

**Issue by GeniusNerd695** [YTVanced/Vanced#1027]
**Bug description**
The video does not loop when playing in pop-up view or background player

**Variant**
Non-Root

**Vanced version**
16.20.35

**Android version**
 Android 11 

**Device**
 Samsung Galaxy M51

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2. Click on 'Loop' button
3. Open pop-up view or background play

**Expected behavior**
The video is supposed to keep on looping even in pop-up view /background play but stops looping and plays the next video (if autoplay is on)  or stops if autoplay is disabled

**Comment by milindgoel15** [comment]
Loop works fine as they should. For loop to work, you need auto Play off and you are not playing videos in a playlist. The loop will never work inside playlist so if you are doing that, play videos from outside playlist for loop to work.
