### ISSUE TITLE
[Bug] 60fps videos are limited to 480p

### ISSUE THREAD

**Issue by Nayr7928** [YTVanced/Vanced#1028]
**Bug description**
Setting a video resolution to 1080p60 or higher resolutions makes the video limited to only 480p. This also applies to any video preference setting. Reinstalling or restarting device didn't fix the issue. This device supports up to 4k30 or 2k60.

**Variant**
Non-Root

**Vanced version**
v16.20.35

**Android version**
Android 11 

**Device**
Poco X3 NFC Global

**Steps to Reproduce**
Steps to reproduce the error:
Method 1
1. Open the app
2. Click on a video
3. Set video resolution to 1080p60 or higher
Method 2
1. Open the app
2. Open settings > Video quality preferences
3. Choose higher quality
Method 3
1. Open the app
2. Open settings > Vanced settings > Video settings
3. Turn on "Max Resolution" or set preferred video quality to 1080p60 or higher. 

**Expected behavior**
If the video has 1080p60 available, it will show 480p as the max available video quality.

Before:
![Screenshot_2021-06-29-15-04-15-079_com vanced android youtube](https://user-images.githubusercontent.com/86649318/123752390-503cad00-d8eb-11eb-86b7-98dfe0a1076a.jpg)

After:
![Screenshot_2021-06-29-15-04-02-846_com vanced android youtube](https://user-images.githubusercontent.com/86649318/123752444-5d599c00-d8eb-11eb-8d2a-d36ba27afc12.jpg)

**Comment by milindgoel15** [comment]
![Screenshot_20210629-132229_YouTube.png](https://user-images.githubusercontent.com/45682747/123758979-18c70400-d8dd-11eb-9f59-f82a55a762cd.png)

![Screenshot_20210629-132211_YouTube.png](https://user-images.githubusercontent.com/45682747/123759002-1d8bb800-d8dd-11eb-9124-b46fec645914.png)

Fine here. The thing is, you literally need to wait for YouTube to buffer accordingly for few seconds.

**Comment by Nayr7928** [comment]
That's not the case for me. It still isn't fixed even after reinstalling all vanced related apps. I also found out that I can play 1080p60 HDR and higher fine but if it's not HDR then a 1080p60 vid will just go to 480p.

**Comment by Nayr7928** [comment]
milindgoel15 closed this one too early.

The problem is now suddenly fixed. I didn't do anything that fixed it. It just fixed itself. There are no changes in app or OS version that triggered the problem and the fix, so the root of the issue is still not identified.
