### ISSUE TITLE
[Bug] Cannot open link in comment 

### ISSUE THREAD

**Issue by suan5555** [YTVanced/Vanced#1030]
**Bug description**
Cannot open link (URL) in comment

**Variant**
Non-Root

**Vanced version**
v16.20.35

**Android version**
Android 11 RKQ1.200826.002

**Device**
Poco x3 nfc

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2. open clip
3. click link in comment
4. 
![Screenshot_2021-06-30-00-53-31-512_com vanced android youtube](https://user-images.githubusercontent.com/86681661/123844868-be11c480-d93d-11eb-9cc2-027908b060b6.jpg)

**Expected behavior**
Replace me with a description of what you expected should happen and what happened instead.

_Attach images or videos or logcats in case of crashes if possible. These can be helpful in solving the issue._

**Comment by milindgoel15** [comment]
Show the error in English.

**Comment by milindgoel15** [comment]
Never mind, this error is related to default links set in your system. Just disable official YouTube app or change the default app to vanced. Nothing else can be done for this.
