### ISSUE TITLE
[Idea] option to persist video quality when changed manually

### ISSUE THREAD

**Issue by Nishit-Dua** [YTVanced/Vanced#1032]
**Description**
I have set my video quality to default to 720p, if i change the quality manually to some other value and play another video it'd reset back to 720p.

It would be amazing to have an option to persist the quality settings if changed manually, and default back once the player is closed.
Something like how playback speed works!

**Comment by milindgoel15** [comment]
You want to defeat the purpose of vanced preferred quality? Seems like it
