### ISSUE TITLE
White splashscreen on Asus ZenPhone Max Pro

### ISSUE THREAD

**Issue by Bezbazaroff** [YTVanced/Vanced#1036]
White splash screen and black theme. Please fix it.
![photo_2021-06-30_11-12-21](https://user-images.githubusercontent.com/86682803/124147478-65563f00-da97-11eb-9f7f-1b12ca2719da.jpg)
![photo_2021-06-30_11-12-47](https://user-images.githubusercontent.com/86682803/124147485-67200280-da97-11eb-80b3-b4274beb2410.jpg)

**Comment by milindgoel15** [comment]
Update your android to android 10+
