### ISSUE TITLE
[Idea] Blocking out the full screen promotion

### ISSUE THREAD

**Issue by MKCOOL142** [YTVanced/Vanced#104]
I would like (if possible) to be able to disable YouTube's own advertisements for YouTube premium, they are annoying and just way to bright at night as well lol
![Screenshot_20201020_235521_com vanced android youtube](https://user-images.githubusercontent.com/40364718/96648823-3dbbae00-1330-11eb-8175-530c286ef64a.jpg)

**Comment by DraconicNEO** [comment]
This is an important feature and should be considered.
