### ISSUE TITLE
[Idea] Lock Vanced Settings Feature

### ISSUE THREAD

**Issue by alieren3453** [YTVanced/Vanced#1042]
**Description**
Can you please add a PIN Lock Feature to Lock Vanced Settings, It is really, really necessary to me. Thanks for making this amazing app. 

_Attach images/videos if possible. Also add any links to possible other applications with the said feature already implemented._

**Comment by milindgoel15** [comment]
Why would you even open vanced settings 24*7 in your life? Just stop putting your mind towards it. Use vanced normally as you would with stock YouTube.

**Comment by Iammethe24** [comment]
Maybe their kids like to play around with it

**Comment by SaberAkiyama** [comment]
Why didn't add Vanced for Kids app, instead
