### ISSUE TITLE
[Bug] Crashing when opening

### ISSUE THREAD

**Issue by SmartManoj** [YTVanced/Vanced#1043]
**Bug description**
Crashing when opening

**Variant**
Non-Root

**Vanced version**
v16.20.35

**Android version**
10 QkQ1
**Device**
Redmi 8A; MIUI 12.0.3
**Steps to Reproduce**
Steps to reproduce the error:
1. Just open the app

Logcat:
https://pastebin.com/91BUebp4

**Comment by SmartManoj** [comment]
In MicroG, Got "Sorry there was a problem communicating with google servers"

**Comment by milindgoel15** [comment]
Reinstall microG

**Comment by SmartManoj** [comment]
> Reinstall microG

Clear Data vs Reinstall?

**Comment by SmartManoj** [comment]
> > Reinstall microG
> 
> Clear Data vs Reinstall?

https://android.stackexchange.com/a/29619/218607

**Comment by milindgoel15** [comment]
Goddamn, do you even understand the difference between clear data and reinstall microG? I literally said "**REINSTALL MICROG**"

**Comment by milindgoel15** [comment]
Do you happen to use any external adblocker or custom DNS or proxy or anything else?

**Comment by SmartManoj** [comment]
Not yet, for first question. In reddit, they told to use VPN.

**Comment by milindgoel15** [comment]
Without VPN and internet being turned off, check whether it crashes again when starting the app or not.

> Not yet, for first question. In reddit, they told to use VPN.

**Comment by milindgoel15** [comment]
If this issue has not solved yet for you, please try reinstalling all vanced applications. It has been seen that reinstallation every app fixes crashing issue faced by users.

Meanwhile we are closing this issue for now. Please report back to us here if the workaround fix fails.
