### ISSUE TITLE
[Bug] Blurry thumbnail in open video in history

### ISSUE THREAD

**Issue by WonSanji** [YTVanced/Vanced#1044]
**Bug description**
When i load a thumbnail in an open video in history by exiting and re-entering Vanced without closing it or go to other app and come back, the thumbnail get blurry this only happens in the last version 16.20.35 i already checked it in the previous version 16.16.38 and it does not happen, the thumbnails in all non-open videos load normal.

It always happens in the second time you open a video in history and then it stays that way in all the videos until closing YT Vanced and reopen it

**Variant**
Non-Root

**Vanced version**
16.20.35 lastest

**Android version**
Android 7.1.1

**Device**
Moto G4 Play

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2. Click on a video in history and close it a couple of times
3. Exit and re-enter without closing vanced or go to other app and come back
4. Blurry thumbnail

**Expected behavior**
The thumbnail should load in the resolution that was uploaded

![Screenshot_20210702-193710](https://user-images.githubusercontent.com/86864986/124343506-8bf8a080-db91-11eb-9424-8507f5213d5e.png)
normal loaded thumbnail (first entry in the video)

![Screenshot_20210702-193647](https://user-images.githubusercontent.com/86864986/124343505-8ac77380-db91-11eb-8bf0-0a4e1d1058c8.png)
blurry loaded thumbnail (second, third, fourth... entry in the video or other videos)

![Screenshot_20210702-193814](https://user-images.githubusercontent.com/86864986/124343507-8c913700-db91-11eb-876c-aedfad795c4a.png)
non-open video loaded thumbnail in history

**Comment by WonSanji** [comment]
i think it is a version error

**Comment by milindgoel15** [comment]
Check official yt before creating bug report here.

**Comment by WonSanji** [comment]
Sorry i didn't realize that, thank you man
