### ISSUE TITLE
Down?

### ISSUE THREAD

**Issue by Mik39907** [YTVanced/Vanced#1045]
**Description**
Anyone else app says its Offline?

**Comment by milindgoel15** [comment]
Duplicate of #786

Start reading guides instead of creating duplicates

**Comment by Mik39907** [comment]
> Duplicate of #786
> 
> Start reading guides instead of creating duplicates

yea the problem is there was no update and it worked fine yesterday and before that and before that etc.. but sure ill reinstall it
