### ISSUE TITLE
[Bug] Crashes when locking screen

### ISSUE THREAD

**Issue by lfercorrea** [YTVanced/Vanced#1046]
**Bug description**
When playing a video, if i lock the screen, the yt vanced will crash in mostly times. But if I minimize the app first, it's okay.

**Variant**
Non-Root

**Vanced version**
v16.20.35 (but the previous version had the same issue)

**Android version**
Android 9

**Device**
Motorola G6

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app;
2. Play a video normally;
3. with the app in foreground, lock the screen.

**Expected behavior**
The video should remain playing, but not.

**Comment by milindgoel15** [comment]
Disable battery optimization for all vanced apps using https://dontkillmyapp.com
