### ISSUE TITLE
[Idea] Take notes from videos

### ISSUE THREAD

**Issue by doGior** [YTVanced/Vanced#1048]
**Description**
Since SponsorBlock was added to the app, would it be possible to add something like [YiNote](https://github.com/shuowu/yi-note) in order to take notes from videos?

I would love a similar feature

![immagine](https://user-images.githubusercontent.com/43815981/124364705-8b204700-dc43-11eb-8f38-c20e224de0c4.png)

**Comment by milindgoel15** [comment]
This is something google should add, not us.
