### ISSUE TITLE
adverts in "up next" section 

### ISSUE THREAD

**Issue by WarningHPB** [YTVanced/Vanced#105]
Hi there, 

Not sure if this is a bug or not, but I'm getting adverts in the up next section. I have also enabled all the advert removal options in the ad settings menu. I've added some screenshots below 

![Screenshot_20201020-155554](https://user-images.githubusercontent.com/72869860/96662569-8aaa7f00-1346-11eb-8e40-6790f84344a6.png)
![Screenshot_20201020-155856](https://user-images.githubusercontent.com/72869860/96662685-c7767600-1346-11eb-8760-9d956f4084eb.png)

**Comment by milindgoel15** [comment]
this has been fixed already. Please update to the latest release if you haven't already. Closing issue
