### ISSUE TITLE
[Bug] Huge box in the comment section while long pressing on currently typed comment

### ISSUE THREAD

**Issue by Mimicthis** [YTVanced/Vanced#1050]
**Bug description**
Huge box in the comment section while long pressing on currently typed comment and it's not allowing me to copy or paste, select all etc. 

**Variant**
Non-Root

**Vanced version**
16.20.35

**Android version**
Android 11 

**Device**
Samsung Galaxy S10 Plus 

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2. Go to comment's section
3. Type something as a comment
4. Tap on it and see if it shows the nice basic thin bar with copy, paste, select all or a huge box with those and covers your comment whilst typing. 

**Expected behavior**
Normal thin bar with copy, paste select all etc. should appear. 

How to post log cats, crashes? 
![Screenshot_20210704-180817](https://user-images.githubusercontent.com/29215437/124392026-c8441200-dcf3-11eb-9493-ca2e9d2d0add.jpg)

**Comment by milindgoel15** [comment]
Known bug, xfile hasn't got any time since 16.16 release so some of the old minor bugs will take time.

**Comment by milindgoel15** [comment]
This is stock yt bug unfortunately. Ask Google for fix.

**Comment by Mimicthis** [comment]
I'm sorry but that's not true.

Regular YouTube: 
![Screenshot_20220122-161818_YouTube](https://user-images.githubusercontent.com/29215437/150644596-4a0d399e-7dc3-4c85-89d2-c85566731d26.jpg)
 YouTube Vanced: 
![Screenshot_20220122-161845](https://user-images.githubusercontent.com/29215437/150644608-8bd8fdb4-ca6d-4e1d-9c28-1b7a18ecd815.jpg)

**Comment by milindgoel15** [comment]
we have confirmed it to be stock bug. Ur OEM probably likes stock more than vanced. Some other oems will give issues on stock as well as every OEM handles their text selection differently.

**Comment by Mimicthis** [comment]
So what should I do, tell Samsung to fix Vanced bug?

**Comment by milindgoel15** [comment]
didn't say its an OEM bug, its a google bug Jesus

**Comment by gghhkm** [comment]
> I'm sorry but that's not true.
> 
> Regular YouTube: ![Screenshot_20220122-161818_YouTube](https://user-images.githubusercontent.com/29215437/150644596-4a0d399e-7dc3-4c85-89d2-c85566731d26.jpg)
> 
> YouTube Vanced: ![Screenshot_20220122-161845](https://user-images.githubusercontent.com/29215437/150644608-8bd8fdb4-ca6d-4e1d-9c28-1b7a18ecd815.jpg)

Vanced is based on a much older version of stock YouTube.
Just wait for next update.

**Comment by Mimicthis** [comment]
> > I'm sorry but that's not true.
> > Regular YouTube: ![Screenshot_20220122-161818_YouTube](https://user-images.githubusercontent.com/29215437/150644596-4a0d399e-7dc3-4c85-89d2-c85566731d26.jpg)
> > YouTube Vanced: ![Screenshot_20220122-161845](https://user-images.githubusercontent.com/29215437/150644608-8bd8fdb4-ca6d-4e1d-9c28-1b7a18ecd815.jpg)
> 
> Vanced is based on a much older version of stock YouTube. Just wait for next update.

Thanks!
