### ISSUE TITLE
[Bug] SponsorBlock "Show button to skip section" breaks after some time 

### ISSUE THREAD

**Issue by 2dgeneralspam1** [YTVanced/Vanced#1051]
**Bug description**
The SponsorBlock "Show button to skip section" option will break after a certain amount of idle time. It will not break if Vanced is being currently used. Annoying because if you leave the app and come back SponsorBlock will break. 

**Variant**
Non-Root

**Vanced version**
16,20,35 (Latest version as of 7/4) 

**Android version**
Andriod 9 

**Device**
Samsung Galaxy S8 

**Steps to Reproduce**
Leave the app focused and then turn off (press the power button once, not complete shutdown) the device. Come back after a while and the button that says "skip" will not show when entering a sponsored segment. 

**Expected behavior**
A button that says "skip" should show up. Instead, it does not.

**Comment by milindgoel15** [comment]
Known, will be fixed with next vanced release.

Also, this is not the correct repo to report vanced sponsorblock implementation bugs. Please report right bugs in right repos.
