### ISSUE TITLE
[Idea] Confirm Settings

### ISSUE THREAD

**Issue by 2dgeneralspam1** [YTVanced/Vanced#1052]
**Description**
I don't know if other people are like me, but I worry that my selected settings are unsaved when I modify Vanced's settings. It would be nice if there was a button to confirm your changes so I can be sure that my settings were saved. Also, this would help prevent me, and other future users, from accidentally toggling functions that I do not want to be on.

**Comment by milindgoel15** [comment]
That's literally useless, every app saves user settings whether it has confirmation dialog or not. This even goes with other software platform.
