### ISSUE TITLE
[Bug] replaceme

### ISSUE THREAD

**Issue by wideboi124** [YTVanced/Vanced#1053]
**Bug description**
Glitched green livestream music

**Variant**
Non-Root

**Vanced version**
The Latest Version installed: 16.20.35

**Android version*
Android 11 

**Device**
Samsung Galaxy A51 (4G RAM)

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2. Click on 'lofi hip hop radio'
3. Then appears some glitch green screen then dissapears for 4 seconds (APPEAR ONCE WHEN YOU PRESS THE VIDEO)

**Expected behavior**
Actually this isn't bad, is a bug and this needs to be fixed soon.

**Comment by wideboi124** [comment]
and for the actual bug 
![Screenshot_20210704-230204](https://user-images.githubusercontent.com/86930288/124397968-e4f44000-dd1b-11eb-94b7-130dd5702888.jpg)

**Comment by milindgoel15** [comment]
Issue with your device codecs, not vanced problem. Go to vanced settings > codec override and play with it until it resolves the issue for you.
