### ISSUE TITLE
[Idea] Direct link to this site, Vanced GitHub

### ISSUE THREAD

**Issue by Mimicthis** [YTVanced/Vanced#1056]
**Description**

[Direct link to this site, Vanced GitHub from the Vanced settings " Support links ". 

![Screenshot_20210706-013013](https://user-images.githubusercontent.com/29215437/124524109-0297d700-ddfa-11eb-81e8-1be464deae70.jpg)
![Screenshot_20210706-012949](https://user-images.githubusercontent.com/29215437/124524113-062b5e00-ddfa-11eb-94f0-5899f400c9e2.jpg)

**Comment by ndm13** [comment]
I wanted to see if a bug was reported and had to go to:
- Vanced Manager
- GitHub link
- VancedApp org
- Finally this repo

This was after looking at the official website for a link that wasn't there. This really should be much more public.

**Comment by milindgoel15** [comment]
yea we know, we will consider adding with next version. dw

**Comment by Mimicthis** [comment]
Oh great, my suggestions are appreciated.
