### ISSUE TITLE
[Bug] Subtitles dissappear after some time the app is open

### ISSUE THREAD

**Issue by Mimicthis** [YTVanced/Vanced#1057]
**Bug description**

Subtitles (CC) dissappear and don't appear back until I close and open the app again. 

**Variant**
Non-Root

**Vanced version**
16.20.35

**Android version**
Android 11 

**Device**
Samsung Galaxy S10 Plus 

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2. Click on video
3. Play it for some time
4. Exit the Vanced app but don't close it 
5. Get back in and after 1 hour or so Subtitles (CC) will stop appearing. 

**Expected behavior**
Subtitles (CC) should keep on showing even after using the app for 1 hour or longer and when the app is left opened in the recent apps menu.

**Comment by Russell-Ali** [comment]
I experienced a similar issue when subtitles don't show even I enabled it (They were subtitles at that part). I don't know what triggers it but it happened when I watching hour + long videos although I don't use subtitles when I watch other videos(they are short usually).

**Comment by Mimicthis** [comment]
So @milindgoel15 did you put this as a bug?

**Comment by milindgoel15** [comment]
Have you all checked this on stock official YouTube app already? Does it happen there?

**Comment by Mimicthis** [comment]
> Have you all checked this on stock official YouTube app already? Does it happen there?

I'm not quite sure anymore.

**Comment by milindgoel15** [comment]
> I'm not quite sure anymore. 

Please check it. If it's youtube issue, then there's nothing we can do. Moreover, someone from our beta testers already have tested it and it persists in official yt. We still not have confirmation on it but if you could confirm it, would be great.

**Comment by Mimicthis** [comment]
It's YouTube Vanced issue. I've confirmed it by watching hours of videos on normal YouTube now.

**Comment by Mimicthis** [comment]
And this isn't reported as a bug?
