### ISSUE TITLE
[Idea] Proxy Support

### ISSUE THREAD

**Issue by chromer030** [YTVanced/Vanced#106]
As you know Youtube is blocked in some countries : https://en.wikipedia.org/wiki/Censorship_of_YouTube
So please add proxy support ( socks 5) .
Will be great.
Thanks you very much.

**Comment by gghhkm** [comment]
Just use a VPN.

**Comment by chromer030** [comment]
It's not a good idea to tunnel a whole traffic just because of a single app.
Along side Gapps . some local websites doesn't work with VPN.

**Comment by gghhkm** [comment]
> It's not a good idea to tunnel a whole traffic just because of a single app.
> Along side Gapps . some local websites doesn't work with VPN.
Ever heard of Split Tunneling?

**Comment by chromer030** [comment]
> Ever heard of Split Tunneling?

Yes , but all of VPN providers doesn't support this mode of networking.
I know ExpressVPN supports this type.
Supporting Proxies is one of the best features of most apps.
If there is not any possibility to add this feature you can close this Feature Request.
Thank you.

**Comment by xmha97** [comment]
I also have this request.
I need the Proxy option.
`Socks5` or at least `HTTP`
Thanks.

**Comment by gghhkm** [comment]
https://github.com/YTVanced/Vanced/issues/338#issuecomment-822695233
