### ISSUE TITLE
[Bug] replaceme

### ISSUE THREAD

**Issue by Bio1Mod** [YTVanced/Vanced#1062]
**Bug description**
the functions button shifted to the edge of the screen and free space on top 

**Variant**
Non-Root

**Vanced version**
 v16.20.35

**Android version**
Android 10

**Device**
Oneplus 7 pro

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app

**Expected behavior**
place it in the same place as on other screens.

[Video](https://youtu.be/cOZDZpgzOTc)

**Comment by milindgoel15** [comment]
Disable wide search bar

**Comment by Bio1Mod** [comment]
nothing changes

**Comment by milindgoel15** [comment]
Ok ah I see it. Ur UI seems stretched to both ends. Clear data or reinstall and check again. It should be fixed with this.

**Comment by Bio1Mod** [comment]
thank you, I should have tried it myself
