### ISSUE TITLE
[Bug] YouTube vanced acting like it has no connection 

### ISSUE THREAD

**Issue by Kn07-1** [YTVanced/Vanced#1063]
**Bug description**
Youtube vanced won't connect to server? It's like there's no internet connection yet there is I've tried reinstalling to no avail can reproduce on 2 devices after reboot and cach clearing 

**Variant**
Non-Root

**Vanced version**
16.20.35

**Android version**
8 and 11

**Device**
 BlackBerry key2 and Samsung tab s6lite

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app

**Expected behavior**
Able to access online videos

**Comment by sudo-nautilus** [comment]
Bruh

**Comment by sudo-nautilus** [comment]
Check #396

**Comment by milindgoel15** [comment]
Duplicate of #786
