### ISSUE TITLE
[Question]Yt music vanced pause location base recommendation not working 

### ISSUE THREAD

**Issue by vihaan-Dev** [YTVanced/Vanced#1064]
In the yt music vanced.Whenever I turn on pause location based suggestion it turns back off I don't know why.
![Screenshot_20210708-112413_YouTube Music](https://user-images.githubusercontent.com/69802401/124884333-cc23ad00-dfef-11eb-9d5f-ec3756bf7512.jpg)

**Comment by milindgoel15** [comment]
Does it work on official music of same version?

**Comment by vihaan-Dev** [comment]
> Does it work on official music of same version?

Yeah it does.

**Comment by milindgoel15** [comment]
Alright.

**Comment by Oizaro** [comment]
> In the yt music vanced.Whenever I turn on pause location based suggestion it turns back off I don't know why.
> ![Screenshot_20210708-112413_YouTube Music](https://user-images.githubusercontent.com/69802401/124884333-cc23ad00-dfef-11eb-9d5f-ec3756bf7512.jpg)

In short: we can't fix microg bug, so you need to ensure this error happens also on stock MicroG/YouTube Music.

If happens there as well, can't be fixed.

**Comment by milindgoel15** [comment]
As oizaro said, please check the same issue on official YouTube music but on a software based on microG project, not a device with google play services.

**Comment by Vendicated** [comment]
I just tried and this issue happens with system microg and stock youtube music too. so this is not a vanced issue and should be reported over at https://github.com/microG/gmsCore
