### ISSUE TITLE
I have trouble downloading into the YouTube Vanced app, can you help me?

### ISSUE THREAD

**Issue by Thang150898** [YTVanced/Vanced#1066]
I have trouble downloading into the YouTube Vanced app, can you help me?

_Originally posted by @CapitanArdeshir in https://github.com/YTVanced/VancedManager/issues/610#issuecomment-875913143_

**Comment by milindgoel15** [comment]
Provide details. We are not mind readers 🤦‍♂️🤦‍♂️
