### ISSUE TITLE
[YTvanced features minimalist and simple for productivity]

### ISSUE THREAD

**Issue by LMWH03** [YTVanced/Vanced#1067]
**Description**
this can be a little tricky, but a remove recommendations function would be nice and remove the explore button, or at least the trending ones.

Something like this chrome extension: 

https://chrome.google.com/webstore/detail/unhook-remove-youtube-rec/khncfooichmfjbepaaaebmommgaepoid?hl=en

**Comment by milindgoel15** [comment]
Duplicate of #334
