### ISSUE TITLE
Shorts Shelf

### ISSUE THREAD

**Issue by Russell-Ali** [YTVanced/Vanced#1070]
Shorts self still shows despite the fact I enabled  "Shorts shelf removal"  setting. I'm on v 16.20.35

**Comment by milindgoel15** [comment]
Try clearing data and start again. It should work

**Comment by Russell-Ali** [comment]
Well, doing it helps for sure but it keeps coming back and I have to redo all the settings again, I wasn't like that before, how can I get an older version, the older ones you put at Mediafire is ancient ones they don't have sponsor block.

**Comment by milindgoel15** [comment]
Use vanced manager itself. Tap on version control and choose the version you want to install.
