### ISSUE TITLE
Can't minimise the screen from landscape mode to portrait mode by swiping down,whenever I swipe down either volume or brightness gets adjusted...

### ISSUE THREAD

**Issue by rupamroopam** [YTVanced/Vanced#1071]
Can't minize the screen from landscape mode to portrait mode by swiping down,whenever I swipe down either volume or brightness gets adjusted... device Google pixel 3xl

**Comment by rupamroopam** [comment]
![Screenshot_20210710-121847](https://user-images.githubusercontent.com/86402769/125154719-09677680-e179-11eb-8200-b0bed3fbc4fd.png)

**Comment by milindgoel15** [comment]
Use latest versions before reporting any issue. You are using ancient versions and reporting old bugs from it. Update to v16.20.35 using [vanced manager](https://vancedapp.com).

**Comment by rupamroopam** [comment]
Using latest version....

**Comment by milindgoel15** [comment]
No, you are not.

**Comment by rupamroopam** [comment]
Are you serious,can't you see the screenshot...Using YouTube vanced from
past 5 years

**Comment by milindgoel15** [comment]
Your screenshot exactly says you are using old version. It doesn't even explain you are using latest version. 

Consider checking this video and confirm it yourself
https://drive.google.com/file/d/1LWL_pXmaPwBFE8_9hsVp_QxQ4fdCfB3b/view?usp=drivesdk

Also, mind showing your version number?

**Comment by rupamroopam** [comment]
![Uploading Screenshot_20210710-133216.png…]()

**Comment by rupamroopam** [comment]
![Uploading Screenshot_20210710-133216.png…]()

**Comment by milindgoel15** [comment]
Nice screenshot

**Comment by rupamroopam** [comment]
![Screenshot_20210710-134326](https://user-images.githubusercontent.com/86402769/125156771-d4612100-e184-11eb-939f-99079492b361.png)

**Comment by rupamroopam** [comment]
![Screenshot_20210710-133216](https://user-images.githubusercontent.com/86402769/125156774-de831f80-e184-11eb-9f9e-fe992cced914.png)

**Comment by milindgoel15** [comment]
Ok check my video link I uploaded above to know how to use swipe controls and youtube default gestures to minimise videos. You probably are not doing it the right way.

**Comment by rupamroopam** [comment]
Bro I knw exactly how to use it and your video shows exact method but not working for me from last update...

**Comment by milindgoel15** [comment]
Clear data and start again.

**Comment by rupamroopam** [comment]
Thanx bro,after clearing data it's working fine now....
