### ISSUE TITLE
[Bug] Video stuttering in Fullscreen

### ISSUE THREAD

**Issue by MohamadFR** [YTVanced/Vanced#1072]
**Bug description**
When i switch to landscape mode (Fullscreen) the video can't play at 60fps it's like stuttering, only happens when in landscape mode, in the normal YouTube app it plays at 60fps

**Variant**
Non-Root

**Vanced version**
V 16.20.35

**Android version**
Android 11 

**Device**
Xiaomi Mi 9

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2. Click on any 60fps video
3. switch to landscape mode

**Expected behavior**
The video plays at 60fps , the video can't play at 60fps and stuttering

_Attach images or videos or logcats in case of crashes if possible. These can be helpful in solving the issue._

**Comment by milindgoel15** [comment]
Go to vanced settings > codec override and try changing codecs and set the one which resolves the issue for you. This issue is related to how codecs are handled on your device.
