### ISSUE TITLE
[Bug] Shorts icon still appearing after remove setting

### ISSUE THREAD

**Issue by zvini77** [YTVanced/Vanced#1073]
**Bug description**
I activated the Dont show shorts icon and it still appears.

**Variant**
Non-Root

**Vanced version**
16.20.35

**Android version**
Android 11

**Device**
Samsung A30

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2. Click on my photo
3. Settings
4. Vanced Settings
5. Ad settings
6. Shorts icon remove or no

**Expected behavior**
Should remove Shorts icon

**Comment by milindgoel15** [comment]
It only removes the shelf, it doesn't remove the tab google introduced later on. 

Read #334 from now
