### ISSUE TITLE
Video thumbnails not autoplaying/previewing in feed

### ISSUE THREAD

**Issue by austingeorge1111** [YTVanced/Vanced#1074]
**Bug description**
Video thumbnails are not previewing / autoplaying in home feed even though 'muted playback in feeds' is set to always on

**Variant**
Root

**Vanced version**
16.20.35

**Android version**
Android 11 

**Device**
Redmi K20 Pro (Pixel Experience ROM)

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2. Click on general -> muted playback in feeds
3. Set to 'always on'
4. Return to home tab

**Expected behavior**
Video thumbnails should preview / autoplay when muted playback in feeds is set to always on. Works fine on non-root variant.

**Comment by milindgoel15** [comment]
You are the first guy I have seen who wants to auto Play videos on home feed lol

Try clearing data and start again.
