### ISSUE TITLE
[Bug] I am unable to tap on video controls

### ISSUE THREAD

**Issue by Weekend999** [YTVanced/Vanced#1077]
**Bug description**
Hello there. 
I am unable to click on the video settings to pause the video or to go into quality settings on YouTube videos I have experienced this problems with most of the released updates and am experiencing this issue with it again on my Google pixel 4a. I will try to tap on the video to pause it and the settings won't come up the only thing that I can do to fix this is to try and force rotate my phone to landscape mode and sometimes this will fix the issue. This issue doesn't happen while in small floating window mode just when the app is fully open.
Many thanks
Weekend

**Variant**
Non-Root

**Vanced version**
16.20.35

**Android version**
Android 11

**Device**
Google pixel 4a

**Steps to Reproduce**
I don't know what you mean but I will happily explain and show you the issue via recording if need be.

**Expected behavior**
When I click on the video I should be expecting to be able to see the pause button and other controls with ease

As you can see in the bottom right part of the video you can see where I'm clicking and how many times it takes to get it to show sometimes. https://youtu.be/8s4AkAFoZT4

**Comment by milindgoel15** [comment]
From where you downloaded vanced? Give the link and the method you used to download/install vanced

**Comment by Weekend999** [comment]
I downloaded the vanced manager off your website then used the manager to download vanced YouTube

**Comment by Weekend999** [comment]
https://vancedapp.com/

**Comment by milindgoel15** [comment]
Not sure why it's happening to you. Please try reinstalling and see if it resolves.

**Comment by Weekend999** [comment]
I have already tried this 3 times still the same issue

**Comment by milindgoel15** [comment]
Then honestly idk.

Are you somehow using any accessibility services?

**Comment by Weekend999** [comment]
Nope none

**Comment by emrednz07** [comment]
Exact same issue except in picture in picture mode here. I can't tap on the PiP window to get the audio only/pause and close options. 

**Variant**
Non-Root

**Vanced version**
16.20.35

**Android version**
Android 9

**Device**
Xiaomi Mi Note 3

**Comment by milindgoel15** [comment]
Are you still facing this issue on v16.29.39?
