### ISSUE TITLE
[Bug] Video stuttering when not in full screen

### ISSUE THREAD

**Issue by WillTheSlayer10** [YTVanced/Vanced#1078]
**Bug description**
If I am not in full screen, the video starts stuttering. This only occurs sometimes.

**Variant**
Non-Root

**Vanced version**
Vanced v16.20.35

**Android version**
Android 10 QP1A

**Device**
Xiaomi Redmi Note 8 Pro

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2. Start on any video
3. Go anywhere, as long the video isn't full screen
4. Video (sometimes) starts stuttering

**Expected behavior**
The video (obviously) shouldn't stutter.

**Comment by milindgoel15** [comment]
Happens on stock?

**Comment by WillTheSlayer10** [comment]
Sorry, but what is stock?

**Comment by milindgoel15** [comment]
> Sorry, but what is stock?

The official YouTube app

**Comment by WillTheSlayer10** [comment]
As far as I know, no.

**Comment by milindgoel15** [comment]
Check it.

**Comment by XKlarity** [comment]
There is already a issue posted for this https://github.com/YTVanced/Vanced/issues/1054
Same exact issue, the videos lag when in comments or not in full screen after some time.
