### ISSUE TITLE
[Bug] Not able to sign in to google account

### ISSUE THREAD

**Issue by IceBot227** [YTVanced/Vanced#108]
**Bug description**
When I try to sign in to the Google account the window just stuck on the "There was a problem communicating with Google servers. Try later" 

**Variant**
NonRoot: Yes
Root: No

**Android version**
Android 10

**Device**
Huawei P40 Lite E 

**Steps to Reproduce**
Steps to reproduce the error:

1. Click on "Account"
2. Click on "SIGN IN" button
3. Click on "Add account" and then "SIGN IN" option. 

_Attach images/videos if possible. These can be helpful in solving the issue._
![Screenshot_20201021_170449_com mgoogle android gms](https://user-images.githubusercontent.com/68005681/96731388-e06f3d80-13bf-11eb-9a19-b155a3a1e7f8.jpg)

**Comment by X1nto** [comment]
press the huawei button on login screen

**Comment by IceBot227** [comment]
> press the huawei button on login screen

**Comment by IceBot227** [comment]
> press the huawei button on login screen

It didn't help

**Comment by Oizaro** [comment]
> > press the huawei button on login screen
> 
> It didn't help

Unfortunately you need a new version (ready but still unreleased). So for the moment you can't solve the problem.

**Comment by IceBot227** [comment]
> > > press the huawei button on login screen
> > 
> > 
> > It didn't help
> 
> Unfortunately you need a new version (ready but still unreleased). So for the moment you can't solve the problem.

Okay, thanks

**Comment by Oizaro** [comment]
@IceBot227 https://mega.nz/file/4JNHkIaI#aunrAOqVRVGGfybhAA_ySlRZNMVdFI8rS5obLOsfnu0

Use this meanwhile.

**Comment by IceBot227** [comment]
> @IceBot227 https://mega.nz/file/4JNHkIaI#aunrAOqVRVGGfybhAA_ySlRZNMVdFI8rS5obLOsfnu0
> 
> Use this meanwhile. Its our "ready to release" apk.

Thanks, it's working!!

**Comment by Oizaro** [comment]
> Thanks, it's working!!

Well...has been officially released now xD.

**Comment by Oizaro** [comment]
@X1nto You can close this report.

**Comment by IceBot227** [comment]
Thank you
