### ISSUE TITLE
[Bug] Vanced Guide can't be updated

### ISSUE THREAD

**Issue by Harmonie666** [YTVanced/Vanced#1081]
There seems to be a new version of Vanced Guide available, but for some reason it won't update, and shows an error message.
Never experienced this with any playstore app before.
![Screenshot_20210712-100309088.png](https://user-images.githubusercontent.com/73917917/125252419-a43a8f00-e2f8-11eb-8dac-de859df385f5.png)![Screenshot_20210712-100435064 (1).png](https://user-images.githubusercontent.com/73917917/125252434-a866ac80-e2f8-11eb-9f12-2c9be712cede.png)

**Comment by KevinX8** [comment]
The app was suspended due to having a link to the vanced website inside the about page, not much we can do other than appeal it and remove the link

**Comment by Harmonie666** [comment]
Gotchu. Thanks for clarification.
