### ISSUE TITLE
[Idea] Adding "Allow Ads on this Channel" to supporting channel by watching ads.

### ISSUE THREAD

**Issue by hafizdkren** [YTVanced/Vanced#1083]
**Description**
The idea of this button is same thing as blocking ads on site like uBlock did, but also making whitelist to several video (link) channel by adding additional ext on browser called "YouTube Ads Whitelist"

The reason of this idea pop-up is as royal viewers on several channel, I wanna helping the channel by contributing some minute or two to helping the channel by allowing the ads play on those whitelisted channel. With that way, people who wanna support their favorite channel able to contributing even if they doesn't had dollar or more on third-party income stream source (such BMAC, Patreon, Ko-fi, etc.)

We can implementing by had two way, this can be tested with A/B tester by allowing people who had GitHub account, Google account, or other kind test participant account to not only share their perspective about this idea/feature, but also some feedback to improving it.

The first one is by playing it foreground, as we already knew this was easy one.
The second one is bit complicated (and I not hoping that this one would be on this semester implementation) where the ads is played in background while another player also playing the main content in foreground.

The second one can be implement by rolling the player without any video and audio being played, while the player still rolling so YouTube is thinking it's being played.

This was a complicated concept and idea, but I not hoping to be implement sooner or if this trick already being done long time ago, I'll let dev team to closing this case ASAP.

Hope everyone in dev still healthy and freed from COVID-19, and hope that this pandemic would finish sooner.

Sincerely.

Hilman Hazazi

**Comment by milindgoel15** [comment]
Vanced has no intentions to break the sole point/purpose of YouTube vanced.
