### ISSUE TITLE
[Bug] internet bug.

### ISSUE THREAD

**Issue by XxMCBxX** [YTVanced/Vanced#1084]
**Bug description**
It seas that i need to connect to wifi but when i try it on the normal yt it works.

**Variant**
Non-Root

**Vanced version**
v16.20.35

**Android version**
Android version 11

**Device**
Samsung Galaxy A71

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app

**Expected behavior**
I expected the app to open and watch some memes but instead i got the message to connect to wifi.

_
![Screenshot_20210713-211318](https://user-images.githubusercontent.com/87391230/125511606-f6b89c86-a8f6-4a9d-a598-0ac19b2514e8.jpg)
_

**Comment by Aayushpatil77** [comment]
This happened on my phone to 

**Variant**
Non-root

**Vanced version** 
Latest

**Android version** 
Android 11

**Device** 
Realme 7

**Comment by milindgoel15** [comment]
Duplicate of #786
