### ISSUE TITLE
[Bug] cant add a google account.

### ISSUE THREAD

**Issue by XxMCBxX** [YTVanced/Vanced#1085]
**Bug description**
Cant add a account to mcroG

**Variant**
Non-Root

**Vanced version**
v16.20.35

**Android version**
Android 11 

**Device**
 Samsung Galaxy A71

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2. Click on 'sign in'

**Expected behavior**
I expected to open microG and add my account and watch some memes without adds xd.

_![Screenshot_20210714-154538_Vanced microG.jpg](https://user-images.githubusercontent.com/87391230/125633551-27d91590-b35e-4c0d-a85c-22fa3095e527.jpg)_

**Comment by milindgoel15** [comment]
Refer this solution from [this link](https://telegra.ph/Troubleshooting-for-vanced-03-19#C:-Trouble-connecting-with-Google-servers)
