### ISSUE TITLE
[Bug] Phone rebooting

### ISSUE THREAD

**Issue by Gotoro** [YTVanced/Vanced#109]
**Bug description**
The Vanced Manager pushed a notification saying that microG can be updated. And so I did. 
Currently, it sits at the latest version 0.2.13.203915. After a few seconds, phone just rebooted. And started doing so without stopping. After a few reboots, I shut down my phone completely and hopped into Discord to see whether I could find the solution. 
Searching "phone shutting", I saw how a user RealGaming#9190 mentioned, quote

`Is it a possibility that your app is causing the Galaxy Note 9 phone to randomly shut off completely. Because I'm running into that problem all day today after I updated this youtube app`

`I deleted the app, and as at the moment for the past hour the phone stopped doing that.`
I decided to follow this and quickly uninstalled the app. This seemed to help.

I tried reinstalling the Vanced app, but it again started to reboot.
I do not remember with what microG it was working as intended, but I think it was something like 0.2.11.x

**Variant**
NonRoot: Yes
Root: No

**Android version**
Android 8.0 - Oreo

**Device**
Lenovo S5 (K520)

**Steps to Reproduce**
Steps to reproduce the error:
1. Update microG to the latest version
2. Install Vanced

**Expected behavior**
Phone not rebooting.

**Comment by X1nto** [comment]
Send a logcat so we can see what's causing problem. also this is an issue with microg, not vanced, so next time consider opening microg-related issues on https://github.com/YTVanced/VancedMicroG

**Comment by Oizaro** [comment]
@Gotoro Try this

https://mega.nz/file/0REi1RoT#4huEVKFaYYrhhoazytk4OI4-XgkaTQKtiQAexwZu8X0

**Comment by toonyrafael** [comment]
Hi, My android is also restarting after installing the latest version of vanced.

**Comment by gghhkm** [comment]
Fixed now
