### ISSUE TITLE
[Idea] Option to completely disable all subtitles

### ISSUE THREAD

**Issue by 1RandomDev** [YTVanced/Vanced#1091]
I've disabled all subtitles in the settings, but they're still shown in some videos regardless how often I turn them of in the videoplayer. (They're mostly in english videos, when my system language is set to German.) I'd really like a setting to block all subtitles in the complete app.

**Comment by Ivonov1** [comment]
Go to your system settings and also disable it there.this usually stops the issue.

**Comment by 1RandomDev** [comment]
When I go to subtitles in the yt settings it redirecty me to the system settings where everything is turned off

**Comment by Ivonov1** [comment]
Does it happen in your normal YouTube app?

**Comment by 1RandomDev** [comment]
Yes also in the original app. But on both of my Samsung Galaxy Tab A SM-T580 the exact same problem.

**Comment by Ivonov1** [comment]
It's a device specific youtube bug that YTvanced devs can't fix.you could try reporting the problem to YouTube themselves.

**Comment by milindgoel15** [comment]
#1358
