### ISSUE TITLE
[Idea] Privacy - Only send account data to YouTube when absolutely necessary.

### ISSUE THREAD

**Issue by Xd-pro** [YTVanced/Vanced#1093]
When you request a video and it's metadata, do not send account information to YouTube. When requesting channel info, do the same. In whatever other scenarios that function correctly when signed out, such as viewing trending, act as if YouTube is signed out.

**Comment by milindgoel15** [comment]
Vanced is modified package based on top of YouTube app. Vanced is not going to modify the internal structure because we don't have the code available. 

If you care about your privacy, use incognito mode or some youtube clients.
