### ISSUE TITLE
[Bug] Youtube Vanced will not launch with only microG

### ISSUE THREAD

**Issue by MyBlackMIDIScore** [YTVanced/Vanced#1095]
**Bug description**
I installed Youtube Vanced on a newly flashed device. On the device I did not install Google Play services and only have microG installed. I read that Vanced works with microG, but when I launch the app it shows me this error (see image) and then exits the app.

**Variant**
Root

**Vanced version**
v16.20.35

**Android version**
Android 11 

**Device**
Xiaomi Mi 9T (davinci)

**Steps to Reproduce**
1. Open the app
2. See the error
3. Click OK

**Expected behavior**
The app launches normally.

**Screenshot**
![Screenshot_20210719-164937720](https://user-images.githubusercontent.com/31241793/126170372-f4506289-53c0-4ae2-ade9-d4692b1fedca.jpg)

**Comment by milindgoel15** [comment]
The dialog explains it all. There's no solution to that other than installing google services.

**Comment by KevinX8** [comment]
Make sure microg passes all self checks, the root version will not work with microg otherwise, you can also just use the non root version
