### ISSUE TITLE
[Bug] Getting tons of notifications and I can't close them

### ISSUE THREAD

**Issue by tabtomi8** [YTVanced/Vanced#1096]
**Bug description**
YouTube Vanced sends out tons (600) of notifications every day, I can't close them because they reappear. 

**Variant**
Non-Root

**Vanced version**
v16.20.35

**Android version**
10 QP1A.190711.020

**Device**
Xiaomi Redmi Note 8 Pro 

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
(that's it) 

**Expected behavior**
It shouldn't send out 600 notifications, I should only get 30 notifications.

_Attach images or videos or logcats in case of crashes if possible. These can be helpful in solving the issue._
![IMG_20210720_112604](https://user-images.githubusercontent.com/59199402/126301687-05810083-f4ce-471e-ab18-67121620321b.jpg)

**Comment by milindgoel15** [comment]
Downgrade back to older build of vanced microG or turn all vanced Notifications off
