### ISSUE TITLE
[Idea] YouTube Vanced Android TV version

### ISSUE THREAD

**Issue by Weafyr** [YTVanced/Vanced#11]
YouTube forced me to install Vanced app on my phone, cause they started to be so greedy with the ads. Now they are even more greedy on my TV.
I tried to install Vanced app on my android TV but the phone UI is unusable with remote controller.
Would it be possible to mod the Android TV YouTube app?

**Comment by Eggroley** [comment]
Yes, SmartYoutubeTV is a modded version of YoutubeTV that removes ads. It is missing some features that Vanced has though.

**Comment by X1nto** [comment]
As mentioned by @Eggroley, SmartYoutubeTV is vanced for TVs. Better to use that

**Comment by Weafyr** [comment]
Thanks, I'll give it try.
