### ISSUE TITLE
[Bug] replaceme

### ISSUE THREAD

**Issue by Klefo0** [YTVanced/Vanced#1103]
**Bug description**
When download videos offline storage, yt vanced said device need to free up space although device had a lot of space

**Variant**
Non-Root

**Vanced version**
V16.20.35

**Android version**
Android 7.1.1

**Device**
Oppo A83

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2. Click on three dot on the right side 
3. Choose "Download video”
4. Click "Library"
5. Click "Downloads"

**Expected behavior**
Replace me with a description of what you expected should happen and what happened instead.

_Attach images or videos or logcats in case of crashes if possible. These can be helpful in solving the issue._

![Screenshot_2021-07-23-10-36-23-20.png](https://user-images.githubusercontent.com/70630854/126734763-9414cebb-2400-49c0-a092-bb3c08f3ef9b.png)![Screenshot_2021-07-23-10-36-28-20.png](https://user-images.githubusercontent.com/70630854/126734773-69606dab-4ef1-4c8f-bff5-41fb4e21b892.png)

**Comment by milindgoel15** [comment]
If it says free up your storage, then do it. Vanced has nothing to do with download feature. It comes from Google.

**Comment by Klefo0** [comment]
the storage have enough to store those file

**Comment by milindgoel15** [comment]
Tell that to Google lol
