### ISSUE TITLE
[Idea] Loop single video in Playlist?

### ISSUE THREAD

**Issue by Yusei-StarDust** [YTVanced/Vanced#1105]
**Description**
Even though enable auto repeat button and disable auto repeat in Vanced settings>misc, it seems to be still unable to loop single video in playlists.

**Comment by milindgoel15** [comment]
It's won't work. Looping single video in a playlist defeats the purpose of a playlist. If you want to loop a video, play it outside of the playlist then loop it.

**Comment by Ivonov1** [comment]
I think it's a good idea.Your opinion is valid for the automatic auto repeat.
But,those who use the repeat button for music in the youtube it's a genuine feature.I believe it or not people have rather large music playlists like me.
We we would be pleased if the repeat button worked for playlists.
