### ISSUE TITLE
[Bug] Notifications are bugged

### ISSUE THREAD

**Issue by DLockholm** [YTVanced/Vanced#1107]
**Bug description**
I just woke up and I had a bunch of vanced notifications from new videos and stuff, I dismiss the notifications (I just cleared them) and everything right until I noticed that the same notifications reappeared, and I cleared them, and they reappeared  and I cleared them and so on and on. Another fact here is that the text of the notifications seems displaced, out of position, and my task bar glitches for a second every time the notifications reappear because yes, even when I don't do nothing the notifications delete themselves and reappear again. I didn't have this issue yesterday nor any issue whatsoever.
I tried force stopping the app and didn't work, I tried rebooting my device and didn't work, I also tried to reinstall vanced from the manager and didn't work as well
![Screenshot_20210724_093930_com vanced android youtube](https://user-images.githubusercontent.com/87905421/126872405-70dc5eeb-dd8d-4654-b853-918a13fa20a3.jpg)

**Variant**
Non-Root

**Vanced version**
16.20.35

**Android version**
Android 10 , with EMUI  10.0.0

**Device**
Huawei Y9 Prime

**Steps to Reproduce**
I don't know how, I woke up and the notifications are bugged no matter if I force the app to stop or even rebooting the device, reinstalling also doesn't work

**Expected behavior**
Dismiss the notifications

**Comment by milindgoel15** [comment]
Roll back vanced microG to an older version or turn off all notifications for vanced app

**Comment by DaniSheng** [comment]
Same problem, deactivating push notifications not working, looping push notifications, same notifications cleared early.

**Comment by J0ddy** [comment]
I have the same issue

**Comment by jacobh12349** [comment]
oh sorry, i tried to make sure that nobody reported this yet but i didnt see any because i was only searching open issues.

**Comment by jacobh12349** [comment]
> **Roll back vanced microG to an older version or turn off all notifications for vanced app** as it's an issue with microG. Ask microG developers for fix
> 
> For older versions of vanced microG, use [this link](https://github.com/YTVanced/VancedMicroG/releases).

what lower version of microG do I use?

**Comment by milindgoel15** [comment]
> which older version of microG do I use?

Roll back to 0.2.20

**Comment by jacobh12349** [comment]
> > which older version of microG do I use?
> 
> Roll back to 0.2.20

ok thx

**Comment by jacobh12349** [comment]
You should reopen this so it's easier for people to find by searching, because it searches open issues by default.

**Comment by jacobh12349** [comment]
> Roll back to 0.2.20

I'm not getting any yt notifications now after switching to 0.2.20. I can just see the notifications in the app.

**Comment by milindgoel15** [comment]
> I'm not getting any yt notifications now after switching to 0.2.20. I can just see the notifications in the app.

Follow this: https://telegra.ph/Troubleshooting-for-vanced-03-19#Notification-fix

**Comment by jacobh12349** [comment]
> Follow this: https://telegra.ph/Troubleshooting-for-vanced-03-19#Notification-fix

Wait, I have to wait a week for it to show notifications now? They aren't showing yet after doing that yesterday.

**Comment by milindgoel15** [comment]
Use root version if notification fail to work. Or otherwise try fresh install

**Comment by jacobh12349** [comment]
> Use root version if notification fail to work. Or otherwise try fresh install

I can't root my phone. I'm under a phone plan.

**Comment by jacobh12349** [comment]
> > Use root version if notification fail to work. Or otherwise try fresh install
> 
> I can't root my phone. I'm under a phone plan. I can try to reinstall youtube though.

Ok, I uninstalled and reinstalled the youtube app on the vanced manager, now i just have to wait until i get a notification on youtube to see if the phone notifications work now.

**Comment by jacobh12349** [comment]
> > > Use root version if notification fail to work. Or otherwise try fresh install
> > 
> > 
> > I can't root my phone. I'm under a phone plan. I can try to reinstall youtube though.
> 
> Ok, I uninstalled and reinstalled the youtube app on the vanced manager, now i just have to wait until i get a notification on youtube to see if the phone notifications work now.

Ok, the phone notifications work now, i just got one. thx for the help.

**Comment by SaberAkiyama** [comment]
I don't think it's a root version rather than non-root version. Even if without root, they aren't fix at all. Period.

**Comment by milindgoel15** [comment]
> I don't think it's a root version rather than non-root version. Even if without root, they aren't fix at all. Period.

The issue comes from microG end, not vanced. Ask microG devs for fix. We can only provide you temporary fix. If you can't follow such directions and resort to complain about bugs, it's your decision.

**Comment by jacobh12349** [comment]
I know this isn't being developed anymore, but I just wanted to give an update on this problem. This started happening again, even on 0.2.20 microG, so I just ended up disabling youtube vanced's notifications, and am just using the default youtube app for notifications and using vanced for everything else now.
