### ISSUE TITLE
[Idea] Download videos without premium

### ISSUE THREAD

**Issue by MKCOOL142** [YTVanced/Vanced#111]
Idk if this is possible to do since this might be server-sided but when using a german vpn you should be able to download most youtube videos by Publicly funded channels even without youtube Premium, idk if you can apply this to all youtube videos but it'd be great if it works
![Screenshot_20201022_123204_com vanced android youtube](https://user-images.githubusercontent.com/40364718/96860917-ab1c2b80-1463-11eb-9054-4b925c339490.jpg)
![Screenshot_20201022_123201_com vanced android youtube](https://user-images.githubusercontent.com/40364718/96860927-ae171c00-1463-11eb-8be7-61d10913309c.jpg)

**Comment by gghhkm** [comment]
This will never be implemented, no matter how many times you ask.

**Comment by MKCOOL142** [comment]
> This will never be implemented, no matter how many times you ask.

I never asked this and just wanted to help improve the app tbh

**Comment by gghhkm** [comment]
> > This will never be implemented, no matter how many times you ask.
> 
> I never asked this and just wanted to help improve the app tbh

Google would just shut down Vanced.

**Comment by simplyTOBBI** [comment]
You can download many videos in Germany because we pay taxes and the government decided to create Funk. Funk should be popular for kids and teens and because we pay for it you can download YouTube videos.
Sorry for the bad explanation...
