### ISSUE TITLE
Why only 2× playback speed

### ISSUE THREAD

**Issue by Isssuemaker** [YTVanced/Vanced#1110]
Why Vanced has only 2× YouTube speed I have opened a issue for increasing it to 4× but it is closed by saying that duplicate of #82 the #82 issue is already closed by a bot but many peoples have requested for increasing maximum playback speed please give me reason why you are not increasing the playback speed

**Comment by milindgoel15** [comment]
Stop spamming all these issues 🤦‍♂️. Go ask Google to add more playback speed for you if you need it so badly.

**Comment by Isssuemaker** [comment]
> Stop spamming all these issues 🤦‍♂️. Go ask Google to add more playback speed for you if you need it so badly.

VlC already have these feature and Newpipe also have this feature

**Comment by Isssuemaker** [comment]
> Stop spamming all these issues 🤦‍♂️. Go ask Google to add more playback speed for you if you need it so badly.

You are so much rude

**Comment by milindgoel15** [comment]
> VlC already have these feature and Newpipe also have this feature

How do you expect us to add a feature when we don't have the source code in the first place? We aren't Google and we do NOT own YouTube in any way.

Vanced puts its patches on top of YouTube app, which doesn't mean vanced is able to do anything. Newpipe and VLC are whole different apps using their own piece of code...

If you and all other users like to have this feature, then learn to be patient instead of begging developers and spamming whole vanced repo for it. It's a free app and no one made you pay to use it. Moreover, developers have their personal life as well. They are humans not robots.


> You are so much rude

Oh, so what you are doing is not rude?

**Comment by gghhkm** [comment]
> You are so much rude
Yes, Yes you are.

**Comment by Isssuemaker** [comment]
> > VlC already have these feature and Newpipe also have this feature
> 
> How do you expect us to add a feature when we don't have the source code in the first place? We aren't Google and **we do NOT own YouTube in any way.**
> 
> Vanced puts its patches on top of YouTube app, which doesn't mean vanced is able to do anything. _Newpipe and VLC are whole different apps using **their own piece of code...**_
> 
> If you and all other users like to have this feature, then learn to be patient instead of begging developers and spamming whole vanced repo for it. It's a free app and no one made you pay to use it. Moreover, developers have their personal life as well. They are humans not robots.
> 
> > You are so much rude
> 
> Oh, so what you are doing is not rude?

Vanced has playback speed feature before the original YouTube has this feature so how vanced has add this feature before YouTube

**Comment by milindgoel15** [comment]
Playback speed is from YouTube, not vanced. Vanced has preferred speed option which lets you choose the default speed you want to play your videos in.

**Comment by Isssuemaker** [comment]
> Stop spamming all these issues 🤦‍♂️. Go ask Google to add more playback speed for you if you need it so badly.

I am going to request Google for increasing playback speed

**Comment by Isssuemaker** [comment]
> > VlC already have these feature and Newpipe also have this feature
> 
> How do you expect us to add a feature when we don't have the source code in the first place? We aren't Google and **we do NOT own YouTube in any way.**
> 
> Vanced puts its patches on top of YouTube app, which doesn't mean vanced is able to do anything. _Newpipe and VLC are whole different apps using **their own piece of code...**_
> 
> If you and all other users like to have this feature, then learn to be patient instead of begging developers and spamming whole vanced repo for it. It's a free app and no one made you pay to use it. Moreover, developers have their personal life as well. They are humans not robots.
> 
> > You are so much rude
> 
> Oh, so what you are doing is not rude?

Please don't be offended I am not spamming I make new issues because my issue is closed by saying duplicate and anyone don't give me a good reason now I will not open any issues in vanced
