### ISSUE TITLE
[Bug] Auto start playing videos after paused stream ends.

### ISSUE THREAD

**Issue by ThisIsBrutus** [YTVanced/Vanced#1112]
**Bug description**
If you are watching a live stream and pause it, after the stream ends it will automatically start playing a video in the queue after the stream. (can be several hours later, and quite the surprise)

**Variant**
Non-Root/Root

**Vanced version**
Latest version

**Android version**
Replace me with the version of Android your device have. For example, Android 11 

**Device**
Replace with the name of the device on which you faced the bug. For example, Samsung Galaxy S8

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
3. ....

**Expected behavior**
Replace me with a description of what you expected should happen and what happened instead.

_Attach images or videos or logcats in case of crashes if possible. These can be helpful in solving the issue._

**Comment by milindgoel15** [comment]
How is that a bug? It's an intended behaviour from YouTube. If you don't want to play next videos automatically, disable auto play.

**Comment by ThisIsBrutus** [comment]
> d

Really? The stream is _paused_ and not running, it shouldn't be autoplaying anything.

**Comment by milindgoel15** [comment]
Have you checked official YouTube app before creating this issue? Does it not happen there?
