### ISSUE TITLE
[Bug] 4k videos limited to 480p 

### ISSUE THREAD

**Issue by MaaX46** [YTVanced/Vanced#1114]
**Bug description**
4k videos are being limited to 480p and it's not possible to pass this quality. Even if you put it in the 2160p video option, the 2160p option when opening the video does not appear 

**Variant**
Non-Root

**Vanced version**
16.20.35

**Android version**
Android 11 

**Device**
Samsung Galaxy A71 SM-A715F

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2. Search for video in 4k 
3. play video 
4. Go to option to change quality 

**Expected behavior**
The 2160p60 option should appear instead of 480p  [2160p quality does not appear ](https://youtu.be/zThttLhO67A)

**Comment by milindgoel15** [comment]
![Screenshot_20210727-114810765.jpg](https://user-images.githubusercontent.com/45682747/127105289-7a6dfec5-aed2-4f21-b094-2a2ee67cddec.jpg)

My device which doesn't even support 4k show it fine everytime for every 4k video. Can say it's an issue on your end. Check reinstalling then play with codecs if it helps. Other than that, enable max resolution then force restart the app.

**Comment by MaaX46** [comment]
> ![Screenshot_20210727-114810765.jpg](https://user-images.githubusercontent.com/45682747/127105289-7a6dfec5-aed2-4f21-b094-2a2ee67cddec.jpg)
> 
> Meu dispositivo, que nem mesmo suporta 4k, mostra-se bem todas as vezes para cada vídeo de 4k. Posso dizer que é um problema do seu lado. Verifique a reinstalação e brinque com os codecs se ajudar. Fora isso, habilite a resolução máxima e force a reinicialização do aplicativo.

I've already tested the codecs and still the maximum that appears in 4k videos, I tried to reinstall and the option still doesn't appear
of the resolution 2160p60

**Comment by milindgoel15** [comment]
Nothing we can do
