### ISSUE TITLE
[Idea] Bringing back muted feed unmute button

### ISSUE THREAD

**Issue by Ivonov1** [YTVanced/Vanced#1116]
**Description**
Once upon a time in a certain YouTube version there was a caption and unmute button on YouTube main feed videos at the top right corner.It annoyed some people thus youtube removed it gracefully.So,I respectfully request the vanced team to add a setting in the misc section to turn on the caption and unmute button and also a always play audio on main feed setting.

**Comment by milindgoel15** [comment]
Which version was it?

**Comment by Ivonov1** [comment]
I can't really find out the version as there is no documentation anywhere where I have researched so I think it was a beta/experimental version but I am not a beta tester which means it's a experimental south east asia variant
