### ISSUE TITLE
[Bug] Random glitch with controls stuck on screen.

### ISSUE THREAD

**Issue by supernoodled** [YTVanced/Vanced#1117]
**Bug description**
This happens randomly, I don't know what causes it. My player settings are:

repeat button enabled, sponsorblock enabled, picture in picture enabled, cast button disabled, video watermark disabled. Seek is set at 5 seconds on tap of left or right, tap on video bar is disabled.

**Variant**
Non-Root

**Vanced version**
v16.20.35 (White/Black)
(Vanced microG - 0.2.21.212417

**Android version**
Android 10

**Device**
Samsung Galaxy S9 (Exynos)

**Steps to Reproduce**
Steps to reproduce the error:
1. I don't know how to reproduce.
2. It's completely random AFAIK.
3. But definitely a bug.
4. Back, forward and pause buttons stuck on screen.

**Expected behavior**
Back forward and pause buttons (controls) disappear from player after a second like normal.

_Attach images or videos or logcats in case of crashes if possible. These can be helpful in solving the issue._

**Comment by supernoodled** [comment]
![20210727_204220](https://user-images.githubusercontent.com/31737227/127217564-46038fa3-5941-484f-85d4-eed5823fccea.jpg)
Here's an image with the controls on screen. 

Once the bug is triggered, these will be frozen no matter what you do and you will be forced to restart the entire app

**Comment by milindgoel15** [comment]
Try reinstalling as well
