### ISSUE TITLE
[Bug] Saving to playlist will not pop up a playlist screen, instead it will auto save to most recent

### ISSUE THREAD

**Issue by supernoodled** [YTVanced/Vanced#1118]
**Bug description**
Videos saving to most recent playlist (you have saved to) rather than asking you what playlist to save to.

**Variant**
Non-Root

**Vanced version**
v16.20.35 (White/Black)
(Vanced microG - 0.2.21.212417

**Android version**
Android 10

**Device**
Samsung Galaxy S9 (Exynos)

**Steps to Reproduce**
Steps to reproduce the error:
1. Try to save a video to a playlist.
2. If you've never done this before, it should save to "Watch Later".
3. If you have done this before, say set a video to a music playlist, it will save the video to said playlist instead of what you want.

**Expected behavior**
Popup asking what playlist to save to.

_Attach images or videos or logcats in case of crashes if possible. These can be helpful in solving the issue._

**Comment by milindgoel15** [comment]
Works fine here, try reinstalling from scratch.
