### ISSUE TITLE
[Bug] annoying YT premium pop up on startup.

### ISSUE THREAD

**Issue by supernoodled** [YTVanced/Vanced#1120]
**Bug description**
This happens randomly on app start.
a YT premium advertisment will cover the entire screen, in full white mode, blinding you.
You can click X in the top right to ignore this, but it's extremely annoying.

**Variant**
Non-Root

**Vanced version**
v16.20.35 (White/Black)
(Vanced microG - 0.2.21.212417

**Android version**
Android 10

**Device**
Samsung Galaxy S9 (Exynos)

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app.
2. Once in a while, your eyes will go blind from an entirely white YT premium advertisement popup that covers the entire screen, even in full black mode.

**Expected behavior**
No YT premium advertisment. I use Vanced to avoid ads, so what is the actual point of getting premium? It doesn't support the content creators anyway.

_Attach images or videos or logcats in case of crashes if possible. These can be helpful in solving the issue._

**Comment by supernoodled** [comment]
Here's a screenshot I have saved. It's blinding so beware.

![Screenshot_20210606-174034](https://user-images.githubusercontent.com/31737227/127219686-77a18e6e-3e8c-460f-acbe-ad65060e975e.jpg)

**Comment by milindgoel15** [comment]
Vanced ≠ YT premium

**Comment by leodoi3** [comment]
> 
> 
> Vanced ≠ YT premium

Vance blocks ads, that is an ad.
