### ISSUE TITLE
[Question] Fullscreen Toggle Button Hit Box

### ISSUE THREAD

**Issue by aoxhwjfoavdlhsvfpzha** [YTVanced/Vanced#1122]
When I tap on fullscreen button on vanced, often times it is misregistered and the video jumps to the end, I have to tap quite high, slightly above the top of the fullscreen button to get it to properly label. Does anyone else have issues with this, or is it just me?

**Comment by veikkop** [comment]
Yes. Change this to Bug

**Comment by milindgoel15** [comment]
Not bug because it's not vanced problem. Try asking Google because they own YouTube.
