### ISSUE TITLE
[Bug] Video page loading problem

### ISSUE THREAD

**Issue by GKid94** [YTVanced/Vanced#1125]
**Bug description**
Video often get's stuck on loading

**Variant**
Non-Root

**Vanced version**
In the image

**Android version**
In the image

**Device**
Xiaomi Redmi 9

**Steps to Reproduce**
Open YouTube Vanced and open a couple of videos

**Expected behavior**
For the video to be loaded immediately

![Screenshot_2021-07-30-10-05-37-294_com vanced android youtube](https://user-images.githubusercontent.com/18757054/127623758-55ce6bb9-1153-4686-9648-90225d637fe8.jpg)
![Screenshot_2021-07-30-10-05-51-540_com vanced manager](https://user-images.githubusercontent.com/18757054/127623780-a1bc2739-e5a4-4d93-b43b-deb3edaddb02.jpg)
![Screenshot_2021-07-16-20-31-42-085_com android settings](https://user-images.githubusercontent.com/18757054/127623813-dcfc74de-9c6a-4c09-866a-680e8756bd7c.jpg)
![Screenshot_2021-07-16-20-31-45-428_com android settings](https://user-images.githubusercontent.com/18757054/127623817-7171d601-3072-4b74-a923-96b6cd5c1758.jpg)

**Comment by milindgoel15** [comment]
It's your network issue, not vanced.

**Comment by GKid94** [comment]
@milindgoel15 My internet is fine, other apps also work fine I only have problems with this app

![Screenshot_2021-07-30-14-47-04-923_org zwanoo android speedtest](https://user-images.githubusercontent.com/18757054/127655259-5a7df5da-8271-4737-a563-d5e390619105.jpg)

**Comment by milindgoel15** [comment]
![Screenshot_20210730-182125600.jpg](https://user-images.githubusercontent.com/45682747/127655550-fb3c174a-dcff-416a-a493-89a6cfc41818.jpg)

Issue on ur end. Try reinstalling from scratch

**Comment by GKid94** [comment]
@milindgoel15 Weird, I installed the app a couple of weeks ago when I bought the new phone
