### ISSUE TITLE
[Bug] Video preview is gone when casting a second video.

### ISSUE THREAD

**Issue by Harmonie666** [YTVanced/Vanced#1126]
Every time when I cast from Vanced with TV Code to my TV (SmartTubeNext) usually the Video preview (which is very important and very practical in knowing at which part of the video you're currently in) -disappears with the second video that I cast to the TV. 
In the first video that I cast, video previews from progress bar are visible:
https://user-images.githubusercontent.com/73917917/127684758-52647f87-e1d6-47d9-9c86-842a3ee73976.mp4
I cast a second video and video previews are gone:
https://user-images.githubusercontent.com/73917917/127684778-5c22dd00-266b-445d-a2a1-1d3fa5ab9692.mp4

In order to get video preview back, I have to disconnect from cast, and reconnect.
This is very tiresome and I'm wondering if you would be able to fix this behavior? 

![Screenshot_20210730-184340348 (1).png](https://user-images.githubusercontent.com/73917917/127685225-d08ffdf5-0461-4883-a0dc-9dbfdec8803f.png)

**Variant**
Non-Root

**Vanced version**
v16.20.35

**Android version**
Android 10

**Device**
ROG Phone 2

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app and cast with TV code 
2. Open any video and you will see video preview when holding progress bar and moving
3. Open a second video and you won't have video preview anymore.

I checked stock YT app now, it doesn't happen when I cast from stock YT. Video preview always shows, no matter how many videos you open.
So this must be a Vanced issue :(

**Comment by milindgoel15** [comment]
Have you checked official YouTube? Does it happen there?

**Comment by Harmonie666** [comment]
> Have you checked official YouTube? Does it happen there?

I checked stock YT app now, it doesn't happen when I cast from stock YT. Video preview always shows, no matter how many videos you open. 
So this must be a Vanced issue :(

**Comment by milindgoel15** [comment]
Are u using tap to seek feature? If yes, disable that and try again.

**Comment by Harmonie666** [comment]
> Are u using tap to seek feature? If yes, disable that and try again.

Disabled Tap to seek, and tested it again. Same behavior. 

(Actually even if it worked without Tap to seek, I couldn't deal not being able to use Tap to seek while casting.)

**Comment by milindgoel15** [comment]
I only asked for the behaviour of it on disabling tap to seek, **nothing MORE**, nothing less.

**Comment by Harmonie666** [comment]
Were you able to reproduce the error? Tell me if you need any assistance or further information.

**Comment by Harmonie666** [comment]
@milindgoel15 
Could you locate the error in the meantime? Is it possible to fix? Please don't leave me in the dark with this issue.

**Comment by milindgoel15** [comment]
LEARN TO BE PATIENT. FYI, I am not a developer but a community moderator. Moreover, the dev is busy with his personal life and there's been nothing new even on beta groups as well. SO please wait and watch out for future updates on changelog channels and notifications...

**Comment by Harmonie666** [comment]
Me asking a month later is not patient? I purposefully waited this long. At least you could've keep me posted about the current situation. I'm trying to develope a calm and respectful dialogue with you.

**Comment by milindgoel15** [comment]
You should know developers and all the team members are humans and we have a lot of important stuff to do than to be online 24*7 on vanced forums and keep reminding you all that we are busy with our life and bla bla bla. 

**REMEMBER, we are volunteers, not some workers on the job.** We are not getting paid by doing any stuff nor are we asking you to pay us to use our app. It's a free and personal app maintained by xfilefin(dev). If you like vanced, use it without demanding or giving orders or spamming again and again in forums to the whole team to fix stuff for you. 

The bugs will get fixed sooner or later. ### Just stop forcing developers for it.

If you want some special attention, use official YT! As we don't do that here.

**Comment by Harmonie666** [comment]
/bump 

still unfixed

**Comment by milindgoel15** [comment]
Fixed with next vanced release(ik we didn't release it yet but it will be released once everything gets settled. We have reached alpha phase so most likely, it will take a month max). 

I'm closing this issue now. Please don't ask when it will come. :)

**Comment by Harmonie666** [comment]
Thanks for updating me on the issue. I appreciate it :) 

I assume you tested it with a beta tester whose also paying for YT premium? In order to reproduce this issue? 
Anyway I'm looking forward to the next Vanced update where it'll be fixed :)
