### ISSUE TITLE
[Bug] The device lags significantly when using PiP-Mode.

### ISSUE THREAD

**Issue by WilcyWilson** [YTVanced/Vanced#1128]
**Bug description**
The device lags significantly when using PiP-Mode. I think what's happening is vanced should ignore preferred resolution settings when being used in PiP-Mode as it would be useless and performance draining to run anything higher than 360p in the small PiP-Window. But it doesn't. And when there is a 480p or higher resolution video which has to be downscaled to  360p while in PIP mode then the device lags significantly because it fails to downscale the video.

**Variant**
Non-Root and Root (Both Variants)

**Vanced version**
v16.20.35

**Android version**
Android 11

**Device**
Redmi Note 10 (sunny)

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2. Click on your profile picture
3. Go to Settings
4. Go to Vanced Settings
5. Go to Video Settings
6. Change Preferred video quality Wifi to 1080p or higher than 360p
7. Go back and play any video.
8. Go to Pip-mode by going to home. 
9. Now, the device lags significantly.

**Expected behavior**
Device should work smoothly during background play(PiP mode)

**Logcat**
[logcat_07-31-2021_10-08-33.txt](https://github.com/YTVanced/Vanced/files/6911200/logcat_07-31-2021_10-08-33.txt)

https://user-images.githubusercontent.com/40534141/127740874-2a6ac3a0-b20c-447c-9ad4-6f62b1924026.mp4

**Comment by milindgoel15** [comment]
Blame ROM. YouTube uses system PIP hence vanced has nothing to do with it.

**Comment by WilcyWilson** [comment]
> Blame ROM. YouTube uses system PIP hence vanced has nothing to do with it.

Ok thanks. Will report to the ROM devs instead.
