### ISSUE TITLE
[Idea] Age Restriction Bypass

### ISSUE THREAD

**Issue by Retrodude20** [YTVanced/Vanced#1129]
There's a useful script called "Simple YouTube Age Restriction Bypass" that allows you to bypass age restriction when using YouTube on a web browser. Is it possible to implement a feature like this into YouTube Vanced the same way you've implemented Sponsorblock?

Here's the script - https://greasyfork.org/en/scripts/423851-simple-youtube-age-restriction-bypass

**Comment by milindgoel15** [comment]
Duplicate of #173
