### ISSUE TITLE
[Bug] mobile phone has crashed and has a bootloop

### ISSUE THREAD

**Issue by kkasimir** [YTVanced/Vanced#1130]
YouTube VANCED 

**Bug description**
I looked at YouTube vanced and then went to my destop and then I got the search function on the huwawei p20pro by swiping from the top to the bottom on the screen, picture in picture mode was still on and then the mobile phone rebottled and is in the bootloop stuck

**Variant**
Non-Root

**Vanced version**
 v16.20.35

**Android version**
 Android 10 
10.0.0.185 (C432E7R1P3)
EMUI 10.0.0.185

**Device**
Huawei P20 Pro CLT-L29

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2. back to the desktop
3. picture in picture mode
4. huawei search window (when swiping from top to bottom on the screen)
5. system reboots into bootloop

**Expected behavior**
expected nothing

**Comment by milindgoel15** [comment]
ROM issue
