### ISSUE TITLE
[Bug] Vanced Terminates after I enter my email

### ISSUE THREAD

**Issue by SkyRider13** [YTVanced/Vanced#1136]
**Bug description**
Whenever I add my google account to the YTVanced installed on my Tablet it automatically logs out and refuses to stay open for even more than a few seconds afterwards.)

**Variant**
Root

**Vanced version**
16.20.35
**Android version**
Android 7.1.1 running a 2017/08 Security Patch

**Device**
 Tablet model is a Lenovo Yogabook(XB1-X90F

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2. Click on The profile picture
3. Sign in with google acount

**Expected behavior**
I expected it to sync with my normal Youtube account so i could properly access my subscribed channels and feed like usual

_Attach images or videos or logcats in case of crashes if possible. These can be helpful in solving the issue._

**Comment by milindgoel15** [comment]
The root version doesn't need anyone to enter their email addresses to sign-in. The root version is capable to signing you in without requiring you to enter your email because it directly uses built-in Google Services or equivalent.

From where have you installed vanced?

**Comment by SkyRider13** [comment]
Did I mention mine was rooted? Sorry my mistake. I'm using the non root
method and I installer Vance's manager from your sight and used it to
install microG and YT

**Comment by milindgoel15** [comment]
Ok provide logcat of crash

**Comment by SkyRider13** [comment]
https://drive.google.com/file/d/1CbqaLhsVt5JMbkmLRAI7NGd76dc1sW0B/view?usp=drivesdk
Tried to send the logcat.txt normally but your systems said it was too
large?

**Comment by milindgoel15** [comment]
Are you still facing this issue with the latest v16.29.39 release? If yes, please report back here. Meanwhile I am closing this issue.
