### ISSUE TITLE
[Idea] Put a warning about vanced-ios

### ISSUE THREAD

**Issue by trajano** [YTVanced/Vanced#1139]
**Description**
I was searching for something like Vanced for IOS which yielded a result, but I suggest you put a warning as I don't think that site is legit.

![image](https://user-images.githubusercontent.com/110627/128235360-e97df1aa-e561-401b-b251-67fdae38359d.png)

_Attach images/videos if possible. Also add any links to possible other applications with the said feature already implemented._

**Comment by milindgoel15** [comment]
Absolutely unnecessary idea because you should always follow XDA threads and official social platforms for searching and getting vanced apps.

You searched on Google despite knowing vanced is only available for Android, which is absolutely your personal issue not of vanced.
