### ISSUE TITLE
[Bug] couldnt download 2 sd

### ISSUE THREAD

**Issue by yant0** [YTVanced/Vanced#1142]
**Bug description**
ive been trying to get sdcard download working, i got the dowload to sd checked but it wont download to sd, instead it download to internal

tried : using root, non root, flashing different rom

funny behaviour : when enabling storage access in settings, i opened the app and get to download settings and scroll down and crashed [trace](https://1.filedit.ch/1/KBxxnEeGEKiBWiTrbFZM.txt)
another funny thing : i have fx file manager installed, when opening sd/android it says access denied,,, perhaps related

**Variant**
Non-Root & Root

**Vanced version**
Manager : 2.60
Microg : 0.2.21.212417
_Vanced_ : 16.20.35

**Android version**
unofficial lineage & rr nougat (7.1)

**Device**
Samsung Galaxy Core 2 (SM-G355H)

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2. Open download
3. Open download settings
4. Open see the sd card option already checked
5. Proceed to download a video
6. See it uses internal instead

Steps to reproduce the ~error~ crash:
1. Open app info
2. Open permission
3. Check storage access
4. Open app
5. Open download
6. Open dowload settings
7. Scroll and
8. Cresh

**Expected behavior**
Download video to sd

# [trace](https://1.filedit.ch/1/KBxxnEeGEKiBWiTrbFZM.txt)
(i catch with Scoop, if its not satisfy you recommend me app)

**Comment by milindgoel15** [comment]
Vanced uses the standard YouTube downloader that google provides. Any issues with it is Google's problem.
