### ISSUE TITLE
[Idea] I wish that you will be able to play music on YouTube /music Vanced trought Google assistant

### ISSUE THREAD

**Issue by Yedidyaa** [YTVanced/Vanced#1144]
**Description**
Replace me with a clear and detailed description of the idea.

_Attach images/videos if possible. Also add any links to possible other applications with the said feature already implemented._

**Comment by milindgoel15** [comment]
Use root version then?

It's not possible on non root for obvious reasons as it uses microG, not built-in google services.

**Comment by Yedidyaa** [comment]
Will it let me to do the "hey google, play {music name}"
If I root there will be another option of music services and that would be
YouTube music Vanced?

**Comment by milindgoel15** [comment]
Yes
