### ISSUE TITLE
[Idea] Configurable Playback Speed

### ISSUE THREAD

**Issue by sixhex** [YTVanced/Vanced#1147]
**Description**
Vanced is wonderful allowing an app to play back at 0.25x steps from 0.25x to 2.00x.

Please add an option for extended range on this parameter to around 4.00x if a device is capable. I see this as an advanced option in settings where a user can select maximum allowable playback speed.

_Attach images/videos if possible. Also add any links to possible other applications with the said feature already implemented._

**Comment by milindgoel15** [comment]
Duplicate of #82
