### ISSUE TITLE
[Idea] Add "Share" to the context menu in the Notification page 

### ISSUE THREAD

**Issue by christubuntu** [YTVanced/Vanced#1148]
**Description**
The context menu (3 dots) in the Notification page lacks a "Share" menu. To share a video from there, I have to open the video first, which is annoying. 
Vanced = 16.16.38
![Screenshot_20210808-093703](https://user-images.githubusercontent.com/55885756/128624855-443e49c4-07fe-4a31-a615-308e509ab959.jpg)

**Comment by milindgoel15** [comment]
Ask google for it.
