### ISSUE TITLE
[Bug] Unable to use gsuite connected account on either Youtube Vanced or YT Music Vanced

### ISSUE THREAD

**Issue by niruhsa** [YTVanced/Vanced#115]
**Bug description**
Unable to login to gsuite account using vanced yet othet youtube/google accounts work fine.

**Variant**
NonRoot: Yes
Root: No

**Android version**
Android 10

**Device**
Samsung Note 10 5G (SM-N976B)

**Steps to Reproduce**
Steps to reproduce the error:
1. Install latest version of Vanced & Micro G via MicroG Manager
2. Launch youtube vanced
3. Click account icon and press add account
4. Login into gsuite linked account (Works on desktop)
5. Get error when finished signing in - unselectable.

**Expected behavior**
Sign into google account thats gsuite enabled with my youtube history/playlists/recommendations. I've confirmed this issue exists on both vanced YT music and Vanced Youtube. The issue is also non-existant on the stock versions of these apps.

![Screenshot_20201024-050642.jpg](https://user-images.githubusercontent.com/48173574/97039670-81c0e400-15b8-11eb-9050-ab201bd62736.jpg)

**Comment by Kanin** [comment]
I'm having this same exact issue!

**Comment by waterlava** [comment]
I'm having the same issue as well on my brand new Google Pixel 4a running Android 11 (non-profit). This error is appearing with my personal Gmail account (not gsuite) too. This is likely because the account is managed with family link as the error wasn't there before I started supervision and it leaves when I stop supervision. I would really appreciate a fix.

**Comment by waterlava** [comment]
@niruhsa No I mean supervision with [family link](https://families.google.com/familylink/). I'm certain that it's the same issue though as both of these apps most likely use common software.

**Comment by waterlava** [comment]
So, is someone working on a fix?

**Comment by waterlava** [comment]
I posted an issue on MicroG's repository as well: https://github.com/microg/android_packages_apps_GmsCore/issues/1253

**Comment by waterlava** [comment]
Can someone help us with this bug?

**Comment by KevinX8** [comment]
It's not a bug with vanced it's an issue with microg as mentioned earlier, please move comments to the issue linked earlier

**Comment by SurycL** [comment]
I am having this same problem - I use gsuite just fine with everything else on my phone / computer and this is the only app that has issues.

My ancient @gmail account works great, but all my subscriptions and saved videos aren't there, so that isn't really a good solution.

**Comment by blackouthyper7** [comment]
I have the same :c
