### ISSUE TITLE
request to reopen older request

### ISSUE THREAD

**Issue by fuzzyhamito** [YTVanced/Vanced#1150]
I was browsing through the forum and noticed that this request has been admitted several times, however due to the initial lack of traction. I do think since then the demand for it has exponentially increased and therefor needs to be revisited instead of closing new request simply due to the first request being closed.

The request I am referring to must be obvious by now, is the age verification bypass for the enitre continent of Europe would be highly appreciated when this could be implemented.

**Comment by fuzzyhamito** [comment]
It is truly a horrendous idea that google would need a goverment issued license and have even more detailed information about it's user. Providing them with such documentation is an absolute no go and a bypass function would allow a even more pleasureble use of youtube vanced.

**Comment by milindgoel15** [comment]
Here's the reply to the problem you are all asking for:

```
xfileFIN: Android app doesn't work the same way. It's protobuf and different kinds of calls. Much harder to figure out if there's a bypass than with browser.
```

**Comment by fuzzyhamito** [comment]
Thank you for your quick and thorough response!

I do have a follow up question on that regard if that's alright with you. I understand that this is not a similair situation to a browser and much more difficult. Despite this fact, are there any plans on developing sich feature or is this matter not even worth the hassle from the get go?

**Comment by milindgoel15** [comment]
As xfile said, it's much harder when most of the components of the app are done with protobuf.

**Comment by fuzzyhamito** [comment]
My apologies for pressing on, that bit doesn't seem clear enough of an answer to me. I understand it's harder, but I presume not impossible. So the question remains, is it so hard that it's not worth the hassle of trying to develop that feature or is truly unable to be realised?

**Comment by VancedOfficial** [comment]
The thing is that we don't have the source code nor the knowledge of how the server works. It's all just guessing and we don't know if it's possible until someone manages to do it. I'll be happy to implement such feature but I don't know how (at least not yet) so until I figure out a way to do it or someone else figures it out and tells me, we don't know if it can be implemented or not.

**Comment by fuzzyhamito** [comment]
Alright, thank you very much for the explanation, despite it not being what I would've liked to hear.

**Comment by Reikimann** [comment]
What about newpipe? They've done it.

**Comment by milindgoel15** [comment]
Newpipe isn't based on YouTube app or its code. They use their own code and YouTube API to fetch YouTube videos and display content.

On the other hand, vanced is made on top of YouTube obfuscated code. [Refer this for more information](https://github.com/YTVanced/Vanced/issues/1150#issuecomment-894780035)

**Comment by anonymous7002** [comment]
> xfileFIN: Android app doesn't work the same way. It's protobuf and different kinds of calls. Much harder to figure out if there's a bypass than with browser.

much harder, but still not impossible
