### ISSUE TITLE
[Bug] In-app browser

### ISSUE THREAD

**Issue by ManoMomen** [YTVanced/Vanced#1154]
**Bug description**
Hii, i have an issue with vanced, i just updated both youtube vanced and microG from Vanced manager
The issue is the app keeps opening any link through in-app browser, even when i turn on/off (use chrome customer tabs) form vanced manager settings !
I dont want links to open in in-app browser , i want it to open through my default browser app
Can any one help me ?

**Variant**
Non-Root

**Vanced version**
16.29.39

**Android version**
Android 7

**Device**
Huawei Gr5 2017

**Expected behavior**
In the last versions of vanced the links was opening normaly in my default browser

**Comment by milindgoel15** [comment]
Does official YouTube work the same way?
