### ISSUE TITLE
[IDEA]

### ISSUE THREAD

**Issue by Sarlay** [YTVanced/Vanced#1157]
The issue: The API is always overloaded when a new update comes out, I guess it even costs a lot and people cancel their download because of slow download speed.

My idea: torrents, as more people will download the files, it will be faster. It will be even cheaper to maintain. It might be difficult to integrate inside the vanced manager but even an "official" torrent link to manually install the updates

**Comment by officiallor** [comment]
I thought of this but it either needs to be implemented in Vanced manager (to act like a p2p client), or vanced manager should have an option to select the folders of the update. I don't know if this is a good idea, because noone would seed after.
