### ISSUE TITLE
[Bug] No Cast devices found

### ISSUE THREAD

**Issue by jasper-r75** [YTVanced/Vanced#116]
**Bug description**
A new cast dialog by youtube with added option to Link TV code / Learn more, in Vanced Youtube does not find my Chromecast. In the official youtube app it **does** work as expected. If I clear the data of the Vanced Youtube app I get the old, plain cast dialog back with just my device (well 2x, but that's a known cast bug unrelated to vanced or youtube). But the next time I open the app... back to square one. The workaround is really annoying, because I lose all my preferences.

**Variant**
NonRoot: Yes
Root: No

**Android version**
Android 10.0 

Vanced Manager 1.3.1 (Arcturus)
Non-root 
Youtube Vanced 15.40.37 
MicroG 0.2.13.203916

**Device**
Xiaomi Redmi Note 7
Pixel Experience 10.0.2020101

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2. Click on 'cast icon'

**Expected behavior**
Display a (list  of) cast device(s)

![Screenshot_20201018-124419](https://user-images.githubusercontent.com/73206156/97064377-bc585b80-157b-11eb-87d2-ff2890de2197.png)

**Comment by jasper-r75** [comment]
Issue seems to be resolved, after Youtube changed a bunch of UI components on the player again..

**Comment by teoulas** [comment]
I have the same problem for a few days now.

**Comment by ferrannl** [comment]
Same problem here. App doesn't find Chromecast. 
Fixed it. 
Go to Settings in the YouTube Vanced app -> Watch on TV. 
There it showed my Chromecast first gen.

**Comment by gghhkm** [comment]
This is accent lol.

Go to #688 @ferrannl  @teoulas

**Comment by pmatusik93** [comment]
The same situation... 
![Screenshot_20210428-231238_Vanced Manager](https://user-images.githubusercontent.com/40670548/116473281-4957d680-a877-11eb-9ab0-95cad1f412c7.png)
![Screenshot_20210428-231227](https://user-images.githubusercontent.com/40670548/116473285-49f06d00-a877-11eb-9850-2118419f901d.png)

**Comment by gghhkm** [comment]
@pmatusik93 please go to #688
