### ISSUE TITLE
[Bug] Skipping in video skips 2 seconds too early

### ISSUE THREAD

**Issue by b-aaron** [YTVanced/Vanced#1160]
**Bug description**
While skipping throughout the video using the bottom bar does not bring me to the time I skipped to, but 2 seconds before that time.
This also leads to another bug:
https://github.com/YTVanced/Vanced/issues/1159

**Variant**
Non-Root

**Vanced version**
v16.29.39

**Android version**
Android 10

**Device**
ZTE Axon 10 Pro

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2. Click on a video
3. Skip through the video using the bottom bar (e.g. 05:36)
4. The video starts playing 2 seconds earlier (e.g. 05:34)
Alternatively using the steps in the before mentioned other bug.

**Expected behavior**
The app should skip me to the correct time in the video.

**Comment by b-aaron** [comment]
A temporary solution to this is to skip to the end of the video and then manually (using the bar at the bottom, not the Restart button) skipping to the wanted time.

**Comment by milindgoel15** [comment]
Same goes here

**Comment by milindgoel15** [comment]
However, both of your issues works perfectly on my end. Please try reinstallation. If it still happens, provide screen recording of such issue in a new issue made in sponsorblock repository.
