### ISSUE TITLE
Searches

### ISSUE THREAD

**Issue by argha54325** [YTVanced/Vanced#1166]
While searching something on youtube, the thumbnails are too large and the texts are on the right side so what happens is, it accually hides the time(year/month/day) informations. This is a really annoying issue to me because i mostly watch news. So its very important to me to know the timing of a specific news before clicking. Also if possible please add a filter/sort option in search results so that we can search for Latest uploaded videos like "Most recent/Older"

The search result's thumbnail should be either smaller or the texts should be at the bottom so that nothing hides. If anyone watching this thread from venced team please sent a reply if its possible to fix?

Mail Id:
![Screenshot_20210811-060304](https://user-images.githubusercontent.com/36828331/128952473-8ce2738f-31cc-4df3-b985-699ac5944400.png)
![20210811_063143](https://user-images.githubusercontent.com/36828331/128953984-28ec3fb8-9fdf-4de9-85dd-20e35ccc1a7b.png)

Arghabasu248@gmail.com

**Comment by sudo-nautilus** [comment]
What about original YouTube

**Comment by argha54325** [comment]
> What about original YouTube

Original Youtube shows every single things perfectly, with proper gaps/spaces,I can clearly see the date. I will feel great if Venced too customizes things like that.

**Comment by argha54325** [comment]
![20210811_123422](https://user-images.githubusercontent.com/36828331/128984470-b6176579-5bc4-48b1-acdf-bfa39cb40857.png)

**Comment by sudo-nautilus** [comment]
![Deez Nuts](https://user-images.githubusercontent.com/78522210/128993980-6399fb6c-1521-4953-b0d9-f1ab372716cc.jpg)

This is Vanced on my device and it's just fine. The layout of video searches **can** be *altered* by the YouTube server. In another words, it's server side. However, you can do one thing, just clear the data of Vanced.

**Comment by sudo-nautilus** [comment]
The second video in your screenshot looks kinda horny

![Adios](https://i.kym-cdn.com/photos/images/original/001/855/264/9c8.jpg)

**Comment by argha54325** [comment]
> The second video in your screenshot looks kinda horny
> 
> ![Adios](https://camo.githubusercontent.com/75dec1d63b5d211ab78fe09160cf347a0dcde28aafdea8e2300c819d1e563e1c/68747470733a2f2f692e6b796d2d63646e2e636f6d2f70686f746f732f696d616765732f6f726967696e616c2f3030312f3835352f3236342f3963382e6a7067)

Haha.. Trust me i don't watch those type content. 🤣😂😂
Bytheway After clearing data now it looks same as your one. 😊 thank you for helping me.. 🤗

**Comment by sudo-nautilus** [comment]
You are welcome
