### ISSUE TITLE
[Idea] Please add removal option for "create shorts" in video.

### ISSUE THREAD

**Issue by Harmonie666** [YTVanced/Vanced#1170]
![Screenshot_20210811-230213517 (1).png](https://user-images.githubusercontent.com/73917917/129113114-84d5debc-e495-4c2e-a393-c40e9a4f39fc.png)

Relevant Reddit topic with many upvotes:
https://www.reddit.com/r/Vanced/comments/p2m31c/please_add_removal_option_for_create_shorts_in/?utm_medium=android_app&utm_source=share

I wholeheartedly agree with this redditors comment saying 
"Yeah of course, a toggle in the settings for hiding/showing each button would be ideal if possible"

**Comment by Harmonie666** [comment]
Another using posting a similar idea:

https://github.com/YTVanced/Vanced/issues/1153#issue-963507153

**Comment by milindgoel15** [comment]
Duplicate

**Comment by Harmonie666** [comment]
> Duplicate

I haven't seen a duplicate of this post. Can you please redirect me to it?

**Comment by milindgoel15** [comment]
That issue that referenced in your own comment means the same thing as u are suggesting for, "_Hide the actions button or rearrange or both_"

**Comment by Harmonie666** [comment]
Gotchu. Hopefully you guys will consider a toggle to edit/remove those icons. They are getting to much, and YT keeps adding more and more..
