### ISSUE TITLE
Watched videos history 

### ISSUE THREAD

**Issue by Jolubeat** [YTVanced/Vanced#1175]
**Bug Description**
Using YouTube vanced, the watched videos don't appear in my YouTube watched videos history. Is this an upcoming feature or some bug in my app? 
Thanks

**Variant**
Root

**Vanced version**
2.6.0

**YouTube Vanced Version**
16.29.39

**Android version**
Android 11 

**Device**
Xiaomi mi 9 SE

**Comment by milindgoel15** [comment]
Duplicate of #301
