### ISSUE TITLE
[Bug] Unable to Install YouTube Vanced in latest update of of Android 11.0.0 in OnePlus 6T

### ISSUE THREAD

**Issue by partharorra** [YTVanced/Vanced#1178]
Device description- 
OnePlus 6T
Android version 11.0.0
Non-root

**Bug description**
Was using YouTube Vanced for a year, a couple days ago I updated my phone to the latest Android version from 10 to Android 11. After the update YouTube Vanced disappeared.
Tried installing again. Downloaded the Vanced Manager, YouTube music works fine but when I tried to install YouTube Vanced, it shows-
INSTALL_FAILED_UPDATE_INCOMPATIB LE: Package com.vanced.android.youtube signatures do not match previously installed version; ignoring!

It shows the same error with the latest version and the previous versions that I tried to download also.

If anyone knows how to correct this issue, please let me know.

![Uploading Screenshot_20210814-130516.jpg…]()

**Comment by milindgoel15** [comment]
OOS Bug.

[Read this guide for possible solutions.](https://telegra.ph/Troubleshooting-for-vanced-03-19#C:-Package-conflict-error-on-android-11)

**Comment by partharorra** [comment]
> OOS Bug.
> 
> [Read this guide for possible solutions.](https://telegra.ph/Troubleshooting-for-vanced-03-19#C:-Package-conflict-error-on-android-11)

![16295971259328936867544815257650](https://user-images.githubusercontent.com/88929575/130339317-4d0e943a-e77b-495f-a003-a5096df68d88.jpg)
My device is not showing. I have enabled USB debugging, and cable is properly connected. The File transfer mode is also turned on

**Comment by partharorra** [comment]
I updated the adb software and was able to do the whole procedure. Vanced successfully installed. thank you
