### ISSUE TITLE
[Bug] Video page loading problem

### ISSUE THREAD

**Issue by GKid94** [YTVanced/Vanced#1179]
**Bug description**
The video page won't fully load

**Variant**
Non-Root

**Vanced version**
Image added

**Android version**
Image added

**Device**
Image added

**Steps to Reproduce**
Play a couple of videos

**Expected behavior**
For the video page to load normally

![Screenshot_2021-08-14-13-03-53-042_com vanced android youtube](https://user-images.githubusercontent.com/18757054/129444646-dcada50b-9334-41ae-85ac-896ef5814c97.jpg)
![Screenshot_2021-08-14-13-13-50-685_org zwanoo android speedtest](https://user-images.githubusercontent.com/18757054/129444647-81243abd-b75d-48d1-934f-6ddc8a319e48.jpg)
![Screenshot_2021-08-14-13-14-39-227_com vanced manager](https://user-images.githubusercontent.com/18757054/129444648-22ab5420-530f-4fcb-a06a-c74bd4df7be8.jpg)
![Screenshot_2021-07-16-20-31-42-085_com android settings](https://user-images.githubusercontent.com/18757054/129444659-efd03e59-1566-4968-9117-dbdef3ec4300.jpg)
![Screenshot_2021-07-16-20-31-45-428_com android settings](https://user-images.githubusercontent.com/18757054/129444662-d6c7473f-5434-4356-9316-3414cece6f02.jpg)
![Screenshot_2021-08-14-13-20-13-075_org blokada origin alarm](https://user-images.githubusercontent.com/18757054/129444731-25fd5b53-c3c4-4281-906f-3549e9d462bc.jpg)

**Comment by milindgoel15** [comment]
youtube server issue, not vanced. Disable VPN that u are using or else try reinstallation.
