### ISSUE TITLE
[Bug] Vanced gets laggy and stops responding

### ISSUE THREAD

**Issue by notkemi** [YTVanced/Vanced#1180]
**Bug description**
Vanced gets laggy and eventually stops responding after about an hour of use. I have to wipe cache to make it work again

**Variant**
Root

**Vanced version**
16.29.39

**Android version**
Android 10.3.11

**Device**
OnePlus 6 

**Steps to Reproduce**
Steps to reproduce the error:
It usually happens when the cache reaches around 300mb

**Expected behavior**
-

_Attach images or videos or logcats in case of crashes if possible. These can be helpful in solving the issue._

**Comment by milindgoel15** [comment]
probably an OOS bug. a device with a much lower spec can handle a much larger cache and still give the same performance as it should. Try reinstalling vanced and see if it helps for you.
