### ISSUE TITLE
[Bug] opening crash of youtube vanced

### ISSUE THREAD

**Issue by hunt978** [YTVanced/Vanced#1183]
**Bug description**
After upgrading to latest version of vanced & microg, youbute vanced  had been keeping crashing when ever opening no matter after reinstalling, changing versions etc, while the Music app seems working fine.

**Variant**
Non-Root

**Vanced version**
YouTube Vanced, v16.29.39
Vanced microG, 0.2.21.212417
YouTube Music Vanced, 4.39.50
Vanced Manager, 2.6.0

**Android version**
Harmony OS 2.0.0.166
Android 11

**Device**
Huawei Mate 30 Pro 5G

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app YouTube Vanced
2. Crash

**logcats**
logs below show that something went wrong with inflating class of com.google.android.apps.youtube.app.watch.nextgenwatch.ui.NextGenWatchLayout.

[0813.txt](https://github.com/YTVanced/Vanced/files/6990954/0813.txt)
[0815.txt](https://github.com/YTVanced/Vanced/files/6990956/0815.txt)

**Comment by SirCow123** [comment]
I've been having this problem as well for a couple of days. It's been happening since it's been updated

**Comment by hunt978** [comment]
Somehow, the problem was solved by itself magically once I **CLICKED THE YOUTUBE ICON IN VANCED MANAGER APP**.
