### ISSUE TITLE
[Idea] Toggling Picture-in-picture in YouTube Vanced

### ISSUE THREAD

**Issue by rebeccazee** [YTVanced/Vanced#1185]
**Description**
I am not sure if this is a bug or if this feature was removed. I use picture-in-picture a lot. I do not remember which version this first happened. It used to be that when the picture-in-picture option was toggled, you did not have to exit the app in order for it to be enabled or disabled. I would listen to music and regular videos throughout the day. I disable the option when I just want to listen to music with my device off and other times I use picture-in-picture when watching an actual video while sometimes using another app. I also look through my feed while a video is playing so if I exit the app my feed would be refreshed which I do not really want to happen. It was nice when you did not have to exit the app in order for picture-in-picture to be toggled. I would appreciate it if this feature was back.

**Comment by milindgoel15** [comment]
Vanced never had any button for toggling pip.

And duplicate issue
