### ISSUE TITLE
[Bug] Full Screen Swipe not working as intended

### ISSUE THREAD

**Issue by VyzerMusic** [YTVanced/Vanced#1186]
**Bug description**
About 75% of the time I open a video and swipe up to enter full screen, 
It automatically exits full screen within a split second, and I then have to open full screen again. I've tried waiting a few seconds before swiping up to open full screen, but that doesn't work either.

**Variant**
Non-Root/Root

**Vanced version**
 v16.29.39

**Android version**
Android 10 

**Device**
Huawei Y9 Prime

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2. Click on any videos
3. Swipe up to open full screen

**Expected behavior**
Having the video stay full screen rather than exit full screen a split second after opening the full screen.

**Comment by VyzerMusic** [comment]
Also, correct me if I'm wrong, but it appears the video I attached to my prior post isn't showing up. If that's the case, let me know and I'll upload it to my YouTube channel as unlisted.

**Comment by milindgoel15** [comment]
ROM issue, not vanced

**Comment by VyzerMusic** [comment]
But this problem doesn't occur in the official YouTube app nor any other apps, is there anything I can do to fix it?

**Comment by VyzerMusic** [comment]
Hello, I'm facing the exact same issue on a completely new phone, different brand and everything. And just like before, it only happens with YouTube Vanced, not any other official or modded YouTube apps
