### ISSUE TITLE
[Idea] Custom Playback Speed faster than 2x (2.25x / 2.5x / 2.75x / 3x)

### ISSUE THREAD

**Issue by AbdulMalikDev** [YTVanced/Vanced#1187]
**Description**
Ability / Feature to Increase playback speed upto 3x. Current maximum is only 2x. 

In desktop version this can be handled by using an extension but there have been multiple issues for this that have been closed even though there is massive support for this feature.

**Comment by milindgoel15** [comment]
Duplicate of #82

**Comment by AbdulMalikDev** [comment]
> Duplicate of #82

This issue is closed thats why i opened a new one
