### ISSUE TITLE
[bug] loop having more priority than the next video

### ISSUE THREAD

**Issue by moonnikill** [YTVanced/Vanced#119]
when playing a video that's in a playlist and looping it, it still goes to the next video in the playlist. This makes you have to either not use the loop function when playing a song from a playlist, or opening the video outside of the playlist (searching up the video, playing it from there, and looping that instead). I don't think this is a good feature because if i wanted to not loop the video, i would turn it off. Thank you for reading this, and i hope it gets implemented.

**Comment by milindgoel15** [comment]
Please update to the latest release if you haven't already. In the latest release, you will find the auto-repeat feature in vanced settings > misc. After this, You also need to turn off autoplay to make sure the auto-repeat/loop feature works. We are closing this issue for now. feel free to reopen if you have any queries with this.
