### ISSUE TITLE
[Idea] Tablet mode UI like Vanced Music

### ISSUE THREAD

**Issue by JustVictor17** [YTVanced/Vanced#1196]
**Description**
Make a tablet like mode on Vanced but mantaining the features of lower DPI' maybe in that way keeping the cool landscape orientation of the tablet mode :)

Here are some cool screenshots

![Screenshot_20210818-235527](https://user-images.githubusercontent.com/87635958/130011393-3efd85d9-b936-49bc-b8a0-caf22bc7a8d0.png)

![Screenshot_20210819-000233](https://user-images.githubusercontent.com/87635958/130011430-89108ec7-2f06-4bf1-9080-d37fef016a5e.png)

![Screenshot_20210819-000241](https://user-images.githubusercontent.com/87635958/130011445-f93e392f-7560-42af-95cd-5d7876e83f89.png)

![Screenshot_20210819-000306](https://user-images.githubusercontent.com/87635958/130011465-94083647-9336-499a-990a-d0137d45c5c4.png)

Also, keep the comentary tab on there it comes in handy, like, a LOT

**Comment by madgoatz** [comment]
lol.. the answer that the mods are going to give you is "ask google"

**Comment by milindgoel15** [comment]
+∞
