### ISSUE TITLE
[Idea] Pressing the download option redirects to a yt downloader...?

### ISSUE THREAD

**Issue by JustVictor17** [YTVanced/Vanced#1198]
**Description**
I'm not quite sure if it would be a good idea since it might have legal issues...
Here's the screenshot:

![Screenshot_20210819-004006](https://user-images.githubusercontent.com/87635958/130014429-d7e4fae7-bd07-4b7a-a29b-60f114948db3.png)

**Comment by MinePlayersPE** [comment]
couldn't you just use the share button to share to newpipe

**Comment by milindgoel15** [comment]
Jesus Christ

DO NOT ASK SUCH THINGS AGAIN.

**Comment by mklr95** [comment]
Maybe it will be a better idea to show a toast for non premium users, that downloading videos is disabled for non premium? This probably will reduce significantly the amount of people asking for the download feature.
