### ISSUE TITLE
[Idea] remove the "image" icon in community posts

### ISSUE THREAD

**Issue by sudo-nautilus** [YTVanced/Vanced#1199]
**Description**

Ok so, this is the icon that I'm talking about:
![IMG_20210819_202729_948](https://user-images.githubusercontent.com/78522210/130091813-7248751d-09f6-4b30-9ebc-7b6286c90c71.jpg)

It would be helpful to steal memes from youtube community posts if the icon was not visible. 

_Attach images/videos if possible. Also add any links to possible other applications with the said feature already implemented._

**Comment by madgoatz** [comment]
no, if that is removed then i will confuse them for videos... u can either crop out the icon or use a editing app to clone or heal that section of the photo... use your brain

**Comment by sudo-nautilus** [comment]
> no, if that is removed then i will confuse them for videos...

![IMG_20210820_093821_997](https://user-images.githubusercontent.com/78522210/130177985-1c272f2d-fa2d-47e7-bbf3-9f551dedd86c.png)
Videos and community posts has different layouts `¯\_(ツ)_/¯`

> u can either crop out the icon or use a editing app to clone or heal that section of the photo... use your brain..

It merges the adjacent pixels to the small/large scale area thus making it even more ugly. 

> or as u replied on this post [#1190 (comment)](https://github.com/YTVanced/Vanced/issues/1190#issuecomment-901982700) ... "use a browser lmao"

![IMG_20210820_093811_712](https://user-images.githubusercontent.com/78522210/130178262-7409d240-7b78-4897-8cec-1aea468e4a70.png)

Okay

**Comment by sudo-nautilus** [comment]
There's no point in keeping this still open
