### ISSUE TITLE
Youtube Vanced

### ISSUE THREAD

**Issue by city2026** [YTVanced/Vanced#12]
It would be wonderful if you implement the feature that would allow select & copy text from description of youtube videos

Sometimes there can be names, addresses, etc. - infirmation that would be easier to copy selectively rather than retyping it on the mobile by heart

**Comment by VancedOfficial** [comment]
Video descriptions use Litho flattened views so copying text from those isn't really possible. I'll keep this open for a while in case I figure out a way to prevent that flattening from happening.
