### ISSUE TITLE
[idea] Ability to hide community post from subscription feed, like is already possible with videos.

### ISSUE THREAD

**Issue by tonn333** [YTVanced/Vanced#1202]
Community posts are quite annoying because most of them I don't care about. I don't want to disable them because some are of interest to me.

**So many community posts are like ad's!!! This is the most ironic and infuriating part of it!**  

So they just sit there with no way to hide them or mark as read... Like I already can do with videos! Why not these annoying community posts, which most of the time have little to do with the content I subscribed for.

I like to keep my subscription feed as clean as possible. Only videos that that I want to watch but have yet to watch will remain.  
![](https://i.imgur.com/SuZ6qx6.jpg) 
![Why is this ad not hidden?](https://i.imgur.com/hXQG95Z.jpg)

**Comment by madgoatz** [comment]
on version 16.29.39 (the latest at the time of writing) there's more options

![unnamed2](https://user-images.githubusercontent.com/88365986/130213394-77661ed5-7a25-4821-9ece-6c6a157cea6d.png)

**Comment by tonn333** [comment]
@madgoatz First this is in home tab not subscription feed. 
And second it is still impossible to hide or mark as read/watched this particular post. Like we can do with videos!!!

**Comment by madgoatz** [comment]
@tonn333 oh, my bad...

**Comment by milindgoel15** [comment]
Ask Google

**Comment by tonn333** [comment]
Ask Google to hide ad's :joy:

**Comment by tonn333** [comment]
@milindgoel15 Ask Google to hide ad's :joy:
