### ISSUE TITLE
[Idea] Option to disable auto-refresh of feed

### ISSUE THREAD

**Issue by oscar75310** [YTVanced/Vanced#1204]
I have dozens of new videos in my subscriptions every day and every time I switch to another app and then back, the app auto-refreshes the feed and it makes me start at the top again. So I gotta spend a good 30 seconds to scroll back down again to look for the spot I was at. It happens in the recommended feed too and I lose a video I was interested in because it refreshes the feed. Kinda how Twitter never loses your spot in the feed. Thanks.

**Comment by madgoatz** [comment]
not a vanced problem. your OS is killing or putting background processes to sleep.

**Comment by oscar75310** [comment]
Awesome thanks for the help.

**Comment by LMarius** [comment]
> Awesome thanks for the help.

Disable battery optimization at youtube vanced and it will work i think.

**Comment by oscar75310** [comment]
Nah I tried it. Before it would do it every time after 5 seconds off the app. Now it does it after like half a second. Either I come back to the app and it fades to black real quick and comes back with the feed refreshed, or I come back and I see the refresh wheel and then takes me to the top of the feed. I've also seen it do it less if I don't change it to fullscreen but I haven't tested it since making this thread.

**Comment by oscar75310** [comment]
Also happens when I go check out a channel and then back out of it.
