### ISSUE TITLE
[Bug] Using VPN will disable Premium status.

### ISSUE THREAD

**Issue by YuyukoSS** [YTVanced/Vanced#1205]
**Bug description**
When using YouTube Vanced with VPN, some Premium features will be unavailable, and "Get YouTube Premium" option will appears (Notice I used a VPN on second attached picture).
So far, background player still worked as intended, but YouTube Music Premium does not.

**Variant**
Non-Root

**Vanced version**
v16.29.39

**Android version**
Android 11

**Device**
Samsung Galaxy A50 (2019)

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app.
2. Activate any VPN.
3. Click on user info panel.

**Expected behavior**
The first attached image.

**Additional media**
![Screenshot_20210821-100653](https://user-images.githubusercontent.com/50669582/130308736-25bee9d0-642a-42ea-917b-b5bc2f62fd85.png)
![Screenshot_20210821-100732](https://user-images.githubusercontent.com/50669582/130308737-2dd7dc2c-185e-45df-94cc-4905b0b9092c.png)

**Comment by milindgoel15** [comment]
Vanced ≠ YT premium

How many times we have to explain that?
