### ISSUE TITLE
[Bug] Unable to log in

### ISSUE THREAD

**Issue by Frozen-cake** [YTVanced/Vanced#1206]
**Bug description**
When attempted to log in it would claim network error or unhability to reach google's server.
If I try by first trying to comment or like, on the log in to do so pop up it will take a moment and say network error
If I try by going to my profile and use that log in option it will open a microG log in thinggy that would say unable to reach google

**Variant**
Non-Root/Root

**Vanced version**
v16.29.39

**Android version**
Android 10

**Device**
Honor 8X

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2. Click on any log in option
3. Follow the instructions
4. Be sad

**Expected behavior**
Succesfully log in an be allowed to comment, like and have access to my subscriptions

**Screenshots**
![Screenshot_20210821_005551_com mgoogle android gms](https://user-images.githubusercontent.com/89288231/130310349-7fa8aa89-5f1d-4ed0-a45d-94afd8b96de3.jpg)
![Screenshot_20210821_005556_com mgoogle android gms](https://user-images.githubusercontent.com/89288231/130310351-fd5579e6-380e-4846-8b09-c4945e902699.jpg)
![Screenshot_20210821_011113](https://user-images.githubusercontent.com/89288231/130310353-4973de60-5353-4040-bd86-462520f58de8.jpg)

Translation: 
"There's an app on your device that's trying to log in on a google account.

If this was intentional press start (or Huawei if your device it's that brand) to connect with the main google log in page, if it wasn't intentional press cancel to go back to the app that created this dialog"

"Sorry..

There was a problem reaching Google's servers.

Try again another moment."

**Comment by milindgoel15** [comment]
Read [this guide](https://telegra.ph/Troubleshooting-for-vanced-03-19) for fix.
