### ISSUE TITLE
[Idea] Video downloader and inbuild mp3 converter.

### ISSUE THREAD

**Issue by Rishibaghel01** [YTVanced/Vanced#1209]
**Description**
Generally when we download videos in youtube it save it in youtube and that video will not be appeared on file manager of your phone....
Add download button which save directly to the phone storage with mp3 converter feature for video songs and also with multiple resolution video download option. Its like many youtube video downloader websites do..

_Attach images/videos if possible. Also add any links to possible other applications with the said feature already implemented._

**Comment by milindgoel15** [comment]
For god's sake, use ur eyes
