### ISSUE TITLE
[Idea] YT music audio integration for YT vanced

### ISSUE THREAD

**Issue by TxJK** [YTVanced/Vanced#1210]
YouTube has very very poor audio quality. The audio quality is much better in YT music or any other Spotify app.
If you guys don't know, the all YT videos are available on YouTube music. And it has much better audio quality.
Maybe you could push this with a beta update at least for watching online maybe with a toggle to switch it on... I guess.
It would be super awesome listening to videos and music videos.

**Comment by madgoatz** [comment]
i disagree with this idea, listening to youtube videos with the audio quality of YT music will take away the clarity or some of the videos.

**Comment by TxJK** [comment]
That's why I request a toggle switch.
Just watch a video and compare.... the audio quality once.

**Comment by milindgoel15** [comment]
Ask google to implement audio quality options for you. It's a Google problem to deal with, not vanced as we do NOT own YouTube or have its code or control their servers
