### ISSUE TITLE
[Bug] Sponsorblock creates an repeate bug

### ISSUE THREAD

**Issue by mkikets99** [YTVanced/Vanced#1211]
**Bug description**
With sponsorblock enabled there is some videos which will stuck in certain positions, and repeating maybe .5 second duration

Enabled features:
- Sponsorblock: all switches are on
- Vanced settings
- - auto repeat button

**Variant**
_Root_ is installed, didnt know about Non-Root though

**Vanced version**
 v16.29.39

**Android version**
 Android 11 

**Device**
 Samsung Galaxy Note 10 Plus

**Steps to Reproduce**
Steps to reproduce the error:
1. Open [link](https://youtu.be/ndYGGlTGL_E) in app
2. Go to sponsorblock nearly at 7:00
3. It's stuck at 7:05

**Expected behavior**
Continues to play after sponsorblock without repeating

_Attach images or videos or logcats in case of crashes if possible. These can be helpful in solving the issue._
https://youtu.be/oRso8zsMiEY

Logcat will be added later

**Comment by mkikets99** [comment]
Ok.. seens like no logcat now, but
This bug is solving when:
1. Background play is enabled
2. You switching to recent apps

You can hear that video is continues to play normally

**Comment by milindgoel15** [comment]
Sponsor lock related issues go to vanced sponsorblock repository only!
