### ISSUE TITLE
[Feature] Shorts tab removal

### ISSUE THREAD

**Issue by TxJK** [YTVanced/Vanced#1212]
YouTube has added shorts and the shorts tab removal should be a feature like the create button.
Please replace it with explore/trending tab if you can.

![Screenshot_2021_0822_212858.png](https://user-images.githubusercontent.com/86510486/130361927-3f697105-7ce4-4402-bb76-ee240e2afeac.png)

**Comment by milindgoel15** [comment]
Duplicate of #334
