### ISSUE TITLE
Vanced Casting Google Play Services MicroG

### ISSUE THREAD

**Issue by PeterKW** [YTVanced/Vanced#1213]
I have had this problem before and I believe I fixed it in settings but I'm not sure how to anymore. When I try to cast YouTube to a device vanced says "YouTube vanced won't run unless you update Google Play Services". I am using micro g and everything seems to be uptodate.
Any ideas on what I should try next?

**Comment by PeterKW** [comment]
![Screenshot_20210822-192823.png](https://user-images.githubusercontent.com/13779157/130366008-79af5f52-3f26-4237-ab9e-25b4a75e2874.png)

**Comment by PeterKW** [comment]
![Screenshot_20210822-193042.png](https://user-images.githubusercontent.com/13779157/130366049-0744ec40-32ab-4c69-b72c-d3a052d10593.png)

**Comment by milindgoel15** [comment]
Duplicate of #688

**Comment by PeterKW** [comment]
> Duplicate of #688

Sorry @milindgoel15 a bit confused. Is this a known bug that's being working on then? It used to work for me and only recently broke and I was wondering if it was something I had got wrong in my settings?

**Comment by milindgoel15** [comment]
It's a known bug and it's microG bug, Not vanced.

**Comment by PeterKW** [comment]
> It's a known bug and it's microG bug, Not vanced.

Ah okay, thank you very much that makes sense
