### ISSUE TITLE
[Idea] replaceme

### ISSUE THREAD

**Issue by Mimicthis** [YTVanced/Vanced#1216]
Please add an option to remove Stories icons. One's on the toolbar on the homepage, other one is under all videos. 

![Screenshot_20210824-231752](https://user-images.githubusercontent.com/29215437/130691378-b4eefcdb-e69d-4e60-9486-7a8d1b4df874.jpg)
![Screenshot_20210824-231723](https://user-images.githubusercontent.com/29215437/130691399-92d60694-81d4-4a30-ba91-4c1af08b75ed.jpg)

**Comment by madgoatz** [comment]
duplicate of #334 #1153 #1170 and others

**Comment by milindgoel15** [comment]
Just #1153
