### ISSUE TITLE
[Idea] Toggle to remove Autoplay function

### ISSUE THREAD

**Issue by Harmonie666** [YTVanced/Vanced#1217]
I personally use the autoplay button extremely rarely if at all, and I would appreciate if you could add a toggle to remove it from the UI, both in vertical and horizontal mode. Only thing that happens is that I accidentally tap it.

![Screenshot_20210824-234024595 (1).png](https://user-images.githubusercontent.com/73917917/130693913-63eb8e61-8a02-4751-a34a-5a0208ea4154.png)

**Comment by madgoatz** [comment]
lol... downgrade to a older version of vanced, the autoplay button is below the video player & not on the video interface

on the other hand, if u disable cast & segment skip rating buttons then the autoplay switch won't be in that position and there for will be in another position that u don't accidentally click.

**Comment by milindgoel15** [comment]
#943
