### ISSUE TITLE
[Bug] video pause after volume up x2

### ISSUE THREAD

**Issue by glennmca** [YTVanced/Vanced#1218]
**Bug description**
When pressing volume up 2 times the video will pause, it does not show as being in a paused state, I have to press pause then play to resume the video, does not happen with volume down. 

**Variant**
Non-Root

**Vanced version**
Replace me with the exact version of vanced you are using. It is mandatory to report issues from the latest available versions only. For example, v16.29. 39

**Android version**
Android 10

**Device**
Huawei P30 Pro

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2. Click on any video or short
3. Press volume up twice (hardware button on device) 

**Expected behavior**
Video or short will pause/freeze, press pause then play and video should resume.

**Comment by glennmca** [comment]
After some research this may not be an issue with the app, I found a reddit thread from two years ago where people were having the same issue across youtube/spotify/sound loud etc.

**Comment by milindgoel15** [comment]
ROM issue, not vanced
