### ISSUE TITLE
[Bug] Probably memory leak

### ISSUE THREAD

**Issue by MasterixCZ** [YTVanced/Vanced#1224]
**Bug description**
Very high RAM Usage (Probably memory leak)
**Variant**
Non-Root

**Vanced version**
v16.16.38

**Android version**
Android 11, MIUI 12.5.1 

**Device**
Redmi Note 8 Pro

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2. Click on video
3. watching video
4. Fast battery consumption
5. First it was 500MB+, then 600MB+, 700MB+ and now almost 1GB of RAM
![IMG_20210828_192208 1](https://user-images.githubusercontent.com/84620639/131226151-b4dd2369-95ce-4a0a-9986-ba51adbb82a0.jpg)

**Expected behavior**
Fix it/optimize it

_Attach images or videos or logcats in case of crashes if possible. These can be helpful in solving the issue._

**Comment by milindgoel15** [comment]
Not Vanced issue, the data usage directly depends on your usage. See this article for information on data usage on various quality options. Youtube play your YT video of 1080p quality with data usage of 480p & below.

https://www.androidauthority.com/how-much-data-does-youtube-use-964560/#:~:text=youtube%20data%20usage%2C%20by%20the%20numbers

**Comment by MasterixCZ** [comment]
It's not mobile data consumption but RAM. I've never had an app consume so much before. And that's right out of the gate.

**Comment by milindgoel15** [comment]
Ok so why the hell are you using an older version?

**Comment by MasterixCZ** [comment]
?! I'm using latest version.

**Comment by milindgoel15** [comment]
> ?! I'm using latest version.

![image](https://user-images.githubusercontent.com/45682747/131246944-f67ff7d4-b212-4627-b0e0-fbd6d8ab90c6.png)
really? v16.29.39 is the latest version of vanced. Please use vanced manager to update to the latest version.

**Comment by MasterixCZ** [comment]
Sorry, my bad. I'm using the latest version. I downgraded to 16.20.35 and I don't have this problem.

**Comment by MasterixCZ** [comment]
This version was listed in the form as an example so I thought it was the latest one 😅 But as I wrote. I was using the latest version and had very high RAM usage.

**Comment by milindgoel15** [comment]
V16.29.39 has no issues regarding memory leak(atleast none of our testers or other members faced it). It's weird why are you getting it. 

Please try reinstalling vanced and use old microG (v0.2.20, not latest) as it might be due to this very latest microG since there are reports that Google hates this version. Because it has other issues as well.
