### ISSUE TITLE
[Bug] issue about repeating any video 

### ISSUE THREAD

**Issue by MocDuong1905** [YTVanced/Vanced#1227]
I turn on loop mode for any video. but it has no effect on that video 

**Variant**
Non-Root

**Vanced version**
16.29.39

**Android version**
Android 7

**Device**
Xiaomi Redmi Note 4x

**Comment by milindgoel15** [comment]
The vanced loop feature requires you to disable auto play in YouTube player for loop to work. Moreover, the loop won't work inside Playlist as it's only designed to work outside playlist.

The YouTube own loop is implemented by Google and any issues with it is not vanced concern.
