### ISSUE TITLE
Looping notifications

### ISSUE THREAD

**Issue by PokemasterDude** [YTVanced/Vanced#1229]
Occasionally, I'll have a bug where about every 30 seconds I get flooded with the SAME NOTIFICATIONS. It makes my device unusable. I've tried redownloading Vanced/MicroG, and that's only a temporary fix. I COMPLETELY SHUT OFF NOTIFICATIONS AND IT'S STILL HAPPENING. PLEASE FIX SOON IVE BEEN HAVING THIS PROBLEM SINCE THE LATEST UPDATE AND I DONT KNOW HOW TO DOWNGRADE

**Comment by milindgoel15** [comment]
Duplicate of #1107
