### ISSUE TITLE
[Bug] App is removed upon restart/power cycle

### ISSUE THREAD

**Issue by lilbud** [YTVanced/Vanced#123]
**Bug description**
Youtube Vanced is removed everytime I turn off and on my phone. I can install it fine and use it fine, but once I power down my phone and power it back on, the app is removed and I must install it again.

**Variant**
NonRoot: No
Root: Yes

**Android version**
Android 10.0 - CrDroid 6.11

**Device**
Oneplus 5 

**Steps to Reproduce**
Steps to reproduce the error:
1. Install the app through Vanced Manager
2. Restart/power cycle phone
3. App is removed

**Expected behavior**
The app should install once and stay installed regardless.

It isn't really something that can be captured in video/pictures, since restarting the phone is part of the issue.

**Comment by HamoBoker** [comment]
Same problem on android 8.0

**Comment by lilbud** [comment]
@HamoBoker Same phone? or a different phone?

I also have vanced installed on my Moto G5 Plus (Android 10, Dirty Unicorns ROM, Rooted) and Vanced stays between power cycles.

**Comment by HamoBoker** [comment]
Hey @lilbud 

```
Samsung C9 Pro SM-C9000 (One UI)
Android v8.0.0 (API 26)
(Rooted) Stock Samsung ROM
EdXposed v0.4.6.2 (YAHFA)
Magisk Latest Version v20.4
```
1. I installed **Rooted** Youtube Vanced via Vanced Manger latest version and works perfectly.
2. app is removed on device restart

**Comment by EL-S** [comment]
I have a Mi Mix 2,
Root Variant,
Android 9
Magisk Root

Vanced stops working when device powers off and on, It crashes until I open Vanced Manager and restore YouTube to factory then reinstall Vanced.

**Comment by ranolfi** [comment]
Related: https://github.com/YTVanced/VancedManager/issues/212

**Comment by milindgoel15** [comment]
please update to the latest version of vanced manager to fix the disappearing issues while rebooting. If the issue still happens, feel free to reopen this issue. We are closing this for now
