### ISSUE TITLE
[Bug] Shorts layout removal doesn't work

### ISSUE THREAD

**Issue by FriederHannenheim** [YTVanced/Vanced#1232]
**Bug description**
I went to Vanced Layout settings and disabled YouTube shorts. When I reloaded the app the shorts are still there.

**Variant**
Non-Root

**Vanced version**
v16.29.39

**Android version**
Android 11 

**Device**
Samsung Galaxy S10 lite

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2. Click on your profile picture
3. Click settings
4. Go to Vanced settings
5. Go to Layout
6. Disable shorts

**Expected behavior**
No YouTube shorts are shown on the front page

**Comment by milindgoel15** [comment]
What type of shorts are you talking about in the first place?

**Comment by FriederHannenheim** [comment]
> What type of shorts are you talking about in the first place?

YouTube shorts
![Screenshot_20210831-133604](https://user-images.githubusercontent.com/41985738/131495808-fe1fc0d0-1c82-4b4d-a6e4-50687d05793b.png)

**Comment by milindgoel15** [comment]
Clear data of vanced app > enable shorts removal > force stop app

**Comment by FriederHannenheim** [comment]
That did not fix it :(

**Comment by milindgoel15** [comment]
Which download link you used to download vanced? and show the screenshot of the version you currently have.

**Comment by FriederHannenheim** [comment]
I downloaded Vanced from the Vanced manager. I got the Vanced Manager from vancedapp.com

![Screenshot_20210831-145612](https://user-images.githubusercontent.com/41985738/131506359-68291749-1535-4e97-804f-25e8a9644f60.png)
