### ISSUE TITLE
[Bug] Thumbnail on video post notification is too big and blocks text on Galaxy Z Fold series front display

### ISSUE THREAD

**Issue by chorong761** [YTVanced/Vanced#1235]
**Bug description**
Thumbnail in video notification too big, blocking text

**Variant**
Non-Root

**Vanced version**
v16.29.39

**Android version**
Android 11 

**Device**
Samsung Galaxy Z Fold 3

**Steps to Reproduce**
Steps to reproduce the error:
When you get a video upload notification, pull down the notification menu on the front display of the Z fold 3 and you will see the notification with the big thumbnail

**Expected behavior**
The thumbnail should be smaller so more text could be shown

Screenshot of issue:

![Screenshot_20210831-062001_One UI Home](https://user-images.githubusercontent.com/17227895/131580327-0a96b902-add0-4b84-afa5-02c8bd881b51.png)

**Comment by milindgoel15** [comment]
OneUI issue, blame samsung
