### ISSUE TITLE
[Bug] No Sort By under videos only showing playlist

### ISSUE THREAD

**Issue by Kasmotmot** [YTVanced/Vanced#1239]
**Bug description**
Under videos when browsing a channel, before i have sort by to sort videos from old, new, popular but now it was replaced by playlist

**Variant**
Non-Root

**Vanced version**
16.29.39 build 01.54.00

**Android version**
Miui 12.5.1 Android 11

**Device**
Poco X3 NFC

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2. Click on VIDEOS
3. It will only show Playlist on the upper part

**Expected behavior**
Should have SORT BY option just like the official YT app

![Screenshot_2021-09-02-19-07-43-236_com vanced android youtube](https://user-images.githubusercontent.com/89977436/131833202-bfe7dd7f-84b4-4bab-a265-9749b5d00947.jpg)

**Comment by milindgoel15** [comment]
Issue on your end. Clear data and don't play with vanced settings.

![20210902_182542.jpg](https://user-images.githubusercontent.com/45682747/131847338-c39c47c2-a079-4bfa-bb0a-1d673fdab785.jpg)

**Comment by Kasmotmot** [comment]
I didn't even touch the settings, i've tried to clear data, uninstalled and reinstall 3 versions of Vanced even microG to solve the issue and it's all coming up with the same result.

**Comment by Kasmotmot** [comment]
> Issue on your end. Clear data and don't play with vanced settings.
> 
> ![20210902_182542.jpg](https://user-images.githubusercontent.com/45682747/131847338-c39c47c2-a079-4bfa-bb0a-1d673fdab785.jpg)

I didn't even touch the settings, i've tried to clear data, uninstalled and reinstall 3 versions of Vanced even microG to solve the issue and it's all coming up with the same result.
