### ISSUE TITLE
[Bug] cannot open videos on the feed

### ISSUE THREAD

**Issue by ghxstshadxw** [YTVanced/Vanced#124]
**Bug description**
downloaded youtube vanced and the last micro G version on telegram and when tried opening videos from the feed, couldn't do that but everything else worked

**Variant**
NonRoot: Yes
Root: No

**Android version**
Android 9.0 - Pie

**Device**
Samsung Galaxy A7s

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2. Click on a video 
3. doesent work
4. trying to install the app again 
5. same bug happens

**Expected behavior**
to be honest the actual app is great ive been using it for more then a year now. i'd like it if more versions will come up and more reports of what your doing.

_Attach images/videos if possible. These can be helpful in solving the issue._

**Comment by milindgoel15** [comment]
Can you check if it still happens on the latest version now? We are closing this issue for now. feel free to reopen if it still happens and provide a screen recording.
