### ISSUE TITLE
[Bug] "Skip segment" icon carries over between videos if it was shown when you click on another one

### ISSUE THREAD

**Issue by oblanmaN** [YTVanced/Vanced#1241]
**Bug description**
When a sponsorblock section with the "Skip segment" icon appears and you open another video during that, usually for an endcards segment. It disappears if you click on it without skipping anything.

**Variant**
Non-Root

**Vanced version**
 v16.16.38

**Android version**
Android 11

**Device**
Samsung Galaxy A11

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2. Click on a video
3. Have a "Skip segment" prompt appear
4. Click on a recommended video

**Expected behavior**
You should expect no prompt to appear unless there is another segment at the start of the next video.

**Comment by milindgoel15** [comment]
Closing this issue since op is using old version. Update to v16.29.39 before reporting any issue.
