### ISSUE TITLE
[None responsive]

### ISSUE THREAD

**Issue by TDMBugs** [YTVanced/Vanced#1243]
YouTube and YT Music Vance are not responding or loading any content, upon re-installation I am unable to log in to any account while using Youtube and YT Music Vance app

Pls fix or help

**Comment by milindgoel15** [comment]
Better to provide some useful information instead of vague information. Show some screenshot of what exact error you are getting

**Comment by TDMBugs** [comment]
![Screenshot_2021-09-04-19-52-18-23_7a4090f09f6554852d748ee9fd6f40d3](https://user-images.githubusercontent.com/90094430/132093561-313315e6-538f-498e-afe3-d1d41182a29e.jpg)
Thank you for responding on such short notice, here are a few screenshots 
![Screenshot_2021-09-04-19-51-39-27_fc456b72a3bc68fcc3663e3817ad5dab](https://user-images.githubusercontent.com/90094430/132093544-1b3505d7-8a70-4da6-a1ed-2ff5ceba6ca0.jpg)
![Screenshot_2021-09-04-19-51-42-02_fc456b72a3bc68fcc3663e3817ad5dab](https://user-images.githubusercontent.com/90094430/132093547-5187eb0b-cc09-4b24-8010-301deb24fde5.jpg)
![Screenshot_2021-09-04-19-51-50-46_7a4090f09f6554852d748ee9fd6f40d3](https://user-images.githubusercontent.com/90094430/132093553-048b78d3-3227-45f8-82f1-ceceb0435418.jpg)
![Screenshot_2021-09-04-19-52-00-39_7a4090f09f6554852d748ee9fd6f40d3](https://user-images.githubusercontent.com/90094430/132093555-4aa61c2a-78df-4fac-b5e8-b8e752a6443e.jpg)
![Screenshot_2021-09-04-19-52-10-97_7a4090f09f6554852d748ee9fd6f40d3](https://user-images.githubusercontent.com/90094430/132093557-811e538a-f5be-4537-85a4-6c561203c5c2.jpg)

**Comment by milindgoel15** [comment]
What version do you have of both vanced, music and microG? And how did you installed them?

**Comment by TDMBugs** [comment]
![Screenshot_2021-09-04-21-43-29-26_664cadb1c148e0d90475ca0f494fbf83](https://user-images.githubusercontent.com/90094430/132096532-1d07b905-53fb-446e-a7cb-cbd2198ed1d0.jpg)

Currently, I have all in its up to date versions, and I installed them from the app itself

**Comment by milindgoel15** [comment]
If you can't bother providing the information we are asking, then we won't bother helping you. If you want us to help you, provide the actual numbers and links you used.

**Comment by milindgoel15** [comment]
Ok alright, what phone do you have?

**Comment by TDMBugs** [comment]
Realme 7I

**Comment by milindgoel15** [comment]
Follow this link and use every possible solution carefully: https://telegra.ph/Troubleshooting-for-vanced-03-19#Login-issues
