### ISSUE TITLE
[Bug] Headset media controls unable to reliably control media

### ISSUE THREAD

**Issue by Dwismas** [YTVanced/Vanced#1244]
**Bug description**
Sometimes media controls on headsets are unable to control playback. Sometimes, pausing and resuming the video temporarily fixes the issue. This issue seems to have popped up after the update to Android 11, but I can't be certain.

**Variant**
Non-Root

**Vanced version**
v16.16.38

**Android version**
Android 11 

**Device**
Samsung Galaxy S10

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2. Play a video
3. Attempt to control media through headset controls (sometimes it works, other times it does not.

**Expected behavior**
Headset media controls should always work.

**Comment by milindgoel15** [comment]
Closing this issue as the OP is using an old version to report old stock YT bugs present at that point in time. Please update to the latest version using vanced manager and your issue will get solved immediately.
