### ISSUE TITLE
[Bug] Video shows black screen

### ISSUE THREAD

**Issue by Harmonie666** [YTVanced/Vanced#1245]
There is a certain video that plays without problem with official YTM, but when I try to play the same video with Vanced Music, it's just stuck on endless loop, and doesn't play. I don't know if other videos are also affected by this.

Video proof:
https://streamable.com/8ytlr9

And this is the video:
https://music.youtube.com/watch?v=QhcJ0IndcUc&feature=share

**Android version**
Android 10

**Device**
ROG Phone 2

**Comment by Harmonie666** [comment]
/bump 

Issue still remains active.

**Comment by milindgoel15** [comment]
The music video you provided plays fine on the latest version of vanced music. Please recheck your issue on your end.

**Comment by Harmonie666** [comment]
Thanks for your input. Unfortunately the video doesn't play fine on my end.
I'm getting **black screen** instead of the video content showing:

https://user-images.githubusercontent.com/73917917/142893216-9ae535af-3f8a-48bf-88b6-37dec40dfc8a.mp4

**Comment by milindgoel15** [comment]
https://imgur.com/um5pjqi

Try reinstall. I will ask more members to reproduce.

**Comment by Harmonie666** [comment]
> https://imgur.com/um5pjqi
> 
> Try reinstall. I will ask more members to reproduce.

I have downloaded many playlists/albums, don't want to loose them by reinstalling :/

I think this is not the only music video where these odd things like black screen happen.

Same black screen I'm getting with this video:

https://music.youtube.com/watch?v=9HG3tbiyYwk&feature=share

**Comment by milindgoel15** [comment]
It's fine for everyone else too 

![Screenshot_20211122-221253.png](https://user-images.githubusercontent.com/45682747/142900832-a4266418-468d-477e-98c1-0f7e5a24ee9a.png)

> I have downloaded many playlists/albums, don't want to loose them by reinstalling 😕

Then I suppose we can't do anything about your issue. It's an issue from ur end.

**Comment by Harmonie666** [comment]
I get it. But could they please test it with the "Grey background for videos" feature aswell? 
So called "Zenmode". I would appreciate if they could turn that on, and test it again :)
![Screenshot_20211122-174541871 (1).png](https://user-images.githubusercontent.com/73917917/142901346-2093f8d2-1e8c-48c2-a0f1-289e37c8efff.png)

**Comment by milindgoel15** [comment]
Still plays fine for us.

**Comment by Harmonie666** [comment]
Hmm then I suppose it must be definitely on my end. Perhaps the next YTM Vanced update might "fix" it? Just a rhetorical question.
