### ISSUE TITLE
[Bug] Can't open in  HarmonyOS 

### ISSUE THREAD

**Issue by eveloki** [YTVanced/Vanced#1247]
**Bug description**
open app，is crash.

**Variant**
Non-Root

**Vanced version**
v16.29.39

**Android version**
Huawei HarmonyOS 2.0 (Android 10 api 29)
**Device**
Huawei mate 40 pro

**Steps to Reproduce**

1. Open the app
2. Down!
![Screenshot_20210906_001224_com vanced android youtube](https://user-images.githubusercontent.com/24290190/132134234-1fd7f5b6-da70-4998-b9ef-c9276e195aba.jpg)
（ps： i use xposed try to show ex message）

**Expected behavior**
 a week ago.my os is update ，vanced is not work.

help me.please.

**Comment by milindgoel15** [comment]
Try this: https://github.com/YTVanced/Vanced/issues/1183#issuecomment-899969280

**Comment by eveloki** [comment]
> 试试这个： [#1183 （评论）](https://github.com/YTVanced/Vanced/issues/1183#issuecomment-899969280)

no，i try，i also try to reinstall vanced，but is dont work

**Comment by milindgoel15** [comment]
Try reboot then reinstall
