### ISSUE TITLE
[Bug] Video glitch :/

### ISSUE THREAD

**Issue by Marikoscz** [YTVanced/Vanced#1248]
**Bug description**
When I play a video, the screen of that video moves to the top-right corner (so I see just 1/4 of that video) with a color weird glitch. Only what works is to restart the app. Then I can watch one or two videos without any problem until the glitch occurs. It is really boring to turn off and turn the app practically every time...

**Variant**
Non-Root

**Vanced version**
16.29.39

**Android version**
Android 8.0.0

**Device**
Sony Xperia XA1 G3112

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2. Play random video or just watch preview
(it is not every time, but sometimes if I want to play the third or tenth video, the glitch appears)

**Expected behavior**
I should be able to watch any video, any time without any annoying video glitch.

Here is an example how it looks like.
![Screenshot_20210905-173700](https://user-images.githubusercontent.com/88329663/132135687-fcca44ad-0bed-473a-a362-f52496928907.png)

**Comment by milindgoel15** [comment]
Device codecs issue
