### ISSUE TITLE
[Idea] Filter for shorter videos

### ISSUE THREAD

**Issue by NathanRuinsHisFuture** [YTVanced/Vanced#1249]
Just got vanced and I'm enjoying it so far, but I have one issue that carried over from the original YouTube app: way too many short video recommendations. I'm saying like less than 1 minute videos. Could there be a way to filter videos on the home page to only show videos with a minimum runtime of say, 5 minutes? I've already disabled YouTube shorts, but that doesn't filter regular short videos.

**Comment by sudo-nautilus** [comment]
**currently** you can't do that. YouTube's algorithm is a meme itself. 

> “*Videos < 1 minute are considered as 
> legendary, because they gain more 
> views in this period, and will continue
> till the very end of YouTube*”

But if you keep watching longer videos, YouTube will recommend lengthy videos

**Comment by milindgoel15** [comment]
Ask google lol
