### ISSUE TITLE
[Bug] Autorepeat of videos in playlists

### ISSUE THREAD

**Issue by ximmo** [YTVanced/Vanced#125]
**Bug description**
When you turn on autorepeat in playlists, it does not repeat the individual video. It does nothing.

**Variant**
NonRoot: Yes
Root: No

**Android version**
Android 10

**Device**
LG V40

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2. Click on a playlist
3. Click on a video
3. Turn on autorepeat

**Expected behavior**
The feature should repeat a video within a playlist, instead it just goes to the next.

**Comment by milindgoel15** [comment]
Please update to the latest vanced release if you haven't already. For the autorepeat function to work, the autoplay settings must be off. kindly see if it still happens with the above-suggested approach. We are closing this issue for now. Feel free to reopen if you have any queries.

**Comment by ximmo** [comment]
Hi,
the autorepeat works wonderfully on single videos, no question.
My issue is that it doesn't work on playlists. And it still doesn't.

**Comment by milindgoel15** [comment]
ok noted.

**Comment by milindgoel15** [comment]
![image](https://user-images.githubusercontent.com/45682747/116691848-0dd51d80-a9d9-11eb-8252-77a6de5821e1.png)
this should answer ur issue.

**Comment by milindgoel15** [comment]
Repeating the same song again from a playlist would defeat the purpose of playlist itself.

**Comment by milindgoel15** [comment]
Well, yes.

About that, it's unlikely to happen. Rest all depends on xfilefin.
