### ISSUE TITLE
Weird big square in the comment section

### ISSUE THREAD

**Issue by Mimicthis** [YTVanced/Vanced#1250]
Weird big square in the comment section appears when I type a comment and select it. 
![Screenshot_20210906-202202](https://user-images.githubusercontent.com/29215437/132257870-a54af07c-bf9c-4ef2-8f3f-7a772f3429c8.jpg)

**Comment by milindgoel15** [comment]
🤦‍♂️

Absolutely disgusting

**Comment by milindgoel15** [comment]
Duplicate of #1050
