### ISSUE TITLE
[Bug] Weird big square in the comment section

### ISSUE THREAD

**Issue by Mimicthis** [YTVanced/Vanced#1251]
**Bug description**
Weird big square in the comment section

**Variant**

Non-Root

**Vanced version**

V16.29.39

**Android version**

Android 11 

**Device**
Samsung Galaxy A52 5G 

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2. Click on a video
3. Open comment section
4. Type something and select it 

**Expected behavior**
A small bar like this should appear 

![Screenshot_20210906-221010_Chrome](https://user-images.githubusercontent.com/29215437/132258091-5dd56fed-1194-4291-b546-8b4d473aacbc.jpg)

**Comment by milindgoel15** [comment]
🤦‍♂️

Absolutely disgusting

**Comment by milindgoel15** [comment]
Duplicate of #1050

**Comment by milindgoel15** [comment]
Shame on you!

**Comment by Mimicthis** [comment]
Fix it?!

**Comment by milindgoel15** [comment]
Oh here we go again, 

go to play store > search YouTube > download. 

And start using your brain?

**Comment by Mimicthis** [comment]
It's not the same in the official app.
