### ISSUE TITLE
[Idea] Enhance Shorts Player

### ISSUE THREAD

**Issue by madgoatz** [YTVanced/Vanced#1252]
**Description**
I searched & didn't find a duplicate, but i remember months ago where I saw a request for shorts to play in the default player for normal videos, although i can't seem to find it again. 

The idea I now have keep the same shorts player and format but have the ability to (touch & hold while sliding left & right) to fast fwd or rewind the short  instead of having having to rewatch the short if i want to see something i missed as some shorts are really long.

**Comment by madgoatz** [comment]
#316 found it. not sure if its the same to u or not.

**Comment by milindgoel15** [comment]
It's not exactly same but I can make changes to that referenced issue to include your idea. Since both these issues are shorts related, it can be seen in under 1 issue rather than 2 separate issue. 

Are you okay with the change?

**Comment by madgoatz** [comment]
yes, i'm okay with the change...

**Comment by milindgoel15** [comment]
Alright, refer that issue from now on.
