### ISSUE TITLE
[Idea]/[Bug] Rewrite or Fix the current Link redirection Sytem

### ISSUE THREAD

**Issue by truehat** [YTVanced/Vanced#1254]
Currently when you click a Link in a comment section, description or discussion to an site like for example Reddit it:
Opens a "Run this once" window where you select Youtube
Opens the normal YouTube App
Opens ANOTHER "Run this once" only for this one to lead into Chrome
When in Chrome it opens ANOTHER GODDAMN "RUN THIS ONCE" Menu this time directing to the desired app

It's also worth noting that when clicking Video Links it redirects you to normal YouTube as well leaving you stranded on that App

**Comment by milindgoel15** [comment]
Not vanced bug, complain to Google.
