### ISSUE TITLE
[Bug] Vanced Music resets 'turn off Location based recommendations'


### ISSUE THREAD

**Issue by Harmonie666** [YTVanced/Vanced#1256]
I'm using Vanced Music Version 4.39.50 non-root on an Android 10. 

Disabling Location based recommendations toggle doesn't work. Always resets it to default (ON) as you can see below:

https://user-images.githubusercontent.com/73917917/132943087-36ab0c50-57e3-47b6-af96-e366fddfd0e5.mp4

**Comment by Harmonie666** [comment]
/unstale 

bug still exists.

**Comment by milindgoel15** [comment]
Oh why did I not see it happens due to microG? Closing this issue.
