### ISSUE TITLE
[Idea] Add support to download premium yt music videos on vanved and venced music

### ISSUE THREAD

**Issue by heartlog** [YTVanced/Vanced#1258]
## Description
Its better to add download support to download music in `vanced` and `vanced music` at least..
## Feature that requested by @heartlog
> Add music download support in yt V music 

> If possible then its better to add download for premium music and other videos on yt vanced directly

![Screenshot_20210913-123014](https://user-images.githubusercontent.com/76758776/133038152-63fcc7b8-6248-46c1-8edd-cab210878090.jpg)

**Comment by milindgoel15** [comment]
Go pay google to get youtube premium and learn to read!

**Comment by heartlog** [comment]
> Go pay google to get youtube premium and learn to read!

Thats not i am saying i mean like [Newpipe](https://github.com/TeamNewPipe/NewPipe/) Add something we call as `Download` option..

i know Its saying to pay to get access to premium..
Like The copy link button over video playback.

CiEhISBmZm8gdW95IGtjdUY=

**Comment by milindgoel15** [comment]
IT WON'T EVER HAPPEN!

damnit
