### ISSUE TITLE
[Bug] MicroG notifications doesn't work on Android 11

### ISSUE THREAD

**Issue by PilaScat** [YTVanced/Vanced#126]
**Bug description**
Notifications system doesn't work on OxygenOS 11 (based on Android 11)

**Variant**
NonRoot: Yes
Root: No
MicroG: 0.2.13.203916
Vance's: 15.40.37

**Android version**
Android 11

**Device**
OnePlus 8T

**Steps to Reproduce**
No steps, i followed the troubleshooting but nothing.
One of my friends with the same phone and os have the same problem

**Comment by milindgoel15** [comment]
Please recheck your issue on the latest versions. If it still happens, try to disable battery optimization using dontkillmyapp.com and make sure you follow the notification guide. We are closing this issue for now. Feel free to reopen if you have any queries.
