### ISSUE TITLE
[Bug] YouTube vanced wont install on android 11

### ISSUE THREAD

**Issue by haripari546** [YTVanced/Vanced#1261]
**Bug description**
INSTALL_FAILED_UPDATE_INCOMPATIBLE: Package com.vanced.android.youtube signatures do not match previously installed version; ignoring!

**Variant**
Non-Root

**Vanced version**
16.29.39

**Android version**
 Android 11 

**Device**
Realme 6i 

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the manager app
2. Click on install youtube vanced
3. then the error shows

**Expected behavior**
The app should install without showing any error 
![Screenshot_2021-09-14-00-49-26-78_664cadb1c148e0d90475ca0f494fbf83](https://user-images.githubusercontent.com/80844342/133181490-b4985601-aefd-4b37-8548-663b052b9bb1.jpg)

**Comment by milindgoel15** [comment]
duplicate of #330
