### ISSUE TITLE
[Idea] Vanced PiP Player

### ISSUE THREAD

**Issue by barbiefan** [YTVanced/Vanced#1265]
Hello and thank you for developing such an amazing app!

My issue is: Vanced by default opens (I'm guessing) a built-in android PiP player, which sucks.  
It would be great if you added your on PiP player or at least an option to open a video in external one.

For reference here's a video of a PiP player that is launched by Vanced:

https://user-images.githubusercontent.com/74291618/133600939-de921325-c721-4208-8c1e-ebc9410e388c.mp4

And this is a PiP that is launched by some random Vanced rip-off [(ProTube)](https://apkpure.com/p/free.video_tube.tube.news.video.stream.player.protube) (probably not safe)

https://user-images.githubusercontent.com/74291618/133601337-fca1d4c2-534a-467c-ae9b-848df11b100c.mp4

I assume their player is build in the app and Vanced uses android built-in one, correct me if I'm wrong

**Comment by milindgoel15** [comment]
one word: NOPE

**Comment by barbiefan** [comment]
Well, that's just sad
I didn't mention anything about original YouTube app or it's player
in the second video it's some shady app that opens a decent PiP player
