### ISSUE TITLE
[Bug] Shorts ads are appearing

### ISSUE THREAD

**Issue by PeterNjeim** [YTVanced/Vanced#1266]
**Bug description**
I was using the Shorts tab and as I was swiping down after a few videos, an ad showed up. Vanced should remove this ad. Note that for the past few weeks I've never seen an ad. Today is the first time I've seen an ad. Note that I rarely use the Shorts tab (TikTok cringe lol), but occasionally I check it out to see what my cringy generation is consuming.

**Variant**
Non-Root

**Vanced version**
v16.29.39

**Android version**
Android 11 

**Device**
Xiaomi Mi 9T Pro (Evolution X ROM (essentially Pixel AOSP))

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2. Click on the Shorts tab
3. Watch videos for a while, swiping down to new videos, read comments, etc. You'll see an ad at some point

**Expected behavior**
All ads should be blocked in YouTube Vanced.

![Screenshot_20210916-131556_YouTube_Vanced](https://user-images.githubusercontent.com/26418974/133648358-712cb7f3-cbe6-4a46-aea4-daaf4eb01785.png)

**Comment by milindgoel15** [comment]
Try clearing out app data. If ad still comes, they are geographical ads.

**Comment by PeterNjeim** [comment]
Should geographic ads not be blocked? I'm not sure why this is closed since no solution nor explanation was given.

**Comment by milindgoel15** [comment]
1. How do you propose the dev should block it when he can't get the ad in the first place?

2. Should the developer leave his personal life to give you special attention and fix bugs for you?


No, he doesn't work on vanced for a living. It's his personal hobby project and no one is asking for your money. If you are getting geo ads, keep patience and the bugs will get fixed sooner or later whenever dev is ready and free to do it!

**Comment by PeterNjeim** [comment]
Sir, I do not understand your hostility. Never have I ever demanded anything of you. In fact, the information you've provided in your latest message is quite good, and is all I could ever ask for.

You mention that geographic ads are a known issue and that a fix is being investigated. You also mention that you cannot reproduce the issue.

This is great to hear, I now fully understand.

However, what I cannot understand is you claiming I asked for special attention or anything of that sort. I take that as an insult.

I am a proud contributor to various open source projects, and I will not be lectured on how to comment on GitHub issues.

Allow me to share a story: I use a custom ROM for my phone, and on XDA I would report bugs to the developer. Every time the developer would get angry, and insult me telling me to stop "asking" for features. I would always kindly reply telling him that I am not demanding anything, merely reporting the existence of a bug. Whether or not the dev would like to investigate further is up to them, of course. Several months later, the dev locked the thread because they couldn't take all the "demands" (bug reports). On Telegram, we successfully convinced this dev that we are grateful for his work, and that we would never demand anything, or ask for special attention. The XDA thread was reopened and all is well now.

I see this a lot in the dev community, a non-contributor asks about something and hostility is immediately followed. Please, I beg of you to understand my view. When you responded to this issue, such little information was given, and the issue was closed. In my mind, I could not even believe the issue was closed, as neither a fix nor an affirmation that this issue is real was stated. To me, this issue was closed without reason.

For next time to avoid situations like this, please at least mention that you are aware of the issue. Otherwise, how can I know?

Thanks for your understanding, I'm always passive, never demanding, and grateful for your work. Please don't take this the wrong way :)
