### ISSUE TITLE
Youtube vanced app doesn't load any videos [Bug] replaceme

### ISSUE THREAD

**Issue by M0hammedImran** [YTVanced/Vanced#127]
**Bug description**
Both YouTube vanced and YouTube Music application does not load any video or music respectively.

**Variant**
NonRoot: Yes
Root: No

**Android version**
Android 10.0 

**Device**
Samsung Galaxy A70s

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app

**Expected behavior**
All the available videos load on the feed upon opening the application.

**Actual behavior**
it just show "You are offline page", but I am online and all other applications work fine. I get notifications and if I click on the notification shade it takes me to the video in the YouTube vanced app and plays the video but the suggestion section says "retry".

![Screenshot_20201029-013211](https://user-images.githubusercontent.com/52968617/97490244-96b9c080-1986-11eb-9219-674400168e7f.png)

**Comment by LucasAlfare** [comment]
Same here

**Comment by harrylim05** [comment]
Same. I solved it by downgrading older version.

**Comment by Vendicated** [comment]
Read the pinned issue.
