### ISSUE TITLE
[Idea] DLNA Airplay casting support

### ISSUE THREAD

**Issue by briantho** [YTVanced/Vanced#1276]
**Description**
Hi, I would like to request support for DLNA and Airplay cast support for both youtube vanced, and youtube music vanced. I am well aware that this would be a big job, but nevertheless i think it would we totally worth it, as well as really cool. this would do the same thing as chromecast, but using dlna or airplay instead of chromecast. Lots of older devices use dlna and airplay, AVR's TV's etc. WHat do you guys think? would this even be possible, or is this just a pipe dream? Please let me know. 

_Attach images/videos if possible. Also add any links to possible other applications with the said feature already implemented._

**Comment by milindgoel15** [comment]
Ask Google. We don't own YouTube
