### ISSUE TITLE
Notification Bar Color Bug

### ISSUE THREAD

**Issue by io-qar** [YTVanced/Vanced#1280]
**Bug description**
Notification bar turns completely black so there is no ability to look at notifications icons, time, data, etc. while playing a video in portrait mod (not fullscreen)

**Variant**
Non-Root

**Vanced version**
v16.29.39 - build - 01.54.00

**Android version**
Android 8.0.0

**Device**
LG V30

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2. Click on any video
3. Notification bar turns completely black

**Expected behavior**
It should be standart notification bar with black background color

**YT Vanced behavior**:

https://sun9-45.userapi.com/impg/ffqYGjkbYlcnnHTt9X5Dhgo_rc-xDy9z-cvrvA/_le4K4aB--w.jpg?size=1440x291&quality=96&sign=283c313a66a0647ab67ee23fd7618f85&type=album

**Expected behavior**:
https://sun9-28.userapi.com/impg/_-5OF4BQXcLc6vLQ-wX8WbdOB3OiqzFsM5Wtlg/EedrUwdtlrI.jpg?size=1440x318&quality=96&sign=31407baad09b3f90c6bc32131e1589c8&type=album

**Comment by milindgoel15** [comment]
stock Youtube issue.

**Comment by natedogith1** [comment]
I'm also seeing this issue (screenshots of Vanced and stock: https://imgur.com/a/tbvrrPn).

**Variant**
Non-Root

**Vanced version**
16.29.39 - build - 01.54.00

**Android version**
Android 11

**Device**
Galaxy S10

**Comment by MagnificentRaider** [comment]
The same exact issue (https://imgur.com/Cuj0LFN)

Variant
Non-Root

Vanced version
16.29.39 - build - 01.54.00

Android version
Android 11

Device
Galaxy S21 Ultra

**Comment by Ineman** [comment]
same issue. status bar is black.
 [https://imgur.com/a/nmn4vD8](https://imgur.com/a/nmn4vD8)

Variant
Non-Root

Vanced version
16.29.39 - build - 01.54.00

Android version
Android 11

Device
SM-T510

**Comment by fenchai23** [comment]
so it's a ROM issue?

**Comment by yvs2701** [comment]
Even I am facing the exact same issue...

Here's a small clip regarding the issue:
![ezgif-7-bf2afc28322a](https://user-images.githubusercontent.com/79207707/137880219-4b820603-abde-40f9-87dd-2cb8648762cd.gif)

Also the color of the icons and other texts in the status bar do change to white (as they were expected to) once you click on a comment to leave a reply.

> The issue doesn't actually persist on v16.30.34 so it might be possible that google changed something through server-side updates which now shows a black status bar for some users on 16.29.39. So please wait for future updates. There's nothing we can do about this issue.

Sure thanks for the update man !
___
Variant
Non-Root

Vanced version
16.29.39 - build - 01.54.00

Android version
Android 11

Device
Motorola Edge 20 fusion

**Comment by milindgoel15** [comment]
Fixed with v17 release
