### ISSUE TITLE
[Idea] Add more video quality option in the tablet

### ISSUE THREAD

**Issue by Winorlose4** [YTVanced/Vanced#1281]
**Description**

For the same video, there is no 1440p quality option in the tablet, but there is a 1440p quality option in the mobile phone.
![微信图片_20210923172206](https://user-images.githubusercontent.com/55885250/134483412-21404b40-132e-4daf-9c86-46d7299cb727.jpg)
![微信图片_20210923172214](https://user-images.githubusercontent.com/55885250/134483424-dde6aa75-b8a5-4c23-9cb0-1ba301a38d28.jpg)

_Attach images/videos if possible. Also add any links to possible other applications with the said feature already implemented._
https://www.youtube.com/watch?v=WMyAGVmiPWE&t=87s

**Comment by milindgoel15** [comment]
It's not upto vanced. The video quality has to be supported by your tablet in the first place and that's why google has all the controls what your tablet can support. If you wish to override it, go to vanced settings and change settings accordingly.
