### ISSUE TITLE
[Bug] Ads Found on Shorts.

### ISSUE THREAD

**Issue by rickninja765** [YTVanced/Vanced#1282]
**Bug description**
Ads Found After a long time.

**Variant**
Root

**Vanced version**
v16.16.38

**Android version**
Android 10

**Device**
Realme 3 Pro

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2. Click on 'shorts'
3. Slides throw shorts and boom you have ads.

**Expected behavior**

It's not supposed to have but still. Maybe New implement from YT side?

![Screenshot_2021-09-23-17-34-27-06.jpg](https://user-images.githubusercontent.com/61545131/134504001-e7529f94-93ff-4d61-9ab9-3542a497efd8.jpg)

**Comment by milindgoel15** [comment]
Closing this issue as OP is using old version (16.16.38). Please use latest version always (which currently is 16.29.39).
