### ISSUE TITLE
[Bug] Video loops after skipping a sponsor

### ISSUE THREAD

**Issue by BobIsMyManager** [YTVanced/Vanced#1284]
**Bug description**
On [this video](https://youtu.be/0SVN1-y1JwI) after the sponsor is skipped by sponsorblock, it loops the audio before the sponsor and loops the video after the sponsor

**Variant**
Non-Root

**Vanced version**
v16.29.39

**Android version**
Android 11 

**Device**
Redmi Note 9 Pro

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2. Make sure to have sponsorblock enabled to skip sponsors
3. Watch [this video](https://youtu.be/0SVN1-y1JwI)
4. Watch the bug occur after the sponsor is skipped

**Expected behavior**
For the video to play as normal after the sponsor segment

[example](https://cdn.kurwa.club/files/jpl5z.mp4)

**Comment by BobIsMyManager** [comment]
By the way it only happens on this video, and still happens after i restart the app

**Comment by milindgoel15** [comment]
Disable sponsorblock and check if it still loops.

**Comment by BobIsMyManager** [comment]
I disabled it and i no longer get this issue
