### ISSUE TITLE
[Bug] "Help & Feedback" removed in Vanced Music. Please add back.

### ISSUE THREAD

**Issue by Harmonie666** [YTVanced/Vanced#1286]
I'm using Vanced Music Version 4.39.50 on an non-root Android 10 phone.
I'm wondering why "Help & Feedback" is removed? Can it please be added back in an next update? 
Sometimes I use it to report bugs and contact YTM team.
Screenshot shows Help & Feedback on stock YTM.
![Screenshot_20210923-230815887 (1).png](https://user-images.githubusercontent.com/73917917/134584817-93d8f684-d005-4027-98cc-95d9a5874767.png)

**Comment by Harmonie666** [comment]
Unstale. Since #Willfix label has been added

**Comment by milindgoel15** [comment]
no need to comment unstale now. I have added willfix label for future releases and also for GitHub not to keep marking this as a stale issue.

**Comment by Harmonie666** [comment]
> no need to comment unstale now. I have added willfix label for future releases and also for GitHub not to keep marking this as a stale issue.

Alright sorry. I thought if a post gets marked with stale the devs might not see recognize it anymore.

**Comment by gghhkm** [comment]
> > no need to comment unstale now. I have added willfix label for future releases and also for GitHub not to keep marking this as a stale issue.
> 
> Alright sorry. I thought if a post gets marked with stale the devs might not recognize it anymore.

Stale is just to auto close old inactive issues that aren't marked so we don't have 1 thousand issues open of which most aren't relevant, aren't filled out properly, or are way out dated like before.
Once it's marked `willfix` the bot cannot close it.

**Comment by Harmonie666** [comment]
Thanks for clarifying that. I'm not too familiar with GitHub yet.

**Comment by gghhkm** [comment]
> Thanks for clarifying that. I'm not too familiar with GitHub yet. Are you part of the Vanced team?

Yes.

**Comment by milindgoel15** [comment]
Hi,

Since this feature is not even going to work on any non-root version of YouTube music Vanced, this option won't come back. (The non-root doesn't work due to another microG bug as it doesn't have required classes for it).
Hence, we are closing this issue. 

Use stock YouTube as always.

**Comment by Harmonie666** [comment]
Thats unfortunate. Thank you for clarifying.
