### ISSUE TITLE
new function

### ISSUE THREAD

**Issue by DJMH2403** [YTVanced/Vanced#1287]
![Screenshot_20210920_132956_com vanced android youtube_edit_190785485230784](https://user-images.githubusercontent.com/91309413/134629724-0fe42592-86e4-432a-8bdd-1fc12b3bc61e.jpg)
 
It would be great if the search bar can be put up or down, and that the labels can be hidden and the access bar can be hidden, or add more shortcuts etc ,.It would be more optimal and functional

**Comment by milindgoel15** [comment]
It's an app, not a joke.
