### ISSUE TITLE
[Bug] Sometimes a video doesn't play

### ISSUE THREAD

**Issue by Almaaa7** [YTVanced/Vanced#129]
**Bug description**
Sometimes a video glitches and only shows weird gradients. (The audio still plays)

**Variant**
NonRoot: Yes
Root: No

**Android version**
Android 10.0 - Q _(Custom ROM)_

**Device**
Samsung Galaxy Tab 4 10.1 (SM-T535)

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2. Click on a video

> Note: If I lock then unlock my device and click play, everything works again.

_Attach images/videos if possible. These can be helpful in solving the issue._
![IMG_20201028_215126](https://user-images.githubusercontent.com/70007627/97497678-2cdfed80-196b-11eb-825b-cccbf22c72ef.jpg)

**Comment by milindgoel15** [comment]
Seems more of a ROM bug. can you recheck if it happens on the latest version. We are closing this issue for now. Feel free to reopen this if it still happens

**Comment by Almaaa7** [comment]
Yes, this still happens with the latest version when I'm using Exoplayer v2 or VP9. If I use an older version with Exoplayer v1, this bug doesn't happen.

**Comment by milindgoel15** [comment]
Try switch to the default codec or set a custom codec which resolves it for you.
