### ISSUE TITLE
[Bug] Opening youtube vanced after update

### ISSUE THREAD

**Issue by ChaserEraserTheSquadGaming** [YTVanced/Vanced#1291]
**Bug description**
I'm having issues opening vanced after my phone got a software version update from android 10 to 11

**Variant**
Non-Root

**Vanced version**
Not sure of the exact version but I'm 99% sure its the newest version

**Android version**
Android 11 Upgrade from Android 10

**Device**
Samsung Galaxy A01

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app

**Expected behavior**
I would expect the app too open

**Comment by milindgoel15** [comment]
Elaborate your issue more

**Comment by ChaserEraserTheSquadGaming** [comment]
My phone got an update today making my phone go from android 10 to 11 and now I can't open youtube vanced

**Comment by milindgoel15** [comment]
Ahh so the update messed up your apps. Check #330 for solutions
