### ISSUE TITLE
[Bug] changing settings to set resolution breaks full screen

### ISSUE THREAD

**Issue by gonzalologorg** [YTVanced/Vanced#1293]
**Bug description**
If you set a custom resolution to play in Vanced settings outside automatic, your videos will exit full screen after you go full screen, having to swipe up twice.

**Variant**
Non-Root

**Vanced version**
v16.16.39 build 01.54.00

**Android version**
Android 10

**Device**
Samsung Galaxy s9

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2. Open Vanced settings and go to video settings
3. change quality to anything but automatic
4. 2/3 times you try to go fullscreen player will return to normal

**Expected behavior**
Full screen should stay as normal

**Comment by milindgoel15** [comment]
Closing this issue as OP is using old version.

**Comment by gonzalologorg** [comment]
My bad, i meant 16.29.39, not 16.16

**Comment by milindgoel15** [comment]
ROM issue
