### ISSUE TITLE
[Idea] Give us more controls over Playback speed

### ISSUE THREAD

**Issue by sadpentester** [YTVanced/Vanced#1294]
Description

YouTube web now has the option to manually set playback speed. This comes into use when I'm watching educational videos and want to get over a long lecture in a reasonable amount of time.. I usually prefer 1.2x and as it goes well with my Pomodoro sessions. With everything that Vanced already this, why not this ಠ‿ಠ

**Comment by milindgoel15** [comment]
Ask google to give source code to us then we might
