### ISSUE TITLE
[Question] Please bump Vanced Music base

### ISSUE THREAD

**Issue by Harmonie666** [YTVanced/Vanced#1295]
Currently the latest YTM base is **Version 4.46.50**

Vanced Music is stuck at _Version_ _4.39.50_

Can you please bump it to latest YTM base? Thanks alot!

**Comment by milindgoel15** [comment]
1 word: nope

**Comment by Harmonie666** [comment]
Why? Is this a difficult thing to do? New YTM base has some significant changes that I would like to see in Vanced Music.

**Comment by milindgoel15** [comment]
- Did you forget asking for updates is prohibited/not allowed?

- Did you forget xfile is busy with his personal life?

- Did you forget we don't work for living? It's a goddamn hobby! 

Vanced updates will come whenever devs wants to. Now please use some common sense next time and

**Comment by Harmonie666** [comment]
Please where is this this stated?
"Did you forget asking for updates is prohibited/not allowed?"

I don't know about such a rule, only that it makes you upset is all I know.
I can't see into your lives, I don't know what you guys are up to. I was just kindly asking to bump base, and you responded.
I hope devs will find time to do it.

**Comment by milindgoel15** [comment]
It's a general rule everywhere.  Go search google/xda/discord/telegram or any community where people work for free.
