### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by NelviusDMoon** [YTVanced/Vanced#1296]
**Bug description**
Youtube vanced keeps spamming notifications that I already dismissed it just keep coming back.

**Variant**
Non-Root/Root

**Vanced version**

16.29.39
**Android version**
Smart android

**Device**
Huawei Y7A

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
3. ....

**Expected behavior**
Replace me with a description of what you expected should happen and what happened instead.

_Attach images or videos or logcats in case of crashes if possible. These can be helpful in solving the issue._

Uploading SVID_20210927_070530_1.mp4…

**Comment by milindgoel15** [comment]
Duplicate of #1107

**Comment by DaniSheng** [comment]
Same problem, deactivating push notifications not working, looping push notifications, same notifications cleared early.

**Comment by NelviusDMoon** [comment]
I still want to have notifications but I don't want it to keep spamming
