### ISSUE TITLE
[Idea] Sign Split APKs for YouTube Vanced

### ISSUE THREAD

**Issue by lazerl0rd** [YTVanced/Vanced#1297]
**Description**
Users who wish to run the "root" variant of YouTube Vanced on unrooted firmware that doesn't include a YouTube application cannot install the package as the signatures of the Split APKs and the "Base" APK don't match up. Resigning isn't a solution, since Vanced will kill itself if it detects that it was resigned with a different key (and also makes updates a pain).

This doesn't currently apply to YouTube Vanced Music as it is a single APK, but if it ever becomes a Split APK in the future the above behaviour would be preferable.

**Comment by milindgoel15** [comment]
We ain't making signed apk from vanced splits. Use the non root version if installing root is not possible for you.

**Comment by KevinX8** [comment]
That's not how you install the root version, look at the vanced manager source code if you're interested in how it works. Also the root version has the signature checks intact in order to keep signing in via Google play services intact.

**Comment by lazerl0rd** [comment]
> That's not how you install the root version, look at the vanced manager source code if you're interested in how it works.

I know how Vanced Manager installs the "root" variant (downloads Stock, installs it, then overlays the modified base.apk in `/data/app` by bind mounting over it). It's just that the modified base.apk had differing signatures so I was wondering if you could just sign all the Split APKs to allow users in my situation to install such (as some of us did in the past).

I resigned all the APKs using Android's test key which does allow the application to insta run, but automatically closes itself to which seemed like signature verification you introduced, which is why I put forward this suggestion.

> Also the root version has the signature checks intact in order to keep signing in via Google play services intact.

That's a bummer. Thanks for an explanation as opposed to a swift decline. I guess this suggestion isn't worth it in that case, so I'll leave this issue be.

And as usual, thanks for Vanced.
