### ISSUE TITLE
[Bug] ERROR 502

### ISSUE THREAD

**Issue by Loganavter** [YTVanced/Vanced#1298]
**Bug description**
Error 502 on the latest version of the program on the Russian version. I can't send an ad segment. Everyone writes about this on 4pda

**Variant**
Non-Root

**Vanced version**
 v16.16.38

**Android version**
Android 11 

**Device**
Realme 6

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2. Click on 'adguard'
3. I choose the desired segment
4. I'm sending it
5. ERROR 502

**Expected behavior**
This segment will be sent to the server.
Error 502 comes out.

https://drive.google.com/file/d/1F3QkImBmscYjuMOcn9P9Zj3gGIuTGNlz/view?usp=sharing

**Comment by milindgoel15** [comment]
We don't support unofficial versions of vanced. Use official vanced then ask for support from us. 

Official vanced can only be found on vancedapp.com

**Comment by Loganavter** [comment]
> We don't support unofficial versions of vanced. Use official vanced then ask for support from us.
> 
> Official vanced can only be found on vancedapp.com

I use the official version that I downloaded on your website, but it is more convenient for me to discuss this program on 4pda

**Comment by milindgoel15** [comment]
I don't understand russian so I can't really what's exactly it says. Moreover, please make sure you are using official version from official sources only.(it's just a reminder again).

Please try reinstalling all the programs from scratch and check if the issue persists.

**Comment by Loganavter** [comment]
> I don't understand russian so I can't really what's exactly it says. Moreover, please make sure you are using official version from official sources only.(it's just a reminder again).
> 
> Please try reinstalling all the programs from scratch and check if the issue persists.

Check the operation of your servers where you store information about ad segments by marked users.

**Comment by milindgoel15** [comment]
We don't have any servers. 

The sponsorblock belongs to ajay and it's servers are managed by his team himself. Sponsorblock doesn't belong to vanced team and we have nothing to do with it. 

Please try the suggestion we suggested above.

**Comment by milindgoel15** [comment]
We have a new information. Their servers are having issues rn so please wait until they resolve it. 

Please note again, sponsorblock is not made vanced team.

You can check the status of their servers here:
https://status.sponsor.ajay.app/
