### ISSUE TITLE
[Bug] Ads back on searched videos. I searched a video but the top was a GTA promo ad 16.14.34

### ISSUE THREAD

**Issue by Schumacher7x** [YTVanced/Vanced#1299]
![Screenshot_20210927_192345_com vanced android youtube](https://user-images.githubusercontent.com/91496236/134967294-0775e39c-4fa9-491e-b90b-5ad5549191bf.jpg)

**Comment by milindgoel15** [comment]
Invalid issue because OP is using old version. Please use latest version (v16.29.39) before reporting any issue.
