### ISSUE TITLE
Cannot change Comment location on tablet installations

### ISSUE THREAD

**Issue by molohov** [YTVanced/Vanced#13]
Consequently, this breaks swipe controls. Occurs on tablets only.

Can reproduce on Nexus 9, Fire HD 10 2019 tablets
Cannot reproduce on Pixel 4 phone

**Comment by VancedOfficial** [comment]
You are not supposed to be able to change it on tablets. This option will be removed in the next version from tablet devices to make it clearer.

**Comment by molohov** [comment]
Will removing the option also fix swipe controls?

**Comment by VancedOfficial** [comment]
Removing the option won't but I've fixed the swipe features so they should work in the next version even for tablets.
