### ISSUE TITLE
[Bug] replaceme

### ISSUE THREAD

**Issue by Masalale** [YTVanced/Vanced#130]
**Bug description**
Replace me with a clear and detailed description of the bug.

**Variant**
NonRoot: Yes
Root: No

**Android version**
Android 10

**Device**
Xiaomi Redmi Note 8 Pro

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
3. ....

**Expected behavior**
It's saying Network error whilst trying to connect my account, I've tried reinstalling the app and clear all data but the problem still persists.

**Comment by gghhkm** [comment]
[Official Vanced Discord Invitation](https://discord.gg/rgwbXEaUCb)
[Message Link](https://discord.com/channels/328493314485518336/358967876193091584/809525073903616022)
