### ISSUE TITLE
[Bug] Notifications page returns glitched, shows white page when logged in

### ISSUE THREAD

**Issue by canerolu2019** [YTVanced/Vanced#1300]
**Bug description**
Today some glitch happened in the version 14.21.54. Whenever i press the notifications page when im logged in the screen shows blank and theres no writing whatsoever in the notifications page.

**Variant**
non root

**Vanced version**
14.21.54

**Android version**
Android 9

**Device**
Samsung Galaxy A6 Plus

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app.
2. Click on notifications.
3. Shows blank page when logged in.

**Expected behavior**
Notifications page always crashes
![Screenshot_20210928-142832_YouTube Vanced](https://user-images.githubusercontent.com/57676524/135079029-307bcfe9-bd08-4e70-86a7-6154d9c63289.jpg)

**Comment by milindgoel15** [comment]
We don't provide support for old version or its bugs. Use latest version if you want support here. FYI, the latest version is v16.29.39.

**Comment by canerolu2019** [comment]
> Yes, always use the latest version before reporting any bugs. Whenever new version comes for any software or service, the old one automatically deprecates. It's just not vanced thing.
> 
> > The support is available only for latest version since im new to this vanced stuff

i see. thx for clarification.
