### ISSUE TITLE
[Idea] Play Shorts as Videos

### ISSUE THREAD

**Issue by Oofman1062** [YTVanced/Vanced#1302]
**Description**
Keep the original shorts menu (The one that appears in recommendations/home) but when ever you click on one of the shorts it opens as a normal video.

For the Shorts Button (The button the the bottom):
Have the Shorts play as Videos while still autoplaying the shorts you would be watching in the regular shorts button.
(or remove it or just have it play regular shorts)

**Comment by madgoatz** [comment]
duplicate or #316
