### ISSUE TITLE
[Bug] Can't cast to WIFI speakers (not due to Google services issue)

### ISSUE THREAD

**Issue by udah1** [YTVanced/Vanced#1307]
**Bug description**
When trying to cast to wifi SPEAKER, getting error that need to upgrade to premium to cast

**Variant**
Non-Root

**Vanced version**
v4.39.50 

**Android version**
Android 11 

**Device**
Samsung Galaxy S21 plus

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2. Click on cast button
3. Select wifi SPEAKER

**Expected behavior**
Should cast

![Screenshot_20211002-201022_YouTube Music](https://user-images.githubusercontent.com/3235731/135726442-f97f4832-2d36-4f51-83ff-7f3def4b5f26.jpg)
![Screenshot_20211001-174621_YouTube Music](https://user-images.githubusercontent.com/3235731/135726447-cd90b007-7e37-4575-811a-df065f43a921.jpg)

**Comment by milindgoel15** [comment]
So??


Vanced ≠ YouTube premium. Subscribe to YouTube premium if you need premium features. Vanced won't bring such features for you!!!

**Comment by udah1** [comment]
Thanks for the pleasant reply 🙄
