### ISSUE TITLE
[Idea] Please add a way to link a tv code with youtube music

### ISSUE THREAD

**Issue by briantho** [YTVanced/Vanced#1308]
**Description**
Hi, I am looking for a way to add a tv code for youtube music yanced. Could this feature be added? The primary reason I want/need this is so i can "cast" to smarttubenext from youtube music vanced. Currently the only way smarttubenext can cast is via a tv code. Since youtube music only supports discovery, I cannot cast to it. Can you please add this feature to youtube music vanced? Thanks

**Comment by milindgoel15** [comment]
Ask google for it

**Comment by briantho** [comment]
Wow, ok.... guess that's your answer for everything. I get that this is a youtube music bug/feature, and that youtube music vanced really considered a side project. I don't think google would do anything about it even if i asked them. I just thought it'd be a possible vanced feature to add. I'm primary looking for a way to have youtube music ad free on a tv. That's my goal. Since youtube music vanced needs a touchscreen, and casting means ads, and bluetooth is a no-go for me, i guess it's back to the drawing board.

**Comment by milindgoel15** [comment]
How do you expect us to add such things when we don't have the source code in the first place? We don't own youtube or a music app. 

Moreover, Vanced is not a Youtube premium and it will never be one. (In case if you are trying to add that vanced will add ad-blocking while casting)

**Comment by briantho** [comment]
I understand. Sorry if i came off as rude or something, I was just trying to understand why this feature could not be added. Anyway, in regards to casting I know from experience that casting to a chromecast has ads, and i understand that there isn't much that can be done about that. My second question is why not create a youtube vanced for android tv with casting? That would solve so many problems, since other projects like smarttubenext don't offer real casting support. Is this something that could be done, or am I back to the drawing board? Sorry again, and hopefully you take my consideration about a android tv app seriously.

**Comment by milindgoel15** [comment]
That ain't happening either.
