### ISSUE TITLE
[Bug] If you are facing ads on vanced, report them here!!

### ISSUE THREAD

**Issue by Oofman1062** [YTVanced/Vanced#1314]
**Bug description**
Pretty simple, I got a ad under a video (the one that shows up in horizontal)

**Variant**
Non-Root

**Vanced version**
16.29.39

**Android version**
Android 11 OneUI 3.1

**Device**
Samsung Galaxy M31

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app.
2. Click a video.
3. Might be a ad there

**Expected behavior**
No ads under videos.

![Screenshot_20211004-185933~2](https://user-images.githubusercontent.com/81549767/135936379-11ce57e9-1ad4-4482-8dc2-4ab7a6d003ea.png)

**Comment by milindgoel15** [comment]
Clear cache and see again

**Comment by madgoatz** [comment]
@milindgoel15 

using the latest version v16.29.39 I got the same type of ad as indicated above... watched a few videos to see if I could get ads again to do the logcat, but only when I searched "Greek Mythology" and watched videos from a channel called "See U in History / Mythology" I would get the ads (probably coincidence)... got the ads on the root variant but haven't gotten any on the non-root variant... btw, only sometimes I would get the ads... logcat is attached below...

![index](https://user-images.githubusercontent.com/88365986/137613883-497c26a0-e22c-4191-ab28-a3664ab10f31.jpg)

[logcat_10-17-2021_00-48-35.txt](https://github.com/YTVanced/Vanced/files/7358903/logcat_10-17-2021_00-48-35.txt)

**Comment by madgoatz** [comment]
> Reply from xfile: There's not a single "Template" keyword. So either the debug logs weren't enabled or the log is somehow messed up. There's a lot of empty lines in there and that doesn't happen when you use adb to take it so I'm guessing the log is taken with some app which doesn't have permissions to log everything.


![unnamed2](https://user-images.githubusercontent.com/88365986/137631876-8f529c73-a40c-498a-ad1b-42d1ebb07546.png)
not sure what is meant by debug logs... google wasn't helpful and this was the only thing I found...

Yeah I used one of the apps listed in vanced guidelines to generate the log...

I just used adb to get the logs, however there was not any "Template" keyword in the log file... so i don't know...

**Comment by rizqiimani** [comment]
Got another log, now with Vanced Debug enabled. Catching the log using MatLog. Hope this will help
https://www12.zippyshare.com/v/u6AIOxHj/file.html

**Comment by bobtheburgerflipper** [comment]
Bug description
Being plagued with ads.

Variant
Root

Vanced version
16.29.39

Android version
Android 11 Oxygen OS 11.0.8.8.IN11BA

Device
Oneplus 8 Pro

Steps to reproduce the error:
Open a video and sometimes theres an ad under the comment section.

Expected behavior
No ads.

![Screenshot_20211109-205356](https://user-images.githubusercontent.com/25465514/140987741-8ef9d67f-1fff-4b7a-9539-373c8ce6388f.jpg)

logcat [https://www.toptal.com/developers/hastebin/pefoqaliwu.yaml](url)

**Comment by milindgoel15** [comment]
> logcat [https://www.toptal.com/developers/hastebin/pefoqaliwu.yaml](url)

Your link goes nowwhere. Please reupload it.

**Comment by bobtheburgerflipper** [comment]
> > logcat [https://www.toptal.com/developers/hastebin/pefoqaliwu.yaml](url)
> 
> Your link goes nowwhere. Please reupload it. Edit: seems i had to just extract the end part of the link. Please retake the logcat with debug mode enabled., the logcat doesn't contain anything to what we look for.

I had debug mode enabled in Settings>Vanced Settings>Debug Mode. What else should I enable?

**Comment by milindgoel15** [comment]
> I had debug mode enabled in Settings>Vanced Settings>Debug Mode. What else should I enable?

Then ig you would have to retake logcat just after you see ads using adb( for once try catlog reader from play store as well)

**Comment by bobtheburgerflipper** [comment]
https://www.toptal.com/developers/hastebin/ifasovurib.pl

Okay I took this with logcat extreme. Hope this is useful.

**Comment by luftw** [comment]
Here's my report about the bug i encounter in yt vanced i hope it will be reviewed. Thanks for your creation devs. Keep it up. 

![Screenshot_2021-11-12-08-17-20-36](https://user-images.githubusercontent.com/94148696/141389210-a096faa5-d11a-484b-a6e6-084f6605c577.jpg)
![Screenshot_2021-11-12-08-16-55-71](https://user-images.githubusercontent.com/94148696/141389233-25700854-f79c-459a-952d-68107e494289.jpg)


[Log_2021-11-12_08-24-26.txt](https://github.com/YTVanced/Vanced/files/7524062/Log_2021-11-12_08-24-26.txt)

**Comment by milindgoel15** [comment]
> Here's my report about the bug i encounter in yt vanced i hope it will be reviewed.

There's not a single instance of log regarding advertisements in this logcat. Please retake(keep debug logs enabled before in vanced settings).

**Comment by luftw** [comment]
> > Here's my report about the bug i encounter in yt vanced i hope it will be reviewed.
> 
> There's not a single instance of log regarding advertisements in this logcat. Please retake(keep debug logs enabled before in vanced settings).

Okay copy that please check this out I've also enable the debug mode in vanced

[Log_2021-11-12_23-02-37.txt](https://github.com/YTVanced/Vanced/files/7528512/Log_2021-11-12_23-02-37.txt)

**Comment by KyrumX** [comment]
Just to add to this, I'm getting the same ads under Home. Toggling ''Comments location (Alpha)" to on in Vanced settings=>Layout Setting it seems to fix it. (Thanks /u/Apprehensive_Way4051 on reddit)

**Comment by thiswastheonlyavailableusername** [comment]
Bug description
I get home ads. Tried emptying the cache. 

Variant
Non-Root

Vanced version
16.29.39

Android version
Android 11

Device
Nokia 3.4

**Comment by bobtheburgerflipper** [comment]
> > I had debug mode enabled in Settings>Vanced Settings>Debug Mode. What else should I enable?
> 
> Then ig you would have to retake logcat just after you see ads using adb( for once try catlog reader from play store as well)

I found the host that is causing these ads. it's yt3.ggpht.com. Blocking it completely deletes the ads.

**Comment by milindgoel15** [comment]
Cool

**Comment by natewu** [comment]
I'm also seeing ads, on root version

**Comment by milindgoel15** [comment]
> I'm also seeing ads, on root version

Follow what @bobtheburgerflipper did

**Comment by JayaKrishnaKruthick** [comment]
Bug Description: Ads under video

Varient: root

Vanced version: 16.29.39

Android Version: 11 (MIUI 12.5)

Device: MI 11X

Tried to grab logs using Logcat Extreme 
[Log_2021-12-01_19-37-57.txt](https://github.com/YTVanced/Vanced/files/7635346/Log_2021-12-01_19-37-57.txt)

**Comment by ProjectPhysX** [comment]
![Screenshot_20211215-062652](https://user-images.githubusercontent.com/90851087/146128773-45c134f1-0e71-4620-9323-5a457304e228.jpg)
Disgusting Minecraft ad popup when launching the app. Sometimes I get popups for YouTube Music or YouTube Premium too.

**Comment by TXPer** [comment]
I have the same problem with ads.
[vanaced_ads.txt](https://github.com/YTVanced/Vanced/files/7718414/vanaced_ads.txt)
![image](https://user-images.githubusercontent.com/94923281/146169258-c9265735-0e16-4b3c-8324-5a5b8121a733.png)

**Comment by ProjectPhysX** [comment]
![Screenshot_20211219-172558](https://user-images.githubusercontent.com/90851087/146682754-56957ad2-6034-4953-bae1-db07f650d111.jpg)
There is a YouTube Premium App when clicking the download video button.

**Comment by TheAmazingBen100** [comment]
Who told you that vanced is the same as premium?
Vanced will NEVER offer any kind of premium service such as downloads, otherwise Google would take Vanced down. If you want downloads, then buy premium.

**Comment by tankaras** [comment]
![Screenshot_2021-12-20-21-53-36-249_com google android youtube](https://user-images.githubusercontent.com/26869897/146818555-2cf87175-60dd-4980-85c2-cf3daccbc81e.jpg)

**Comment by m-scha1337** [comment]
Bringing something completely new to the table it seems!
<hr>

**Bug description**
As mentioned above. A billion times already

**Variant**
Root, using magisk and VancedManager (2.6.2 [Crimson])

**Vanced version**
16.29.39

**Android version**
Android 10, OxygenOS 10.0.11GM21BA

**Device**
OnePlus 7 Pro


Attached I have the raw logcat but also a curated version, containing only Debug level events with the `Template` tag and YTVanced' PID at the time using this regex `/.*(19863)\s(\d{5})\s(D Template: ).*/gm`. Enjoy.
<hr>

Full Log: [5e6be885a558421e098d0ca4dbbca54eb9d06864.txt](https://github.com/YTVanced/Vanced/files/7752678/5e6be885a558421e098d0ca4dbbca54eb9d06864.txt)
Filtered Log: [curated_5e6be885a558421e098d0ca4dbbca54eb9d06864.txt](https://github.com/YTVanced/Vanced/files/7752674/curated_5e6be885a558421e098d0ca4dbbca54eb9d06864.txt)

**Comment by ProjectPhysX** [comment]
![Screenshot_20211222-074917](https://user-images.githubusercontent.com/90851087/147048393-2b2e421d-a8b6-4590-9a70-52fc43967dbb.jpg)
YouTube Shorts ad on the start page in Version 16.29.39

**Comment by VarunBanka** [comment]
> **Bug description** Pretty simple, I got a ad under a video (the one that shows up in horizontal)
> 
> **Variant** Non-Root
> 
> **Vanced version** 16.29.39
> 
> **Android version** Android 11 OneUI 3.1
> 
> **Device** Samsung Galaxy M31
> 
> **Steps to Reproduce** Steps to reproduce the error:
> 
> 1. Open the app.
> 2. Click a video.
> 3. Might be a ad there
> 
> **Expected behavior** No ads under videos.
> 
> ![Screenshot_20211004-185933~2](https://user-images.githubusercontent.com/81549767/135936379-11ce57e9-1ad4-4482-8dc2-4ab7a6d003ea.png)

Same issue here

**Comment by ProjectPhysX** [comment]
Got this ad popping up and covering the entire screen in version 16.29.39:
![Screenshot_20220107-081454](https://user-images.githubusercontent.com/90851087/148506527-a78dbcff-5026-4958-b3a4-d95daa437150.jpg)

**Comment by milindgoel15** [comment]
It's actually not an ad but ok

**Comment by ProjectPhysX** [comment]
Unwanted full screen popup advertising for YouTube shorts crap. I think this classifies as an ad. Vanced version 16.29.39.
![Screenshot_20220110-153745](https://user-images.githubusercontent.com/90851087/148784071-f988433e-1ad3-4c52-843a-c9e3affc3dbb.jpg)

**Comment by TheAmazingBen100** [comment]
> Unwanted full screen popup advertising for YouTube shorts crap. I think this classifies as an ad. Vanced version 16.29.39. ![Screenshot_20220110-153745](https://user-images.githubusercontent.com/90851087/148784071-f988433e-1ad3-4c52-843a-c9e3affc3dbb.jpg)

It's a server side thing from Google, Vanced can't really do anything about that

**Comment by VarunBanka** [comment]
It's not a proper ad

**Comment by m-scha1337** [comment]
@ProjectPhysX you've commented 4 times now about the same thing.. These full screen popups about YT Premium have never been considered to be ads and they have never been blocked by YTV before.. Stop asking about it.

**Comment by VerdantFable74** [comment]
![Screenshot_20220120-050328](https://user-images.githubusercontent.com/98074992/150276758-d7e0bcb4-094e-4ada-9834-47c039457b3b.jpg)
Unwanted adverts apperaring on home page. 
Variant: Non-Root
Vanced Version 16.29.39
Android 11 One UI 3.1
Samsung Galaxy A41

Issue appears about 1/3 of the time. It is often just one ad at the top of the home screen, although scrolling down may cause more to appear. Only happens on the home page. The ads vary each time although some ads say the same thing. All ads are blacked out.

**Comment by Vianns** [comment]
Hello !

Having ads displayed like other users in this issue.

Bug description:
Ads are displayed (not at every app launch) on the main video list.

Have you read vanced guides already? (YES/No)
Yes

Variant:
Non-Root

Vanced version:
YT Vanced ver. 16.29.39

Link used to download vanced:
https://github.com/YTVanced/VancedManager/releases/latest/download/manager.apk

Android version:
11 RKQ1.200826.002

Device:
Poco F3

Steps to Reproduce
1- Open the app
2- See that ads are displayed on the main video list.

Expected behaviour:
When opening the app, I expect no ads to be displayed anywhere in the application.

Logcat log: https://www.toptal.com/developers/hastebin/nupobaduge.yaml

Thanks !

**Comment by jwhitlow45** [comment]
Bug description
Started ads on YouTube shorts

Variant
Root

Vanced version
16.29.39

Android version
LineageOS 18.1 (Android 11)

Device
OnePlus 6T

Steps to reproduce the error:
View YouTube shorts and scroll down a few videos https://user-images.githubusercontent.com/46979583/153530791-56fe7abc-4405-46cd-95e3-fec5969e6b42.png

**Comment by Shadow-Hunt3r** [comment]
[logcat.txt](https://github.com/YTVanced/Vanced/files/8055653/logcat.txt)
My attempt of grabbing logcat on youtube stories, it does show up i sat for a while trying to get one to pop up, not as many as other ads mentioned by other users, could be factor of youtube getting new ad links to use if im not mistaken, havent seen/heard any ads on video tho which is still good on that note

Variant: Non-Root
Vanced ver.: 16.29.39
Android Ver.: Android 12 Build SQ1A.220105.002
Device: Pixel 4a

**Comment by milindgoel15** [comment]
Patched with v17 release
