### ISSUE TITLE
Video controls in the drop-down notifications missing.

### ISSUE THREAD

**Issue by Mesum-Hussain** [YTVanced/Vanced#1315]
I recently changed my phone and downloaded YouTube Vanced in my new phone. In my previous phone when I used to press home button while a video is playing, the video used to continue playing in the background and a video controls panel used to show in the drop-down notifications section. But in my new phone the video is still playing in the background but the video controls panel is not appearing in the drop-down notifications. It's becoming a little inconvenient listening to the videos while I do something else. I am very used to that feature and I am not sure if it is removed or it's a bug. Please do something about it. My phone is Redmi 6 pro, for context.

Thanks.

**Comment by milindgoel15** [comment]
It's an issue with MIUI. We can't do anything about it.
