### ISSUE TITLE
[Bug] replaceme

### ISSUE THREAD

**Issue by Wkwkland45** [YTVanced/Vanced#1317]
**Bug description**
Replace me with a clear and detailed description of the bug.

**Variant**
Non-Root/Root

**Vanced version**
Replace me with the exact version of vanced you are using. It is mandatory to report issues from the latest available versions only. For example, v16.16.38

**Android version**
Replace me with the version of Android your device have. For example, Android 11 

**Device**
Replace with the name of the device on which you faced the bug. For example, Samsung Galaxy S8

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
3. I have an issue when I want to download offline videos on YouTube, I can't download videos with 720p resolution and can't open the links on YouTube vanced

The cell phone that I'm currently using is: XIAOMI REDMI NOTE 10 android 11, miui 12.5.1 no root
![Screenshot_2021-10-08-01-12-54-067_com vanced android youtube](https://user-images.githubusercontent.com/92117613/136441471-9595e9b3-8a0f-41c0-85df-1bde1086ac4b.jpg)
![Screenshot_2021-10-08-01-13-29-819_com vanced android youtube](https://user-images.githubusercontent.com/92117613/136441483-1ccc5c43-35d5-4553-9a32-b8d0c0fcd914.jpg)

**Expected behavior**
Replace me with a description of what you expected should happen and what happened instead.

_Attach images or videos or logcats in case of crashes if possible. These can be helpful in solving the issue._

**Comment by milindgoel15** [comment]
- Buy YouTube premium because vanced is not YouTube premium and it will never be.
- For fixing links not opening, either disable stock YouTube app or change app defaults.
