### ISSUE TITLE
[Bug] Cant install root variant

### ISSUE THREAD

**Issue by Developer-Mike** [YTVanced/Vanced#1321]
**Bug description**
When I want to install it this error pops up: avc: denied {read } for scontext=u:r:system_server:s0 tcontext=u:object r:sdcardfs:s0 tclass=file permissive=0 System server has no access to read file context u:object_r:sdcardfs:s0 (from path /data/local/tmp/ split config.arm64_V8a.apk, context u:r:system_server:s0) Error: Unable to open file: /data/local/tmp/ split_config.arm64_V8a.apk

**Variant**
Root

**Vanced version**
v16.29.39

**Android version**
Android 11 

**Device**
Mi 9T pro. ROM: Pixel Experience

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2. Choose root variant
3. Install it. 

Language: DE
Theme: Light + Dark
YouTube app not preinstalled

**Expected behavior**
That it installs YT Vanced.

**Comment by milindgoel15** [comment]
Downgrade vanced manager to an older version using [this link](https://github.com/YTVanced/VancedManager/releases/download/v2.6.0/manager.apk). Don't use the latest release v2.6.1

**Comment by milindgoel15** [comment]
Duplicate of https://github.com/YTVanced/VancedManager/issues/697
