### ISSUE TITLE
Videos keep playing

### ISSUE THREAD

**Issue by Evel270** [YTVanced/Vanced#1323]
I have the problem even after reinstallation that videos that I posted automatically start playing again NH and even the other way around sometimes.

**Comment by milindgoel15** [comment]
Could you elaborate please?

**Comment by Evel270** [comment]
I normally watch YouTube and pause the video and in probably 1/10 cases the video resumes and just plays.

**Comment by gghhkm** [comment]
Did you have anything connected at the time, such as a Bluetooth device or Wired ear buds?

**Comment by Evel270** [comment]
No I have this problem for a long time with and without Bluetooth connection

**Comment by gghhkm** [comment]
Did it appear after a system update?

**Comment by Evel270** [comment]
No maybe it's my os itself its on my Xiaomi 11 ultra

**Comment by Evel270** [comment]
Ok I will try that any other possible fix?
