### ISSUE TITLE
[Bug] 60fps video lag

### ISSUE THREAD

**Issue by GKid94** [YTVanced/Vanced#1325]
**Bug description**
60 fps videos are lagging on my Xiaomi Redmi 9 4GB phone and the stream chat won't show in fullscreen

**Variant**
Non-Root

**Vanced version**
16.29.39

**Android version**
Android 11 

**Device**
Xiaomi Redmi 9 4GB

**Steps to Reproduce**
Open a 60fps video and select a 60fps quality and open a stream and enable chat when in fullscreen

**Expected behavior**
For the videos and chat to work normally

![Screenshot_2021-10-10-18-43-55-613_com android settings](https://user-images.githubusercontent.com/18757054/136715018-5dca6499-7f93-40d8-be1f-48cc29704db1.jpg)
![Screenshot_2021-10-10-18-43-57-639_com android settings](https://user-images.githubusercontent.com/18757054/136715020-0f1ad601-aa2b-46a1-93a3-5012852f866e.jpg)
![Screenshot_2021-10-11-00-33-09-269_com vanced manager](https://user-images.githubusercontent.com/18757054/136715042-bb4697af-81da-441c-96cd-c139d4cbb560.jpg)

**Comment by GiFRforever** [comment]
I have similar issue with 60 fps playback. From my findings, it's due to exo2 in newer versions of YouTube. In older ones, you could force exo, but now it's not supported.
Usually going few seconds back or selecting lower than higher resolution fixes the issue, but sometimes it just won't play nice and smoothly.

**Comment by milindgoel15** [comment]
Not a vanced issue.

**Comment by DragonX1301** [comment]
> **Bug description**
> 60 fps videos are lagging on my Xiaomi Redmi 9 4GB phone and the stream chat won't show in fullscreen
> 
> **Variant**
> Non-Root
> 
> **Vanced version**
> 16.29.39
> 
> **Android version**
> Android 11 
> 
> **Device**
> Xiaomi Redmi 9 4GB
> 
> **Steps to Reproduce**
> Open a 60fps video and select a 60fps quality and open a stream and enable chat when in fullscreen
> 
> **Expected behavior**
> For the videos and chat to work normally
> 
> ![Screenshot_2021-10-10-18-43-55-613_com android settings](https://user-images.githubusercontent.com/18757054/136715018-5dca6499-7f93-40d8-be1f-48cc29704db1.jpg)
> ![Screenshot_2021-10-10-18-43-57-639_com android settings](https://user-images.githubusercontent.com/18757054/136715020-0f1ad601-aa2b-46a1-93a3-5012852f866e.jpg)
> ![Screenshot_2021-10-11-00-33-09-269_com vanced manager](https://user-images.githubusercontent.com/18757054/136715042-bb4697af-81da-441c-96cd-c139d4cbb560.jpg)
>
