### ISSUE TITLE
[Idea] Please add support for h264ify 

### ISSUE THREAD

**Issue by shockergit** [YTVanced/Vanced#1327]
h264 codecs help to reduce the battery consuption please add support for this in vanced.

https://github.com/erkserkserks/h264ify/pull/66

https://addons.mozilla.org/en-US/firefox/addon/h264ify-embed-fix/?utm_source=addons.mozilla.org&utm_medium=referral&utm_content=search

**Comment by Invictaz** [comment]
Second this. Allow h264 for older devices

**Comment by milindgoel15** [comment]
Extensions don't work on YouTube android clients(browser is a whole different scenario). If they have any API, then you can provide that. Otherwise not possible
