### ISSUE TITLE
[Idea] Replace feature Picture in Picture into Display over other apps

### ISSUE THREAD

**Issue by cvphat4796** [YTVanced/Vanced#133]
With Picture in Picture, The mini window of PiP is very small. I can not resize mini window, can not seek or playback video. 
So I want to have a button in detail screen of video. 
When we touch the button. A mini window will stream video.
In this window we should have some feature as: resize, seek and playback 5s, select quality or caption.

Many thanks Vanced team!

**Comment by LeetPtato** [comment]
that would require making from scratch a custom pip window since the YouTube pip is dependant on your ROM, while it would be useful to have a more dynamic, stable pip implemented in vanced itself, the current devs will probably not bother implementing this due to the effort it would require

**Comment by cvphat4796** [comment]
@LeetPtato  Yeah, I see. 
But I hope It will be in the plan of Vanced team and will be implemented in the future.
PiP is so bad but I still usually has to use it 😩
