### ISSUE TITLE
[Bug] YT Vanced crashing after adding account to it

### ISSUE THREAD

**Issue by JustFragger** [YTVanced/Vanced#1331]
**Bug description**
So I just installed Youtube Vanced on my phone, but after adding account app just crash instantly. I have been searching through the issue on Github also and Discord in pinned messages, but nothing worked ... 

So tried:
Uninstalling microG (also removed account from it) and Youtube Vanced. Then installing first microG, after that installed YT Vanced. Tried logging again but same, crash instantly. Tried looking on Issue (https://github.com/YTVanced/Vanced/issues/687) but did not worked for me.

**Variant**
Non-Root

**Vanced version**
Using latest version (16.29.39)

**Android version**
8.1.0 (Oreo)

**Device**
Meizu M8 (https://www.devicespecifications.com/en/model/a5f84e2f)

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2. Sign In, enter email and password
3. Crashes

**Expected behavior**
Be signed in and use app normally.

Attached logcat created through adb. Or here https://hastebin.com/vaqiwuzuge.yaml
[logcat.txt](https://github.com/YTVanced/Vanced/files/7330871/logcat.txt)

**Comment by TXPer** [comment]
> **Bug description** So I just installed Youtube Vanced on my phone, but after adding account app just crash instantly. I have been searching through the issue on Github also and Discord in pinned messages, but nothing worked ...
> 
> So tried: Uninstalling microG (also removed account from it) and Youtube Vanced. Then installing first microG, after that installed YT Vanced. Tried logging again but same, crash instantly. Tried looking on Issue (#687) but did not worked for me.
> 
> **Variant** Non-Root
> 
> **Vanced version** Using latest version (16.29.39)
> 
> **Android version** 8.1.0 (Oreo)
> 
> **Device** Meizu M8 (https://www.devicespecifications.com/en/model/a5f84e2f)
> 
> **Steps to Reproduce** Steps to reproduce the error:
> 
> 1. Open the app
> 2. Sign In, enter email and password
> 3. Crashes
> 
> **Expected behavior** Be signed in and use app normally.
> 
> Attached logcat created through adb. Or here https://hastebin.com/vaqiwuzuge.yaml [logcat.txt](https://github.com/YTVanced/Vanced/files/7330871/logcat.txt)

does it also crash on another account?

**Comment by JustFragger** [comment]
> > **Bug description** So I just installed Youtube Vanced on my phone, but after adding account app just crash instantly. I have been searching through the issue on Github also and Discord in pinned messages, but nothing worked ...
> > So tried: Uninstalling microG (also removed account from it) and Youtube Vanced. Then installing first microG, after that installed YT Vanced. Tried logging again but same, crash instantly. Tried looking on Issue (#687) but did not worked for me.
> > **Variant** Non-Root
> > **Vanced version** Using latest version (16.29.39)
> > **Android version** 8.1.0 (Oreo)
> > **Device** Meizu M8 (https://www.devicespecifications.com/en/model/a5f84e2f)
> > **Steps to Reproduce** Steps to reproduce the error:
> > 
> > 1. Open the app
> > 2. Sign In, enter email and password
> > 3. Crashes
> > 
> > **Expected behavior** Be signed in and use app normally.
> > Attached logcat created through adb. Or here https://hastebin.com/vaqiwuzuge.yaml [logcat.txt](https://github.com/YTVanced/Vanced/files/7330871/logcat.txt)
> 
> does it also crash on another account?

Yeah. I have tried 3 different accounts but it is same issue.

**Comment by milindgoel15** [comment]
It's a microG issue. Ask microG team for fixes.

**Comment by JustFragger** [comment]
Ok seems might be OS issue. Because phone had installed custom OS (FlymeOS) and at first start of phone Google services didn't worked. I had to install them from built in Chinese play store.

Right now I bought Poco X3 Pro running on MIUI and YT Vanced is worked excellent without any problem.
