### ISSUE TITLE
[Idea] Youtbe Study Mode toggle| Filter Content for Students

### ISSUE THREAD

**Issue by Jarvis-Ank** [YTVanced/Vanced#1336]
**Description**
**Youtbe Study Mode toggle| Filter Content for Students**
Filter videos based on <b>content type</b>
- Entertainment
- Education
- Tutorial
- infotainment etc.
Then allow users to toggle to Study mode when needed. option to filter content based on user preferences (*content type) could help students and other users to focus more on what they are doing without diverting to other content recommend by Youtbe. This feature could help wide variety of users.

Looking forward to opinions and Questions.

**Comment by Mesum-Hussain** [comment]
I actually asked for something similar in #1207 but one of the maintainers closed it immediately.
