### ISSUE TITLE
[Idea] Completely remove Shorts via toggle

### ISSUE THREAD

**Issue by GalaxyLinus** [YTVanced/Vanced#1338]
**Description**
There should be a toggle for YouTube Shorts, many people don't like it, and it's very addicting.

**Comment by madgoatz** [comment]
![unnamed](https://user-images.githubusercontent.com/88365986/137605205-afc11a7f-b314-448d-8498-0b808b7a6130.png)

bruh... go and search settings 🤦‍♂️
