### ISSUE TITLE
App crash in fullscreen vertical videos

### ISSUE THREAD

**Issue by Zerox1001** [YTVanced/Vanced#1342]
**Bug description**
App crashes whenever I click anywhere on a fullscreen vertical video.

**Variant**
Non-Root

**Vanced version**
v16.29.39

**Android version**
Android 9

**Device**
Honor play

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2. Click on any vertical video.
3. go to fullscreen
4. click anywhere
5. crash
**Expected behavior**
Should show the toggles on screen instead of crashing

https://user-images.githubusercontent.com/92817265/137964534-9e1f95b4-51ff-4865-8a9c-c9b84f9a750a.mp4

_Attach images or videos or logcats in case of crashes if possible. These can be helpful in solving the issue._

**Comment by Zerox1001** [comment]
Seems to only crash when enable voting is turned on in sponsorblock .
(How to get logs?)

**Comment by milindgoel15** [comment]
Follow this [guide](https://telegra.ph/Bug-Reports-10-17#How-to-get-logs)
