### ISSUE TITLE
[Bug] Manager kicking me out

### ISSUE THREAD

**Issue by Hengyboi1** [YTVanced/Vanced#135]
Vanced manager kicking me out every time I enter the app. I think the reason is that my phone doesn't support google or something I guess

NonRoot: Yes

**Android version**
Android 10

**Device**
Huawei Nova 5i

**Steps to Reproduce**
Steps to reproduce the error:
1. Open Vanced Manager
2. Then it kicks me out

**Expected behavior**
Open the app then update YouTube vanced

I open the app then it kicks me out

_Attach images/videos if possible. These can be helpful in solving the issue._

**Comment by X1nto** [comment]
Report this in manager github and attach a logcat
