### ISSUE TITLE
[Bug] When choosing 2160p resolution it auto adjust to 480p

### ISSUE THREAD

**Issue by Kasmot** [YTVanced/Vanced#1351]
**Bug description**
When changing resolution to 2160p it will play for a second then it will auto adjust to 480p after that i cannot choose any resolution above 480p anymore.
I Need to close the video first to reset reso choices.
Before i can play 4k using vanced. My official YT app can play 4k no problem.

**Variant**
Non-Root

**Vanced version**
16.29.39

**Android version**
Android 11 

**Device**
Poco x3 NFC

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2. Search for 4k video
3. Change resolution to 2160p

**Expected behavior**
For Vanced to play 4k reso but instead it auto adjust to 480p.

Troubleshooting steps:
Tried changing the default wifi reso to 2160p all it did is make all 4k YT videos default to 480p

Tried lowering down the version used 16.14, 16.16 and 16.20 and all of them can play 4k (2160p) without any issues just the latest version 16.29.

**Comment by milindgoel15** [comment]
Works fine on our end. Probably an issue on ur end only
