### ISSUE TITLE
Saving videos for watching later and saving them to playlist without Google Account.

### ISSUE THREAD

**Issue by clicky6** [YTVanced/Vanced#1366]
Add options for the following :- 

- Subscriptions -Subscribe to channels without logging into Google account and receive notifications from that channel.

- Subscriptions Video History should be stored locally and should be visible and stored even if we don't log in using a Google Account.

- Save videos for Watching Later and Save videos to playlist, make playlists and edit them without logging into Google Account.

And all these things should be done locally.

Regards.

**Comment by milindgoel15** [comment]
Use some other YouTube client instead.

**Comment by clicky6** [comment]
> Use some other YouTube client instead.

@milindgoel15 
What's this kind of behavior?

**Comment by TheAmazingBen100** [comment]
If you want to create local playlists you're better off using Newpipe

**Comment by clicky6** [comment]
> If you want to create local playlists you're better off using Newpipe

Thanks I didn't knew about that one...

**Comment by milindgoel15** [comment]
> What's this kind of behavior?

I replied to what you actually asked in your issue. Vanced is basically a mod made on top of proprietary YouTube app(which is not open source). Vanced only adds ad-blocking, bg playback and some extra features. It doesn't remove/modify the core components of YouTube app in any way. 

Hence, we suggest using some other client as per your liking.
