### ISSUE TITLE
[Idea] Convert and download videos for offline viewing.

### ISSUE THREAD

**Issue by Srking91** [YTVanced/Vanced#1370]
As far as converting videos, I'm not suggesting piracy as far as directly paid for content like movies or TV shows.

**Comment by TheAmazingBen100** [comment]
Downloading videos is server-side (we do not have any control over the download system). Vanced will never support fully free video downloading.
Some countries / territories may have access to it for free ([https://support.google.com/youtube/answer/6141269](https://support.google.com/youtube/answer/6141269)) for certain qualities of video, but in other places or for higher qualities please get YouTube Premium. This also applies to Music as well.
Once again, Vanced will never add a free video downloader as this was the main reason why other modded YouTube clients were taken down in the past.
Remember that Vanced is NOT Premium!
