### ISSUE TITLE
[Bug] crush YouTube vanced every time after opening this app within a few second 

### ISSUE THREAD

**Issue by invalid2valid** [YTVanced/Vanced#1372]
**Bug description**
crush YouTube vanced every time after opening this app within a few second 

**Variant**
Non-Root

**Vanced version**
16.29.39,16.20.35, 16.16.38 and more

**Android version**
10
**Device**
Poco m2

**Comment by milindgoel15** [comment]
Provide more information such as logs and installation method you used.

**Comment by milindgoel15** [comment]
Closing this issue due to non-activity
