### ISSUE TITLE
[Bug] When the "Comments Location (Alpha)" is turned on the 3 dots menu is nowhre to be found

### ISSUE THREAD

**Issue by Felipe9999** [YTVanced/Vanced#1373]
Bug description: 
When I turn on the old Comments location, none of the videos on the homepage have the 3 dot menu, thus can't be set to watch later, shared nor marked as "not interested".

Variant: NonRoot

Vanced version: v16.29.39

Android version: Android 10, realmeui 1.0

Device: Realme 7i

Steps to reproduce the error:
1. Open the app
2. Click on Settings/Vanced Settings/Layout settings
3. Turn on Comments Location (Alpha)
4. Return to the homepage.

When in the homepage, there should be a 3 dot menu at the rigth side of every video, with option like share, watch later, etc but after doing the steps that menu disappears.

**Comment by milindgoel15** [comment]
Do you have any screenshot showing the bug?

**Comment by Felipe9999** [comment]
@milindgoel15 
> Do you have any screenshot showing the bug?

Yes, however I've noticed that the menu is registered to be in the screen (as the picture below shows) however it's so far to the right that there isn't a way to click on it nor see it during normal use as that part of the screen isn't actually usable
![combinepedf-1](https://user-images.githubusercontent.com/70220216/140926165-fc89d9b0-5de3-43e6-80dd-99f12a4c9c4d.png)

> Edit: Also, it is known for comments location to break things. Since it is in alpha stage, it will cause bugs here and there.

I'm aware of that, however I believe that for getting this function to a stable state bugs like this one should be reported and fixed.

**Comment by TheAmazingBen100** [comment]
There will be UI issues as the old comments location toggle essentially forces the tablet experience of youtube to be displayed. The UI elements in the tablet experience were never designed to be shown on a phone, hence the UI issues.

**Comment by milindgoel15** [comment]
Since the comments location alpha toggle is removed with the latest release, this issue should not appear anymore. Closing down issue
