### ISSUE TITLE
Make the swipe controls a bit better.

### ISSUE THREAD

**Issue by clicky6** [YTVanced/Vanced#1374]
**Make the swipe controls a bit better.**
The swipe controls that exist in YouTube Vanced today are not that great ,It should be something like it is there in Google Files App in Android .The swipe controls in Google Files App look and feel a bit better.

Demonstration of the idea:-

https://user-images.githubusercontent.com/89839714/140775038-1a0b266d-4a8f-4882-a257-69645fd5d2f3.mp4

**Comment by milindgoel15** [comment]
What's the difference? The files app just displays full overlay with background and doesn't work together. Vanced does it better having them display and work side by side.

**Comment by clicky6** [comment]
OK
