### ISSUE TITLE
[Idea] Video paused. Continue watching?

### ISSUE THREAD

**Issue by Drupalorg** [YTVanced/Vanced#1375]
Hello YouTube Vanced team, through this message, I would like to request that YouTube Vanced in the next update have a feature to disable the message "Video paused. Continue Watching?", because it is very annoying.

Thanks,

Ben

**Comment by psyclonex** [comment]
This would be an excellent addition

**Comment by TheAmazingBen100** [comment]
It's a server side thing from Google, Vanced can't do anything about it. To get rid of it, buy yt premium.
