### ISSUE TITLE
Problems on Xioami Phones with Xiaomi.eu ROM

### ISSUE THREAD

**Issue by thommycgn** [YTVanced/Vanced#1384]
**Bug description**
If I watch a video and put the vanced app to the background, video-popup is not showing up, but I can still hear the sound of the video playing.  Vanced is not showing up in the Taskmanager. Going back into Vanced is only possible with the app-icon from the Desktop or AppDrawer. 
After restarting the phone video-popups are working for a while, just to stop working again. It's never visible in Taskmanger.

**Variant**
Non-Root

**Vanced version**
v16.29.39

**Android version**
Android 11 RKQ1.200826.002
MIUI 12.6 by xiaomi.eu  21.11.3 Beta

**Device**
Xiaomi Mi 9

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2. Start a Video
3. Switch to another app or click on Home-Button  >> Sometimes Video-popup is working, sometimes not
4. Go to Taskmanager >> Vanced is not showing up

**Comment by TheAmazingBen100** [comment]
Complain to Xiaomi instead, Vanced will always use the native PiP built into the Android System. It is known that there are some issues with PiP on certain roms, but you're better off complaining to the OEM instead, and not to Vanced.

**Comment by thommycgn** [comment]
> Complain to Xiaomi instead, Vanced will always use the native PiP built into the Android System. It is known that there are some issues with PiP on certain roms, but you're better off complaining to the OEM instead, and not to Vanced.

Ok. And what about the really annoying problem that Vanced is not showing up in the taskmanager? Quitting Vanced or bringing it back to the foreground is not possible, because Vanced is not visible in the task manager. Is it because PiP too or something else?

**Comment by TheAmazingBen100** [comment]
pip too

**Comment by thommycgn** [comment]
Thank you
