### ISSUE TITLE
[Idea] Adding a Netflix like screen lock feature.

### ISSUE THREAD

**Issue by mistergoliath41** [YTVanced/Vanced#1386]
Hi,
I'm here because i would to suggest a Netflix like screen lock feature on YT Vanced:
![Screenshot_20200420_170917 0](https://user-images.githubusercontent.com/37485357/141680417-6c2f5079-8f5a-4361-8357-f3b64feee21f.png)

Imagine the frustration when you watching a video and misclicking on the screen and it forward the video, switch to the next one or clicking on the suggestions at the bottom of the video player:
![Screenshot_2021-11-14-13-14-00-370_com vanced android youtube](https://user-images.githubusercontent.com/37485357/141680580-a346d720-f552-4006-bdec-b14ff983f0f9.png)

**Comment by milindgoel15** [comment]
Imagine coding a feature without having the source code of the app. lmaooo ask google for your screen lock feature

**Comment by mistergoliath41** [comment]
> Imagine coding a feature without having the source code of the app. lmaooo ask google for your screen lock feature

I mean implementing this on YT Vanced, if it is possible to implement the SponsorBlock API on the YT app, it should also be possible to add a lock screen feature.
I don't understand why there an option to ask to add a feature on the issues of your repository if you bully users who ask to and ask them to search on Google and close their issues directly.

**Comment by milindgoel15** [comment]
It doesn't mean if it's possible to add something, it's possible to add almost everything on this planet on vanced. FYI, we don't own YouTube. We don't have the source code for it either. Implementing a screen lock feature on player requires source code which we don't have. How do u propose we implement now??

**Comment by mistergoliath41** [comment]
> How do u propose we implement now??

Maybe with a LSPosed module:
https://github.com/LSPosed/LSPosed

**Comment by mistergoliath41** [comment]
Maybe with a LSPosed module:
https://github.com/LSPosed/LSPosed
If you need the source code, maybe you can get it with JADX:
https://github.com/skylot/jadx

**Comment by mistergoliath41** [comment]
Can you delete this issue please ?

**Comment by mistergoliath41** [comment]
> It doesn't mean if it's possible to add something, it's possible to add almost everything on this planet on vanced. FYI, we don't own YouTube. We don't have the source code for it either. Implementing a screen lock feature on player requires source code which we don't have. How do u propose we implement now??



> Can you delete this issue please ?

up

**Comment by milindgoel15** [comment]
Stop spamming. It cannot be deleted

**Comment by mistergoliath41** [comment]
> Stop spamming. It cannot be deleted

![IMG_20211123_124917](https://user-images.githubusercontent.com/37485357/143019149-fed6637f-1a9c-468a-a66e-ee1c94347585.jpg)

**Comment by milindgoel15** [comment]
We won't.
