### ISSUE TITLE
[Idea] Landscape Mode comments

### ISSUE THREAD

**Issue by MariusFusariu** [YTVanced/Vanced#1389]
**Description**
Reading and posting comments in landscape mode

_Attach images/videos if possible. Also add any links to possible other applications with the said feature already implemented._

**Comment by milindgoel15** [comment]
That's a server side feature. Wait for Google to roll it out for you.

**Comment by MariusFusariu** [comment]
This feature is already available on some YouTube apks that run on tablets.
I was for hoping for an exact replication of this feature
