### ISSUE TITLE
[Question] Why Is YouTube Vanced Consuming Power Too Much

### ISSUE THREAD

**Issue by bsoav** [YTVanced/Vanced#1391]
**Description**
One Hour Of Using Yt Vanced Consumes 700mAh. While Original Yt, Consumes 400mAh. Why?
![Screenshot_2021-11-16-17-13-22-43](https://user-images.githubusercontent.com/94442471/141956704-a604d972-e0aa-44ec-824a-77cc1f1482fc.jpg)
![Screenshot_2021-11-16-17-13-28-79](https://user-images.githubusercontent.com/94442471/141956714-a5b0f669-4aba-4fc4-b14b-167d3cf5b0cb.jpg)

**Comment by milindgoel15** [comment]
It's your ROM. Even tho my active usage is 11 mins for today. It just consumed 102mah

![20211116_171127.jpg](https://user-images.githubusercontent.com/45682747/141979124-ae6f19f8-4b2d-4fed-9e5d-a17340c5c3c1.jpg)
