### ISSUE TITLE
[Idea] Integration with 3rd party like\dislike source - returnyoutubedislike

### ISSUE THREAD

**Issue by Anarios** [YTVanced/Vanced#1394]
**Description**
Would Vanced consider integration with an external dislike\like source? I've created an API and a browser extensions [site](https://returnyoutubedislike.com), [repo](https://github.com/Anarios/return-youtube-dislike).

The goal of the project is to scrape as much data as possible while it's available, also integrating data from projects like [https://filmot.com/](https://filmot.com/)

After that I'll be collecting like\dislike clicks from extension users to estimate total number of dislikes.

I'd be really happy if collaboration with Vanced was possible, and I think it would be mutually beneficial, avoiding data fragmentation across desktop and mobile users.

The project is in it's infancy (I wrote first line of code this Saturday), but I'm already receiving 30k+ daily clicks from users.

Let me know what you think and who could be contacted for this.

UPDATE:
Over a million unique users per day and over 2500 RPS now. This had some growth.

**Comment by tremon36** [comment]
That's a really cool idea! I was about to post something similar!
Unfortunately I'm not part of the team.

**Comment by milindgoel15** [comment]
the op ain't part of the team either. (at least not yet)

If you wanna implement or help with the implementation, you are very welcome. The OP can also help implement it once his API gets stable enough.

**Comment by Anarios** [comment]
> If you wanna implement or help with the implementation, you are very welcome. The OP can also help implement it once his API gets stable enough.

yeah, I'm the creator of returnyoutubedislike, I'm working on stabilizing the API and preparing it for high load. It's getting about 100k daily requests now from extension users, with vanced integration that number of requests would be coming in 5 minutes, I guess - so that's something to prepare for.

Just wanted a point of contact with Vanced team if they are interested at all.

**Comment by milindgoel15** [comment]
@KevinX8 @VancedOfficial

**Comment by KevinX8** [comment]
https://support.google.com/youtube/thread/134791097/update-to-youtube-dislike-counts?hl=en
The dislikes will be removed for everyone on December 13th so we won't be able to look into it until then, sponsorblock is thinking of doing something about it when the time comes so we are just going to see if they decide to make an integration, discussion is in #dislikes here: https://discord.gg/sponsorblock

**Comment by Anarios** [comment]
@KevinX8, sure, just wanted to let you know that I'm open for collaboration and my API is open. But, of course, if you decide to use it with your huge user base - some preparation will need to be done.

**Comment by KevinX8** [comment]
> @KevinX8, sure, just wanted to let you know that I'm open for collaboration and my API is open. But, of course, if you decide to use it with your huge user base - some preparation will need to be done.

Oh I didn't notice that you were the developer of the extension, it would probably be best to integrate whichever API has the most users on all platforms to ensure the most dislikes are counted, so we will wait until the actual switch over happens and see what the situation is like then.

**Comment by fym35** [comment]
There is an open-sourcee chrome and firefox extension that allows you too see the dislike count [ https://github.com/Anarios/return-youtube-dislike ] so i think it would be me much better to implement something like that into vanced

**Comment by Anarios** [comment]
> There is an open-sourcee chrome and firefox [extension](https://github.com/Anarios/return-youtube-dislike) that allows you too see the dislike count so i think it would be me much better to implement something like that into vanced

yeah, it's mine, and I asked if we could cooperate with vanced )

**Comment by xparadoxical** [comment]
Dislike counts are visible on older versions of youtube and yt vanced apps. Is a 3rd party source even required if YouTube's API keeps sending dislike counts?

**Comment by fym35** [comment]
> Dislike counts are visible on older versions of youtube and yt vanced apps. Is a 3rd party source even required if YouTube's API keeps sending dislike counts?

Im using version of vanced from December 2020 and they still dont show up for me , weird

**Comment by KevinX8** [comment]
> Dislike counts are visible on older versions of youtube and yt vanced apps. Is a 3rd party source even required if YouTube's API keeps sending dislike counts?

https://support.google.com/youtube/thread/134791097/update-to-youtube-dislike-counts?hl=en yes because that won't happen anymore on December 13th

**Comment by xparadoxical** [comment]
@fym35 I'm on Vanced 16.29.39 (latest) and see dislike counts. This will sadly change on December 13th.

**Comment by gghhkm** [comment]
Has this come to a consensus yet?
@KevinX8 as SponsorBlock seem to be doing their own whole other system, maybe integration with @Anarios thing would be the best option?

I've been away for a while so I'm not very in the loop on the current status, could you guys update me rq.

**Comment by birth23** [comment]
> Dislike counts are visible on previous versions of youtube and the latest yt vanced apps. Is a 3rd party source even required if YouTube's API keeps sending dislike counts? True dislike counts would of course be better to see than unreal and small dislike counts of a minor group of [3rd party source] users.

Yes because YouTube is disabling API access to the Dislike information on December 13.    That's why a service is needed to scrap that data and to keep track of all dislikes.  Yes while it might not represent all of the YouTube population, but at least it is a step in the correct direction.

**Comment by xXRealXxx** [comment]
I'm on Vanced and yet I can't see the dislike count anymore. I'm using the latest version.
Haven't been able to see it for a while now.

**Comment by milindgoel15** [comment]
Vanced doesn't enable dislike counts. It has been removed server sidedly by google

**Comment by yume-chan** [comment]
Does your extension record users clicking like/dislike buttons (on YouTube webpage, Invidious, Vanced and other third-party YouTube frontends) to your service for calculating video like/dislike ratio? I guess the "integration" is not only about showing the estimated dislike count in Vanced?

**Comment by birth23** [comment]
> Does your extension record users clicking like/dislike buttons (on YouTube webpage, Invidious, Vanced and other third-party YouTube frontends) to your service for calculating video like/dislike ratio? I guess the "integration" is not only about showing the estimated dislike count in Vanced?

From my understanding the repo that the OP referenced scraps the existing like/dislike information from youtube API and once that information is disabled from Youtube API it will start counting the dislike for the users that have the extension installed.   So integration into the vanced would assist in quantifying the dislike by the users along with showing a ratio bar.

**Comment by Rerbun** [comment]
I'd suggest getting it from https://github.com/Anarios/return-youtube-dislike since that one probably has the most users and therefore biggest database at the moment

**Comment by Anarios** [comment]
> > Does your extension record users clicking like/dislike buttons (on YouTube webpage, Invidious, Vanced and other third-party YouTube frontends) to your service for calculating video like/dislike ratio? I guess the "integration" is not only about showing the estimated dislike count in Vanced?
> 
> From my understanding the repo that the OP referenced scraps the existing like/dislike information from youtube API and once that information is disabled from Youtube API it will start counting the dislike for the users that have the extension installed. So integration into the vanced would assist in quantifying the dislike by the users along with showing a ratio bar.

That is correct

**Comment by Anarios** [comment]
Just a quick update - we're over 150k users now, and over 800RPS. Still small numbers compared to Vanced, but we're getting there.

**Comment by Anarios** [comment]
1.5 million unique users according to cloudflare. 1 mil in chrome, 150k in FF.

So, any plans for integration?

**Comment by KevinX8** [comment]
Dislike integration is being looked into yes, the actual hard part is the modding tho not the API

**Comment by Inspired2150** [comment]
This would be dope

**Comment by MinersWin** [comment]
The Extension already got all the Dislikes, i would prefer this solution over the sponsorblock one. So we have one solution for everything and less fragmentation over many different solutions.

**Comment by astrOtuba** [comment]
We need it! Returnyoutubedislike is still alive. I think working dislikes in Vanced will make both Vanced.

**Comment by leodoi3** [comment]
What’s the update on this?

**Comment by AnishPoddar** [comment]
I'm interested to hear about this as well. Really hope this comes to fruition.

**Comment by CallMeAlexO** [comment]
I also support this suggestion. RYD already has quite a large db, and have proven they can handle the traffic.

**Comment by milindgoel15** [comment]
We know you all are very much excited for dislikes to come back whether with 1 API or the other. So I request you all to be patient. As soon as we have news on it, we will share it with you all here.

**Comment by VexTheWanderer01** [comment]
I should note this also exists, sorry if its already been linked.
https://returnyoutubedislike.com/docs/fetching

**Comment by Tuba202** [comment]
Has there been any update in the past month or so?

**Comment by Uniter343** [comment]
It's being worked on

**Comment by KevinX8** [comment]
> Has there been any update in the past month or so?

https://github.com/YTVanced/Integrations/tree/ryd-integration

**Comment by gghhkm** [comment]
For anyone looking for an update :
This feature is now in alpha testing.

**Comment by Ectalite** [comment]
> For anyone looking for an update :
> This feature is now in alpha testing.

Do you have to build it or is there a prebuild version somewhere ?

**Comment by gghhkm** [comment]
> > For anyone looking for an update :
> > This feature is now in alpha testing.
> 
> Do you have to build it or is there a prebuild version somewhere ?

You have to be an alpha tester member to get access to the pre-built version for testing which is completely exclusive to a select few. 
Tho I believe you can manually build it yourself if you wish following the link posted by xfile on this thread.

**Comment by gghhkm** [comment]
Update for you guys
A semi-working build is available for public beta testing in the official [Vanced Discord](discord.gg/vanced).
Make sure you read the channel pins and log any crashes.

**Comment by cheesits456** [comment]
Just leaving a comment so I'll be notified of future comments on this issue (not sure if there's a better way to do this). Keep up the good work Vanced team!

**Comment by cheesits456** [comment]
Just figured out how to get the public beta, but noticed it doesn't work for shorts yet

**Comment by gghhkm** [comment]
> Just leaving a comment so I'll be notified of future comments on this issue **(not sure if there's a better way to do this)**. Keep up the good work Vanced team!

click the "subscribe" button...

**Comment by kennychenfs** [comment]
This is a excellent integration. I hope to enjoy it soon!
