### ISSUE TITLE
[Bug] YT music - cannot okay

### ISSUE THREAD

**Issue by bazouh** [YTVanced/Vanced#1397]
**Bug description**
Replace me with a clear and detailed description of the bug.

**Variant**
Non-Root/Root

**Vanced version**
, v16.29.39

**Android version**
Replace me with the version of Android your device have. 
MmFor example?
**Device**
Replace with the name of the device on which you faced the bug. For example, Samsung Galaxy S8

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2. Click on playlist
3. Click on song
4- Message displaying : "Upgrade to play [song title]

**Expected behavior**
4- every playlist are wormi

**Comment by NotByMe** [comment]
Are you from Canada? It seems that YouTube has pushed some regional changes to the Music app users there, for example unable to play music on demand.

Also, please do a proofreading before sending bug reports next time, and read the instructions written in each section carefully.

Cheers.

**Comment by milindgoel15** [comment]
Adding more info to this thread:

Vanced will never unlock any premium service. If you can't play those music on demand, get YT premium for it.
