### ISSUE TITLE
[Bug] playlists in vanced YouTube keep getting shown up again and again when i go down searching a YouTube channel playlists

### ISSUE THREAD

**Issue by K7FU3RKILLA** [YTVanced/Vanced#1398]
**Bug description**
Replace me with a clear and detailed description of the bug.

**Variant**
Non-Root

**Vanced version**
 v16.29.39

**Android version**
Android 9

**Device**
Huawei Y9

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
3. ....

**Expected behavior**
Replace me with a description of what you expected should happen and what happened instead.

_Attach images or videos or logcats in case of crashes if possible. These can be helpful in solving the issue._
![20211118_090008](https://user-images.githubusercontent.com/94593729/142362135-dad291d5-887d-40fd-93a7-84dfeec053b6.gif)

**Comment by milindgoel15** [comment]
Definitely some server side glitch. Blame google
