### ISSUE TITLE
Bug swiping volume and brightness 

### ISSUE THREAD

**Issue by juckendesAuge** [YTVanced/Vanced#14]
After Update all with the vanced Manager 1.20 nico, I cant use anymore the swiping for volume and brightness. 
![Screenshot_20200910-201637](https://user-images.githubusercontent.com/24550429/92779711-98adcd00-f3a2-11ea-833a-e0d552ec0fbb.png)

**Comment by incIined** [comment]
is the old comment section toggled on in Vanced settings? swipe controls won't work if they're enabled

**Comment by juckendesAuge** [comment]
No, it is not switched on.
I also uninstalled the Vanced app and reinstalled it using Vanced Manager.
The problem still exists.

**Comment by VancedOfficial** [comment]
But you are using a tablet though? The swipe features aren't working in the current version for tablet devices. Will be fixed in the next version.

**Comment by juckendesAuge** [comment]
Thanks a lot

**Comment by VancedOfficial** [comment]
Should be fixed in the 15.38.35 release. Open a new issue if not.
