### ISSUE TITLE
[Idea] Pinch to go to full-screen landscape mode

### ISSUE THREAD

**Issue by Zohair-coder** [YTVanced/Vanced#140]
**Description**
I was thinking if you guys could add a feature where when you're watching a video in portrait mode, you could just pinch  it (like you do to zoom in to an image) and it would change the orientation to landscape.

The maximize button is too small and requires two taps on the YouTube app and most people prefer to keep their screen orientation locked so this would help.

### Portrait mode screen:
![Portrait Mode Screen](https://lh3.googleusercontent.com/pw/ACtC-3echEGXhbM8mIP09sn1tqpTBvNbjxIImJ_ahClfztXemHeYyoElhBxJSQOx7Swdq4uL1mEVYl4aZ1j7TQUtqFTpS913jOPVlpRgPzg2zO_pT2O4YdA3ge273GoqaoJ-PUhymnqR-ywlSAr-AGj0ljQDfw=w428-h903-no?authuser=0)

### Screen after pinching on the video:
![Landscape Mode Screen](https://lh3.googleusercontent.com/pw/ACtC-3ci59o8RNZKsrWD_ssW_vfx-ohuiKhLayVRqq6Xn-9hYVIljpZOnPWO5CgSl_YeL5-7qFr_LM4CSTTbYsLK6s9R7l6VGP9z9agMbnhLSNeFe0KUejIE67kmBpu3u6IkTNQV7B-pM4FCykeRf0mM1g23gw=w1907-h903-no?authuser=0)
_Attach images/videos if possible. Also add any links to possible other applications with the said feature already implemented._

**Comment by Prakyy** [comment]
This feature is already available for most YouTube users. If you haven't received it yet, be patient as it is a staged rollout.

Instead of pinching, which would require 2 fingers (making one handed use difficult), you can swipe up on a video to go to fullscreen and swipe down in fullscreen to go to portrait.
