### ISSUE TITLE
[Bug] YouTube Music Vanced Can't play on demand

### ISSUE THREAD

**Issue by Ynng** [YTVanced/Vanced#1402]
I know it's a YouTube Vanced Music issue, I've read the readme, but it breaks main functionality.

**Bug description**
"Play on demand" is no longer available. Error message says "Upgrade to play on demand"

**Variant**
Root

**Vanced version**
v4.39.50

**Android version**
Android 11

**Device**
Mi 11 and Oneplus 7

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2. Click on any playlist, such as your mix
3. Get this error message

**Expected behavior**
Expected to simply play the music I choose.
The app was NOT auto-updated by playstore, I have reinstalled the app multiple times and the issue persists.

![Screenshot_2021-11-18-13-02-19-124_com google android apps youtube music](https://user-images.githubusercontent.com/44907675/142471570-211a6b58-a4c8-4ce9-b87f-bc445b8264d3.jpg)

**Comment by milindgoel15** [comment]
Go pay google then. Vanced doesn't unlock any premium server and will never do. Google probably changed something through server-side update which now requires some users to get YT premium first. 

Again, blame google & get Premium.

**Comment by Ynng** [comment]
Sorry, didn't know it was server-side.

Here's a nicer explanation for anyone else coming across this issue.
https://github.com/YTVanced/Vanced/issues/1397#issuecomment-972545580
