### ISSUE TITLE
There are two ways to solve this:

### ISSUE THREAD

**Issue by VarunBanka** [YTVanced/Vanced#1405]
There are two ways to solve this:
1: Downgrade MicroG from the Github Repo [https://github.com/YTVanced/VancedMicroG/releases](https://github.com/YTVanced/VancedMicroG/releases)  AND reinstall Vanced
2: Disable all Vanced notifications

_Originally posted by @TheAmazingBen100 in https://github.com/YTVanced/Vanced/issues/1368#issuecomment-959619381_
Didn't worked

**Comment by TheAmazingBen100** [comment]
Well downgrade to the first version of MicroG that does have notifications and doesn't spam them.
Essentially, downgrade, check if it works, then rinse and repeat until you get working notifications.

**Comment by milindgoel15** [comment]
Downgrade to v0.2.20
