### ISSUE TITLE
[Bug] The app freezes sometimes

### ISSUE THREAD

**Issue by LMarius** [YTVanced/Vanced#1406]
**Bug description**
The app freezes. I can't tap on anything in it, but last time, I had problems only with comments tab, I couldn't do anything in the comments tab, but I could play/pause the video, use search etc.

**Variant**
Non-Root

**Vanced version**
Replace me with the exact version of vanced you are using. It is mandatory to report issues from the latest available versions only. For example, v16.29.39

**Android version**
Android 11, One UI 3

**Device**
Samsung Galaxy A20e

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2. Click on a video
3. Open comments tab

Or do anything untill it freezes.

I want to add that the bug doesn't happen 100%, it happens pretty rare.

**Expected behavior**
I do not expected the app to freeze.

**Comment by milindgoel15** [comment]
doesnt happen on our end. Try basic troubleshooting.
