### ISSUE TITLE
[Bug] In standby mode, the videos pause after a while.

### ISSUE THREAD

**Issue by MaXfAa** [YTVanced/Vanced#1409]
**Bug description**
Sometimes I listen to music on YouTube because they are not on Spotify, for this I choose the music video, it starts and then I put my phone to sleep (turn off the screen). And after a few tens of seconds the music will pause. And when I turn on my screen, I see on the lock screen that the video is paused and the play button is displayed but not working. On the other hand, as soon as I unlock my phone it resumes instantly. And this is a bug that happens to me every time I listen to something with the screen off.

**Variant**
Non-Root

**Vanced version**
v16.29.39

**Android version**
Android 11 

**Device**
Samsung Galaxy A71

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2. Click on a video
3. Let the video load
4. Turn off the screen
5. Wait...

**Expected behavior**
The music/sound of the video is supposed continued to play without problem.

_Attach images or videos or logcats in case of crashes if possible. These can be helpful in solving the issue._
I will be adding a screen recording very soon.

**Comment by milindgoel15** [comment]
Disable battery optimization for vanced using the help of [this site](https://dontkillmyapp.com/samsung).
