### ISSUE TITLE
[Idea] Return YouTube's Dislike Count.

### ISSUE THREAD

**Issue by jwiley17** [YTVanced/Vanced#1411]
**Description**
The following is a project designed to return YouTube's dislike counter via Chrome extension on desktop. I would think this could be merged into YTVanced to bring a solution to mobile versions. Not sure how much this has been discussed with you, their website seems to obviously be open to this idea. I've not seen anything opened here nor acknowledgement of the project here.

https://github.com/Anarios/return-youtube-dislike

**Comment by milindgoel15** [comment]
Duplicate of #1394
