### ISSUE TITLE
[Idea] Open Vanced up to community-developed extensions

### ISSUE THREAD

**Issue by harkaj33** [YTVanced/Vanced#1413]
As it has been pointed out in a [previous issue](https://github.com/YTVanced/Vanced/issues/1411), other developers of browser extensions would love to reach mobile users with the same solutions, and Vanced would be the perfect medium. I understand that it is easier said than done, but it would be awesome if people could have a way to customize even the YT mobile app to their liking much further.

**Comment by milindgoel15** [comment]
Extensions don't work on mobile clients. If they could, we would have implemented so many things by now. Plus the fact youtube ain't open source makes it more complex. The only way is thru API just like sponsorblock implementation (not through extensions).

**Comment by Loganavter** [comment]
> Extensions don't work on mobile clients. If they could, we would have implemented so many things by now. Plus the fact youtube ain't open source makes it more complex. The only way is thru API just like sponsorblock implementation (not through extensions).

So will you implement dislikes in the application? It is not necessary to cooperate with any extension.

**Comment by KevinX8** [comment]
if someone wants to add their own code to vanced we are very welcome to it, but there is no easy way to do something like that currently especially with how obfuscated youtube is, you would have to add your mod from the ground up every update.
