### ISSUE TITLE
[Idea] Possible to reinstate the small video thumbnails? 

### ISSUE THREAD

**Issue by Harmonie666** [YTVanced/Vanced#1418]
Previously we had smaller video thumbnails, and more videos did fit into your mobilephones screen, but a while ago, maybe 1 year ago, YouTube decided to change the video thumbnail size and make them huge. Now only 2 videos with their respective titles fit into my huge mobilephones screen. I find this ridiculous and very uncomfortable, as it forces us to scroll alot more up/down to find a video that we want to watch. They've also done this deliberately for the PC experience and their TV app. I think they did this changes to force us spend more time in YT, by making it more difficult to orientate ourselves in YT.
![Screenshot_20211126-004947836.png](https://user-images.githubusercontent.com/73917917/143508600-54738a43-65c8-40ed-ba84-f2bac437e30a.png)

My request for the devs is, would you please be willing to bring back the previous small video thumbnails and make it an optional toggle? 
I believe this would be a very welcome change to Vanced. 
This also has been requested in the YT forum many times, with tons of upvotes, but ignored by Google.
https://support.google.com/youtube/thread/40009707/change-youtube-app-search-results-back-to-smaller-thumbnails-new-large-thumbnails?hl=en

Same is with video thumbnail size under an open video. You can only see one large thumbnail. In that thumbnail (Mrwhosetheboss) you could literally fit 2-4 smaller video thumbnails.![Screenshot_20211126-011544374.png](https://user-images.githubusercontent.com/73917917/143509690-9bd06f86-bdb2-466d-8c3d-91b85fba7b0f.png)

Perhaps the best way to proceed with this issue is for Vanced to reinstate the previous small thumbnails, and develope own small thumbnails? 

Thanks for reading.

**Comment by milindgoel15** [comment]
Short answer: nope
