### ISSUE TITLE
[Idea] package that install youtube vanced with the original youtube package name instead of the vanced one

### ISSUE THREAD

**Issue by Kyrela** [YTVanced/Vanced#1425]
Offer, in addition to the classic version of YoutubeVanced, a version where the package name is identical to the youtube's one. (`com.google.android.youtube` instead of `com.vanced.android.youtube`)

The reason is simple : It helps the communication between the different applications. For example, with YoutubeVanced installed but not Youtube, when reading a Tweet containing a link to a video, Twitter does not propose to "open the video in youtube" but to "install youtube" - and we're forced to open youtube in the navigator because the Twitter's urls are not openable in YoutubeVanced (it's just a redirection link). The same thing for the Google assistant, which states that "Youtube is not installed" and that it is therefore not possible to launch a video/music from it.

The above example are just what they are - examples - and there are many other use cases for this "feature".

The same exact thing can apply for YoutubeVanced Music, especially for the Google assistant. (`com.google.android.apps.youtube.music` instead of `com.vanced.android.apps.youtube.music`)

This "feature" is already implemented by the "Aero" mod collection ([WhatsApp Aero](https://whatsaero.com/)/[AeroInsta](https://aeroinsta.com/)/[AeroWitter](https://aerowitter.com/))

**Comment by TheAmazingBen100** [comment]
What do you think the root version is for?

**Comment by milindgoel15** [comment]
Root your device and use root version.
