### ISSUE TITLE
[Idea] Add an "Return Youtube Dislike"

### ISSUE THREAD

**Issue by D3xron** [YTVanced/Vanced#1426]
Can you please add an addon from this website? - [Return Youtube Dislike](https://www.returnyoutubedislike.com/)

**Comment by GalaxyLinus** [comment]
That's actually a very good idea.

**Comment by enNCODER** [comment]
Yeah I'd really like to see this added

**Comment by odog8** [comment]
yuhhh lets see it

**Comment by gghhkm** [comment]
#1394
