### ISSUE TITLE
[Bug] App don't connect to internet

### ISSUE THREAD

**Issue by NickVanMarkes** [YTVanced/Vanced#1429]
**Bug description**
When I open the app, youtube vanced don't connect to internet, and can't see any videos

**Variant**
Non-Root/Root (I don't know but think root)

**Vanced version**
v16.29.39

**Android version**
Android 11 

**Device**
Samsung Galaxy S20

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app

**Expected behavior**
youtube maybe see if it's a vanced display, and block it

**Comment by milindgoel15** [comment]
#786
