### ISSUE TITLE
[Bug] Notifications Loop on Android 11

### ISSUE THREAD

**Issue by VilcsiTH** [YTVanced/Vanced#1430]
**OS:** Android 11
**Build Number:** 00WW_2_410_SP02
**Root:** Unrooted
**Phone name:** Nokia 3.4
**Model:** TA-1283
**YouTube Vanced version:** 16.29.39
**MicroG version:** 0.2.22.212658

**Description:**
Since the Android 11 update released for the phone a few months ago, waking the phone from sleep after a day of light use has a chance to make the app start looping notifications. The notifications are normal notifications - "x uploaded a new video", "your comment received a reply" and the usual stuff that appears under your bell on YouTube. Since I am unrooted, I cannot delete the default YouTube app, but I have turned off all notifications from that version, so it isn't just a case of duplicated notifications. Furthermore, even swiping the notifications away makes them reappear, seemingly at a random interval of about 5-20 seconds, and Force Stopping Vanced YouTube doesn't stop them either. Rebooting the phone has no effect. I've let the phone run during the day to see if it resolves by itself, but by the 1400th notification that day, I gave up. Apart from being really distracting visually, the rapid frequency of these notifications also impacts the device's performance. Since I rely on those notifications heavily, and because normal YouTube app notifications open normal YouTube instead of Vanced Youtube, I've found myself unable to use YouTube Vanced the way I need it.

**Why wait so long to report this?**
I thought that the issue was widespread and it would be fixed, but even now I struggle to find people with the same issue. I tried including everything about my environment to see if I can find some people in the same boat.

**Why not report this under MicroG?**
I've said that even Force Stopping YouTube Vanced keeps the notifications coming, so logically it shouldn't be the fault of YouTube Vanced, but rather MicroG. However, Vanced Music, although not known for having frequent notifications, has not shown any similar behaviour, even though it is an app I use on a daily basis aswell. This, combined with the fact that uninstalling and then reinstalling YouTube Vanced fixes the issue, albeit temporarily, made me come to the conclusion that this could be the fault of YouTube Vanced first and foremost. This, and the fact that when checking YouTube Vanced's App Info, the Notifications are credited under its name.(Hence how I could tell that 1400 notifications have appeared during the day, Android keeps count in the App Info tab.)

**Did you make sure to disable power-saving for MicroG?**
I have made sure, and just double-checked before submitting this report. MicroG reports "Not optimised" under Battery Use. I suspect some sort of power-saving feature to be the culprit nonetheless, since the looping occurs after waking the phone from sleep.

**Do you use any sort of special settings for YouTube Vanced?**
Yes, but to make sure, I installed YouTube Vanced completely fresh and used it as it came out of the box, nothing changed. The looping notifications still occurred after a few days of normal usage.

**Did you check if other people are experiencing the same issue?**
Yes, but sadly, came up empty handed. When I used Android 10, I didn't have this issue. My fiancée, who uses Android 8 and the latest YouTube Vanced, is also completely bug-free. This made me believe the issue lies within Android 11 compability.

**Comment by milindgoel15** [comment]
#1107
