### ISSUE TITLE
[Bug] Youtube Music Recent Updates Broke Vanced Music: Cannot Choose Songs

### ISSUE THREAD

**Issue by zalsader** [YTVanced/Vanced#1431]
**Bug description**
Recently, YouTube made a change to its YT Music app that allowed songs to be played in the background. In exchange for that, they restricted the ability to choose songs, and instead now you are only allowed to listen to "radio stations" that might or might not include the song. This change essentially provides one feature that Vanced music used to provide while taking away a core feature, choosing songs. I know that Music is a side project, but I am a developer and I would love to help if given some guidance.

**Variant**
Non-Root

**Vanced version**
Music Vanced 4.39.50

**Android version**
Android 12

**Device**
Google Pixel 6

**Steps to Reproduce**
1. Install the Vanced Music app on a fresh google account (You can use a [new user profile](https://www.androidcentral.com/how-add-multiple-users-and-use-guest-mode-your-android-phone))
2. Search for any song by name and try to play it
3. No play button is provided, a message pops up that says "upgrade to play on demand". See attached
4. The only option is to play a radio station which might include the needed song.

A similar thing happens when trying to play an album, the play button is greyed out and if you try to click it, it displays the same message.

**Expected behavior**
I expected to be able to play any song on demand.

**Screenshots**
![playondemand](https://user-images.githubusercontent.com/3438324/144164525-d25d6f10-6913-4dd9-ab55-e7a4a32357bf.png)

**Comment by milindgoel15** [comment]
Nope, it didn't break anything. 

More info - 1397
