### ISSUE TITLE
[Idea] "Non Live Stream Video" Only Filter for Subscription Feed

### ISSUE THREAD

**Issue by arjuna17jax** [YTVanced/Vanced#1432]
**Description**
There is live stream only filter. But the existing video only filter also include live stream. Would be useful when we subscribe channel that has both regular video and live stream. But only want to watch regular videos.

![Screenshot_20211201-104505_1](https://user-images.githubusercontent.com/48570369/144168888-89375617-185d-4c74-b03c-dffc1013d896.png)

**Comment by milindgoel15** [comment]
Ask google for this
