### ISSUE TITLE
[Bug] can't connect (December 2021, new problem)

### ISSUE THREAD

**Issue by FlashlightET** [YTVanced/Vanced#1433]
**Bug description**
Nobody else seems to be experiencing this.
on both wifi and data i can't connect and i just get that stupid astronaut. everything else on my phone connects and everyone else has no problems. i restarted. this started happening yesterday morning. i updated vanced and microg today with no luck fixing it. Netguard is not blocking YouTube. I can connect on my computer (plus this happens on data too anyways so)

**Variant**
Non-Root

**Vanced version**
16.29.39

**Android version**
Android 10

**Device**
Samsung Galaxy A21

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app

**Expected behavior**
Shows the recommended

_Attach images or videos or logcats in case of crashes if possible. These can be helpful in solving the issue._
![Screenshot_20211201-060435](https://user-images.githubusercontent.com/29938499/144224155-b99083ed-27ab-4e4e-9809-41c2842bbee0.png)
![Screenshot_20211201-060448](https://user-images.githubusercontent.com/29938499/144224159-c9c0af93-bcab-4d62-836a-7512193d1e4d.png)

**Comment by TheAmazingBen100** [comment]
[#786](https://github.com/YTVanced/Vanced/issues/786)

**Comment by FlashlightET** [comment]
OH ok makes sense yeah i just changed my google password lol i forgot

**Comment by Vpane3** [comment]
I am having the same issues. My password hasn't been changed though. One minute it was fine. Next minute non stop Astronaut.

**Comment by milindgoel15** [comment]
> I am having the same issues. My password hasn't been changed though. One minute it was fine. Next minute non stop Astronaut.

Passwords ain't the only reason for this error to occur. Many OS also cause the non-root to give offline error due to excessive battery optimization being done under the hood, killing microG app in the background so as to save your battery which is not needed in real. Please follow troubleshooting for offline fix in the referenced issue.

**Comment by Vpane3** [comment]
I have followed the trouble shooting as I like to try and solve things before asking. The moment I wrote that previous message I re read everything and went to trouble shooting. I canned the battery optimisation.

**Comment by milindgoel15** [comment]
> I have followed the trouble shooting as I like to try and solve things before asking. The moment I wrote that previous message I re read everything and went to trouble shooting. I canned the battery optimisation. 

Read the 6th point in this: https://telegra.ph/Troubleshooting-for-vanced-03-19#B:-You-are-Offline-and-connect-to-the-internet-error

Actually, read all the points.
