### ISSUE TITLE
Option to disable YouTube shorts.

### ISSUE THREAD

**Issue by clicky6** [YTVanced/Vanced#1436]
Please Add an option to disable YouTube Shorts in Vanced settings because I go to YouTube to watch videos but end up clicking on Shorts and scrolling-scrolling till I realize that I wasted my time and it is a vicious cycle.
I don't know If this is a problem for me only or everybody else but an option to disable shorts in Vanced settings would definitely be useful.
Thank You.

**Comment by milindgoel15** [comment]
Duplicate of #334
