### ISSUE TITLE
vanced is 120hz but when you check comments the whole app becomes 60 hz (bug) 

### ISSUE THREAD

**Issue by zainullahk** [YTVanced/Vanced#1437]
i use vanced for 120hz but comments in videos is 60hz which feels really slow and sometimes makes the whole app 60 hz
(poco x3 pro)

**Comment by milindgoel15** [comment]
Have you checked if this happens on the official youtube app of the same version as vanced?

**Comment by milindgoel15** [comment]
Issue with your device. 120hz works fine on vanced, even while scrolling in comments section.

**Comment by zainullahk** [comment]
Youtube does not support 120hz

**Comment by milindgoel15** [comment]
I had confirmed with other users that 120hz work fine on vanced even when you do scroll in comments. Some issue on your side. Try basic troubleshooting if it resolves.
