### ISSUE TITLE
[Bug] Youtube Music is not working

### ISSUE THREAD

**Issue by keremlight** [YTVanced/Vanced#1442]
**Bug description**
Youtube music keeps stopping

**Variant**
Rooted device
Custom rom LineageOS 16.0 

**Vanced version**
Youtube Vanced 16.29.39 (Working)
Youtube Music Vanced 4.39.50 (Crashing and Stoping even didn't open)

**Android version**
9.0.0

**Device**
Samsung Galaxy A3 2017(sm-a320f)

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2. Click on app
3. I saw youtube music icon then
3. Nothing happened and it closed

**Expected behavior**
I expexted youtube music will open but it didn't even open.

**Important note**
I tried to install older version( youtube music vance v4.30.51) and it worked i don't know why. 

_Attach images or videos or logcats in case of crashes if possible. These can be helpful in solving the issue._

![Screenshot_20211204-102613_Lawnchair](https://user-images.githubusercontent.com/95520937/144701657-4f81b0c1-466f-4837-9c61-fd7f27a3e06e.png)
[mylog.txt](https://github.com/YTVanced/Vanced/files/7653525/mylog.txt)

**Comment by milindgoel15** [comment]
Your log says it couldn't find a Library after which the app gets closed. Somehow when installation of music app, that library didn't install.

Try reinstalling vanced music again after a reboot. Follow this order: uninstall music > reboot > install again.

**Comment by milindgoel15** [comment]
Closing this issue due to non-activity. If you are still facing the bug, please report back here.

**Comment by keremlight** [comment]
I couldn't solve this problem. Then for some reasons, i had to flash stock rom. Now, I use youtube vanced 16.29.39 and youtube music vanced 4.30.50(not lastest version). There is no any problem. Everything is fine.

**Comment by milindgoel15** [comment]
problems with the rom

**Comment by thechosensausage** [comment]
I have same problem, mine is galaxy note 4, lineage os 17.1 (android 10). 
The non-root variant works fine, though.

**Comment by milindgoel15** [comment]
Lineage OS is the issue here then
