### ISSUE TITLE
youtube vanced won't run unless you update google play services

### ISSUE THREAD

**Issue by batata004** [YTVanced/Vanced#1445]
I had a MI A3 phone that whenever I tried to cast Vanced to Chromecast it would display this message:

youtube vanced won't run unless you update google play services

Then I bought a Samsung A52 smartphone and for my surprise, today I tried casting and I had the same problem! So it was not a problem of my phone, it looks like a problem with the app.

Searching at google I found tons of people complaning about the problem, some say the problem is with microG others say I should use an older version (I tried, didnt work)... So, is there an official alternative to fix this or I just have to wait the community fix it, instead of keeping trying suggestions people say all around that dont work?

**Comment by Chesk14** [comment]
Exact same thing!  I'm constantly casting to my tvs/chromecasts, so this is a new issue.  Tried an older version as well.  Same thing. 
The notification (shown below) comes up.  And then if I tap it, opens the play store and says try again. 
Not sure what to try.  May try an older version of microG as well.  Have you?

![Screenshot_20211205-154243_Google Play Store](https://user-images.githubusercontent.com/95590070/144763193-f0dc3b4c-6967-4d28-8dbc-f03a501c7c5a.jpg)
![Screenshot_20211205-154207](https://user-images.githubusercontent.com/95590070/144763195-4230ad65-d899-43a9-bf72-45d8d3411311.jpg)

**Comment by Nubebuster** [comment]
I am also having this issue

**Comment by TheAmazingBen100** [comment]
[#688](https://github.com/YTVanced/Vanced/issues/688)

**Comment by batata004** [comment]
> [#688](https://github.com/YTVanced/Vanced/issues/688)

it was locked/closed so I opened this to check if there is an ETA. I am facing this problem for almost 2 years. If there is no intention in fixing this bug, please say so! This way I wont be waiting for it and will use Firefox with uBlock on my android, instead.

**Comment by Chesk14** [comment]
Interesting!  
I now see there's been a thread for this at #688 
which started months ago.  Yet I've been able to cast to my tv with Vanced for the past year or two up until today!
Strange.  
Good ol' wonky technology

**Comment by milindgoel15** [comment]
> I am facing this problem for almost 2 years

2 years lmao. The bug started with YouTube's March update this year. Go throw your bs somewhere else

> If there is no intention in fixing this bug, please say so!

Vanced will provide a fix for you as soon as microG devs fix it as it's microG issue, not vanced. Please do your homework properly.
