### ISSUE TITLE
[Idea] Prevent watching shorts

### ISSUE THREAD

**Issue by Alwinator** [YTVanced/Vanced#1448]
**Description**
YouTube Shorts are very addictive. It would be great if there is an option to prevent swiping up on shorts to show a new video. This way the users could only watch the one video they clicked on and would not be stuck and wasting their time watching other videos.

Thanks for you great development work!

**Comment by milindgoel15** [comment]
Just don't tag on shorts tab.

**Comment by milindgoel15** [comment]
#334

**Comment by Alwinator** [comment]
I have programmed a temporary fix using the Automate app which works well. You can find my flow / script here: https://llamalab.com/automate/community/flows/41555

#334
