### ISSUE TITLE
[idea] restore dislike stats

### ISSUE THREAD

**Issue by yaktoma2007** [YTVanced/Vanced#1450]
![Screenshot_20211207-123623~2](https://user-images.githubusercontent.com/83469060/145022448-6267cd95-d6ab-4009-b243-8c4c8b5f102b.png)

So there is a web extension that restores dislike stats using a combination of their own servers and archived dislikes to bring those dislikes back.

Here is the github page:
https://github.com/Anarios/return-youtube-dislike

![image](https://user-images.githubusercontent.com/83469060/145022297-84fcde51-bbee-40c9-b9fc-6c5dfb7d4cc8.png)

**Comment by milindgoel15** [comment]
#1394
