### ISSUE TITLE
[Question] "2021 Recap" doesn't appear in YTM Vanced.

### ISSUE THREAD

**Issue by Harmonie666** [YTVanced/Vanced#1451]
This is not a bug or feature request per se, but just a FYI. The 2021 Recap is missing in YTM Vanced. It only appears in Stock YTM. Perhaps this could be looked into, and made available in YTM Vanced aswell? Not sure if it's the base version that needs to be updated.

![Screenshot_20211207-213707695 (1).png](https://user-images.githubusercontent.com/73917917/145102929-3b59ac54-d13b-4022-af30-bffe9751ae7f.png)

**Comment by milindgoel15** [comment]
It did need base update which we aren't going to do specially for **this 1 temporary feature**. Use official yt music for that
