### ISSUE TITLE
[Feature] Downloading videos in 720p and 1080p

### ISSUE THREAD

**Issue by phoenix-the-dev** [YTVanced/Vanced#1453]
**Description**
Youtube now does not allow you to download videos in 720p and 1080p.It instead hides the option behind a paywall. I want to download the videos natively in side the app. If you've already enabled other premium features like PiP and Background Play then this is also probably possible right? I dunno :P

**Comment by milindgoel15** [comment]
Vanced ain't yt premium and will never provide such features. Go get a job
