### ISSUE TITLE
[Bug] Phone crashes suddenly and Youtube Vanced is gone

### ISSUE THREAD

**Issue by maximilian1001** [YTVanced/Vanced#1454]
**Bug description**
Several times a day the phone suddenly crashes and immediately shows the boot animation. I am not prompted to re-enter my SIM PIN, so I assume that only SystemUI is crashed. After everything reloads, I suddenly have the stock YouTube app installed again.

**Variant**
Root

**Vanced version**
v16.29.39

**Android version**
Android 11 

**Device**
OnePlus 9 (Model LE2113)

**Steps to Reproduce**
1. Disable updates for Youtube in Playstore
2. Uninstall updates for Youtube app
3. Install Youtube Vanced via Vanced Manager (everything works fine in this stage!)
4. Wait some hours until phone crashes
5. Now Youtube Vanced is away and I am back on stock Youtube (v16.14.34) without updates

**Expected behavior**
Vanced Youtube should stay installed and phone should not crash. Reason for the crash is unkown so far.

**Comment by milindgoel15** [comment]
Your phone is crashing because of your OS bug. It has nothing to do with vanced. The vanced disappears because your OS soft reboots which then removes vanced patch over stock base. A manual reboot after this soft reboot can bring vanced back.

But again, you need to fix your ROM first which will fix vanced with it.

**Comment by maximilian1001** [comment]
@milindgoel15 Thank you for your fast reply!

Can you tell me whats wrong with my OS? I'm using OnePlus' OxygenOS (rooted with Magisk).

**Comment by milindgoel15** [comment]
I'm pretty sure OnePlus messed something. Ask them for fixes. Or otherwise try factory reset or use non-root.
