### ISSUE TITLE
[Bug] Crash after starting

### ISSUE THREAD

**Issue by Koumar-01** [YTVanced/Vanced#1455]
**Bug description**
So, couple hours ago i accidently deleted vanced stuff. After reinstalling i tried to open Vanced Youtube, but sadly it instantly crashed.
I tried redownloading it but it didn't worked.

**Variant**
Non-Root

**Vanced version**
16.29.39

**Android version**
Android 7.1.2

**Device**
Meizu M6 Note

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app

**Expected behavior**
Expected opening of the app.

_Attach images or videos or logcats in case of crashes if possible. These can be helpful in solving the issue._

https://user-images.githubusercontent.com/60773901/145261141-095d3873-a2b1-4303-b98d-f81dd69551a9.mp4

[logcat.txt](https://github.com/YTVanced/Vanced/files/7678002/logcat.txt)

**Comment by milindgoel15** [comment]
Refer [troubleshooting](https://telegra.ph/Troubleshooting-for-vanced-03-19) guides for fixing such issue. If the issue persists, provide logs here.
