### ISSUE TITLE
[Bug] Picture in picture doesn't work 

### ISSUE THREAD

**Issue by Mimicthis** [YTVanced/Vanced#1456]
Picture in picture doesn't work and the  notification bar player dissaperas. Even after closing the app it still continues to play the song. 

**Variant**
Non-Root

**Vanced version**
v16.29.39

**Android version**
Android 11 

**Device**
Samsung Galaxy A52 5G 

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2. Turn off picture in picture and turn it on again 
3. Exit the app, it won't work and 

**Expected behavior**
Picture in picture doesn't work and the  notification bar player dissaperas. Even after closing the app it still continues to play the song.  

Picture in picture windows should appear if it works. 

_Attach images or videos or logcats in case of crashes if possible. These can be helpful in solving the issue._

**Comment by milindgoel15** [comment]
#197
