### ISSUE TITLE
[Idea] Notification bar player style custom

### ISSUE THREAD

**Issue by Mimicthis** [YTVanced/Vanced#1457]
**Description**
Please add personalized look to the notification bar player look.
It looks like this right now:
Plain gray and boring,not like the official YouTube app 
![Screenshot_20211209-051807_Chrome~2](https://user-images.githubusercontent.com/29215437/145333695-ae2706df-cba5-4260-9d27-ec1dae6d108c.jpg)

**Comment by milindgoel15** [comment]
Complain to google and samsung

**Comment by Mimicthis** [comment]
Hi diva, it's Vanced issue.

**Comment by milindgoel15** [comment]
K

![Screenshot_20211209-112121.png](https://user-images.githubusercontent.com/45682747/145341868-cf5194cf-12f8-41e3-9af1-ad3151aafba4.png)

**Comment by milindgoel15** [comment]
we will look into this anyway. Probably **another google base bug** hitting some os. It sure ain't vanced bug as we said earlier so a new base update will fix this issue.

**Comment by Mimicthis** [comment]
Tnx :)
