### ISSUE TITLE
[Bug] replaceme

### ISSUE THREAD

**Issue by bck7788** [YTVanced/Vanced#1458]
**Bug description**
It is disconnect

**Variant**
Non-Root

**Vanced version**
 v16.29.39

**Android version**
 Android 11 

**Device**
Realme gt master edition

**Expected behavior**
I already re-install

![Screenshot_2021-12-09-14-09-39-84_7a4090f09f6554852d748ee9fd6f40d3](https://user-images.githubusercontent.com/95845385/145352719-1572788a-dc93-4e83-9e03-8e382c7589ef.jpg)

**Comment by milindgoel15** [comment]
#786
