### ISSUE TITLE
[Bug] Video keeps playing but can't go back/select other video 

### ISSUE THREAD

**Issue by Asstronaut69** [YTVanced/Vanced#1459]
**Bug description**
When switching back to vanced from another app, OR after locking and unlocking phone into vanced, I can resume the current video, but if I try to swipe it down or hit the back button on my phone everything below the video will dissappear and just leave black space. The video will keep playing and I can even click to the next video with the next button, but I can't go back to home/subscriptions or anything without force closing and restarting the app. Doesn't happen every time but pretty frequently. 

**Variant**
Non-Root

**Vanced version**
v16.29.39

**Android version**
Android 11 

**Device**
Samsung A21s

**Steps to Reproduce**
Steps to reproduce the error:
1. Open vanced
2. Play a video
3. Switch to another app and back to vanced OR lock/unlock phone

**Expected behavior**
I should be able to navigate the app as normal but I'm unable to return to the main home/subscriptions screen.

**Comment by milindgoel15** [comment]
Refer [troubleshooting](https://telegra.ph/Troubleshooting-for-vanced-03-19) guides for fixing such issue. Vanced works fine on our end.
