### ISSUE TITLE
[Idea] A universal region block work around?

### ISSUE THREAD

**Issue by Glixil** [YTVanced/Vanced#1460]
**Description**
I've noticed a ton of videos in my music playlists have been blocked in my country (for seemingly no reason). I know this might be nearly impossible to implement, but it would be amazing if you could! 

For example: https://youtu.be/PYk2cHaoJjI this video was available less than a year ago I think. There are easily at least 10 videos this has happened to.

**Comment by Glixil** [comment]
Well, I've been meaning to buy a VPN for a while so I finally did. Only to realize that the videos in my playlists say "video blocked in your country" because (I think anyways) the channel it came from changed something. (Google's) YouTube has been changing regions for videos for at least a year, theres been many others who've experienced this and I dont think anyone knows why for sure, at least I haven't found anything definitive.

**Comment by milindgoel15** [comment]
Free VPN also exists but anyway.
