### ISSUE TITLE
[Bug] Phone hard crash on Android 11

### ISSUE THREAD

**Issue by Quikswitch** [YTVanced/Vanced#1461]
**Bug description**
App hard-crashes phone (as in full-restart) seemingly randomly while connected to the internet. Sometimes also has visual "glitch" noise during the crash. No input is acknowledged during these glitches.

Anecdotally, I've noticed that a lot of the crashes happen when there are updates that need to happen from the Google Play Store (unable to see which update causes it, though) or right after accessing the settings menu > Try new features

Apologies if this ends up being a Micro G bug, but it's not easy to track down exactly why this is happening.

**Variant**
Non-Root

**Vanced version**
Vanced Manager 2.6.2
Vanced microG 0.2.22.212658
Youtube Music Vanced 4.39.50
**Youtube Vanced 16.29.39** Light+Black version

**Android version**
Android 11

**Device**
Samsung Galaxy A32

**Steps to Reproduce**
1. Download and install app from vancedapp.com through manager
2. Connect to internet
3. Open app
4. Log in to profile (not sure if this is needed)
5. Wait for a few minutes (3-5 seems to do it) or restart phone and reconnect to internet
    An alternative that seems to work frequently is to go to settings>Try new features
6. Hard crash (as in restart of phone) sometimes accompanied by visual "glitchiness"

**Expected behavior**
I feel like this might be obvious, but not crashing?

I'll attempt to get a video to post at some point in the near future.

[Similar seeming report on Reddit](https://www.reddit.com/r/Vanced/comments/r6v311/vanced_or_microg_hard_crashes_my_phone_question/)

Thanks in advance for the otherwise great apps!

**Comment by milindgoel15** [comment]
Not vanced bug.
