### ISSUE TITLE
[Bug] Notification issues

### ISSUE THREAD

**Issue by Thai2706** [YTVanced/Vanced#1462]
**Bug description**
Infinity repeat

**Variant**
Non-Root

**Vanced version**
v16.29.39

**Android version**
Android 11 

**Device**
POCO X3 NFC

**Steps to Reproduce**
Steps to reproduce the error:
I didn't know

**Expected behavior**
New notification replaces the old notification according to the queue principle

https://user-images.githubusercontent.com/53868553/145571488-16396feb-da36-4d3d-896c-31850b051fc8.mp4

_Attach images or videos or logcats in case of crashes if possible. These can be helpful in solving the issue._

**Comment by milindgoel15** [comment]
#1107
