### ISSUE TITLE
[Bug] In Dark mode rotating the device will not go to full screen and will not change screen orientation to landscape

### ISSUE THREAD

**Issue by novakma7** [YTVanced/Vanced#1466]
**Bug description**
In Dark theme screen orientation does not change to landscape when the device is rotated, does not go to full screen. In light mode it works as expected.

**Variant**
Root

**Vanced version**
3.2.9 - production

**Android version**
Android 10

**Device**
Zenfone Max 4

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2. Go to menu "More" -> Main Settings -> change theme to "Dark theme"
3. Go back, open any video
3. Rotate the device to landscape orientation. Video will not change to full screen, and the screen will remain in portrait mode.

**Expected behavior**
When the device is rotated it should switch to full screen and change screen orientation.
In Light theme this works as expected.

**Comment by milindgoel15** [comment]
From where did you download vanced from?

**Comment by novakma7** [comment]
google play

**Comment by milindgoel15** [comment]
Bruh moment.

Vanced never uploaded a single app on the play store except for our guide app which was taken down by Google for non-valid reasons. Any type of modified apps can NEVER be published on google play by anyone. The app that you are now using is fake, unofficial and probably with adware or malicious files.  

The only site vanced can be found on our official website at https://vancedapp.com. So please uninstall the app you are having and install the official apps from our website.
