### ISSUE TITLE
[Idea] Add option to return the dislike counter

### ISSUE THREAD

**Issue by IveMalfunctioned** [YTVanced/Vanced#1467]
**Description**
YouTube made the lousy decision of removing video dislikes, so maybe [this code](https://github.com/Anarios/return-youtube-dislike) could be implemented (as was SponsorBlock's) to re-add dislikes

_Attach images/videos if possible. Also add any links to possible other applications with the said feature already implemented._

**Comment by milindgoel15** [comment]
Duplicate of #1394
