### ISSUE TITLE
[Bug] Youtube Vanced version from 16.14.34 to 16.29.39 closing itself 3 seconds after screen is turned off

### ISSUE THREAD

**Issue by slavchez** [YTVanced/Vanced#1468]
**Bug description**
Hi, Youtube Vanced started closing itself 3 seconds after I put my Huawei P40 pro with latest EMUI 12 to sleep.
Issue happened after an update of the application.  

**Variant**
Non-Root

**Vanced version**
All versions from 16.14.34 to 16.29.39 are having this issue. (tested)
Issue is NOT present on version 16.02.35 and lower, since I have tested them and everything is okey.
Running the same Vanced MicroG 0.2.22.212658 while testing all of them.

**Link used to download vanced**
I have downloaded Youtube Vanced with Vanced Manager --> 2.6.2 (Crimson) downloaded from vancedapp.com

**Android version**
Android 10 with EMUI 12 build number 11.0.0.230

**Device**
Huawei P40 pro

**Steps to Reproduce**
Steps to reproduce the error:
1. Install latest Vanced Manager 2.6.2 (Crimson)
2. Open it and install Vanced microG latest version
3. From the same menu Install also YouTube Vanced latest version
4. Open Youtube Vanced and start playing some video with sound on
5. Minimize the video to play in small window
6. Phone will ask to add the app as Battery Optimizing Exception - do that
7. Lock your phone and wait until goes black screen
8. 3 seconds later video will stop playing and Youtube Vanced will disappear from tasks as well forgetting your progress.

**Expected behavior**
I expect Youtube Vanced to be able to play at background after I put device to sleep as it is with version 16.02.35 and lower

**Comment by milindgoel15** [comment]
Please read vanced guides before creating issues. All your problems are listed there already.

**Comment by slavchez** [comment]
> **Bug description** Hi, Youtube Vanced started closing itself 3 seconds after I put my Huawei P40 pro with latest EMUI 12 to sleep. Issue happened after an update of the application.
> 
> **Variant** Non-Root
> 
> **Vanced version** All versions from 16.14.34 to 16.29.39 are having this issue. (tested) Issue is NOT present on version 16.02.35 and lower, since I have tested them and everything is okey. Running the same Vanced MicroG 0.2.22.212658 while testing all of them.
> 
> **Link used to download vanced** I have downloaded Youtube Vanced with Vanced Manager --> 2.6.2 (Crimson) downloaded from vancedapp.com
> 
> **Android version** Android 10 with EMUI 12 build number 11.0.0.230
> 
> **Device** Huawei P40 pro
> 
> **Steps to Reproduce** Steps to reproduce the error:
> 
> 1. Install latest Vanced Manager 2.6.2 (Crimson)
> 2. Open it and install Vanced microG latest version
> 3. From the same menu Install also YouTube Vanced latest version
> 4. Open Youtube Vanced and start playing some video with sound on
> 5. Minimize the video to play in small window
> 6. Phone will ask to add the app as Battery Optimizing Exception - do that
> 7. Lock your phone and wait until goes black screen
> 8. 3 seconds later video will stop playing and Youtube Vanced will disappear from tasks as well forgetting your progress.
> 
> **Expected behavior** I expect Youtube Vanced to be able to play at background after I put device to sleep as it is with version 16.02.35 and lower

**Comment by slavchez** [comment]
I have followed all the guides available in Internet, also downloaded an app called Vanced Guides and I did all steps in troubleshooting by disabling Battery optimization for both Youtube Vanced, Vanced Manger and MicroG, then I did a reboot,but issue is still present with the versions I mentioned already. Issue is NOT present with the old version as mentioned already, so the issue is related to something added later on.

**Comment by milindgoel15** [comment]
Follow dontkillmyapp.com/huawei for disabling battery optimization. The problem is caused by your device OS, not vanced.

**Comment by slavchez** [comment]
> Follow https://dontkillmyapp.com/huawei for disabling battery optimization. The problem is caused by your device OS, not vanced.

Thanks!
"adb shell pm uninstall -k --user 0 com.huawei.powergenie" did the trick. Still does not explain why Vanced 16.02.35 and lower is working without uninstalling com.huawei.powergenie, but this is part of the "magic" called developing :)

**Comment by milindgoel15** [comment]
Ask Huawei, not us. We didn't change anything.
