### ISSUE TITLE
[Idea] Option to enable old comments on tablets as well

### ISSUE THREAD

**Issue by 1unar-Eclipse** [YTVanced/Vanced#1469]
**Bug description:**
The comments are now activated by tapping under the description box rather than scrolling under the Recommended tab. There is no option for this on tablet, and I have heard in the Discord that the phone option no longer works consistently.

**Have you read vanced guides already? (YES/No)**
Searched "comment", found nothing. 

**Variant:**
Non-Root

**Vanced version:**
16.29.39

**Link used to download vanced:**
Don't remember

**Android version:**
11

**Device:**
Galaxy Tab S6

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2. Click on any video
3. Scroll down to the bottom of recommended
4. "Comments have moved" appears

**Expected behaviour:**
At step 4, the comments should have appeared under the recommended videos.

Flawed comments:
https://cdn.discordapp.com/attachments/358967876193091584/920147262955458590/Screenshot_20211213-215635.png

Intended comments:
https://cdn.discordapp.com/attachments/358967876193091584/920044098172358686/Screenshot_20211213-150610.png

**Comment by milindgoel15** [comment]
First of all, have you checked official YouTube to check how are comments showing there?

**Comment by 1unar-Eclipse** [comment]
Official YouTube displays in the first (flawed) way.

Something tells me this is leaning into feature request territory.

**Comment by milindgoel15** [comment]
Then it's not a bug, it's a feature by Google itself. Google has already moved the comment section on mobiles months ago. I guess google be pushing new changes to tablets now. It is what it is now.

For old comments, there's already an option available for mobiles under layout settings as comments location (alpha). Dunno if that appears in tablets. So check it and try.

**Comment by 1unar-Eclipse** [comment]
The option isn't on tablets. Really annoying; the new layout is not great at all.

**Comment by milindgoel15** [comment]
Complain to google for that lol

**Comment by 1unar-Eclipse** [comment]
Where is a feedback link?

**Comment by milindgoel15** [comment]
> Where is a feedback link?

For reporting Google related bugs, the feedback option can be found in profile menu

**Comment by apaxc** [comment]
The new comment box under description is difficult to use.
Not only is it difficult to use it is also ugly. I would love to have an option to turn it back to the original layout location under the videos on the side.

This update is especially hard to use on tablets as the button to click the comment box open is small.

Thanks.

**Comment by Kolsky** [comment]
Old comments location is broken on a phone too
![IMG_20211216_042226](https://user-images.githubusercontent.com/22716073/146280630-a6ce7630-c854-4115-90f9-46c10e83cd55.jpg)

**Comment by milindgoel15** [comment]
Why are people calling this as broken? Lmao I don't get it

**It's server side update by Google**

**Comment by Fogapod** [comment]
> The new comment box under description is difficult to use.

I don't have comments at all for the past 10 or so days. "GO TO COMMENTS" displays "Tap to see all comments" pointing to nowhere on top of channel name. Both portrait and landscape

**Comment by dokufreenet** [comment]
> ~Why are people calling this as broken? Lmao I don't get it **It's server side update by Google**~
> 
> Finally got what you mean. seems like google pushed some changes thru server-side updates to force new comments on every platform, which broke the old comments location toggle. SO xfilefin would have to look if that can be fixed or otherwise say rip to old comments.

Goggle dont, i've downgraded vanced,  and since then it stays on the old desing,  i just hope it will be patched, cause in a few years, the version i am using now will stop working,  like ogyoutube did, i used it many years after support end (i like the old red desing much much better), umtil google changed something serverwise, that causes the old yt app to just dont work.

**Comment by milindgoel15** [comment]
Google removed it from new base. How are u gonna bring it back?
