### ISSUE TITLE
[Bug] Latest vanced update removed the "wide search bar" in Layout Settings.

### ISSUE THREAD

**Issue by Harmonie666** [YTVanced/Vanced#147]
**Bug description**
If I deactivate the wide search bar, the default small search icon is back. It also looks like the position of the search icon has changed from left to right (closest to user profile picture) which could be the cause of this bug.

**Variant**
NonRoot: Yes
Root: No

**Vanced version**
15.43.32 - Build - 01.47.00

**Android version**
Android 10

**Device**
ASUS ROG Phone II

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2. Click on Layout settings, → enable 'wide search bar' 
3. Search bar is removed completely when enabling it.
Can't search for a video, unless it's disabled again.

**Expected behavior**
Fix the wide search bar please.
I love that feature.

![Screenshot_20201104-011522645 (1)](https://user-images.githubusercontent.com/73917917/98056131-6ae38280-1e3f-11eb-8fa5-aba3ef863f08.png)

**Comment by milindgoel15** [comment]
Please update to the latest v16.16.38 if you haven't already. We are closing this issue. Feel free to reopen if you still face any issues.
