### ISSUE TITLE
[Bug] Shorts crash and restart the app for the first several launches

### ISSUE THREAD

**Issue by novocaiin** [YTVanced/Vanced#1473]
**Bug description:**
For the first 4-5 launches (after maybe half an hour of not using the app?) opening a short causes the app the flash white and restart after a couple seconds (see first video).
Sometimes it just force closes the app (see second video).
Battery optimization is disabled for both Vanced and Vanced Manager.

**Have you read vanced guides already? (YES/No)**
YES

**Variant:**
Non-Root

**Vanced version:**
v16.29.39

**Link used to download vanced:**
https://vancedapp.com/

**Android version:**
Android 12

**Device:**
Google Pixel 5

**Steps to Reproduce**
1. Open a short.

**Expected behaviour:**
App doesn't crash.

https://user-images.githubusercontent.com/95007229/146161436-04860eea-b52c-4aa1-8a22-c59b5fd90639.mp4

https://user-images.githubusercontent.com/95007229/146161459-9bbe242a-5a73-46a8-81f0-b36d8fca4089.mp4

**Comment by milindgoel15** [comment]
Get logs. The guide on how to get logs can be found in vanced guides section.

And also, try clean install and then again check the crash, it still happens. Then report here.

**Comment by novocaiin** [comment]
Turns out I was using a fake version of Vanced 😳
No crashes on the legit version.
Sorry to bother and I'm closing this.

That said, #1472 and https://github.com/YTVanced/Vanced/issues/1472#issuecomment-994607594 still happen, so if you could still test it out that'd be great.

**Comment by milindgoel15** [comment]
Lmao which link you were following?😂😂

**Comment by novocaiin** [comment]
youtubevanced.com

It was the first result too xD

**Comment by milindgoel15** [comment]
😂😂😂😂😂
