### ISSUE TITLE
[Bug] Stuck in the installation 

### ISSUE THREAD

**Issue by Pocarai** [YTVanced/Vanced#1474]
**Bug description:**
A while ago, after Installing of Xprivacy by Riru devs. My youtube says need sign of my account in this device after that I uninstall it then the problem found again. It stuck in Vanced manager during installation. I was waiting more than minutes and same happenings

**Have you read vanced guides already? (YES/No)**
YES 

**Variant:**
Root

**Vanced version:**
version 2.6.2 (Crimson)

**Link used to download vanced:**
(https://vancedapp.com/) 

**Android version:**
Android 11 

**Device:**
Xiaomi Redmi Note 9 pro

**Steps to Reproduce**

1. Open the app
2. downloading and Installing YouTube Vance
3. Problem occured

**Expected behaviour:**
Sucessful of Youtube Vance installation

![Screenshot_20211216-104901465](https://user-images.githubusercontent.com/96225118/146323358-284550df-0f42-4e1f-83fc-dd2c5b637af2.jpg)

**Comment by milindgoel15** [comment]
Read vanced guides again. You said yes but you still missed out the solution for stuck on installation.

If that fails, uninstall ur riru module. Or use non-root version.
