### ISSUE TITLE
[Bug] Youtube Vanced crashing

### ISSUE THREAD

**Issue by Kardynal098** [YTVanced/Vanced#1476]
**Bug description:**
I loged in to my account. Then I clicked search to find video. Next I clicked three dots to share the video but app instantly crashed. At first I thought it was my custom rom's fault but I tried it on my 2nd phone and... the problem was the same. The strange thing is that it only happens to one specific google account. When I switched account the problem disappered but when I switched back to first account problem reappeared. On normal yt all of my account works perfectly fine. I installed older version of vanced (15.43.32) and the is no problem yet. 

**Have you read vanced guides already? (YES/No)**
Yes 

**Variant:**
Non root and root

**Vanced version:**
 v16.29.39

**Link used to download vanced:**
https://vancedapp.com/

**Android version:**
Android 11

**Device:**
Mi 9t pro with custom rom arrow os 11 installed (first december package)

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2. Click on 'search'
3. Click on three dots to share a link
4. App crashes

**Expected behaviour:**
if you can fix it I will be very grateful

**Comment by milindgoel15** [comment]
Lmao the way you wrote in "expected behaviour" to "fix this bug" is pretty hilarious. Do you think we work for you? Vanced is a free project, not some job and we are not your slaves. Better to speak nicely next time.

Provide logs of the crash

**Comment by Kardynal098** [comment]
> Lmao the way you wrote in "expected behaviour" to "fix this bug" is pretty hilarious. Do you think we work for you? Vanced is a free project, not some job and we are not your slaves. Better to speak nicely next time.
> 
> Provide logs of the crash. And try basic troubleshooting as well.

Okay bro I understand. It wasn't supposed to sound like that. I'm sorry. I tried basic troubleshooting like restarting phone or reinstalled YT vanced and Vanced Menager (I deleted the rest of the files in vanced folder by orange fox) however, it did not help. I have no idea why this only happens on one account. I installed older version and vanced is working fine. Yea I provide logs of the crash but it could be sound funny. I don't not how to check this logs. When app crash I have only notification "the application keeps crashing" or something like that. If you tell me how to do it I would be grateful.

**Comment by milindgoel15** [comment]
According to the bug u are facing, I guess the bug u are having is probably known to us. But for us to make sure you are one of those users with one specific bug, we would need logs.

To get logs, check the [bugreport guide.](https://telegra.ph/Bug-Reports-10-17#How-to-get-logs)

**Comment by milindgoel15** [comment]
Apparently, this issue is not related to vanced. Google is pushing some new change for few users through server side switch which makes the app crash when searching and sharing a some videos. Wait for next base update by Google & vanced.
