### ISSUE TITLE
[Bug] Youtube Vanced crashes when searching

### ISSUE THREAD

**Issue by emptyworldexe** [YTVanced/Vanced#1477]
**Bug description:**
When searching for videos on Vanced, the app crashes.

**Have you read vanced guides already? (YES/No)**
YES

**Variant:**
Non-Root

**Vanced version:**
v16.29.39

**Link used to download vanced:**
vancedapp.com

**Android version:**
Android 11 

**Device:**
Samsung Note 10 Lite

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2. Search for a video
3. Scroll past the first result(s)

**Expected behaviour:**
App does not crash & shows results as normal.

Logcat: https://www.toptal.com/developers/hastebin/upuqejebed.yaml

**Comment by milindgoel15** [comment]
We confirmed that this is an issue pushed by google through server-side updates just recently. It's a bug from google's end so wait for future updates. Meanwhile, you can try clearing out app data for a temporary fix.
