### ISSUE TITLE
[Idea] re add high quality download disabled by official yt

### ISSUE THREAD

**Issue by ilyasbabu** [YTVanced/Vanced#1478]
**Description**
YouTube now officially disabled the 720p download feature for users and only premium users can get it. So adding 720p download will be a great feature.

![Screenshot_2021-12-17-09-02-36-338_com.vanced.android.youtube.jpg](https://user-images.githubusercontent.com/86759152/146484553-ed04ca6c-39bb-4ced-bac2-8849923327b0.jpg)

**Comment by milindgoel15** [comment]
Go get YT premium

**Comment by ilyasbabu** [comment]
This was an idea suggested and how can u say that to go get premium. If so we can't even use vanced yt because there's no ads so u should get premium for disabling ads. Lol
Why so rude?

**Comment by ilyasbabu** [comment]
> Go get YT premium

At least elaborate y u say so?!

**Comment by milindgoel15** [comment]
Vanced was never made for providing video downloaders. It was made for blocking ads and background playback both of which existed long before google introduced youtube red. Please do your research properly and read the vanced faq before asking for same stuff again and again. 

Vanced will never make a video downloader. Period
