### ISSUE TITLE
[Idea] Tablet UI layout for vanced on win11

### ISSUE THREAD

**Issue by 1YuvrajS** [YTVanced/Vanced#1479]
**Description**
I am Windows 11 user but Android already supported that Microsoft released. I installed YouTube Vanced on Windows 11 with smartphone layout portrait mode but i wan tablet layout with clear visible of YouTube thumbnail and texts. Please bring this feature. I having issue I can't see small text and thumbnail.

_Attach images/videos if possible. Also add any links to possible other applications with the said feature already implemented._

**Comment by milindgoel15** [comment]
Have you checked the official youtube app already? does it show a mobile layout or tablet?

**Comment by milindgoel15** [comment]
WSA is treated as a phone so there's no way that either vanced or official yt could give tablet layout.

**Comment by 1YuvrajS** [comment]
I am posting a photo of YouTube on Tablets just look like..
![images](https://user-images.githubusercontent.com/93419850/146739091-524b50d2-a9df-4cd5-9108-40bef151396e.jpeg)

**Comment by milindgoel15** [comment]
That has nothing to do with windows and YouTube layout. **If you wanna show layout, show it off YouTube app actually installed on windows subsystem for android**, not some random tablet image. That's of no use to anyone.

Hence, the answer to this issue stays the same.
