### ISSUE TITLE
[Bug] Dark mode miui 12.0.2. notification bar

### ISSUE THREAD

**Issue by znaczki654** [YTVanced/Vanced#148]
**Bug description**
When you turn on dark mode in miui 12.0.2.0 the notification bar on YouTube Vanced turns black with opacity and black text making it not clear. Would have wanted to optimise the app for dark mode to display white font like in the portrait mode. Phone: Xiaomi Redmi Note 8 Pro, android 10, miui 12.0.2.
Disabling dark mode solves the issue.
Neither setting dark mode at Vanced settings nor YouTube settings in YouTube Vanced app solves the issue. Also disabling/enabling miui enhancements doesn't solve the issue. Setting "disable dark mode for specific app" for YouTube Vanced to turn off dark mode doesn't work. You could just fix this to let disable dark mode from miui for that specific app or somewhat trick the font.
**Variant**
NonRoot: Yes
Root: No

**Vanced version**
15.43.32 - Build - 01.47.00

**Android version**
Android 10

**Device**
Xiaomi Redmi Note 8 Pro

**Steps to Reproduce**
Steps to reproduce the error:
1. Have Xiaomi phone with miui
2. Enable dark mode
3. Open app
4. Turn on video
5. Make it full screen (landscape)
6. Show notification bar - text is black, bar is black
7. In portrait mode notification bar is black text is white.

**Expected behavior**
Make text in the notification bar white when in landscape mode using miui dark mode.

_Attach images/videos if possible. These can be helpful in solving the issue._
![Screenshot_2020-11-04-03-29-46-995_com vanced android youtube](https://user-images.githubusercontent.com/27486533/98067447-d76b7b00-1e59-11eb-89b1-395af6fa6361.jpg)
![Screenshot_2020-11-04-03-29-52-107_com vanced android youtube](https://user-images.githubusercontent.com/27486533/98067469-e4886a00-1e59-11eb-80ef-3ee9c38775d0.jpg)

**Comment by milindgoel15** [comment]
It's an issue with MIUI. We can't fix it, sorry! We are closing this issue. Feel free to reopen if you still face any issues.
