### ISSUE TITLE
[question] When will the Material You widgets be added to Vanced Music?

### ISSUE THREAD

**Issue by PicoPlanetDev** [YTVanced/Vanced#1480]
![Screenshot_20211217-212546](https://user-images.githubusercontent.com/50522829/146648815-452f93da-4a5d-4861-8d77-aa2755f979b8.png)
![Screenshot_20211217-212523](https://user-images.githubusercontent.com/50522829/146648818-e5d9213f-b119-4b61-b1e2-9fc263eddb71.png)
Currently YouTube Music has 3 widgets now with 2 being part of Google's Material You update. When will YT Music Vanced get these widgets, or is it even planned?

**Comment by milindgoel15** [comment]
We didn't design or make YouTube music. Yt music vanced just gives what google gives but with ad blocking and bg playback. 

So you are receiving what google is giving you.

**Comment by KevinX8** [comment]
Update your vanced music version, the latest version has them

**Comment by PicoPlanetDev** [comment]
On the latest version but they aren't appearing. It's 4.57.52 correct? If so maybe it's a server side update.

**Comment by Harmonie666** [comment]
> Update your vanced music version, the latest version has them

Even tho I'm on Android 10, and I won't have these new widgets anyways, I would still like to update YTM Vanced from 4.39.50 to new base, but apparently "Enforce Repeat" stops working in the new version.
I hope it can fixed one day, since it's a very important feature :)
