### ISSUE TITLE
[Idea] Music service for assistant

### ISSUE THREAD

**Issue by Cartman34** [YTVanced/Vanced#1481]
For now, google assistant is not recognizing yt vanced as music service.
Please, I would like to launch at least "Hey google, play music"
And if possible
"Play my playlist jazz"
"Play eddy de pretto"

**Comment by milindgoel15** [comment]
Use root version of yt music vanced. Not possible with non-root packages.

**Comment by Cartman34** [comment]
Rooting my phone is not a solution.
Is this an Android limitation ?

**Comment by milindgoel15** [comment]
It's a limitation from google. Google only designed google assistant to use some specific package name to use as music service which non-root cant fulfil. SO the only solution is to use root packages.

**Comment by Cartman34** [comment]
Ok, but what about "more service section" ? There are Spotify, Deezer & Apple Music in it, but these ones are not google apps.

**Comment by milindgoel15** [comment]
I said that google defined specific package names, I didn't say "google only package names". both are different. Google defined all those apps which could use music service.
