### ISSUE TITLE
[Idea] "Local" Subscriptions Folders

### ISSUE THREAD

**Issue by bakinazik** [YTVanced/Vanced#1484]
**Description**
Let's folder the channels and see only the channels belonging to that folder from the top of the subscribers tab. All artists we subscribe to because of youtube music continue to appear in our subscription list. It would be great if you could prepare a system based on it.
Likewise, these subscription folders should be able to be saved and exported using the import and export method.

**Comment by bakinazik** [comment]
or if this system is too big to do, you can at least add an option to hide the artist channels we subscribe to from the subscription list on youtube music.

**Comment by milindgoel15** [comment]
It's YouTube, not newpipe.

**Comment by bakinazik** [comment]
dude just consider! at least we should be able to hide artist subscriptions

**Comment by bakinazik** [comment]
youtube does nothing about this, at least try to add it as the vanced team.

**Comment by milindgoel15** [comment]
Not possible sar

**Comment by bakinazik** [comment]
got it! thanks
