### ISSUE TITLE
[Bug]  phone status bar not showing while playing video in portrait mode in YouTube vanced . Variant : non root . Version: 16.29.39 . Android version :10 .

### ISSUE THREAD

**Issue by Uday7raj** [YTVanced/Vanced#1486]
**Bug description:**
Replace me with a clear and detailed description of the bug.

**Have you read vanced guides already? (YES/No)**
If your answer is no, please consider reading before creating this issue. The guides can be found in the readme section of this repository. 

**Variant:**
Non-Root/Root

**Vanced version:**
Replace me with the exact version of vanced you are using. It is mandatory to report issues from the latest available versions only. For example, v16.16.38

**Link used to download vanced:**
Replace here with the source/link you used to download and install on your device. 

**Android version:**
Replace me with the version of Android your device have. For example, Android 11 

**Device:**
Replace with the name of the device on which you faced the bug. For example, Samsung Galaxy S8

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
3. ....

**Expected behaviour:**
Replace me with a description of what you expected should happen and what happened instead.

_Attach images or videos or logcats in case of crashes if possible. These can help solve the issue._

**Comment by milindgoel15** [comment]
Known, will get fixed automatically with next updates.

And please make issues in proper manner.
