### ISSUE TITLE
[IDEA] Youtube Vanced for Android TV

### ISSUE THREAD

**Issue by dluigi** [YTVanced/Vanced#1488]
I'm using Xiaomi Mi Box 4S streamer running Android operation system.
Why there is no option to use Youtube Vanced in there already?
This app is running on mobile phone for years but no option for smart TV's.. why is that?

**Comment by TheAmazingBen100** [comment]
Vanced is not adapted for use on TVs. For a Vanced-like TV experience please use SmartTubeNext (not made by vanced)
