### ISSUE TITLE
[Bug] Cant see polls in subscription section and community tab isn't opening.

### ISSUE THREAD

**Issue by VarunBanka** [YTVanced/Vanced#1489]
YouTube vanced

**Bug description:**
Cant see polls in subscription section and community tab isn't opening. I have tried all the troubleshooting methods but nothing worked.

**Have you read vanced guides already? 
YES

**Variant:**
Non-Root

**Vanced version:**
16.29.39

**Link used to download vanced:**
Vanced manager

**Android version:**
Android 11 

**Device:**
Samsung Galaxy M12

**Expected behaviour:**
In the near future I am looking forward 
, for this bug to get fixed as soon as possible.
Thankyou.

![Screenshot_20211223-191050](https://user-images.githubusercontent.com/88031057/147248572-38c2e038-1190-4cdd-b4f9-e30e6a5bec39.jpg)

![Screenshot_20211223-191137](https://user-images.githubusercontent.com/88031057/147248686-193b6295-1859-4e8b-b133-7fbb23403586.jpg)

**Comment by TheAmazingBen100** [comment]
This is caused by people mindlessly enabling all the ad settings.
Please revert your ad settings back to the defaults (only general ad removal turned on, everything else off).

**Comment by VarunBanka** [comment]
> This is caused by people mindlessly enabling all the ad settings. Please revert your ad settings back to the defaults (only general ad removal turned on, everything else off).

Okay, thanks:D
