### ISSUE TITLE
[Bug] Swipe up video overlay in landscape not functioning.

### ISSUE THREAD

**Issue by JBustin5** [YTVanced/Vanced#149]
**Bug description**
While watching a video, swiping up will normally display subscribe button and suggested videos etc. This is not functioning. 

**Variant**
NonRoot: Yes
Root: No

**Vanced version**
15.43.32

**Android version**
Android 10

**Device**
Samsung Galaxy Note 20

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2. Play video.
3. Turn landscape.
4. Swipe up.

**Expected behavior**
Subscribe button, suggested video overlay should appear.

*****image is of actual YT app*****
 #![Screenshot_20201104-112044_YouTube](https://user-images.githubusercontent.com/73940785/98105372-cdfd0580-1e8f-11eb-95c4-20967a1ebe0f.jpg)

**Comment by JBustin5** [comment]
Figured out that this is linked to the Alpha Comment Placement setting. Bug is fixed when this is disabled.

**Comment by milindgoel15** [comment]
Please update to the latest v16.16.38 if you haven't already. We are closing this issue. Feel free to reopen if you still face any issues.
