### ISSUE TITLE
[Idea] Adjust time according to playback speed.

### ISSUE THREAD

**Issue by bartoszek** [YTVanced/Vanced#1491]
Currently seek bar shows playback time plus reduced time excluding skipped segments if sponsor block is enabled. 

After switching playback speed it would be more informative to show time info adjusted to playback speed e.g: 12:00 -> 10:00(x1.2) like in SmartTubeNext for Android TV app.

**Comment by TheAmazingBen100** [comment]
Ask Google instead!
It is not possible to implement that unless if Google added it or if there was an API with user-submitted/auto-generated times for sped-up videos.

**Comment by bartoszek** [comment]
@TheAmazingBen100 what? just divide video distortion returned by ytv3 api by speedup factor, and volila :smirk:
https://github.com/yuliskov/SmartTubeNext/blob/4273bae63a93eb021e8f05724c2c72e9bf46de2b/smarttubetv/src/main/java/com/liskovsoft/smartyoutubetv2/tv/ui/widgets/time/EndingTimeView.java#L89
