### ISSUE TITLE
[Idea] Expand the quality preferences

### ISSUE THREAD

**Issue by Szwagi** [YTVanced/Vanced#1493]
**Description**
The current quality preferences are simply "prefer high quality" or "data saver".
It would be great to be able to pick a specific resolution that playback would default to.
This is mostly a problem when viewing 60fps gaming footage. My app is set to "prefer high quality", but videos very often start in 480p which doesn't support 60fps. Lower resolutions also have a lower bitrate, making some high action gaming videos not pleasing to watch even at 720p/1080p.
There also exists a smaller problem where the app decides to change the quality to 144p just because my wifi cut off for 1 second, which this could potentially fix.

_Attach images/videos if possible. Also add any links to possible other applications with the said feature already implemented._
This option exists in a lot of "youtube enhance" extensions for desktop browsers.

**Comment by milindgoel15** [comment]
Use vanced's preferred video quality wen?
