### ISSUE TITLE
[Bug] Instant Crash on Vivo Origin OS Ocean

### ISSUE THREAD

**Issue by Chilluminati91** [YTVanced/Vanced#1497]
**Bug description:**
Can not properly get YouTube Vanced to run on the Vivo x70 Pro Plus on the newest Origin OS Ocean Beta.
When installing from Vanced Manager I get a security risk warning (which I can ignore). The App is then installed and shows on the homescreen.
Vanced Manager is stuck in an unlimited install loop and when starting YouTube Vanced it closes immediatly.

**Have you read vanced guides already? (YES/No)**
Yes

**Variant:**
Non-Root

**Vanced version:**
v16.29.39

**Link used to download vanced:**
https://vancedapp.com/
Same with apkmirror latest version.

**Android version:**
Android 12

**Device:**
Vivo x70 Pro Plus

**Steps to Reproduce**
1. Install either from Vanced Manager or apkmirror.
2. Skip Vivo Security Warning
3. Open YouTube Vanced -> Instant Crash

**Expected behaviour:**
Everything worked on Origin OS 11.

![Screenshot_20211230_200342](https://user-images.githubusercontent.com/47525435/147781490-57ebd7d4-cbcf-41c8-84bd-817e7bb3caf5.jpg)
![Screenshot_20211230_200354](https://user-images.githubusercontent.com/47525435/147781492-34cd2b81-8771-49e0-97f1-393eabcf8423.jpg)

**Comment by milindgoel15** [comment]
Give logs

**Comment by Chilluminati91** [comment]
Logs are not possible to access. Manager is stuck at second screen, can not press on cancel and if i force close and reopen logs are gone.
When trying to install via ADB I get this error: Failure [INSTALL_FAILED_ABORTED: User rejected permissions]

It must be related to split apk, ive found a joined single apk version which did install (although same warning) fine.

**Comment by gghhkm** [comment]
I've seen multiple issues with Vivo and Origin OS, unfortunately there's not much we can do because none of the staff members have a Vivo device, and so we can't debug it. you could help out by providing a logcat. [Guide Here.](https://telegra.ph/Bug-Reports-10-17)

**Comment by Chilluminati91** [comment]
Just wanted to produce a logcat but the problem seems to have fixed itself?!
Started up Vanced Manager, installed YouTube Vanced (not even redownloaded, just used the downloaded version) and didnt get the risk detection window but a simple install app view. YouTube Vanced now running flawlessly.

Will try to dump a logcat if this ever pops up again, really weird.
