### ISSUE TITLE
[Idea] ability to enable video ads for channels that user pics

### ISSUE THREAD

**Issue by quentincaffeino** [YTVanced/Vanced#1498]
**Description**

Recently LTT posted a [video](https://youtu.be/Nz9b0oJw69I) about thumb down removal, one of the points of that video was talking about vanced and how it could help solving this issue in the future by collaborating with ryd extension. What he mentioned on that video is that for some yt creators, especially small - revenue gained from platform is really essential. And seeing how he made the decision to promote tool that affects him but helps users I think it would be nice to show that we as a community also can do good not only for ourselves.

I think having in settings a list of user subscriptions where user could pick channels that he wants to support by enabling showing ads on those would be great. 

Adding this would make more creators to not be afraid to advertise vanced as they know that real supporters of the channel would still keep supporting them.

**Comment by KevinX8** [comment]
It's going to be in the next update along with RYD

**Comment by quentincaffeino** [comment]
Awesome, thanks for instantaneous response :)

**Comment by Itay123TheKing** [comment]
I'm not sure how the YT servers know that you actually watched the ad, but would it be possible for you to play both the ad and the video somehow? perhaps in splitscreen, or one being in a miniplayer of sorts? that way the viewing experience wouldn't be entirely interrupted.

**Comment by milindgoel15** [comment]
> I'm not sure how the YT servers know that you actually watched the ad

The same way it detects everything else since vanced is just built on top YouTube app itself.

About the video ads, it will come up the same way as official YouTube gives.

**Comment by Itay123TheKing** [comment]
> The same way it detects everything else

I mean it's not like someone is watching over you to make sure you've watched the ad, so perhaps it's possible to forge the packet or something.

**Comment by quentincaffeino** [comment]
> but would it be possible for you to play both the ad and the video somehow? perhaps in splitscreen, or one being in a miniplayer of sorts?

Good idea but the amount of work required to develop and support such solution would be unreasonable really.

**Comment by milindgoel15** [comment]
Implemented with v17 release. Closing this issue
