### ISSUE TITLE
[Idea] Android TV YouTube Vanced

### ISSUE THREAD

**Issue by UnderFact** [YTVanced/Vanced#1500]
The Android TV version of YouTube could theoretically get the same treatment as the mobile app, e.g. no ads, sponsorblock, black dark mode…

This could already be in the works, or utterly impossible, but the idea definitely felt worth pitching

**Comment by TheAmazingBen100** [comment]
It already exists. It's called smarttubenext. Do yourself a favour and get it.
[https://vancedapp.com/tv](https://vancedapp.com/tv)
