### ISSUE TITLE
[Idea] Kids Safety for YouTube

### ISSUE THREAD

**Issue by arpitsinghi** [YTVanced/Vanced#1503]
Hi

My child is 2 years old and gets constantly Bombarded by icecream videos. Unfortunately, due to Google suggestions and watchtime generated we are not able to remove it

We are only able to remove if they appear on homepage like below
![IMG-20220101-WA0100](https://user-images.githubusercontent.com/25055654/147853324-f48a5f11-3699-493c-9bd3-b24202819ca3.jpg)

But we don't get same options in 

Recent
And
Watch history

![IMG-20220101-WA0099](https://user-images.githubusercontent.com/25055654/147853340-02c1b952-f7a3-46e5-82fc-aa088c6678f0.jpg)
![IMG-20220101-WA0098](https://user-images.githubusercontent.com/25055654/147853342-14019eae-763e-4204-99a3-b2deeb4e85ef.jpg)

This is affecting my child in a big way and she gets triggered by this to demand icecream which in excess  is unhealthy for her

I would request you to add both options in menu
Not interested : removes particular video from YouTube suggestion

Don't Recommend Channel : stops recommending the channel, this helps if the channel has overall toxic quality videos

Please add it in the recent and history videos

Thanks for considering

**Comment by KevinX8** [comment]
You should probably be using the YouTube kids app as it has much more restrictions on what it recommends kids

**Comment by arpitsinghi** [comment]
Hi @kevinX8,

Thank you for your prompt reply 🙏🏻

I explored YouTube kids app after you had suggested and had explored it before as well

Unfortunately, there is no option to view history and remove SPECIFIC video from YouTube kids as well.

![Screenshot_20220101-222249](https://user-images.githubusercontent.com/25055654/147855661-fea22324-7b0a-4308-8209-5d5c6ad8a9ad.jpg)
![Screenshot_20220101-222252](https://user-images.githubusercontent.com/25055654/147855662-dce27a49-8bfb-4854-9476-54a7bc72be4d.jpg)

Deleting entire history is not a very right option

It does give you an option to block particular video on the spot which is very tedious as child becomes stubborn to give you the phone while watching and these videos do come many a times from suggested videos


Also it contains ads 😒

![Screenshot_20220101-221343__01](https://user-images.githubusercontent.com/25055654/147855519-6283e32a-d2ce-4457-9ed7-cbcaedee74ff.jpg)

I request you to please consider this as this may help other people in the community to take more charge on their digital life

If u can consider duplicating those two menu option from YouTube app homepage to history page, that would be great 🙂

Thanks

**Comment by KevinX8** [comment]
The algorithm YouTube uses for YouTube kids has to be the same for every kid, same for the ads due to COPPA rules in the US, so stuff like targeted ads and videos about ice cream wouldn't be recommended on it. Also from what I've seen YouTube kids rarely shows ads because YouTube gains next to no money from the ads in it as they aren't targeted. Basically you don't have to manually block ice cream videos, YouTube kids will just not recommend them due to COPPA rules.

**Comment by arpitsinghi** [comment]
Hi KevinX8

You are right about ads i believe, yes they are quite less over there or not to my knowledge

But w.r.t to icecream videos and history issue the problem still persist

I am attaching below screenshot

![Screenshot_20220101-223347__01](https://user-images.githubusercontent.com/25055654/147855912-7ecb73cc-af5e-4519-918d-99207881f404.jpg)


I genuinely appreciate your response 🙏🏻

Please consider request If it's not very difficult for you 🙏🏻

**Comment by KevinX8** [comment]
Well from what I can see in YouTube kids is not as easy to find them, on YouTube they were shoving them into your kids face, best solution would be to explain to your kid why eating so much ice cream is bad etc so that they don't keep looking for ice cream videos

**Comment by arpitsinghi** [comment]
I agree with you Kevin, we have been trying hard to make her understand.

But these suggested videos keep coming up. Also the child is stubborn for us to change the video when she watches which generates high watchtime and again it takes the suggestion loop, that is how YouTube suggestion algorithm work

Also, it's not just about ice cream, there are many videos which as a parent we realise that some are entertaining + education others are just time waste

Above two options are very powerful to streamline YouTube Suggestion Algorithm and overall child influence

**Comment by milindgoel15** [comment]
That's the thing with kids nowadays. You have to try hard to make them understand whate right for them and what's not. You even have to take serious steps to make sure they don't see such videos. 

But instead of doing that, you want an entire platform to work according to your child. That's not the solution to the problem. You are only teaching your kid to look for another alternative to watch such videos thru another means. You have to teach your kid to play with toys and your family instead of going towards this entire step.
