### ISSUE TITLE
[Bug] I can't use the Chromecast function

### ISSUE THREAD

**Issue by Pokecrafter2019** [YTVanced/Vanced#1504]
I can't use the Chromecast function, it appears that I have to update Google Play Services, but it's already up to date.
![Screenshot_20220101-195741](https://user-images.githubusercontent.com/96960675/147861834-6026a49d-8529-42f1-8add-58ad1e25be76.png)
Obs: The image is in Portuguese, if you cannot understand please translate

**Comment by TheAmazingBen100** [comment]
Casting is a MicroG bug, see this for more details: [#688](https://github.com/YTVanced/Vanced/issues/688#issuecomment-992102591)

**Comment by Pokecrafter2019** [comment]
Oh ok thx dude
