### ISSUE TITLE
[Question] Why is Milind Goel trying to suppress my feature requests even though clearly some more people are interested in it?

### ISSUE THREAD

**Issue by Mesum-Hussain** [YTVanced/Vanced#1506]
**Description**
I requested for a feature twice a few months ago and I am sure it's not duplicate of any feature request. @milindgoel15 beged to differ back then and closed both of my requests and was behaving very rudely. Few days ago some other people noticed my closed request issue and they expressed that they would like to have this feature too. Noticing this activity, @milindgoel15 restricted the communication in those issue threads just to the maintainers, that means no other person can express if they want that feature or not. 
I genuinely think that it is @milindgoel15's personal opinion that this feature is not useful and people wouldn't like to have it, and based on his/her preconceived notions @milindgoel15  is closing those issues entirely and stopping free speech by restricting the thread.

I would like to know from @milindgoel15  why he/she is portraying such a behaviour? In my opinion @milindgoel15  is misusing their powers as a maintainer, which nobody in this world has a right to do.

The issues where #1207 and #1189

**Comment by darkRaspberry** [comment]
Hey I genuinely respect your opinion. 
Why don't you give a small try about that feature and push a PR referencing it.😉

Most probably it will be merged. The benefits of open source app.

**Comment by milindgoel15** [comment]
> Most probably it will be merged. The benefits of open source app.


Vanced ain't open source.

**Comment by Mesum-Hussain** [comment]
> Hey I genuinely respect your opinion. Why don't you give a small try about that feature and push a PR referencing it.😉
> 
> Most probably it will be merged. The benefits of open source app.

I think you aren't aware that YouTube Vanced is not open source. 
If it was open source, I would have rather forked it than dealing with @milindgoel15.

But YouTube Vanced is a close sourced Mod of the original YouTube app. 
Haven't you guessed it by now from the striking resemblance to the official YouTube app?

**Comment by Mesum-Hussain** [comment]
> > Most probably it will be merged. The benefits of open source app.
> 
> Vanced ain't open source.
> 
> Plus the idea of us is to remove the tab whole together the way the original issue wants to have (334). The OP's idea is to hide the feeds from those tabs. So hiding the tab is somewhat more intuitive and cleaner than hiding the feeds. But unfortunately the OP's just doesn't want to understand this logic and also the fact that he wants an whole app to change instead of changing his own habits.

This explanation certainly justifies your point in your head, but I wonder why don't you see all the dislikes you got on some of your replies to those issue and other people asking for it?
If it was just me asking and nobody else cared (like a few months ago) then I would have just kept quiet (like I was already doing). But when some other people also want it this way and you are restricting the discussion by limiting it only to the maintainers, I don't see any reason for changing my own habits and tolerating a rude maintainer's unjust behaviour.

What one person thinks doesn't matter, if more than one person is saying then it should not be suppressed. In your case, I don't see anyone supporting your opinion in the thread of those issues so essentially you are only one with that opinion no matter how right you think it is.

I wouldn't have bothered much if you just had kept the issue open and let people rant that they want it implemented and get ignored big time. Or simply let the comments remain open to all even if the issue is closed. 

What made me angry big time is that you restricted the discussion to the maintainers, of every single issue which was mentioning #1207 and #1189. This clearly is restricting free speech and discussion to favour your agenda. And you have no right to stop people from discussing about it even if you are a maintainer of the project!

I warn you to correct your mistakes or I am going to do my part and report this illigal repo.

**Comment by KevinX8** [comment]
No one is suppressing your rights to discuss it, you can discuss it elsewhere if you want, we decide what features we want to add, your two issues were closed and locked by Milind as he saw them as too similar to #334 which is fair enough, they are very similar.
 
Discussion was locked on 334 because people kept saying "vanced is abandoned, +1 +1" which is not constructive to the issue, it would be much more helpful if someone joined the discord and looked into the smali code of the latest vanced beta on where to add it. Vanced is not a company and vanced is not a paid app so everything is done by volunteers in our free time.

This could have been communicated better to you so sorry for that.

**Comment by Mesum-Hussain** [comment]
> No one is suppressing your rights to discuss it, you can discuss it elsewhere if you want

@milindgoel15  did try to suppress by locking every single issue where #1207 and 1189 is mentioned. I don't see any legitimate reason to lock evey single one of them. Closing would have been fine if @milindgoel15  didn't wanted to work on them, but why go extra mile to lock evey single one of them?
And why can't I discuss about this in the thread which is created specifically for this topic? I am not going off topic. Why should I go elsewhere to discuss the topic and not in the thread dedicated to it?



>we decide what features we want to add.

Fair enough, could have left people ranting about it in the thread getting badly ignore instead of locking the thread entirely in that case. Closing the issue wasn't a problem but restricting the discussion is.

>your two issues were closed and locked by Milind as he saw them as too similar to #334 which is fair enough, they are very similar.

Whatever @milindgoel15's personal opinion was (or your personal opinion for that matter), it doesn't justify locking every single issue even so slightly mentioning this topic. And I don't it believe people should be tolerating @milindgoel15  impolite behaviour regardless of the outcome of this discussion.

>it would be much more helpful if someone joined the discord and looked into the smali code of the latest vanced beta on where to add it. 

If that's the case then I will look into it, but then I still doubt @milindgoel15 will create some hinderance as he just went out of his way to lock evey single issue related to this topic, can't predict what can happen.

>Vanced is not a company and vanced is not a paid app so everything is done by volunteers in our free time.

I know this and appreciate the effort of every single person who is contributing. But I just expect people to behave politely and not go out of their way to be a menace.

> This could have been communicated better to you so sorry for that.

I understand. No problem. I just request you to atleast unlock all those threads if no opening that issue back. Can you please do that?

**Comment by milindgoel15** [comment]
Was i going to murder you? Lmao

You calling me a menace really tells that I was having some gun pointing towards your head to murder/kill/cause you any physical harm. And I was very polite in all my comments. Tell me where did I used any abusive words? Did I call you anything? Nope, a 100% NOPE.

So better to watch your words next time. 

I accept the fact I closed your both issues but you were indeed making 2 issues for same extension & same feature suggestion. And since the 334 issue is very very similar to the idea of urs and to prevent repeated messages, i decided to lock it. 

But anyways you are never gonna accept anything so i won't bother with your issues.

Good luck! Opened one of your issues for you.

**Comment by Mesum-Hussain** [comment]
> Was i going to murder you? Lmao
> 
> You calling me a menace really tells that I was having some gun pointing towards your head to murder/kill/cause you any physical harm. And I was very polite in all my comments. Tell me where did I used any abusive words? Did I call you anything? Nope, a 100% NOPE.
> 
> So better to watch your words next time.
> 
> I accept the fact I closed your both issues but you were indeed making 2 issues for same extension & same feature suggestion. And since the 334 issue is very very similar to the idea of urs and to prevent repeated messages, i decided to lock it.
> 
> But anyways you are never gonna accept anything so i won't bother with your issues.

Bla bla bla


>Opened one of your issues for you.

Please open #1207 in that case.

**Comment by milindgoel15** [comment]
I opened the conversation, not the issue. The issue will stay closed.
