### ISSUE TITLE
[Question] Have a YouTube Premium Switch

### ISSUE THREAD

**Issue by 123-bott** [YTVanced/Vanced#1507]
This is both a question and a suggestion.

I have been using YT Vanced for a long time but I decided to subscribe to YouTube Premium because I just want to (really that's the reason). I didn't switched to the regular YouTube App because it's so bad, it has so many clutter like the shorts button. Been happy using it. 

My question is does YouTube still give the channels I watch to because I use YouTube Vanced? I know (I read it on a Reddit Post) that YouTube doesn't pay the creator if the view(er) uses Adblocker both in mobile and web. I just want to be sure because maybe I am wasting my money (I know I am wasting it, but I want to support the channels I watch) by paying for YT Premium.

If really helps if the app has a toggle to disable the AdBlock or has a switch for YouTube Premium users. I know you are planning to add the feature #1498 that lets the user pick channels but I want to ask if you could disable it fully with a switch.

Thank you.

**Comment by milindgoel15** [comment]
Once you subscribe to YouTube premium, it doesn't matter what client you use, you are supporting every creator. So if you use vanced with yt premium, there's no issue. Plus vanced is thinking for enabling ad blocking to support some creators as in the issue mentioned. In both of the ways, you will be supporting creators.

**Comment by KevinX8** [comment]
Sure, adding a global switch is easy, YouTube premium pays YouTubers more than if you watched ads and it still pays them while using vanced yes
