### ISSUE TITLE
[Bug] Yt Vanced music Pern Auto Repeat toggle no longer works

### ISSUE THREAD

**Issue by thekcat3** [YTVanced/Vanced#1508]
There is literally no place to report vanced music issues, sorry.

**Bug description:**
I think all other settings works but I can only confirm  that shuffle works and everything under design works, but the repeat toggle does not work. Worked in older versions

**Have you read vanced guides already? (YES/No)**
Yes

**Variant:**
Non-Root(I think?)

**Vanced version:**
4.57.52

**Link used to download vanced:**
Used Vanced manager

**Android version:**
10

**Device:**
G8X ThinQ

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2. Go to vanced settings
3. Toggle "Permanent Repeat Toggle"
4. Click in any video/radio station
5. Repeat will not be on

**Expected behaviour:**
Expected repeat to turn on, it didn't. (Sorry If any of my text sounds agressive, it is not my intention, sorry if there was an actual proper place to report vanced music bugs, thank you for your time and the great apps)

_Attach images or videos or logcats in case of crashes if possible. These can help solve the issue._

**Comment by milindgoel15** [comment]
Yes, the issue is already known. And we had already mentioned it in the changelog too before anyone tried to update or install music vanced.

![Screenshot_2022-01-02-21-21-36-602_com.vanced.manager.jpg](https://user-images.githubusercontent.com/45682747/147881275-25d12316-af68-469d-bbc7-4b238ba9de5e.jpg)

**Comment by milindgoel15** [comment]
Don't worry, I closed this issue we were already aware of this. Also, I have put the necessary labels to keep records and to mark any future duplicates.

**Comment by Harmonie666** [comment]
I would also like to see this feature fixed, as this is the only issue that prevents me from updating to new base. Thanks for the report 👍🏻
