### ISSUE TITLE
[Idea] VolumeBooster

### ISSUE THREAD

**Issue by JohnuuDev** [YTVanced/Vanced#1509]
A volume booster for Youtube, will be a nice feature.

**Comment by milindgoel15** [comment]
Duplicate of #1143

**Comment by PuNiShEr202** [comment]
My vanced youtube wont connect to my internet it keeps saying no internet connection

**Comment by milindgoel15** [comment]
And why the hell are u saying this in an issue irrelevant to yours. Please create or read issues concerning your problem only.

The solution to your problem is in vanced troubleshooting which can be found in the readme section of this repository.
