### ISSUE TITLE
[Bug] Watch-History doesn't update

### ISSUE THREAD

**Issue by bloedboemmel** [YTVanced/Vanced#1510]
**Bug description:**
Normally Youtube logs all watched Videos and shows how far i watched one video

**Variant:**
Non-Root

**Vanced version:**
v16.29.39

**Android version:**
Android 11 

**Device:**
Oneplus 6T

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2. Click on any Video
3. Click on History

**Expected behaviour:**
Watched Video schould be there

**Comment by TheAmazingBen100** [comment]
[#301](https://github.com/YTVanced/Vanced/issues/301#issuecomment-752574012) has your solution.

**Comment by bloedboemmel** [comment]
Sorry, my mistake
