### ISSUE TITLE
[Bug] Google play update

### ISSUE THREAD

**Issue by KingTino104** [YTVanced/Vanced#1511]
**Bug description:**
If i download youtube vanced / music vanced it will say it needs update in google play.

**Have you read vanced guides already? (YES/No)**
YES

**Variant:**
Root

**Vanced version:**
16.29.39

**Link used to download vanced:**
https://vancedapp.com/

**Android version:**
Android 10 (TB-X606F-S300429_211101_BMP)

**Device:**
Smart Tab M10 FHD Plus with Smart Charging Station / Google Assistant (Lenovo Tab M10 FHD Plus)

**Steps to Reproduce**
Install youtube vanced/music

**Expected behaviour:**
It shouldn't ask me to update it.

_Attach images or videos or logcats in case of crashes if possible. These can help solve the issue._
i think my description descripes it enough

**Comment by milindgoel15** [comment]
Send screenshot of what you are really getting. It's hard to understand based on what you wrote.

**Comment by KingTino104** [comment]
![IMG_20220106_150437](https://user-images.githubusercontent.com/90916297/148398729-ca9bb3da-6b98-4409-aa2c-b6eac10c592f.jpg)

**Comment by milindgoel15** [comment]
They will. Cuz the root variant uses the same package name as official. If you don't wanna see them, you can either detach YouTube from play store using temifi or use non-root version. 

The detach guides can be found in troubleshooting in the readme section of this repository.
