### ISSUE TITLE
[Bug] rep

### ISSUE THREAD

**Issue by NoMandy65** [YTVanced/Vanced#1514]
**Bug description:**
Opening vanced lead to a screen stating Im offline and not connected to the internet. Tried redownloading both vanced manager and yt vanced but leads to the same issue 

**Have you read vanced guides already? 
Yes

**Variant:**
Non-Root

**Vanced version:**
16.29.39

**Link used to download vanced:**
https://www.google.com/url?sa=t&source=web&rct=j&url=https://vancedapp.com/&ved=2ahUKEwiEx7KL1qL1AhUfxzgGHd6BCPMQFnoECAQQAQ&usg=AOvVaw0Q0FqQt24ZeKZb5VGq5Nv5

**Android version:**
Android 10

**Device:**
Sony XZ2

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app

**Expected behaviour:**
The app should open as normal instead of showing a screen saying im offline

![Screenshot_20220109-012610](https://user-images.githubusercontent.com/97356312/148653653-62402dd7-ba01-4476-992e-3f7ef4450737.png)

**Comment by TheAmazingBen100** [comment]
[#786](https://github.com/YTVanced/Vanced/issues/786)
