### ISSUE TITLE
[Bug] Edit and Upload Video Problem

### ISSUE THREAD

**Issue by cuynu** [YTVanced/Vanced#1520]
**Bug description:**
On YouTube Vanced, i can't upload or edit details video. While choose video its stuck loading.. 

**Have you read vanced guides already? (YES/No)**
YES

**Variant:**
Non-root

**Vanced version:**
v16.29.39

**Link used to download vanced:**
https://vancedapp.com

**Android version:**
Android 10

**Device:**
Sony Xperia XZ2

**Steps to Reproduce**
Steps to reproduce the error:
1. Open YouTube Vanced
2. Click + Button on homepage
3. Choose any video.

**Expected behaviour:**
Fix edit/upload video Problem 

_Attached images
![Screenshot_20220110-174058](https://user-images.githubusercontent.com/90895715/148753746-a5acde01-a616-41c1-9ba3-b5be1c5bdbe8.png)

**Comment by TheAmazingBen100** [comment]
Nonroot has issues when uploading videos because of MicroG issues. Please use root/stock to upload videos and manage your channel.
