### ISSUE TITLE
[Request] Please accept $XNO (Nano) donations 

### ISSUE THREAD

**Issue by avndp** [YTVanced/Vanced#1527]
Have been using YouTube Vanced since 2+ years and loving it. Would like to donate Aegis using Nano (https://hub.nano.org/). Please allow me to!

It is as simple as installing Natrium Wallet and pasting the address at Github. Just like how [LibreTorrent](https://github.com/proninyaroslav/libretorrent) , [Aegis](https://github.com/beemdevelopment/Aegis/issues/864)  and others are doing at their donations tab.

Thanks.

**Comment by milindgoel15** [comment]
We don't accept any donations. Consider supporting us through adguard and brave referral links instead.
