### ISSUE TITLE
[Bug] "Shorts" are still appearing

### ISSUE THREAD

**Issue by Harmonie666** [YTVanced/Vanced#153]
**Bug description**
After I deactivated the annoying "shorts" short videos, with the new Vanced update, they are still showing up. In the main homepage, and under open videos aswell.

**Variant**
NonRoot: Yes
Root: No

**Vanced version**
15.43.32 - Build - 01.47.00

**Android version**
Android 10

**Device**
ROG Phone II

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2. Click on any video, or scroll down the home page.
3. You will still see "Shorts", even with "Shorts shelf removal" enabled.

**Expected behavior**
Fix this issue please.
![Screenshot_20201104-150224392 (1)](https://user-images.githubusercontent.com/73917917/98121483-a28a1300-1eaf-11eb-86c6-c219ad7d68df.png)

**Comment by milindgoel15** [comment]
Please update to the latest v16.16.38 if you haven't already. We are closing this issue. Feel free to reopen if you still face any issues.
