### ISSUE TITLE
[Question] cli flags?

### ISSUE THREAD

**Issue by gartensofa** [YTVanced/Vanced#1534]
I am trying to set vanced as an external player for the kodi media center running on android: https://kodi.wiki/view/HOW-TO:Use_external_players_on_Android#Working_Example
The example uses VLC with the following cli command: 
`org.videolan.vlc --fullscreen "videourl"`
Is there a command like this that would work for ytvanced?

**Comment by milindgoel15** [comment]
Vanced is not a video player. It's a YouTube app client.

**Comment by gartensofa** [comment]
That was a bit vague on my side, sorry.
I would only use ytvanced for youtube urls passed to kodi. One can define different apks for certain url formats. 
So to rephrase: Are there command line arguments to start a youtube video with ytvanced??

**Comment by milindgoel15** [comment]
There isn't any command line for YouTube as it's not a video player. YouTube dl might work for you as they offer numerous command line options.
