### ISSUE TITLE
[Bug] whenever I try to go into YouTube Vanced it tells me that it isn't connected to the internet even though normal YouTube works fine and as I've checked everything is updated to the latest version

### ISSUE THREAD

**Issue by X34stayalert** [YTVanced/Vanced#1535]
**Bug description: YouTube Vanced won't connect to the internet

**Have you read vanced guides already? (YES/No)**
If your answer is no, please consider reading before creating this issue. The guides can be found in the readme section of this repository: Yes

**Variant:**
Non-Root/Root: nonroot

**Vanced version:**
Replace me with the exact version of vanced you are using. It is mandatory to report issues from the latest available versions only. For example, v16.16.38

**Link used to download vanced:**
Replace here with the source/link you used to download and install on your device. 

**Android version:**
Replace me with the version of Android your device have. For example, Android 11: android 11

**Device:**
Replace with the name of the device on which you faced the bug. For example, Samsung Galaxy S8: Samsung Galaxy tab A 2019 and OnePlus 5t

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app

**Expected behaviour:* I expected it to connect just fine

_Attach images or videos or logcats in case of crashes if possible. These can help solve the issue

**Comment by TheAmazingBen100** [comment]
1: You didn't fill out the issue information correctly
2: [#786](https://github.com/YTVanced/Vanced/issues/786#) has your fix.
