### ISSUE TITLE
[Bug] Next/Previous and Autoplay Buttons missing on overlay.

### ISSUE THREAD

**Issue by pynoob11** [YTVanced/Vanced#1537]
**Bug description:**
For a few days now, autoplay has stopped working. There is no next/previous/autoplay button on the overlay(as seen in uploaded image). Autoplay option is enabled in settings too.
Tried clearing storage and cache of all yt and microG, uninstalling and reinstalling them. Uninstalled vanced manager and performed fresh installed. Tried older versions of all related apps. No fix yet.

Edit: Stock YouTube also has the same problem on my device. No such error on an MIUI device and an iPhone.

**Have you read vanced guides already? (YES/No)**
Yes.

**Variant:**
Non-Root

**Vanced version:**
16.29.39

**Link used to download vanced:**
https://github.com/YTVanced/VancedManager/releases/latest/download/manager.apk

**Android version:**
Android 11

**Device:**
OnePlus 8

**Steps to Reproduce**
1. Open the app
2. Play any video.
3. Wait for it to end.

**Expected behaviour:**
Expected next video to play and for there to be an autoplay/next/previous button on the overlay.

![Screenshot_20220115-064319](https://user-images.githubusercontent.com/40825704/149852729-2a992657-bc78-442a-aac8-1365cb76b0a9.jpg)

**Comment by pynoob11** [comment]
Issue was also on stock YouTube. Raising an issue at Google.

**Comment by milindgoel15** [comment]
> Edit: Stock YouTube also has the same problem on my device. No such error on an MIUI device and an iPhone.

Then it's an issue with the device you are having this issue on.
