### ISSUE TITLE
[Idea] Add support for 3rd party plugins

### ISSUE THREAD

**Issue by suhan-paradkar** [YTVanced/Vanced#1538]
Well, I guess this app would be better of supporting 3rd party plugins. I've seen apps like [Aliucord](https://github.com/Aliucord/Aliucord) (A modified discord client) do this. They use [pine framework](https://github.com/canyie/pine) to hook into java ART.

Some screenshots

![Screenshot_2022-01-18-17-23-03-34](https://user-images.githubusercontent.com/76830230/149933148-bc4cdb20-0fb7-48c4-94c5-fd3ee9a58819.jpg)
![Screenshot_2022-01-18-17-23-13-52](https://user-images.githubusercontent.com/76830230/149933177-d4536dea-819e-4adc-b562-fc91d3c437c7.jpg)

**Comment by milindgoel15** [comment]
The pine framework could make vanced buggy and very unstable. Hence, we might not implement this. 

If you want something to add to vanced, you can try coding them, that way we might add. You can just use the official YouTube APK > decompile it > apply ur code > recompile, sign > test.
