### ISSUE TITLE
[Question] comments are turned off

### ISSUE THREAD

**Issue by reef2009** [YTVanced/Vanced#1540]
Hi since a view weeks/months I often het the message below video's "comments are turned of"
Almost every livestream but normal video's too. See my screenshot

I can't find any setting to unlock this and no other users have the same probleem.
I already cleared cache, and app settings including Manager and microG. I even fully delete it but no fix. 

Is this a know setting of Just an issue? 

![Screenshot_20220118-205304__01](https://user-images.githubusercontent.com/1585138/150010072-aeb8d958-13d1-4234-a999-779f4fbaf258.jpg)

**Comment by TheAmazingBen100** [comment]
Check that comments removal isn't turned on in ad settings. Also check that restricted mode is not enabled too.

**Comment by reef2009** [comment]
Thnx yes comments removal found. Restricted mode not yet. Next livestream I'll check again!

**Comment by reef2009** [comment]
Sadly enoughe the probleem is'nt gone.
YouTube and YouTube vanced only open in restricted mode but it is turned off 🤔.

Only google workspace admins Could fix this. But its not manage by google workspace. 

Any ideas? 

![Screenshot_20220119-204722](https://user-images.githubusercontent.com/1585138/150204270-7178c72c-a713-4db0-972f-35547a60b283.jpg)
![Screenshot_20220119-204412](https://user-images.githubusercontent.com/1585138/150204280-3d230723-5929-42e8-8af5-eb5308f914e7.jpg)
![Screenshot_20220119-204240](https://user-images.githubusercontent.com/1585138/150204287-d20a33a6-1b5c-4bca-9966-7c021a061416.jpg)

**Comment by milindgoel15** [comment]
The restrictions are either controlled by your network operator or your Google account. Vanced has nothing do with this issue.

If it's network, just tell your operator to fix it or change your operator.

If it's Google account, follow [this](https://telegra.ph/Troubleshooting-for-vanced-03-19#E:-Offline-errors-with-gsuite-account).
