### ISSUE TITLE
[Bug] [UI/UX] Pressing the full-screen button is more prone to fast forwarding the video than going into full-screen mode

### ISSUE THREAD

**Issue by SimonHanel** [YTVanced/Vanced#1541]
Running YouTube Vanced 16.29.39 Build 01.54.00 on a OnePlus 6 running OxygenOS 10.3.12, Android 10.

I'm the type of guy that often has automatic screen rotation turned off on my phone, so I like to use the full screen button in video apps for most occasions.
I recently updated YouTube Vanced through the Vanced Manager from an old build. Can't remember what the older build was, but...

Sometimes, more often than not, when I press the full screen button when watching a video, it's more prone to pressing the timeline,  skipping to the end of the video than setting the video in full screen mode. I've [uploaded a video](https://youtu.be/1XU8nVx8Ww0) of an example of me clicking the full screen button a couple of times.

Maybe I'm just aiming a bit too low (heck, or even fat-fingering the button), but it wasn't this sensitive in the older build.
Usually I just tap the screen so that the on-screen options show up, and the timeline slider pops up, and then click on the timeline/drag the slider to the point where I want to fast forward to.

I hope I've provided adequate information, otherwise please let me know, and I hope this is something you can tweak for an update.
Thanks in advance.

**Comment by TheAmazingBen100** [comment]
vanced settings > misc settings > turn tap to seek off

**Comment by SimonHanel** [comment]
@TheAmazingBen100 That did the trick, thanks :)
