### ISSUE TITLE
[Idea] Disable SponsorBlock features while adding a segment

### ISSUE THREAD

**Issue by Itay123TheKing** [YTVanced/Vanced#1545]
**Description**
when adding a SponsorBlock segment that would overlap another segment or a replacement segment for one that starts/ends just a few milliseconds too early or late, it is extremely annoying not being able to skip to the desired location to place a start/end pin there.
The reason this annoyance occurs is because the app will automatically attempt to skip any existing segment so a lot of the time it is impossible to accurately add a new segment.

**Comment by milindgoel15** [comment]
Please make Sponsorblock issues in vanced [Sponsorblock repository](https://github.com/YTVanced/Integrations/issues) only.
