### ISSUE TITLE
Autoplay issues

### ISSUE THREAD

**Issue by Tristan7776** [YTVanced/Vanced#1548]
**Bug description:**
I am having an issue with the autoplay feature for vanced.
After a video has played completely and the next begins, I am unable to double tap to seek forward or backwards as well as play/pause the video. The last issue is one the new video has started and plays for a few moments the screen begins to timeout as in it dims the screen then turns off completely. My phone is a Samsung Galaxy s21 Ultra.

**Have you read vanced guides already? (YES/No)**
If your answer is no, please consider reading before creating this issue. The guides can be found in the readme section of this repository. 

**Variant:**
Non-Root/Root

**Vanced version:**
Replace me with the exact version of vanced you are using. It is mandatory to report issues from the latest available versions only. For example, v16.16.38

**Link used to download vanced:**
Replace here with the source/link you used to download and install on your device. 

**Android version:**
Replace me with the version of Android your device have. For example, Android 11 

**Device:**
Replace with the name of the device on which you faced the bug. For example, Samsung Galaxy S8

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
3. ....

**Expected behaviour:**
Replace me with a description of what you expected should happen and what happened instead.

_Attach images or videos or logcats in case of crashes if possible. These can help solve the issue._

**Comment by gghhkm** [comment]
Please fill out the issue template more completely thanks.

**Comment by TheKucel** [comment]
Same story.

Have you read vanced guides already? Yes

Variant:
Non-Root

Vanced version: lastest (18.02.33)

Link used to download vanced:
https://github.com/cuynu/ytvanced/releases/tag/18.02.33

Android version:
Android 13

Device:
Google pixel 7

Steps to Reproduce
Steps to reproduce the error:

Click on the video, wait until autoplay changes it to another, wait ~1min, tadaaa screen is black and video not playing.

Expected behaviour:
Video plays normally

**Comment by cuynu** [comment]
> Same story.
> 
> Have you read vanced guides already? Yes
> 
> Variant: Non-Root
> 
> Vanced version: lastest (18.02.33)
> 
> Link used to download vanced: https://github.com/cuynu/ytvanced/releases/tag/18.02.33
> 
> Android version: Android 13
> 
> Device: Google pixel 7
> 
> Steps to Reproduce Steps to reproduce the error:
> 
> Click on the video, wait until autoplay changes it to another, wait ~1min, tadaaa screen is black and video not playing.
> 
> Expected behaviour: Video plays normally

don't report unofficial vanced issue in official vanced repo
