### ISSUE TITLE
[Bug] Vanced returns to the top of subscriptions feed after watching a video or entering a channel from subscriptions feed

### ISSUE THREAD

**Issue by fosam** [YTVanced/Vanced#155]
**Bug description**
On the subscriptions tab, I'll scroll down and watch videos im my subscription feed and click on channels of those videos and after some time of browsing and watching, when i click the back button to go back where i left in the subscriptions i find myself at the top of the page so i have to scroll all the way down to find where i left, this can be cumbersome

**Variant**
NonRoot: Yes
Root: No

**Vanced version**
15.43.32 - Build - 01.47.00

**Android version**
Android 10.0 - Q

**Device**
Samsung Galaxy S9

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2. Click on 'Subscriptions'
3. Scrolll down and watch some videos there or click and enter a channel there.
4. Watch some videos on that channel, and click the back button to go back the subscription tab, if you are at the top of the page, then that's the issue (**try to watch/browse for at least 5 min before clicking the back button**)

**Expected behavior**
The expected behavior is when you click the back button to go back the subscription tab, you should see where you left instead of being taken at the top of the page.

**Version** `14.21.54` **does not have this issue.**

More on this issue here:
https://www.reddit.com/r/Vanced/comments/jhppg2/other_vanced_returns_to_the_top_of_subscriptions/
https://www.reddit.com/r/Vanced/comments/jarcav/question_vanced_returns_to_the_top_of_suggestion/

**Comment by milindgoel15** [comment]
Please update to the latest v16.16.38 if you haven't already. We are closing this issue. Feel free to reopen if you still face any issues.
