### ISSUE TITLE
[Idea] YouTube Core Version Update

### ISSUE THREAD

**Issue by MuhammetEminCakir** [YTVanced/Vanced#1551]
I know you are busy and i know you have a life. That's why app doesn't update regularly. But if it isn't hard you can update only YouTube core version. Because YouTube's developers fix some issues and add new features(unbelievable but fact). And it musn't be every core version, once per a week or mount.

A bug in YouTube 16.29.39 and fixed version of YouTube's newer version.
![IMG_20220127_000225](https://user-images.githubusercontent.com/64583157/151246521-4adf92b7-f282-4331-a574-8e6edb61c71e.jpg)

Player sidebar feedbacks tab(Added newer version of YouTube).
![Screenshot_2022-01-27-00-05-28-070_com google android youtube](https://user-images.githubusercontent.com/64583157/151247242-15ba7ff0-d040-4b88-bfdb-bb603f65c36f.jpg)

This feature
![IMG_20220127_000800](https://user-images.githubusercontent.com/64583157/151247391-e097099d-f994-4c24-8b0e-b7e98c106170.jpg)

**Comment by milindgoel15** [comment]
We are working on new updates. Be patient.
