### ISSUE TITLE
[Bug] PIP function and split screen android function conflict

### ISSUE THREAD

**Issue by DragneelDM** [YTVanced/Vanced#1553]
Bug description:
The PIP and Split Screen function unusually tries to bypass each other. When I play a video, go into PIP mode and then open split screen mode; It works! Except this is not the case when the video passes a minute mark and suddenly My Split Screen works as a PIP button instead of a split screen button. This only happens with YT app. This problem then gets even glitchier with every single tap, Android opens a empty blank split screen and also opens miniature player simultaneously. The Workaround for this problem is opening split screen with another app and then setting YT app second.

Variant:
Non-Root

Vanced version:
v16.29.39

Android version:
Android 11 

Device:
Vivo v17( 1919, FunTouchOS)

Steps to reproduce the error:
1. Open the app
2. Click on a video and wait for a min (Necessary)
3. Press Home Button, PIP miniature player is activated
4. Use Split Screen Shortcut 
5. Mash the split screen button several times to see how far the glitch goes

Expected behaviour:
If I want split screen, I'll use the split screen button and if I want PIP function, I'll use the Home Button. I want PIP function to seamlessly switch to split screen without conflicts

![PIP Split_Screen_Function](https://user-images.githubusercontent.com/64640316/151331875-450f054c-63ef-4e52-9384-de6438400744.jpg)
![The_Glitch](https://user-images.githubusercontent.com/64640316/151331949-d5778694-5f80-40cc-b406-8327ae697bf4.jpg)
![Split_Screen_Functioning_Properly](https://user-images.githubusercontent.com/64640316/151331899-32c68e15-2bf5-4eda-99c3-910ff051685e.jpg)
![Split_Screen_FunctionLocked](https://user-images.githubusercontent.com/64640316/151331903-b7577169-f39b-4129-b31f-211794871e92.jpg)
![Bruh_Moment](https://user-images.githubusercontent.com/64640316/151331922-9b24bc8b-7031-4105-afd6-b28e4a8aa4d5.jpg)
![Fixing_Bruh_Moment](https://user-images.githubusercontent.com/64640316/151331929-964571b1-39b3-4502-a4d6-335ff4f910fe.jpg)

**Comment by DragneelDM** [comment]
Sorry, i didn't think images would be this big

**Comment by milindgoel15** [comment]
Pip issues aren't vanced concern. It's either your OS or wait for new "base" update.

(But in your case, it's more your OS than base issue.
