### ISSUE TITLE
[Idea] Disable adding a video to recent playlist via settings

### ISSUE THREAD

**Issue by SquidsuneMiku** [YTVanced/Vanced#1556]
When I press the save to playlist button, it always chooses the last playlist I added a video to instead of letting me choose myself. Maybe have a setting that can disable this?

**Comment by Fooftilly** [comment]
Hold save button on the videos for a second and an option to choose the playlist will appear. This is from default Youtube app.

**Comment by SquidsuneMiku** [comment]
I never knew that feature existed, thanks.
