### ISSUE TITLE
[Bug] Links don't open in YV since Android 12

### ISSUE THREAD

**Issue by Mimicthis** [YTVanced/Vanced#1559]
**Bug description**

So the issue after the Android 12 update. Everything in the settings was as it was but now all links open in the YouTube app or if I unselect it, in the preffered browser. When I go to YouTube Vanced and then select "Supported Aeb Addresses " settings get turned off immediately. I have to use Better Open With app...

**Have you read vanced guides already? YES

**Variant:**
Non-Root

**Vanced version:**
V16.29.39

**Link used to download vanced:**

https://vancedapp.com/

**Android version:**
Android 12

**Device:**

Samsung Galaxy A52 5G 

**Steps to Reproduce**
Steps to reproduce the error:
1. Open any link for the YouTube video in any app
2. It will redirect it to official YouTube app 
3. If the official YouTube app isn't set as default it will open a video in the preffered browser then
4. This has worked before Android 12, but when I select " Supported Web Addresses " and turn all the links, it just turns it off after exiting them. 

**Expected behaviour:**

The video from the link should open in YouTube vanced like before Android 12 and " Supported Web Adresses " should stay turned on. 
The YouTube Vanced needs a fix for that. 

Turned on:

![Screenshot_20220130-132703_Settings](https://user-images.githubusercontent.com/29215437/151701537-4556b4fa-7657-4501-ba3d-1e16f6f8aa59.jpg)

After exiting and returning, turned off:

![Screenshot_20220130-132658_Settings](https://user-images.githubusercontent.com/29215437/151701546-de73cf55-08d1-4b0c-8cdc-068f275388db.jpg)

**Comment by milindgoel15** [comment]
Aint a vanced issue. Use the "better open with" app from the play store to change the default app or uninstall stock YouTube using adb or use the root version of vanced.

**Comment by leranp** [comment]
Same here, with root
![Screenshot_20220205-201950_Rotter.jpg](https://user-images.githubusercontent.com/9452319/152653982-05ca1167-9694-4860-87bd-a306bc776ff1.jpg)

**Comment by milindgoel15** [comment]
@leranp If you are posting a screenshot, better post it without cropping. cropping doesn't help. Also, better write a detailed issue instead of writing same issue
