### ISSUE TITLE
[Bug] Slide up gesture - instant return to vertical view 

### ISSUE THREAD

**Issue by Mimicthis** [YTVanced/Vanced#1560]
**Bug description:**

Slide up gesture so the video would go to the horizontal way doesn't work properly. I slide up the video and then it goes back immediately to the vertical view. After second try it works. While pressing the square icon to do this it doesn't do that. It works properly on the basic YouTube app.

**Have you read vanced guides already? YES

**Variant:**
Non-Root

**Vanced version:**
v16.29.39

**Link used to download vanced:**

https://vancedapp.com/

**Android version:**

Android 12 

**Device:**
Samsung Galaxy S8

A52 5G

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2. Open any video
3. Make a gesture, slide up your finger to the top of the screen in the vertical view where the video is small. 

**Expected behaviour:**

After doing the gesture the video shall go to full screen and stay that way.

**Comment by milindgoel15** [comment]
Not a vanced issue either. It's a very random bug that very few users have and is also related to OS. 

If we find any fix for this, it will be released with a future release. Or probably even fixed by google itself through new base patches.

**Comment by Mimicthis** [comment]
Will you fix the bug?
