### ISSUE TITLE
Blackbox chrome extension integration

### ISSUE THREAD

**Issue by TxJK** [YTVanced/Vanced#1563]
Blackbox is a popular chrome extension that allows to copy texts from YouTube videos. This is extremely helpful for students.
The sponsorblock integration was supercool. Similarly adding this extension would be really helpful.

**Comment by gghhkm** [comment]
Not possible.

**Comment by milindgoel15** [comment]
Does that extension have any API? 

It doesn't mean we are able to integrate Sponsorblock and ryd, we can add any extensions. Nah It doesn't work that way. Adding support for extensions needs a lot of work and an API to actually implement it.
