### ISSUE TITLE
[Bug] pause video

### ISSUE THREAD

**Issue by MetiuRix** [YTVanced/Vanced#1565]
**Bug description:**
When i pause a video in horizontal, After a few seconds It automatically start by It self
**Have you read vanced guides already? (YES/No)**
No

**Variant:**
Not root

**Vanced version:**
v16.29.39

**Link used to download vanced:**
https://vancedapp.com/

**Android version:**
 Android 12 

**Device:**
Realme GT 5G

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2. Open a video
3. Pause It
4.And After a few seconds the video Will start by It self

**Expected behaviour:**
When i pause a video It shouldnt start by It self

**Comment by TheAmazingBen100** [comment]
Not a Vanced issue. Probably an issue with your headphones or something

**Comment by milindgoel15** [comment]
You either have some loose port or your OS has some accessibility to continue playing media. Still, it's not vanced issue.

**Comment by xppenTC** [comment]
I have a Realme GT 5G like him, and i have the exact same issue. I'm pretty sure it is not a headphone issue. Maybe a OS issue (not a accessibility one i think) or a bug on vanced with this OS.

**Comment by milindgoel15** [comment]
Check stock youtube app of the same version as vanced and see if it happens there.

**Comment by MetiuRix** [comment]
> Check stock youtube app of the same version as vanced and see if it happens there.

With the stock YouTube app di not happen

**Comment by xppenTC** [comment]
> > Check stock youtube app of the same version as vanced and see if it happens there.
> 
> With the stock YouTube app do not happen

Yes, it do not happen on stock youtube.

**Comment by milindgoel15** [comment]
have u both checked the same version as vanced or did u check with an updated version of stock yt? stock must be of v16.29 as well

**Comment by xppenTC** [comment]
No have checked with the latest version of yt stock

**Comment by MetiuRix** [comment]
> have u both checked the same version as vanced or did u check with an updated version of stock yt? stock must be of v16.29 as well

My stock YouTube is 17.03.35
My YouTube vanced is 16.29.39

**Comment by xppenTC** [comment]
> > have u both checked the same version as vanced or did u check with an updated version of stock yt? stock must be of v16.29 as well
> 
> My stock YouTube is 17.03.35 My YouTube vanced is 16.29.39

Same

**Comment by milindgoel15** [comment]
> Check stock youtube app of the same version as vanced

I literally said to check on same version as vanced is. Still you both checked on newest stock base.

**Comment by xppenTC** [comment]
> > Check stock youtube app of the same version as vanced
> 
> I literally said to check on same version as vanced is. Still you both checked on newest stock base.
> 
> I won't help any further. It's an issue on device end and will probably be fixed with new vanced release. If not, blame Google.

Ok thanks.
