### ISSUE TITLE
[Bug] video pauses on increasing volume when on in built speakers

### ISSUE THREAD

**Issue by TxJK** [YTVanced/Vanced#1567]
I'm using Android 9 phone. I've seen a wierd big where video pauses on increasing volume but not decreasing.
This doesn't happen all the time. But it does happen quite frequently. I've noticed this happen even while having wired headphones on. That was just one time.

**Comment by TheAmazingBen100** [comment]
probably an issue with your headphones, not a vanced issue

**Comment by milindgoel15** [comment]
Problem with your port then

**Comment by TxJK** [comment]
Should have happened with half a dozen other apps that I use. Other apps like music player from musicolet, stock music player, WhatsApp media, Spotify, VLC and tonne of other encrypted video players work fine.
Issue only on YouTube vanced and is not present on YouTube music.
It works fine once the app is restarted.

**Comment by milindgoel15** [comment]
YouTube Vanced  is not YouTube music. Both are separate different apps. U wanna check better, check on stock yt of same version v16.29.

**Comment by TxJK** [comment]
I use the YouTube app as a default app for opening YouTube links. In my brief usage I did not find any such bug.

**Comment by TxJK** [comment]
All of my apps are on auto update. Hence all the version of the YouTube app.
And yes, I'll try to keep up with your template.
Vanced version 16.29.39
Direct website download of vanced manager
Vanced manager used to install app.
Vivo U10
Stock ROM
Stock YouTube version 17.03.35

**Comment by milindgoel15** [comment]
> All of my apps are on auto update. Hence all the version of the YouTube app.
> And yes, I'll try to keep up with your template.
> Vanced version 16.29.39
> Direct website download of vanced manager
> Vanced manager used to install app.
> Vivo U10
> Stock ROM
> Stock YouTube version 17.03.35

Uninstall ur stock to v16.29 then check on it. Otherwise wait for new base update.
