### ISSUE TITLE
[Idea] Option to hide seen videos

### ISSUE THREAD

**Issue by paveldvorak5** [YTVanced/Vanced#1568]
**Description**
I'd like an option to hide watched videos from the feed and subscriptions.
Sometimes when I open the app there are on the first page only videos that I have already seen.
I want generally only to see the subscribed videos and I see them only once.

**Comment by TheAmazingBen100** [comment]
Blame Google and the YT algorithm instead, vanced can't really do much about it

**Comment by paveldvorak5** [comment]
Yes, I blame them for everything ;)
So can't "post process" the response from YT?

**Comment by milindgoel15** [comment]
nope
