### ISSUE TITLE
[Bug] Can't find device to cast YouTube video on TV

### ISSUE THREAD

**Issue by Gladiaria** [YTVanced/Vanced#157]
**Bug description**
I click cast video to Chromecast, but it always show "find device" and "can't find device".
This app cast video is run ok yesterday.
I can't find any solutions to cast YouTube video on TV.

**Variant**
NonRoot: Yes
Root: No

**Vanced version**
15.43.32 - Build - 01.47.00

**Android version**
Android 9.0 - Pie

**Device**
Sony Xperia XZ Premium

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2. Click on 'Cast Video Button'
3. Show find device..
4. Show can't find any device.

**Expected behavior**
Replace me with a description of what you expected should happen and what happened instead.

![Screenshot_20201105-205952.png](https://user-images.githubusercontent.com/73999368/98244521-8f0fa280-1faa-11eb-975e-a34343c55bbd.png)
![Screenshot_20201105-210010.png](https://user-images.githubusercontent.com/73999368/98244570-9afb6480-1faa-11eb-9501-a38ef152f36a.png)
![Screenshot_20201105-210034.png](https://user-images.githubusercontent.com/73999368/98244598-a64e9000-1faa-11eb-86eb-361cdcb8b705.png)
![Screenshot_20201105-210040.png](https://user-images.githubusercontent.com/73999368/98244617-af3f6180-1faa-11eb-87b8-6ed4bd5cd225.png)

_Attach images/videos if possible. These can be helpful in solving the issue._

**Comment by frapgadz** [comment]
I also have this issue, uninstall and reinstall of Vanced brings back the functionality but after a short while it reverts to being unable to find any device. This is on a Huawei Mate 20 Pro

**Comment by Gladiaria** [comment]
I have another question. my mobile is not in WiFi zone, but still show cast button and always find device...like this picture:
![Screenshot_20201107-171850.png](https://user-images.githubusercontent.com/73999368/98437491-7d9ad780-211d-11eb-88ae-e345f84dad0c.png)

**Comment by Gladiaria** [comment]
I may find the problem...
Vanced settings is the main cause of the problem that can't cast to TV.
When I setup and restart YouTube vanced.

**Comment by noskap** [comment]
I have exactly the same issue. Reinstalling fixes it only temporarily
