### ISSUE TITLE
[Idea] Add quick-toggle to change video speed. 

### ISSUE THREAD

**Issue by AbdulAleem69** [YTVanced/Vanced#1571]
**Description**
Please add a quick-toggle to change video speed preferably near the cc and autoplay button since once you get used to watching yt vids in higher speeds there's no going back. 

![Screenshot_20220202-091913_YouTube](https://user-images.githubusercontent.com/77669093/152090244-792e78a0-9a26-4486-9539-7b3ffd54cc1f.png)

One press can go to previously set speed, then 1.25x, 1.5x and 1.75x and 2x. Then to normal 1x speed. (Just a suggestion, maybe implimented in a better way.)

**Comment by milindgoel15** [comment]
Please refer issue #1602 from now on.
