### ISSUE TITLE
[Idea] Add scrubber in YouTube shorts. 

### ISSUE THREAD

**Issue by AbdulAleem69** [YTVanced/Vanced#1572]
**Description**
Add an option to scrub through YouTube shorts after long pressing it like in a normal yt video. Would be very useful.

**Comment by milindgoel15** [comment]
What do you mean by scrubber?

**Comment by AbdulAleem69** [comment]
![Screenshot_20220202-174943_YouTube~2](https://user-images.githubusercontent.com/77669093/152152737-b5c6e76c-398c-4d09-ab3c-47cdb365a42a.png)
Long press to scrub through the video. 
You could impliment something like this...

**Comment by AbdulAleem69** [comment]
https://file.io/gacn5E62cYOc

Example of an implimentation

**Comment by milindgoel15** [comment]
We don't have control over YouTube shorts. Ask Google.
