### ISSUE TITLE
[Bug] Keyboard shortcut for pause/play

### ISSUE THREAD

**Issue by Merlin1809** [YTVanced/Vanced#1574]
**Bug Description**
When using a external keyboard, there are keybinds to use like on the web version. Pressing any button only selects elements on the youtube page for whatever reason. The only exceptions are the left and right arrow keys which correctly either jump 5 seconds forwards or backwards, the "C" key which correctly turn off/on subtitles and the CTRL key which brings up a small menu showing all the available keyboard shortcuts. By pressing spacebar to pause/play a video it only makes the screen get a white tint because it highlights it. By pressing it again it actually pauses and plays correctly though, but only on my tablet. On my phone even after pressing it multiple times it doesn't pause/play. It's quite annoying to either use my mouse or reach for my tablet in order to pause the video in order to avoid the white tint.

**Have you read vanced guides already? (YES/No)**
yes

**Variant:**
non-root

**Vanced version:**
16.29.39 and 16.49.39 (beta version)

**Link used to download vanced:**
https://vancedapp.com/

**Android version:**
Android 12 with One Ui 4.0

**Device:**
Samsung Galaxy Tab S7 and S20FE with a bluetooth keyboard

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2. Open a video
3. Go fullscreen
4. Press spacebar

**Expected behaviour:**
Pressing spacebar should pause/play the video and any button that doesn't have a keybind should do nothing.

_Attach images or videos or logcats in case of crashes if possible. These can help solve the issue._
1. normal video
![Screenshot_20220203-211125](https://user-images.githubusercontent.com/88194861/152423850-e13bb0a3-ea69-4fa0-a781-32563b8b4630.png)

2. after pressing spacebar
![Screenshot_20220203-211059](https://user-images.githubusercontent.com/88194861/152423878-1c98e1fe-7995-4cf2-9f71-b442da4dbddd.png)

3. keybinds
![Screenshot_20220203-211107](https://user-images.githubusercontent.com/88194861/152423900-5fb241a7-6651-4e07-b472-d87105f202ab.png)

**Comment by milindgoel15** [comment]
Does it happen on stock yt?

**Comment by Merlin1809** [comment]
Looks like so, yeah

**Comment by milindgoel15** [comment]
Not vanced issue then
