### ISSUE TITLE
[Idea] comment spam filter

### ISSUE THREAD

**Issue by Rerbun** [YTVanced/Vanced#1579]
**Description**
Since YouTube is getting overruled with spam from bots it would probably be nice to add a filter to not show these or maybe even to report them automatically when loaded.

There is a popular project for reporting spam automatically with a pretty good success rate which could also maybe be used for reference, but I'd say just having the option to block non-ascii usernames would be a nice first step

https://github.com/ThioJoe/YT-Spammer-Purge popular spam purger for reference

**Comment by milindgoel15** [comment]
Ask Google.

**Comment by Rerbun** [comment]
> bump (to make sure that vanced youtube devs will add it)

This issue got closed, so I wouldn't bet on it
