### ISSUE TITLE
[Bug] Mini-Player (Picture-in-Picture-Player) sometimes is invisible

### ISSUE THREAD

**Issue by tiuub** [YTVanced/Vanced#158]
**Bug description**
Sometimes the Mini-Player (Picture-in-Picture-Player) appears to be completely invisible. So I can hear the video is running, but the video isn't showing in the Mini-Player. (This happens about half the time I try. [Odds: 50%])
If I reopen Vanced and go to the homescreen again, the bug is mostly gone and the Mini-Player is working.

**Variant**
NonRoot: Yes
Root: No

**Vanced version**
15.43.32 - Build - 01.47.00

**Android version**
Android 10 - OxygenOS

**Device**
OnePlus 7T

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2. Click on any video
3. Wait until video starts
4. Click the home button (go back to homescreen)

**Expected behavior**
The Mini-Player should now be invisible. In my case I am only able to see the little "x" for closing the Mini-Player.

**Logcat**
https://hastebin.com/evotomumos.yaml

**Video**
(Sorry, cant upload .mp4. Therefore I have zipped the video.)
[YTVanced Bug Report.zip](https://github.com/YTVanced/Vanced/files/5501814/YTVanced.Bug.Report.zip)

**Comment by gghhkm** [comment]
PiP is controlled by your ROM, Vanced team can't do anything about it.
