### ISSUE TITLE
[Bug] Links signs you into your browser without password or authentication

### ISSUE THREAD

**Issue by wafles38** [YTVanced/Vanced#1580]
**Bug description:**
When you click a link from a website outside of youtube (such as twitter.com). Vanced will open the browser, and will open this link: https://accounts.google.com/MergeSession?args=continue%3Dhttps%253A%252F%252Fwww.youtube.com%252Fredirect%253Fevent%253Dbackstage_event%2526redir_token%253DHzARPFxkN2xqU5wpX4erxiRmv9Bm8E7gipPrvEYQzXkfnti6QgJzVXpA9q2BtvbgTWn3ZCaAMGf4FFQyYY8berdq8PVtmqjMrwdDi7wcrGTfCbjtM2PveyhpPdzm2DGbDYtv23JHcrVnbBGHGiJvGp6chfktqgAet9PnqDEwXdJ4DAtGNJ7vX8WzVvguUwPMpruW3HMeTGX2RE%2526q%253Dhttps%25253A%25252F%25252Ftwitter.com%25252Fmiyabihanasaki%25252Fstatus%25252F1489600867020189699%2526html_redirect%253D1&uberauth=hJRprMEh7jFjbJyn6nCT5HFA9ZDTETeMeaiHRr3Q6JkAwT6mWMuf3P7Wr5ZDQaKBFePiDv4Qha9FQetfPgWnpTbFAJgvSuqtMEJwDKZVpDr4g76X7fe93J9jQCGNN6k2CmnTATk2fkVBqGUGJMC5vcZfgnTXrgZaXWNuJR27pGHcrAbYC4PvnhBMXYZ5Krh3Q4KSZPUuJtB8Fd8V9uUahDAZgMzz9FicwCStW7QTDDWmcneAyrCLdkrgV7r2AVAE7wuFQJ5PMkqkUNaMbT9P8xSHQFBW5LNnr3tcWEiLD2We3A35QzQnyaEPR6hTgH76r7L5Ng3PVfqGZgvdRuha54B442dTScQ89MJD8KVHyftacKmeLjeYvnjqcZ2Wqvzw8TCLnjWSHPhgn8TtqCdapT2XJzJHT6G6L8wJq4kBu6VYxnQY9WFiQYVxrSwSYZ3npGFZ7YbFb4nFZgSqDN7VruQavEnSgbYxuYtC2gq8Eqfw4KMjg63CjRXdEwXJGGpdqanZEcfhYx6DT5zqVU6MYwmHvzArNnnPz7FMFizqxAp7h7CJapeC5bPYXziDvdnnQTurYmCAfhxfviiu2U4AVz4PLMmUJHFWewUi48a4L6GryQSgpVHFV8j25YUhMUZHjxyEJnQBTciQaCSg9KJux2nkuYhHLAK3ax&source=AndroidWebLogin&displayContext=webview which will then take you to the youtube redirect link and then take you to the website you were trying to access

After doing this, you will notice by going to accounts.google.com, that you are now logged into your account.

This gives me privacy concerns because I don't want my search results and other activity I do online to be recorded on my google account. This also gives me security concerns because I am afraid the link above can be used by anyone to log into my account, which exposes users to man in the middle attacks (since urls are not encrypted). This would grant full access to someone's google account to a bad actor. I am pretty sure the url does expire though.

Because of these concerns, the random strings of characters on the link above had been anonymized with a generator of random strings of characters and it should not work. You should be seeing a page that says "are you sure you want to leave Youtube?" when the url uses an invalid token. You won't see this page if the url has a valid token even if it has expired

**Have you read vanced guides already? (YES/No)**
YES
Nothing there was relevant to this

**Variant:**
Non-Root

**Vanced version:**
16.29.39

**Link used to download vanced:**
https://vancedapp.com/

**Android version:**
Android 11 and Android 10

**Device:**
Tested with multiple Samsung devices (4 different models)
Samsung Galaxy A90
Samsung Galaxy A6

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2. Look for a community post with a link that won't automatically open on an app (A twitter link should work)
3. Click on the link
4. Make sure you get the dialog of what app you wish to open. At this point, you should turn off the wifi to prevent the direct
5. Open the app you wish to open the link with
6. See that the url starts with accounts.google.com. Copy and paste this url somewhere else for closer inspection

**Expected behaviour:**
The official youtube app doesn't do this. You should be taken to https://www.youtube.com/redirect?event=backstage_event&redir_token=. Preferably I would like Vanced to just take me to the link itself in order to avoid trackers (no redir tokens, just twitter.com)

**Comment by milindgoel15** [comment]
It's more of stock yt behaviour, not vanced. A future vanced release might fix it for you.

But also, when you use internet, you are already loosing your privacy. There's nothing more you will gain when you don't record your activity. Google or other companies already know so much and they will still track you as long as you are using internet.

Please rather describe your issues straight to what is happening and what should happen instead. Talking about privacy when reporting any issue/report doesn't help anyone here.

**Comment by wafles38** [comment]
How is this stock yt behavior when it doesn't happen on the stock app?

**Comment by milindgoel15** [comment]
Also #1012

**Comment by milindgoel15** [comment]
> How is this stock yt behavior when it doesn't happen on the stock app?

Because you literally just checked on the very latest version of stock, not the same version as vanced. Tell me did u check it on v16.29 of stock?

**Comment by wafles38** [comment]
Man, did I do something wrong? I am sorry if I did, I was not trying to insult you. If it's because of the theories and sharing why I want this fixed, I guess I'll try to remind myself to not do it again. I didn't mean to insult you when I did that.

After you made that comment I tried to install v16.29, and it didn't let me because my youtube app (with all updates unnistalled) is an older version. The oldest I can go is v16.30.34, and it doesn't happen there

I want to clarify that this is not about trackers (or the youtube.com/redirect link). It's about the accounts.google.com/mergesession link. I just don't want to be logged into my account on my browser. I am not sure if that's addressed on the issue.

If the issue or fix you mentioned already addresses that, and I won't be logged into my google account when I click on a link, then I think that's cool.

**Comment by milindgoel15** [comment]
> Man, did I do something wrong? I am sorry if I did, I was not trying to insult you. If it's because of the theories and sharing why I want this fixed, I guess I'll try to remind myself to not do it again. I didn't mean to insult you when I did that.

No, it was not an insult but rather you were trying to tell that vanced is the cause of it because it didn't happen on stock yt. There's nothing vanced has added to track your activity or anything.
So if it's happening on vanced, it's not vanced issue. It's either google stock behaviour or i just found one more possibility which could be microG. 

So there's nothing vanced can do in this respect unless the referenced issue addresses this then yes you will be fine afterwards. However, there's no plan to implement such feature as yet so you are most likely to live with it.

**Comment by wafles38** [comment]
Alright, thanks for the reply and clarifying things. I hope that this stops happening on a future release (maybe after moving to v1.17 or if the issue referenced addresses it)
