### ISSUE TITLE
[Bug] Membership/community section doesn't show all the content

### ISSUE THREAD

**Issue by YuhiAida** [YTVanced/Vanced#1581]
**Bug description:**
The membership/community section only shows videos instead of all the content (images/text).

**Have you read vanced guides already? (YES/No)**
YES

**Variant:**
Non-Root

**Vanced version:**
v16.29.39

**Link used to download vanced:**
Vanced Manager

**Android version:**
Android 11 

**Device:**
Samsung Galaxy S20 ultra

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2. Click on 'Notifications'
3. Click on 'for members only from...' (in this case). Or just go to any channel to the section 'community/membership'

**Expected behaviour:**
See all the post videos, text, images. 

**youtube app**
![Original post on youtube](https://user-images.githubusercontent.com/21134775/152649896-95802e31-db7c-4de8-9227-f53d2e709740.png)
**Vanced**
![Vanced](https://user-images.githubusercontent.com/21134775/152649997-80288990-1368-4a15-a62d-9f6687145656.png)

**youtube app membership**
![membership section youtube app](https://user-images.githubusercontent.com/21134775/152650034-7818bddc-f595-436e-b1e9-03fd6631150d.png)
**Vanced membership**
![Vanced membership section](https://user-images.githubusercontent.com/21134775/152650069-61021963-08e7-465b-b68a-e04ca7ba3873.png)

**Youtube app community section**
![Youtube app community section](https://user-images.githubusercontent.com/21134775/152650111-a0d574cd-38a7-42af-91db-267d193200d5.png)
**Vanced community section**
![Vanced community section](https://user-images.githubusercontent.com/21134775/152650127-14813232-f3ec-4951-a256-b33de1e48ebd.png)

**Comment by milindgoel15** [comment]
![Screenshot_2022-02-05-23-54-24-921_com.vanced.android.youtube.jpg](https://user-images.githubusercontent.com/45682747/152654123-a109915e-7f19-44b8-aba3-b23f3cac85c9.jpg)

**Comment by milindgoel15** [comment]
Please try basic troubleshooting to fix your issue. You can find troubleshooting guides in the readme section of this repository.

Meanwhile, i am closing this issue.
