### ISSUE TITLE
[Bug] Restricted mode enabling itself randomly

### ISSUE THREAD

**Issue by TheGinGear** [YTVanced/Vanced#1582]
**Bug description:**
It seems when connecting to some random wifis (or at least that's the only time I have noticed this happening at first), restricted mode enables itself in YouTube Vanced. There is no way to turn this off  even when disconnecting from that internet and connecting to another. The only way to remove it  is to clear all storage to the app.

**Have you read vanced guides already? (YES/No)**
Yes 

**Variant:**
Non-Root

**Vanced version:**
16.29.39

**Link used to download vanced:**
https://github.com/YTVanced/VancedManager/releases

**Android version:**
Android 12

**Device:**
Pixel 4a 5G

**Steps to Reproduce**
Steps to reproduce the error:
1. Connect to wifi that causes said restriction

**Expected behaviour:**
Restricted mode should not enable itself. That or it should at MINIMUM let you turn it off; I am using Vanced for a reason

_Attach images or videos or logcats in case of crashes if possible. These can help solve the issue._
![Screenshot_20220205-191334](https://user-images.githubusercontent.com/39550332/152664346-0d00cf1b-3c41-4e87-9818-b6e0c0bf4985.png)

![Screenshot_20220205-191425](https://user-images.githubusercontent.com/39550332/152664362-c2ba4838-a720-4913-8c0b-f44d603da52c.png)

**Comment by milindgoel15** [comment]
Not vanced issue, the restrictions are applied by that WiFi, not vanced.
