### ISSUE TITLE
[Idea] Download Community Post Images

### ISSUE THREAD

**Issue by UnboltedWork** [YTVanced/Vanced#1584]
Wait, don't instantly delete, this is NOT Videos, this is youtube community posts. Basically allowing us to download that community post allows us to share memes and things a bit easier.

**Comment by TheAmazingBen100** [comment]
Downloading will never be added.
Google doesn't like people downloading copyrighted content off their platform so don't ask for it.

**Comment by milindgoel15** [comment]
I don't really think the community post are copyrighted but since it's Google, it might be possible.
