### ISSUE TITLE
[Idea] Optimize YouTube Vanced APK for Android TV OS devices. (Support / Compatibility)

### ISSUE THREAD

**Issue by RFL0WGitPR** [YTVanced/Vanced#1585]
It would be extremely nice
to test and run future YouTube Vanced APK's on Chromecast / Android TV OS / Google TV devices.

**Comment by TheAmazingBen100** [comment]
It already exists. It's called SmartTubeNext. Do yourself a favour and get it.
[Get It Here!](https://vancedapp.com/tv)
