### ISSUE TITLE
[Bug] replaceme

### ISSUE THREAD

**Issue by Walmartrl** [YTVanced/Vanced#1588]
**Bug description:**
When I try to open any link or open basically anything in another app I just can't

**Have you read vanced guides already? (YES/No)**
yes
**Variant:**
Non-Root/Root
non-root
**Vanced version:**
Replace me with the exact version of vanced you are using. It is mandatory to report issues from the latest available versions only. For youtube, v16.29.39

**Link used to download vanced:**
[Replace here with the source/link you used to download and install on your device. ](https://www.google.pl/url?sa=t&source=web&rct=j&url=https://vancedapp.com/&ved=2ahUKEwiw4b6G4-_1AhXIl4sKHSLoAeEQFnoECAMQAQ&usg=AOvVaw0Q0FqQt24ZeKZb5VGq5Nv5)

**Android version:**
Replace me with the version of Android your device have. For example, Android 11 
11
**Device:**
Replace with the name of the device on which you faced the bug. For example, Samsung Galaxy S8
Xiaomi Mi 9T
**Steps to Reproduce**
Steps to reproduce the error:
1. Jyst have the app downloaded
2. try to open any link in any app apart from youtube and browser for example discord 

**Expected behaviour:**
![Screenshot_2022-02-08-10-03-38-693_android](https://user-images.githubusercontent.com/99249031/152956507-4b368c7b-1bc0-4e08-9436-6d52011721c2.jpg)
![image](https://user-images.githubusercontent.com/99249031/152956536-7c387bf2-4be3-46d6-977a-b9885215e94f.png)

**Comment by milindgoel15** [comment]
Sounds like your os issue because it has nothing to do with vanced. Or try to explain your issue a little better with screen recording and providing screenshots in the English language.

**Comment by mon5termatt** [comment]
I am having this issue as well. Any links (including on app) open as of Vanced is not installed.

**Comment by milindgoel15** [comment]
Please provide some useful bug report which we can look and find. Post screenshots or screen record

**Comment by milindgoel15** [comment]
The solution to this issue would be to set vanced as default apps for opening links. Otherwise your only option would be to use root version.

([You can find guide on how to make vanced default for opening links here](https://telegra.ph/Installation-for-Vanced-09-01#Default-app))
