### ISSUE TITLE
[Bug] The cleared alarm keeps popping up.

### ISSUE THREAD

**Issue by ghkimwoo** [YTVanced/Vanced#1592]
**Bug description:**
Replace me with a clear and detailed description of the bug.

**Have you read vanced guides already? YES**
If your answer is no, please consider reading before creating this issue. The guides can be found in the readme section of this repository. 

**Variant:**
Non-Root

**Vanced version:**
v16.29.39

**Link used to download vanced:**
Download in Vanced Manager

**Android version:**
Android 12

**Device:**
Samsung Galaxy S20 Ultra

**Steps to Reproduce**
Steps to reproduce the error:
0. Make sure the alarm is on
1. Clear all YouTube Vanced alarms.
2. waiting.
3. Deleted alarm pops up.
4. repeat from 1

**Expected behaviour:**
(https://cdn.discordapp.com/attachments/660773334363013134/940937834590781471/Screen_Recording_20220209-2042451.mp4)

_Attach images or videos or logcats in case of crashes if possible. These can help solve the issue._
(Sorry, I turned on debug logging, but I couldn't upload it because I didn't know where to look.)

**Comment by TheAmazingBen100** [comment]
1: Fill out the issue template properly
2: They are called NOTIFICATIONS, not "alarms"
3: [#1107](https://github.com/YTVanced/Vanced/issues/1107)
