### ISSUE TITLE
[Idea] Remove suggested videos from search results

### ISSUE THREAD

**Issue by ndm13** [YTVanced/Vanced#1598]
**Description**
More frequently, when searching for videos, I will get "results" that aren't related to my search. These are usually labeled "You might also like" or "People also watched this." This is incredibly annoying, especially when looking for something specific where I'm going through dozens of results and most of them are spam.

The ability to block these results would be greatly appreciated.

![Screenshot_20220214-002747.png](https://user-images.githubusercontent.com/4514895/153805733-888238c3-94eb-498c-b696-9f409ac30744.png)
![Screenshot_20220214-001530.png](https://user-images.githubusercontent.com/4514895/153805747-2ed315fe-69fd-4a56-8b79-1df9fbf0463d.png)

**Comment by milindgoel15** [comment]
ask google

**Comment by leodoi3** [comment]
> ask google

what kind of a response is that? why can't you do it within the app?

**Comment by milindgoel15** [comment]
We didn't made YouTube. Ask google to give us source code then yea we might
