### ISSUE TITLE
[Bug] internal and external links opening in browser

### ISSUE THREAD

**Issue by mon5termatt** [YTVanced/Vanced#1600]
**Bug description:**
All of the internal and external links to YouTube videos are being opened in a browser window instead of YouTube vanced

**Have you read vanced guides already? (YES/No)**
A week ago on discord

**Variant:**
Non-Root

**Vanced version:**
16.29.39

**Link used to download vanced:**
Default

**Android version:**
Android 12

**Device:**
Samsung Galaxy S20+

**Steps to Reproduce**
Steps to reproduce the error:
1. Open any app
2. Click on any YouTube link
3. see web browser open

**Expected behaviour:**
I expect the video to open in YouTube and not the web browser

_Attach images or videos or logcats in case of crashes if possible. These can help solve the issue._

https://youtu.be/g7qLfQcMDyU

**Comment by milindgoel15** [comment]
Then we can't do anything.

If you need a better guide for making apps default for opening links, check out [this link](https://telegra.ph/Installation-for-Vanced-09-01#Default-app).
