### ISSUE TITLE
[Bug] Messed Up Video Notifications On S21

### ISSUE THREAD

**Issue by TheBrokenRail** [YTVanced/Vanced#1604]
**Bug description:**
YouTube Vanced video notifications have broken UI.

![Screenshot_20220214-232909_Firefox](https://user-images.githubusercontent.com/17478432/153993037-e63b46a1-b31d-475e-ba4f-50486e132543.jpg)

**Variant:**
Non-Root

**Vanced version:**
v16.29.39

**Link used to download vanced:**
Downloaded Vanced Manager from https://vancedapp.com/, then installed Vanced from there.

**Android version:**
Android 12

**Device:**
Samsung Galaxy S21

**Steps to Reproduce**
Wait for a video notification.

**Expected behaviour:**
I don't have a screenshot on me, but basically a smaller image and not having the timestamp wrap into 3 lines.

**Comment by milindgoel15** [comment]
OneUI moment

**Comment by TheBrokenRail** [comment]
The issue is that normal YouTube renders it fine, while Vanced doesn't.

**Vanilla:**

![Screenshot_20220215-092051_Google Play Store.jpg](https://user-images.githubusercontent.com/17478432/154080840-2c5368a8-e902-4145-953e-0db79fa011a9.jpg)

**Vanced:**

![Screenshot_20220215-092112_Google Play Store.jpg](https://user-images.githubusercontent.com/17478432/154080884-a2e13731-0163-4a9c-816d-a6ce5e390fae.jpg)

**Comment by milindgoel15** [comment]
Might be because Google has changed a lot  since our last vanced release. As you may know vanced stable release is still on 16.29.  We are currently preparing for new release so soon as the build gets stable, we will release it which could fix your issue.
