### ISSUE TITLE
[Bug] App window stuck after maximizing

### ISSUE THREAD

**Issue by nv-ua** [YTVanced/Vanced#1606]
**Bug description:**
After reopening Youtube Vanced I got it opened on upper half screen but in a fullscreen size, like it's meant to be opened fullscreen but something broken in a process. After that happened I can't press any button on the screen for example: I opening the app manager by dragging a line from the low middle of the screen but I can't swipe because Youtube Vanced covers the screen with it's broken window preventing me from any input.
I'm opening the settings from fast buttons menu but I can't operate with anything because it opens under broken Youtube Vanced window.
The only thing which solves the problem is a device reboot.
That trouble arrived after official update to android 12.

**Have you read vanced guides already? (YES/No)**
I'm using Vanced for almost 3 years don't need guides.

**Variant:**
Non-Root

**Vanced version:**
v. 16.29.39

**Link used to download vanced:**
https://vancedapp.com/

**Android version:**
Android 12

**Device:**
Google Pixel 3 XL

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2. Play video
3. Minimize and hide playback miniature 
4. Reopen app from it's link on homescreen
Can't tell if it's 100% reproduce the bug but I'm suffering it every day.

**Expected behaviour:**
App must reopen normally as it was on android 11 and 7 on my other device.

![Screenshot_20220216-084435](https://user-images.githubusercontent.com/71972191/154214695-2fe15a9a-d76e-43c0-9a5e-a30bc4c86373.png)

Sorry, I don't know where you app saves it's logs.

**Comment by milindgoel15** [comment]
Have you did basic troubleshooting since you wrote that u are vanced user from 3 years and don't need guides?

**Comment by nv-ua** [comment]
@milindgoel15
I tried to reinstall apps via Vanced Manager and manager too, checked updates, checked youtube vanced permissions but "один х*й" as we told in my homeland, nothing helped. I also tried to find that troubleshooting guide on Vanced git also official vanced website which you talking about but there was nothing similar to it.

**Comment by milindgoel15** [comment]
Update to v17 release and see if it happens

**Comment by milindgoel15** [comment]
Closing this issue due to non-activity
