### ISSUE TITLE
[Bug] Shorts shelf cannot be Disabled

### ISSUE THREAD

**Issue by harshavardhannarla** [YTVanced/Vanced#1609]
I have updated to new version(17.03.38), In previous version, Shorts shelf removal option along with Comments location (alpha) combiningly removed shorts , but in new version Comments location (alpha) is removed so now Shorts shelf removal alone is not able to disable shorts.

**Comment by TheAmazingBen100** [comment]
Old comments location was removed because of a server side change google made to the tablet ui, so it no longer worked. Unfortunately you can no longer disable the shorts tab in Vanced.
