### ISSUE TITLE
Sponsored blocker and RYD  does not work on Huawei media pad m6

### ISSUE THREAD

**Issue by Hammoudi2299** [YTVanced/Vanced#1612]
**Bug description:**
Sponsored blocker and RYD  does not work on Huawei media pad m6 after the latest update.

**Have you read vanced guides already? (YES/No)**
Yes

**Variant:**
Non-Root

**Vanced version:**
v17.03.38

**Link used to download vanced:**
vanced Manager

**Android version:**
Android 10 HarmonyOS 2.0

**Device:**
Huawei Media Pad M6 10.8

I already did everything froom cleaning cash or data or reinstalling everything
It doesn't show the dislikes or the sponsors not skipping and i can't submit a sponsor suggestions

**Comment by milindgoel15** [comment]
Yes, we did told it ain't gonna work for few people. Start reading changelogs?
