### ISSUE TITLE
[Bug] Disable live chat animation

### ISSUE THREAD

**Issue by NikSantos** [YTVanced/Vanced#1613]
I'm watch some streams on my phone and I leave the chat open everytime. But when the message flux is too high, the message animation (fade up/swipe up) goes chaotic and the stream starts buffer and lag. I think this animation is purely stetical and unnecessary. I have sent a feedback to youtube to fix this, but seems that never will be fixed

**Comment by milindgoel15** [comment]
Not vanced issue
