### ISSUE TITLE
[Question] Is the "enforce repeat" feature for YTM working again? 

### ISSUE THREAD

**Issue by Harmonie666** [YTVanced/Vanced#1615]
I'm afraid too update and still using 4.39.50 but the enforce repeat is working again with today's new release right? I would appreciate if someone from Vanced team can confirm.

**Comment by KevinX8** [comment]
Yes it's in the changelog?

**Comment by Harmonie666** [comment]
Thanks for confirming. I wasn't sure how to interpret "added back" as if these features were removed in a previous version. The wording made me unsure.
