### ISSUE TITLE
[Bug] [YTM] Tracks don't automatically maximize anymore.

### ISSUE THREAD

**Issue by Harmonie666** [YTVanced/Vanced#1616]
**Bug description:** {Mod edit}
YouTube music Vanced v4.64.51 breaks the ability the play every new music in maximized player if the enforce repeat is turned on. Previous versions were fine.

Edit: Removed the unnecessary bug description given by OP which are not even helpful for bug fixing

**Variant:**
Non-Root

**YTM Vanced version:**
Version 4.64.51

**Link used to download vanced:**
vancedapp.com

**Android version:**
Android 11

**Device:**
ASUS ROG Phone II

**Steps to Reproduce**
Steps to reproduce the error:
1. Open YTM Vanced app
2. Go into any playlist, album and tap a track
3. Track plays in minimized player, instead of automatically opening maximized player.

**Expected behaviour:**
Yt music vanced should play music in maximized player as before while keeping enforce repeat on 

YTM Vanced bug. Tap a track, it stays minimized:
https://streamable.com/dfw6fr

Stock YTM behavior. Tap/play a track and it immediately opens maximized player. This is the correct behavior, which needs to be addressed in the next YTM Vanced release:
https://streamable.com/i72ww2

**Comment by Harmonie666** [comment]
@KevinX8

**Comment by milindgoel15** [comment]
When are you going to stop tagging devs on small issues? Please learn to be patient

**Comment by milindgoel15** [comment]
Also, it works fine for us. Do basic troubleshooting such as clear data or reinstall and it will be fine.

**Comment by Harmonie666** [comment]
> Also, it works fine for us. Do basic troubleshooting such as clear data or reinstall and it will be fine. 

I did uninstall it and did a fresh install. All my downloads wiped.

After that I also disabled all Vanced features, and enabled one after another. I found out that the "Enforce Repeat" feature is breaking the player, and stopping it from maximizing.
Although the Enforce Repeat feature is working, it now causes issues with the player.

You can see it in the following demonstration that I recorded. I turn enforce repeat on, player stays minimized, I turn it off = player maximizes/goes into full screen. See here. You should be able to reproduce this:

https://streamable.com/lszsmu

In 4.39.50 this behavior wasn't happening.

**Comment by milindgoel15** [comment]
Ah yes

**Comment by Harmonie666** [comment]
I went back to 4.39.50 until this bug is dealt with, and "Enforce Repeat" is working without causing other issues.

Thanks for understanding, and sorry for tagging dev. I won't do it anymore.

**Comment by Harmonie666** [comment]
Thanks I'm looking forward to the release.
