### ISSUE TITLE
[Idea]Load audio codec priority.

### ISSUE THREAD

**Issue by Originalimoc** [YTVanced/Vanced#1628]
For both YouTube Vanced and YouTube Music Vanced.
Premium user can request 141 codec for music videos. Then 251, then 140. To me 160kbps Opus(251) sounds better than 128kbps AAC(140).
Stock behaviour is 251 for YouTube and 141/140 for YT music.
For non premium user, 251 unchanged, 140 changes to 251.
For premium user, 251 changed to 141, 141 unchanged.

**Comment by Originalimoc** [comment]
And another idea, disable/kill/don't load 249 in any case, it's a horrible thing and should go to hell.

**Comment by milindgoel15** [comment]
Please post audio-related ideas in #1143
