### ISSUE TITLE
[Bug] Bottom Android toolbar missing after maximizing video

### ISSUE THREAD

**Issue by petruccigp** [YTVanced/Vanced#1634]
**Bug description:**
Android screen misses the home bottom toolbar after maximizing video.

**Have you read vanced guides already? (YES/No)**
Yes, could not find anything particularly related to this issue neither in the guide nor in already opened issues. Only "similar" one I could find is [#1606](https://github.com/YTVanced/Vanced/issues/1606)
I have tried fully removing all Vanced apps (manager and Youtube) and reinstalling, the issue persists.

**Variant:**
Non-Root

**Vanced version:**
17.03.38
The issues was present with the latest offered v16 app as well.

**Link used to download vanced:**
Vanced Manager

**Android version:**
Android 12 (Samsung UI 4)

**Device:**
Samsung A52s 5G

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2. Start playing any video
3. Go full screen by rotating the phone (have tried to reproduce by pressing the fullscreen button, but could not reproduce). The issues sometimes cannot be reproduced, but I get it typically one out of three times by playing different videos
4. Go out of full screen by turning the phone again
5. The bottom row home toolbar is not displaying
6. Dragging from the top to display the quick access fixes the GUI

I've tried disabling "Home Screen - Rotate to landscape mode". The issue still reproduces.

**Expected behaviour:**
Bottom toolbar should still be visible after entering and exiting full screen

Issue being displayed: 

![Issue being displayed](https://user-images.githubusercontent.com/658179/154666179-cd3517b9-cc09-4740-a88f-bd3708ecae14.jpg)

Expected behaviour:

![Expected behaviour](https://user-images.githubusercontent.com/658179/154666231-1fa53346-8037-45b1-835a-4300203e4098.jpg)

Top toolbar gets mangled with bottom home row buttons in some occasions:

![Top toolbar gets mangled with bottom home row buttons in some occasions](https://user-images.githubusercontent.com/658179/154666455-ad4bcc18-f1ac-4ea1-977b-ee51ec7bf581.jpg)

**Comment by milindgoel15** [comment]
Does it happen on same stock yt version?

**Comment by petruccigp** [comment]
Hi @milindgoel15 . I've been trying with different apps and was able to replicatevit with other video streaming apps (jellyfish), so my conclusion is that it's most likely an Android or Samsung UI issue. Closing this one. Thanks
