### ISSUE TITLE
Bug long description

### ISSUE THREAD

**Issue by Katy9900** [YTVanced/Vanced#1635]
**Bug description:**
When description of video is long half of it is not able to be seen

**Have you read vanced guides already? Yes

**Variant:**
Non-Root

**Vanced version:**
v17.03.38

**Link used to download vanced:**
I downloaded it from Vanced Manager

**Android version:**
Android 6.0

**Device:**
MYA-L11

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2. Click on video where description is long
3. Half of it will not be able to be seen

**Expected behaviour:**
The whole description shall be seen
![Screenshot_2022-02-18-13-29-49](https://user-images.githubusercontent.com/99971022/154690583-56f3e3b3-0e8b-48c5-85a6-1c7c4b1dbc9a.png)

_Attach images or videos or logcats in case of crashes if possible. These can help solve the issue._

**Comment by milindgoel15** [comment]
Does it happen on same stock yt version?

**Comment by Katy9900** [comment]
Hi!
I checked it and yes it also happens on youtube stock version.

**Comment by milindgoel15** [comment]
Then it's actually an issue with your device OS (something to do with your dpi). Nothing we can do about it.
