### ISSUE TITLE
[suggestion]

### ISSUE THREAD

**Issue by imxcr** [YTVanced/Vanced#1637]
player subtitles setting, or change the appearance of the default YouTube captions

**Comment by imxcr** [comment]
manga[]()https://mangahasu.se/

**Comment by imxcr** [comment]
[]()https://mangahasu.se/

**Comment by imxcr** [comment]
[hasu](https://mangahasu.se/)

**Comment by milindgoel15** [comment]
The subtitles can changed within your device OS settings. Look it up.
