### ISSUE TITLE
[Idea] Stop autoplay in downloaded videos

### ISSUE THREAD

**Issue by BenjaminFraeyman** [YTVanced/Vanced#1638]
**Description**
I love Vanced for the extra customization it provides.
I do however also use Premium.
I have videos downloaded but it acts as a playlist where at the end of 1 video, the next automatically plays.
I'd like the option to stop the video at the end because i fall asleep sometimes and dont want my phone to be dead by morning :)

I looked through recent issues and didnt see a similar one. 
Thanks already :)

**Comment by milindgoel15** [comment]
Duplicate of #1079

**Comment by milindgoel15** [comment]
It happens because downloaded videos loads up as a playlist, not individual videos and as auto play is the default and only behaviour in playlists.
