### ISSUE TITLE
[Bug] replaceme

### ISSUE THREAD

**Issue by theredbaron05** [YTVanced/Vanced#164]
**Bug description**
My youtube vanced crashes with most actions other than opening a video on the front page and even then trying to open the channel window crashes it. Opening subscriptions or library crashes it and if I'm lucky it won't but it will crash later when just navigating youtube

**Variant**
NonRoot: Yes

**Vanced version**
15.43.32 - Build - 01.47.00

**Android version**
Android 8.1 - Oreo

**Device**
Samsung Galaxy Tab A 10.1 SM-T580

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2. Click on subscriptions

3. crash
**Expected behavior**
doesn't crash

**Comment by gghhkm** [comment]
This could fix it.

#### Preparations for clean install
• if you've already installed it and have problems
Remove the microG account from system settings and uninstall Vanced & MicroG & Vanced Music, then reboot. 

#### Installation
Make sure you're using Vanced Manager 2.4.0+, Install MicroG and disable battery optimization ( https://dontkillmyapp.com/ ) for it ASAP, install Vanced V15.40.37 &/or Music V4.04.52.
Make sure to follow the guide below about the MicroG bug if you plan on updating to Vanced V16+ & V Music V4.11+ . https://github.com/Vendicated/Vanced/blob/master/Guides/VancedLoadingFix.md 

I'm going to close this now, but feel free to reopen it if the solution provided doesn't work.
