### ISSUE TITLE
[Bug] SponsorBlock Segment Voting overlays on Minimize 'X' Button

### ISSUE THREAD

**Issue by John-Afolayan** [YTVanced/Vanced#1653]
**Bug description:**
When entering full-screen mode, the X button on the top right of the device is not accessible since the SponsorBlock segment voting icon is placed on top of the button.

**Have you read vanced guides already? (YES/No)**
YES

**Variant:**
Non-Root

**Vanced version:**
v17.03.38

**Link used to download vanced:**
Vanced Manager.

**Android version:**
Android 11 

**Device:**
OnePlus 7 Pro

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2. Click on a video and enter fullscreen mode
4. Check the top right of the screen where X/minimize button is located
5. The SponsorBlock segment voting button is overlaid on the X/minimize button
6. Note: Recreating this issue is not consistent, it happens at random.

**Expected behaviour:**
The SponsorBlock segment vote button should be to the left of the X/minimize button.

_Attach images or videos or logcats in case of crashes if possible. These can help solve the issue._
![Screenshot_20220219-140414](https://user-images.githubusercontent.com/49284081/154816235-6aca8b4e-4b08-4aa4-8f64-2ebf6f2aecce.jpg)

**Comment by milindgoel15** [comment]
Yep known issue. No fix available for it. Guess you have to live with it
