### ISSUE TITLE
[Bug] Stream to SmartTubeNext rarely working

### ISSUE THREAD

**Issue by itobey** [YTVanced/Vanced#1658]
**Bug description:**
I'm a heavy user of the streaming feature to connect my Vanced to my Android TV running SmartTubeNext. Since updating to Vanced 17.03.38 the list of devices when hitting the stream button does only rarely show the SmartTubeNext device. Sometimes just hitting and closing it a few times will make it appear, sometimes it just takes a few minutes. Eventually it shows up, but everytime while watching the video on the Android TV Vanced loses the session and I'll have to go through the hassle again, until it sometimes finally appears again in the list for the next video stream. This didn't happen before the update. Re-pairing the devices and rebooting did not fix the issue.

**Have you read vanced guides already? (YES/No)**
Not applicable imo.

**Variant:**
Non-Root

**Vanced version:**
17.03.38 | (SmartTubeNext Version: 14.16)

**Link used to download vanced:**
Vanced Manager, installed from the official website

**Android version:**
10 on Phone, 8 on TV

**Device:**
OnePlus 7t, TV: Sony KD-55XD7004 

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2. Choose a video
3. Hit the stream to button on the top
4. the SmartTubeNext device may be missing
5. a) wait a few seconds, re-open the app, play around and check again, it may have appeared and you can stream
6. b) pair the SmartTubeNext device by code and play the video
7. after a few minutes watching choose another video, the session is now lost and you have to restart Step 5 or 6

**Expected behaviour:**
It should keep connected to the stream device or at least the device should stay in the list of devices and not disappear.

**Comment by milindgoel15** [comment]
> Vanced Manager, installed from the official website

Define "official website"

And 

Check your issue on stock YouTube 17.03.38.

**Comment by itobey** [comment]
I got the manager from: https://vancedapp.com/

Unfortunately stock YouTube streaming does not work for me, as I get a notification from Vanced to update google play services, but it just displays a retry button. This has not worked for me in older versions as well.

If I could get my hands on the recent Vanced apk before the current one, that would be fantastic to see if it's an issue with the version. However the only release here is the current one, which is quite disappointing.

**Comment by milindgoel15** [comment]
> Unfortunately stock YouTube streaming does not work for me,

No, the official YouTube relies on built-in Google play services. It doesn't use vanced microG for login or casting. The official YouTube have no issues with Casting whatsoever (you are using microG based ROM which you think you are not, so that's not the case)

>as I get a notification from Vanced to update google play services

In continuation of my reply from above, when beginning to cast from official YouTube, vanced has no role to play here. Hence, it shouldn't be giving such notification either.

> However the only release here is the current one, which is quite disappointing.

We started uploading on GitHub just a few days back. But they are NOT in the apk format. They are bsdiff files which needs to compiled first to be able to install on any device. We currently are going for different backend approach for managing the vanced releases instead of using some other third party service for hosting apks.

**Comment by itobey** [comment]
Thanks for the reply. I do understand that this error should not be happening, but it does anyway. Strangely I can cast from the official YouTube app on my phone to the official YouTube app on my TV.

I saw there are no apks on here and imagined the files have to be compiled first. As it's just the current release, no point in doing so for me. I would suggest that you guys just upload every minor release here as an apk, that would probably be helpful for other people as well. But for now I'm stuck on my issue, as there's no way for me to rollback to the last version which worked for me. Guess I'll have to wait then.

**Comment by milindgoel15** [comment]
![IMG_20220221_082324.jpg](https://user-images.githubusercontent.com/45682747/154881561-d6a74823-cd64-40a0-aef3-15429e241a65.jpg)
![IMG_20220221_082342.jpg](https://user-images.githubusercontent.com/45682747/154881569-d903cd35-c057-4f21-8fd9-b0f6b47f019e.jpg)
![IMG_20220221_082359.jpg](https://user-images.githubusercontent.com/45682747/154881581-ef98a963-df58-4bad-a4d9-bdedfa8948be.jpg)
![Screenshot_2022-02-21-08-24-04-526_com.vanced.manager.jpg](https://user-images.githubusercontent.com/45682747/154881591-dffd3ac1-6703-4959-bc16-541083fe2616.jpg)

You can get old versions here.

**Comment by itobey** [comment]
Thanks a lot. For some reason the streaming works as of today again without issues. I have not changed anything though. Really weird but I guess I can close this issue now. Thanks for your help.
