### ISSUE TITLE
[Idea] Completely remove Shorts (add toggle option)

### ISSUE THREAD

**Issue by aioue** [YTVanced/Vanced#1659]
**Description**
Add a settings option to disable Shorts appearing in searches, remove the Shorts tab, and if possible via video metadata, don't show shorts anywhere in suggested videos or anywhere else in the app.

User story: I compulsively browse short-form media, and am completely unable to stop scrolling that when I encounter it.

After Youtube added shorts, I now regularly lose a hours to compulsively browsing Shorts and it's disrupting my life. I'm tired of having to delete all my entertainment apps. Paying for Premium and google don't even reply to feature requests or feedback about this.

Willing to donate to have an option to totally hide Shorts and Shorts related links.

**Comment by TheAmazingBen100** [comment]
#334 
also your fault for being addicted to them

**Comment by tremarley** [comment]
Is this a possibility, up until the latest update we were able to enable 'Comments Location (alpha) in the Layout Settings but now we can't

Is this on the roadmap?

I have YouTube Premium but the main reasons I use Vance's is because it gives us the ability to remove that annoying Shorts Tab

**Comment by milindgoel15** [comment]
> Is this on the roadmap?
Nope, it isn't. (not as of now)
