### ISSUE TITLE
[Bug] Tapping the Chapter Section (By Timestamp) Doesn't Open List of Chapters

### ISSUE THREAD

**Issue by daylightEX** [YTVanced/Vanced#1661]
**Bug description:**
Tapping the name of the current section of video, located to the right of the current timestamp and just above the seek bar, doesn't open the chapter list as it should. This worked as intended before the latest update, and still works fine on the official YouTube app. 

**Have you read vanced guides already?
Yes. 

**Variant:**
Non-Root.

**Vanced version:**
YouTube Vanced: 17.03.38.

**Link used to download vanced:**
I downloaded and installed YouTube Vanced through the Vanced Manager app. 

**Android version:**
Android 12. 

**Device:**
Samsung Galaxy S10+.

**Steps to Reproduce**
Just open the app, watch a video that has different chapters that are timestamped, try and click the chapter name to open the chapter list. 

**Expected behaviour:**
The chapter list should open, as it did in previous versions and as it does in the current official YouTube app.

**Comment by milindgoel15** [comment]
Stock bug
![IMG_20220222_090922.jpg](https://user-images.githubusercontent.com/45682747/155058871-1bfc00b6-a620-4490-91ed-176e1166b8bf.jpg)

If you test your bugs on the very latest base from Google, then yea Google patched the bug later on. Wait for new base release ig?
