### ISSUE TITLE
[Bug] Caption Preferences

### ISSUE THREAD

**Issue by Zyo20** [YTVanced/Vanced#1663]
**Bug description:**
I've been waiting for this issue to be reported but it seems no one did (or maybe only I experienced this). I've been wondering why the caption preferences does not apply on YouTube Vanced. I usually customize it to Serif-Drop Shadow, but when I apply it system-wide, it just uses the default font and no font outline. I tried testing it on the stock YouTube app and it works just fine.

**Have you read vanced guides already? (YES/No)**
Yes

**Variant:**
Non-Root

**Vanced version:**
v17.03.38

**Link used to download vanced:**
Downloaded using Vanced Manager

**Android version:**
Android 11 

**Device:**
OPPO A92

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2. Choose a video that has CC

**Expected behaviour:**
The player should be able to pick up the customized caption found on Accessibility settings

Vanced:
![Screenshot_2022-02-22-07-36-27-18_7a4090f09f6554852d748ee9fd6f40d3](https://user-images.githubusercontent.com/24516479/155038712-a039755a-d13e-4865-8cb9-790a9a7ae667.jpg)

Stock YouTube app:
![Screenshot_2022-02-22-07-37-30-08_f9ee0578fe1cc94de7482bd41accb329](https://user-images.githubusercontent.com/24516479/155038734-87fa137c-0920-49f5-bf8c-87eab9c37579.jpg)

**Comment by milindgoel15** [comment]
Works fine. Do basic troubleshooting and it will get fixed.
