### ISSUE TITLE
[Bug] Weird video glitch

### ISSUE THREAD

**Issue by Mike2003ca** [YTVanced/Vanced#1664]
**Bug description:**
It looks like a glitched transmission on a TV.

**Have you read vanced guides already? (YES/No)**
Yes.

**Variant:**
Non-Root

**Vanced version:**
17.03.38

**Link used to download vanced:**
https://vancedapp.com

**Android version:**
9

**Device:**
Huawei P10

**Steps to Reproduce**
Happens randomly. Restarting the app send to fix it for a while.

**Expected behaviour:**
Video is glitched while audio is not. It shouldn't happen.

https://1drv.ms/v/s!AhtnGyCgF5q1mUf4BVxsvK-l8nQr

**Comment by milindgoel15** [comment]
Stock YouTube v17.03.38 bug. Will get resolved with a new base update whenever it gets released.

For now, either downgrade to an old version or try disabling HW overlays from device developer options (if this doesn't help, downgrade is the only option)

**Comment by milindgoel15** [comment]
#1630
