### ISSUE TITLE
[Idea] implement age restriction bypass

### ISSUE THREAD

**Issue by Jann3107** [YTVanced/Vanced#1665]
**Description**
Implement [this Simple YouTube age restriction bypass](https://github.com/zerodytrash/Simple-YouTube-Age-Restriction-Bypass) 
Maybe also add an option to enable or disable it.

**Comment by TheAmazingBen100** [comment]
Browser extensions DO NOT WORK in apps.

**Comment by milindgoel15** [comment]
#173

**Comment by Jann3107** [comment]
I know, but in the Readme is described how you can bypass the age restriction. (and you can implement that method in apps)

**Comment by milindgoel15** [comment]
> I know, but in the Readme is described how you can bypass the age restriction. (and you can implement that method in apps) 

YouTube on Browser works differently than android app.

**Comment by Jann3107** [comment]
But somehow it has to get the video magical from the internet. And couldn't you change that point so it just tries to get the viedeo from the "unrestricted" endpoint?

**Comment by Jann3107** [comment]
But how does it download the videos?
I cannot see the code so I'm just trying to understand what limits you...

**Comment by KevinX8** [comment]
The APIs the app use are completely different, most of it is done over protobuf and then rendered with litho and exoplayer v2, the inside bares no resemblance to the website version

**Comment by milindgoel15** [comment]
More info: 
Vanced ain't any separate app. It is built right on top of official YouTube app. Whatever google provides, you get.
