### ISSUE TITLE
[idea] SponsorBlock

### ISSUE THREAD

**Issue by gghhkm** [YTVanced/Vanced#167]
Instead of having the segment adding icon sit there on the video player UI, how about putting a setting for it here :
![Screenshot_20201108-095308](https://user-images.githubusercontent.com/72711094/98468623-525dca00-21a9-11eb-8f03-487dfc48390b.jpg)
You could also add the General SponsorBlock settings in that menu too. It would be convenient.

**Comment by KevinX8** [comment]
The source code of the sponsorblock implementation is here https://github.com/YTVanced/SponsorBlock and putting ideas for it would probably be best to be put on that repo, we also accept pull requests

**Comment by gghhkm** [comment]
> The source code of the sponsorblock implementation is here https://github.com/YTVanced/SponsorBlock and putting ideas for it would probably be best to be put on that repo, we also accept pull requests

Ah, ok.
