### ISSUE TITLE
[Bug]  Update to 17.03.38 broke comment-editing

### ISSUE THREAD

**Issue by Michas0206** [YTVanced/Vanced#1672]
**Bug description:**
With latest update to 17.03.38 I am not able to write comments anymore / edit these -
when I write something and then trying to mark typo errors or parts of the text, a big fat dark 'field' opens and I do not see the text anymore. It covers the text, the keyboard and it is not movable.

It looks as if it tries to open a 'picture in picture' for videoplayback and its nearly impossible to edit comments anymore. 

**Have you read vanced guides already? (YES/No)**
Yes 

**Variant:**
Non-Root

**Vanced version:**
17.03.38

**Link used to download vanced:**
vanced manager

**Android version:**
Android 11 (Lineage OS 18.1)

**Device:**
LG V20

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2. Write a comment
3. Mark parts of it

**Expected behaviour:**
Expected: a small field with 'copy, paste, share' opens (and not such a big, black box)

_Attach images or videos or logcats in case of crashes if possible. These can help solve the issue.
![Screenshot_20220223-103535_YouTube_Vanced-01](https://user-images.githubusercontent.com/29848666/155293518-7cd90bf4-f07f-47c1-88a9-481002010164.jpeg)
_

**Comment by TheAmazingBen100** [comment]
stock yt bug. wait for google to patch it.

**Comment by Michas0206** [comment]
Seems youre right, a downgrade to 16.** makes no difference...strange.
However, then I'll have to wait.... 😑 
Thanks anyway for your efforts + fast reply
