### ISSUE TITLE
Have to go to full screen twice to get full screen 

### ISSUE THREAD

**Issue by awesomeferret** [YTVanced/Vanced#1674]
When using a clean install, things work as they should. Then, it will randomly decide to exhibit the behavior that I will describe in a moment, and will do so in a 100 percent reproducible manner going forward once it has "decided" to exhibit this bug.

The unwanted behavior is this: when you tap the full screen icon, no rotation or full screen will happen. Instead, it very briefly goes "full screen" in portrait mode (black bars on top and bottom) with the "rotate" thingy popping up, then immediately goes back to portrait view. The second time you tap full screen, it works as expected. Having it take two tries to go full screen is very strange, and it's ALWAYS two times.

Android 8.0, latest Vanced microG and latest Vanced build (17.03.38).

I thought this may be related to my choosing the "wide search bar" feature or "copy button" feature, but I disabled those and the bug still persists.

**Comment by milindgoel15** [comment]
ROM issue

**Comment by awesomeferret** [comment]
Wait... HOW is it a "ROM issue"? This is a stock, unmodified ROM. Closing that for such a reason is VERY dubious. You are obligated to provide an explanation for ignoring this very serious bug, since with that very shaky logic, you could say ANY bug for ANY version of Android is a "ROM issue". I did not expect such a rude and offensive response from the Vanced team. This is basically a "screw you, we don't want to fix this issue" response.
