### ISSUE TITLE
[Question] How do I enable video search in channel?

### ISSUE THREAD

**Issue by fromtheeast710** [YTVanced/Vanced#1681]
**Description**
In the HOME bar and next to ABOUT in a channel view, there used to be search bar that allow me to search for videos within that channel. But after a re-installation of Vanced, that icon is gone and I can't find a config to re-enable it.

**Comment by milindgoel15** [comment]
YouTube app never had such a button. It only exists on web version.

**Comment by fromtheeast710** [comment]
Can I submit a request for such feature to be implemented?

**Comment by milindgoel15** [comment]
Only if we had source code of actual YouTube code.. Gotta ask Google to reimplement such feature?
