### ISSUE TITLE
[Bug] Video title position distorted

### ISSUE THREAD

**Issue by MuhammetEminCakir** [YTVanced/Vanced#1682]
Bug description:
Video title position is distorted when playing any video over YouTube Vanced while Tablet mini player is enable

Have you read vanced guides already? 
YES

Variant: 
Non-Root

Vanced version: 
v17.03.38

Link used to download vanced: 
https://github.com/YTVanced/VancedManager/releases/download/v2.6.2-262/manager.apk
https://api.vancedapp.com/api/v1

Android version:
Android 11 

Device:
Xiaomi mi 11 lite(4G)

Steps to Reproduce
Steps to reproduce the error:
1. Open the app
2. Open Vanced settings
3. Enable Tablet mini player
4. Play any video on YouTube Vanced

Expected behaviour:
Video titles appear at the top of the video even when Tablet mini player is enable

Tablet mini player disable
![WhatsApp Image 2022-02-24 at 13 07 16](https://user-images.githubusercontent.com/64583157/155507210-74dfc12a-9da4-4a33-836d-b02e64cef156.jpg)

Tablet mini player enable
![WhatsApp Image 2022-02-24 at 13 07 16 (1)](https://user-images.githubusercontent.com/64583157/155507509-0579338c-2fcb-4ef3-8aad-6abc8fed833b.jpg)

**Comment by milindgoel15** [comment]
The whole point of tablet mini player is to enable tablet version of player UI. It's intended to show like that because tablet screens are larger than phones. Hence, you will see it above the video instead of the normal position.

**Comment by MuhammetEminCakir** [comment]
But its work fine with v16

**Comment by milindgoel15** [comment]
Because v16 still uses the old player UI but Google has been pushing new UI to v17 now.
