### ISSUE TITLE
Can't login to youtube vanced with my main account.

### ISSUE THREAD

**Issue by amir2543** [YTVanced/Vanced#1683]
Hi I've been using youtube vanced for a few months with my old android phone and the latest youtube vanced version that it supports is 14.05.56. It has been working flawlessly but in the last few days I couldn't login to my main account it just says "There was a problem with the... Tap to retry" but when I try to login to another account it works without giving any errors. I tried everything I even factory reset my phone and kicked out everyone from my google account but nothing helped. Is there any way to fix this?

**Comment by milindgoel15** [comment]
Does it work on official YouTube app with the account you are having trouble logging in?

**Comment by amir2543** [comment]
No it gave me the exact error on there too.

**Comment by milindgoel15** [comment]
Then ig your YouTube account has been banned by Google for violating their tos. You much have received a mail from Google stating what exactly you violated. Nothing we can do here.

(And moreover, just a FYI, Google doesn't ban users for using vanced or any means of ad blocking software.)

**Comment by amir2543** [comment]
Yeah It worked on my pc. I even tested it on an emulator and it also worked. so I guess my phone is the problem but why does other accounts work in my phone that's weird.

**Comment by amir2543** [comment]
I fixed it by making a brand channel on my main google account then transferred the main channel to the brand channel and added my second google account that worked on my phone to the list of admins of the brand channel and now it works. That was such a headache tho.

**Comment by TheAmazingBen100** [comment]
V15 and older no longer works because of a change on Google's end. Please use V16 or newer.

**Comment by amir2543** [comment]
Oh, well that sucks because my phone doesn't support higher versions. Thank you both for answering though. I'm going to close this because my problem is solved.
