### ISSUE TITLE
[Bug] scroll lag

### ISSUE THREAD

**Issue by bernard671997** [YTVanced/Vanced#1684]
**Bug description:**
Scroll animation lag on comunity posts when using 120hz refresh rate

When scrolling the animation gets laggy like if its now on 60hz and i need to stop scrooling to make it go back to normal, but the problem soon returns.

**Have you read vanced guides already? (YES/No)**
yes

**Variant:**
Non-Root

**Vanced version:**
17.03.38

**Link used to download vanced:**
Oficial one: https://vancedapp.com/

**Android version:**
Android 12

**Device:**
 Samsung Galaxy S20 FE 5G

**Steps to Reproduce**
Steps to reproduce the error:

If open the app and go to comunity posts, not every one, just the ones that include voting polls, sometimes the scrolling animation gets laggy and it only stops if i stop scrolling but then it returns. 

Problem only when using 120hz mode

*Expected behaviour:**
smooth scrolling

**Comment by milindgoel15** [comment]
Try basic troubleshooting such as clearing data or reinstallation. Not a vanced issue
