### ISSUE TITLE
[Bug] Video won't load

### ISSUE THREAD

**Issue by GKid94** [YTVanced/Vanced#1685]
**Bug description:**
Some videos won't load when you open them

**Have you read vanced guides already? (YES/No)**
Yes

**Variant:**
Non-Root

**Vanced version:**
17.03.38

**Link used to download vanced:**
https://vancedapp.com/

**Android version:**
Android 11 

**Device:**
Xiaomi Redmi 9 4GB

**Steps to Reproduce**
The problem only happens sometimes on some videos so try to open the one on the image and test it

**Expected behaviour:**
For the video page to load instantly

![155423095-ce34454e-05af-49cc-851d-30125c99e3f1](https://user-images.githubusercontent.com/18757054/155584704-e0540ff3-57e4-4ad9-a5eb-79392fefc7c2.jpg)
![155423098-c2df4248-2d7c-496f-a39f-6d5ad2bf4a25](https://user-images.githubusercontent.com/18757054/155584707-5cc89d88-85ab-4b6d-9c24-e3401c5814f1.jpg)
![155423100-9e76e11f-a98d-480c-b398-64071311e8e3](https://user-images.githubusercontent.com/18757054/155584710-3d42804d-bc48-4873-af74-878539bf0bd3.jpg)

**Comment by milindgoel15** [comment]
Problems with your network connection. Videos are loading fine

**Comment by GKid94** [comment]
> Problems with your network connection. Videos are loading fine
> 
> (Just clear cache and it will work fine. If it doesn't, check if your network connection is not doing any excessive tasks but yea it's totally network related)

I have a full Wi Fi signal as you can see

**Comment by milindgoel15** [comment]
Network connection issues is caused by many factors. Having full signal strength doesn't necessarily mean you have good internet connection. The quality of that strength matters. 

The things you should try on your end is to do basic troubleshooting, involving clearing app data or reinstallation.

**Comment by GKid94** [comment]
@milindgoel15 My internet speed is 100/10
![Screenshot_2022-02-25-19-17-56-776_org zwanoo android speedtest](https://user-images.githubusercontent.com/18757054/155767163-6dafa484-4309-4ba3-905c-c1f2416381a5.jpg)

**Comment by milindgoel15** [comment]
You are also using VPN, try disabling that. Plus i don't think you even bothered doing basic troubleshooting since you are just complaining about your network again and again. 

(And your internet speed ain't even close to 50 which you said 100 for it but ok, as said earlier as well, the issue is caused on your end only)

**Comment by GKid94** [comment]
@milindgoel15 Disabled Blokada and it's still happening
![Screenshot_2022-03-01-16-26-36-169_com vanced android youtube](https://user-images.githubusercontent.com/18757054/156197758-269b6113-aa6a-4a4f-8a8f-9bcbb17a09cc.jpg)

**Comment by milindgoel15** [comment]
The issue is still affected by your device itself. Whatever you are using in your device (dns, ad blocker, or anything) is causing it. Try to reset your settings, particularly related to networks and all.

**Comment by GKid94** [comment]
I think it's a system problem because it happens in other apps too
