### ISSUE TITLE
[Idea] Bypass AVMSD age gate

### ISSUE THREAD

**Issue by Kamil118** [YTVanced/Vanced#1686]
**Description**
Currently when watching age restricted video from European Economic Zone IP address youtube app will demand you to verify your identity with an ID or credit card. As this is an obvious privacy concern, it would be useful to be able to bypass this age gate.

https://support.google.com/youtube/answer/10070779?hl=en#zippy=%2Cif-youre-in-the-european-union-eu-european-economic-area-eea-switzerland-or-united-kingdom

https://media.discordapp.net/attachments/178922555602632704/946582944699514930/Screenshot_2022-02-25-02-42-19-05.jpg

**Comment by milindgoel15** [comment]
Google has already patched out any bypass tricks. Hence, vanced won't implement any bypass in the near future. Ask Google
