### ISSUE TITLE
[Question] Chapters Missing 

### ISSUE THREAD

**Issue by Red-Baran** [YTVanced/Vanced#1692]
**Description**
After the latest update to 17.03.38 I no longer see any chapters. Ad/into/etc segments work. 

How can I enable chapters again? 

_Attach images/videos if possible. These can be helpful in figuring out what the question is about._

**Comment by milindgoel15** [comment]
Chapters are meant to be turned on or provided by the creator of that video itself. App clients doesn't have anything to do with it. 

So if you are not seeing chapters, ask your creator to enable or provide it. You can even check using YouTube website to confirm whether such video have any chapters.

If a video have chapters but you are not able to click them to open chapters list, then this is a stock bug. A future base release will automatically address such issue.
