### ISSUE TITLE
[Bug] Vanced playlist stops immediately 

### ISSUE THREAD

**Issue by dayo05** [YTVanced/Vanced#1696]
**Bug description:** Sometimes when I play playlist from vanced, video sometimes stop.

**Have you read vanced guides already? (YES/No)** Yes. 

**Variant:**
Non-Root/Root non root

**Vanced version:** 17.03.38

**Link used to download vanced:**
I've updated via vanced manager

**Android version:**
12 

**Device:**
Galaxy S10 5g

**Steps to Reproduce**
Open the app
Play any playlist
Wait for times
Video stops itself

**Expected behaviour:**
Video never stops on playing playlist

**Comment by milindgoel15** [comment]
Could u elaborate "Video stops itself"?

**Comment by dayo05** [comment]
Video stops without any control

**Comment by milindgoel15** [comment]
> Video stops without any control

Any screen/video recording you can provide?

**Comment by dayo05** [comment]
I found why, It has caused by video paused, continue watching message.
I suggest removing this message

**Comment by milindgoel15** [comment]
Then it's no longer a bug. Closing this issue.

About the second part, we may or may not.
