### ISSUE TITLE
[Idea] An option that disables sponsorblock for certain videos?

### ISSUE THREAD

**Issue by jakdev2** [YTVanced/Vanced#1698]
Sometimes you just don't want sponsorblock, and in those cases going to the home screen, pressing your profile pic, going to config, going to sponsorblock menu, and finally disabling it is not convenient. A quicker way to do that would be cool, like a little button that enables/disables sponsorblock for that video or something similar.

(maybe there is already something like this, in which case im dumb)

**Comment by milindgoel15** [comment]
Yes, it is already there. Go to sponsorblock settings > channel whitelisting which will enable the button below the video player itself allowing you to whitelist channels altogether.
