### ISSUE TITLE
[Idea] Option to remove notification grouping

### ISSUE THREAD

**Issue by ZH0UDUS** [YTVanced/Vanced#1701]
Hello, my apologies if this is bothersome, and before anything I'm sorry if I make any language mistakes, English isn't my first language!

**Description**
I would like to suggest an option to remove the notification grouping and return it to normal notifications? YouTube added this feature months ago, but it's been constantly bothersome and annoying, especially when you follow channels that constantly stream! 
This is, if it's even possible to implement this option. (I've read that iOS normal YouTube app does have this option, it's just android that does not have it.) 

Attaching a screenshot of how notifications look, they are basically grouped into playlists even if you've already watched the video or even if it's the same video. (it counts "[Channel name] is going live in 30 minutes!" and "[Same channel] is live!" as different videos.)
![IMG_20220301_134102](https://user-images.githubusercontent.com/100715576/156220781-52971692-05e3-4950-8a8c-8b43cc549d71.jpg)
![Screenshot_2022-03-01-13-44-55-364_com vanced android youtube](https://user-images.githubusercontent.com/100715576/156220964-7f7ce107-16ba-4e69-b8e5-95957c11ccf2.jpg)

**Comment by milindgoel15** [comment]
Only Google can do it. Ask them
