### ISSUE TITLE
[Idea] For the SponsorBlock

### ISSUE THREAD

**Issue by LOSEARDES77** [YTVanced/Vanced#1704]
**My idea was to make a button that appears when a part eith a sponsor is cming and when you click it skip it not automaticaly skip it.
Lile netflix has to skip intros**

**Comment by milindgoel15** [comment]
It already exists. Maybe search what all settings exists before creating issues?

Go to Sponsorblock settings > tap on any segment u want to change skipping of and do ur thing

![Screenshot_2022-03-02-18-48-47-223_com.vanced.android.youtube.jpg](https://user-images.githubusercontent.com/45682747/156369420-1e759899-f1bc-440b-aff2-5da46adec630.jpg)
