### ISSUE TITLE
[Idea] Add a button to replay the video from the start

### ISSUE THREAD

**Issue by asdsadsaasd12312132** [YTVanced/Vanced#171]
I frequently rewatch videos that I don't finish but would like to rewatch them from the start. It would be very convenient to get a button to instantly start the video from the beginning again.

**Comment by milindgoel15** [comment]
Please update to the latest v16.16.38 if you haven't already and use the auto-repeat feature from vanced settings > misc while keeping autoplay off. We are closing this issue. Feel free to reopen if you still face any issues.
