### ISSUE TITLE
[Idea] Vanced Web Application.

### ISSUE THREAD

**Issue by KidCanada7** [YTVanced/Vanced#1710]
**Description**
IOS users need a better way of using YouTube, but sadly many users are left to Jailbreak in order to get that experience. I believe there might be a way to have IOS users able to use YouTube Vanced without having an android device or using alternatives and jailbreaking. XCloud, which is a Cloud Streaming Service from Microsoft, implements the feature I am suggesting, a Web Application (or commonly referred to by developers as "PWA"). Which would allow IOS users to use an App without downloading or jailbreaking. I believe this would be the fastest and easiest way for users and developers to have Vanced on IOS Devices. The only issues however would be translating the app into HTML, CSS, and JavaScript for the PWA. But I am sure that it can be done. 

You can see the XCloud Web App [here](https://www.xbox.com/play)

**Comment by milindgoel15** [comment]
[Please read and follow me](https://telegra.ph/Installation-for-Vanced-09-01#Platforms)

**Comment by KidCanada7** [comment]
Understandable, have a good one!
