### ISSUE TITLE
[Idea] Toggle to replace/remove the shorts button

### ISSUE THREAD

**Issue by fym35** [YTVanced/Vanced#1711]
**Description**
add a toggle i vanced settings to replace or remove the annoying shorts button from the main screen and replace it with something actually useful (or it could be straight up removed)

**Comment by Ghibranalj** [comment]
I like this idea. A toggle for disabling/enabling shorts all together would be nice too as i find shorts very distracting.

**Comment by milindgoel15** [comment]
Duplicate of #334
