### ISSUE TITLE
[Idea] Add multilingual subtitles and remove such banners

### ISSUE THREAD

**Issue by SASUKE0721** [YTVanced/Vanced#1713]
1.Could you add the multilingual subtitles feature of some channels such as the BBC to Vanced?
https://www.youtube.com/watch?v=23q6eNufxZQ

<details><summary>Screenshot :</summary>

![キャプチャ](https://user-images.githubusercontent.com/87330832/156703529-1501074f-6c57-4ed9-99c3-dfb8eeea2596.PNG)

</details>

2.I want you to be able to delete the banner here as well

<details><summary>Screenshot :</summary>

![Screenshot_20220304-141600904_1](https://user-images.githubusercontent.com/87330832/156703932-909afab7-31c9-4864-b69a-9294bcc843dd.jpg)

</details>

**Comment by milindgoel15** [comment]
1st is controlled and provided by Google and the creator of the channel uploading/providing videos. 
2nd is the duplicate issue of #1660
