### ISSUE TITLE
[Bug] the Auto Quality toggle in each video's settings is no longer available

### ISSUE THREAD

**Issue by GitExploraa** [YTVanced/Vanced#1718]
**Bug description:**
the Auto Quality toggle in each video's settings is no longer available

**Have you read vanced guides already? (YES/No)**
Yes

**Variant:**
Non-Root

**Vanced version:**
17.03.38

**Link used to download vanced:**
Official Site

**Android version:**
Android 12L

**Device:**
Google Pixel 4

**Steps to Reproduce**
Steps to reproduce the error:
1.Play any video
2.Open the quality setting picker
3.there's no option to change it to auto (i know its set to auto by default, but after manually changing it, there's no way to go back to Auto on said video)

**Expected behaviour:**
the Auto option to be available to choose from in each video's quality picker

![image](https://user-images.githubusercontent.com/44654056/156886755-89aaa431-2b98-4914-bce5-6661980cf0fa.png)

**Comment by RealKasumi** [comment]
Not a bug. Select the auto quality in YT settings > Video quality preferences, or enable the new (worse) quality settings by going to Vanced Settings > Video settings and then toggling video quality style.

**Comment by GitExploraa** [comment]
i'am aware of both settings, but i just want an auto quality setting to choose from inside this screen, much more convenient imo (like it used to be)

**Comment by milindgoel15** [comment]
It's no longer possible, unfortunately

**Comment by GitExploraa** [comment]
> It's no longer possible, unfortunately

noted, thank you
