### ISSUE TITLE
[Bug] Error Downloading Music

### ISSUE THREAD

**Issue by Powerisinschool** [YTVanced/Vanced#172]
Trying to update my vanced youtube music from the manager and everytime I tap on the update, it gives me a toast saying **`Error Downloading Music`**, which is preventing me from being able to update my music app. I'm running on android 7.0, *I know it's quite old*, but I think this needs to be fixed really soon, or is there any workaround?

## Screenshot:
![image](https://user-images.githubusercontent.com/65245607/98593574-9e0c9280-22d3-11eb-84f9-25673594e160.png)

### Variant
- NonRoot: Yes

### Android version
- Android 7.0 - Nougat

### Steps to Reproduce
- Steps to reproduce the error:

- Open the app

- Click on Update

> Toast: Error Downloading Music

### Expected behavior
- Downloads the app

> **Thanks for help rendered**

**Comment by Brian95852** [comment]
I have the same problem.

**Comment by GitStudying** [comment]
I have the exact same problem. 
Android: 9
No root
Version manager: 1.3.1

I didn't have the app installed yet so it would be a fresh install.

**Comment by X1nto** [comment]
Please use https://vancedapp.com/api/v1/music/v4.02.51/nonroot.apk until we resolve issue with manager

**Comment by Powerisinschool** [comment]
> Please use https://vancedapp.com/api/v1/music/v4.02.51/nonroot.apk until we resolve issue with manager

Thanks, will do so now
