### ISSUE TITLE
[Idea] add back drop down filter by date or view counts under channel page

### ISSUE THREAD

**Issue by AlexeSimon** [YTVanced/Vanced#1721]
Youtube has once again removed a great option from its users, and I hope YoutubeVanced can once more bring it back.

**Description**

This feature request is about adding back the dropdown menu allowing the user to filter videos by view count or date under a channel>videos page.

Settings should at least be "latest", "oldest", and "most viewed", but this is an opportunity for more choices ("most liked",...)

Best would be to add a setting under vanced settings > layout to turn that dropdown menu on or off.

Thank you in advance

**Comment by RealKasumi** [comment]
server side change, nothing much vanced can do about it

**Comment by AlexeSimon** [comment]
I have no experience with the Vanced App or Youtube's API, but I observed it is still possible to do it in a basic browser (by adding "?view=0&sort=p&flow=grid" after the channel/video url), and worse case scenario I reckon the Vanced App could fetch all videos for this channel and sort them client side.

**Comment by milindgoel15** [comment]
YouTube is not made using web code or anything like that. It's an android client, not a web wrapper.
