### ISSUE TITLE
[Bug] Not able to play above screen resolution-Moto G51

### ISSUE THREAD

**Issue by navkb** [YTVanced/Vanced#1722]
**Bug description:**

 The resolution stays at the max of 1080p even after enabling the option to override to max.

**Have you read vanced guides already? (YES/No)**
 Yes
**Variant:**
Non-Root

**Vanced version:**
v17.03.38 Build 01.55.00

**Link used to download vanced:**
https://github.com/YTVanced/VancedManager/releases/latest/download/manager.apk

**Android version:**
Android 11 

**Device:**
Motorola G51 
Build no:RRYA31.Q3-56-79-2

**Steps to Reproduce**
Steps to reproduce the error:

1.Open the app
2.Click on upper right corner 
3.Go to 'Settings'
4.Vanced Settings→ Video Settings → Toggle:Max Resolution to"Overriden to Max"
5.Click on any 4k or higher than 1080p resolution video
6.Click on upper right corner then Quality.

**Expected behaviour:**
Expect !440p and 2160p options but the resolution only goes upto 1080p.

**Comment by milindgoel15** [comment]
First, not a bug

Second, YouTube will only show 2k/4k resolutions only if your device supports it, which in real, your device packing sd480+ is not even capable of streaming such high quality.

**Comment by navkb** [comment]
Oh ok but what was confusing was my 5 year old Redmi note 3 was able to play 2k 60 fps without hitch on a snapdragon 650 although the phone had a custom rom. So that's why I thought it was a bug.

> First, not a bug
> 
> Second, YouTube will only show 2k/4k resolutions only if your device supports it, which in real, your device packing sd480+ is not even capable of streaming such high quality.
