### ISSUE TITLE
[Bug] Clicking on the web link will jump to the browser to open and watch

### ISSUE THREAD

**Issue by zhugexinmo** [YTVanced/Vanced#1724]
Bug description:
*from google translate
Clicking the web link in other people's community news will directly jump to the external browser, if you open the youtube internal link in the normal version of youtube, such as https://www.youtube.com/watch?v=172IGxuQkRg
It will jump to the video interface directly on youtube, but Youtube Vanced will jump to the browser whether it is an internal link or an external link.

Have you read vanced guides already? (YES/No)YES

**Variant:Non-Root

**Vanced version:17.03.38

**Link used to download vanced:Vanced Manager

**Android version:MUI 13

**Device:Xiaomi 11

Steps to Reproduce
Steps to reproduce the error:
1. Open the app
2. Click on the web link in the community news
3. Automatically jump to the browser to watch the video

**Expected behaviour:Watch directly in Youtube Vanced

https://user-images.githubusercontent.com/45967629/156903563-a944ea08-3ad4-49da-9040-f42f245b6e76.mp4

**Comment by milindgoel15** [comment]
Set your default app link handler or use root version.

[A guide to set defaults can be found here](https://telegra.ph/Installation-for-Vanced-09-01#Default-app)

**Comment by zhugexinmo** [comment]
I read it carefully and did see the solution, and I'm sorry for taking up your time because of the translation deviation and the problem of not reading it very carefully.

**Comment by zhugexinmo** [comment]
> 设置您的默认应用链接处理程序或使用根版本。
> 
> [可以在此处找到设置默认值的指南](https://telegra.ph/Installation-for-Vanced-09-01#Default-app)

I read the solution carefully and set it up as required, but found new problems.
Clicking on the link on Vanced youtube will jump to youtube to watch, if you uninstall youtube, Vanced youtube will jump back to the web page.
So to ensure the viewing experience, you must turn on youtube, Vanced youtube and VancedMicroG at the same time? Wouldn't it look too bulky.

**Comment by milindgoel15** [comment]
> So to ensure the viewing experience, you must turn on youtube, Vanced youtube and VancedMicroG at the same time? Wouldn't it look too bulky.

No, not really. Since you have android 12(MIUI 13), setting vanced as the default app has always been difficult from the start, except for AOSP based ROMs as they are able to just add supported links and keep original yt uninstalled. For MIUI, if you still aren't able to set vanced default, using root variant is the option left. 

But also, there's nothing vanced can do about this.

**Comment by zhugexinmo** [comment]
> 

Thanks for your patient answer, I'll go back and try the root version.
