### ISSUE TITLE
[Idea] Age Restriction Bypass

### ISSUE THREAD

**Issue by jyushiaimono** [YTVanced/Vanced#173]
Apparently YouTube decided to update the age verification system for age restricted videos, forcing you to verify your age with an ID or credit card if you live in a certain area. This is quite troublesome considering a lot of music videos are age restricted for something as simple as having explicit lyrics and its putting a huge dent in my music playlist. I would like to ask for an option to bypass this age verification, so you can continue watching age restricted videos without having to prove an ID or similar. I would like to add on that as of now I am able to watch age restricted videos on the desktop version of YouTube, but not on the mobile version of YouTube and YouTube vanced. Although on desktop it gives me a pop-up that mentions this new requirement. Screenshot attached shows the affected countries and more details on the system. 
![image](https://user-images.githubusercontent.com/74212847/98596661-09586380-22d8-11eb-8a4c-ded5fd9dfa08.png)

**Comment by Funeoz** [comment]
If you could update the app to remove the annoying popup, that would be very nice !

**Comment by KraXen72** [comment]
+1

**Comment by kineci** [comment]
Why is this not going to be implemented?

**Comment by milindgoel15** [comment]
For all those who want answers to this feature request, refer this comment:

https://github.com/YTVanced/Vanced/issues/1150#issuecomment-894770299

**Comment by DraconicNEO** [comment]
> For all those who want answers to this feature request, refer this comment:
> 
> [#1150 (comment)](https://github.com/YTVanced/Vanced/issues/1150#issuecomment-894770299)

That's too bad, it would be nice if we could have a way to bypass age restriction in the Vanced app since apps like Newpipe aren't that reliable for it anymore.

Seems like they're probably not going to work anymore at all on age restricted videos in the not too distant future.

![1newpipe](https://user-images.githubusercontent.com/44508470/154203352-06334d64-cecd-440e-b1a7-783e16a2d260.jpg)
