### ISSUE TITLE
[Idea] Youtube Live Chat Channel Resolver

### ISSUE THREAD

**Issue by Eleazar23535** [YTVanced/Vanced#1731]
**Description**
Youtube Livechat channel resolver

_Attach images/videos if possible. Also add any links to possible other applications with the said feature already implemented._
https://github.com/zerodytrash/YouTube-Livechat-Channel-Resolver

**Comment by milindgoel15** [comment]
Extensions aren't made to work with android app code. If you have some other solution for such feature, you can suggest that.
