### ISSUE TITLE
[Bug] links instantly open in tor browser without asking

### ISSUE THREAD

**Issue by UnknownUser95** [YTVanced/Vanced#1732]
**Bug description:**
As the title says, links (in descriptions for example) always open instantly in tor browser. I do not have it or any browser as a default, because I regularly need to switch where I open links.

**Have you read vanced guides already? (YES)**

**Variant:**
Non-Root

**Vanced version:**
17.03.38 - the latest as of time of writing

**Link used to download vanced:**
I don't know anymore. The installation was a long time ago, but I'd say https://vancedapp.com/

**Android version:**
Android 12, OneUI 4.0

**Device:**
S20FE (G780F)

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2. Click on any link (that is not a YouTube link itself)

**Expected behaviour:**
The default "What app do you want to open this link with?" menu.

**Comment by UnknownUser95** [comment]
I should also say that only YT vanced has this problem. Any other app works completely fine

**Comment by JapanYoshi** [comment]
Go into the settings and turn off "open by default" for Tor Browser. You probably accidentally tapped "always" some time.

**Comment by UnknownUser95** [comment]
I made sure to have no default browser. It isn't. Otherwise it would also apply on other apps as well, but it's just the YT app and YT vanced.
I even made sure that tor is not set to any links. Uninstalling Tor brings back the menu.
It's incredibly weird, but like I said it's in the base YT app too. That's why I think the vanced team can't do anything about it.

**Comment by JapanYoshi** [comment]
Are you definitely sure that you have the default *links* turned off? Specific links can be set to open in specific apps, like YouTube video links on the YouTube app or Facebook posts on the Facebook app. It's a different setting from the default *browser,* in that it only applies to certain links.

If you already knew this, I'm sorry. I know how frustrating it is to have someone tell you what you already know.

**Comment by UnknownUser95** [comment]
Yes I do. This is why this is so weird. Especially because it only happens in the YT apps and nowhere else
