### ISSUE TITLE
[Bug] No option to translate Korean comments

### ISSUE THREAD

**Issue by muddakinjaz** [YTVanced/Vanced#1735]
![Screenshot_20220308-230453](https://user-images.githubusercontent.com/101236000/157370769-51f6c97a-8610-4bec-8297-55e06622704b.jpg)

**Bug description:**
There is no option to translate Korean comments. Other languages are able to be translated into English. It used to work for Korean but now it stopped.

**Have you read vanced guides already? (YES/No)**
Yes. 

**Variant:**
Non-Root

**Vanced version:**
17.03.38

**Link used to download vanced:**
[Replace here with the source/link you used to download and install on your device. 
](https://github.com/YTVanced/VancedManager/releases/latest/download/manager.apk)

**Android version:**
 Android 11 

**Device:**
OnePlus 6T

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2. Click on korean language video
3. scroll down to see korean comments.

**Expected behaviour:**
Expect to see option to translate Korean comments. No translate option appears. For other languages , they do appear.

**Comment by milindgoel15** [comment]
Does it work on official YouTube v17.03.38?

**Comment by muddakinjaz** [comment]
What do you mean official v17.03.38? Regular stock YouTube? Definitely not.

**Comment by milindgoel15** [comment]
Then why are u expecting vanced to work? 😂😂

**Comment by muddakinjaz** [comment]
> Then why are u expecting vanced to work? 😂😂

Regular YouTube doesn't have translate comments. Vanced does. It used to translate Korean. No need to be so dismissive. Just say you don't know.

**Comment by milindgoel15** [comment]
Vanced is built from stock YouTube app itself. We didn't made anything and translate feature comes from Google, not us.

You are having issues with it, complain to Google.

**Comment by muddakinjaz** [comment]
> Vanced is built from stock YouTube app itself. We didn't made anything on our own and translate feature comes from Google, not us.
> 
> Tl:Dr; Vanced = stock yt + ad blocker + bg playback + other enhancements
> 
> You are having issues with it, complain to Google.

My apologies. I was wrong. What you said seems to be true.

**Comment by muddakinjaz** [comment]
I tried the basic troubleshooting. Cleared app data and cache + cleared downloaded files. Uninstalled vanced and micro G. Rebooted phone. Reinstalled everything. Sill the same issue. Do I need to clear out Vance manager as well?

**Comment by muddakinjaz** [comment]
After searching on Google it seems many stock YouTube users have the same problem so it's not vanced. And there is no real solution. Sorry to wasted your time.
