### ISSUE TITLE
[Idea] adding proxy for using vpns in proxy mode

### ISSUE THREAD

**Issue by 08AGH80** [YTVanced/Vanced#1739]
Hi team vanced .

 I use vpn to bypass my country restrictions for youtube and it really is power consuming since it really is heavy to use vpn and video at the same time . 

My vpn has proxy mode .i can use it for apps like telegram and it use less power than whole device vpn .

Can i request to add proxy mode like socks 5 or https for youtube so i can redirect its connections to my vpn client app with less powe ?

Thanks for your hard work.

I think the reason youtube dosent add this to its app is because of location based ads. so when i block ads with YTV there shouldnt be a problem in adding proxy mod to YTV .

**Comment by milindgoel15** [comment]
Vanced ain't adding any VPN or proxy.
