### ISSUE TITLE
[Bug] Shorts can't be disabled

### ISSUE THREAD

**Issue by FahrulID** [YTVanced/Vanced#1742]
**Bug description:**
Can't disable Shorts

**Does your issue exists in the vanced guides? (YES/No)**
No

**Variant:**
Non root

**Vanced version:**
v17.03.38 build 01.55.00

**Link used to download vanced:**
From your vanced manager, latest

**Android version:**
Android 11 

**Device:**
Poco F1

**Steps to Reproduce:**
Steps to reproduce the error:
1. Vanced Settings
2. Ad settings
3. Disable shorts

**Expected behaviour:**
Shorts are disabled, duh.

**Screen recording/screenshot of the bug:**
![Screenshot_2022-03-11-10-15-15-818_com vanced android youtube](https://user-images.githubusercontent.com/49786305/157795555-259dc08c-d0e5-4f07-bc7b-f3e8228bf138.jpg)
![Screenshot_2022-03-11-10-15-08-985_com vanced android youtube](https://user-images.githubusercontent.com/49786305/157795561-b739abec-2846-4e4f-9b34-77828f58f666.jpg)

**Comment by milindgoel15** [comment]
Shorts shelf wasn't made to disable shorts tab. It disables the shelf layout of the shorts on the home tab.

And moreover, a feature to disable such things is planned for future releases and is tracked at #334.
