### ISSUE TITLE
[Bug] Some videos are only partially available

### ISSUE THREAD

**Issue by itsoriki** [YTVanced/Vanced#1743]
**Bug description:**
There are videos (didn't manage to find a clear pattern for the problematic ones) are PARTIALLY available with an inaccessible (i.e. I **can't watch** this part of the video) orange segment in the video's progress bar and a shorter video duration in parentheses next to the real one. 

**Does your issue exists in the vanced guides? _No_**

**Variant:**
Non Root

**Vanced version:**
v17.03.38

**Link used to download vanced:**
Vanced Manager 

**Android version:**
Android 11 

**Device:**
OnePlus 8 Pro

**Steps to Reproduce:**
Steps to reproduce the error (for an example video):
1. Open the app
2. Search for "Laa Lee - Tip Inna It (Official Video)"
3. Click on the first result
4. The first 51 seconds of the video should be unavailable for you to watch with an orange segment in the progress bar for this part of the video - clicking this segment should jump to the 51st sec of the video.

**Expected behaviour:**
I expected the video to be fully available for me to watch. Instead I only managed to watch a part of it.

**Screen recording/screenshot of the bug:**
![Screenshot_20220311-092353](https://user-images.githubusercontent.com/93577239/157823536-01436779-9121-47e1-96f3-aa56c934dbf8.jpg)

**Debug Info**
{"cplatform":"mobile","cbr":"com.vanced.android.youtube","c":"android","cplayer":"ANDROID_EXOPLAYER_V2","cmodel":"IN2023","cos":"Android","csdk":"30","cbrver":"17.03.38","cver":"17.03.38","cosver":"11.RP1A.201005.001.2202181007","cbrand":"OnePlus","videoid":"gqHMuFJkuKU","cpn":"GATIrwPhnA-KSuCp","fmt":"242 vp9 426x240@24","afmt":"251 opus","bh":32201,"conn":6,"volume":73,"loudness":"2.730","bat":"1.000:1","df":"0\/73","time":"2022-03-11T07:40:09.500Z","glmode":"RECTANGULAR_2D","mtext":"","error":"No errors","logged_in":"1","e":"24175488,24141413,24177636,24045475,23918597,24078649,23925789,24120820,24077241,24063124,39321511,24117491,23946420,23744176,23885490,24074379,24165080,24168963,24156600,24182223,24170336,24133739,24154616,24077266,24001373,24054345,24180801,24045478,24110902,24138064,24106839,24132305,39321475,24178748,24059624,24101621,24060091,24082169,24141499,24157779,23964928,24169726,24094144,24078457,24159749,24149832,24126999,23882502,24034168,24120829,24183411,24166867,24165226,24145515,24007246,24177193,24135310,24004644,24085811,24007790,23934970,23998056,24082661,24036947,24091230,24119845,24118644,39321565,24143331,24123943,24161848,24084052,24570081,1714252,23735347,24180221,24177977,24108147,23983296,24102339,24109689,24166201,24080738,24183971,23966208,24138442,24140247,24141462,24021124,24105745,24152443,23865461"}

**Comment by RealKasumi** [comment]
check sponsorblock settings

**Comment by milindgoel15** [comment]
That's called Sponsorblock segments and by default, the Sponsorblock integration will automatically skip such segments unless you choose not to.

It's better you read things when enabling any features before creating a bugreport on any repository. 

Head to Sponsorblock settings and change your config to either disable whole settings or individual segments as you would like to have.
