### ISSUE TITLE
[Idea] Remove Shorts

### ISSUE THREAD

**Issue by BbayuGt** [YTVanced/Vanced#1744]
**Description**
Add an option to redirect you to original player when opening YouTube Shorts Video. Youtube Shorts Suck.

**Comment by milindgoel15** [comment]
Duplicate of #334

**Comment by BbayuGt** [comment]
Im not requesting to remove the explore button tho, i just doesn't like it when you click a shorts video, the UI will fill your screen

Instead of https://youtube.com/shorts/roAJd7C64Q8?feature=share
Redirect it to original https://youtube.com/?v=roAJd7C64Q8

**Comment by milindgoel15** [comment]
Your title says remove shorts & ur description says convert to a regular page. 

Perhaps u should decide what exactly you want. And even if you want the other, that feature suggestion is tracked at #316
