### ISSUE TITLE
[Bug] Scrolling stuck bug

### ISSUE THREAD

**Issue by GKid94** [YTVanced/Vanced#1749]
**Bug description:**
I still have the scrolling stuck bug like other users even on the latest YouTube Vanced and regular YouTube, can the bug be fixed in Vanced? 

**Does your issue exists in the vanced guides? (YES/No)**
The only fix is to clear the cache but the bug happens later again

**Variant:**
Non-root

**Vanced version:**
17.03.38

**Link used to download vanced:**
https://vancedapp.com

**Android version:**
Android 11 

**Device:**
Redmi 9 4GB

**Steps to Reproduce:**
The problem only happens sometimes when you open a video and you can't scroll down on the video page and it get's stuck

**Expected behaviour:**
To scroll down the video page

**Comment by milindgoel15** [comment]
Ask google for stock bug fixes, not us
