### ISSUE TITLE
[Bug] App crashes after apparently random amount of time

### ISSUE THREAD

**Issue by reseune** [YTVanced/Vanced#175]
**Bug description**
I frequently use Vanced on a clean Android device to run one specific playlist while I cook dinner (thank god for CinemaSins!). At some point (I have yet to discern a pattern) the app will close out and return to the home screen. This happens whether or not a video is playing, and there doesn't seem to be a consistent time interval; sometimes it will go for literally days, other times it will close out in the first 30 seconds. I am willing to provide whatever information to help debug this. If it helps, I would happy send you the device for testing!

**Variant**
NonRoot: Yes
Root: No

**Vanced version**
15.43.32 - Build - 01.47.00

**Android version**
Android 5.1.1

**Device**
Nexus 7

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2. Wait. Behavior occurs regardless of user activity, whether videos are playing or not
3. App crashes

**Expected behavior**
App continues to play videos without crashing.

**Comment by prabanjanraja** [comment]
I also experienced this 
For me the app crashes after the current song if I turn off the screen it works fine when on background

**Comment by milindgoel15** [comment]
Please update to the latest v16.16.38 if you haven't already. We are closing this issue. Feel free to reopen if you still face any issues and provide logcats.
