### ISSUE TITLE
[Idea] Block youtube videos via tags

### ISSUE THREAD

**Issue by SquidsuneMiku** [YTVanced/Vanced#1750]
Add the ability to prevent videos with certain tags/keywords from being recommended to you.

**Comment by thepwrtank18** [comment]
Vanced got a cease and desist from Google, so you're probably not getting that any time soon.

**Comment by SquidsuneMiku** [comment]
> Vanced got a cease and desist from Google, so you're probably not getting that any time soon.

yeah i saw the announcement, i just hadn't gotten around to closing this yet.
