### ISSUE TITLE
[Bug] instalation failed

### ISSUE THREAD

**Issue by GiFRforever** [YTVanced/Vanced#1751]
**Bug description:**
Instalation of v17.03.38 fails with error: "There was an error parsing the package"

**Variant:**
non-root

**Vanced version:**
v17.03.38

**Link used to download vanced:**
Vanced Manager

**Android version:**
Android 5.1

**Device:**
Huawei Y6 II 

**Steps to Reproduce:**
Steps to reproduce the error:
1. Open the app
2. Click on 'Vanced'
3. Click on 'Install'
4. Wait for downloads to complete

**Expected behaviour:**
Instead of install promt I get an error "There was an error parsing the package"

Couldn't attatch log due to frozen VManager

**Comment by RealKasumi** [comment]
Vanced no longer works on Android 5 or below. Either use another custom YT client (NewPipe) or buy a better phone.

**Comment by milindgoel15** [comment]
Or use old versions. The oldest supported version is v16.xx.xx
