### ISSUE TITLE
[Idea] Use NewPipe instead of original youtube app

### ISSUE THREAD

**Issue by Tarek-Hasan** [YTVanced/Vanced#1754]
**Description**
Use NewPipe which is opensource thus immune to copyright. Fork it and add YouTube ID login to it and other vanced features to it like SponsorBlock, return YouTube dislike etc.

NewPipe:
https://github.com/TeamNewPipe/NewPipe
NewPipe with SponsorBlock:
https://github.com/polymorphicshade/NewPipe/

**Comment by NatsuDragneelHM** [comment]
YouTube still may take legal action for ad blocking, but we will see ultimately

**Comment by milindgoel15** [comment]
Nope, not gonna happen.
