### ISSUE TITLE
[Question] YouTube Vanced Revival?

### ISSUE THREAD

**Issue by yuckdevchan** [YTVanced/Vanced#1755]
I was wondering, if YouTube Vanced was open-sourced (I know that's kind of a big ask) and you then created a way to compile just the modifications to a vanilla YouTube apk so that all you would be distributing would be the modifications and not Google's Code.

I know this is kind of unrealistic but I was wondering it would be possible and am generally just interested.

**Comment by RealKasumi** [comment]
vanced isn't open source, nor do they have the source code
never has been open source, never will be

**Comment by NotHuza** [comment]
Noice

**Comment by LifeIsStrange** [comment]
@RealKasumi What does it means that Vanced does not have the source code? It's meaningless. Even if you defer to an external entity this entity or you could open source the code, not under the Vanced umbrella (for legal reasons) but as anonymous leak. The world needs Vanced.

**Comment by TacoTheDank** [comment]
@LifeIsStrange Vanced is a modification of the stock YouTube app. This means that it modifies code that is owned by Google and is protected under copyright. Thus, it's literally impossible to be open-sourced.

**Comment by LifeIsStrange** [comment]
@TacoTheDank thanks for the answer!
So 1) where is the repository of the diffs?
2) how did you get access to the code in order to apply the diff? For the community to revive the project we need you to explain the build step/diff merging
I would have thought that Vanced was binary/APK patching the YouTube APK but according to you, you are patching the source code instead. If so, how did you get access to the YouTube source code in the first place?

**Comment by Systemad** [comment]
> @TacoTheDank thanks for the answer! So 1) where is the repository of the diffs? 2) how did you get access to the code in order to apply the diff? For the community to revive the project we need you to explain the build step/diff merging I would have thought that Vanced was binary/APK patching the YouTube APK but according to you, you are patching the source code instead. If so, how did you get access to the YouTube source code in the first place?

In this case, I believe the actual modifications are written in Java, then transfer the compiled dex files of your code and a decompiled app, then depending on how you do it, it can involve lots of smali patching.

**Comment by LifeIsStrange** [comment]
Decompiling/reverse engineering for private use is absolutely LEGAL. What can be illegal in some countries (probably legal in europe) is to redistribute the decompiled code publicly.

The solution for Vanced is simple:
Do NOT opensource the Youtube decompiled code however, write a blog/markdown file explaining how to use a decompiler for an APK (here YT) and how to do a merging of diffs (here the ones that needs to be opensourced) and if necessry opensource the corresponding line numbers of the opensource diff that match the output of the decompiled code at the time of writing.
Hence you can completely avoid opensourcing youtube decompiled APK by instead explaining us the steps in natural languages and opensourcing as explained, a table that maps line numbers to your diff code.
This is absolutely legal.

**Comment by yuckdevchan** [comment]
I know YouTube is not open-source. I know YouTube Vanced is not open-source. I may have not worded it well but what I was trying to say is that it would definitely be possible to engineer a way to patch a standard YouTube APK if the Vanced developers allowed this. For example, if my idea actually materialised, you could maybe download an app that you drop the YouTube APK into and it modifies it with the Vanced improvements that do not infringe on Google's code.

**Comment by TacoTheDank** [comment]
Btw here's the diffs (they were deleted, but they're still accessible through the git versioning).

https://github.com/YTVanced/Vanced/tree/4da2e24bea942c8ef754715b9acc260362f1e0a0/v17.03.38

**Comment by LifeIsStrange** [comment]
@TacoTheDank Thanks!
@KevinX8 Hi, friendly ping :)
Could you please explain to us how to apply the diffs? I don't know what tool generate .bsdiff files

**Comment by milindgoel15** [comment]
We cannot share any information in such matters. You are on your own.

**Comment by Systemad** [comment]
> @TacoTheDank Thanks! @KevinX8 Hi, friendly ping :) Could you please explain to us how to apply the diffs? I don't know what tool generate .bsdiff files

bsdiff is for generating patches, bspatch is for applying.
Although, if I'm not mistaken, it is not much of use because I don't think we have all the files that are needed.

JADX to reverse engineer the apk is your best bet if you want to make your own modded app.

**Comment by KevinX8** [comment]
You apply the patch to the respective stock YouTube apk file of the same split type, apart from base which I left exact instructions for

**Comment by AkechiShiro** [comment]
Just giving my two cents here but what if Vanced's source code got leaked by a mysterious hacking attack what would happen, would there be any legal issues with that ?

**Comment by X1nto** [comment]
> Just giving my two cents here but what if Vanced's source code got leaked by a mysterious hacking attack what would happen, would there be any legal issues with that ?
> 
> Maybe we can get the anonymous group on this matter...

No, thanks. 


To sum things up: revival is not happening, the discussion is pointless.
