### ISSUE TITLE
[Idea] Add playing video id to media session change event and logcat

### ISSUE THREAD

**Issue by Bluscream** [YTVanced/Vanced#1756]
**Description**
```
03-16 02:32:33.173 20749 20749 E YT.mlplayer: MedialibPlayer.loadVideo(cpn=jMFRD_Pu3kA5rr5G playWhenReady=true positionMs=0 playerEvents=[77] videoId=scrubbed mediaView=194941493(0,0,1344,756) volume=1.0)
```
Youtube assholes are redacting the video id to harass me

_Attach images/videos if possible. Also add any links to possible other applications with the said feature already implemented._

**Comment by milindgoel15** [comment]
Ask Google for it. Vanced can't help you with it

**Comment by Bluscream** [comment]
Of course vanced can patch that method and revert the scrubbing. Or just log the videoId on its own when media changes
