### ISSUE TITLE
Un problème est survenu au niveau du serveur [400]

### ISSUE THREAD

**Issue by POULPE65** [YTVanced/Vanced#1761]
Hi ! 
sorry for disturbing you.  I don't understand how github works.  I want to ask a question but I can't.  sorry I'm french and my english sucks.
i have youtube pink.  a friend installed it for me.  However, I have already had this message twice.
"a problem has occurred with the server [400]"
I deleted the caches and donnés and I was never able to reconnect my account.  So I created another one but the problem came back.  I do not know what to do.

**Comment by milindgoel15** [comment]
Not our problem anymore. But v14 versions have been deprecated by Google. Update to newer YouTube from play store.

**Comment by POULPE65** [comment]
Du coup je dois télécharger une version plus récente de YouTube vanced ?
