### ISSUE TITLE
[Bug] an ad while scrolling through youtube shorts

### ISSUE THREAD

**Issue by TeleportingPheonix** [YTVanced/Vanced#1762]
**Bug description:**
While I was scrolling through the youtube SHORTS on youtube vanced, I saw 3 ads which shouldnt be there because of youtube vanced's adblock

**Does your issue exists in the vanced guides? (YES/No)**
No

**Variant:**
 root

**Vanced version:**
Latest

**Link used to download vanced:**
Vancedapp.com

**Android version:**
Idk

**Device:**
Samsung Galaxy S8+

**Steps to Reproduce:**
Steps to reproduce the error:
1. Open the app
2. Click on 'youtube SHORTS '
3.  Scroll down

**Expected behaviour:**
I expected a clean, ad-free scroll in youtube SHORTS but nope

**Screen recording/screenshot of the bug:**
Replace here with the screenshot of the bug or provide screen recording for proper debugging.

_Attach logcats in case of crashes by uploading them to pastebin or katbin if possible. These can help solve the issue._
![Screenshot_20220319-081411](https://user-images.githubusercontent.com/101922623/159113409-9f65a62f-9161-4c9c-8b8e-b32f02228fbf.jpg)
![Screenshot_20220319-081419_One UI Home](https://user-images.githubusercontent.com/101922623/159113411-ef078087-4d1b-4316-b0df-0bcc0e6da2a1.jpg)

**Comment by milindgoel15** [comment]
Vanced has been discontinued. There will no more future updates

**Comment by TeleportingPheonix** [comment]
I didnt know the difference between vanced and youtube vanced
