### ISSUE TITLE
[Bug] replaceme 

### ISSUE THREAD

**Issue by Higor86** [YTVanced/Vanced#177]
**Bug description**
Replace me with a clear and detailed description of the bug.

**Variant**
NonRoot: Yes
Root: No
YouTube music

 no start download
**Vanced version**
15.43.32 - Build - 01.47.00

**Android version**
Android 9.0 - Pie

**Device**
LG K50S

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
3. ....

**Expected behavior**
Replace me with a description of what you expected should happen and what happened instead.

_Attach images/videos if possible. These can be helpful in solving the issue._

**Comment by gghhkm** [comment]
We don't accept Vanced Music issues, and downloading Music/Videos will never be apart of any Vanced apps for legal reasons.
