### ISSUE TITLE
I can't install Music. Can you help me please.

### ISSUE THREAD

**Issue by ACH030** [YTVanced/Vanced#179]
![Screenshot_20201110-225804_Vanced Manager](https://user-images.githubusercontent.com/74258200/98700724-16925280-23ab-11eb-9422-878aecf9b247.jpg)
**Bug description**
Replace me with a clear and detailed description of the bug.

**Variant**
NonRoot: Yes
Root: No

**Vanced version**
15.43.32 - Build - 01.47.00

**Android version**
Android 9.0 - Pie

**Device**
Samsung Galaxy S8

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
3. ....

**Expected behavior**
Replace me with a description of what you expected should happen and what happened instead.

_Attach images/videos if possible. These can be helpful in solving the issue._

**Comment by davwheat** [comment]
Any reason why you closed this? I'm having the same issue.
