### ISSUE TITLE
Audio Skips (Blanks Out)

### ISSUE THREAD

**Issue by animule** [YTVanced/Vanced#18]
I installed the latest Vanced app on an Android TV device (H96 Max using Rock Chip 3299 chip, Android 7.1), and I am experiencing audio skipping (audio drops?) every few seconds, but not on a regular interval. 

It occurs on various video and at different audio volumes in the video.

Has anyone else encountered this?

**Comment by incIined** [comment]
vanced doesn't work on Android TV, use SmartYouTubeTV instead
