### ISSUE TITLE
[Idea] Disable HD 60fps variant on videos / Force 1080p 30fps

### ISSUE THREAD

**Issue by e596643** [YTVanced/Vanced#180]
**Description**
I use vanced on a android tv box and HD 60fps videos can be played but they lag and buffer a lot, the box is connected to Ethernet.
A option to force the 1080p 30fps variant would be appreciated, since they play fine on the tv box.

**Comment by X1nto** [comment]
Go to vanced settings > tap "about" 5 times > to to codec override > override manufacturer to Samsung and override model to sm-t520 > restart vanced

**Comment by e596643** [comment]
Thank you very much, is that the only device that makes a difference on the codecs? or there is like a list of devices that i can try?
