### ISSUE TITLE
[Idea] remove feature that automatically translates titles

### ISSUE THREAD

**Issue by axelbostrom** [YTVanced/Vanced#182]
Please consider removing the feature that translates videotitles to the same language as the phone has (very annoying). Or add a feature to disable this. 

I couldn't recreate it for a photo, because it is so random. Sometimes it happens a few times a day, sometimes not in months.

Will upload photo if I manage to get one. Changing language of the Phone is the only fix right now, changing location does not work.

**Comment by axelbostrom** [comment]
Photo, the title of the marked area is translated from english to my phones language (swedish).
![Screenshot_20201111-230351](https://user-images.githubusercontent.com/56017794/98869636-6556ef80-2472-11eb-8e73-5508ec323de6.jpg)

**Comment by swaree** [comment]
now it seems that YouTube is automatically translating titles even if the author didn't provide any translation (see the Google Translate logo next to the video title)
![IMG_20210404_130645](https://user-images.githubusercontent.com/13753165/113506749-f8d6ad00-9546-11eb-8355-5bc183eefb5e.jpg)

**Comment by axelbostrom** [comment]
It's a very annoying feature from Youtube. Really wish that it was a option. If YT vanced had this as an option the app would be almost perfect.
