### ISSUE TITLE
[Idea] - Improved SponsorBlock 

### ISSUE THREAD

**Issue by nicol1212** [YTVanced/Vanced#183]
1. Would be cool to see a pop-up that's showing how many people that used the skip on the specific segment. 

2. Be able to report bad skips.

3. A timer or a "Time stamp" that shows how long the skip is

There is a site that you can take the information from to make this possible "https://sb.ltn.fi/"

**Comment by gghhkm** [comment]
Everything SponsorBlock go to
https://github.com/YTVanced/SponsorBlock sir. Thank you.
