### ISSUE TITLE
[Idea] Focus Features - removing recommendations

### ISSUE THREAD

**Issue by reagag** [YTVanced/Vanced#184]
Hello,
I was wondering if you guys could implement a couple options that would discourage distractions:
1) an option to disable the recommendations feed that appears under videos.
2) disable the "home" and "explore" tabs, leaving only "subscriptions" and "library" available

If this was an option, I think that it would be a very helpful feature for those who want to minimize their distractions by falling into a rabbithole of recommended or suggested videos. I sometimes open the app for a specific video (a tutorial or recipe, etc.) and can find myself getting sidetracked.

Thanks for all the work you guys continue to do!

**Comment by Ali-Nazlier** [comment]
I would appreciate if there was a toggle to remove the "explore tab".

**Comment by ndm13** [comment]
Simply adding an option to default to Subscriptions would be amazing. I have the Subscriptions activity on my launcher, but any time I reload the app I get bumped back to home.

**Comment by ashudva** [comment]
that's exactly what I'm looking for, it'd save many of us a lot of time that we could use for productivity instead of falling prey to clickbaits.

**Comment by NickKaramoff** [comment]
Agreed: I would love to just have the option for the default startup page to be "Subscriptions"

**Comment by spicyfoxx** [comment]
> Agreed: I would love to just have the option for the default startup page to be "Subscriptions"

But you can already do that? Just hold on the app icon and create a shortcut of it.
![20210104_203746](https://user-images.githubusercontent.com/24849056/103540820-ebb90c00-4ecc-11eb-9323-f27743af6b16.png)

**Comment by NickKaramoff** [comment]
> > Agreed: I would love to just have the option for the default startup page to be "Subscriptions"
> 
> But you can already do that? Just hold on the app icon and create a shortcut of it.

This is not acceptable because I can only create shortcuts on my desktop and I don't want the YouTube link on my Desktop; I want it in the Applications Menu only.

Also, as mentioned above, any time the app is reloaded (e.g., due to low memory) or a video is opened from a link, the main screen of the app is still "Home"

**Comment by eldon97** [comment]
remove home page, remove video recommendation below video comment, and be able to set default tab would be the best thing in my life to prevent me from procrastinating lol you will be our savior, dev if you implement this..

**Comment by spicyfoxx** [comment]
> remove home page, remove video recommendation below video comment, and be able to set default tab would be the best thing in my life to prevent me from procrastinating lol you will be our savior, dev if you implement this..

Newpipe is what you need. 😸

>
