### ISSUE TITLE
[Bug] Watch History not working

### ISSUE THREAD

**Issue by ApexDevelopment** [YTVanced/Vanced#185]
**Bug description**
Watching a video does not add it to the watch history. My watch history is not paused. Watching videos on other devices does add the video to my history. I have tried removing the microG accounts and adding them again through Vanced, and I have tried uninstalling and reinstalling Vanced+microG. The issue persists.

**Variant**
NonRoot: Yes
Root: No

**Vanced version**
15.43.32 - Build - 01.47.00

**Android version**
Android 9.0 - Pie

**Device**
Samsung Galaxy S9

**Steps to Reproduce**
1. Open the app
2. Click on a video
3. Watch for any amount of time, or all the way through
4. Navigate to Library
5. Observe under "Recent" that no new video has been added

**Expected behavior**
The recently viewed video should be added to the watch history under "Recent."

**Comment by bmnascimento** [comment]
I'm having the same problem, also using the NonRoot version, but on Android 10 on a Redmi 5 Plus

**Comment by X1nto** [comment]
Are you guys using any adblock? If yes, just whitelist `*s.youtube.com`

**Comment by ApexDevelopment** [comment]
> Are you guys using any adblock? If yes, just whitelist `*s.youtube.com`

My fault for not mentioning this in the bug report. No, I'm not using any adblock.

**Comment by bmnascimento** [comment]
> Are you guys using any adblock? If yes, just whitelist `*s.youtube.com`

I am using AdAway and that worked, thanks!

**Comment by ApexDevelopment** [comment]
This seems to have resolved itself. I have no idea how.

**Comment by Baria1996** [comment]
> Are you guys using any adblock? If yes, just whitelist `*s.youtube.com`

I've been having this issue for so long and i had no idea this was the problem. Was using AdAway and this worked perfectly.

**Comment by chethan749** [comment]
> 
> 
> Are you guys using any adblock? If yes, just whitelist `*s.youtube.com`

I'm using pihole and this did the trick. Thanks a lot!!

**Comment by Sandman224** [comment]
> > Are you guys using any adblock? If yes, just whitelist `*s.youtube.com`
> 
> I'm using pihole and this did the trick. Thanks a lot!!

How did you whitelist it? Did you remove the asterisk cause I couldn't get it to whitelist without removing the asterisk.

**Comment by mh166** [comment]
Thank you, @chethan749! This solved the problem for me as well! 🥳 

@Sandman224: You have to add it as a "regular expression", not as a domain. Then you'll be able to keep it as is and it will work flawlessly. 😃 
<img src="https://user-images.githubusercontent.com/3167596/147830442-53f47b53-8cae-40cb-8074-066774a29e5d.jpg" width="350">
