### ISSUE TITLE
[Idea] Make a toggle to enable legacy icons!

### ISSUE THREAD

**Issue by Defarius** [YTVanced/Vanced#187]
**Description**
I would like a toggle to change the new, wireframe style icons with the ones that are currently on pc. Me and many other people fine the old icons significantly more appealing.

Current icons:
![Screenshot_20201111-180657](https://user-images.githubusercontent.com/74347554/98912871-853ee100-247b-11eb-9cb7-7d3e9b635486.png)
![Screenshot_20201111-19244](https://user-images.githubusercontent.com/74347554/98912872-85d77780-247b-11eb-9359-80f17c162ccc.png)
![Screenshot_20201111-192449](https://user-images.githubusercontent.com/74347554/98912875-86700e00-247b-11eb-8628-4f5da41dfda7.png)

Legacy icons:
![Screenshot_20201112-000825_YouTubee](https://user-images.githubusercontent.com/74347554/98912936-9a1b7480-247b-11eb-8fcc-0e31b1d01764.png)
![Screenshot_20201112-000825_YouTube](https://user-images.githubusercontent.com/74347554/98912939-9ab40b00-247b-11eb-8f9e-469f8e64753d.png)
![Screenshot_20201111-162429](https://user-images.githubusercontent.com/74347554/98912940-9b4ca180-247b-11eb-9879-9135a3d9ce7e.png)

**Comment by VityaSchel** [comment]
Yes, this should be added

**Comment by FrozenPhoton** [comment]
Agreed!

**Comment by Michael82548** [comment]
It should be added

**Comment by Michael82548** [comment]
Issues auto close? Wow...

**Comment by Michael82548** [comment]
First time I ever seen something like that on GitHub. Really makes me lose hope in this project's community :(

**Comment by Michael82548** [comment]
So to keep an issue open, you would have to bump issues like this every day once it gets "marked as stale" from the bot.
