### ISSUE TITLE
[Bug] I can't download Music from the vance manager..

### ISSUE THREAD

**Issue by NROLP** [YTVanced/Vanced#188]
**Bug description**
I can't download Music from the vance manager. Thank you for your response.

**Variant**
NonRoot: Yes
Root: No

**Vanced Manager version**
1.3.1 (Arcturus)

**Android version**
Android 10

**Device**
Samsung A11

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2. Click on 'Install for music'
3. The app says 'Error Downloading Music'

![Screenshot_20201112-161554_Vanced Manager](https://user-images.githubusercontent.com/74348285/98914302-7865d000-2503-11eb-8082-e2b0fa22957e.jpg)

**Comment by X1nto** [comment]
Duplicate issue

**Comment by NROLP** [comment]
What is the best solution for this?

**Comment by X1nto** [comment]
Use https://vancedapp.com/api/v1/music/v4.02.51/nonroot.apkuntil we resolve issue with manager

**Comment by NROLP** [comment]
Thanks mah dood!
