### ISSUE TITLE
Error Downloading YT Music Update and Official page down

### ISSUE THREAD

**Issue by danibalcr** [YTVanced/Vanced#189]
**Bug description**
I wanted to download the YT Music Update 4.02.51 from Vanced Manager, this Produces an error when Downloading and your Official page is Down.

**Variant**
NonRoot: Yes
Root: No

**Vanced Manager Versión**
1.3.1

**Android version**
Android 8.1 - Oreo

**Device**
Huawei Nexus 6P

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2. Click on To update 
3. Load a moment 
4. Download Error

**Expected behavior**
You should Download the New Update and Replace the Old Version with the New, Instead I throw an Error.

_Attach images/videos if possible. These can be helpful in solving the issue._
![Screenshot_20201112-092117](https://user-images.githubusercontent.com/52415902/98945154-80544e80-24c8-11eb-8299-ef18c478eada.png)

**Comment by gghhkm** [comment]
Know problem

https://vancedapp.com/api/v1/music/v4.02.51/nonroot.apk
