### ISSUE TITLE
Live videos when in PIP mode are cropped. 

### ISSUE THREAD

**Issue by stephen147** [YTVanced/Vanced#190]
This doesn't happen all the time but sometimes this is the case. Sorry, I don't know how to replicate this bug.

I'm on Android 9 using colour os on an oppo reno 5g.

**Comment by gkp1** [comment]
Picture-in-Picture not working
The way PiP works is controlled by your operating system. If it's broken, there's nothing we can do, so please don't report PiP related issues.
Page 9/9•08/11/2020
