### ISSUE TITLE
[Bug] pinch to zoom does not work

### ISSUE THREAD

**Issue by SkaarlIsMyWaifu** [YTVanced/Vanced#192]
The newer phones has a long display which makes it have blackbars when watching in a normal resolution. So you can pinch to get rid of blackbars from the side while in fullscreen but sometimes this doesnt work and you have to close the app in multitask to fix it but will come back eventually.

Variant
NonRoot: Yes
Root: No 

Vanced Manager Versión
1.3.1 

Android version
Android 10 

Device
Samsung Galaxy S20 FE 

Steps to Reproduce
Steps to reproduce the error: 

Watch a video 

Pinch to zoom while in fullscreen 

Either it will work as intended or just be the same size and it will say that you are in the pinching mode 

Expected behavior
I expect it to zoom so the side blackbars wont be visable

**Comment by gghhkm** [comment]
Stock bug.
You have to wait for a build on 15.45.
