### ISSUE TITLE
[Bug] replaceme

### ISSUE THREAD

**Issue by 9ilyas** [YTVanced/Vanced#193]
**Bug description** Replace me with a clear and detailed description of the bug.
 **Variant** 
NonRoot: No 
Root: Yes 

**Vanced version** 15.43.32 - Build - 01.47.00 

**Android version** Android 8.0 

**Device** SM-A730F 

**Steps to Reproduce** Steps to reproduce the error: 1. Open the app 2. Click on '....' 3. .... 

**Expected behavior** 

[logcat.txt](https://github.com/YTVanced/Vanced/files/5535975/logcat.txt)
I was watching a video, clicked on the YouTubers profile and it crashed. Tried it again and it crashed again. The app crashes a lot for me.

**Comment by X1nto** [comment]
There are no crashes logged in the logcat you provided

**Comment by gghhkm** [comment]
You must provide a valid LogCat or at the very least fill out the forum more.
