### ISSUE TITLE
[Bug] [ROOT] Vanced crashes on second (and every consecutive) attempt to launch

### ISSUE THREAD

**Issue by TRI99ERED** [YTVanced/Vanced#195]
**Bug description**
Vanced crashes on second (and every consecutive) attempt to launch. Whenever I install the app, it launches and works alright, I can watch videos, change theme and settings etc. But even if I just close it immidiately and try to reopen, on every consecutive attempt the app will just crash immidiately after loading screen (logo) is shown. It appears, that wiping out app Data for Vanced solves this issue untill the next reopen attempt (at that point it starts to crash).

**Variant**
NonRoot: No
Root: Yes

**Vanced version**
15.43.32 - Build - 01.47.00

**Android version**
Android 5.0.2 - Lollipop

**Device**
LG Max X155

**Steps to Reproduce**
Steps to reproduce the error:
1. Install app;
**A**:
2. Open the app (it works fine);
3. Close the app (doesn't matter if immidiately or after watching video);
4. Try to launch app again;

Alternative:
1. Wipe app Data;
All steps from **A** proceed.

**Expected behavior**
After any reopen attempt app crashes showing an ANR screen after logo. UI is not even loaded. If in ANR I choose to wait it shows the same ANR after few seconds. App UI is still not loaded (and it never loads).
The only way to reopen app is to wipe it's data every time before reopening.

**Comment by milindgoel15** [comment]
Please update to the latest v16.16.38 if you haven't already. We are closing this issue. Feel free to reopen if you still face any issues.
