### ISSUE TITLE
[Bug] The button below cannot be pressed while in the pop up window

### ISSUE THREAD

**Issue by Riciuu** [YTVanced/Vanced#196]
**Bug description**
buttons to move to homepage, exploration, subscribe and collections cannot be pressed while in floating window mode

**Variant**
NonRoot: Yes
Root: No

**Vanced version**
15.43.32 - Build - 01.47.00

**Android version**
Android 10 Q

**Device**
Xiaomi redmi note 8 pro

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2. Click floating window on control center
3. then press the button below such as exploration, collection or others.

**Expected behavior**
the button can be pressed like it is not in floating window mode.

_Attach images/videos if possible. These can be helpful in solving the issue._
#
![Screenshot_2020-11-14-01-42-20-411_com miui videoplayer](https://user-images.githubusercontent.com/74426580/99109033-c91c1c80-261a-11eb-827e-98d3a0c8f520.jpg)
![Screenshot_2020-11-14-01-42-09-297_com miui videoplayer](https://user-images.githubusercontent.com/74426580/99109068-d507de80-261a-11eb-8453-1a01ec16e774.jpg)

**Comment by milindgoel15** [comment]
it is not a bug. While in recent, you cannot use any app because it's not in active use because that's how recent screen work
