### ISSUE TITLE
[Solved] [Bug] [no-root] after updating to v2.0, manager crashes at launch

### ISSUE THREAD

**Issue by LOUDER97** [YTVanced/Vanced#198]
**Bug description** 
I just got a notification for the 2.0 version (nov.13 ~ 3PM EST.)
I wanted to install it because with the [1.3.something] version of vanced manager i couldn't download vanced music anymore

**Variant**
NonRoot: Yes
Root: No

**Vanced version**
v2.0.0 i dont know which build, or how to check it

**Android version**
Android 6 marshmallow

**Device**
LG G4 H818

**Steps to Reproduce**
Steps to reproduce the error: 
1. Open the app and imediately crashes

i tried reinstalling it, and it has the same behaviour 
only older versions work

https://hastebin.com/rujaxidina.yaml 
im not very much of a techie, i don't really know which info is considered private on that log, so i just pasted it whole
also, i'm not sure if it can be reproduced on other phones since nobody else complained about it, i just assumed is my old phone's fault

*edit: 2.0.1 works perfectly

**Comment by RaceRalph** [comment]
I experience the same.
Vanced Manager updated itself to 2.0.0 and now crashes immediately after launch.
Android 6.0.1 non-root
Sony SGP621 (Xperia Compact Tablet Z3)
