### ISSUE TITLE
[Bug] google play services error

### ISSUE THREAD

**Issue by gustasmor** [YTVanced/Vanced#201]
So when I install youtube vanced, and open it it shows this message: YouTube won't run without Google Play services, which are not supported by your device.

**Variant**
Root

**Vanced version**
15.43.32 - Build - 01.47.00

**Android version**
Android 11-R (Octavi-os 1.2, gapps build)

**Device**
Redmi note 8

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app

**Expected behavior**
I expect it not to show me the message and work as normal

I've tried to upload the photo, but it shows an error, I can send it if you want me to send the photo

**Comment by ullortnaci** [comment]
Same happens on Mi 9, Android 11 Fluid ROM, gapps already included.

**Comment by BearTS** [comment]
Same is happening with me on Zenfone Max Pro m1, Android 11, gapps included

**Comment by imprezzion** [comment]
Same here. Oneplus 8 Pro with LineageOS 18 Android 11 with GMS installed. Non root works with microG.

**Comment by puuuuh** [comment]
Same here. Its because https://developer.android.com/about/versions/11/privacy/package-visibility, com.android.vending is not visible by default, need to add it to app manifest

**Comment by ralphocdol** [comment]
Same here, Asus Zenfone Max Pro M2 AOSP Extended v8 Unoffical with MicroG

**Comment by shubell** [comment]
Same on LOS 18.1 with root version. Non root works.

**Comment by panyuhang93** [comment]
Same on LOS 18.1 ,opengapps with root version

**Comment by panyuhang93** [comment]
first install og youtube 15.43.32 by lucky patcher ,then use magisk module
og youtube
https://drive.google.com/file/d/11FLaMnrmYvZZ9ZIolIYvrgOigLHwFSyl/view?usp=sharing
magisk module
https://forum.xda-developers.com/t/app-mod-root-nonroot-youtube-vanced-edition.3758757/page-870#post-83855303

**Comment by shubell** [comment]
the point is not having og

**Comment by gustasmor** [comment]
15.33.34 and older from vanced manager works for me just fine.

**Comment by shubell** [comment]
> 15.33.34 and older from vanced manager works for me just fine.

which version android do you have?

**Comment by gustasmor** [comment]
> > 15.33.34 and older from vanced manager works for me just fine.
> 
> which version android do you have?

Android 11, build number RD1A.201105.003.C1, octavi os 1.3 ginkgo (gapps)

**Comment by Shished** [comment]
> 15.33.34 and older from vanced manager works for me just fine.

Can confirm that this version is working, I', using LOS 18.1 on Poco F2 Pro.

**Comment by panyuhang93** [comment]
i think it's a rom bug,i use pixel 2 ,the youtube vanced on stock 11 rom work well for me ,but when i switch the rom to lineage 18.1 ,it happen ,and the bug is same for    stock youtube just install without play store,use lucky patcher install like install by play store (pm -i com.android.vending)

**Comment by Shished** [comment]
It also works correctly on OP8T with stock ROM (11 based). I think that's custom Gapps problem, i'm using openGapps test package.

**Comment by panyuhang93** [comment]
same here ,gapps testpackage, i think you're right

**Comment by brackhap** [comment]
Same problem here:

**Variant**
Root

**Vanced version**
15.43.32 

**Android version**
Crdroid 7.0 - Android 11- RP1A.201105.002 + Nikgapps core

**Device**
Redmi note 5 AI/Pro

No other app reports issues with Play service but vanced youtube. And it's working fine with vanced 14.

**Comment by dragonBall561** [comment]
> 15.33.34 and older from vanced manager works for me just fine.

Uhh which old version?

**Comment by brackhap** [comment]
> > 15.33.34 and older from vanced manager works for me just fine.
> 
> Uhh which old version?

It was the 14

**Comment by dragonBall561** [comment]
15.33.34 works on newest manager but play store keeps auto updating.

**Comment by gustasmor** [comment]
> 15.33.34 works on newest manager but play store keeps auto updating.
> 

You can turn off auto updates, go to youtube in play store, press on 3 dots on the top right and press auto uodate, if its already unmarked, mark it and unmark it again, should work.

**Comment by gghhkm** [comment]
>> 15.33.34 works on newest manager but play store keeps auto updating.
>
> You can turn off auto updates, go to youtube in play store, press on 3 dots on the top right and press auto uodate, if its already unmarked, mark it and unmark it again, should work.

They can also use the "Detach" magisk module if simply turning off auto updates within the Google Play store isn't enough.

**Comment by gghhkm** [comment]
https://github.com/YTVanced/VancedManager/issues/501#issuecomment-824800438

**Comment by jedenastka** [comment]
Why is this closed? The issue persists, downgrading is not a fix.

**Comment by milindgoel15** [comment]
> Why is this closed? The issue persists, downgrading is not a fix, only a workaround.

Because it's not vanced issue. Kindly use a better ROM or better gapps. We suggest using nikgapps if you are using a ROM without prebuilt gapps. Pls search your issues first before laying it out on vanced.

**Comment by PhoenixxClaw** [comment]
> > Why is this closed? The issue persists, downgrading is not a fix, only a workaround.
> 
> Because it's not vanced issue. Kindly use a better ROM or better gapps. We suggest using nikgapps if you are using a ROM without prebuilt gapps. Pls search your issues first before laying it out on vanced.

'kindly use a better ROM'


I'm using default android 11 on my galaxy s20 FE and the non rooted version of vanced and have the exact same problem.
How can it be a problem with the ROM if even default android isn't working?

**Comment by Shished** [comment]
Are you sure you installed everything correctly? Non root version can't have this problem because it doe not interacts with gapps, uses microg instead.

**Comment by milindgoel15** [comment]
Non root version don't even use the Google play services to connect to Google servers. It redirects through microG. The problem you might really be facing is of Chromecast when casting. That issue is related to microG and it's already known. Please consider reading this particular issue #688
> I'm using default android 11 on my galaxy s20 FE and the non rooted version of vanced and have the exact same problem.

When reporting any issue, please include your error screenshot. Please don't same every error to be same. 1 Google play services error doesn't really mean all other Google play services will the same as 1.
> How can it be a problem with the ROM if even default android isn't working?

**Comment by PhoenixxClaw** [comment]
Oh alright.
Then I'm very sorry for wasting your time and thankful for the link to issue #688!

**Comment by milindgoel15** [comment]
I am writing this particular message for all users out here who may face Google Play services error on root version on vanced when using custom ROMs based on android 11. The issue related to "YouTube can't run without Google play services" on root version on android 11, was fixed in the month of January. A fix was made in vanced manager itself for adding play store query while installation. And the same fix had to made by Gapps developers too. 

Hence, if you are using a ROM without prebuilt Gapps and facing such issue, please update your Gapps or switch to others(we suggest using nikgapps). If you are using microG, consider migrating to Gapps (atleast pico) or try to fix your microG installation. You can join our discord server or telegram for support on such purposes or microG support team for help.

For future purposes, please do refer to changelogs as they are pretty much handy to read for any type of issue.

**Comment by pmatusik93** [comment]
Hi,

after ~2 months I have once again this error in version 16.20.35 + 0.2.21.212417 in microG

**Comment by DrSaad77** [comment]
It is 2 days already I am facing this same issue.
Error: "YouTube can't run without Google play services".
I even restore all the phone, thinking something was wrong with the Rom itself...
Rom: BlackDiamond v.10 & latest Vanced version. With previous Vanced version, same issue.
Can please some advice a solution.
Thx

**Comment by milindgoel15** [comment]
Get nikgapps if your ROM does not have any google services.

**Comment by DrSaad77** [comment]
> Get nikgapps if your ROM does not have any google services.

Thx very much.
It is weird I have to install gapps, I mean back on Lineage I was installing gapps... But now Vanced was working fine. More GooglePlay is ok.
And strict Basic  nikgapps is anough?? 
I mean not looking for additional apps, just what necessary for google stuffs to work.

**Comment by milindgoel15** [comment]
Yea it's fine

**Comment by DrSaad77** [comment]
I tried it, Core nikGapps are the phone started getting crazy. Every 5sec, some google services are not responding or closing themself, and the whole system is freezing.
After some testing, I realised that Vanced is fine, and as soon I enable back EdXposed, again Google Service error happen with Youtube Vanced, and even with Original YouTube from PlayStore.
So guilty is EdXposed I guess.
Another point, is with v.15.33.34, Vanced is working fine even with EdXposed enabled.

**Comment by DrSaad77** [comment]
I finally found out guilty. I use SudoHide to hide youTube from PlayStore, cause of auto-update shit.
I tried a year ago all options, disable auto-update in PlayStore, try Titanium Backup (work but need to repeat detach through all the day, and even Magisk Module.
And SudoHide worked great for 2 years now!
When I disabled it, hope no errors Google Service with Last Vanced even, but as usual I found original Youtube auto-updated itself.

**Comment by gustasmor** [comment]
>  I finally found out guilty. I use SudoHide to hide youTube from PlayStore, cause of auto-update shit.
> I tried a year ago all options, disable auto-update in PlayStore, try Titanium Backup (work but need to repeat detach through all the day, and even Magisk Module.
> And SudoHide worked great for 2 years now!
> When I disabled it, hope no errors Google Service with Last Vanced even, but as usual I found original Youtube auto-updated itself.

You can turn off auto-updates through google play store. Go into youtube's page, then click 3 dots in the top right corner and uncheck "enable auto-update"

**Comment by DrSaad77** [comment]
I did that, and even mentioned it in my previous update.
It do not works. I mean even with auto-update for youtube disabled in PlayStore, morning I find Youtube update itself and Vanced is gone.
