### ISSUE TITLE
[no-root] YouTube Casting disables Preferred Playback Speed and SponsorBlock Functionality

### ISSUE THREAD

**Issue by kevakil** [YTVanced/Vanced#203]
EDIT: Thanks to gkp1 for informing me that this is not a bug!

**Bug description**
Whenever I try casting to my Roku or my Chromcast, the casted video does not retain the playback speed or have an option to alter the playback speed. Additionally, the SponsorBlock functionality does not work on the casted video. 

**Variant**
NonRoot: Yes
Root: No

**Vanced version**
15.43.32 - Build - 01.47.00

**Android version**
Android 10.0

**Device**
Samsung Galaxy S10e

**Steps to Reproduce**
Steps to reproduce the error:
1. Play a video with known sponsorships that are detectable and skippable by SponsorBlock
2. Alter the playback speed of the video
3. Cast the video to Chromecast/Roku
4. Cast video will play at 1.0 playback speed and will play sponsorship content.

**Expected behavior**
Instead of having the cast video always play at 1.0 playback speed, the cast video should play at the preferred playback speed. Additionally, the SponsorBlock functionality should be retained, which will allow for sponsorships in casted videos to be skipped.

**Comment by gkp1** [comment]
Casting to TV
Casting to TV doesn't actually cast, it just makes your TV open its Youtube app and play the video there.
This means that casting to TV will use the standard Youtube player which has ads and lacks the Vanced modifications.
There's nothing Vanced can do about this and this is not a bug.

Page 4/4•08/11/2020

![JlDIyQX 1](https://user-images.githubusercontent.com/63517877/99288993-2383cb80-281b-11eb-8b6f-45a93be322d3.png)

**Comment by kevakil** [comment]
Ooooh I see, my apologies. 

So I guess a better question then would be, what would be the technical restrictions to implement these features. Could I install YT Vanced on a Chromecast and have casting functionality redirect to use YT Vanced instead of the default app?

Also, is there any additional documentation you recommend that I can read through?
