### ISSUE TITLE
[Idea] Blocking Subtitles

### ISSUE THREAD

**Issue by Joystick01** [YTVanced/Vanced#204]
I would like to be able to block subtitles as they often enough appear without explicitly enabling them!

**Comment by Trysupe** [comment]
I just had the exact same idea.
I have an issue where they are turning on completely randomly which is pretty bothering. I am not the only one having this issue: https://www.reddit.com/r/Chromecast/comments/2320ib/cant_turn_off_captions_on_some_youtube_vids/

It'd be nice to have a button which completely disables the subtitles in the whole app.

**Comment by astankov84** [comment]
I will be really happy if such option exists because I constantly turn CC off and they appear again in every next video.

**Comment by annego15** [comment]
Same for me. This is so annoying and there seems to be no option to disable it.
