### ISSUE TITLE
my vanced manager is always crashing after the new update even i reinstalled it my variant is non-root and my android version is 6.0.1 now

### ISSUE THREAD

**Issue by HubUser09** [YTVanced/Vanced#208]
**Bug description**
Replace me with a clear and detailed description of the bug.

**Variant**
NonRoot: Yes
Root: No

**Vanced version**
15.43.32 - Build - 01.47.00

**Android version**
Android 9.0 - Pie

**Device**
Samsung Galaxy S8

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
3. ....

**Expected behavior**
Replace me with a description of what you expected should happen and what happened instead.

_Attach images/videos if possible. These can be helpful in solving the issue._

**Comment by gghhkm** [comment]
This is not a Vanced issue sir.

https://github.com/YTVanced/VancedManager/issues

**Comment by gghhkm** [comment]
This is not a YouTube Vanced issue sir.

https://github.com/YTVanced/VancedManager/issues
