### ISSUE TITLE
[Idea] Remove the swipe down on the video to exit fullscreen

### ISSUE THREAD

**Issue by Slimakoi** [YTVanced/Vanced#21]
**Please describe your idea. Add as much info as possible**
With the new update, a new feature was added. That when you where watching a video on full screen, and swiped down, the video made an animation going downwards an exit out of full screen mode. I suggest adding a checkbox on the vanced settings to enable or disable said feature.

**Why is this idea relevant? What makes this feature useful?**
So you wouldn't accidentally exit out of full screen mode when swiping down to see the notification bar for example, this can happen specially to phones with smaller screens.

**Comment by VancedOfficial** [comment]
I'll try to remember look into this. I think it should be doable.

**Comment by Slimakoi** [comment]
Thank you good sir.
