### ISSUE TITLE
[Idea] loop video without making playlist 

### ISSUE THREAD

**Issue by hafx** [YTVanced/Vanced#211]
**Description**
Hi, 

I would like to know if is possible to have a function to loop video in vanced like we can on youtube desktop website. 
I know it is possible to do that with playlist but I think it can be nice to have this function with all videos. 

Thanks

**Comment by milindgoel15** [comment]
Please update to the latest v16.16.38 if you haven't already and use the auto-repeat feature from vanced settings > misc while keeping autoplay off. We are closing this issue. Feel free to reopen if you still face any issues.
