### ISSUE TITLE
[Question] Is it possible to download music from YTMusic(Vanced)

### ISSUE THREAD

**Issue by rjshrjndrn** [YTVanced/Vanced#212]
**Description**
Hi, Thank you for these awesome mods. One question, is it possible to download music, even if it's offline, from YTMusic(vanced) ?

**Comment by gkp1** [comment]
no

**Comment by ChildishGiant** [comment]
With youtube premium you can download songs for offline on vanced but afaik it's not implemented outside of that.

**Comment by rjshrjndrn** [comment]
oh.. okay. So that means, smart download also won't work.. ?

**Comment by ChildishGiant** [comment]
You can download with premium, like you can with the standard app (mixes and all). What I'm trying to say is that you cant download music without premium as fair as i know.

**Comment by rebokdev** [comment]
Is it will be added? Later?

**Comment by milindgoel15** [comment]
It will NEVER be added.
