### ISSUE TITLE
[Idea] Android Auto support

### ISSUE THREAD

**Issue by frankkienl** [YTVanced/Vanced#213]
**Description**
View videos on Android Auto headunit.

_Attach images/videos if possible. Also add any links to possible other applications with the said feature already implemented._

I got it working in this open-source YouTube-client.
https://github.com/TeamNewPipe/NewPipe/pull/4883
But because it uses a closed-source library, the PR was not accepted.
(And that's understandable)

**Comment by playingbball20** [comment]
Agreed. It does show up in Android Auto, but it states there is an error
