### ISSUE TITLE
No internet connection in app but search works

### ISSUE THREAD

**Issue by DonMito** [YTVanced/Vanced#214]
I'm a long time vancer now, but suddenly when i opened vanced today youtube said i had no internet connection, i'm connected to the internet and am aware i'm connected, search filling works just fine when i type what i search for but as soon as i press search it says to connect to internet, if i press retry nothing happens...

**Comment by milindgoel15** [comment]
Please update to the latest v16.16.38 if you haven't already. For troubleshooting, check out our [vanced guide](https://play.google.com/store/apps/details?id=com.vanced.faq) We are closing this issue. Feel free to reopen if you still face any issues.
