### ISSUE TITLE
[Bug] UI crash when scrolling through settings 

### ISSUE THREAD

**Issue by excalabir26** [YTVanced/Vanced#215]
**Bug description**
When scrolling through settings , once you get to the bottom, there is a java.lang.ArrayIndexOutOfBoundsException.

This is from using the "Vanced App" from the Google Play Store

**Variant**
NonRoot: Yes
Root: No

**Vanced version**
0.9.5

**Android version**
Android 8.0

**Device**
Samsung Galaxy S7

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2. Click on hamburger menu on top left
3. Click on 'Settings'
4. Click on 'Video and Audio'
5. Scroll to the bottom

**Expected behavior**
Not to crash

Crash Log:
{"user_action":"ui error","request":"App crash, UI failure","content_language":"en-US","content_country":"US","app_language":"en","service":"none","package":"you.tube.vanced","version":"0.9.5","os":"Linux samsung/heroqltetmo/heroqltetmo:8.0.0/R16NW/G930TUVU4CRI2:user/release-keys 8.0.0 - 26","time":"2020-11-17 02:59","exceptions":["java.lang.ArrayIndexOutOfBoundsException: length=4; index=4\n\tat androidx.preference.ListPreference.getEntry(ListPreference.java:213)\n\tat androidx.preference.ListPreference.getSummary(ListPreference.java:164)\n\tat androidx.preference.Preference.onBindViewHolder(Preference.java:510)\n\tat androidx.preference.PreferenceGroupAdapter.onBindViewHolder(PreferenceGroupAdapter.java:418)\n\tat androidx.preference.PreferenceGroupAdapter.onBindViewHolder(PreferenceGroupAdapter.java:47)\n\tat androidx.recyclerview.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:7065)\n\tat androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:7107)\n\tat androidx.recyclerview.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:6012)\n\tat androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6279)\n\tat androidx.recyclerview.widget.GapWorker.prefetchPositionWithDeadline(GapWorker.java:288)\n\tat androidx.recyclerview.widget.GapWorker.flushTaskWithDeadline(GapWorker.java:345)\n\tat androidx.recyclerview.widget.GapWorker.flushTasksWithDeadline(GapWorker.java:361)\n\tat androidx.recyclerview.widget.GapWorker.prefetch(GapWorker.java:368)\n\tat androidx.recyclerview.widget.GapWorker.run(GapWorker.java:399)\n\tat android.os.Handler.handleCallback(Handler.java:789)\n\tat android.os.Handler.dispatchMessage(Handler.java:98)\n\tat android.os.Looper.loop(Looper.java:164)\n\tat android.app.ActivityThread.main(ActivityThread.java:6944)\n\tat java.lang.reflect.Method.invoke(Native Method)\n\tat com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)\n\tat com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)\n"],"user_comment":""}

**Comment by gghhkm** [comment]
I'm pretty confident this has been fixed, you can consult [The Official Vanced Discord](https://discord.gg/rgwbXEaUCb) for help.
