### ISSUE TITLE
[Idea] Integrate youtube-dl for downloading an using offline videos

### ISSUE THREAD

**Issue by PureNetProyect** [YTVanced/Vanced#217]
**Description**
I was reading about youtube-dl, if it is used for dwonloading content, why dont intregate it with vanced microg, or youtube vanced, and assign it a directory in which to download the videos and configure that path in vanced so it loads the offline content from that path? it's the only missing feature and it would be a great improvement for vanced users.

**Comment by milindgoel15** [comment]
Vanced will never add any type of downloader. Please stop it.

**Comment by PureNetProyect** [comment]
so i should integrate the python core? hmm
