### ISSUE TITLE
[Bug] picture-in-picture Mode is bugged

### ISSUE THREAD

**Issue by Kagelar** [YTVanced/Vanced#218]
**Bug description**
Picture in picture is broken on my oneplus Devices (6 and 7 pro) 
Either the Video wont play. 
Or i cant enter the Video on picture in picture or i can only See the thumbnail
![Screenshot_20201119-115027](https://user-images.githubusercontent.com/74714088/99661182-c169d700-2a63-11eb-91f8-00edec4f1ed3.jpg)

**Variant**
NonRoot: Yes
Root: No

**Vanced version**
15.43.32 

**Android version**
Android 10.0

**Device**
Oneplus 7 pro

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2. Click on a Video 
3. Go to homescreen
4. Try to open the picture-in-picture Video 

**Expected behavior**
Opening the video

**Comment by gghhkm** [comment]
Close this one.
 #219 has a lot more information.

**Comment by gghhkm** [comment]
PIP is controlled by your ROM and not Vanced.
