### ISSUE TITLE
[Bug] Option to hide cast button stoped working

### ISSUE THREAD

**Issue by Linxgos** [YTVanced/Vanced#219]
**Bug description**
Title

**Variant**
NonRoot: Yes
Root: Sorry I don't have a rooted device to test on

**Vanced version**
15.43.32 - 01.47.00

**Android version**
Android 11

**Device**
Google Pixel 4XL

**Expected behavior**
The cast button should be hidden when cast button option in vanced settings is disabled.

**Comment by Ali-Nazlier** [comment]
Yes. I have the same problem. Even tho I turned the cast icon off, it appeared today out of a sudden. Must be a YT update.

**Comment by gghhkm** [comment]
Close this one.
#220 has much more information on the topic.
