### ISSUE TITLE
[Bug] Low quality audio/audio sounding distorted

### ISSUE THREAD

**Issue by Gugga9** [YTVanced/Vanced#22]
Very common, can happen on any video, but isn't guaranteed to happen, the only temporary fix I have found is to repeatedly close and open the video until the audio is normal

Started happening in version 15.33.34, from my experience it doesn't happen in normal YouTube

**Comment by VancedOfficial** [comment]
Do you perhaps have some codec override set? VP9 as an example? If so, remove those and test if that helps.

**Comment by Gugga9** [comment]
Also happens with no codec override set.

**Comment by NaGaaDEV** [comment]
Yes it started happening a couple of updates ago, the original YouTube is clean. Any fix being made? or I provide you with more information.

**Comment by Gugga9** [comment]
No more comments were made by any contributor and I haven't seen anything about a fix for this anywhere else so I don't think a fix is being made

**Comment by VancedOfficial** [comment]
I can't replicate the issue so I have no idea where to even begin looking. Have you tried clearing data from Vanced and then testing without changing any settings?

**Comment by NaGaaDEV** [comment]
I just cleared the data, will be trying it for a while

**Comment by NaGaaDEV** [comment]
Clearing the data with the default settings didn't help either, there still distortion
