### ISSUE TITLE
[Bug] Problemas ao assistir video no Moto G5

### ISSUE THREAD

**Issue by Sejuaini** [YTVanced/Vanced#225]
**Bug description**
Ao rodar o vídeo no YouTube Vanced no Moto G5 ele começa a travar o vídeo como se estivesse a 15FPS (frames por segundo)

**Variant**
NonRoot: Yes
Root: No

**Vanced version**
15.43.32 - Build - 01.47.00

**Android version**
Android 9.0 - Pie

**Device**
Moto G5

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2. Click on video

**Expected behavior**
Replace me with a description of what you expected should happen and what happened instead.

_Attach images/videos if possible. These can be helpful in solving the issue._

**Comment by milindgoel15** [comment]
Please update to the latest v16.16.38 if you haven't already. We are closing this issue. Feel free to reopen if you still face any issues.
