### ISSUE TITLE
[Bug] Picture in Picture random bug

### ISSUE THREAD

**Issue by pmarconep** [YTVanced/Vanced#226]
**Bug description**
When you use picture in picture feature, sometimes (apparently random, but pretty consistently) the picture in picture has in the background the thumbnail of the video. Even some of the time I have noticed the thumbnail is over the video itself. I do not know how to reproduce this bug, but it appears regularly.

**Variant**
NonRoot: Yes
Root: No

**Vanced version**
15.43.32 - Build - 01.47.00

**Android version**
Android 10.0 - Q

**Device**
Samsung Galaxy S9

**Steps to Reproduce**
I do not know how to reproduce it. But it happens with the android 10 navigation gestures as well as the built in under display S9 home button

![Screenshot_20201123-095619_Samsung Notes](https://user-images.githubusercontent.com/49997440/99965775-1a8f7e80-2d74-11eb-8ebf-f211f50e417d.jpg)

**Comment by gghhkm** [comment]
PiP is controlled by your ROM not by Vanced. 🗿

**Comment by TrianguloY** [comment]
And sometimes I even have a transparent pip, that I can move and click to show the buttons, but no video shown.

I have never had any issue with pip in other apps, nor with previous versions of vanced, so I don't think it is an issue with the rom (or stock android on my case).

The current YouTube pip is so broken...but I guess fixing it requires so many changes that the vanced team won't even care (and it is YouTube's job to fix them anyways).

**Comment by pmarconep** [comment]
> PiP is controlled by your ROM not by Vanced. 🗿

I take your word on it. But, im running on stock samsung ROM 10.0, and this issue only happends with Vanced pip, not Netflix or web browser

**Comment by gghhkm** [comment]
> And sometimes I even have a transparent pip, that I can move and click to show the buttons, but no video shown.
> 
> I have never had any issue with pip in other apps, nor with previous versions of vanced, so I don't think it is an issue with the rom (or stock android on my case).
> 
> The current YouTube pip is so broken...but I guess fixing it requires so many changes that the vanced team won't even care (and it is YouTube's job to fix them anyways).

Ok, now you're just being disrespectful.
If Vanced team could fix it they would.
Also please remember that Vanced is a FREE Mod that has years of VOLUNTARY work behind it.
Also it is your ROM, many other people have 0 issues.
Also I know how to fix the other guy issue easy because I know how to fix a OnePlus ROM, all he needs to do is come to the Discord.

**Comment by gghhkm** [comment]
> > PiP is controlled by your ROM not by Vanced. 🗿
> 
> I take your word on it. But, im running on stock samsung ROM 10.0, and this issue only happends with Vanced pip, not Netflix or web browser

One UI has many changes in it.
Also not every app uses ROM PiP like Stock Youtube (and In turn Vanced) does. If you want to fix it you'll eathor need to report it to Google or use Android 11.
There is nothing Vanced team can do, they are a Mod group not some Dev group at Google.

**Comment by TrianguloY** [comment]
Wasn't trying to be disrespectful towards vanced (a bit towards YouTube) so I apologize if it sounded that way. I'm very aware of what vanced is, although it is true that sometimes the responses to user bugs were not very empathic (specially when they needed to be reported on the discord server).

About the bug in question, please understand that 'a lot of people doesn't have any problem' isn't the same as 'the bug doesn't exists'. This reported bug happens with official stock android versions, and even though pip is an OS feature, what is displayed inside the pip windows is property of the app, and is modified by the app, not android. https://developer.android.com/guide/topics/ui/picture-in-picture#handling_ui

**Comment by gghhkm** [comment]
> Wasn't trying to be disrespectful towards vanced (a bit towards YouTube) so I apologize if it sounded that way. I'm very aware of what vanced is, although it is true that sometimes the responses to user bugs were not very empathic (specially when they needed to be reported on the discord server).
> 
> About the bug in question, please understand that 'a lot of people doesn't have any problem' isn't the same as 'the bug doesn't exists'. This reported bug happens with official stock android versions, and even though pip is an OS feature, what is displayed inside the pip windows is property of the app, and is modified by the app, not android. https://developer.android.com/guide/topics/ui/picture-in-picture#handling_ui


> what is displayed inside the pip windows is property of the app, and is modified by the app, not android. 

And that right there is where the problem lies.
You assume that your ROM is perfect and that it wouldn't cause a conflict in an app that trys supports nearly every Android on the market. Think of it this way; if you try to support a bunch of Androids with many changes a problem is bound to happen. What if changing the app to accommodate your ROM breaks it for someone else.

Anyway like I said before this is *Not* a Vanced issue and should be reported to Google or your ROM provider.
Hell if you can; Android 11's PiP is has complete working without issue on all Android 11 ROMs atm.

**Comment by yiddytlq** [comment]
> PiP is controlled by your ROM not by Vanced. 🗿

I'm having the same issue on my OnePlus 7 Pro android 10.

Only happens with cancer app.

**Comment by yiddytlq** [comment]
Right now the issue is a bit different. If I go into pip mode when watching a video in portrait mode, the video will be 100% transparent. If I go into pip mode when it's in landscape mode it works fine.

**Comment by Kunal-Azirius** [comment]
I have the same issue on my Realme X2 Pro with Android 10 and realme ui 1.0.  Blank PiP. I need to click on it to reopen and then go back using home button, then it works fine. But yes, this occurs 90% of the time. Not a dealbreaker, came here just to confirm it's not just me facing this.
