### ISSUE TITLE
[Bug] Unable to load

### ISSUE THREAD

**Issue by SodaWithoutSparkles** [YTVanced/Vanced#227]
**Bug description**
Unable to load, a blue loading icon is loading.

**Variant**
NonRoot: Yes
Root: No

**Vanced version**
15.43.32
**Android version**
10 QKQ1.190828.002

**Device**
Pocophone F1, Redmi note 8 Pro

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2. No video shows up
3. Keeps loading, seems to be forever, won't recover unless I reboot
4. Force close doesn't recover it

**Expected behaviour**
Shows some videos. (Homepage)

_Attach images/videos if possible. These can be helpful in solving the issue._
![image](https://user-images.githubusercontent.com/64138578/100196392-c206df80-2f33-11eb-91c0-989b3a7592e2.png)

**Comment by GhostyJade** [comment]
In my case (non rooted phone, latest vanced and MicroG updates), it says that I'm offline in every section I visit (even if I'm online, lmao). 
It doesn't fetch in any way anything
(the only section reachable is the settings menu...but it doesn't store any changed setting)
