### ISSUE TITLE
[Idea] Toggle to get the old small video thumbnails back 

### ISSUE THREAD

**Issue by Harmonie666** [YTVanced/Vanced#229]
**Description**
I would appreciate it, if we could have those old small video thumbnails back, that we used to get as search results. Nowadays the new updated thumbnails are so huge, that;
1) two videos take up the entire screen 
2) it's a lot more difficult to find a video, because the thumbnails are so huge, and we need to scroll down/up alot more.
3) it's just a terrible UI and user unfriendly

I think many users would appreciate if we could disable those new large thumbnails, and get the old small ones back.  
![cb36e80](https://user-images.githubusercontent.com/73917917/100270575-8df1e580-2f58-11eb-8950-fa01709ff886.jpg)

**Comment by milindgoel15** [comment]
Youtube server side. we cant do anything
