### ISSUE TITLE
No connection 

### ISSUE THREAD

**Issue by Martydk85** [YTVanced/Vanced#23]
So now I can't use my ytv it says I have no connection, even though I'm home on my wifi,
Im used to use it when I'm at work, watching videos.
But it says I have no connection what so ever.
I have tried deleting it 2 times and reinstalling it.
Tried the playstore version to,
But with that one I can't connect to my YouTube channel and se my videos or my subscriptions and how far a got in my channel watching..
What could it be, pls help I'm addicted to this app without ads
Android 
Samsung A50

**Comment by milindgoel15** [comment]
We have no app on play store. And it will never be. What fake app you installed lmao?

**Comment by milindgoel15** [comment]
https://telegra.ph/Troubleshooting-for-vanced-03-19

Try the connection issue fix from this

**Comment by Martydk85** [comment]
Connection is ok, but now i get this.. 

![20200916_203711](https://user-images.githubusercontent.com/71259786/93378298-89c09200-f85c-11ea-8e43-32b1f6a498f2.jpg)

**Comment by milindgoel15** [comment]
> Connection is ok, but now i get this.. 
> 
> ![20200916_203711](https://user-images.githubusercontent.com/71259786/93378298-89c09200-f85c-11ea-8e43-32b1f6a498f2.jpg)
> 

Remove microg account from your account settings
Wipe microg data
Then login

**Comment by Martydk85** [comment]
Thank you so much 
It worked
