### ISSUE TITLE
[Bug] Won't get notifications, only notifications I get is from real youtube.

### ISSUE THREAD

**Issue by 6ass** [YTVanced/Vanced#230]
**Bug description**
Whenever I get a new youtube upload notification it is from the real youtube app and it redirects me to the real youtube application if I click on it.

**Variant**
NonRoot: Yes
Root : No

**Vanced version**
15.43.32 

**Android version**
Android 10 

**Device**
Redmi Global Note 9 Pro

**Steps to Reproduce**
Steps to reproduce the error:
No idea

**Expected behavior**
I expected to get notifications from youtube vanced but instead I get notifications from normal youtube app

_Attach images/videos if possible. These can be helpful in solving the issue._

**Comment by milindgoel15** [comment]
duplicate of #126
