### ISSUE TITLE
[Idea]see the name of the deleted video

### ISSUE THREAD

**Issue by fusephoto** [YTVanced/Vanced#231]
**Description**
The title says it all. The problem is that sometimes videos get deleted or put on private which is ok but I still want to know the name of the video/song so I can find it again. So it would be cool if you could somehow manage it to still show the name of the deleted video. This would be possible by for example somehow saving the names of the videos in the playlist. 
Also thanks for making the apps, very cool and useful. I am using your apps everyday 👍

**Comment by Svk1190** [comment]
This is a regular point of frustration for me. It would be amazing if we can create a backup (or export into text file) of our YouTube playlists including at least the url and name of the video (and possibly the video description).
