### ISSUE TITLE
[Bug] replaceme nothing I  can't use the app

### ISSUE THREAD

**Issue by Fernandosza** [YTVanced/Vanced#232]
![Screenshot_20201127-122401](https://user-images.githubusercontent.com/75132463/100464085-ae7e8480-30ab-11eb-8cf4-857e8beb9e3e.png)

**Bug description**
Replace me with a clear and detailed description of the bug.

**Variant**
NonRoot: Yes
Root: No

**Vanced version**
15.43.32 - Build - 01.47.00

**Android version**
Android 9.0 - Pie

**Device**
Samsung Galaxy S8

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
3. ....

**Expected behavior**
Replace me with a description of what you expected should happen and what happened instead.

_Attach images/videos if possible. These can be helpful in solving the issue._

**Comment by gghhkm** [comment]
https://www.youtube.com/playlist?list=PLtCHXepv2DczTqtpOazWk-M8euiGSlRxi

**Comment by gghhkm** [comment]
[Official Vanced Discord Invitation](https://discord.gg/rgwbXEaUCb)
[Message Link](https://discord.com/channels/328493314485518336/358967876193091584/809525073903616022)
