### ISSUE TITLE
[Bug] crash

### ISSUE THREAD

**Issue by jlkkljh** [YTVanced/Vanced#233]
**Bug description**
Crash after clicking update and rotate screen

**Variant**
NonRoot: Yes

**Vanced version**
15.43.32 - Build - 01.47.00

**Android version**
Android 9.0 - Pie
Root: No

**Device**
Lg Stylo 3 cricket

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2. Click on update vanced
3. rotate screen

**Expected behavior**
After clicking update, rotate the screen and crash

![Screenshot_2020-11-27-14-43-15](https://user-images.githubusercontent.com/33626414/100484709-24421a80-30c3-11eb-929d-3c8665386ba9.png)

**Comment by milindgoel15** [comment]
it has already been fixed. Please update to the latest manager v2.6.0 if you haven't already. We are closing this issue. Feel free to reopen if you still face any issues.
