### ISSUE TITLE
Not Connecting to internet 

### ISSUE THREAD

**Issue by thekingwailer** [YTVanced/Vanced#235]
Non-Rooted Samsung Galaxy Note 10+
I just updated microg and removed and reinstalled youtube vanced. Due to previously i signed to my account.  Now i can't connect to internet. Tryed both wifi and mobile data. Checked if any firewall block. Don't have any logcat. 
![Screenshot_20201128-031937](https://user-images.githubusercontent.com/74659561/100489175-255b6200-312c-11eb-91df-5ac318e55c25.jpg)

**Comment by dharmasidi** [comment]
I have the same problem

**Comment by gghhkm** [comment]
> Non-Rooted Samsung Galaxy Note 10+
> I just updated microg and removed and reinstalled youtube vanced. Due to previously i signed to my account. Now i can't connect to internet. Tryed both wifi and mobile data. Checked if any firewall block. Don't have any logcat.
> ![Screenshot_20201128-031937](https://user-images.githubusercontent.com/74659561/100489175-255b6200-312c-11eb-91df-5ac318e55c25.jpg)



> I have the same problem

Remove the microG account from your devices settings, and disable battery optimization for MicroG then relogin to Vanced.

Also please go to [Vanced Discord](https://discord.gg/dz8J3Xrq) before writing issues, it exists for a reason.
