### ISSUE TITLE
[Idea] Increase Maximum Playback Speed

### ISSUE THREAD

**Issue by TempUser13** [YTVanced/Vanced#238]
My request is to increase the Maximum Playback Speed from 2x to 3x via increases of 0.25x. My second request is to be able to type in a numerical value for the payback speed which would be between 0 and 3. Thank you.

**Comment by surajkumarbehera09** [comment]
I also need this.....

**Comment by Vasilich1234** [comment]
I vote for this

**Comment by gghhkm** [comment]
#82

**Comment by milindgoel15** [comment]
duplicate of #82
