### ISSUE TITLE
[Bug] Stories are glitched

### ISSUE THREAD

**Issue by GalaxyLinus** [YTVanced/Vanced#240]
**Bug description**
When I swipe through stories, sometimes a stripe of the last story appears on the current one (see pictures)
![100553236-10e2ab00-328d-11eb-9eaa-9db7450d84ec](https://user-images.githubusercontent.com/57060126/100554964-e39bfa00-3298-11eb-8fff-58c2fcd993b2.jpg)
![100553238-1213d800-328d-11eb-9290-1ae0138a21e3](https://user-images.githubusercontent.com/57060126/100554966-e7c81780-3298-11eb-9466-d88f24e8e9fe.jpg)

**Variant**
NonRoot: Yes
Root: No

**Vanced version**
15.43.32 - Build - 01.47.00

**Android version**
Android 9.0 - Pie

**Device**
ZTE Blade 10 Smart

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2. Click on 'Stories'
3. Swipe down a few times until you see the bug happen

**Expected behavior**
It should just display the current story.

**Comment by GalaxyLinus** [comment]
I couldn't test if it works on rooted devices

**Comment by milindgoel15** [comment]
Please update to the latest v16.16.38 if you haven't already. We are closing this issue. Feel free to reopen if you still face any issues.
