### ISSUE TITLE
[Idea] Youtube Clickbait Remover Integration

### ISSUE THREAD

**Issue by VisualFootprint** [YTVanced/Vanced#241]
**Description**
I love the Integration with SponsorBlock and it would be awesome if it'd be possible to integrate the "Youtube Clickbait Remover" Chrome extension aswell. <3

https://chrome.google.com/webstore/detail/clickbait-remover-for-you/omoinegiohhgbikclijaniebjpkeopip

**Comment by Ali-Nazlier** [comment]
Sounds like a good idea. I will definitely check that ext 👍🏻
