### ISSUE TITLE
[Bug] Ads sometimes shows below video

### ISSUE THREAD

**Issue by asdsadsaasd12312132** [YTVanced/Vanced#242]
**Bug description**
Ads sometimes shows below video 

https://imgur.com/a/0gJepnL

**Variant**
Root: Yes

**Vanced version**
15.43.32 - Build - 01.47.00

**Android version**
Android 9.0 - Pie

**Device**
Oneplus 3

**Steps to Reproduce**
Open a video and it's there sometimes.

**Expected behavior**
No ad

**Comment by pythonInRelay** [comment]
Sale issue, same version, but on Huawei P30 Pro as seen below.

![Uploading Screenshot_20201209_110509_com.vanced.android.youtube.jpg…]()

**Comment by milindgoel15** [comment]
Please update to the latest v16.16.38 if you haven't already. We are closing this issue. Feel free to reopen if you still face any issues.
