### ISSUE TITLE
[Bug] Continuously says error connecting to network

### ISSUE THREAD

**Issue by izchieve** [YTVanced/Vanced#243]
**Bug description**
I have both Youtube and YT Music from Vanced, and every time I open these apps, it says that there's no network connection or I have to login. I always have to login to access videos and music. Though this isn't a big of a problem to me because I'm used to it, it would still be nice if someone can tell me how to fix this. 

**Variant**
NonRoot: Yes
Root: No

**Vanced version**
15.43.32 

**Android version**
Android 10

**Device**
Tecno Pouvoir 4 Pro

**Steps to Reproduce**
Steps to reproduce the error:
1. Make sure that the app hasn't been opened for a while. 
2. Open the app
3. There should be an error stating "Connect to the internet. You're offline. Check your connection." something like that. I cannot reproduce the error for now because I've been using Vanced YT and Music for a while now. 

**Expected behavior**
The app should show all the videos in the home page section, as well as the home page in the YT Music app, but it shows that i have it failed connecting to network. 

_Attach images/videos if possible. These can be helpful in solving the issue._
![Screenshot_20201203-133819.png](https://user-images.githubusercontent.com/74660231/100968908-2f86c180-356d-11eb-8a14-f8cbf79ca190.png)

**Comment by DPrinceKumar** [comment]
Update micro-g you will be good to go

**Comment by DPrinceKumar** [comment]
I tried...it worked for me

**Comment by gghhkm** [comment]
[Official Vanced Discord Invitation](https://discord.gg/rgwbXEaUCb)
[Message Link](https://discord.com/channels/328493314485518336/358967876193091584/809525073903616022)
