### ISSUE TITLE
[Idea] Whitelist channel from Sponsor Block API

### ISSUE THREAD

**Issue by Blackenergy25** [YTVanced/Vanced#245]
My idea is to add a whitelist for the SB-API so the user can select their channel that they want to support (or watch their sponsor Segway) without the hassle of turning it off and back on when done with a channel

**Comment by Martin5001** [comment]
I would definitely use that for some channels.

**Comment by milindgoel15** [comment]
This has already been noted in our lists. But unfortunately the user who implemented sponsorblock is not available till June. Please wait patiently. Meanwhile, we are closing this issue. If you have any other concern, feel free to ask.
