### ISSUE TITLE
[Bug] Vanced closing while opening short videos

### ISSUE THREAD

**Issue by WickedCerberus** [YTVanced/Vanced#25]
1. Version 15.33.34
2. Downloaded and installed through vanced 
    manager root method (disabled signature 
    verification after installing)
3. Device is Redmi 4 
     ROM - RROS-Q-8.6.0-20200910-santoni-Official
4. [Crash Log](https://del.dog/cramipopyp) 
5. Rooted with magisk (got viper4android module)
6. Everything else works fine but as soon as I click 
    on a short video it force closes 
    No problem on the stock app

**Comment by milindgoel15** [comment]
Known issue
