### ISSUE TITLE
[Idea] Youtube Vanced on Android TV/Fire TV

### ISSUE THREAD

**Issue by PalanixYT** [YTVanced/Vanced#251]
It may be a bit outrageous of anyone to ask of a basically new project, but I think it's a great idea. So there are Youtube alternatives on Android/Fire TV, but they are not uptodate and lack alexa implementation because they are based on old builds. 
It would basically be the same as Youtube Vanced but with the Android/Fire TV interface(and perhaps alexa support, but that would be included if it were based on a new build of Youtube on TV)

**Comment by pythonInRelay** [comment]
You're right. It is outrageous.
