### ISSUE TITLE
[Bug] google account

### ISSUE THREAD

**Issue by Bemnadel** [YTVanced/Vanced#254]
**sign in microg**
I can't sign in microg

**Variant**
NonRoot: Yes
Root: No

**Vanced version**
15.43.32 - Build - 01.47.00

**Android version**
Android 8.0

**Device**
Huawei y7 prime 2018 

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2. Click on add account on Huawei
3. I'm putting my e-mail and the pass.
4. It says that "sorry there was a problem communicating with google servers" 

**Expected behavior**
I expect sign in but it's not. I tried vpn and everything And it doesn't allow sign-in.

https://photos.app.goo.gl/QG4vtnBWsqwKJFNZ6

**Comment by bunnygamer** [comment]
Me too

**Comment by myxcilo** [comment]
same on one plus 8t. did anyone figure it out?

**Comment by milindgoel15** [comment]
Please update to the latest version of both microG and vanced if you haven't already. We are closing this issue. Feel free to reopen if you still face any issues.
