### ISSUE TITLE
[Bug] Subscription Feed Issue.

### ISSUE THREAD

**Issue by JustJumpy** [YTVanced/Vanced#255]
When you click on sorting your subsriptions and set it to 'Videos Only' and then relaunch the app, the setting has reverted to 'Videos and Posts'. 
This occurs every time the app is relaunched. This is not the case on the official YouTube app.

**Comment by milindgoel15** [comment]
Please update to the latest v16.16.38 if you haven't already. We are closing this issue. Feel free to reopen if you still face any issues.
