### ISSUE TITLE
[Idea] enable the ability to use the miniplayer for vids made for kids 

### ISSUE THREAD

**Issue by MuhannadYT** [YTVanced/Vanced#256]
**Description**
enable the ability to use the miniplayer for vids made for kids, for example, add the option to "Enable miniplayer for videos made for kids" and people can toggle it on or off, it could be set off as default 

![Screenshot_20201206_170917_com vanced android youtube](https://user-images.githubusercontent.com/49660804/101294612-97940c80-37e6-11eb-989a-4bf82670043a.png)

**Comment by surajkumarbehera09** [comment]
It would be great.....

**Comment by Ali-Nazlier** [comment]
Yes that would be helpful. There are some videos that are not kids friendly, but are still uploaded as video for kids..

**Comment by surajkumarbehera09** [comment]
Yes....I agree with you.

I have an issue with vanced. In picture in picture mode miniplayer looks
like dual (screenshot). If you are facing similar issue you can also report
that bug.

I have also another suggestion to increase and decrease playback speed, you
can support that idea.

Thanks & Regards.....
