### ISSUE TITLE
[Bug] Can't connect to internet

### ISSUE THREAD

**Issue by VancedUser** [YTVanced/Vanced#258]
I open youtube vanced, get the picture with the astronaut and says "Can't connect to internet." With a retry button

NonRoot: Yes

**Vanced version**
15.43.32 - Build - 01.47.00

**Android version**
Android 9.0 - Pie

Moto G8 Plus

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2. Get error message as soon as the app opens "can't connect to internet."

I've tried restarting the phone. Removing my google account and re-adding it. Try with WiFi and data only. Internet works fine on the rest of my phone. Have tried uninstalling and reinstalling vanced manager. I'm out of ideas.

**Comment by dhruvdg5** [comment]
with my device also

**Comment by VancedUser** [comment]
Updated microg just now. Still running into same issue.

**Comment by VancedUser** [comment]
Been 4 days, still have this issue.

**Comment by dhruvdg5** [comment]
Bug fixed by removing google account and re adding it to vanced app

**Comment by DPrinceKumar** [comment]
That f

> Same happened with me too
> Updated micro-g you will be good to go

This worked for me ..but I don't know what issue you have

**Comment by VancedUser** [comment]
I see what I did. I removed the google account from my phone, but micro G will still hold onto it, apparently even if you uninstall and reinstall micro G. 

Went into the Google app, clicked on the top right corner with the icon, clicked on micro G, clicked remove account. 

You can also remove the Google account from the Micro G app. 

Once I did that and re-added the Google account. Vanced is working again. Thanks all!

**Comment by Monir966** [comment]
How long will this problem last? What good is a web site if it simply "blends in" with everything else out there? It is possible to reinstall microG repeatedly. Every time I reinstall, the problem is after a while

**Comment by milindgoel15** [comment]
> How long will this problem last? What good is a web site if it simply "blends in" with everything else out there? It is possible to reinstall microG repeatedly. Every time I reinstall, the problem is after a while

Go blame your ROM. It ain't vanced issue. The problem arises due to your device aggressive battery optimization which kills apps for its own sake. If you don't wanna see such problems in any way, ur best options would be to use root version or use stock official YouTube app. 

**It's NOT vanced issue.**

**Comment by milindgoel15** [comment]
Duplicate of #786

**Comment by johntony366** [comment]
Did you by any chance change the password of the google account associated with Youtube Vanced? I had the same issue as you and I think this was what caused it. Removing the google account from Micro G and then re-adding it solved the problem for me.

**Comment by TDMBugs** [comment]
I might have and just forgotten about it, how do i removed the account from the Micro G

**Comment by milindgoel15** [comment]
Yes, because microG doesn't fully support it. It's not because of vanced.

**Comment by Trcavus** [comment]
Telefonum android 11. Poco X3 Pro işletim sistemi Mi12.5 sürüm
![Screenshot_2021-09-28-23-04-44-184_com android settings](https://user-images.githubusercontent.com/91570613/135165849-9695439b-b48a-4441-824b-7dd4f345761c.jpg 
Telefonunuzun Ayarlar>Uygulamalar>Uygulamaları yönet> kısmında arama çubuğuna microG yazın ve Vanced microG uygulamasını açın. İzinler kısmında veri kullanımını kısıtla bölümündeki mobil veriyi işaretleyin. Sorun çözülecektir.

In your phone's Settings>Applications>Manage applications> type microG in the search bar and open the Vanced microG application.  Tick ​​mobile data in the Restrict data usage section in the Permissions section.  The problem will be solved.
