### ISSUE TITLE
X Button

### ISSUE THREAD

**Issue by jackal918** [YTVanced/Vanced#26]
hi vanced, sorry to ask, 
but do you know how i can get rid of the x button the layout? i tried going to accessability in youtube but it says i have no apps able to open it.
thank you!

**Comment by ShashankRaoM** [comment]
You need to turn it off in accessibility. But I'm not able to open accessibility in the settings. That issue must be reported.

**Comment by milindgoel15** [comment]
@ShashankRaoM don't create duplicate issues.  Since this issue is already created by jackal, issue created by you wasn't needed.

**Comment by VancedOfficial** [comment]
Should be fixed in the 15.38.35 release. Open a new issue if not.
