### ISSUE TITLE
In picture in picture mode miniplayer the window looks dual like and odd

### ISSUE THREAD

**Issue by surajkumarbehera09** [YTVanced/Vanced#260]
![Screenshot_20201209-180839_One UI Home](https://user-images.githubusercontent.com/75734796/101631826-007bbe80-3a4b-11eb-9efa-30d820d8b91f.jpg)

**Comment by Jonius7** [comment]
I have this, and also if I switch from landscape to portrait, the picture-in-picture goes out of alignment and the video shifts about 200 pixels to the right)

**Comment by surajkumarbehera09** [comment]
Yes

**Comment by milindgoel15** [comment]
PIP is system side. please don't report pip-related issues.
duplicate of #253
