### ISSUE TITLE
[Bug] Vanced Video Quality changing bug 

### ISSUE THREAD

**Issue by BlueStarBRS** [YTVanced/Vanced#261]
**Bug description**
Videos not changing to the settings Quality What you have saved example you set 360p on Mobile but its Loading every time on 1080p

**Variant**
NonRoot: Yes

**Vanced version**
15.43.32 - Build - 01.47.00

**Android version**
Android 8.0 - Oreo

**Device**
Samsung Galaxy A5 (2017)

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2. Click on settings
3. Click on vanced settings
4. Click on Video settings
5. Set 360p on mobile and 1080p by WiFi
6. Play video with mobile data 
it dont changed to 360 but to 1080p
7.start Video with wifi its 1080p but if you set 720p it dont change to 720p

**Expected behavior**
If you change it to 360p its change on mobile to 1080p and the same by wifi its since this new YouTube BETA video quallity Option/Feature, i have installed a older version 15.40.37 this is the last bersion without this beta Quality setting and its works perfect but not on actuall Version 15.43.32. 

_Attach images/videos 
https://youtu.be/Wc4GxPOtMwE
![Screenshot_20201208-020945.jpg](https://user-images.githubusercontent.com/25110093/101670213-2dcc6a80-3a53-11eb-81ab-47e74113cc3f.jpg)
I have set 360p but its 1080p everytime :(

![Screenshot_20201208-021204.jpg](https://user-images.githubusercontent.com/25110093/101670267-3b81f000-3a53-11eb-94fe-806e4479b883.jpg)
This Feature makes the Problems i think.

![Screenshot_20201208-024226.jpg](https://user-images.githubusercontent.com/25110093/101670533-94518880-3a53-11eb-932e-12989f4acf77.jpg)
I have changed 1080p but its 480p on wifi 

I hope for a fix, thx

**Comment by BlueStarBRS** [comment]
Notice i mean the video quality settings on the start from a video.
(Autoload Quality)

**Comment by milindgoel15** [comment]
Refer to #576 from now since that is one of the current issues as well. closing this
