### ISSUE TITLE
[Bug] Cast button is missing

### ISSUE THREAD

**Issue by psycho2170** [YTVanced/Vanced#265]
**Bug description**
Replace me with a clear and detailed description of the bug.

**Variant**
NonRoot: Yes
Root: No

**Vanced version**
15.43.32 - Build - 01.47.00

**Android version**
Android 9.0 - Pie

**Device**
Samsung Galaxy S8

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
3. ....

**Expected behavior**
Replace me with a description of what you expected should happen and what happened instead.

_Attach images/videos if possible. These can be helpful in solving the issue._

**Comment by milindgoel15** [comment]
Are u sure u are using the same network on both of your devices?

**Comment by ochen1** [comment]
Issue similar to #295

**Comment by psycho2170** [comment]
Yes ....but now it works perfectly fine.... updated the app

**Comment by ochen1** [comment]
> Yes ....but now it works perfectly fine.... updated the app

If it works now you could close this issue

**Comment by psycho2170** [comment]
Sorry my bad
