### ISSUE TITLE
[Bug] Can't See Channels Subscribed To

### ISSUE THREAD

**Issue by addedsomewater** [YTVanced/Vanced#268]
**Bug description**
On the subscriptions tab, it is not possible to scroll sideways through all channels you are currently subscribed to. The "ALL" button is missing too. Both features are present in the default YouTube app.

**Variant**
NonRoot: Yes
Root: No

**Vanced version**
15.43.32 - Build - 01.47.00

**Android version**
Android 8.0 - Oreo

**Device**
Samsung Galaxy S7

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2. Click on 'Subscriptions'
3. Note you can't scroll horizontally through the subscribed channels at the top, or view a list of them.

**Expected behavior**
Ability to scroll through all subscribed channels, and/or open a full list of them.

YouTube Vanced:
![Screenshot_20201212-170806](https://user-images.githubusercontent.com/63992620/102000679-cc004080-3c9e-11eb-9520-9490d584baa6.jpg)

Stock YouTube app with most recent update, for comparison:
![Screenshot_20201212-172229_YouTube](https://user-images.githubusercontent.com/63992620/102000683-dc182000-3c9e-11eb-962c-39a2d9e0a2aa.jpg)

**Comment by milindgoel15** [comment]
Try clearing data.

**Comment by Omega944** [comment]
I have the same issue on version 16.02.35. It can be fixed by keeping the option to force the old comment layout disabled.

**Comment by fh-rabbi** [comment]
🔰 For solve this problem ~ go to (yt vanced app settings ➡️vanced settings ➡️ layout settings ➡️ Turn off comments location [feature]).
- You have successfully solved it, now restart the app 😍
