### ISSUE TITLE
[Bug] Tap to seek doesn't work for videos with chapters

### ISSUE THREAD

**Issue by Harmonie666** [YTVanced/Vanced#269]
**Bug description**
If you watch a video that has chapters, and you try to tap a time in the progress bar, it always drags you back to the last chapter. You cannot use tap to seek in the progress bar properly. I think many of us have experienced it, and know exactly what I mean. 

**Variant**
NonRoot: Yes

**Vanced version**
15.43.32 - Build - 01.47.00

**Android version**
Android 10

**Device**
ASUS ROG Phone II

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2. Click on a video with chapters. 
(For example this: https://youtu.be/vpUmi-M1E3I)
3. Try tap to seek in a video with chapters, it doesn't work at all. Always drags you back to the chapter point.

**Expected behavior**
Fix the tap to seek issue for videos with chapters in them.
![Screenshot_20201213-124450676 (1)](https://user-images.githubusercontent.com/73917917/102011080-4c2bb200-3d42-11eb-96ab-a5af060116bc.png)

**Comment by milindgoel15** [comment]
Works fine here for me. Have you checked clearing data or reinstalling?

**Comment by milindgoel15** [comment]
Since there's no reply from op, we will close this issue for now. Feel free to reopen if you still face this issue
