### ISSUE TITLE
[Bug] Links in description of videos won't open

### ISSUE THREAD

**Issue by waterlava** [YTVanced/Vanced#27]
Android 6.0.1
Device: Motorola Moto E
Vanced Version 15.33.34

Error message: "Sorry, you cannot open this link."

Steps to reproduce:
Click on any link in the description of a video within the app.

Exceptions:
This error is not produced when you click on a link to a channel or video.

I'm new to GitHub so I hope this is sufficient :)

**Comment by waterlava** [comment]
Here is a link to the logcat: [https://hastebin.com/ucagixubos.pl](https://hastebin.com/ucagixubos.pl)
[logcat.txt](https://github.com/YTVanced/Vanced/files/5226401/logcat.txt)

**Comment by AinzTheSupremeOne** [comment]
What about links on stock YouTube app? Do they work?

**Comment by waterlava** [comment]
Unfortunately, I wouldn't know because my device doesn't have stock YouTube. I can't install stock currently because my phone does not have enough remaining storage. When I switch over to a new device (mid October), I can afford to help solve this bug by making room for both the stock YouTube and Vanced, but I can't afford to do this right now as it's my main device. 

It may be relevant that my device also does not have chrome installed (again, due to my storage space limitations) and that I only use Google Go and Opera Mini. Maybe the app doesn't have anywhere to open the link in?

**Comment by waterlava** [comment]
Fixed: I didn't have chrome installed and it wouldn't recognize Opera Mini as a valid browser to open links in.
