### ISSUE TITLE
[Bug] replaceme

### ISSUE THREAD

**Issue by eqge** [YTVanced/Vanced#272]
**Bug description**
No internet connection while trying to login on Youtube Vanced

**Variant**
NonRoot: Yes
Root: No

**Vanced version**
15.43.32 - Build - 01.47.00

**Android version**
Android 7.0 Nougat

**Device**
Redmi Note 4X 3GB/32GB

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2. Click on Accounts
3. Click on Sign In
4. Then it will show no internet connection under my account

**Expected behavior**
It will sign me in on my account if i press my account email

_Attach images/videos if possible. These can be helpful in solving the issue._

![Screenshot_2020-12-14-13-26-16-940_com vanced android youtube](https://user-images.githubusercontent.com/75966609/102043668-03dac580-3e10-11eb-818f-cb69aefb4860.jpg)

**Comment by milindgoel15** [comment]
Follow this https://telegra.ph/Troubleshooting-for-vanced-03-19#Login-issues
