### ISSUE TITLE
[BUG] All vanced app can't connect to internet

### ISSUE THREAD

**Issue by nitayc04** [YTVanced/Vanced#274]
Since the Google server Collapsed I can't use any of the vanced apps it says that he can't connect to internet but the regular youtube works for me I don't know what to do

**Comment by caseysui** [comment]
Same problem here for weeks.

**Comment by eisidoro** [comment]
Try clean all data and cache for Vanced Apps. Here it worked but still cant login in apps

**Comment by milindgoel15** [comment]
Apparently this issue is irrelevant now. Please close this

**Comment by gghhkm** [comment]
Close this issue.
If you somehow still have this issue go to the discord.
https://discord.gg/vanced
