### ISSUE TITLE
[Bug] replaceme

### ISSUE THREAD

**Issue by sH1222J** [YTVanced/Vanced#275]
**Bug description**
Replace me with a clear and detailed description of the bug.

**Variant**
NonRoot: Yes
Root: No

**Vanced version**
15.43.32 - Build - 01.47.00

**Android version**
Android 10

**Device**
Samsung Galaxy Tab S7+ (SM-T975N)

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
3. ....

**Expected behavior**
Replace me with a description of what you expected should happen and what happened instead.

_Attach images/videos if possible. These can be helpful in solving the issue._

Can't see comments on Galaxy Tab S7+

**Comment by VancedOfficial** [comment]
You have disabled them from the ad settings. Don't toggle settings if you don't know what happens from them.
