### ISSUE TITLE
[Bug] Suggestions Feed Missing Profile Pictures

### ISSUE THREAD

**Issue by addedsomewater** [YTVanced/Vanced#277]
**Bug description**
When watching a video, if you scroll down to the suggested videos feed, profile pictures are missing next to the channel name. In contrast, the default YouTube app has this feature. I'd imagine the absence of this feature is a bug.

**Variant**
NonRoot: Yes
Root: No

**Vanced version**
15.43.32 - Build - 01.47.00

**Android version**
Android 8.0 - Oreo

**Device**
Samsung Galaxy S7

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2. Select any video
3. Scroll down to the video suggestions and observe how channel profile pictures are missing.

Problem:
![Screenshot_20201215-203757](https://user-images.githubusercontent.com/63992620/102306232-99607d00-3f16-11eb-880a-760f286d628d.jpg)

Expectation:
![Screenshot_20201215-203615_YouTube](https://user-images.githubusercontent.com/63992620/102306258-aed5a700-3f16-11eb-86ea-f76c88568d32.jpg)

**Comment by Ali-Nazlier** [comment]
They are not missing for me. That's weird.
