### ISSUE TITLE
Casting problem to chromecast from YTV in miui 11

### ISSUE THREAD

**Issue by subrata82** [YTVanced/Vanced#28]
![Screenshot_2020-09-11-22-30-01-708_com vanced android youtube](https://user-images.githubusercontent.com/71309213/93171383-9eab0180-f746-11ea-9fca-b4c26c6af3b6.jpg)
In miui 11, YTV installed to most updated version in non-root poco f1 ( through YTV manager).  But, when tried to cast to chromecast it says "there is a problem in connecting to speakers". It was found the ytv created 2 casting speakers list automatically. All other cast enabled softwares show these 2 custing sources, when YTV uninstalled, resumed to single cast source. 
Please help.

**Comment by weirdal3333** [comment]
This looks like it's an issue with how youtube casts to a smartspeaker.
When I try to cast to my google home, it sometimes complains that you need youtube premium to cast, shows this message, or (rarely) skips the current song and starts playing, until it realizes about 2 minutes later that I'm trying to cast a song, and then it either starts playing an ad or disconnects from the google home.

**Comment by KevinX8** [comment]
This is unrelated to vanced as vanced microg handles casting
