### ISSUE TITLE
[Bug] Video mini player not find functioning or selectable

### ISSUE THREAD

**Issue by outdoorsdev** [YTVanced/Vanced#285]
**Bug description**
When watching a video in vanced and then moving to another app or home screen, the miniplayer is positioned out of the normal space.

It isn't selectable and hides completely when touched. It can't be selected and when double tapped or single tapped it disappearssl. Sound still plays but to watch the video you have to open the app again.

See video

**Variant**
NonRoot: Yes
Root: No

**Vanced version**
15.43.32 - Build - 01.47.00

**Android version**
Android 11
OxygenOS 11.0.5.6.KB05BA

**Device**
OnePlus 8T

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2. Click on a video
3. minimise app
4. Mini player is hidden at bottom right
5. When tapping it hides but still plays
6. Can't select to make full screen or keep on top
7. Can't get back to video without reopening app

See video here
https://streamable.com/8v4l5b

**Comment by milindgoel15** [comment]
Pip bug is either system side or Google side.
