### ISSUE TITLE
[two buttons overlapping] idk what one of the buttons is

### ISSUE THREAD

**Issue by TooneyTurkey** [YTVanced/Vanced#293]
**Bug description**
The advanced player settings thing is under the x button when you swipe up

**Variant**
NonRoot: Yes
Root: No

**Vanced version**
15.43.32 - Build - 01.47.00

**Android version**
Android 10 - oct release

**Device**
Google pixel 2

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2. Click on any video
3. swipe up

**Expected behavior**
The button should go away or be next to the x not under it

_Attach images/videos if possible. These can be helpful in solving the issue._
![Screenshot_20201228-174138](https://user-images.githubusercontent.com/66298544/103249530-539fad80-4935-11eb-8822-7bf99c0d4c0e.png)

**Comment by gghhkm** [comment]
@TooneyTurkey 
![tfahgdxhgfcbhff](https://user-images.githubusercontent.com/72711094/103254292-b8b5cc00-4952-11eb-9cbc-a188bfb74bb8.jpg)

**Comment by TooneyTurkey** [comment]
Oh ok thanks foe putting up with my stupidity
