### ISSUE TITLE
[Bug] Chromecast icon not showing

### ISSUE THREAD

**Issue by OwO-tism** [YTVanced/Vanced#295]
**Bug description**
Both on the YT homepage and while watching videos there is an icon at the top allowing you to cast videos onto your TV. In Vanced this icon is missing for me, so I have to go through the settings. This still works just fine but gets a bit tedious if you do it a lot.

**Variant**
NonRoot: Yes
Root: No

**Vanced version**
15.43.32 - Build - 01.47.00

**Android version**
Android 10 QKQ1.190825.002

**Device**
Xiaomi Mi Note 10

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2. Icon is missing at the top
3. When opening any video the icon is missing aswell

**Expected behavior**
The Icon should be visible by default afaik, whether a suitable device is near or not.

![PicsArt_12-29-10 27 55](https://user-images.githubusercontent.com/56203839/103317566-d145e500-4a2b-11eb-9e1e-23d86f60dc1d.jpg)

**Comment by Hyperboraeer** [comment]
Same here. It's a bug. Because I have Chromecast icon enabled in Layout settings of Vanced. But the Chromecast icon is still not showing. If I remember correctly it used to show, but then it vanished some time.

**Comment by OwO-tism** [comment]
I did some experimenting, for me the issue fixed itself when I turned it off and back on, then doing a full phone restart. Not sure if I did anything else that fixed it or why the bug appeared in the first place, but that worked for me

**Comment by Hyperboraeer** [comment]
That's weird. Unfortunately it doesn't work for me.

**Comment by ochen1** [comment]
Similar issue to #265

**Comment by Vendicated** [comment]
Should be fixed in the latest version

**Comment by adWroc** [comment]
I have the same problem, the latest version 16.02.35 B 01.49.00
