### ISSUE TITLE
[Bug] Chrome will not open vanced for youtube links

### ISSUE THREAD

**Issue by Skoooz** [YTVanced/Vanced#296]
**Bug description**
Chrome mobile browser will not open youtube links by default. It WILL use vanced if you scroll down to the video section in search results. It WILL NOT use vance if you click on the video tabs and click any of the search results. It WILL use vanced if you enable desktop mode. It WILL use vance if you log out of your account in chrome.

**Variant**
NonRoot: Yes
Root: No

**Vanced version**
15.43.32 - Build - 01.47.00

**Android version**
Android 10.0

**Device**
Samsung Galaxy A71

**Steps to Reproduce**
1) Open Chrome browser
2) Search for anything
3) Click "Video" tab
4) Click any of the search results
5) Test with other variations mentioned above

**Expected behavior**
Chrome mobile browser will not open youtube links by default. It WILL use vanced if you scroll down to the video section in search results. It WILL NOT use vance if you click on the video tabs and click any of the search results. It WILL use vanced if you enable desktop mode. It WILL use vance if you log out of your account in chrome.

**Comment by gghhkm** [comment]
That's a problem with chrome (and really Browser as a whole) not with Vanced, browser rarely open/direct links to other apps (they only really like to open them) Vanced can't do anything if the browser does send the link over to it.

**Comment by Skoooz** [comment]
> 
> 
> That's a problem with chrome (and really Browser as a whole) not with Vanced, browser rarely open/direct links to other apps (they only really like to open them) Vanced can't do anything if the browser does send the link over to it.

i tried firefox and it works, but i just cant make it work with chrome no matter what i do, i tried chrome beta chrome devs and even canary, none of them work, there is no chrome://urls that works too, i just cant make it work.

Is there a fix for it or my only option is to use other browsers?

**Comment by gghhkm** [comment]
> > That's a problem with chrome (and really Browser as a whole) not with Vanced, browser rarely open/direct links to other apps (they only really like to open them) Vanced can't do anything if the browser does send the link over to it.
> 
> i tried firefox and it works, but i just cant make it work with chrome no matter what i do, i tried chrome beta chrome devs and even canary, none of them work, there is no chrome://urls that works too, i just cant make it work.
> 
> Is there a fix for it or my only option is to use other browsers?

You're going to have to use a different browser, you can try one's that are based on chrome e.g. Brave, Bromite, Chromium, Opera, ect. But you'll have better luck with other browsers like Firefox, Fennec, IceCat. You can even try ones that aren't Based on Firefox or Chrome, although you'll have a harder time finding them and I don't know any so you'll have to look on your own.

**Comment by KevinX8** [comment]
The issue is clearly with chrome and not the app, the app cannot force Chrome to use it.

**Comment by 0100hem** [comment]
funny that chrome monopolizes youtube links to open in either youtube app or the browser itself while forwarding links in video description to vanced even if not leading to a youtube video

**Comment by ismail8t5** [comment]
Solution is here
https://youtu.be/lgBdb461VHc

**Comment by leopucci** [comment]
Didn't worked for me on OnePlus 5. Even after changing on instant apps config, chrome video opens on YouTube.
What's I am doing is to be logged in on vanced so the video shows on history. So I open normally with YouTube, then go to vanced and the video is there.

**Comment by putrawahh** [comment]
> Solution is here https://youtu.be/lgBdb461VHc

this soulution worked for me, and the cause is different links generated by search result depend on if you logged in or logged out on google account in chrome app

here is one example
if you logged in, the search result goes like this:
https://www.google.com/search?q=chasm+secret+entrance&oq=chasm&aqs=chrome.2.0i355i512j46i512j69i59j0i512l4j46i512j0i512j0i271.1604j0j1&client=ms-android-xiaomi-rvo3&sourceid=chrome-mobile&ie=UTF-8#

if you logged out, the search result goes like this:
https://www.google.com/url?sa=t&source=web&rct=j&url=https://m.youtube.com/watch%3Fv%3Dnap2hJCpTkQ&ved=2ahUKEwi9_MqZ1aP7AhX6jdgFHdw3Dl4QwqsBegQIChAF&usg=AOvVaw1hYjmIPh2sIGt4RmQUpFvF

both of them open the same youtube video, but the weird thing is the first link never failed to open in official yt app.

so is there anyway to make yt vanced to disguise as the official one?

**Comment by TURB042O** [comment]
> Solution is here https://youtu.be/lgBdb461VHc

https://github.com/TeamVanced/Vanced/issues/1800#issuecomment-1324824649

and 

https://github.com/TeamVanced/Vanced/issues/1800#issuecomment-1324832976

and my solutions
