### ISSUE TITLE
[Idea] share video with timestamp

### ISSUE THREAD

**Issue by eldon97** [YTVanced/Vanced#299]
add an option to share(copy link) with a timestamp. I mostly watch youtube at my phone and often I want to share the link with a timestamp to my friend via chatting app. it will be annoying if i need to go to my pc only for getting the link, I know we can add this " ?t=#m##s" to the link, but it will be more convenient if vanced add the option copy link with the current timestamp, maybe in the share dialogue. thank you

**Comment by AinzTheSupremeOne** [comment]
Implemented in beta, wait for an update.

**Comment by shivasagarrao** [comment]
Duplicate of #206 
@VancedOfficial commented [here](https://github.com/YTVanced/Vanced/issues/284#issuecomment-750256619) regarding this issue.

**Comment by Vendicated** [comment]
Added. Make sure to enable it in Vanced Settings > Misc
