### ISSUE TITLE
New bug I'm facing after updating the vanced apk

### ISSUE THREAD

**Issue by maradock101** [YTVanced/Vanced#3]
so I updated the vanced apk to the latest version(15.33.34) and after updating it, I'm not able to open the app.It force stops and doesn't responds even after reinstalling the app. HERE'S thr proof-
![Screenshot_20200903-143521_One UI Home](https://user-images.githubusercontent.com/70692368/92095029-c5864100-edf2-11ea-854d-057657b938a0.jpg)

**Comment by X1nto** [comment]
Did you uninstall microg?

**Comment by VancedOfficial** [comment]
Closing because no reply.
