### ISSUE TITLE
[Bug] Vanced crash at startup

### ISSUE THREAD

**Issue by Zarros** [YTVanced/Vanced#300]
**Bug description**
Vanced will crash randomly, when browsing video or at startup, no matter how i install vanced and microG (First or second / root or nonroot).
Support instructions give no solution.
Can you check the log attached ?

[logcat_12-30-2020_10-07-36.txt](https://github.com/YTVanced/Vanced/files/5759279/logcat_12-30-2020_10-07-36.txt)

**Variant**
NonRoot: Yes
Root: No

**Vanced version**
15.43.32 - Build - 01.47.00

**Android version**
Android 8.00

**Device**
Samsung Galaxy S7

**Steps to Reproduce**
Open YouTube Vanced
Wait some secondes or browse videos on the main screen.
App crash.

**Comment by Zarros** [comment]
Hi, any feedback ?
Thanks in advance

**Comment by X1nto** [comment]
Can you grab logs using ADB instead of whatever app you're using because logcat is incomplete

**Comment by Zarros** [comment]
Xposed was causing vanced crashes. I uninstalled it, and everything is OK. (Thanks Kevinx8 on discord)
