### ISSUE TITLE
[Bug] Search History 

### ISSUE THREAD

**Issue by Kyoo01** [YTVanced/Vanced#301]
**Bug description**
The search history doesn't add and update. Videos I already watched keeps showing up as video recommendations. I tried reinstall the app a few times but that doesn't fix the problem. It could be a bug or a problem with the ROM that I put on my phone. Either way its better to report this as a bug because I dont really think it has something to do with the ROM. 

**Variant**
NonRoot: No
Root: Yes

**Vanced version**
15.43.32 - Build - 01.47.00

**Android version**
Android 10

**Device**
Samsung Galaxy S8

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
3. ....

**Expected behavior**
It should add videos I already watched in my history, but it doesn't. It keeps showing up as recommendation every time i start the App.

**Comment by VancedOfficial** [comment]
You probably have some adblock which is blocking the watch history url.

https://telegra.ph/Troubleshooting-for-vanced-03-19#History

**Comment by Kyoo01** [comment]
Yeah that was the problem. Forgot i had that. Thx for the help

**Comment by Jolubeat** [comment]
Hi.
Indeed, I had Adguard installed for a couple of days, but not anymore. Already updated YouTube vanced to the newer version, and still don't get the YouTube history bug fixed.
Should I do a fresh Install of vanced, or a complete system restore might be the only way?
Thanks

**Comment by milindgoel15** [comment]
If adguard modified ur hosts in any way and u didn't rolled back those changes, then roll back those changes. Otherwise start fresh

**Comment by Audition-CSBlock** [comment]
If you ever gain root access, then you can use termux or connect it to your pc with `adb shell` and cd to the hosts file and delete/modify it to default.
