### ISSUE TITLE
The Vanced version change to the stock in a while

### ISSUE THREAD

**Issue by Thonamy1** [YTVanced/Vanced#303]
Hello I'm Thonamy
I'm here to tell u that I have a issue with the root version of YouTube Vanced because when I install it is all good but when pass some minutes it changes to the stock version 
That's why I don't use the root version 
Can u help me?

PD: if it serves to u 
My device: Moto G5 (Cedric) 
                    Android 9 (Resurrection Remix Rom) Unofficial

**Comment by Thonamy1** [comment]
I hope u can help me

**Comment by gghhkm** [comment]
> I hope u can help me

It's possible that it's just Google play is auto updating it, you can try disabling auto updates in Google play; however if this isn't enough use the "Detach" magisk module.

**Comment by reconman** [comment]
I thought I did something wrong, but this thing is persistent. I've only had this problem since installing an Android update including Security Patch 2020.11.

Before that, disabling automatic updates was enough.

First I installed Youtube Vanced via TWRP like before the system update. After a few days it was reverted back to stock.

Then I installed Youtube Vanced via Magisk and detached it from the playstore with the Youtube Vanced Detach module. After a few days, stock is back.

I've got an OnePlus 6 with OxygenOS 10.3.7.

**Comment by gghhkm** [comment]
> I thought I did something wrong, but this thing is persistent. I've only had this problem since installing an Android update including Security Patch 2020.11.
> 
> Before that, disabling automatic updates was enough.
> 
> First I installed Youtube Vanced via TWRP like before the system update. After a few days it was reverted back to stock.
> 
> Then I installed Youtube Vanced via Magisk and detached it from the playstore with the Youtube Vanced Detach module. After a few days, stock is back.
> 
> I've got an OnePlus 6 with OxygenOS 10.3.7.

There's currently nothing you can do on OxygenOS, trust me I've already tried just about everything I could think of.

**Comment by reconman** [comment]
I'm just confused as where that stock Youtube version comes from, as /system/app still contains the data from Vanced.

**Comment by gghhkm** [comment]
> I'm just confused as where that stock Youtube version comes from, as /system/app/Youtube still contains the data from Vanced.

Root Vanced installs ontop of stock via mounting to the stock YouTube location; it can't do that if there is no youtube so it installs stock YouTube automatically.
If the mount process fails then you're left with stock.

**Comment by gghhkm** [comment]
https://github.com/YTVanced/VancedManager/issues/501#issuecomment-824800438

**Comment by milindgoel15** [comment]
Adding more alternative solutions directly here to avoid people making duplicate issues again.

[Please read how to detach root variant from play store guide here](https://telegra.ph/Troubleshooting-for-vanced-03-19#Detach)

**Comment by reconman** [comment]
> Then I installed Youtube Vanced via Magisk and detached it from the playstore with the Youtube Vanced Detach module. After a few days, stock is back.

Detaching didn't work for me, I'm running non-root now.

**Comment by czerwinski76** [comment]
Bug description:
Youtube Vanced always rollback to stock Youtube apk.
I don't know why it does always do that.
Removing Youtube Vanced every 3 days and reinstalling it does the trick.

Have you read vanced guides already?
Yes

Variant:
Rooted mobile

Vanced version:
v17.03.38 (latest)

Link used to download vanced:
Official YouTube Vanced Manager app.

Android version:
Android 11

Device:
Samsung Galaxy S20 FE
One UI 3.1

Steps to Reproduce
Normal usage of the smartphone.
I don't know why it happends.

**Comment by milindgoel15** [comment]
@czerwinski76 read the solution given in this particular issue. 

It's why i linked this issue to your issue so that you read what had been discussed or what are the possible solutions.

**Comment by czerwinski76** [comment]
@milindgoel15 Thank you for your help but none avec the solutions here worked for me.

**Comment by reconman** [comment]
For me only switching to a new phone helped. OnePlus 6 had this issue, 9 does not.

**Comment by czerwinski76** [comment]
> For me only switching to a new phone helped. OnePlus 6 had this issue, 9 does not.
Does you have a stock rom or a cooked one ?

**Comment by reconman** [comment]
> Does you have a stock rom or a cooked one ?

Stock with Magisk.

**Comment by milindgoel15** [comment]
> @milindgoel15 Thank you for your help but none avec the solutions here worked for me.

if using temifi or any detach methods didn't work for you, then ig use the non-root version.

**Comment by czerwinski76** [comment]
> > Does you have a stock rom or a cooked one ?
> 
> Stock with Magisk.

Same here.

**Comment by czerwinski76** [comment]
> > @milindgoel15 Thank you for your help but none avec the solutions here worked for me.
> 
> if using temifi or any detach methods didn't work for you, then ig use the non-root version.

Where can I find the latest non-root version please ?
I don't find it on the official website. Just Vanced Manager. 

v15.05.54 isn't compatible with my device.

**Comment by milindgoel15** [comment]
Vanced manager provides both root and non-root. If you are on root installer, switch to non-root from vanced settings settings.

> Where can I find the latest non-root version please ?

**Comment by gghhkm** [comment]
> Vanced manager provides both root and non-root. If you are on root installer, switch to non-root from Vanced **_manager_** settings.

**Comment by czerwinski76** [comment]
> Vanced manager provides both root and non-root. If you are on root installer, switch to non-root from vanced manager settings.
> 
> > Where can I find the latest non-root version please ?

Thank you again.

3 points menu on the top right corner on Vanced Manager > Parameters > Variant > nonroot
