### ISSUE TITLE
[Idea] Un-Delayed bluetooth audio.

### ISSUE THREAD

**Issue by pi3trek** [YTVanced/Vanced#304]
**Description**
I had this idea for a while now, but, what if: you could play the audio before it's supposed to be played to eliminate the delay from some bluetooth earphones/headphones?

**Comment by KevinX8** [comment]
That would be almost impossible to sync up as you would have to predict the delay rather than already know what it is and just compensate for it (as when delaying the video it can be done after the fact but audio has to be "fast forwarded" in advance)

**Comment by pi3trek** [comment]
I thought about it as a calibration tool to set a set value of a delay which would make the audio offset when connecting to a specific bluetooth device (mainly cheap tws earphones) or when the bluetooth is turned on. The more i think about it the less sense it makes since it would benefit like 2% of the users and would be a hell of a nightmare to code i imagine. Anyway sorry for wasting your time and thanks for the amazing work you guys out out. ❤️
