### ISSUE TITLE
[Idea] Advanced Profanity Filter support for YT Vanced

### ISSUE THREAD

**Issue by CreeperPookie** [YTVanced/Vanced#306]
**Description**
Now, I know this is a near-impossible thing to do; one is a chrome extension written in JS and Vanced is written in Java/Kotlin. But if there was a way to filter videos and audio muting, it would be so GREAT!

**Comment by gghhkm** [comment]
I think you'd have better luck getting SponsorBlock to implement something like this into their API and then wait for it to go downstream into Vanced.

**Comment by CreeperPookie** [comment]
Well SponsorBlock and APF are 2 completely different extensions, so it's unlikely for them to add that.

**Comment by gghhkm** [comment]
> Well SponsorBlock and APF are 2 completely different extensions, so it's unlikely for them to add that.

Not really tbh, they do simulator things they just go about it differently.
 it'd be way easier to implement if it's added into SponsorBlock and you'd have the added benefit of having the users upload segments as; let's say 'profanity' and it would use the already available and implemented SponsorBlock API and from there I'd be easy to have it skip over the curse word entirely or possibly mute it in Vanced.

**Comment by CreeperPookie** [comment]
Oh true! What about for custom words though; like a word one person might consider offensive but others don't?
