### ISSUE TITLE
[Idea] Block Channels

### ISSUE THREAD

**Issue by leodoi3** [YTVanced/Vanced#308]
**Description**
 I see many annoying clickbate channels and I just want to completely hide them , in homepage, search, recommended, etc. 

An option to block videos via: Video Title / Channel Name / Channel ID / Video ID
Using normal text and regex.

[Blocktube](https://github.com/amitbl/blocktube) is a webextension that does everything I mentioned. Maybe you can create an extension on Vanced?

**Comment by OlegLxx** [comment]
Up!
I support! A very necessary feature:: Channel blacklist.
Who might need it?
- For yourself. People don't want to see annoying content. Less nervous.
- Monitor children who consume any content.
- Control of elderly parents who are susceptible to propaganda.

The standard functionality of the application already has the ability to block a user. This is the only feature that works for commentators. I think that developers can access this list and, based on it, exclude certain channels from the search results.

![Screenshot_2021-06-13-18-24-39-076_com vanced android youtube](https://user-images.githubusercontent.com/73443706/121813976-496d3380-cc77-11eb-9a8e-e69efaf22da8.jpg)
