### ISSUE TITLE
[Bug] Screen overlapping

### ISSUE THREAD

**Issue by mukul01bahediarj** [YTVanced/Vanced#309]
when i play a video, another screen freezes over the top of main screen. I need to manually click on cross sign to get rid of it.

![Screenshot_20210102-113607~2](https://user-images.githubusercontent.com/54141509/103451860-43018580-4cef-11eb-9110-cc04cf784803.png)

**Comment by gghhkm** [comment]
Turn off accessibility player.

**Comment by mukul01bahediarj** [comment]
Thanks gghhkm! you saved me✌️
