### ISSUE TITLE
bring back square miniplayer [Idea]

### ISSUE THREAD

**Issue by homamgamer** [YTVanced/Vanced#31]
I HATE the rectangular mini player, it's so annoying
youtube vanced had the square mini player as a feature, until version 15
why would you remove a feature you added?
I would love it if the new version of youtube vanced had the old square miniplayer (not tablet miniplayer)
Examples:

**old one (good)**
![photo_2020-09-17_02-51-55](https://user-images.githubusercontent.com/38010452/93403675-e473e100-f890-11ea-9993-d82a936ff32c.jpg)

**New one (nah)**
![photo_2020-09-17_02-39-53](https://user-images.githubusercontent.com/38010452/93403710-fce3fb80-f890-11ea-9f5f-2da55e834ef9.jpg)

**Comment by KevinX8** [comment]
We didn't add it, it was already in the code and we just added a toggle for it.

**Comment by homamgamer** [comment]
> We didn't add it, it was already in the code and we just added a toggle for it.

And now the toggle is gone 
just the tablet mode which is not the same

**Comment by VancedOfficial** [comment]
References to that old miniplayer are gone as well so I'm assuming the whole player is removed by Google.
