### ISSUE TITLE
[Bug] click Youtube link doesn't redirect to vanced

### ISSUE THREAD

**Issue by eldon97** [YTVanced/Vanced#310]
**Bug description**
so here's the thing. i disable youtube app because i never use it again, instead i always use vanced. so before disabling the youtube app, sometimes when i browse something in google and click at youtube link, it redirects to the youtube app, not vanced. I don't want that, i want the youtube link always redirec me to vanced. in order to do that, i think disabling the youtube app could work. it turns out, it isn't. after disabling the youtube app, when i click the youtube link, sometimes it redirects me to the play store of the youtube app, sometimes it's open the youtube link in the browser, sometimes it redirects me to the vanced.

**Variant**
NonRoot: Yes
Root: No

**Vanced version**
15.43.32 - Build - 01.47.00

**Android version**
Android 10

**Device**
Xiaomi Redmi Note 7

**Steps to Reproduce**
Steps to reproduce the error:
1. Open chrome/google app
2. browse something which the result will be some videos or go straight to videos tab
3. click on the youtube link

**Expected behavior**
always redirected to vanced

**Comment by Marooned-MB** [comment]
Had similar issue. Clear YouTube (original) data helped in my case.

**Comment by eldon97** [comment]
> Had similar issue. Clearing YouTube (original) data helped in my case.

thanks, it works. i clear all data, uninstall update, and disable it..
