### ISSUE TITLE
[Idea] Option to change the default tab that opens first

### ISSUE THREAD

**Issue by chokingyou** [YTVanced/Vanced#311]
Hello!
Could there be added an option in the YTVanced settings to **change the default tab** that opens first when the app is opened?
For example, I would be glad to see my "**Library**" or specifically my "Watch later" playlist instead of the "Home" tab with those addictive YT suggestions :)

I find myself too often lost scrolling YT suggestions (and adding some of them to the infinite "Watch later" list, as if I will ever have a 1+ year of spare time to watch all that), even when I initially opened YT to just find and watch something quite specific.

(There was a similar suggestion #184 by @reagag which was also aimed at limiting distractions.)

Thank you in advance,
—Maksim

**Comment by TrianguloY** [comment]
If you can create a shortcut to open this url :

https://m.youtube.com/playlist?list=WL

It will directly open YouTube in the watch later playlist.

**Comment by chokingyou** [comment]
> If you can create a shortcut to open this url :
> https://m.youtube.com/playlist?list=WL
> It will directly open YouTube in the watch later playlist.

Thank you, that's actually a good idea (although I couldn't find yet if there is a possibility to create a custom shortcut for a specific URL on the desktop on my KeyOne, but I'm on it).

Also, I found that there are already similar shortcuts created by the app itself. They lead to Search, Subscriptions, and Explore — but, alas, not to Watch later.
Probably it would be even easier for the developers to add an automatically created Watch Later shortcut, instead of adding an option to the Settings menu.

**Comment by chokingyou** [comment]
I don't think this issue should be closed yet.
There is still a request to the developers for either
1. add an option in the YTVanced settings to change the default tab that opens first when the app is opened (e.g. to "Library" or specifically to "Watch later" playlist instead of the "Home" tab)
or
2. add automatically created "Watch Later"/"Library"/etc. Android shortcuts that would lead directly to the respective tabs on opening.

**Comment by aruku** [comment]
> > If you can create a shortcut to open this url :
> > https://m.youtube.com/playlist?list=WL
> > It will directly open YouTube in the watch later playlist.
> 
> Thank you, that's actually a good idea (although I couldn't find yet if there is a possibility to create a custom shortcut for a specific URL on the desktop on my KeyOne, but I'm on it).
> 
> Also, I found that there are already similar shortcuts created by the app itself. They lead to Search, Subscriptions, and Explore — but, alas, not to Watch later.
> Probably it would be even easier for the developers to add an automatically created Watch Later shortcut, instead of adding an option to the Settings menu.

Do you mean the activities with _shortcuts_?

I would love this feature too.

**Comment by chokingyou** [comment]
> Do you mean the activities with _shortcuts_?
I think yes.
Currently the list of available "Shortcuts" on my BlackBerry Launcher contains these three:
![Screenshot_20210531-021901](https://user-images.githubusercontent.com/28399054/120123563-34dd6580-c1b8-11eb-8142-d69d2387ad3d.png)
Would be great if the developers added some more, including "Watch Later".

> I have thought of using links as shortcuts in the launcher, but while clicking the one @TrianguloY used opens the app, when I add it to the launcher it doesn't.
I managed to make a custom shortcut containing this URL with a special app:
https://play.google.com/store/apps/details?id=rk.android.app.shortcutmaker
Hope this helps.

**Comment by aruku** [comment]
> > Do you mean the activities with _shortcuts_?
> > I think yes.
> > Currently the list of available "Shortcuts" on my BlackBerry Launcher contains these three:
> > ![Screenshot_20210531-021901](https://user-images.githubusercontent.com/28399054/120123563-34dd6580-c1b8-11eb-8142-d69d2387ad3d.png)
> > Would be great if the developers added some more, including "Watch Later".
> 
> > I have thought of using links as shortcuts in the launcher, but while clicking the one @TrianguloY used opens the app, when I add it to the launcher it doesn't.
> > I managed to make a custom shortcut containing this URL with a special app:
> > https://play.google.com/store/apps/details?id=rk.android.app.shortcutmaker
> > Hope this helps.

Thank you! That app did it, and then I realized the one I've been using for similar stuff, _More Shortcuts_, also allows this.
I wonder what the actual difference with the regular links from Chrome is, since I don't select Vanced when creating it.

Now the only missing piece is getting it to open links from Chrome, Assistant, etc. I have tried everything: setting Vanced to always open the links, YouTube to never, uninstalling YT's updates, stopping, and disabling it, and restarting the phone, but nothing has worked.
Looks like this is only possible with root.

**Comment by chokingyou** [comment]
> Thank you! That app did it, and then I realized the one I've been using for similar stuff, _More Shortcuts_, also allows this.
> I wonder what the actual difference with the regular links from Chrome is, since I don't select Vanced when creating it.
Great! :)

> Now the only missing piece is getting it to open links from Chrome, Assistant, etc. I have tried everything: setting Vanced to always open the links, YouTube to never, uninstalling YT's updates, stopping, and disabling it, and restarting the phone, but nothing has worked.
> Looks like this is only possible with root.
This is actually strange, I have no problems with YT Vanced opening links from browser or e-mails, and my phone isn't rooted (in fact, you just can't root a BlackBerry KeyOne). I have the original YouTube app disabled.

**Comment by aruku** [comment]
For anybody facing the same issue in the future: soon after I wrote that message, the OS started asking what to use when opening YT links no matter the source app. 
So I can't say for sure what actually did it, but you can always do everything and then wait a few hours, as I did.
