### ISSUE TITLE
[Bug] Can't upload videos on hauwei

### ISSUE THREAD

**Issue by ghost** [YTVanced/Vanced#312]
**Bug description**
So I got a bug where I can't upload 

**Variant**
NonRoot: Yes

**Vanced version**
Current 

**Android version**
Android 10

**Device**
Hauwei P20 Pro 

**Expected behavior**
Sometimes happen when I reinstall
. 

Proof with text it says:
No apps can perform this action.

**Comment by sam-cross** [comment]
"Current" is not helpful. Check your version. Is it working after updates?
