### ISSUE TITLE
[Idea] Disable YouTube notifications option

### ISSUE THREAD

**Issue by GKid94** [YTVanced/Vanced#314]
Add an option to disable the YouTube notifications and only leave the YouTube Vanced player background notification

**Comment by gghhkm** [comment]
You can already disable YouTube notifications in Device settings.

**Comment by GKid94** [comment]
@gghhkm But then you disable the background player notification too

**Comment by gghhkm** [comment]
> @gghhkm But then you disable the background player notification too

Nope, Vanced has it's own separate notifications.

**Comment by GKid94** [comment]
@gghhkm I disable it and I don't have the background player notification

**Comment by gghhkm** [comment]
> @gghhkm I disable it and I don't have the background player notification

https://discord.gg/rgwbXEaUCb
We'll help you there; it'll be much easier then doing it here.

**Comment by GKid94** [comment]
@gghhkm I'm already in the server
