### ISSUE TITLE
[Bug] Player Controls Won't Disappear

### ISSUE THREAD

**Issue by adebusayo** [YTVanced/Vanced#315]
Except when I'm watching in picture-in-picture, nothing I do can make the controls disappear. Tapping the blank/empty space is fruitless, messing with the accessibility changes yields nothing. As far as I know, no one else has this issue. 

This is my first time using YT Vanced, and I followed the site instructions and installed MicroG before YT Vanced as the manager required.

**Comment by gghhkm** [comment]
Disable Accessibility Player.
