### ISSUE TITLE
[Bug] replaceme

### ISSUE THREAD

**Issue by Nova985** [YTVanced/Vanced#319]
**Bug description**
Sometimes when I exit out of the vanced app and the miniplayer shows it it becomes invisible and I cannot see the miniplayer but I hear the audio in the background. if I find the miniplayer and tap on it the miniplayer shows up again and it isnt invisible

**Variant**
NonRoot: Yes
Root: No

**Vanced version**
15.43.32 - Build - 01.47.00

**Android version**
Android 9.0 - Pie

**Device**
Samsung Galaxy j3 orbit

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2. Click on a video and play it
3. Exit the app by tapping on the home button

**Expected behavior**
I expected the miniplayer to be visible all the time but it turned invisible at certain times

**Comment by KevinX8** [comment]
Stock YouTube/Android issue
