### ISSUE TITLE
[Bug] sponsorblock skips apply to youtube short videos

### ISSUE THREAD

**Issue by abdurrahman101** [YTVanced/Vanced#320]
**Bug description**
Whenever a video with flagged sponsored segments is played, and sponsorblock is enabled, clicking on a recommended short video/story will open the short video in the viewer, but the flagged segments in the original video will apply to the short video and so it'll skip through it when it shouldn't

**Variant**
NonRoot: Yes

**Vanced version**
15.43.32 - Build - 01.47.00

**Android version**
Android 11

**Device**
Google Pixel 4 XL

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app, with sponsorblock on
2. Click on a video that should have a flagged sponsored segments near the beginning (for example, any video from pewdiepie with the intro)
3. scroll down below the comments to a suggested short video or story
4. the short video will receive the same skip from the pewdiepie video 

**Expected behavior**
short videos should not receive the skip from the original video's flagged sponsorblock segments

**Comment by Vendicated** [comment]
The sections are provided by [sponsorblock](https://github.com/ajayyy/SponsorBlock), not us. Additionally, you can select which categories you want to skip in the Sponsorblock settings menu
