### ISSUE TITLE
[Idea] an ACTUAL account block button

### ISSUE THREAD

**Issue by MilkyDood64** [YTVanced/Vanced#323]
**Description**
Can there be a proper channel block button implemented? So a channel's reccomends don't pop up on my feed? Asking because someone's gore thumbnail keeps popping up on my reccomends and reporting does nothing...

**Comment by TrianguloY** [comment]
When pressing the three dots in the recommendation a "don't recommend this channel" or similar wording should appear. I've been using that option several times with perfect results, sometimes it requires a second time but after that that channel is gone from all the recommendations (at least for several months).

Does it not work for you?

**Comment by leodoi3** [comment]
I requested an issue similar to this #308 . But mine deals with videos where "don't recommend this channel" doesn't appear. Like in Explore tab.
