### ISSUE TITLE
[Bug] Freezing On Android 10

### ISSUE THREAD

**Issue by CarterTheHacker99** [YTVanced/Vanced#326]
**Bug description**
Video Hangs On Android 10

**Variant**
NonRoot: Yes
Root: No

**Vanced version**
15.43.32 - Build - 01.47.00

**Android version**
Android 10.0 - Go Edition

**Device**
Onn Android Tablet 6 inch

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2. Open video

**Expected behavior**
Video would play but it hangs

_Attach images/videos if possible. These can be helpful in solving the issue._
https://youtu.be/WPnN83Gw390

**Comment by Avinash-Dwivedi** [comment]
Same issue on One UI 2.0 also, after this issue happens other apps are not able to play any media as well...
