### ISSUE TITLE
[Idea] Open a sidebar (such as Notifications or Subscriptions) while playing a video

### ISSUE THREAD

**Issue by dontspammeplz** [YTVanced/Vanced#329]
Hello,
I frequently like to switch what video I'm watching when I'm playing them in fullscreen mode. Unfortunately, my phone (OnePlus 6T) is relatively narrow and it is difficult to scroll in my notifications list. (Moving into portrait mode is possible but a little annoying, especially for lots of videos.) Would you be able to add a slide-out sidebar for notifications/subscriptions? It would be much appreciated, and make switching videos a lot easier. I've included some rough mockups if my description above was a little unclear:
![unopened](https://user-images.githubusercontent.com/67651490/103943539-1ed6e780-50e7-11eb-8de4-e50ff4d2809f.png)
![opened](https://user-images.githubusercontent.com/67651490/103943544-21394180-50e7-11eb-804e-313ce519dd5b.png)

**Comment by ramishsaeed** [comment]
Great idea
