### ISSUE TITLE
A "disable update reminder" switch would be nice.

### ISSUE THREAD

**Issue by alexceltare2** [YTVanced/Vanced#33]
I keep getting the "A new YouTube version is available" popup whenever I open the app and I don't want to update. This is akin to an ad and would like a feature where this stops showing up as even if I click the Ignore button is still showing up.

**Comment by alexceltare2** [comment]
Rename

**Comment by incIined** [comment]
this is a serverside thing, i dont think vanced can do anything about it

**Comment by alexceltare2** [comment]
You mean Vanced can't block update checks the same way it blocks ads?

**Comment by KevinX8** [comment]
YouTube actively hides the ability to block it each update, not sure if playing their cat and mouse game is worth it
