### ISSUE TITLE
[Idea] "Add to queue" feature should be added to app

### ISSUE THREAD

**Issue by ramishsaeed** [YTVanced/Vanced#333]
**Description**
The feature is so useful. It's on desktop site of YouTube but not in the mobile app. Developers should consider including this option. It's like a playlist but in real-time. When I am watching informative/educational videos and wish to add videos on the go, I want to be able to queue them instead of playing every single video when the current one ends. Same can be said for songs depending on a person's mood

**Comment by Itsyahboidavid** [comment]
I +1 this feature. I think adding a queue option (similar to the casting queue option) would complete the features I use on the daily!

**Comment by Vendicated** [comment]
Cant' you just play the Watch Later playlist and add videos to watch later? This way they should automatically be played once the previous one ended. Once done just use the `Remove Watched Videos` button to clear it again

**Comment by ramishsaeed** [comment]
That's quite time consuming. And I have other videos that I want to watch
later.

**Comment by vogues** [comment]
This is a must have feature.

**Comment by BaptisteOrieuxDecathlon** [comment]
I +1 this feature :)
I would greatly appreciate this !

**Comment by hafizmuhmmadismail** [comment]
I need this

**Comment by milindgoel15** [comment]
Ask google to code this playlist mode for you all. We don't own YouTube!

**Comment by megamorphg** [comment]
This feature is there on desktop YouTube and on Chromecast already.... Hopefully Google will have it eventually on Android YouTube!
Until then Watch Later is the only option to us.
