### ISSUE TITLE
[Idea] Select where you want to launch the app to.

### ISSUE THREAD

**Issue by Itsyahboidavid** [YTVanced/Vanced#335]
**Description**
A nice feature would be if you could select which tab you want Youtube Vanced to open when launching the app. Similar to long pressing the icon on the phone homescreen and clicking "subscriptions" this feature would auto open selected tab every time. As an example someone that never browsers the "home" tab could choose "subscriptions" as there starting tab. To add onto this a [remove tabs] could be added so tabs like "explore" can be hidden (as @Hyperboraeer mentioned)

**Comment by Hyperboraeer** [comment]
I totally agree with you. Let's hope the devs will look into this suggestion.

**Comment by duradara** [comment]
You can already do this in both Vance's and normal YouTube since forever.  You just hold the icon,like you said, and then you hold the "subscription" popup and move it to the homescreen.

**Comment by gghhkm** [comment]
> **Description**
> A nice feature would be if you could select which tab you want Youtube Vanced to open when launching the app. Similar to long pressing the icon on the phone homescreen and clicking "subscriptions" this feature would auto open selected tab every time. As an example someone that never browsers the "home" tab could choose "subscriptions" as there starting tab. To add onto this a [remove tabs] could be added so tabs like "explore" can be hidden (as @Hyperboraeer mentioned)

You use a custom launcher that can do this, it's the only way and it's been available for all Android apps since a long time.

**Comment by Itsyahboidavid** [comment]
> You can already do this in both Vance's and normal YouTube since forever. You just hold the icon,like you said, and then you hold the "subscription" popup and move it to the homescreen.

Yeah I know that is possible, and is also what I've done. I'm thinking of launchers that don't support this for example using Kustom will not allow you to do this. It should be an easy fix to let people choose what tabs to have and not have and where the app will launch.
