### ISSUE TITLE
[Idea] [Request] "Proxy" settings in YT Music

### ISSUE THREAD

**Issue by alucard-alb** [YTVanced/Vanced#338]
**Description**
Hi, I'm from Bangladesh 🇧🇩
In here, Youtube Music still unsupported. Whenever I need to open YT Music, I have to connect to a VPN first. Which is not very time/battery/RAM efficient. 

I'm sure, among Vanced users, there are many people’s who are suffering this problem for ages.

So, can you guys please make an inbuilt "Proxy" setting in the Youtube Music app? It would be really helpful. 

Thanks in advance. ❤️🤞🏼

**Comment by AinzTheSupremeOne** [comment]
Just use Spotify lol. This request is probably never gonna be implemented because proxy/VPN service isn't mostly free and setting up a paid one would defeat the purpose of Vanced being free.

**Comment by AinzTheSupremeOne** [comment]
Android has a built-in proxy setting. Available with WiFi network settings and Mobile network apn settings. If you can't afford a VPN, you can try one of the lightweight clients and an open VPN server. There is a proxy app for Android too, called Shadowsocks.
