### ISSUE TITLE
[Bug] Swipe Controls and comments location bug

### ISSUE THREAD

**Issue by ar0177417** [YTVanced/Vanced#34]
Hello! I am on Samsung Tab A 
Since the 15.33.34 update the swipe Controls aren't working and the comments new location option is broken 
Plz fix this
Note: the swipe Controls were working fine before update

**Comment by incIined** [comment]
swipe controls don’t work if old comment location toggle is on

**Comment by ar0177417** [comment]
Old comment location is off

**Comment by mkamran67** [comment]
Tab S4 tried everything.  Same issue.

**Comment by HuFux** [comment]
Huawei MediaPad M5 10.8 Pro here and just updated today to the newest YTVanced version. Overall a BAD idea. I can confirm that the swipe gestures für brigthness as well as volume control do NOT work anymore. And this is NOT related to any comment location setting. So bug confirmed on my side too.

**Comment by HuFux** [comment]
> 
> 
> swipe controls don’t work if old comment location toggle is on

This fix is not working, see my post above.

**Comment by ar0177417** [comment]
Comments location toggle is also not working
Tried everything

**Comment by Moonlight63** [comment]
Same here on multiple devices.

**Comment by VancedOfficial** [comment]
Should be fixed in the 15.38.35 release. Open a new issue if not.
