### ISSUE TITLE
[Bug] Some videos seems to only show a black screen instead of the content

### ISSUE THREAD

**Issue by Cream733** [YTVanced/Vanced#340]
**Bug description**
A few videos seems to play but they only show a black screen rather than the content. It happens on a few videos and I have only recently encountered it. Other videos seems to work fine. And I have checked on stock youtube, and those videos seems to play fine on stock but on vanced they only show a black screen. 

[Please check this video for better understanding](https://cdn.discordapp.com/attachments/358967876193091584/799548433572691979/20210115_135144.mp4) 

**Variant**
NonRoot: Yes
Root: No

**Vanced version**
15.43.32 - Build - 01.47.00

**Android version**
Android 10

**Device**
Samsung Galaxy m11

**Expected behavior**
The video should play it's Content rather than just a plain black screen on videos

**Comment by Avinash-Dwivedi** [comment]
Isn't your issue similar to this: https://github.com/YTVanced/Vanced/issues/326
