### ISSUE TITLE
[Bug] Unable to send super chats, stickers or join membership (paid actions)

### ISSUE THREAD

**Issue by YanLobianchi** [YTVanced/Vanced#343]
**Bug description**
When I try to send a super chat, sticker in a livestream or join the membership, the message "This link cannot be opened." ("_Não é possível abrir este link_" in brazilian portuguese) is shown.

**Variant**
NonRoot: Yes
Root: No

**Vanced version**
15.43.32 - Build - 01.47.00

**Android version**
Android 10.0 - Q (MIUI 12)

**Device**
Xiaomi Pocophone F1

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2. Open a livestream
3. Try to send a super chat or sticker

**Expected behavior**
Let it be possible to send super chats, stickers or join the membership.

![Screenshot_2021-01-16-08-22-32-763_com.vanced.android.youtube.jpg](https://user-images.githubusercontent.com/24674211/104810725-62131380-57d5-11eb-9be2-6c45394f36da.jpg)

**Comment by KevinX8** [comment]
Microg which is what non root vanced depends on does not support payments at this time, make a PR/issue to the mainline repo to add support if you require or use root vanced.
