### ISSUE TITLE
Re-add intel variant

### ISSUE THREAD

**Issue by WWWWaaaaattttt** [YTVanced/Vanced#346]
**Description**

I frequently use vanced youtube installed on my chromebook. There was a variant for x86 chips and I manually installed it using adb on Crostini, but the latest version doesn't include this variant.

**Comment by KevinX8** [comment]
We include x86 libs in every update just use vanced manager?

**Comment by WWWWaaaaattttt** [comment]
@KevinX8 Vanced Manager won't work unless developer mode is enabled. I was trying to download it from https://www.mediafire.com/folder/g9usa0v3uvkoy

**Comment by KevinX8** [comment]
https://mirror.codebucket.de/vanced/ use this and get the splits you want
