### ISSUE TITLE
[Idea] Allow to backup data, to support downgrading

### ISSUE THREAD

**Issue by stdedos** [YTVanced/Vanced#347]
**Description**
In spirit of https://github.com/YTVanced/VancedManager/issues/348, I would like to be able to downgrade and keep my settings.

If not possible (or too complicated) to export all settings, I would like to be able to at least export Vanced-specific settings.

That could be used e.g. for migration too.

**Comment by smed79** [comment]
Backup/Restore will be a very useful feature.

**Comment by stdedos** [comment]
Hmmm ... interesting

**Comment by KevinX8** [comment]
We're not adding this lol just use another app to do it or adb

**Comment by smed79** [comment]
@KevinX8 

> use another app

Do you suggest an app to make a backup for noob user as me ?

**Comment by stdedos** [comment]
No - he's suggesting that I (we) manually hook the phone to a USB and run a command every time I (we) want to have the ability to downgrade cleanly.

**Comment by smed79** [comment]
Thank you for your answer.

**Comment by stdedos** [comment]
Actually - @KevinX8, it's impossible to do that via `adb backup`. All Vanced apps are returned with 47 bytes file.

**Comment by KevinX8** [comment]
> Actually - @KevinX8, it's impossible to do that via `adb backup`. All Vanced apps are returned with 47 bytes file.

Look up if ADB supports split APKs at all, Google probably were too lazy to add support, this can back them up just fine https://play.google.com/store/apps/details?id=com.aefyr.sai

**Comment by stdedos** [comment]
Do split apks have anything to do with `data` backup? 😕 
The apk/installation should be doable via the Vanced Manager "any time" I guess.

SAI does not support anything more than `apks`

**Comment by KevinX8** [comment]
If you're talking about data you'll have to look into this and see what Google applies to the XML https://developer.android.com/guide/topics/data/autobackup#include-exclude-android-11 and send us a fixed one
