### ISSUE TITLE
[Idea] Black splash screen for a black themed app version

### ISSUE THREAD

**Issue by TheGreySquare** [YTVanced/Vanced#348]
**Description**

Just a small suggestion

Maybe in the future updates you would be interested in replacing default grey splash screen with black status bar to black splash screen for a black themed app version, so that it would fit better

Good luck

Android 10, AOSP, v16.14.34 black

Mockup image vs Current splash screen:

![YTV – Black Splash Screen.png](https://user-images.githubusercontent.com/47947180/116170001-979d9600-a70e-11eb-8c5b-aad4ec404a40.png)
![YTV - Current Splash Screen.jpg](https://user-images.githubusercontent.com/47947180/116170036-aa17cf80-a70e-11eb-9773-1b55a6b79bb7.jpg)

**Comment by vrindavan** [comment]
+1

**Comment by TheGreySquare** [comment]
Edited recently

**Comment by milindgoel15** [comment]
Vanced/YouTube now uses the Android framework color for its splash screen to match with system theme colors. You can use third party themes such as substratum or swift to color the Android framework color as per your needs. 
We are closing this issue for now. Feel free to reopen if you have any queries.

**Comment by TheGreySquare** [comment]
> Vanced/YouTube now uses the Android framework color since v15 for its splash screen to match with system theme colors. You can use third party themes such as substratum or swift to color the Android framework color as per your needs. 
> We are closing this issue for now. Feel free to reopen if you have any queries. 

Pretty strange that it's uses framework values now since it's should be possible to set those from the app itself

Honestly neither light nor dark splash screen looks consistent:
as I mentioned, grey splash on black theme;
 white status bar icons with grey background on light splash (instead of dark ones);
 new icon got persistent squircle background on light splash (where as previous icon was dark with light outline so it looked correct on both themes)

Minor stuff, of course, but it's there, so maybe I'll reopen this one in the future when devs wouldn't be so busy with all those issues

Good luck

**Comment by milindgoel15** [comment]
In black theme apk, the black theme is independent from the color used by splash. Like I said, the color on splash screen comes from Android frameworks, not from app so it matches with system theme. (This is the work of Google itself) So when using black apk, the grey splash is intended.

On light splash, the status bar icons color are the same used in stock YouTube app. (Please check if you haven't already)

Vanced haven't changed any color of splash screen neither in light or dark. Google is pretty inconsistent with the colors of splash and it's them who wrote YouTube. Xfile might be able to fix the light splash colors but we cannot guarantee it.
