### ISSUE TITLE
[Idea] hide specific text/picture post from subscription feed

### ISSUE THREAD

**Issue by tonn333** [YTVanced/Vanced#35]
I want to hide these picture/text posts from my subscription feed like I'm currently able to do with videos. That way I can keep my feed cleaner by removing posts that I have already read or have no interest in.

Right now I'm only able to hide videos that I dont want to watch or have watched... Leaving only the ones that I'm yet to watch or finish watching.
And sometimes a channel posts many videos at once, it's great that I have the ability to hide them if I so choose. Why can't I do the same with those text/picture posts. I don't want to never see them just the ability to hide specific posts.

It's a very important feature to have in my opinion.

**Comment by tonn333** [comment]
Great answers!

**Comment by KevinX8** [comment]
The feature doesn't sound easy to implement nor useful

**Comment by tonn333** [comment]
First, how is it not useful? 
There already is a feature which enables you to hide videos from your subscription tab. 
I just want this feature to INCLUDE the ability to hide text and image posts in addition to the video post that I’m already able to hide.

I don’t know how easy it would be to implement. But it is not a new feature. So one would need to expand this existing hide feature to include all entries in subscription tab... not just videos.
