### ISSUE TITLE
[Bug] replaceme

### ISSUE THREAD

**Issue by avrahammeir** [YTVanced/Vanced#354]
**Bug description**
Stucked at 90hz even when playing 60hz vid which sucks a lot of battery

**Variant**
Rooted

**Vanced version**
15.43.32 - Build - 01.47.00

**Android version**
Android 11.0 - Pie

**Device**
Mi 10 pro

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
3. ....

**Expected behavior**
60hz..

1) 15.43.32 (rooted)
2)http://Vancedapp.com
3)vanced manager
4) mi 10 pro global
5) miui china closed beta(but same on other roms I think ) 21.1.13 
6) liv dark ..but didn't apply it in vanced tho
7) none
8) refresh rate stuck at 90hz all the time,even in 60fps video playback.which sucks battery A LOT
9) none related to refresh rate basically
10) stock ytb gives 60fps as usual

**Comment by KevinX8** [comment]
Issue with your Rom, apps cannot control refresh rate without root.

**Comment by avrahammeir** [comment]
I AM ROOTED,ITS STATED IN THE BUG REPORT…. Provenance : Courrier pour Windows 10 De : KevinX8Envoyé le :jeudi 21 janvier 2021 04:49À : YTVanced/VancedCc : avrahammeir; AuthorObjet :Re: [YTVanced/Vanced] [Bug] replaceme (#354) Issue with your Rom, apps cannot control refresh rate without root.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
