### ISSUE TITLE
[Bug] Overlay during Copy and paste

### ISSUE THREAD

**Issue by EinUser2** [YTVanced/Vanced#356]
**Bug description**
Everytime I try to copy and paste Text in the comments, a big black bar appears that make it unpossible to mark/select something.

**Variant**
NonRoot: Yes
Root: No

**Vanced version**
15.43.32 - Build - 01.47.00

**Android version**
Android 11

**Device**
Samsung Galaxy S10+

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2. Click on the comment section
3. Type some Text as you comments
4.  Press and hold to mark/select a part

**Expected behavior**
Be able to still see the text for selecting and copy/past

_Attach images/videos if possible. These can be helpful in solving the issue._
![Screenshot_20210120-162057](https://user-images.githubusercontent.com/77740338/105197658-22358e80-5b3d-11eb-8aca-b10ea61dca16.jpg)
![Screenshot_20210120-162057](https://user-images.githubusercontent.com/77740338/105197781-45603e00-5b3d-11eb-9c6f-b31c6af159e2.jpg)

Tried best to describe it in detail

**Comment by EinUser2** [comment]
Also was present in Android 10 and in the previous versions of the vanced YT app

**Comment by dmack6464** [comment]
I too have this issue and have had it for a long time

**Comment by Vendicated** [comment]
Does this issue also occur in the official youtube app?

**Comment by EinUser2** [comment]
> Does this issue also occur in the official youtube app?

I've tried it just now, normal YT app has the same issue,
just embarrassing...

**Comment by gghhkm** [comment]
@EinUser2 @dmack6464 

This is a Stock Youtube issue and not a Vanced one as you've stated yourself @EinUser2.
This issue can be closed.
