### ISSUE TITLE
[Idea] Age restrictions bypass

### ISSUE THREAD

**Issue by VyrCZ** [YTVanced/Vanced#358]
**Description**
I think it is good idea to make bypass to this
![IMG_20210120_210305](https://user-images.githubusercontent.com/60008354/105228504-edd4c900-5b62-11eb-98f4-65991d1ab995.jpg)
(just window saying to verify I'm over 18)
I don't think this will be abused very much, it could be EASILY bypassed before so will be not that difference. Main reason I hate that (I am less than 18) is because it don't let me watch my favourite youtuber (just because someone is making banana gun in game is marked as 18+)

**Comment by Vendicated** [comment]
You could just set your age to 18 in your google account settings

**Comment by VyrCZ** [comment]
> You could just set your age to 18 in your google account settings

yes i did it but I have no way to prove it and I don't want to anyway so it shows the verification box

**Comment by gghhkm** [comment]
> > You could just set your age to 18 in your google account settings
> 
> yes i did it but I have no way to prove it and I don't want to anyway so it shows the verification box

I'm guessing it's the "confirm age with credit card" bs they started doing in the UK.

You can use Newpipe to bypass it, or you could make an account outside the with the use of a VPN.

**Comment by VyrCZ** [comment]
> > > You could just set your age to 18 in your google account settings
> > 
> > 
> > yes i did it but I have no way to prove it and I don't want to anyway so it shows the verification box
> 
> I'm guessing it's the "confirm age with credit card" bs they started doing in the UK.
> 
> You can use Newpipe to bypass it, or you could make an account outside the UK with the use of a VPN.

You have to take photo of your id and I am not from England but VPN worked
