### ISSUE TITLE
[Idea] Remove "miniplayer is off for videos made for kids"

### ISSUE THREAD

**Issue by TikiPlayz** [YTVanced/Vanced#360]
![image](https://user-images.githubusercontent.com/20033421/105277754-0bf5f580-5b72-11eb-860f-446440042aca.png)
This feature is total bullshit and utterly useless, just an annoyance. Please remove this on all videos (if even possible) TiA
https://www.reddit.com/r/Vanced/comments/khwkts/suggestion_remove_this_bs/

**Comment by Hyperboraeer** [comment]
Definitely agree with you. It's so annoying.

**Comment by vrindavan** [comment]
+1
