### ISSUE TITLE
[Bug] Fit-To-Screen doesn't work anymore

### ISSUE THREAD

**Issue by JKamsker** [YTVanced/Vanced#363]
**Bug description**
When trying to fit the video to the whole screen by "zooming in with 2 fingers", it tells me that it did what its supposed to do but there is literally no change.

**Variant**
NonRoot: Yes
Root: No

**Vanced version**
15.43.32 - Build - 01.47.00

**Android version**
MIUI Global 12.0.3 Stable
10 QKQ1.190825.002

**Device**
Xiaomi 9T Pro

**Steps to Reproduce**
Steps to reproduce the error:
1. Having a Phone that doesnt have 16:9 aspect ratio and therefore needs to be stretched or zoomed
2. Open the app
3. Open a video
4. Try to zoom in/Fit video to screen

**Expected behavior**
Video should fill whole screen, but nothing happens. There are still black boxes on both vertical ends of the screen.

![signal-2021-01-21-121841](https://user-images.githubusercontent.com/11245306/105344144-dccb9c80-5be2-11eb-9311-8baf215a85b4.jpeg)

**Comment by JKamsker** [comment]
I just noticed, that the feature begins to work after opening and moving the app to background several times in a row. Changing videos sometimes also helps...sometimes

**Comment by RichardSauer** [comment]
Same

**Comment by milindgoel15** [comment]
It should be working with the v16.20 release. If it doesn't, feel free to post your issue again here. We are closing this for now.
