### ISSUE TITLE
[Bug] Vanced Manager crash

### ISSUE THREAD

**Issue by nareshkatta99** [YTVanced/Vanced#366]
**Bug description**
App crashing everytime after completing the initial loading.

**Variant**
NonRoot: Yes
Root: No

**Vanced version**

**Android version**
Android 10

**Device**
Redmi Note 8 pro

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2. Wait for the swipe refresh to close.

**Expected behavior**
App should search for new versions

![Screenshot_2021-01-21-22-41-48-078_com.miui.bugreport.jpg](https://user-images.githubusercontent.com/7877291/105386635-a15cbc80-5c3a-11eb-8e6c-b8d7feed4419.jpg)

**Comment by nareshkatta99** [comment]
![Screenshot_2021-01-21-22-40-48-885_com.vanced.manager.jpg](https://user-images.githubusercontent.com/7877291/105387511-a2dab480-5c3b-11eb-9ca9-6e696240bb41.jpg)

Sorry, missed Vanced Manager version.
Here it is, in the screenshot.

**Comment by X1nto** [comment]
use 2.2.1, also this should go under https://github.com/YTVanced/VancedManager/issues
