### ISSUE TITLE
[Idea] Disable Loudness Normalization

### ISSUE THREAD

**Issue by Kafu-Yukimura** [YTVanced/Vanced#367]
I request to add a feature to disable Loudness Normalization in Youtube Vanced.

I can use YouTube Music, but YouTube Music has its limitations in listening to the comparison sound inserted in the video, previewing the sound source, and playing some uploaded music.
Also, YouTube Music may be restricted depending on the region.

**Comment by Raihanshams** [comment]
It would be nice to have that feature
