### ISSUE TITLE
[Idea] Submit translations for Vanced FAQ

### ISSUE THREAD

**Issue by AnotiaWang** [YTVanced/Vanced#368]
**Description**
I want to help translate Vanced FAQ into my language. Would you open a Crowdin project for that? Thank you!

**Comment by KevinX8** [comment]
The FAQ is just too long for crowdin (some 20 pages worth of text) https://github.com/YTVanced/VancedBackend/tree/master/strings/en you can make a PR here with your translations but it's just way too large for crowdin

**Comment by AnotiaWang** [comment]
> The FAQ is just too long for crowdin (some 20 pages worth of text) https://github.com/YTVanced/VancedBackend/tree/master/strings/en you can make a PR here with your translations but it's just way too large for crowdin

Ok, I'm working now. Thanks

**Comment by AnotiaWang** [comment]
finished translating
