### ISSUE TITLE
[Bug] Can't play/pause while chromecasting

### ISSUE THREAD

**Issue by MxRay** [YTVanced/Vanced#370]
**Bug description**
When I start chromecasting everything works as it should. Unfortunately, after some time of playing content, I can't play/pause from within the app. Everything else works - skip ahead/back 10s, play next/previous video, add to queue, etc. The app reacts with no delay when I play/pause the video with a TV remote control and changes its play/pause symbol accordingly. 

**Variant**
NonRoot: Yes
Root: No

**Vanced version**
15.43.32 - Build - 01.47.00

**Android version**
Android 10

**Device**
Sony Xperia 5 II

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2. Click on the Chromecast icon
3. Connect to a TV
4. Stream some video
5. Wait
6. Tap on the pause icon
6. Nothing happens

**Expected behavior**
The expected behavior is that when I click on a play/pause icon in the app itself the video on TV will react to it.

**Comment by Vendicated** [comment]
microGs Chromecast implementation is an absolute mess so I doubt this will be fixed
