### ISSUE TITLE
Don't installing

### ISSUE THREAD

**Issue by Accuracydev** [YTVanced/Vanced#371]
I trying to install YouTube Vanced (ROOT) and when it installed Vanced Manager crashes and YouTube don't openning
Variant
NonRoot: No
Root: Yes

Vanced version
Latest

Android version
Android 10

Device
Xiaomi Redmi Note 9S

**Comment by Vendicated** [comment]
- Clear app data of manager
- Turn internet off
- Open manager app
- Turn internet on

if the issue persists, open a new issue in [YTVanced/VancedManager](https://github.com/YTVanced/VancedManager)
