### ISSUE TITLE
[Bug] Networking Issues 

### ISSUE THREAD

**Issue by CosmicDaemon** [YTVanced/Vanced#372]
-Bug description-
The Vanced displays "Please check your network" even though my internet is fine.It shows it on both of my devices the same thing.

**Variant**
NonRoot: Yes
Root: No

**Vanced version**
15.43.32 - Build - 01.47.00

**Android version**
Android 9.0 - Pie

**Device**
Samsung Galaxy S8

-Steps to Reproduce-
Steps to reproduce the error:
1. Open the app

**Expected behavior**
It showed a network error instead of my homescreen.

**Comment by hacker812c** [comment]
Unistall microG and teste my friend

**Comment by hacker812c** [comment]
MicroG this relesse rum perfectly
https://techbigs.com/pt/download?pid=24812&n=YouTube+Premium#

**Comment by KevinX8** [comment]
please do not post links to sketchy sites.

**Comment by hacker812c** [comment]
Sorry my friend kevinx8
Thanks for vanced
