### ISSUE TITLE
[Question] YouTube 16.02.35 fake?

### ISSUE THREAD

**Issue by hacker812c** [YTVanced/Vanced#373]
**Description**
I found this relesse YouTube vanced 16.02.35
My question is this relesse is fake?
REDACTED
This app is dangeours?

**Comment by KevinX8** [comment]
We do not make it and the site is marked as malicious by Malwarebytes so I would say avoid anything posted on that site, please do not share any links from there.

**Comment by KevinX8** [comment]
if you post the link again I will be forced to ban you from this repo.

**Comment by hacker812c** [comment]
Thanks kevinx8 
Thanks for reply and information
