### ISSUE TITLE
[Idea] remove "includes paid promotion" text

### ISSUE THREAD

**Issue by eldon97** [YTVanced/Vanced#375]
![Screenshot_2021-01-24-16-52-58-846_com vanced android youtube](https://user-images.githubusercontent.com/19554521/105626778-ac933080-5e64-11eb-94b6-938d98775c8f.jpg)

**Comment by Vendicated** [comment]
Whats the point of this? It's important to let you know that what the creator is saying isnt actually their opinion but rather a script they are paid for

**Comment by eldon97** [comment]
> Whats the point of this? It's important to let you know that what the creator is saying isnt actually their opinion but rather a script they are paid for

it's overlapped with subtitle text, sometimes I need to wait a few seconds for the text disappeared.

**Comment by Xane123** [comment]
To me, it's kinda annoying (seriously, why did they make it last **20 seconds?**) and completely unnecessary since SponsorBlock usually skips the sections it's there for. On my laptop, I have a userstyle dedicated to hiding this notice, and it would be nice to be able to do the same on my phone.

**Comment by vrindavan** [comment]
-1
