### ISSUE TITLE
[Bug] Not recognising my google profile after a password change

### ISSUE THREAD

**Issue by Leqwar** [YTVanced/Vanced#376]
I was forced to change password on my email which is my main YT channel. After that, Vanced is not able to sign me in with that, while everything else was able to bear with the changing. The photo provided, shows the situation, and even 'Tapping retry' does nothing, just like refresh it, but does not solve the problem. 
![Screenshot_20210124_171222](https://user-images.githubusercontent.com/77930972/105636393-853e6280-5e68-11eb-85c3-a67c27a9f8d3.jpg)

**Comment by Vendicated** [comment]
Remove the account via `Device Settings > Accounts` and add it again
