### ISSUE TITLE
[Question] Why doesn't skip to end & replay video remove ads?

### ISSUE THREAD

**Issue by NoFate82** [YTVanced/Vanced#377]
**Description**
As the title suggests, why do ads still appear on videos after skipping to the end & replaying? It works on the stock YouTube app but not on vanced. Frustrating when I want to watch a good doco but it is peppered with yellow markers forcing me to put it in history then having to switch to the stock YouTube app. Which actually leads me to another annoyance; if video is on a watch later or playlist it is not possible to skip to the end & replay as it automatically jumps to the next video in the list. I have to put in history so it actually stops at the end. Or am I just an old whinging c*nt? 🙄

**Comment by Vendicated** [comment]
I don't understand this question. Vanced blocks all ads so you don't need to do the skip trick. It leaves the yellow ad markers so you can see how many ads you would have usually seen, but doesn't actually display any of them. This is a design choice but might be toggleable in the future (Create a suggestion issue)
