### ISSUE TITLE
Zoom to fill issue (Samsung phone) 

### ISSUE THREAD

**Issue by ShoGan20** [YTVanced/Vanced#378]
Hi I'm using the Note 20 Ultra. The zoom to fill option doesn't seem to work for videos. They only work when video has autoplayed during the preview and the opened. I've tried using run video at phone max resolution, as well as allowing Vanced to have full screen access. Both don't seem to help.

**Comment by Vendicated** [comment]
Google messed around server-side and broke Zoom to fill for the older builds. It will be fixed in the next release. For now, turn it off and on again and it should be back to normal

**Comment by w-kok** [comment]
Random zoom to fit an not able to fit for videos on S10+ as well. Lot of similar issues mentioned that are still open. None the less, gj devs overall on ytVanced.

**Comment by ETJeanMachine** [comment]
Hi, I'm using a Note 20 Ultra too. This issue can be resolved if you go into Settings>Display>Full Screen Apps and enable YT Vanced. 👍[Screenshot_20210331-125715_Settings.png](https://user-images.githubusercontent.com/54557728/113182299-bd737000-9220-11eb-897d-b3f360036fae.png)

**Comment by KevinX8** [comment]
This not vanced related it's stock YouTube bugs
