### ISSUE TITLE
[Bug] YouTube Vanced Don't installing.

### ISSUE THREAD

**Issue by Accuracydev** [YTVanced/Vanced#379]
**Bug description**
I trying to install YouTube Vanced (ROOT) and when it installed Vanced Manager crashes and YouTube don't openning.
Everything was fine before, it installed fine. After updating the version of MIUI to 12.0.3 version, YouTube Vanced stopped installing.

**Variant**
NonRoot: No
Root: Yes

**Vanced version**
Vanced Manager v2.2.1 (RootedFirebase)

**Android version**
Android 10 - Q

**Device**
Xiaomi Redmi Note 9S

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2. Click on 'Install'
3. Vanced Manager crash.

**Expected behavior**
I was expecting that I would press the install button and the YouTube Vanced will install. But instead, what happened is that YouTube Vanced is not installed correctly and the Vanced manager crashes.

**Comment by miltos11** [comment]
Try that
1. Delete vanced manager
2. Download sal (slit apk's installer) from play store 
3. Open sal 
4. Press install APKs
5. Locate manager.apk (it is most likely in the download folder except you moved it somewhere else)
6.  Select manager.apk
7. After manager is installed open it grant superuser permission and install youtube vanced even if it says unavailable.
If it still fails to install it then
1. Clean storage
2. Restart your device 
 If this doesn't fix it it is most likely that there is a problem with your device after the update (really unlikely) just wait for future updates

**Comment by Vendicated** [comment]
Make sure you have Miui optimisation disabled in your developer settings. If the issue is still occurring, please create a logcat:
- Install a terminal emulator. I recommend [Termux](https://play.google.com/store/apps/details?id=com.termux)
- open it and run `su`, grant root permissions when prompted
- Now run `logcat *:W > /storage/emulated/0/logcat.yaml`
- Cause the crash again
- Exit the terminal
- Attach the file logcat.yaml found in your sdcard

**Comment by Accuracydev** [comment]
> Try that
> 
> 1. Delete vanced manager
> 2. Download sal (slit apk's installer) from play store
> 3. Open sal
> 4. Press install APKs
> 5. Locate manager.apk (it is most likely in the download folder except you moved it somewhere else)
> 6. Select manager.apk
> 7. After manager is installed open it grant superuser permission and install youtube vanced even if it says unavailable.
>    If it still fails to install it then
> 8. Clean storage
> 9. Restart your device
>    If this doesn't fix it it is most likely that there is a problem with your device after the update just wait for future updates

Thank you! That's helped
