### ISSUE TITLE
Vance Manager Crashes on Pixel 4a Android 11

### ISSUE THREAD

**Issue by MrCaspan** [YTVanced/Vanced#38]
So brand new device and tried to install Vanced Manager app tries to load and shows app logo for 2 seconds then I get app has crashed.

I have uninstalled and reinstalled, download APK again, rebooted device. Running Android 11 with September update installed. No other updates

**Comment by Koomongous** [comment]
Seems like the Big Sur update works on Android 11
https://github.com/YTVanced/VancedManager/releases/tag/1.1.0

**Comment by KevinX8** [comment]
definetly not vanced related

**Comment by MrCaspan** [comment]
It 100% was Vanced related and it has been fixed in the last patch, by you guys! so.... just saying
