### ISSUE TITLE
[Bug] Vanced Crashing after left playing in the background for few minutes

### ISSUE THREAD

**Issue by Clashpoint** [YTVanced/Vanced#381]
**Bug description**
When running Youtube Vanced in the background for few minutes it get closed 

**Variant**
NonRoot: Yes
Root: No

**Vanced version**
15.43.32 - Build - 01.47.00

**Android version**
Android 8.1 

**Device**
Infnix Note 4 

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2. play any video
3. turn off the screen or exit the app while the video is still playing 
4. wait few mintues

**Expected behavior**
The video plays smoothly until the end or until the end of the playlist 

_Attach images/videos if possible. These can be helpful in solving the issue._

[logcat.zip](https://github.com/YTVanced/Vanced/files/5876093/logcat.zip)

<details> 
  <summary>Steps I did to try to fix this issue</summary>
 - I tried to  disable doze altogether from my phone using this command [adb shell dumpsys deviceidle disable] and it didn't do much 
- removed an app called phone master (was built in so used adb) that might have interfered with apps starting and closing them but it didn't do anything 
- whitelisted all vanced apps from battery optimization  
</details>

**Comment by ProDebPap** [comment]
The steps that you tried to fix the issue also concerned me that it might fix the problem. Now that you have already attempted those probable fixes where I didn't, saved a lot of my efforts.

I also would like to remove the phone master app regardless. Please provide some help.

**Comment by ProDebPap** [comment]
I suggest you uninstall the PhoneMaster Services App too

**Comment by Clashpoint** [comment]
> I also would like to remove the phone master app regardless. Please provide some help.

I suggest looking up how to uninstall apps using adb 
> I suggest you uninstall the PhoneMaster Services App too

I have already done that

**Comment by ProDebPap** [comment]
I have tried one. After following their method the system shows the app is still installed but not for the current user but is still installed as a system app where Play Store still let the option install it.

Is it anything same with the method you followed?

**Comment by Clashpoint** [comment]
> I have tried one. After following their method the system shows the app is still installed but not for the current user but is still installed as a system app where Play Store still let the option install it.
> 
> Is it anything same with the method you followed?

No, the app is fully removed from my system and it's not usable in any capacity, and even with adb checking for packages it wasn't there.

**Comment by ProDebPap** [comment]
I request you to check again from your phone's app manager (including system apps) and provide me the status here

**Comment by Clashpoint** [comment]
> I request you to check again from your phone's app manager (including system apps) and provide me the status here

As I already said, it's fully removed. System doesn't detect it nor does play store.

**Comment by ProDebPap** [comment]
You misunderstood. I said Play Store says I can install it like it's not installed in my phone but settings/app manager shows its still there but not usable for this user even after being removed.![Screenshot_20210209-042127.png](https://user-images.githubusercontent.com/78584412/107289082-b33dbc80-6a8e-11eb-8655-be539c3cd97d.png)

**Comment by Clashpoint** [comment]
> You misunderstood. I said Play Store says I can install it like it's not installed in my phone but settings/app manager shows its still there but not usable for this user even after being removed. 

Hence my reply 

> **System** doesn't detect it nor does play store.

**Comment by ProDebPap** [comment]
If you can provide any direct instruction regarding uninstalling this app issue, that would be very kind.

**Comment by ProDebPap** [comment]
> > You misunderstood. I said Play Store says I can install it like it's not installed in my phone but settings/app manager shows its still there but not usable for this user even after being removed. 
> 
> Hence my reply 
> 
> > **System** doesn't detect it nor does play store.

You're wrong. ADB just uninstalls it from the current user

**Comment by Clashpoint** [comment]
> You're wrong. ADB just uninstalls it from the current user

**My system doesn't detect it**. 
What exactly am I wrong about??

**Comment by ProDebPap** [comment]
Please check back again if you have the app still installed in your system or not.

**Comment by Clashpoint** [comment]
> Please check back again if you have the app still installed in your system or not.

M system doesn't dystect it

**Comment by Clashpoint** [comment]
> Please check back again if you have the app still installed in your system or not.


**My system doesn't detect it**. I checked.

**Comment by ProDebPap** [comment]
adb shell
pm list packages | grep 'transsion'

**Comment by ProDebPap** [comment]
I believe adb is not privileged enough to help here. If it is then I must ask for help from you

**Comment by Clashpoint** [comment]
- this has nothing to do with vanced 
- you already know the commands (in case you don't [adb shell pm uninstall --user 0 com.useless.piece.of.trash] ) 
- if you need help, either open a new issue or go to the discord server since I am not capable of helping you.

**Comment by ProDebPap** [comment]
Is the app still installed in your system even though you're saying you removed it? It does not concern me if it has anything to do with the vanced or not. I just wanted to make myself sure. No offence.

**Comment by Vendicated** [comment]
the `--user 0` flag makes it so that the app is only uninstalled for the current user. omitting this flag will result in the app being uninstalled in it's entirety but you require root to do that. So with the command you're using, the app gets deleted only for the current user, it still remains in the system. 

Either way this entire issue isn't even vanced related, it's your rom or transsion that's to blame. Vanced is just the "victim" of the issue
