### ISSUE TITLE
[Bug] YTmusic Country block

### ISSUE THREAD

**Issue by Ca1pha** [YTVanced/Vanced#383]
**Bug description**
YTmusic is blocked at South Korea, so korean users can't use the free ytm
and the music vanced can't make it work either

**Variant**
NonRoot: Yes
Root: No

**Vanced version**
15.43.32 - Build - 01.47.00

**Android version**
Android 9.0 - Pie

**Device**
All devices

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the yt music vanced app in korea(connecting vpn to South Korea)

**Expected behavior**
What I expected:
![Screenshot_20210127-124439~2.png](https://user-images.githubusercontent.com/67798936/105939961-8f957200-609d-11eb-9fbc-ad427c04d7b8.png)

What happens:
![Screenshot_20210127-122544~2.png](https://user-images.githubusercontent.com/67798936/105940005-a5a33280-609d-11eb-9053-51f31b3db034.png)

**Comment by Vendicated** [comment]
There's nothing Vanced can do to solve this, since it is a server side restriction. Just use a vpn or use an alternative like normal YtVanced or newpipe
