### ISSUE TITLE
[Bug] YouTube Vanced Crashes Or Kicks Me Out Of The App While Or During Playing A Video

### ISSUE THREAD

**Issue by Suli799** [YTVanced/Vanced#384]
**Bug description**
I open YouTube vanced and watch desired video while or during watching this video while it's playing the app closes or crashes 

**Variant**
NonRoot: Yes
Root: No

**Vanced version**
15.43.32 - Build - 01.47.00

**Android version**
Android Oreo

**Device**
Huawei Y7 2019

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2. Click on Any Video. While playing Wait Around 5- 10 min
3. Vanced Kicks out or Crashes

**Expected behavior**
Video keeps playing normally and app doesn't crash or close while playing 

_Attach images/videos if possible. These can be helpful in solving the issue._

**Comment by FlashlightET** [comment]
same here on non rooted galaxy a21, it also randomly signs me out and that seems to be related

**Comment by FlashlightET** [comment]
I noticed that you (and me) were on build 16 when the latest is version 16 maybe that could be a factor

**Comment by FlashlightET** [comment]
nope still happening
