### ISSUE TITLE
[Bug] Cant install updates from vanced manager

### ISSUE THREAD

**Issue by ms123myrddin** [YTVanced/Vanced#386]
**Bug description**
When i try to update YouTube vanced it says
" Download failiure while downloading Dark.apk"

**Variant**
NonRoot: Yes
Root: No

**Vanced version**
15.43.32 - Build - 01.47.00

**Android version**
Android 10.0 

**Device**
Oneplus nord

**Comment by Vendicated** [comment]
Temporary server issue. Should be fixed now, if not try again later
