### ISSUE TITLE
[Bug] Cannot switch account, not appearing

### ISSUE THREAD

**Issue by sltcmoib** [YTVanced/Vanced#389]
**Bug description**
Cannot switch of YT account anymore, account already signed in into microg but not appearing into vanced. 
Only asking me to add account but when i sign in it says me this account already exist on my phone.
Tryied to clear cache or some other techniques but nothing change.

**Variant**
Non-Root

**Vanced version**
16.02.35 - Build - 01.47.00

**Android version**
Android 10

**Device**
Redmi Note 9 Pro

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2. Click on your account information at the top right
3. Select your account to switch account 
4. Your other account do not appear here

**Expected behavior**
Maybe microg bug? Idk

_Attach images/videos if possible. These can be helpful in solving the issue._
![Screenshot_2021-01-28-02-24-09-212_com vanced android youtube](https://user-images.githubusercontent.com/78123461/106076496-f3588300-610f-11eb-9cbb-13e26c59f6d7.jpg)

**Comment by shreyassanthu77** [comment]
Even I have the exact same problem

**Comment by gghhkm** [comment]
This is an issue caused by the upstream microG bug mentioned before.

**Comment by aqoraan** [comment]
Hello, Any update on this? I have same issue. I have 4 accounts already added to Vanced but they are not listed and can't switch accounts :(
I've tried to sign out and re-sign it with no luck

**Comment by gghhkm** [comment]
> Hello, Any update on this?
> I've tried to sign out and re-sign it with no luck

The only way to get multiple accounts to work is by using the previous version.
As for an update on it, I doubt even the Vanced Dev's know for sure because it's an upstream MicroG issue so it's out of our control.
