### ISSUE TITLE
[Bug] Vanced manager doesn't send notifications about new updates 

### ISSUE THREAD

**Issue by Mimicthis** [YTVanced/Vanced#39]
Hi!

As the title says, vanced manager doesn't send notifications about new updates to the YouTube Vanced or MicroG updates. Power saving is turned for it, notifications are enabled. 

Also why is my username included in this link? 
![Screenshot_20200921-002557_Chrome](https://user-images.githubusercontent.com/29215437/93723712-3ecab580-fba1-11ea-9df0-2ae6e26533bc.jpg)

I can't label things because I have no permission.

**Comment by Mimicthis** [comment]
Hello?

**Comment by KevinX8** [comment]
please only report vanced related issues here
