### ISSUE TITLE
Not working one UI 3.0

### ISSUE THREAD

**Issue by btrain-git** [YTVanced/Vanced#391]
Note 10+ no longer working with the latest one UI 3.0 update.

**Variant**
Non-Root

**Vanced version**
16.02.35 - Build - 01.47.00

**Android version**
Android 11.0

**Device**
Samsung Galaxy note 10+

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2. Stays on loading circle indefinitely

**Expected behavior**
It should work. Suggested vids should come up first.

![Screenshot_20210128-192411](https://user-images.githubusercontent.com/60606521/106110127-6dcfe400-619e-11eb-899f-2354860a43cb.jpg)

**Comment by btrain-git** [comment]
My bad, I had to do the downgrade/re log in/update trick and now it's working 🤦‍♂️ feel free to close this

**Comment by zcake3000** [comment]
I  have same issue one UI 1.1(android 9) on sm-p205.
