### ISSUE TITLE
[Idea] ignore age warning 

### ISSUE THREAD

**Issue by JustJoxem** [YTVanced/Vanced#393]
In the EU there is now a chance that the youtube algorithm will decide you have to confirm your age. You have to do this by adding a credit card or submiting your ID card/drivers license/passport. But I don't have a credit card and don't feel like giving my identification to Google. Is there any chance that you will add a feature to vanced to get around this?

With kind regards, 
Jochem

**Comment by Vendicated** [comment]
In the meantime you can use a VPN or watch the video inside a third party video player (Newpipe / VLC / mpv)

**Comment by vrindavan** [comment]
-1

**Comment by VL4DST3R** [comment]
For me the prompt doesn't even work properly, all i can do is close it but the video still doesn't work. A bypass would be great.

**Comment by milindgoel15** [comment]
Duplicate of #173
