### ISSUE TITLE
[Bug] Login issue with Google G-suit account

### ISSUE THREAD

**Issue by norouzimahalli** [YTVanced/Vanced#394]
**Bug description**
I installed the new version but obviously you should install the old versio, login to your account and then upgrade to 16 version.
But the Vanced just recognize the G-suit account for the first time and then it goes away. It says "no internet connection" or "retry to login again". With the same app and same situation I added the normal Google account and it works normally.
Obviously it doesn't have anything to do with the config or battery optimization, app clear cache and etc since I already tried everything and the normal Google account works just fine. Both normal and G-suit account has 2SA on and I tried to turned them off as well but no luck. So what's Vanced problem with G-suit accounts?!

**Variant**
Non-Root

**Vanced version**
16.02.35 - Build - 01.47.00

**Android version**
Android 10

**Device**
Oneplus 6

**Comment by Vendicated** [comment]
This is related to microg which is not maintained by us. Please move your issue to the [official microg](https://github.com/microg/GmsCore) repository. Do not mention Vanced as they have nothing to do with it, simply explain that G-Suite accounts don't work with microG
