### ISSUE TITLE
[Bug] YouTube account switching

### ISSUE THREAD

**Issue by anedroid** [YTVanced/Vanced#397]
**Bug description**
In latest version cannot switch YouTube account, event though in 16.02.32 it worked. Dialog window shows but it's empty. If I install this version first time, after opening app nothing content shows.

**Variant**
Non-Root

**Vanced version**
16.02.35 - Build - 01.47.00

**Android version**
Android 9.0 - Pie

**Device**
Moto g7 Power

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2. Click on your account icon
3. Try to switch account

**Expected behavior**
After clicking "switch account" or your account should show dialog with YouTube accounts.

_Attach images/videos if possible. These can be helpful in solving the issue._
Before: https://mega.nz/file/hB00ACyS#l7b1htf1r3HR1UBFcY0KoLRk1q-3qhT_L1UjB0vB9jM
After: https://mega.nz/file/AVtAVC6L#uMoAwzmeMJLcGe_3GnZcgGCXm6gvEsGmugwtg9ItPnM, https://mega.nz/file/hFVARLZb#wCAhf4vDfWSF-pxKAMjVPoxjfYRueBJafd5EpgjhG0M

**Comment by Xyleos** [comment]
I had the same problem too. I want to change my account but it doesn't show at all the the account menu. I thought it was deleted when I updated the app but when I tried to sign in using the Microg it said the account was already registered.

**Comment by AinzTheSupremeOne** [comment]
It's probably because of the microG bug. Try downgrading to 15.43

**Comment by anedroid** [comment]
> It's probably because of the microG bug. Try downgrading to 15.43

No, it's YouTube Vance bug, because it's work on previous version without downgrading microG.

**Comment by tomas-samot** [comment]
I am also experiencing this issue.

**Comment by AinzTheSupremeOne** [comment]
> > It's probably because of the microG bug. Try downgrading to 15.43
> 
> No, it's YouTube Vance bug, because it's work on previous version without downgrading microG.

No, it's not Vanced bug, it's just a side effect of a microG bug. https://github.com/microg/GmsCore/issues/1373 New YouTube v16 requires a higher play services version code to work and a bug in microG prevents "the fix". That's why this instruction even be posted there https://github.com/YTVanced/Vanced/issues/396. ~~Just spam the microG issue until they fix it~~

**Comment by goxr3plus** [comment]
SAME here :(!!!!

**Comment by beryozavv** [comment]
Same here.

**Comment by cryptoicobitcoin** [comment]
how can i restore my password from youtube vanced?) i lost my password of gmail/youtube and cann't restore it, but i'm still logged in in youtube vanced. how can i get the password out of the program on the tv box

**Comment by mighty-phoenix** [comment]
This is a major bug.

Kindly fix this whenever you can.

**Comment by gghhkm** [comment]
Guys, use 15.43.32 until 16.08 is released.

**Comment by omarfar25** [comment]
Same here..  but with root  privileged

**Comment by beryozavv** [comment]
Everything works in last version 16.14.34
