### ISSUE TITLE
Multiple bugs

### ISSUE THREAD

**Issue by Mimicthis** [YTVanced/Vanced#4]
1. HDR full brightness setting no longer works in the and HDR video.

2. End cards removal setting doesn't work for any video. Branding watermark also doesn't work. 
![Screenshot_20200904-204507](https://user-images.githubusercontent.com/29215437/92275550-8b4e9980-eeef-11ea-89f5-f8e83c7aa4e3.jpg)
 
[Bug.]

Did I type that tag correctly? Will GITHUB email me about the reply?

**Comment by VancedOfficial** [comment]
@AdemSof 
1. Known, will look into this at some point but other things take priority over this one.
2 (a). I was just testing and it seems like the end cards and info card are swapped, at least for me. So the actual settings work, just wrong buttons. 

2 (b). Branding watermark, hmm, it works fine for me. Could you link a video where it doesn't work?

**Comment by AdemSof** [comment]
2 (a).  OK, so I'll enable the end cards to have info cards back then. Thanks!

3. Here you go:
https://youtu.be/kzYSyIrBkmY
https://youtu.be/VwMo3ipsT6I
https://youtu.be/Er0Jh2dh3_c
 Could you please provide me the on which it works? Maybe these can't be removed or I'm mistaking it.
[Bug] 

Please tell me if [Bug] is correctly written tag. I should just write it anywhere or is there a special GITHUB procedure for that? Tnx!

**Comment by VancedOfficial** [comment]
Those videos have it embedded in the actual video.

Test with this: https://youtu.be/W-VInHvlrZo 

That MKBHD should be removed from bottom right corner (in landscape view at least).

**Comment by AdemSof** [comment]
Yes, yes you're right!

Sorry, my mistake. 

Am I tagging it correctly? You've said to put [Bug] or [Idea] respectively. I don't know if I'm doing it correctly,

**Comment by VancedOfficial** [comment]
I think the idea for those was to put them in the title of this. You know, at the top where you have "Multiple bugs #4" -> "[Bug] Multiple bugs #4". So that it's easy to see whether it's an bug or enhancement idea. Could just use labels though.

**Comment by AdemSof** [comment]
Oh, so sorry, I understand now. I thought that you can get it if I put it in a message, like it's a code. So, could you tell me how to put labels in my future posts also?

**Comment by VancedOfficial** [comment]
You should have the option on the right when you create a ticket. There's that gear icon next to "Labels" text. At least I think you can add them (as in I think those don't require some specific permissions).

**Comment by AdemSof** [comment]
I'm so sorry but I see no gear icon when posting a new topic. Look:
![Screenshot_20200906-010001_Chrome](https://user-images.githubusercontent.com/29215437/92314758-566c4080-efdc-11ea-8584-6818afb0b389.jpg)

**Comment by AdemSof** [comment]
Should I add this as a new suggestion? Black mode isn't everywhere it's dark mode here:
![Screenshot_20200907-025340](https://user-images.githubusercontent.com/29215437/92339303-b1259b00-f0b5-11ea-9350-7348cd71ce54.jpg)

**Comment by spicyfoxx** [comment]
The developers will try their best to make the whole UI black except some hard to do or highlighted parts.

**Comment by AdemSof** [comment]
> You should have the option on the right when you create a issue. There's that gear icon next to "Labels" text. At least I think you can add them (as in I think those don't require some specific permissions).

I have no permission to label stuff here.
