### ISSUE TITLE
[Idea] Remove "autoplay next video" button 

### ISSUE THREAD

**Issue by Harmonie666** [YTVanced/Vanced#400]
**Description**
Could you please give us the option to remove the "autoplay next video" button? I never use it, and it's in the way. The idea has alot of support in [Reddit](https://www.reddit.com/r/Vanced/comments/l7v52p/remove_autoplay_button_could_you_please_give_us/?utm_medium=android_app&utm_source=share)
![Screenshot_20210129-161656076 (1)](https://user-images.githubusercontent.com/73917917/106292891-aaa6e400-624d-11eb-91ab-45c09ff19e6a.png)

**Comment by Ryonez** [comment]
In the way of what? I'm not seeing any other controls under it.
