### ISSUE TITLE
[Idea] Video downloading

### ISSUE THREAD

**Issue by anedroid** [YTVanced/Vanced#402]
**Description**

In YouTube there's download button, but downloading is available only in some videos, in addition files are stored in app data so I cannot access them, and after 2 days they're deleting.
I have one app to download youtube video (dentex.youtube.downloader), but because I use TOR, Google often requests captcha. App above doesn't show then anything, only error.
Including download option to YouTube Vanced would make this much easier and less problematic for TOR users - Google doesn't request for captcha if I'm logged in. Files could be stored in download dir or where user decided.

_Attach images/videos if possible. Also add any links to possible other applications with the said feature already implemented._
![CM_20210129221421958.jpg](https://user-images.githubusercontent.com/72965850/106328004-5c123d80-627f-11eb-9c8e-3645f9a216ca.jpg)

**Comment by Vendicated** [comment]
Download will never be added as it very drastically increases the odds of youtube taking Vanced down. Try using youtube-dl or newpipe, they should bypass captcha

**Comment by Xi-PP** [comment]
I know they will not & never going to add download option but I think they can just add custom activity trigger option, there in the download button.. so users can share the link in their choosen app/activity

**Comment by Vendicated** [comment]
> I know they will not & never going to add download option but I think they can just add custom activity trigger option, there in the download button.. so users can share the link in their choosen app/activity

The share options are handled by the apps that you share it to, not by the app currently open. If your downloader app doesn't show up when you click on share video, that's their fault

**Comment by gghhkm** [comment]
> Could it be possible to make a call out to a NewPipe API instead.
> I mean if you Vanced devs add a toogle in the settings to redirect download button to Newpipe..?
> In this way you could reduce the hassle of Close Vanced > Newpipe > Search for video > Download Audio or Video
> This feature would be more cool in YTMusic though....

It's simply not legal, adding anything that allows for Users to freely download content within Vanced breaks DRM and would get Vanced DMCA'd real fast. We want Vanced to continue well into the future, not get killed off. Also can't you just share the link to Newpipe and download it? No reason to close Vanced. If Newpipe can't do it, I'm sure Ymusic can.
