### ISSUE TITLE
The copy icon isnt showing on the screen like in the video you guys posted at vanced youtube  chanel

### ISSUE THREAD

**Issue by Leonitduga** [YTVanced/Vanced#404]
**Bug description**
The icon to copy the link of the video isnr showing.

**Variant**
Non-Root

**Vanced version**
16.02.35 - Build - 01.47.00

**Android version**
Android 10 - Pie

**Device**
Huawei p20

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2. Click on the video that you want to wacn
3. And tap at the video the copy link isnt showing

**Comment by Xi-PP** [comment]
Did you really enabled the option from
Vanced Settings » Misc ??
By Default it's disabled so please try to enable it..

**Comment by Leonitduga** [comment]
Yes sorry i was trying to enable it but it was at miscs os smth i was
looking at vanced setings opsion and didnt find it sorry
