### ISSUE TITLE
[Bug] Vanced Manager crashes when updating Vanced

### ISSUE THREAD

**Issue by Macdom** [YTVanced/Vanced#405]
**Bug description**
When trying to update, Manager downloads: dark.apk, split_config.armeabi_v7a.apk, stock.apk, dpi.apk and split_config_en.apk. Then, the app abruptly closes.

**Variant**
Non Root

**Vanced manager version**
2.3.0

**Android version**
Android 8.1.0

**Device**
Hammer Energy 18x9

**Steps to Reproduce**
Steps to reproduce the error:
1. Open vanced manager
2. Click on 'update'

**Expected behavior**
"Install" window should pop up

**Comment by milindgoel15** [comment]
![Screenshot_20210130-213104502.jpg](https://user-images.githubusercontent.com/45682747/106361211-bd4f1500-6342-11eb-9262-9f8651a87a40.jpg)🤦‍♂️🤣🤣

**Comment by Macdom** [comment]
I picked NON ROOT each time.

Had to clear app data THREE TIMES and it somehow got through with the update. 
The issue can be closed for now, but I recommend adding it to troubleshooting page.

**Comment by X1nto** [comment]
> I picked NON ROOT each time.
> 
> Had to clear app data THREE TIMES and it somehow got through with the update.
> The issue can be closed for now, but I recommend adding it to troubleshooting page.

You can't select nonroot on each time, it's only selectable via settings
