### ISSUE TITLE
[Idea] Implementing a comment/video filter (BlockTube)

### ISSUE THREAD

**Issue by vardogor** [YTVanced/Vanced#406]
The only reason I ever use desktop YouTube anymore is [BlockTube](https://github.com/amitbl/blocktube). Being able to hide some channels and keywords is great--for example, I can filter out all those comments lately that have the words "recommended" or "algorithm" in them. If this could be implemented in a similar manner SponsorBlock was, it would be very much appreciated!

**Comment by Hyperboraeer** [comment]
I definitely support this idea. Would be a great addition to Vanced.

**Comment by takmilihsan** [comment]
A blocktube integration will be absolutely stellar! I will be able to import my options from my pc to Android. Even if it's a far stretch, having just a way to filter based on video title/channel name would be an instant improvement. Hope it gets implemented.
