### ISSUE TITLE
[Idea] Dark theme at startup

### ISSUE THREAD

**Issue by TikiPlayz** [YTVanced/Vanced#407]
The YouTube/YouTube Vanced logo when you start the app is light theme even if I have dark theme applied, please fix
![image](https://user-images.githubusercontent.com/20033421/106360614-69631280-62e7-11eb-8f13-ac834087792a.png)

**Comment by Vendicated** [comment]
Enable systemwide dark theme

**Comment by TikiPlayz** [comment]
yeah how do you do that

**Comment by Vendicated** [comment]
Android 8 and higher have this in their settings, if you're on android 7 or below then just search for dark mode in the Google play store
