### ISSUE TITLE
[Bug] glitched button

### ISSUE THREAD

**Issue by NoHqckzSkillz** [YTVanced/Vanced#410]
![Point Blur_Jan312021_220737](https://user-images.githubusercontent.com/51239705/106386973-8811f800-6412-11eb-938a-40b9051e70ce.jpg)

**Bug description**
 when you turn on the "Enable new segment adding" on "SponsorBlock settings" and you go and watch a video, when you scroll up, where various of videos will pop up, the icon/button is on the "X" button on the top right. Plz fix.

**Variant**
Non-Root

**Vanced version**
16.02.35 - Build - 01.47.00

**Android version**
Android 6.0.1

**Device**
Samsung Galaxy j7 prime

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2. Click on a YouTube video
3. Scroll Up and you'll see the Shield icon or smth under the "X" button on mobile.

**Expected behavior**
It's under the "X" button

_Attach images/videos if possible. These can be helpful in solving the issue._

**Comment by gghhkm** [comment]
This was pre-established in the description of the setting.
