### ISSUE TITLE
[Bug] Youtube Vanced doesn't load anything when signed in on Vanced

### ISSUE THREAD

**Issue by randyMC93** [YTVanced/Vanced#412]
**Bug description**
When you try to log-in on the Galaxy Tablet S7 with Youtube Vanced, it first off doesn't show you the added account, and if you restart the program youtube vanced load infinitetly unless you remove the log in via the microsoft settings. un-linking the email from Vanced MicroG.

**Variant**
Non-Root

**Vanced version**
16.02.35 - Build - 01.47.00

**Android version**
Android 10.0 One UI 2.5

**Device**
Samsung Galaxy Tab S7
**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2. Log in
3. Choose login, enter email and password
4. The Add Account Window is still blank, and if vanced is restarted, youtube vanced doesnt load anything but loops loading until you un-link the email from the vanced microG.
**Expected behavior**
I should be logged into Youtube Vanced but im actually not and cant even watch videos.

_Attach images/videos if possible. These can be helpful in solving the issue._
![image](https://user-images.githubusercontent.com/78309718/106388381-8d554f80-63de-11eb-82a3-1572309cd6a3.png)
![image](https://user-images.githubusercontent.com/78309718/106388384-97774e00-63de-11eb-87b3-22ae1a1cd6be.png)

**Comment by Vendicated** [comment]
Read https://github.com/YTVanced/Vanced/issues/396
