### ISSUE TITLE
[Bug] "BHM" has removed the "Wide search bar" feature, and now I can't search for videos, unless I disable wide search bar. Please fix this and remove these stupid logo things by YT. 

### ISSUE THREAD

**Issue by Harmonie666** [YTVanced/Vanced#414]
**Bug description**
"BHM" (BlackHistoryMonth) Logo has removed the "Wide search bar" feature, and now I can't search for videos, unless I disable Wide search bar. This issue occurs whenever YT adds a new logo. Please fix this issue. I really appreciate having the wide search bar, and now I can't use it again, because of "BHM".
Also created a [Reddit](https://www.reddit.com/r/Vanced/comments/l9y0op/bhm_has_removed_the_wide_search_bar_feature_and/?utm_medium=android_app&utm_source=share) post about it.

**Variant**
Non-Root

**Vanced version**
16.02.35 - Build - 01.47.00

**Android version**
Android 10

**Device**
ASUS ROG Phone II

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2. Enable Wide search bar 
3. There will be no search bar, and you won't be able to search for videos.

**Expected behavior**
Remove BHM Logo, and make it so YT can't add new Logos whenever they feel like.
![Screenshot_20210201-084934032 (1)](https://user-images.githubusercontent.com/73917917/106430331-ef0fcb00-646b-11eb-9ade-96e5d2eda71a.png)

**Comment by gghhkm** [comment]
#459
