### ISSUE TITLE
[Idea] Add playback speed above 2x

### ISSUE THREAD

**Issue by Vasilich1234** [YTVanced/Vanced#417]
**Description**
Hi! For my research on applying innovations in business and nonprofit activities  i'm looking for successful and not successful precedens. I'm reading a lot of books, magazine with "speedreading" and watch a lot of videos on YouTube. Most of them are useless because they have only general descriptions on the matter. And i need details so i can make "generalisation" and "deduce a rule". It take about 50 videos to find one example that i need. And i need as many examples as i could find.

I'm asking to add the playback speed above 2x to reduce time for watching YouTube videos.

In desktop i use Opera with extension that allows to have various speeds : https://addons.opera.com/ru/extensions/details/youtube-speed-control/

Thank you in advance!

**Comment by Vendicated** [comment]
for now you could use [newpipe](https://newpipe.net) to get up to 3x speed if this is something important to you

**Comment by Vasilich1234** [comment]
> for now you could use [newpipe](https://newpipe.net) to get up to 3x speed if this is something important to you

Thank you! I will try.

**Comment by Vasilich1234** [comment]
I tried NEWPIPE and i see that it doesn't have a "sing in" option and there is only option to import subscriptions from Youtube. I will test it. On my current YouTube account i have a playlist with 250 videos that i collected so far to watch. I will try to export this list to Newpipe.

> for now you could use [newpipe](https://newpipe.net) to get up to 3x speed if this is something important to you

I tried NEWPIPE and i see that it doesn't have a "sing in" option and there is only option to import subscriptions from Youtube. I will test it. On my current YouTube account i have a playlist with 250 videos that i collected so far to watch. I will try to export this list to Newpipe.

**Comment by hefty-fading-culprit-epiphany-drew** [comment]
> > for now you could use [newpipe](https://newpipe.net) to get up to 3x speed if this is something important to you
> 
> I tried NEWPIPE and i see that it doesn't have a "sing in" option and there is only option to import subscriptions from Youtube. I will test it. On my current YouTube account i have a playlist with 250 videos that i collected so far to watch. I will try to export this list to Newpipe.

You can download the Playlist using NewPipe or yt dl and use vlc to do 5x speeds

**Comment by Vasilich1234** [comment]
> > > for now you could use [newpipe](https://newpipe.net) to get up to 3x speed if this is something important to you
> > 
> > 
> > I tried NEWPIPE and i see that it doesn't have a "sing in" option and there is only option to import subscriptions from Youtube. I will test it. On my current YouTube account i have a playlist with 250 videos that i collected so far to watch. I will try to export this list to Newpipe.
> 
> You can download the Playlist using NewPipe or yt dl and use vlc to do 5x speeds

Thank you! I will try

**Comment by milindgoel15** [comment]
duplicate of #82
