### ISSUE TITLE
[Idea] Open links in Vanced

### ISSUE THREAD

**Issue by GKid94** [YTVanced/Vanced#418]
Make the app so that all YouTube links open in the Vanced app instead of YouTube

**Comment by gghhkm** [comment]
> Make the app so that all YouTube links open in the Vanced app instead of YouTube

That's impossible.

**Comment by Homura82567** [comment]
delete youtube?

**Comment by gghhkm** [comment]
> delete youtube?

He's suggesting to make it so that youtube Vanced somehow forces all links to it, which is impossible because Android doesn't work like that.

**Comment by Homura82567** [comment]
oh sorry,my bad

**Comment by Vendicated** [comment]
As said above this is not possible. You have to do it yourself. Disable/Uninstall stock youtube or go to `Settings > Apps > YouTube > Open by default > Open supported links > Don't open in this app`. Now do the same for vanced but set it to Open in this app

**Comment by GKid94** [comment]
@Vendicated Ok thx

**Comment by GKid94** [comment]
@Vendicated I changed those options and the YouTube links still open in the regular app

**Comment by gghhkm** [comment]
> @Vendicated I changed those options and the YouTube links still open in the regular app

Set Vanced as `open in this app`

**Comment by GKid94** [comment]
@gghhkm I did
