### ISSUE TITLE
[Bug] Notifications not working

### ISSUE THREAD

**Issue by PrincessFlu** [YTVanced/Vanced#419]
**Bug description**
Some, my notifications aren't working. I've checked everything, notifications are allowed and I've restarted my device and reinstalled both vanced and micro-g, no notifs

**Variant**
Non-Root

**Vanced version**
16.02.35 - Build - 01.47.00

**Android version**
Android 10

**Device**
Samsung Galaxy Note 9

**Comment by Vendicated** [comment]
Disable battery optimisations for Vanced and microG. Make sure you dont have daily digest on in your youtube notification settings. Now it should work properly
