### ISSUE TITLE
[Bug] Feed image zoom creates permanent undismissable overlay

### ISSUE THREAD

**Issue by geominorai** [YTVanced/Vanced#42]
**Description**
Home feed images can create an overlay drawn on top of the entire app that cannot be dismissed without terminating the app.

**Steps to reproduce**
1. Open the feed via the Home tab at the bottom
2. Scroll to a non-video post with a text link to a YouTube video.
3. Pinch to zoom the image, release to stop zoom.
4. Click the link to play the video

Notes:
- Repeat steps 2-3 on multiple image posts first for all of them to show up simultaneously during step 4.
- Image is still drawn alongside the mini-player when minimized via the Android home button.

**Expected behavior**
Previously zoomed images should not draw on top of a playing video.

**Screenshots**
- [screen recording](https://i.imgur.com/PFFBVlx.mp4)

**Version:**
- Vanced: 15.33.34
- microG: 0.2.12.203315
- Manager: 1.2.0
- Root: No

**Device:**
- Device: Samsung Galaxy S9+
- OS: Android 10

**Comment by milindgoel15** [comment]
Please test your issue on both the latest vanced and official youtube. If it happens on both apps, then it's a stock bug. If not, please report back soon. We are closing this issue for now.
