### ISSUE TITLE
[Idea] Add setting to stop thumbnail previews from playing

### ISSUE THREAD

**Issue by TikiPlayz** [YTVanced/Vanced#420]
I'll be trying to look at a videos thumbnail and the goddamn preview won't stop playing and it's very annoying. Please add the option to remove it in Vanced settings. TiA
https://support.google.com/youtube/answer/7074781?hl=en

**Comment by AinzTheSupremeOne** [comment]
Option to disable is right there, in the general category of Settings. Just turn off muted playback in feeds. 
![IMG_20210204_184111](https://user-images.githubusercontent.com/50095635/106897222-a6306e80-6718-11eb-9c78-6e0c18b8e80a.jpg)
