### ISSUE TITLE
[Idea] Stop YouTube from refreshing if I leave the app for a while

### ISSUE THREAD

**Issue by TikiPlayz** [YTVanced/Vanced#421]
If I'm watching a video and then I pause it and close the app for a while, whenever I open the app again it will completely refresh like the app was never even open in the first place. It closes the player and puts new videos in my recommended. This can get very annoying, if possible please make it stop refreshing unless I actually fully close the app. TiA

**Comment by AinzTheSupremeOne** [comment]
Your phone's battery/RAM optimization is killing it. When you leave the app, most process of the app is cached to RAM, except background processes which run all the time. Your system just removes the cached processes after some time of inactivity of the app, to free up the RAM and resources (CPU load). System does it more often if your phone is low end. Check your settings and exclude it from battery optimization and all kinds of optimization. It might help.
