### ISSUE TITLE
[Idea] Make YouTube vanced website associations working

### ISSUE THREAD

**Issue by JerryLiu2008** [YTVanced/Vanced#425]
I find out this problem when I realizes if I go to youtube.com or m.youtube.com, it won't redirect.
In my memory, the older versions seems have the ability to redirect. Anyways, then I go to settings/apps and find this:
![20210204_153357](https://user-images.githubusercontent.com/59402967/106951995-82f8c580-66fe-11eb-83b8-6a7fcbb14066.jpg)

Then I tapped on set default, this what I saw:
![20210204_153704](https://user-images.githubusercontent.com/59402967/106952254-dec34e80-66fe-11eb-98ff-c528c1323c41.jpg)

So, I think this leads to why the supported websites cannot redirect automatically. So I set it to In this app to prevent my chrome loading the website.
I think vanced team should fix this 'bug' , (actually is some type of enhancement) I think it was related to permissions.
Hope they can see this!

**Comment by Vendicated** [comment]
Go to Youtube's app settings and disable opening supported links, then enable it for vanced. If it still doesn't work then welp, nothing vanced can do about that since link opening is handled by your system, not the apps
