### ISSUE TITLE
[Bug] Channel/playlist (deep) linking has broken in 16.02.35

### ISSUE THREAD

**Issue by FlaminSarge** [YTVanced/Vanced#426]
**Bug description**
Clicking on a YouTube channel link with the format "https://www.youtube.com/channel/ABCDEFGH-abcdefghijklmnop" from within the app (such as from a video description) opens a web view to e.g. "https://channel/ABCDEFGH-abcdefghijklmnop". Clicking on a channel link with this format from another app does not seem to cause a deep link prompt to open in Vanced, either.

The above behavior also seems to happen with any "https://www.youtube.com/playlist?list=..." links, though I haven't tested that to as much of an extent.

Of note that /join URLs with this format work properly within the app, but it seems that just the base channel URLs do not. Also of note that the format "https://www.youtube.com/c/channel" seems to function properly. In addition, if there's any query params on the URL, it also seems to function properly (e.g. ?sub_confirmation=1). I was unable to test for differences in behavior if the URLs did have a trailing slash/ present, but I believe all the URLs I tested did _not_ have one.

**Variant**
Non-Root

**Vanced version**
16.02.35 - Build - 01.49.00

**Android version**
Android 9.0 - Pie

**Device**
Samsung Galaxy S8

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2. Navigate to a video whose description contains a URL of the format "https://www.youtube.com/channel/ABCDEFGH...". This URL must not have query parameters, and potentially must not have trailing slashes either.
3. Select that URL to open that channel link.

**Expected behavior**
The app opens a web view to "https://channel/ABCDEFGH..." (which does not load as it is not a valid URL) where instead it should have opened the channel page directly in the app.

**Comment by eldon97** [comment]
this bug occur in my device too..
