### ISSUE TITLE
[Bug] Cannot switch accounts

### ISSUE THREAD

**Issue by yannishams** [YTVanced/Vanced#427]
**Bug description**
When i click on switch accounts, none of my other accounts show up

**Variant**
Non-Root

**Vanced version**
16.02.35 - Build - 01.47.00

**Android version**
Android 10

**Device**
Poco X3 NFC

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2. Click on the profile icon
3. Click on switch accounts

**Expected behavior**
When i click on "switch account" on the youtube app (not the vanced one), it shows me the other accounts i can switch to.
![IMG_20210205_190606](https://user-images.githubusercontent.com/78600628/107037404-3b009e00-67e5-11eb-9915-8f9ef9e963d0.jpg)

**Comment by Vendicated** [comment]
known issue and duplicate issue. Will be fixed as soon as upstream microg fixes it. Downgrade for now if you need this
