### ISSUE TITLE
[Bug] video auto pauses after 15 minutes from turing off my phone (Android 9)

### ISSUE THREAD

**Issue by Romeo1691** [YTVanced/Vanced#428]
**Bug description**
Replace me with a clear and detailed description of the bug.

**Variant**
Non-Root/Root

**Vanced version**
16.02.35 - Build - 01.47.00

**Android version**
Android 9.0 - Pie

**Device**
Samsung Galaxy S8

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
3. ....

**Expected behavior**
Replace me with a description of what you expected should happen and what happened instead.

_Attach images/videos if possible. These can be helpful in solving the issue._

**Comment by Vendicated** [comment]
https://dontkillmyapp.com/samsung
