### ISSUE TITLE
[Idea] Option to remove the bar with channel icons from the subscriptions tab.

### ISSUE THREAD

**Issue by MeatToboggan47** [YTVanced/Vanced#430]
On my phone and probably many others, when it's in landscape and I'm trying to scroll up through the videos from channels I'm subscribed to, I can only see 1 video at a time. It's a little less of an issue in the portrait orientation, but it still takes up a lot of space. If the bar that shows the thumbnails and the bar that lets you sort which videos show up was removed or had an option to be removed, it would be much more convenient.

**Comment by vrindavan** [comment]
-1
