### ISSUE TITLE
[Bug] replaceme

### ISSUE THREAD

**Issue by Potatotot123** [YTVanced/Vanced#431]
**Bug description**
It will play music in the background, and then after a few songs it just stops. I have to go back to the app and pick a new song, I can't even hit play from the one before. It has done this for about a week now 

**Variant**
Non-Root/Root

**Vanced version**
16.02.35 - Build - 01.47.00

**Android version**
Android 9.0 - Pie

**Device**
Samsung Galaxy S8

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
3. ....

**Expected behavior**
Replace me with a description of what you expected should happen and what happened instead.

_Attach images/videos if possible. These can be helpful in solving the issue._

**Comment by Vendicated** [comment]
https://dontkillmyapp.com/samsung
