### ISSUE TITLE
[Bug] replaceme

### ISSUE THREAD

**Issue by Leonitduga** [YTVanced/Vanced#437]
**Bug description**
When i open any vanced youtube videos the video isnt showing up it is just black screen. 

**Variant**
Non-Root

**Vanced version**
16.02.35

**Android version**
Android 10

**Device**
Huawei p20

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2. Click on any video
3. Then the video screen isnt showing up only black screen

https://drive.google.com/file/d/1A6JqiK-KMWZmoosD6mAOfZfPfblEvs7L/view?usp=drivesdk 

Please fix this bug its happening allways.

**Comment by RSTZ93** [comment]
Same

**Comment by Vendicated** [comment]
clean reinstall & reboot should fix it.
