### ISSUE TITLE
[Bug] replaceme

### ISSUE THREAD

**Issue by RSTZ93** [YTVanced/Vanced#438]
**Bug description**
I cant use youtube vanced anymore cause it said no connexion , youtube normal is working

**Variant**
Non-Root

**Vanced version**
16.02.35 - Build - 01.47.00

**Android version**
Android 10

**Device**
Samsung Galaxy S20+

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2. Click on anything
3. It said there is no connexion 

**Expected behavior**
Replace me with a description of what you expected should happen and what happened instead.

_Attach images/videos if possible. These can be helpful in solving the issue._
![Screenshot_20210207-192833](https://user-images.githubusercontent.com/78699877/107155797-b051a780-697a-11eb-8d6b-43f7c9847b29.jpg)

**Comment by Vendicated** [comment]
#396
