### ISSUE TITLE
Automatic resize when landscape fails

### ISSUE THREAD

**Issue by riffamyno** [YTVanced/Vanced#439]
I set my phone's density to 200 (wm density 200). When the resolution is this small, it breaks vanced to when turning phone into landscape mode doesn't automatically full screen the video. I took the time to where it breaks

The last density setting it full screens on rotate is 289 (wm density 289).anything with 288 or lower doesn't work. 

Please fix it to fill screen regardless of the density

**Comment by Vendicated** [comment]
https://support.google.com/youtube/answer/4347644
