### ISSUE TITLE
[Bug] Another day, another new logo that has removed the "wide search bar" feature....

### ISSUE THREAD

**Issue by Harmonie666** [YTVanced/Vanced#441]
Just like with the BHM Logo this new Logo has now removed the "wide search bar" vanced feature aswell. Means there is no search button anymore, and I'm unable to search for videos, unless I disable wide search bar.
Please devs make it somehow impossible for YT to add new Logos to their app! They are doing this frequently, and it's fucking annoying me so much, when it removes my wide search bar! Give us the option to disable new Logos added by YT. 
I also created a [Reddit](https://www.reddit.com/r/Vanced/comments/lf84cr/just_like_with_the_bhm_logo_this_new_logo_has_now/?utm_medium=android_app&utm_source=share) Post that has gotten alot of attention.
BHM GitHub post:
https://github.com/YTVanced/Vanced/issues/414#issue-798080891

**Variant**
Non-Root

**Vanced version**
16.02.35 - Build - 01.47.00

**Android version**
Android 10

**Device**
ROG Phone II

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2. Enable Wide search bar in Vanced Layout settings
3. Search bar is gone!
![Screenshot_20210208-100839660 (1)](https://user-images.githubusercontent.com/73917917/107199077-3ced7b80-69f6-11eb-8646-b86cf0d3d58b.png)

**Comment by gghhkm** [comment]
#459
