### ISSUE TITLE
[Bug] Accounts aren't showing, so can't switch

### ISSUE THREAD

**Issue by moehammm** [YTVanced/Vanced#442]
When I press on the account icon on the top right corner to navigate between accounts, nothing is showing, it's only the one that I left open in the previous version. Deleted the accounts from phone to re login again, logged in but still accounts aren't showing

**Comment by subsevenx** [comment]
Hey, looks like the issues has been reported a bit (per #427.) I *just* had the issue and the solution was downgrading to the previous version of Vanced via the manager. Hope it helps.

**Comment by Vendicated** [comment]
Duplicate. Downgrade for now until the microg dev fixes it
