### ISSUE TITLE
[Bug] Google Apps accounts cannot log in

### ISSUE THREAD

**Issue by alexwh** [YTVanced/Vanced#443]
**Bug description**
Attempting to sign in to a Google Apps backed account with a custom domain in Vanced either through MicroG or the app itself results in a "please check your network connection" error. Signing in to a regular Google account works fine.

I've tried the standard FAQ advice to no avail:
I removed the MicroG account, uninstalled both Vanced and MicroG, rebooted, reinstalled MicroG then Vanced.

Also tried removing 2FA and disabling battery optimization for both MicroG and Vanced (was not needed before), as well as disabling the system wide OnePlus battery optimization (Adaptive Battery and Sleep standby optimisation). I have not changed my Google security settings recently, other than to remove 2FA as suggested by the FAQ.

**Variant**
Non-Root

**Vanced version**
15.43.32 - Build - 01.47.00
MicroG version - 0.2.16.204713

**Android version**
Android 10

**Device**
OnePlus 7 Pro

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2. Sign in to a Google Apps account

![Screenshot_20210209-062528](https://user-images.githubusercontent.com/1723612/107324539-256acd00-6aa0-11eb-9f83-f47dc6c5f9ec.jpg)

**Comment by faded714** [comment]
Man my issue says "There was a problem communicating with google servers." 

I already tried reinstalling apks and removing to readd my google account on android.

**Comment by gghhkm** [comment]
#396

**Comment by alexwh** [comment]
> 
> 
> #396

I had previously followed the advice in this issue to no avail, but since updating the Vanced Manager to the latest version (2.5.0), it works fine now.
