### ISSUE TITLE
[Bug] internet fix

### ISSUE THREAD

**Issue by Robert9617** [YTVanced/Vanced#444]
**Bug description**
Replace me with a clear and detailed description of the bug.

**Variant**
Non-Root

**Vanced version**
16.02.35 - Build - 01.47.00

**Android version**
Android 9.0 - Pie

**Device**
Samsung note 8

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2. And tell me , i not have internet connection,  here is the screenshot  
! (Screenshot_20210209-120749](https://user-images.githubusercontent.com/78793318/107348308-852c9c80-6acf-11eb-8aa3-795990f046a3.jpg)

**Expected behavior**
Replace me with a description of what you expected should happen and what happened instead.

_Attach images/videos if possible. These can be helpful in solving the issue._

**Comment by imisugipuladegunoideaplicatie** [comment]
Same here

**Comment by Vendicated** [comment]
Check pinned issue
