### ISSUE TITLE
[Bug] multiple accounts yt vanced

### ISSUE THREAD

**Issue by w-kok** [YTVanced/Vanced#445]
Please only report your issue here, if all points below are true

I installed the App from vancedapp.com, this github repository or the Vanced Discord server
I am using the latest version
This is an issue in the Vanced Manager app (NOT Youtube Vanced)
This issue keeps re-occurring every time I try
For MIUI users: I disabled MIUI optimisation
Phone Specifications:

Brand: samsung
Operating System: os11-R & one ui3
Android Version: 11
Vanced Manager Version: 2.4.0
Please describe the problem you are having in as much detail as possible:

Steps to reproduce:
(reboot between each step to be sure)
install micro G
install yt vanced
add account 1
add account 2
account 2 never shows up in yt vanced, but microG shows added.

Further details:
Already removed and reinstalled all steps, problem occurred after update.

**Comment by gghhkm** [comment]
#427
#442
