### ISSUE TITLE
[Bug] brightness doesn't go to zero

### ISSUE THREAD

**Issue by toppk** [YTVanced/Vanced#446]
**Bug description**
Since getting a new phone/OS , swipe brightness doesn't go to zero.  I can adjust brightness up and down, but going all the way to zero, actually sets brightness to the system brightness level.

This worked on old os/phone combo but something about this new phone breaks this.

only thing in logcat related to this are these lines:

when I go from any high value to zero (swipe all the way down):
02-09 15:37:52.229  1228  1336 V DisplayPowerController: Brightness [255] reason changing to: 'manual', previous reason: 'override'.

when I swipe up from "off" position:

02-09 15:37:53.545  1228  1336 V DisplayPowerController: Brightness [5] reason changing to: 'override', previous reason: 'manual'.

These lines only come when leaving or entering the lowest ("off") position.  The number in [brackets], seem to indicate a brightness level.

**Variant**
Root

**Vanced version**
16.02.35 - Build - 01.47.00

**Android version**
Android 10 - (LineageOS)

**Device**
OnePlus 7 Pro

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2. Enable swipe controls
2. Click on any video 
3. swipe brightness down to zero

**Expected behavior**
Screen should go blank.  Screen goes to full brightness.

**Comment by rud-boy** [comment]
Same here, can reproduce it to the letter using a Redmi Note 8 with LineageOS, so I guess it has something to do with the ROM
