### ISSUE TITLE
[Idea] option to disable Information panel giving topical context

### ISSUE THREAD

**Issue by toppk** [YTVanced/Vanced#447]
**Description**
Some topics youtube feels it is necessary to push a political agenda.  They call this "Information panel giving topical context".  It would be nice to be able to remove this from viewing.  Any video in the US on elections, covid, climate change, even the moon landing have such propaganda.

**Comment by Theta-Dev** [comment]
Yeah, I'd definitely like to see that implemented in YT Vanced.
I dont know why you would call Wikipedia links about flat earth, covid, climate change, etc. "propaganda", but it just seems annoying and patronizing to have these infocards put there.
As if YT thinks that people cant form an opinion on their own.

**Comment by AinzTheSupremeOne** [comment]
I don't like them either, especially the covid-19 banners. Example video: https://youtu.be/yB4lpwBwxYk
![IMG_20210430_143346](https://user-images.githubusercontent.com/50095635/116676739-f8ee8f00-a9c4-11eb-82ca-229611a981c0.jpg)

Would be nice to have a toggle to remove this 😁

**Comment by AinzTheSupremeOne** [comment]
Kevin stop being gay and trying to close this issue

**Comment by darthnater4ever** [comment]
Unstale pls
