### ISSUE TITLE
[Bug] YouTube Vanced crash

### ISSUE THREAD

**Issue by GKid94** [YTVanced/Vanced#451]
**Bug description**
YouTube Vanced crashes on background play

**Variant**
Non-Root

**Vanced version**
16.02.35

**Android version**
Android 6.0.1

**Device**
Samsung Galaxy A5 2015

**Comment by VancedOfficial** [comment]
Can't do anything with this information. Needs crash logs as a minimum. The bug template was there for a reason.

**Comment by GKid94** [comment]
@VancedOfficial How do I create the logs?
