### ISSUE TITLE
Max resolution override not working

### ISSUE THREAD

**Issue by pranshuthegamer** [YTVanced/Vanced#452]
so i have a tablet that by default shows 1080p but i wanted to watch 4k videos in 4k so i turned on the override and it still wont work
and IM 100% SURE that the video i want to watch is in 2160p

**Device** Huawei mediapad M3

**vanced version** i dunno its the latest one

**Comment by gghhkm** [comment]
The ability to play 4k and 2k videos still pretty much depends on the phone's hardware. Not only that, but YouTube also intentionally imposes server side restriction to prevent users from streaming higher quality videos (like how it did in India last year where users were stuck with 480p videos, even the YouTube premium subscribers). Also, if the screen isn't 2k/4k resolution it would just be downscaled to your device screen resolution wasting bandwidth.
