### ISSUE TITLE
[Bug] Installation Error

### ISSUE THREAD

**Issue by ValiLuzifer** [YTVanced/Vanced#453]
**Bug description**
If I try to install Vanced i get the message "Installation failed because the user tried to downgrade the package. Unistall updates from the stock app, then try again. But I dont have vanced installed right now so how am i supposed to downgrade

**Variant**
Non-Root

**Device**
Huawei Mate 20 Light

**Comment by AinzTheSupremeOne** [comment]
Try following these instructions https://gist.github.com/Vendicated/e66d26a48b389023b99b44a45e46fdea
