### ISSUE TITLE
[Bug] Links will be opened when they are at the end of Community posts ("Reas More" button doesnt work).

### ISSUE THREAD

**Issue by LennDoMations** [YTVanced/Vanced#456]
**Bug description**
If a community post or any text in youtube where you can click "read more"has a link in it it will open that link and you cant read more.

**Variant**
Root

**Vanced version**
16.02.35 - Build - 01.49.00

**Android version**
Android 10 - Q

**Device**
Xiaomi Mi 9T Pro  (Europe) // Redmi K20 Pro

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2. Find community post with link before "read more"

**Expected behavior**
You press "read more" and text expands  But Link will be opened. Post doesnt expand.

**Comment by VancedOfficial** [comment]
I believe this is YouTube bug rather than Vanced bug. Also try clicking somewhere in the post where there's text and not link, I believe you don't have to click "Read more" to expand it.
