### ISSUE TITLE
[Bug] remind me to take a break

### ISSUE THREAD

**Issue by neptr34** [YTVanced/Vanced#464]
**Bug description**
Im using vanced to fall asleep.
One day when i woke op, my phone was still playing videos.
I found that the setting 'time watched' was missing, and under it is the 'remind me to take a break'

I would like to see 'remind me to take a break' come back.
And maybe with an option to enable it after a 'set time'.
Also, it could be neat if a reset button comes on, say 30 sec before it stops the video.

Best regards,

**Variant**
Non-Root

**Vanced version**
16.02.35 - Build - 01.47.00

**Android version**
Android 9.0 - Pie

**Device**
Samsung Galaxy S8

**Comment by fndrsm** [comment]
Can u turn off 'remind me to take a break'.
![Screenshot_20210218-222930](https://user-images.githubusercontent.com/48046968/108379760-d1e34680-7238-11eb-8ab6-1abfe828b594.jpg)

**Comment by neptr34** [comment]
I can turn it off( in general settings ), but makes no difference. It does not stop playing after the time i asked for.
- i did try a fresh install of both microg and vanced.

**Comment by neptr34** [comment]
Update:
Got it to work now.
Cant tell what did it, been turning the setting on and off, cleraing cache and so on. Ealier on, i also did a fresh install.

Will make a suggestion on the things i mentioned.


 Thanks for the feedback fndrsm!

**Comment by adelneo** [comment]
I fixed this issue by removing cash and data, it showed up
