### ISSUE TITLE
[Bug] unable to connect with google services/log in

### ISSUE THREAD

**Issue by ianj39** [YTVanced/Vanced#465]
**Bug description**
When the update came out yesterday I logged in later and was advised there was no Internet connection. After testing this on my WiFi and mobile data it seems to be an issue with communications with Google. I uninstalled everything and re-installed but my account will not log in. Vanced still works fine without an account logged in, it was only when I was logged in it would not work (and now it will not connect, saying try again later ) 

**Variant**
Non-Root

**Vanced version**
16.02.35 - Build - 01.47.00

**Android version**
Android 9.0 - Pie

**Device**
Samsung Galaxy S8

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
3. ....

**Expected behavior**
Replace me with a description of what you expected should happen and what happened instead.

_Attach images/videos if possible. These can be helpful in solving the issue._

**Comment by dgudim** [comment]
Same issue

**Comment by Vendicated** [comment]
Check the pinned issue.
