### ISSUE TITLE
[Bug] Hard embeded caption incorrectly display

### ISSUE THREAD

**Issue by TanagiMS** [YTVanced/Vanced#466]
**Bug description**
I found out that some video with hard embeded captions is display incorrectly when I update Vanced to latest version

**Variant**
Non-Root

**Vanced version**
16.02.35 - Build - 01.49.00

**Android version**
Android 9.0 - Pie

**Device**
Realme 2

**Steps to Reproduce**
None

**Expected behavior**
The vids suppose to display 2 lines of captions: one top one bottom but it only display the top caption. Example vid: https://youtu.be/3qkXc6zheig

![IMG_20210217_230604](https://user-images.githubusercontent.com/32317350/108232509-713f0580-7175-11eb-844d-0c3e2bd5e366.jpg)
![IMG_20210217_230642](https://user-images.githubusercontent.com/32317350/108232565-7ef48b00-7175-11eb-832b-c00eeb9c1292.jpg)

**Comment by TanagiMS** [comment]
Update: It seem like the lasted version of normal Youtube also bugged, don't know why

**Comment by gghhkm** [comment]
I'm going to close this for now, If it's still bugged when the next Vanced release build comes out feel free to reopen this. Also you should go to [The Vanced Discord](https://discord.gg/rgwbXEaUCb) to trouble shoot.
