### ISSUE TITLE
[Bug] Watch History & Brand Accounts

### ISSUE THREAD

**Issue by fritolays** [YTVanced/Vanced#467]
**Bug description**
Watch history does not update when using a youtube brand account.

**Variant**
Non-Root

**Android version**
Android 9.0 and 11

**Device**
Tab S and Tab S5e

**Steps to Reproduce**
Steps to reproduce the error:
1. Follow standard non-root install via manager
2. Login
3. Watch random video
4. Check watch history for said video

**Expected behavior**
Video should tracked in history but isnt.

**Further details:**
There is currently a warning in the manager app to install version 15.43.32 first to be able to login. However, this version doesn't enable watch history for brand accounts. I found only version 14.21.54 will connect the account properly. Once logged in you can update Vanced to latest without issue.

Just to note, I tried microg version 0.2.6.17455 and 02.16.204713 and both work fine. So I suspect the issue is withing Vanced builds after 14.21.54.

**Comment by gghhkm** [comment]
Could be an issue with your Adblocker (e.g. Adaway) if you have one.
You need to whitelist `s.youtube.com`
feel free to reopen this if my assumption is incorrect. 

You can also go here for additional guidance.
[Official Vanced Discord Invitation](https://discord.gg/rgwbXEaUCb)
[Message Link](https://discord.com/channels/328493314485518336/358967876193091584/809525073903616022)

**Comment by fritolays** [comment]
I disabled/removed all blocking while testing.
Sorry I neglected to note that.

Either way, my workaround fixed it.

**Comment by fritolays** [comment]
> 
> 
> Could be an issue with your Adblocker (e.g. Adaway) if you have one.
> You need to whitelist `s.youtube.com`
> feel free to reopen this if my assumption is incorrect.
> 
> You can also go here for additional guidance.
> [Official Vanced Discord Invitation](https://discord.gg/rgwbXEaUCb)
> [Message Link](https://discord.com/channels/328493314485518336/358967876193091584/809525073903616022)

I disabled/removed all blocking while testing.
Sorry I neglected to note that.

Either way, my workaround fixed it.
