### ISSUE TITLE
[Bug] Vanced keep changing theme it self.

### ISSUE THREAD

**Issue by fndrsm** [YTVanced/Vanced#469]
**Bug description**
App theme changing it self, from dark to white.

**Variant**
Non-Root

**Vanced version**
15.43.32

**Android version**
Android 8.0 - Oreo

**Device**
Samsung Galaxy S7 Edge

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2. And theme back to white
3. Changing to black again
4. Open again after a while, and the theme back to white

**Expected behavior**
It just happen tonight. FEB 18 2020. I was open the app, and vanced back to white theme. So i swith to dark, and i closed, after couple minutes, i open again, and it back to white theme again.

_Attach images/videos if possible. These can be helpful in solving the issue._

**Comment by RandomGuyJCI** [comment]
I've been having the same issue for 2 days, except now I can't even enable dark mode anymore. It gives a "Please check your network connection" error when I try to change the toggle

Version and Device: Root 16.02.35, Samsung Galaxy J5 on Android 5.1.1

Screenshots: 
![image](https://user-images.githubusercontent.com/22722393/109407102-303ac280-79b9-11eb-868d-36330d535ff2.png)
![image](https://user-images.githubusercontent.com/22722393/109407109-3af55780-79b9-11eb-988e-af532046784a.png)

Logcat file:
[logcat.txt](https://github.com/YTVanced/Vanced/files/6056239/logcat.txt)

**Comment by KevinX8** [comment]
Fixed in 16.16.38
