### ISSUE TITLE
[Bug] replaceme

### ISSUE THREAD

**Issue by thedarknight039** [YTVanced/Vanced#471]
**Bug description**
The pop up screen starts on the down right side of the screen. And when I try to move it up it just flies down and disappears. When i turn the phone sideways I can see it. When it disappears I also can't see it on the notifications

**Variant**
Non- root

**Vanced version**
16.02.35 - Build - 01.47.00

**Android version**
Android 11

**Device**
Samsung Galaxy S10+

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
3. ....

**Expected behavior**
That I can move the pop up video to any side of the screen

**Comment by sciento149** [comment]
I have the same issue. Galaxy NOTE 10+ 5G.Android 10 UI3.0.

**Comment by Vendicated** [comment]
Picture In Picture is Rom dependant. Go bug Samsung

**Comment by thedarknight039** [comment]
What?

**Comment by Vendicated** [comment]
the floating player is called picture in picture. this is manged by your system, vanced has no control over it. if your pip has issues, it's your system. So go blame Samsung.

For some Samsung users this was fixed by rebooting to recovery (ask Google) and clearing cache

**Comment by thedarknight039** [comment]
I didn't touch any setting in the last 3 months. One day it just started
doing that
