### ISSUE TITLE
[Bug] replaceme

### ISSUE THREAD

**Issue by Kiregamo** [YTVanced/Vanced#472]
**Bug description**
Can't install in my device (android 10, MIUI 12), i try all version youtube vanced but still can't install, please fix it soon

**Variant**
Non-Root

**Vanced version**
16.02.35 - Build - 01.47.00

**Android version**
Android 10.0 - Q

**Device**
Xiaomi Redmi Note 9 Pro

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
3. ....

**Expected behavior**
I can install with normal in android 10, MIUI 12

_Attach images/videos if possible. These can be helpful in solving the issue._

**Comment by Vendicated** [comment]
Join one of our social channels for support
