### ISSUE TITLE
Higher resolution videos not able to play on realme 7i (i already enabled higher resolution videos settings and also change video format i ll try all the settings regarding higger resolution videos but its not working and also when sing in google ac content is not loding  [Bug] replaceme

### ISSUE THREAD

**Issue by shubhammohite00011** [YTVanced/Vanced#474]
![Screenshot_2021-02-20-11-14-16-31_7a4090f09f6554852d748ee9fd6f40d3](https://user-images.githubusercontent.com/79350599/108585173-e7f22380-736c-11eb-8987-45ba29c7fe4b.jpg)
![Screenshot_2021-02-20-11-14-22-95_7a4090f09f6554852d748ee9fd6f40d3](https://user-images.githubusercontent.com/79350599/108585174-e9bbe700-736c-11eb-9b26-5f2a5343e3ca.jpg)
![Screenshot_2021-02-20-11-13-54-04_7a4090f09f6554852d748ee9fd6f40d3](https://user-images.githubusercontent.com/79350599/108585175-ea547d80-736c-11eb-90bf-6b841bf9f0e1.jpg)

**Bug description**
After enabling MAX resolution option - 1440p and 2160p option is not visible for 2k and 4k video 
**Variant**
Non-Root

**Vanced version**
16.02.35 - Build - 01.47.00 - letest

**Android version**
Android 9.0 - Pie

**Device**
Realme 7i Indian varient ( sd 662) 

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
3. ....

**Expected behavior**
After enabling the max resolution videos option supported 2k or 4k  video should play in higger resolution

_Attach images/videos if possible. These can be helpful in solving the issue._

**Comment by gghhkm** [comment]
1. the ability to play 4k and 2k videos pretty much depends on the phone's hardware. Not only that, but YouTube also intentionally imposes server side restriction to prevent users from streaming higher quality videos (like how it did in India last year, all indian users were stuck in shitty 480p videos, even the YouTube premium subscribers). Also, if you don't have a screen of 2k/4k resolution, it would just be downscaled to your phone's screen resolution anyway. 
2. read the pinned Issue.
