### ISSUE TITLE
[BUG] APP not loading when you opened

### ISSUE THREAD

**Issue by Leonitduga** [YTVanced/Vanced#475]
**Bug description**
App not loading when you open it. 

**Variant**
Root

**Vanced version**
16.02.35

**Android version**
Android 10

**Device**
Huawei P20

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
3. ....

**Expected behavior**
It should load the videos on the main theme vut it isnt oppening anything at all. 

![Screenshot_20210220_160515_com vanced android youtube](https://user-images.githubusercontent.com/78247865/108600473-b0e53780-7397-11eb-9d7a-9d2b92bbc92e.jpg)

**Comment by walout** [comment]
Hello,

I have the same issue with my Huawei P30 Light :

Variant
non-Root

Vanced version
16.02.35

Android version
Android 10

Device
Huawei P30 Light 


I downgraded to 15.43.32 version.

**Comment by bi00dw0rk** [comment]
Same thing with a Samsung Galaxy S21 Ultra 5G. Seems like it doesn't matter which phone it is or if it's the rooted or non rooted Version. Only similarity I can see on first glance is the App Version 16.02.35. Probably just needs a hotfix.

**Comment by Leonitduga** [comment]
Yes i noticed that so i uninstalled the app and dowloaded another version
not the 16.

Thank you for your time

**Comment by Vendicated** [comment]
Read the pinned issue.
