### ISSUE TITLE
[Idea] Add 4K support

### ISSUE THREAD

**Issue by TikiPlayz** [YTVanced/Vanced#477]
YouTube mobile doesn't have options for 1440p and 2160p, please add them if possible.
![image](https://user-images.githubusercontent.com/20033421/108630567-6618fd80-7433-11eb-8276-0a4b66c98e84.png)
![image](https://user-images.githubusercontent.com/20033421/108630573-6ca77500-7433-11eb-9e67-fd25241a27cc.png)

**Comment by AinzTheSupremeOne** [comment]
Enable max resolution in Vanced settings > video settings. And 2k and 4k still might not appear in the option list, as the ability to play 4k and 2k videos still pretty much depends on the phone's hardware. Not only that, but YouTube also intentionally imposes server side restriction to prevent users from streaming higher quality videos (like how it did in India last year, all indian users were stuck in shitty 480p videos, even the YouTube premium subscribers). Also, just so you know, if you don't have a screen of 2k/4k resolution, it would just be downscaled to your phone's screen resolution.
