### ISSUE TITLE
[Bug] can't even sign in

### ISSUE THREAD

**Issue by semhdmr24** [YTVanced/Vanced#479]
**Bug description**
When i try to sign in it doesn't let me do it. İt says "check your connection try again" when i do it apeears back in less than a second. Because of that i can't log in.

**Variant**
Non-Root

**Vanced version**
16.02.35

**Android version**
Android 8.1 

**Device**
Meizu x8

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2. Click on account logo in right top
3. click sign in

**Expected behavior**
İ expected that it would let me sign in.

_Attach images/videos if possible. These can be helpful in solving the issue._

**Comment by gghhkm** [comment]
Not a bug with Vanced.
https://github.com/Vendicated/Vanced/blob/master/Guides/VancedLoadingFix.md
