### ISSUE TITLE
[Idea] Hide videos from certain channels

### ISSUE THREAD

**Issue by leodoi3** [YTVanced/Vanced#48]
I would like a feature to block videos from specific channels that I can't normally remove from explore and other pages. Additionally I would like to block from appearing in search results.

Also: If I click on a YouTube link that's in my blocked channels, show me a warning.

**Comment by adrifcastr** [comment]
I second this, shouldn't be hard, just need to store the blocked CIDs somewhere and then when loading search results/reccommendations check against the saved CIDs

**Comment by leodoi3** [comment]
Bump.
