### ISSUE TITLE
[Bug] OSD controls are frozen.

### ISSUE THREAD

**Issue by RebelliousX** [YTVanced/Vanced#480]
**Bug description**
YouTube Vanced v16.02.35 on Shield TV running Android 10, v15.43.32 was working fine. As you can see from the video, the controls for the Play or Pause, Next or Previous and even the 3 vertical dots menu  on top right are not responsive! The controls won't go away no matter how long you wait, as usually it takes about 3 seconds to auto hide.
**Variant**
Non-Root/Root

**Vanced version**
16.02.35 - Build - 01.47.00

**Android version**
Android 10

**Device**
Shield TV Pro 2019

**Steps to Reproduce**
Randomly doing this, but once this happens, it will keep doing it after after reboot. I had to downgrade to latest offering of v15 to fix it. 

**Expected behavior**
For on-screen display to auto hide, the 3 vertical dot menu on top right to be working. For the controls to respond to the mouse.

**See the Video below**
Click on the link or thumbnail.

https://youtu.be/MrNcNUjSHlI

[![](http://img.youtube.com/vi/MrNcNUjSHlI/0.jpg)](http://www.youtube.com/watch?v=MrNcNUjSHlI "Youtube Vanced v16")

**Comment by AinzTheSupremeOne** [comment]
YouTube Vanced is not optimised for Android TV, so it might not work. Please use an alternative (like Smart YouTube TV).

**Comment by RebelliousX** [comment]
I really hate the layout of the Youtube for Android TV. Since it s not intuitive when using a mouse.

It is okay, I prefer Vanced, I got it working, it seems carrying settings from v15 to v16 caused the problem.
I left all settings to default after uninstalling and reinstalling v15 then upgraded to v16. It seems it is fixed.

As a side note, Vanced works fine on Android TV the same way it works for phones, the layout is the same.
All I had to do to make it appear like the layout on phones is by changing the DPI from 240 to 288.
Changing DPI does not require root, just an app to change dpi and adb command to this.
And there is no need to connect it to computer to do this, using remote adb through WIFI
and running the ADB commands directly from Shield TV. I chose 288 as it is the sweet spot for Nvidia to allow
me to use the Nvidia Share feature on the shield. Anything higher Nvidia Share menu won't even show up.

**Comment by BobbyBabes** [comment]
> I really hate the layout of the Youtube for Android TV. Since it s not intuitive when using a mouse.
> 
> It is okay, I prefer Vanced, I got it working, it seems carrying settings from v15 to v16 caused the problem. I left all settings to default after uninstalling and reinstalling v15 then upgraded to v16. It seems it is fixed.
> 
> As a side note, Vanced works fine on Android TV the same way it works for phones, the layout is the same. All I had to do to make it appear like the layout on phones is by changing the DPI from 240 to 288. Changing DPI does not require root, just an app to change dpi and adb command to this. And there is no need to connect it to computer to do this, using remote adb through WIFI and running the ADB commands directly from Shield TV. I chose 288 as it is the sweet spot for Nvidia to allow me to use the Nvidia Share feature on the shield. Anything higher Nvidia Share menu won't even show up.

Does the DPI workaround still work today?

**Comment by RebelliousX** [comment]
Yes.
