### ISSUE TITLE
cant sign in android 11

### ISSUE THREAD

**Issue by LedzCop** [YTVanced/Vanced#482]
Hello i have android 11 (Galaxy note 10 lite). i cant sign in anynore. i reinstaled microg and vanced more times, signe in again, but after callback there are not showen my account in vanced app and in microg also. when im trying to sign in again from vamced app, its telling me that username already exists on that account, but when im going back in vanced app there are no my gmail account.

**Comment by gghhkm** [comment]
https://github.com/YTVanced/Vanced/issues/396
