### ISSUE TITLE
[Bug] Unable to install old version of Youtube Vanced although no Youtube Vanced installed

### ISSUE THREAD

**Issue by L-W-J1** [YTVanced/Vanced#483]
Recently MicroG is having issue and caused Youtube Vanced to not loading any video so I follow this guide #396 (which required to install old Youtube Vanced) but I can't install old version of Youtube Vanced (refer to the screenshot below) although I don't have any Youtube Vanced installed. Installing latest version of Youtube Vanced have no issue.
![Vanced](https://user-images.githubusercontent.com/79555758/108941464-21d66900-7690-11eb-8c4d-ca1f5c8042c0.jpg)

**Comment by gghhkm** [comment]
This should [Fix](https://github.com/Vendicated/Vanced/blob/master/Guides/INSTALL_FAILED_UPDATE_INCOMPATIBLE.md) it.
