### ISSUE TITLE
[Bug] Account list blank after signing in

### ISSUE THREAD

**Issue by rico-387** [YTVanced/Vanced#484]
After I sign into my account, the account list doesn't show it, only the add account button. If I try and add it again, it tells me that the account is already on my device. I've tried reinstalling and redownloading and rebooting several times.

**Comment by gghhkm** [comment]
#396 
https://github.com/YTVanced/Vanced/issues/396#issuecomment-785298600

**Comment by datthureddy** [comment]
as they mentioned before i have alogin issue. I can't login to my account even if i add my mail id it is showing the account already exists in this device amd the account field in the youtube section shows none. please do something about this.

**Comment by gghhkm** [comment]
@datthureddy plz use the links provided above.
