### ISSUE TITLE
[bug] Video progression not saved

### ISSUE THREAD

**Issue by KelianS** [YTVanced/Vanced#485]
Version : 16.02.35, version root, YT vanced.

Since the last update i've noticed that all the videos already seen are showing on my recommandation. 
And if i go to a video go the middle of it, then exit, the progression is not saved on my account.
The progression seems to not be saved in my account. 
Am I the only one ? It's a bit annoying to get notification for a video that i already saw 🤔

Thanks

**Comment by gghhkm** [comment]
It's possible that it's just not saving to history and in that case check your adblocker if you have one and whitelist `s.youtube.com`

**Comment by AinzTheSupremeOne** [comment]
> Since the last update i've noticed that all the videos already seen are showing on my recommandation.
That's a normal behaviour of YouTube, especially in case of music videos. **They want you to watch again the videos you have already watched.** 
![Screenshot_2021-02-25-11-26-24-247_com google android youtube](https://user-images.githubusercontent.com/50095635/109110128-86f79080-775c-11eb-97f1-a81c8d614f44.jpg)

As you can see from the above screenshot from stock YouTube app (not Vanced), I _have already watched_ One in a million music video (the read line just above the video title indicates that). And YouTube video progression/history is always saved in your account, unless you have disabled watch history for YouTube or disabled YouTube history entirely in Google account privacy settings. And it can also be blocked automatically by adblockers (which is often an issue with Adaway adblocker app) as gghhkm mentioned above.

**Comment by KelianS** [comment]
> It's possible that it's just not saving to history and in that case check your adblocker if you have one and whitelist `s.youtube.com`

Thanks a lot, that was it. My shitty AdGuard was unabled to whitelist 's.youtube.com'. I came back to AdAway and it's all good.
Thanks again, i close this thread.
