### ISSUE TITLE
[Question] replaceme

### ISSUE THREAD

**Issue by joseph11q3** [YTVanced/Vanced#487]
I'm sorry if in writing this in the wrong section but  I'm new to all of this. I've downloaded YouTube vanced before and it worked fine , however my phone updated and now won't let me download it again. This is the advanced message from the manager app. I have deleted the normal YouTube before installing this too.
![Screenshot_20210225-022545_Vanced Manager](https://user-images.githubusercontent.com/79617155/109094900-a4077180-7712-11eb-9f91-0681c7514413.jpg)

**Comment by AinzTheSupremeOne** [comment]
This is a OneUI bug. You need to manually "uninstall" Vanced and reinstall it again from Manager to get it working. Check out this guide and follow the instructions. https://gist.github.com/Vendicated/e66d26a48b389023b99b44a45e46fdea I know it sounds confusing but that's what the bug is.

**Comment by gghhkm** [comment]
https://github.com/YTVanced/Vanced/issues/330#issuecomment-778443803
