### ISSUE TITLE
[Question] Where can I manually download all the split apks for manual installation?

### ISSUE THREAD

**Issue by pczmr8v5n454iycf** [YTVanced/Vanced#489]
**Description**
Manager doesn't work on my intel chromebook because I have not enabled developer mode.
I was able to find apks of an older version (15.05.54) on mediafire and manually installed them using adb.
Where can I download the latest version?

_Attach images/videos if possible. These can be helpful in figuring out what the question is about._

**Comment by gghhkm** [comment]
https://mirror.codebucket.de/vanced
