### ISSUE TITLE
[Bug] Stuck On Loading

### ISSUE THREAD

**Issue by NotGrizzlys** [YTVanced/Vanced#493]
**Bug description**
So when i sign in on youtube vanced it doesnt sign in then i reload the app then i get stuck on loading and the videos wont show up nor can i open anything in the app

**Variant**
Non-Root

**Vanced version**
16.02.35 - Build - 01.47.00

**Android version**
Android 10

**Device**
Samsung Galaxy S10 Lite

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2. Sign in
3. Not signed in immediatally
4. reload the app
5. Stuck on Loading screen

**Expected behavior**
It would load the videos but what happened is it didnt load anything it kept looping the loading screen

Image :
![SmartSelect_20210226-180531](https://user-images.githubusercontent.com/79698063/109293296-2badc700-785e-11eb-8572-8a0ee082b42e.jpg)

**Comment by Ozzy146** [comment]
I have the exact same issue here, I really hope they fix this soon!

**Comment by gghhkm** [comment]
A work around is available at #396

**Comment by NotGrizzlys** [comment]
> I have the exact same issue here, I really hope they fix this soon!
Just a help from a fellow comrade :)
Ik how to fix... well atleast for me. Just download an old version of yt vanced https://youtu.be/NnjAOcU0p_g thats the download i used The pw is  AAN0607 btw just follow the vid and its done. Hope this helped u man. This legit took me an hour to figure out by myself ;)

**Comment by gghhkm** [comment]
@NotGrizzlys please don't advertise fake Vanced links thanks.



https://vancedapp.com is the official site of Vanced, and as I said above you can find the work around for this bug at #396

**Comment by NotGrizzlys** [comment]
Oh i did not see that. Sorry i just wanted to help that guy that said he
had the same bug as me 🙏

Pada tanggal Sab, 27 Feb 2021 15:41, gghhkm <notifications@github.com>
menulis:
