### ISSUE TITLE
[Idea] Remove functions

### ISSUE THREAD

**Issue by vahik95** [YTVanced/Vanced#494]
Dear Vanced,

I would like to suggest a few functions.
I would like to be able to remove/toggle the explore page, home page and suggested video's under a YouTube video.
The reason I am asking this is because I find it very distracting and time consuming.

I hope you consider to look into this.

Kind Regards,

Vahik95

**Comment by vahik95** [comment]
So are we gonna do this?

**Comment by KevinX8** [comment]
Duplicate
