### ISSUE TITLE
[Idea] Remove "breaking news" annoying bar

### ISSUE THREAD

**Issue by Harmonie666** [YTVanced/Vanced#496]
**Description**

Please remove these "breaking news" crap that is popping up every here and then. Even when I hide it, it comes back after a while. 
I would appreciate it, if you guys could add a toggle to disable it. 
I already reported this issue once:
https://github.com/YTVanced/Vanced/issues/470#issue-811477959
![Screenshot_20210226-211038899 (1)](https://user-images.githubusercontent.com/73917917/109350279-899ad880-7877-11eb-802f-31f893658108.png)

**Comment by Brayman30** [comment]
Agreed!
