### ISSUE TITLE
[Bug] I can't open youtube vanced 

### ISSUE THREAD

**Issue by 70abk** [YTVanced/Vanced#497]
**Bug description**
I was using a Samsung Galaxy A20, but this time I changed the device to a Samsung Galaxy A31.  And when I installed and run vanced to watch youtube, I am not logged in.  When I logged in from microG and ran vanced, it continued to load and did not open.

**Variant**
Non-Root

**Vanced version**
16.02.35 - Build - 01.47.00

**Android version**
Android 10 - Q

**Device**
Samsung Galaxy A31(SM-A315N)

**Steps to Reproduce**
Steps to reproduce the error:
1. Sign in on microG
2. Open the vanced app

**Expected behavior**
I don't know what to answer to this question.

_Attach images/videos if possible. These can be helpful in solving the issue._
![Screenshot_20210227-110046](https://user-images.githubusercontent.com/40334680/109372210-b8529680-78eb-11eb-9784-cd46a80c94c5.png)

**Comment by gghhkm** [comment]
#396
