### ISSUE TITLE
[Idea] Please add option of Shizuku

### ISSUE THREAD

**Issue by gurmohanb** [YTVanced/Vanced#50]
I have issue with MIUI. Vanced manager does not work if we do not disable MIUI optimizations and if we do so, all permissions break and apps does not work properly. So after enabling MIUI optimizations, every app that require permission asks us to enable again and its headache to enable permission again specially UPI apps that requires contacts, dialer and message permission.
   So developers, my question is can you add option to install vanced manager through Shizuku because earlier it was easy for us to install .apks files from SAI through Shizuku and Shizuku requires only to enable adb permission from PC and it is not required to disable MIUI optimizations. 
I am not bashing vanced manager here and indeed it is great app to install YTV and i just have this idea or any idea to install in MIUI in easy way. Thanks.

**Comment by weiyi308** [comment]
You can use SAI to set the Installer to Shizuku,then use SAI install all apks under the /sdcard/Android/data/com.vanced.manager/files/apks/ folder,it works for me!

**Comment by KevinX8** [comment]
this repo is for vanced youtube only.
