### ISSUE TITLE
[BUG] Ads are back on Chromecast

### ISSUE THREAD

**Issue by jasper-r75** [YTVanced/Vanced#501]
A few weeks ago ads started appearing when casting to my chromecast 2, but not when playing videos on my phone.

Vanced manager, YT, microG  all updated to latest versions

**Comment by gghhkm** [comment]
Not a bug, that's just how casting works.
The phone simply sends the link to the chromecast and acts as a remote control, none of the video goes through the phone.

**Comment by jasper-r75** [comment]
Then why were there no ads before just a few weeks ago?I have been using vanced with my chromecast for YEARS and never saw an ad.. .

**Comment by gghhkm** [comment]
> Then why were there no ads before just a few weeks ago?I have been using vanced with my chromecast for YEARS and never saw an ad.. .

Maybe everyone was demonized 🤣.
Read [this](https://chromecastappstips.com/how-does-chromecast-work/#/?playlistId=0&videoId=0)

**Comment by jasper-r75** [comment]
Haha, No.. . Watching the same wholesome content. 
I understand how casting videos works. But the ads (video) url also would have to be passed / loaded somehow. I just assumed that those were somehow prevented from being sent by  vanced YT before.

**Comment by gghhkm** [comment]
> Haha, No.. . Watching the same wholesome content.
> I understand how casting videos works. But the ads (video) url also would have to be passed / loaded somehow. I just assumed that those were somehow prevented from being sent by vanced YT before.

Simply not how it works, none of the video (including ads) gets passed through the phone.

**Comment by jasper-r75** [comment]
I was talking about the urls

**Comment by gghhkm** [comment]
> I was talking about the urls

URL are basically just addresses and only one gets sent, e.g. to the video.

**Comment by jasper-r75** [comment]
Ok, thanks for your troubles. I am just left curious why I never saw ads before then.
