### ISSUE TITLE
[Idea] Add to playlist option against videos in notifications section

### ISSUE THREAD

**Issue by onlytanmoy** [YTVanced/Vanced#503]
Hiya, currently in the Notifications section of YTVanced, below two standard options are present when I click the 3 dots against a video:
1. Hide this notification
2. Turn off all from that channel

Please provide an additional option - Add to playlist
On clicking that it will display all my playlists like Watch later, Favorites, Personal playlists etc where I can add that video...TIA

**Comment by brunowildhagen** [comment]
Bump. This would be great.
