### ISSUE TITLE
[Idea] YouTube TV Vanced?

### ISSUE THREAD

**Issue by Cee123** [YTVanced/Vanced#507]
**Description**
Any chance you guys could make a YouTube TV Vanced? You know for Android boxes. Because there seems to be an issue with the normal YouTube app on my Android box where I am unable to change the quality settings etc (ive tried everything) and it displays like it would on a very basic mobile device with very low quality, blurriness and pixelation.

_Attach images/videos if possible. Also add any links to possible other applications with the said feature already implemented._

**Comment by gghhkm** [comment]
The lead Developer has already decided that this won't be happening a long time ago.

Use these alternatives and others instead.
https://github.com/yuliskov/SmartYouTubeTV
https://github.com/yuliskov/SmartTubeNext

**Comment by Cee123** [comment]
> The lead Developer has already decided that this won't be happening a long time ago.
> 
> Use this alternatives and others instead.
> https://github.com/yuliskov/SmartYouTubeTV
> https://github.com/yuliskov/SmartTubeNext

Aww really? Damn, that's a shame. :(

**Comment by Cee123** [comment]
> The lead Developer has already decided that this won't be happening a long time ago.
> 
> Use this alternatives and others instead.
> https://github.com/yuliskov/SmartYouTubeTV
> https://github.com/yuliskov/SmartTubeNext

Thanks, I'll try those and see if i change the video playback quality on there.

**Comment by Cee123** [comment]
> The lead Developer has already decided that this won't be happening a long time ago.
> 
> Use this alternatives and others instead.
> https://github.com/yuliskov/SmartYouTubeTV
> https://github.com/yuliskov/SmartTubeNext

Oh my God thank you!! I just tried Smart YouTube TV app. That is a much better option! I can change the quality settings and the videos are crystal clear!
