### ISSUE TITLE
Dark Mode bug 16.02.35

### ISSUE THREAD

**Issue by Jutish123** [YTVanced/Vanced#509]
![Screenshot_2021-02-28-12-20-06-0396730806](https://user-images.githubusercontent.com/79780868/109409763-8b6fb380-79bf-11eb-9d75-595810f279ef.png)
![Screenshot_2021-02-28-12-21-05-0561859009](https://user-images.githubusercontent.com/79780868/109409765-8f033a80-79bf-11eb-8caa-74ccf6f97df3.png)
![Screenshot_2021-02-28-12-21-28-1992781317](https://user-images.githubusercontent.com/79780868/109409769-9296c180-79bf-11eb-9edc-befdb8a1bb4e.png)

Use Dark mode after sometime its automatically turn on light mode please fix the problem.

**Comment by gghhkm** [comment]
#469
