### ISSUE TITLE
[bug] Swipe controls not working

### ISSUE THREAD

**Issue by vordx** [YTVanced/Vanced#51]
Vanced 15.33.34, MicroG 0.2.12.203315-vanced, Galaxy note 8, pie, non root.

Swipe controls don't work when vertical video is in full screen or if the app is in multi window mode which makes it so  **annoying** when watching the video because sometimes it's on full brightness and you can't adjust the brightness thanks to it blocking brightness change from system while it's in this mode.

**Comment by AinzTheSupremeOne** [comment]
Please edit the title of this issue. Just "[bug]" doesn't make it obvious.

**Comment by VancedOfficial** [comment]
Should be fixed in the 15.38.35 release. Open a new issue if not.
