### ISSUE TITLE
Package signature match

### ISSUE THREAD

**Issue by bossk50** [YTVanced/Vanced#510]
**Bug description**
My phone upgraded from Android 10 to Android 11 this morning. This removed the YouTube Vanced that was installed on this phone. I have tried to reinstall from the package that I had, which was version 15. I installed the Vanced Manager when that didn't work and try to install YouTube Vanced that way, but that didn't work either. I have attached a screenshot that shows the error where the package signatures do not match. I have installed from unknown sources enabled.

As an addendum to this issue? I did end up resetting the phone, and this resolved any install issues I had with Vanced YT.  I was able to use advanced manager to install both the micro g Vanced YT. So you might want to think about uninstalling advanced prior to an upgrade to Android 11.

**Variant**
Non-Root

**Vanced version**
16.02.35 - Build - 01.47.00

**Android version**
Android 11

**Device**
LG V60

**Steps to Reproduce**
Steps to reproduce the error:
![Screenshot_20210228-081158](https://user-images.githubusercontent.com/79795342/109420543-11303680-79a1-11eb-9d70-532a35d355fb.png)

**Expected behavior**
I did not expect that the YT Vanced app would be removed when I upgraded the phone OS. I don't know why the install of the app from the APK file is being blocked. This happens when just trying to install the APK directly or using the Vanced Manager method

_Attach images/videos if possible. These can be helpful in solving the issue._

**Comment by manosdias** [comment]
I have the exact same problem. I had vanced YouTube running on OnePlus Nord. Upgraded to android 11 and it had vanished. Went through all the same steps as you and had no luck. I download SD maid app to try and find remnants of the app. It manages to find a tiny file but it could not be removed. I believe this prevents us from installing the new vanced as there is remnants from our old download. 
![Screenshot_20210303-133330](https://user-images.githubusercontent.com/80017941/109903013-23f18680-7c93-11eb-8d7f-b61f4bcaa029.jpg)
![Screenshot_20210303-133229](https://user-images.githubusercontent.com/80017941/109903017-2522b380-7c93-11eb-992a-3b29d0c2a716.jpg)
![Screenshot_20210303-133335](https://user-images.githubusercontent.com/80017941/109903020-2653e080-7c93-11eb-8eb4-5e014bd0c90d.jpg)
![Screenshot_20210303-133343](https://user-images.githubusercontent.com/80017941/109903022-27850d80-7c93-11eb-97d3-5a045aed0d81.jpg)
I hope this helps resolve the issue

**Comment by manosdias** [comment]
The tiny file found through SD maid bounces back after attempting to delete. I wouldn't be stuck had I uninstalled the app before upgrading. Perhaps you could leave a note for users upgrading from 10 to 11

**Comment by bossk50** [comment]
I'm sorry to say that the only thing that resolved the issue for me was resetting the phone. After that, Vanced installed without any issues and has been working fine. I think if I was dealing with a rooted phone, then I could have removed that leftover file myself and proceeded as usual. But alas, the days of rooting phones for me are done.

**Comment by manosdias** [comment]
I really don't want to reset my phone or go down the rooting route. guess I have to use stock YouTube until vanced work something out.nim sure many other long time users will encounter this with the android 11 rollout

**Comment by gghhkm** [comment]
https://github.com/gghhkm/Vanced-Issue-Center/blob/master/Guides/INSTALL_FAILED_UPDATE_INCOMPATIBLE.md
