### ISSUE TITLE
[Bug] Sponsorblock is not working

### ISSUE THREAD

**Issue by Hx2-code** [YTVanced/Vanced#515]
**Bug description**
The sections of a video that were previously marked by sponsorblock are not getting skipped or being shown by different colours.

**Variant**
Non-Root

**Vanced version**
16.02.35 - Build - 01.47.00

**Android version**
Android 10.0 - Q

**Device**
Samsung M11

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2. Enable Sponsorblock in settings
3. Enable all features of Sponsorblock to skip automatically
4. Close the app and reopen it
5. Open any Linus Tech Tips video, there will be no section marked by Sponsorblock

**Expected behavior**
It is expected that on the videos marked by sponsorblock certain sections of the video will get skipped and will be shown by different colours.

**Comment by rickninja765** [comment]
Yeah Same for me its not working since yesterday.

**Comment by Hx2-code** [comment]
@AinzTheSupremeOne Yes I know that. The videos which previously had the segments are no longer showning them. Thats the bug.

**Comment by Hx2-code** [comment]
Never mind its working after I restarted my phone.

**Comment by yShyboy** [comment]
I have the same problem, already restarted and videos that worked earlier (last week) or work in the browser (chrome+extension) don't work anymore. I've tried to go back and install 15.3X version and still got nothing.

**Comment by Delphox** [comment]
https://status.sponsor.ajay.app/

The Sponsorblock API has been pretty unstable lately. Maybe @ajayyy can give some more insight.
