### ISSUE TITLE
[Bug] Can't use the lock screen controls on PocoPhoneF2 due to in-screen fingerprint location

### ISSUE THREAD

**Issue by nonSH** [YTVanced/Vanced#517]
**Bug description**
The audio controls don't react due to the fingerprint scanner having higher priority (?).

**Variant**
Non-Root

**Vanced version**
16.02.35 - Build - 01.47.00

**Android version**
Android 10 QKQ1.191117.002

**Device**
Pocophone F2 Pro

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2. Click on any video
3. Lock screen
4. Now the audio controls (pause, play button) are unresponsive.

**Expected behavior**
Move the location of the controls below/above the fingerprint scanner on the PocoF2 Pro? I am not 100% sure this falls within Vanced, it might be a MIUI issue instead, but I thought I would try here. If it is, I apologize.

_Attach images/videos if possible. These can be helpful in solving the issue._

**Comment by gghhkm** [comment]
This is a MiUi issue like you said.
