### ISSUE TITLE
[Bug] Internet Not Working

### ISSUE THREAD

**Issue by EmVeddii** [YTVanced/Vanced#519]
**Bug description**
Whenever I open the app it states that I have no Internet connection. Even though I do, and every other app I have works. Even normal YouTube works in browser so I assume it's a Vanced issue.

**Variant**
Non-Root

**Vanced version**
16.02.35 - Build - 01.49.00

**Android version**
Android 11 / One UI 3.0

**Device**
Samsung Galaxy S20+

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2. The error appears

**Expected behavior**
When I open the app it should work as normal and not say "No Internet Connection" unless I actually have no Internet connection.

_Vanced_
![Screenshot_20210302-122303.png](https://user-images.githubusercontent.com/59317664/109648109-20a2b180-7b52-11eb-9327-e7391a0d5ecd.png)

_Regular YouTube_
![Screenshot_20210302-122331_Firefox.png](https://user-images.githubusercontent.com/59317664/109648166-344e1800-7b52-11eb-83b7-7665de97888a.png)

**Comment by ShielleRivera** [comment]
just started having the same issue as well! internets working fine as usual, checked on any updates, uninstalled n reinstalled all together, and still getting the Connect To Internet page

**Comment by EmVeddii** [comment]
Yeah I understand mods get busy but I do hope this is fixed ASAP. literally makes the app completely unusable and there appears to be no way for me to fix it myself.

**Comment by gghhkm** [comment]
* ***General fix for everything Non-root:***
 **`• this will fix most non-root Vanced related issues`**
`• you can consider this the proper Vanced install method`



**#Preparations for clean install**
 `• if you've already installed it and have problems`
1. Remove the MicroG account from system settings 
2. Uninstall Vanced, Vanced MicroG & Vanced Music.  
3. Reboot. 

**#Installation**
1. Make sure you're using Vanced Manager 2.4.0+ 
(MiUi users make sure to disable MiUi optimization)
2. Install Vanced MicroG
3. Disable battery optimization for Vanced MicroG ASAP
Use [Don't Kill My App](https://dontkillmyapp.com/) if needed.
4. Install Vanced ***15.40.37***  &/or Music ***4.04.52***
5. Login 
6. Update to latest
(MiUi users, you can readable MiUi optimization at this point if you have to)
For further assistance please refer to the
[Vanced Official Discord](https://discord.gg/rgwbXEaUCb)

**Comment by EmVeddii** [comment]
Uhm.. Vanced 15.40.37 isn't there. It wants me to install 16.02.35
