### ISSUE TITLE
[bug] Double Chromecast device still not fixed

### ISSUE THREAD

**Issue by pushkargogte** [YTVanced/Vanced#52]
Double Chromecast device bug is still not fixed with lastest microg update on non root version.

I have attached the video for your reference.

https://drive.google.com/file/d/1YOpwspjkogDrnfgs-gi0zFUj22vPlAoa/view?usp=drivesdk

**Comment by weirdal3333** [comment]
It works fine on my android 10 gsi. However, my device shows 2 different types of devices when the toggle is off... Your phone is showing 2 of the same device, weird. Attached is an example of my phone when toggled off
![Screenshot_20201001-204454](https://user-images.githubusercontent.com/3537180/94876908-017ae900-0427-11eb-9dba-bce0467b3cde.png)

**Comment by pushkargogte** [comment]
Yes that's weird. Maybe 32-bit gsi has problems with x64 SoC. My phone is using Snapdragon 712 SoC. Also when I uninstalled microg and vanced YouTube the issue disappers.

**Comment by KevinX8** [comment]
this is microg related and has been fixed in the latest update.
