### ISSUE TITLE
[Idea] Remove the "Watch in VR" and "Help & feedback" options. Bring back "i" button.

### ISSUE THREAD

**Issue by Kevi-n7** [YTVanced/Vanced#520]
**Description**
Remove the "Watch in VR" and "Help & feedback" options from the video menu. imo, >99% of the users don't use these options.
![Screenshot_20210302_184657](https://user-images.githubusercontent.com/79917621/109654056-c02e6700-7b87-11eb-8f7e-050ac5576461.jpg)

Also, Move the "i" from the video menu to its original place in the video player (near the "CC" and Autoplay buttons). It's more convenient.
![PicsArt_03-02-07 02 00](https://user-images.githubusercontent.com/79917621/109655932-db9a7180-7b89-11eb-8cf6-82e4ab6014de.jpg)

**Comment by vrindavan** [comment]
This is nice one but...closed sadly.
