### ISSUE TITLE
[Idea] Skipping age verification

### ISSUE THREAD

**Issue by nicolasGEL** [YTVanced/Vanced#522]
**Description**
whenever i look at a mature/age rated video, my main account can directly watch them in a browser but the app requests verification via credit card/ID, i don't want to give my ID or credit card info to google

![Screenshot_20210302-145323](https://user-images.githubusercontent.com/42648527/109659013-86e5ff00-7b67-11eb-9985-6a151d2922d3.jpg)

**Comment by gghhkm** [comment]
Try using a VPN to make an account outside the UK.
Google now requires a credit card for age verification in the UK but no where else that I'm aware of. Using a VPN should help you to bypass the ID portion of the verification and after the account is created I believe you can then use that account without the VPN.

If it doesn't work or you don't want to go that route you can try Newpipe as well.

**Comment by nicolasGEL** [comment]
currently in switzerland, so it's not just the UK

**Comment by gghhkm** [comment]
@nicolasGEL 
Here's the whole thing.
![985966610958638022d811eb8a4cded5fd9dfa08](https://user-images.githubusercontent.com/72711094/110253084-6ac2d300-7f56-11eb-9042-00d39a1c7b25.png)

**Comment by Vendicated** [comment]
Vanced is not going to bypass something required by law. Either use a vpn, a player like newpipe or mpv that does not reequire login, or simply submit your ID/credit card (google has to delete it after the verification and [depending on where you live you might be able to censor parts](https://support.google.com/accounts/answer/10071085?p=age-verify&visit_id=637508333781491547-3492183699&rd=1#zippy=%2Cget-country-specific-guidance))

**Comment by stdedos** [comment]
It's a little weird though that the stock YouTube app (or PC version) does not require me to do any verification 😕

**Comment by Kippenhof** [comment]
> It's a little weird though that the stock YouTube app (or PC version) does not require me to do any verification

Yes, it does not seem to be fully rolled out, or some people may not are not affected on the pc because of certain factors that I do not know.

I am also not affected, but 2 Buddys of me are, so they have to use an vpn.
