### ISSUE TITLE
[Idea] Remove "Trending" infobar.

### ISSUE THREAD

**Issue by Harmonie666** [YTVanced/Vanced#524]
This is kinda like a ad and is appearing frequently. Please add the option to disable them within a upcoming vanced update. They are incredibly annoying and bothering. I've reported this issue several times already:
![Screenshot_20210302-192439315 (1)](https://user-images.githubusercontent.com/73917917/109696426-55802a00-7b8d-11eb-9b9e-d329cb6df4fe.png)

All my GitHub posts about this issue:

https://github.com/YTVanced/Vanced/issues/496

https://github.com/YTVanced/Vanced/issues/470

https://github.com/YTVanced/Vanced/issues/234

I also made several reddit posts about this issue.

**Comment by smed79** [comment]
> All my GitHub posts about this issue

Please post your request only once, otherwise it will interpret as spam.

I would recommend you to close old issues and keep this one. & If you want to add additional details in futur for the same request/issue poste them here.
