### ISSUE TITLE
[Bug] Can not open youtube video links shared in the description

### ISSUE THREAD

**Issue by Bulzahr10** [YTVanced/Vanced#525]
**Bug description**
Replace me with a clear and detailed description of the bug.

**Variant**
Non-Root/Root

**Vanced version**
16.02.35 - Build - 01.47.00

**Android version**
Android 9.0 - Pie

**Device**
Samsung Galaxy S8

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
3. ....

**Expected behavior**
Replace me with a description of what you expected should happen and what happened instead.

_Attach images/videos if possible. These can be helpful in solving the issue._

**Comment by colinBranca** [comment]
Hi, 
I encounter the same issue with my non-rooted OnePlus 8T on Android 11 (also with Vanced Version 16.02.35).
When you click on a link you get an error message "cannot open this link with Youtube"
