### ISSUE TITLE
[Idea] chrome extention?

### ISSUE THREAD

**Issue by lavadaragon15396** [YTVanced/Vanced#526]
I know that there are quite a few ad blocking and colour changing extensions already out there but the reasons why I would want this are:

- a YT music ad blocker
- a not dodgy extension that has all the features that you could need
- features like sponsorblock

https://chrome.google.com/webstore/detail/adblocker-for-youtube/maekfnoeejhpjfkfmdlckioggdcdofpg 
https://chrome.google.com/webstore/detail/colorful-youtube/nmpopbiiioibcfhpdbeggkgpebpjfanc

**Comment by gghhkm** [comment]
SponsorBlock is a browser extension.
use Ublock Origins.

**Comment by sagarsoni7** [comment]
We can create a Rule for this in Requestly chrome extension. Check it out once

**Comment by Vendicated** [comment]
Sponsorblock: https://chrome.google.com/webstore/detail/sponsorblock-for-youtube/mnjggcdmjocbbbhaepdhchncahnbgone

Adblock: https://chrome.google.com/webstore/detail/ublock-origin/cjpalhdlnbpafiamejdnhcphjbkeiagm

Both open source and safe
