### ISSUE TITLE
[Idea] Dark loading screen & replace YT logo with YT:vanced

### ISSUE THREAD

**Issue by TheTopComp** [YTVanced/Vanced#528]
**Description**
1st idea ~ When dark mode is enabled, make the loading screen dark too.
2nd idea ~ Replace top left logo with YT:vanced logo.
![Screenshot_20210304-030756](https://user-images.githubusercontent.com/55924795/109900040-058d8a00-7c97-11eb-88cb-e98af98dff34.png)
![IMG_20210304_030840](https://user-images.githubusercontent.com/55924795/109900074-0de5c500-7c97-11eb-95de-72385a02ab53.png)

**Comment by fargotable** [comment]
> **Description**
> 1st idea ~ When dark mode is enabled, make the loading screen dark too.
> ![Screenshot_20210304-030756](https://user-images.githubusercontent.com/55924795/109900040-058d8a00-7c97-11eb-88cb-e98af98dff34.png)

1. Enable dark mode in your phone :) 
![Screenshot_2021-03-17-13-35-29-703_com vanced android youtube](https://user-images.githubusercontent.com/80829981/111468477-e0345d80-8725-11eb-8288-0251ed9c8102.jpg)
