### ISSUE TITLE
[Bug] Ads in search results 

### ISSUE THREAD

**Issue by leodoi3** [YTVanced/Vanced#53]
I am getting ads / sponsored results showing up in search. 
![Screenshot_20200927-023033.jpg](https://user-images.githubusercontent.com/46114199/94361524-b8631780-0069-11eb-864b-a8fd05532032.jpg)

**Comment by Moonlight63** [comment]
Same here

**Comment by VancedOfficial** [comment]
Should be fixed in the 15.38.35 release. Open a new issue if not.
