### ISSUE TITLE
[Bug] True Dark mode on AMOLED screen not working

### ISSUE THREAD

**Issue by cl-ement05** [YTVanced/Vanced#530]
**Bug description**
"True dark mode" that's to say black pixels on AMOLED screens is not working. I tried reinstalling several times and changing the appearance but still

**Variant**
Non-Root

**Vanced version**
16.02.35

**Android version**
Android 11.0 - R

**Device**
Xiaomi Mi 8

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2. Well the issue is is front of your eyes

**Expected behavior**
Pixels turning off because I am on an AMOLED screen

**Comment by gghhkm** [comment]
you have to select Black theme at install
