### ISSUE TITLE
Vanced microG fails on Samsung Galaxy S21 Ultra

### ISSUE THREAD

**Issue by moktadir** [YTVanced/Vanced#531]
Using latest Vanced Manager, tried following all troubleshooting/preparation steps, including multiple reboots between steps, still SOL on being able to log in on YT Vanced—results in infinite loading screen.However, if I remove microG account, YT Vanced works fine. 

I'm not sure what's going on here, and as I'm not taking any chances with root anytime soon (just bought this phone), and there doesn't seem to be any other angle I can try to tackle this.

![Screenshot_20210306-100940_Settings](https://user-images.githubusercontent.com/5289802/110213072-19d2b200-7e64-11eb-91dc-50d011c9b61e.jpg)

**Comment by StazriN** [comment]
Same issue here.

**Comment by StazriN** [comment]
Fixed by uninstalling and installing again MicroG and YT Vanced. (Vanced manager asked me to install YT Vanced v15 firstly and after that, I upgrade YT Vanced to v16.)

**Comment by clarence112** [comment]
I'm having the same issue. Reinstalling did nothing to fix it.

**Comment by moktadir** [comment]
Fixed by uninstalling everything, including Vanced Manager, and re-installing in order:

1. Uninstall everything
2. Reinstall Vanced Manager
3. Reinstall MicroG
4. Set up MicroG optimization settings
5. Install YouTube Vanced v15
6. Log into microG/YouTube
7. Update YouTube Vanced.
