### ISSUE TITLE
[Bug] EMUI knuckle gesture PIP mode

### ISSUE THREAD

**Issue by Kevi-n7** [YTVanced/Vanced#533]
**Bug description**
EMUI knuckle gesture PIP bug on Vanced which could be used to fix the existing PIP mode issues on Vanced apps running on Huawei devices.

**Variant**
Non-Root

**Vanced version**
16.02.35 - Build - 01.47.00

**Android version**
Android 10

**EMUI version**
EMUI 11.0.0

**Device**
Huawei P30 Pro 

**Preface**
The knuckle gesture of a straight line from left to right was used on older EMUI versions to go into split screen mode, but this gesture was  removed and replaced by side bar in recent EMUI versions. On newer EMUI versions, this knuckle gesture will not trigger anything on any app I've tested, except Vanced.

**Steps to Reproduce**
Steps to reproduce the bug:
1. Open the Vanced
2. Play any video in normal mode (don't go full screen & keep your device in portrait orientation) 
3. Tap on left side of your screen with your knuckle and draw a straight line towards right and release knuckle
4. An abnormal PIP mode will be triggered, the popup window will be present at the botttom right corner of our display but it will not be visible, until we swipe or tap at the bottom right corner of the display
5. Tap on Vanced icon
6. Do the knuckle gesture again(Step 3)
7. A NORMAL PIP MODE is triggered, the popup window was visible, it even shows the popup window animation 
8. Now, repeat steps 5 & 6 multiple times, it will always go to step 7 without any issues.

P. S. Instead of Step 3, you can do a normal home gesture (swipe up from the bottom of the screen) , it will still trigger an abnormal popup window. Rest of the steps will remain same.

**So why did I report this EMUI bug?**
I know this might be complicated but maybe you could find out the reason why PIP mode was correctly triggered by the second knuckle gesture in Step 6. Then reconfigure the app's current response to a home gesture so that it could properly trigger the PIP mode.

**Video**

https://user-images.githubusercontent.com/79917621/110233446-0732a880-7f4a-11eb-891f-83df253f65cb.mp4

That blue sparkly line on the middle of the screen was the knuckle gesture.

**Comment by X1nto** [comment]
It's a bug in stock youtube, not vanced. Wait for google to fix it
