### ISSUE TITLE
[Bug] ADS not blocking in trnasmition on Xbox 360 app

### ISSUE THREAD

**Issue by Ligiero** [YTVanced/Vanced#534]
**Bug description**
Using YouTube Vanced on Android app, transmiting in Xbox 360 app, the ADS is not blocked.

**Variant**
Non-Root

**Vanced version**
16.02.35 - Build - 01.47.00

**Android version**
Android 10 QKQ1.200114.002

**Device**
Xiaomi Redmi note 8
MIUI 12.0.3

**Steps to Reproduce**
Steps to reproduce the error:
1. YouTube Xbox 360 app open
2. Open the app on android
2. Click on "transmit tô"
3. chose Xbox 360
4. Working and playing a vídeo, but, about few minutes, an ADD propaganda appears and repeat in some time intervals.

**Expected behavior**
Working and playing a vídeo, but, about few minutes, an ADD propaganda appears and repeat in some time intervals.

_Attach images/videos if possible. These can be helpful in solving the issue._

**Comment by KevinX8** [comment]
This is not adblock for Xbox 360, this only blocks ads on Android it's not magical.

**Comment by Ligiero** [comment]
You didn't have to be so stupid and rude to answer me. Occours that this directly affected the functioning of the vanced on my cell phone ALSO. If think the complaint useless, you shoud have been more cordial. Thanks for nothing, shit technician!

**Comment by Ligiero** [comment]
> This is not adblock for Xbox 360, this only blocks ads on Android it's not magical.

You didn't have to be so stupid and rude to answer me. Occours that this directly affected the functioning of the vanced on my cell phone ALSO. If think the complaint useless, you shoud have been more cordial. Thanks for nothing, shit technician!

**Comment by gghhkm** [comment]
> > This is not adblock for Xbox 360, this only blocks ads on Android it's not magical.
> 
> You didn't have to be so stupid and rude to answer me. Occours that this directly affected the functioning of the vanced on my cell phone ALSO. If think the complaint useless, you shoud have been more cordial. Thanks for nothing, shit technician!

You just called one of the developers stupid for giving you a genuine response.

Also, none of the content passes through the phone when casting, it's all handled by the Xbox itself. The phone just sends the video link to the Xbox and acts as a remote control.
![aw15sg5tf22sqa6xfrsqef236arx](https://user-images.githubusercontent.com/72711094/110247971-d13af780-7f3c-11eb-8db1-2c23f5d1e31a.jpg)
[Source](https://chromecastappstips.com/how-does-chromecast-work/#/?playlistId=0&videoId=0)

**Comment by Ligiero** [comment]
> > > This is not adblock for Xbox 360, this only blocks ads on Android it's not magical.
> > 
> > 
> > You didn't have to be so stupid and rude to answer me. Occours that this directly affected the functioning of the vanced on my cell phone ALSO. If think the complaint useless, you shoud have been more cordial. Thanks for nothing, shit technician!
> 
> You just called one of the developers stupid for giving you a genuine response.
> 
> Also, none of the content passes through the phone when casting, it's all handled by the Xbox itself. The phone just sends the video link to the Xbox and acts as a remote control.
> ![aw15sg5tf22sqa6xfrsqef236arx](https://user-images.githubusercontent.com/72711094/110247971-d13af780-7f3c-11eb-8db1-2c23f5d1e31a.jpg)
> [Source](https://chromecastappstips.com/how-does-chromecast-work/#/?playlistId=0&videoId=0)

Now I have received a technical, polite and attentive response. Now I understand the problem and I gladly accept the explanations. I kindly ask you to demonstrate and teach the previous technician what you did, an appropriate, technical and attentive service to users and fans of your products. Thank you very much for returning and have a good day.

**Comment by X1nto** [comment]
we got 297 other issues and we're not gonna explain everything in detail just for one user

**Comment by Ligiero** [comment]
> we got 297 other issues and we're not gonna explain everything in detail just for one user

I didn't ask anyone for detailed explanations, but there are more polite and technical ways to respond in a short way, instead of "it's not an ADblock for Xbox" or "that's not magic".
If you have a proposal to foster customer service, this is the minimum required.
thanks again and have a great day.
