### ISSUE TITLE
[Bug] Can't refresh YouTube Feed

### ISSUE THREAD

**Issue by ua1-atl** [YTVanced/Vanced#535]
**Bug description**
Replace me with a clear and detailed description of the bug. When I try to refresh my home page on YT Vanced it doesn't refresh and no matter how many times I uninstall and reinstall it doesn't work 

**Variant**
Non-Root

**Vanced version**
16.02.35 - Build - 01.47.00

**Android version**
Android 10.0

**Device**
Oneplus 6

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2. Try to refresh. It may work for one or two tries then later will not refresh
3. ....

**Expected behavior**
Should refresh the page with new videos 

_Attach images/videos if possible. These can be helpful in solving the issue._

**Comment by Barkash** [comment]
Yeah I got basically the same Problem here, expect I can't refresh a single time. ):
I thought it was an weird YouTube Update again, but it works on 'normal' YouTube. 
Hope it gonna be fixed, cuz close and start the App everytime is kinda yucky.

**Comment by ua1-atl** [comment]
It doesn't work at all for me and even if I close and open app and clear cache tried everything but nope

**Comment by P-C-R** [comment]
Same Problem Here!

**Comment by madeinlisboa** [comment]
Same issue of bug #540

**Comment by P-C-R** [comment]
> Same issue of bug #540

No.

**Comment by P-C-R** [comment]
![Screenshot_20210311-124247919](https://user-images.githubusercontent.com/47773180/110782337-4cffb180-8267-11eb-9ef1-383882a57ccb.jpg)Activating old comments fixed it

**Comment by madeinlisboa** [comment]
> > Same issue of bug #540
> 
> No.

Yes it is.

**Comment by madeinlisboa** [comment]
> ![Screenshot_20210311-124247919](https://user-images.githubusercontent.com/47773180/110782337-4cffb180-8267-11eb-9ef1-383882a57ccb.jpg)Activating old comments fixed it

This option has nothing to do with old features. By the contrary. It's a new one. 
It doesn't fix anything

**Comment by P-C-R** [comment]
no because i can log in with my account. It does only not refersh when i swipe down @ the home screen. your problem is completly diffrent.

**Comment by P-C-R** [comment]
From the discord
![Uploading Screenshot_20210311-125744066.jpg…]()

**Comment by gghhkm** [comment]
This might be fixed in the next release soon-ish to come out. Let me know if it is or isn't when then next version is released, so I can close this issue if it is.
