### ISSUE TITLE
[Bug] login Google already sign in...

### ISSUE THREAD

**Issue by drnico2016** [YTVanced/Vanced#538]
Impossible to connect Youtube music but Youtube vidéo works.
Everytime i want to connect it say already login.
Try everything i can on your support but no solution

**Comment by drnico2016** [comment]
Sad that you dont know how to fix this problem

**Comment by drnico2016** [comment]
Why you closes it? If you dont know how to fix juste leave it open

Téléchargez Outlook pour Android<https://aka.ms/ghei36>

________________________________

**Comment by gghhkm** [comment]
-> This has been answered about 10000x.
1. Install Vanced Music ***4.04.52***
2. Login 
3. Update to latest

**Comment by Vendicated** [comment]
I closed it because this is answered in the pinned issue and has been answered dozens of times already
