### ISSUE TITLE
[Bug] Can't switch between accounts 

### ISSUE THREAD

**Issue by leodoi3** [YTVanced/Vanced#540]
**Bug description**
When I want to switch between other youtube accounts the account picker is empty. I try to sign in to my Google account but says the account is already added. I am still logged into my primary account. 

I tried to remove Google account & readd it. Reinstalled Vanced & microG but it persists.

**Variant**
Non-Root

**Vanced version**
16.02.35 - Build - 01.47.00

**Android version**
Android 11

**Device**
Samsung Galaxy S10

**Steps to Reproduce**
???

**Expected behavior**
It should show me all my account 

_Attach images/videos if possible. These can be helpful in solving the issue._
![Screenshot_20210308-235236.jpg](https://user-images.githubusercontent.com/46114199/110430540-c3cf5b80-8069-11eb-8f9c-cb766eab0e01.jpg)

**Comment by madeinlisboa** [comment]
Same with me 
YouTube Vanced stopped suddenly to load my account. I deleted all apps related including manager and reinstalled all.
When YouTube launches for the first time it displays the generic home feed, but as soon as I add an account, it doesn't display anything. It just sits there with the loading symbol.
When I try to add an account, the list is empty, although there are accounts shown in the system settings page. 
It's the unroot version on a Samsung M21.

**Comment by madeinlisboa** [comment]
![Screenshot_20210312-092305](https://user-images.githubusercontent.com/27363132/110920873-cbb32800-8315-11eb-9f8b-d515ed1a9c8e.jpg)
Always like this

**Comment by gghhkm** [comment]
@leodoi3
Switching accounts is not possible on 16.02.35 unless you're using the Root version. Not to worry the next version that'll come out soon-ish will address this.
