### ISSUE TITLE
[Bug] Youtube Vanced Installation Error

### ISSUE THREAD

**Issue by mohitey007** [YTVanced/Vanced#546]
**Bug description**
Installation fails as shown in screenshot. Yesterday I updated my Samsung Galaxy M51 to Android 11 as update rolled out. Soon after installation, the pre-installed Youtube vanced and manager got uninstalled automatically and were unable to be installed later on.
![Screenshot_20210309-215000_Vanced Manager](https://user-images.githubusercontent.com/63991700/110660620-bccf5700-81e9-11eb-96d8-545190c38f3c.jpg)

**Variant**
Non-Root/Root

**Vanced version**
16.02.35 - Build - 01.47.00

**Android version**
Android 11

**Device**
Samsung Galaxy M51

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
3. ....

**Expected behavior**
Post installation, the Youtube Vanced should have been installed and can be executed.

_Attach images/videos if possible. These can be helpful in solving the issue._

**Comment by gghhkm** [comment]
https://github.com/gghhkm/Vanced-Issue-Center/blob/master/Guides/BrokenVancedPackage.md
