### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by hsmtrym** [YTVanced/Vanced#549]
There IS write that there IS no connexion

**Comment by gghhkm** [comment]
- General fix for everything Non-root:
- this will fix most nonroot Vanced related issues
- you can consider this the proper Vanced install method

## Preparations for clean install
1. Remove the microG account from system settings 
2. Uninstall Vanced, Vanced MicroG & Vanced Music.  
3. Reboot. 

## Installation
1. Make sure you're using Vanced Manager 2.4.0 or above.
(MiUi users disable MiUi optimization too)
2. Install Vanced MicroG
3. Disable battery optimization for Vanced MicroG ASAP
Use [Don't Kill my app](https://dontkillmyapp.com/) if needed.
4. Install Vanced 15.40.37  &/or Music 4.04.52
5. Login 
6. Update to latest
(MiUi users, you can readable MiUi optimization at this point if you have to)
