### ISSUE TITLE
[Idea] Option to hide tabs (e.g. Home/Explore)

### ISSUE THREAD

**Issue by ralismark** [YTVanced/Vanced#55]
The home and explore feed can be quite distracting, so I'd like to hide them.

**Comment by jace** [comment]
This will be a huge aid to the `nosurf` life. The YouTube app is the most painful to suppress as its a system app on Android. Chrome can be told to turn off recommendations, and the Google app can be put into search-only mode. The YouTube app has no such option.

I want to watch, not surf.

**Comment by PranavARC** [comment]
Agreed. Having features like the [YouTube DF Extension](https://chrome.google.com/webstore/detail/df-tube-distraction-free/mjdepdfccjgcndkmemponafgioodelna?hl=en) on the Chrome Web Store like options to remove Home and Trending tabs, video suggestions, etc. would help the app appeal to a huge userbase of people who don't want to waste time on YouTube.

**Comment by PranavARC** [comment]
@ralismark @jace It's not perfect, but you should check out [NewPipe](https://newpipe.net/). It doesn't look like this feature will be added anytime soon in Vanced, and while the app definitely isn't as high quality as Vanced, it's amazing for a No Distraction Experience. However, it might be a bit too restrictive, so if that's a problem, just use it as a secondary app.
