### ISSUE TITLE
[Bug] incorrectly losing internet.... again

### ISSUE THREAD

**Issue by EmVeddii** [YTVanced/Vanced#551]
**Bug description**
This is a persistent bug. YT Vanced will simply stop working and state I have no Internet. This happened before a few weeks ago and the solution worked, but took too long to do and I can't be bothered to do it this many times. I have fine Internet and Youtube.com works fine in my browser. 

**Variant**
Non-Root

**Vanced version**
16.02.35 - Build - 01.49.00

**Android version**
Android 11 - One UI 3.1

**Device**
Samsung Galaxy S20+

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2. Voilà. "No Internet".

**Expected behavior**
An app that's usable and doesn't keel over and die for 0 reason

Don't want the fix for Non-Root I got last time. That took time I can't be bothered to do every few weeks just to listen to music. I just want you guys to fix the error. Idek what the issue is but I've checked time and time again and it ain't my end.

**Comment by momentoxdtuko** [comment]
The same thing is happening to me with youtube advanced too

**Comment by gghhkm** [comment]
Not to worry, this should be mostly fixed if not completely in the next release.

**Comment by momentoxdtuko** [comment]
is to say that I have to wait?

**Comment by gghhkm** [comment]
Unfortunately yes, if the work around OP mentioned (found no the [Office Vanced Discord](https://discord.com/invite/vanced)) isn't good enough the only thing left to do to use the previous version and wait for next release.

**Comment by momentoxdtuko** [comment]
Okay, I'll wait, I hope it's the last time, by the way, thank you very much for your attention :)

**Comment by oz42** [comment]
This bug still exists in version 16.14.34. Any plans to fix it soon?

**Comment by EmVeddii** [comment]
> This bug still exists in version 16.14.34. Any plans to fix it soon?

I blimming hope so

**Comment by KevinX8** [comment]
It's not a vanced issue it's a microg + battery saving shit issue, the only fix is a full reinstall until android stops killing apps randomly, which is never.

**Comment by EmVeddii** [comment]
It clearly ain't closed mate. Someone else just said it's still happening. But sure just close it because its a reoccurring bug...

**Comment by KevinX8** [comment]
> It clearly ain't closed mate. Someone else just said it's still happening. But sure just close it because its a reoccurring bug...

read my edit, it's an unfixiable bug, what's the point of leaving it open?

**Comment by EmVeddii** [comment]
I doubt it's UNFIXABLE but sure we'll live with a defective app. Whatever

**Comment by KevinX8** [comment]
> I doubt it's UNFIXABLE but sure we'll live with a defective app. Whatever

tell us how to stop android killing microg, we're waiting
