### ISSUE TITLE
Bug da página inicial 

### ISSUE THREAD

**Issue by Vinicius6969** [YTVanced/Vanced#553]
A página inicial do aplicativo quando a gente desce o dedo para recarregar a página, ela simplesmente não funciona, a página não recarrega, só se você sair do aplicativo, fechar e depois abrir novamente.
Já desinstalei, limpei, desinstalei o launcher, mas nada funciona

**Comment by gghhkm** [comment]
From what I was able to translate.
This is a duplicate of issue #535
