### ISSUE TITLE
[Bug]  Video controls sometimes stop disappearing

### ISSUE THREAD

**Issue by Profmash** [YTVanced/Vanced#554]
**Bug description**
After some time watching video, when you tap the screen and the video gets dark and covers with Play button and anything, it does not hide away until restart (waiting or tap)

**Variant**
Non-Root

**Vanced version**
16.02.35 - Build - 01.47.00

**Android version**
Android 7.0

**Device**
Huawei Honor 8

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2. Click on video
3. Watch it for long time 
4. Tap the screen
5. Sometimes Play/Pause buttons and anything around don't disappear anymore

**Expected behavior**
Fix

_Attach images/videos if possible. These can be helpful in solving the issue._

**Comment by gghhkm** [comment]
Can you provide a screenshot? Thanks.
