### ISSUE TITLE
I need the root apk signed.?? 

### ISSUE THREAD

**Issue by GaboHernandezG** [YTVanced/Vanced#555]
How can I install the "com.google.android.youtube" package on HUAWEI phone
(Without ROOT)

**Comment by gghhkm** [comment]
You can't, you need to be rooted with [Magisk](https://github.com/topjohnwu/Magisk) to use root version. Use Non-Root version available in [Vanced Manager](https://github.com/YTVanced/VancedManager/releases/latest/download/manager.apk)
