### ISSUE TITLE
[Idea] Option to download as video/audio

### ISSUE THREAD

**Issue by onlytanmoy** [YTVanced/Vanced#556]
Please provide option in YTVanced to download the video as mp4 file or just the audio track alone as mp3 file. That way I need not rely on other apps like NewPipe or YMusic.

**Comment by gghhkm** [comment]
We legally can't included any form of download in Youtube Vanced.

**Comment by onlytanmoy** [comment]
@gghhkm ok understood.
Please confirm if this Pure Tuber app (https://www.vanced.pro/) is from Vanced or not? I can install it then.

**Comment by gghhkm** [comment]
> @gghhkm ok understood.
> Please confirm if this Pure Tuber app (https://www.vanced.pro/) is from Vanced or not? I can install it then.

It is not, official Vanced website is https://vancedapp.com

**Comment by onlytanmoy** [comment]
@gghhkm Thanks for confirming mate. Glad I clarified with you :)
