### ISSUE TITLE
[Bug] Watch History & Brand Accounts

### ISSUE THREAD

**Issue by fritolays** [YTVanced/Vanced#557]
Bug description:
Watch history does not update when using a youtube brand account.

Variant:
Non-Root

Android version:
Android 9.0 and 11
No Adblocking installed

Device:
Tab S and Tab S5e

Steps to reproduce the error:
1. Follow standard non-root install via manager
2. Login
3. Watch random video
4. Check watch history for said video

Expected behavior:
Video should tracked in history but isnt.

Further details:
There is currently a warning in the manager app to install version 15.43.32 first to be able to login. However, this version doesn't enable watch history for brand accounts. I found only version 14.21.54 will connect the account properly. Once logged in you can update Vanced to latest without issue.

Just to note, I tried microg version 0.2.6.17455 and 02.16.204713 and both work fine. So I suspect the issue is withing Vanced builds after 14.21.54.

I cant (?) reopen a closed bug so here we are: https://github.com/YTVanced/Vanced/issues/467#issuecomment-783607882

**Comment by gghhkm** [comment]
This should be addressed in the next version to come out soon-ish. I'll leave this open just in case. Close this issue or @ me if it's fixed completely in next version. Thank you for your patience.
