### ISSUE TITLE
[Bug] Download issue

### ISSUE THREAD

**Issue by AntiJack15** [YTVanced/Vanced#558]
The vanced manager won't let me download YouTube vanced anymore, its saying it's incompatible with my phone but I've had it on this phone before, it just disappeared one day and I'm not sure why but now this is happening and I'd like any help I can get.

**Comment by gghhkm** [comment]
https://github.com/gghhkm/Vanced-Issue-Center/blob/main/Guides/BrokenVancedPackage.md
