### ISSUE TITLE
[Bug] The code to link does not load

### ISSUE THREAD

**Issue by z89C** [YTVanced/Vanced#560]
**Bug description**
Well, I wanted to put the code of my TV to YouTube Vanced, but it does not want to link it, I already tried the same way with the original YouTube apk, and everything normal, it lets me link it and everything, but for some reason in YouTube Vanced it does not it works.

**Variant**
Non-Root

**Vanced version**
16.02.35 - Build - 01.47.00

**Android version**
Android 9.0

**Device**
Samsung Galaxy J7 Prime 2

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2. Click on "your account or profile"
3. Setting
4. Watch on TV
5. Enter TV code

**Expected behavior**
Well I was hoping it would work as usual the code doesn't want to load from the new YouTube Vanced update.

YouTube original apk:

https://user-images.githubusercontent.com/80788769/111387045-7f544900-8683-11eb-94b3-8e694e1480e1.mp4

YouTube Vanced:

https://user-images.githubusercontent.com/80788769/111387109-972bcd00-8683-11eb-9d87-3a9e6491eced.mp4

**Comment by gghhkm** [comment]
Most likely just a microG issue, it's possible that the next release will inadvertently fix this as well. I'll leave this open just in case, tell me if the next release fixes it.

**Comment by z89C** [comment]
Hm, I went to check if there was already a Vanced microG update, and apparently a recent one came out, the new update would be 0.2.18.210390, but. Thought I'd fix it, as you said, it's probably a microG issue, but the error is still there, the code still doesn't want to load. I tried to reinstall it, to see if it would fix, but no.

**Comment by z89C** [comment]
Oh well, thanks for clarifying, I just hope that error is fixed, if I have no other choice, I will not use YouTube Vanced Chromecast, no offense

**Comment by BakedCanadian420** [comment]
I just made an account to say that I am facing a similar issue, but not with a code link, Vanced not finding my Chromecast. I can see my CCast just fine in normal YouTube.

Galaxy S10+ Android 11 running February security patch. 

Anyways just throwing g it out there. I figure with the issue preventing the OP to link his stuff can't be resolved at the time, my issue can't either. 

Thanks!

**Comment by gghhkm** [comment]
There's a on going thread in #688 now.
If you're facing issues in the current latest it's do to a whole other thing now and you should move over there.
