### ISSUE TITLE
[Bug] It says that the user blocked the instalation when it didn't happened

### ISSUE THREAD

**Issue by KombatKing** [YTVanced/Vanced#562]
I installed the App from vancedapp.com.
I am using the latest version
This is an issue in the Vanced Manager app (NOT Youtube Vanced/Music)
This issue keeps re-occurring every time I try
As a MIUI user, I disabled MIUI optimisations

Phone Specifications:
Brand: Xiaomi Redmi Note 8
Variant: Non-Root
Operating System: MIUI Global 12.0.3
Android Version: 10 QKQ1.200114.02
Vanced Manager Version: 2.5.1 (Weed)

Every time I try to install MicroG Version 0.2.16.204713 from Vanced Manager Version: 2.5.1 (Weed), even after I allow the app to install from unknown sources, it shows the message "Error: the installation failed because the user blocked the installation"
When I click in the option Avanced it says "INSTALL_FAILED_INTERNAL_ERROR: Permission denied"
I never denied any permission
I allowed everything
It just keeps going to this error, I tried multiple times, redownloaded, rebooted my device, even tried a factory reset, nothing works
I used Vanced for months, never stopped working, and I never had an error like that until I had to reinstall the app, and after that, simply didn't work again.
Please help (hate ads from the bottom of my heart).

Screenshots attatched:

Error screen
![Screenshot_2021-03-17-21-09-27-000_com vanced manager](https://user-images.githubusercontent.com/80862426/111554562-5c01ca80-8765-11eb-934c-f42420561bb3.jpg)

App configs screen (extended)
![Screenshot_2021-03-17-21-09-48-076_com miui securitycenter](https://user-images.githubusercontent.com/80862426/111554564-5d32f780-8765-11eb-9ae9-d6af13e96415.png)

**Comment by dhruvkrishnavaid** [comment]
Try the installation again.

If it fails this time too, then you can go to Android/data/com.vanced.manager/files/microg and manually install the microg.apk

If the folder is empty, then you may go [here](https://drive.google.com/file/d/1-LCUV9WTBum8_rbQFAveYabiViADWPNS/view?usp=drivesdk) and download the microg.apk which I have uploaded and try to install that.

**Comment by gghhkm** [comment]
Disable MIUI optimization

**Comment by KombatKing** [comment]
@gghhkm MIUI is set to "no restrictions" I can install MicroG from another source and use it, but still can't use Vanced manager to install YTVanced, with I can't find any way to do it without the manager

**Comment by KombatKing** [comment]
@dhruvkrishnavaid This helped, I could install MicroG without the Manager and use it, but still can't install YouTube Vanced since I need the manager to do it

**Comment by gghhkm** [comment]
Disable MIUI optimization in Dev settings 😐
Google it.

**Comment by KombatKing** [comment]
@gghhkm Ok,I googled it, and could finish the install, but now I have another issue, the app simply won'nt open, keeps loading for hours (I tried) with all the steps before done and stable and fine network, sorry for being bothering you, but it's really bothering me, but I just want to use your app without touble at all

https://user-images.githubusercontent.com/80862426/111716229-545d2700-8834-11eb-802c-b1e4317950d8.mp4

**Comment by gghhkm** [comment]
1. Make sure you're using Vanced Manager 2.4.0 or above.
2. disable MiUi optimization
3. Install Vanced MicroG
4. Disable battery optimization for Vanced MicroG ASAP
Use https://dontkillmyapp.com/ if needed.
5. Install Vanced ***15.40.37***
6. Login 
7. Update to latest
8. you can readable MiUi optimization at this point if you're MIUI version requires it.

Go to [The Official Discount]https://discord.gg/Vanced
