### ISSUE TITLE
[Bug] home page doesn't refresh

### ISSUE THREAD

**Issue by yousefsrour** [YTVanced/Vanced#563]
**Bug description**
Home page doesn't refresh when pulled from top, works on explore/subscription/library but not on home page.

**Variant**
Non-Root

**Vanced version**
16.02.35

**Android version**
Android 10

**Device**
Google pixel 2 xl

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2. Pull from top
3. doesn't show refresh animation nor does it refresh

**Expected behavior**
Should refresh like last version

**Comment by gghhkm** [comment]
This is being addressed in the next release.
