### ISSUE TITLE
[Bug] Portrait/Vertical Video Bug

### ISSUE THREAD

**Issue by 123-bott** [YTVanced/Vanced#566]
**Bug description**
Portrait/Vertical videos can't be viewed in max resolution possible. 

**Variant**
Non-Root

**Vanced version**
16.02.35 - Build - 01.47.00

**Android version**
Android 6

**Device**
Vivo Y53

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app.
2. Watch any portrait/vertical videos. (I mean any videos in 1080p or higher so you can really check.)
3. Check video resolution.

**Expected behavior**

EXPLAINATION: What I mean "portrait videos" are videos intended to be viewed as portrait or many used to the words this kind of videos as "vertical videos". I'm not saying that videos doesn't work/play unexpectedly when the phone is in portrait mode. 

When the "max resolution" option and VP9 is enabled, my phone can work at 1080p 60fps. But I noticed that when I tried to watch a video that is in portrait, the only highest possible resolution (when the video is portrait/vertical) is 480p. I already tested 1:1, 18:9, and 4:3 videos and it works as intended, but 9:16 doesn't. 

I don't know if this is because of the update (just used this app 1 month on this phone). Maybe it's just a bug that only shows in this particular phone.

**Comment by milindgoel15** [comment]
Refer to #576 from now since that is one of the current issues as well. closing this
