### ISSUE TITLE
[Bug] Can not connect with google

### ISSUE THREAD

**Issue by melzer12** [YTVanced/Vanced#567]
**Bug description**
When I run youtube, I can't connect to my Google account, it says "there was a problem communicating with Google servers"

**Variant**
Non-Root/

**Vanced version**
16.02.35 - Build - 01.47.00

**Android version**
Android 11

**Device**
Samsung Galaxy S21

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2. Click on account logo
 

![Screenshot_20210318-163950_Vanced microG](https://user-images.githubusercontent.com/80909616/111654250-dfc0c300-8808-11eb-9aae-6d4a2c4864a5.jpg)

**Comment by gghhkm** [comment]
1. Make sure you're using Vanced Manager 2.4.0 or above.
3. Install Vanced MicroG
4. Disable battery optimization for Vanced MicroG ASAP
Use [Don't Kill My App](https://dontkillmyapp.com/) if needed.
5. Install Vanced ***15.40.37***
6. Login 
7. Update to latest


Go to [The Official Discord](https://discord.gg/Vanced) for any further assistance.
