### ISSUE TITLE
[Bug] non-root. 16.02.35.   Android version 11.   Samsung Note 20 ultra.  Steps to reproduce the error: 1. Open the app.    **Expected behavior**  When i open the app it just buffers forever. It wont let me view any videos. I can open up the settibgs and what not but cant do anything on the app itself. (I can post a video in discord if this helps)

### ISSUE THREAD

**Issue by BlakeGoat** [YTVanced/Vanced#569]
**Bug description**
Replace me with a clear and detailed description of the bug.

**Variant**
Non-Root/Root

**Vanced version**
16.02.35 - Build - 01.47.00

**Android version**
Android 9.0 - Pie

**Device**
Samsung Galaxy S8

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
3. ....

**Expected behavior**
Replace me with a description of what you expected should happen and what happened instead.

_Attach images/videos if possible. These can be helpful in solving the issue._

**Comment by gghhkm** [comment]
You filled this out incorrectly.
Sense you're already in [The Vanced Discord](https://discord.gg/Vanced) you can go to [this message](https://discord.com/channels/328493314485518336/358967876193091584/809525073903616022)

**Comment by BlakeGoat** [comment]
Oh sorry not good at reading. Thanks for the help!
