### ISSUE TITLE
[Bug] Auto-Repeat linked to Autoplay does not function

### ISSUE THREAD

**Issue by CherenTheCat** [YTVanced/Vanced#57]
I am using the latest version of Vanced, and despite having the "Autorepeat is linked to Autoplay" option on, and Autoplay off, the video does not repeat, instead showing the typical end of video controls. This is one of the primary reasons I use Vanced, so the fact that it's not working is pretty annoying.

**Comment by VancedOfficial** [comment]
Should be fixed in the 15.38.35 release. Open a new issue if not.
