### ISSUE TITLE
[Bug] YouTube vanced is not working at all and all the versions are like that  

### ISSUE THREAD

**Issue by wildbeast1** [YTVanced/Vanced#571]
![Screenshot_20210320-005557](https://user-images.githubusercontent.com/81002190/111859407-1422a500-8917-11eb-8cd9-5107a62aadde.jpg)
![Screenshot_20210320-005602](https://user-images.githubusercontent.com/81002190/111859408-14bb3b80-8917-11eb-8d0c-e8243d9ca87b.jpg)

**Bug description**
Replace me with a clear and detailed description of the bug.

**Variant**
Non-Root

**Vanced version**
16.02.35 - Build - 01.47.00

**Android version**
Android 11

**Device**
Samsung Galaxy A71

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
3. ....

**Expected behavior**
Replace me with a description of what you expected should happen and what happened instead.

_Attach images/videos if possible. These can be helpful in solving the issue._

**Comment by gghhkm** [comment]
#Preparations for clean install
1. Remove the microG account from system settings 
2. Uninstall Vanced, Vanced MicroG & Vanced Music.  
3. Reboot. 

#Installation
1. Make sure you're using [Vanced Manager 2.4.0 or above](https://github.com/YTVanced/VancedManager/releases/latest/download/manager.apk).
2. Install Vanced MicroG
3. Disable battery optimization for Vanced MicroG ASAP
Use [Don't Kill My App](https://dontkillmyapp.com/) if needed.
4. Install Vanced 15.40.37  &/or Music (Note : latest music should work without issue now)
5. Login 
6. Update to latest

[Official Discord](https://discord.gg/Vanced)

**Comment by wildbeast1** [comment]
> #Preparations for clean install
> 
> 1. Remove the microG account from system settings
> 2. Uninstall Vanced, Vanced MicroG & Vanced Music.
> 3. Reboot.
> 
> #Installation
> 
> 1. Make sure you're using [Vanced Manager 2.4.0 or above](https://github.com/YTVanced/VancedManager/releases/latest/download/manager.apk).
> 2. Install Vanced MicroG
> 3. Disable battery optimization for Vanced MicroG ASAP
>    Use [Don't Kill My App](https://dontkillmyapp.com/) if needed.
> 4. Install Vanced _**15.40.37**_ &/or Music (Note : latest music should work without issue now)
> 5. Login
> 6. Update to latest
> 
> [Official Discord](https://discord.gg/Vanced)

Thank you it worked.
