### ISSUE TITLE
[Bug] Some videos defaults to 480p and cannot be tuned higher regardless of settings

### ISSUE THREAD

**Issue by Neubulae** [YTVanced/Vanced#576]
**Bug description**
Some videos, especially a lot of portrait videos I watch(attached below, almost every Groove Coaster playthrough of his channel suffer from the same issue) always set themselves to 480p. I can try to select a higher resolution(in this case, 720p60) but then it drops back the the one exactly below.(720p60 minus one is 480p)

**Variant**
Root

**Vanced version**
16.02.35 - Build - 01.47.00

**Android version**
Android Q

**Device**
Xiaomi RedMi 5 Plus

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the video
2. Video defaults to 480p
3. Try to change the resolution higher
4. Still 480p.

**Expected behavior**
The video itself defaults to the resolution I set in the settings.

**Video**
https://www.youtube.com/watch?v=B4XSARGONe4

**Related issues**
https://github.com/YTVanced/Vanced/issues/261
https://github.com/YTVanced/Vanced/issues/452
https://github.com/YTVanced/Vanced/issues/499
https://github.com/YTVanced/Vanced/issues/566

**Comment by mrerick94** [comment]
I'm having the same issue here. Android 11. Galaxy S20+ Exynos 990 version.

**Comment by Neubulae** [comment]
> I'm having the same issue here. Android 11, Galaxy S20+ Exynos 990 version. Non-root. Vanced version 16.02.35. For me it's only on vertical videos tho.

yes it happens a lot on vertical videos

**Comment by Neubulae** [comment]
what the hec

**Comment by KevinX8** [comment]
It's for portrait videos, it's a known issue

**Comment by Neubulae** [comment]
I mean how is this marked as closed and wontfix

**Comment by KevinX8** [comment]
It's a duplicate and being addressed on the original
