### ISSUE TITLE
[Bug] "Youtube can't open this link"

### ISSUE THREAD

**Issue by MonoSoda** [YTVanced/Vanced#578]
**Bug description**
When I use youtube vanced I cant open any sort of links inside the app, but when I use normal youtube I can open the same links I couldnt in vanced. I have this problem for about 2 days.

It always says: "youtube can't open this link"

**Variant**
Non-Root

**Vanced version**
16.02.35 - Build - 01.47.00

**Android version**
Android 11.0

**Device**
Samsung Galaxy A51

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2. Click on 'any link'

**Expected behavior**
The link's should open again.

Example (clicked on the first link):

![Screenshot_20210322-064725](https://user-images.githubusercontent.com/81140670/111945824-a6bf7180-8ada-11eb-98fc-8407e7e10ef9.jpg)

**Comment by TheGlitchMaster** [comment]
Me To how to fix it

**Comment by MonoSoda** [comment]
Okay I guess I fixed it... I changed the option in Apps>Standard Apps>open links>YT Vanced from always ask to open in app and that seemd to fix it idk why though I never change any option like that and it was working before

**Comment by charger677** [comment]
> Okay I guess I fixed it... I changed the option in Apps>Standard Apps>open links>YT Vanced from always ask to open in app and that seemd to fix it idk why though I never change any option like that and it was working before

Is that on the phone's settings or on the vanced yt settings?

**Comment by MonoSoda** [comment]
> > Okay I guess I fixed it... I changed the option in Apps>Standard Apps>open links>YT Vanced from always ask to open in app and that seemd to fix it idk why though I never change any option like that and it was working before
> 
> Is that on the phone's settings or on the vanced yt settings?

Its in your phone settings

**Comment by Sutiwas031189** [comment]
ไม่มีอะไรแล้ว

**Comment by LaazV** [comment]
As to not create a duplicate, this bug occurs when trying to open ANY link, not just YouTube links. This kinda of confused me

**Comment by Viom888** [comment]
I have a Simple Solution
1. Download "Android hidden Settings" app
2. Open the app and search for "default apps settings"
3. Tap "Opening links"
4. Scroll down to YouTube Vanced and tap on it
5. Tap on "Add link" and select all links below

Done 👍🏻
