### ISSUE TITLE
Can not Update my Homepage on YouTube app. Can someone helpe me?

### ISSUE THREAD

**Issue by DeadKingVapes** [YTVanced/Vanced#579]
I cant Update my Homepage on the New YouTube Version 16.02.35. If I Download the Version before it works.

**Comment by fargotable** [comment]
> I cant Update my Homepage on the New YouTube Version 16.02.35. If I Download the Version before it works.

If you have the latest version of "android system webview" you need to go back to previous versions.

**Comment by fargotable** [comment]
> If you don't update to the latest version of the Android system webview application, a lot of applications crashes on startup. I don't know why. Let me know about this issue.

No. If you go back a few versions or just click uninstall update, everything will work.

**Comment by gamerover98** [comment]
> > If you don't update to the latest version of the Android system webview application, a lot of applications crashes on startup. I don't know why. Let me know about this issue.
> 
> No. If you go back a few versions or just click uninstall update, everything will work.

Nope, it doesn't work. I've uninstalled all updates from the play store and restart the phone. After its startup, the YouTube Vanced application doesn't load properly.
In addition, Vanced MicroG doesn't login into my google account. It trows me that the account already exists on this phone.

**Comment by gamerover98** [comment]
**UPDATE**

Follow this guide to fix this issue: https://github.com/Vendicated/Vanced/blob/master/Guides/VancedLoadingFix.md
