### ISSUE TITLE
[Bug] Bug with buttons on lock screen

### ISSUE THREAD

**Issue by ksixen** [YTVanced/Vanced#582]
**Bug description**
I can't skip video on lock screen after 5 skips

**Variant**
Non-Root

**Vanced version**
15.43.32

**Android version**
Android 9.0 - Pie

**Device**
Xiaomi Redmi 6

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2. Click on random video
3. Lock the phone
4. Press the 'next' button on lock screen 5 or more times

**Expected behavior**
The 'next' button becomes unclickable. Sometimes with 'previous' button or 'pause' button.
To fix it i need to unlock my phone and open YT Vanced and skip

_Attach images/videos if possible. These can be helpful in solving the issue._

**Comment by dhruvkrishnavaid** [comment]
Hey, install Vanced Manager from https://vancedapp.com and update YouTube Vanced to the latest version.
