### ISSUE TITLE
[Bug] Vanced microG update is not successful

### ISSUE THREAD

**Issue by kristijan1205** [YTVanced/Vanced#583]
**Bug description**
It's stucks with update on Version from 2.....16 on 2....18

**Variant**
Non-Root

**Vanced version**
16.02.35 - Build - 01.47.00

**Android version**
Android 9.0 - Pie

**Device**
Samsung Galaxy S8

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
3. ....

**Expected behavior**
Replace me with a description of what you expected should happen and what happened instead.

_Attach images/videos if possible. These can be helpful in solving the issue._

**Comment by gghhkm** [comment]
Try reinstalling.
Make sure you're using Vanced Manager from https://vancedapp.com
