### ISSUE TITLE
[Bug] can't login to my youtube account at the moment it doesn't recognize the vanced microg account

### ISSUE THREAD

**Issue by amrahmed11922911** [YTVanced/Vanced#584]
**Bug description**
can't access youtube account

**Variant**
Non-Root

**Vanced version**
16.02.35 - Build - 01.47.00

**Android version**
latest version for infinix note 8

**Device**
infinix note 8

**Steps to Reproduce**
Steps to reproduce the error:
i open the app it doesn't recognize the account i try to add it but no use

**Expected behavior**
when i open the app it should connect me automatically with my account it was broken from the beginning i used to manually access my account every time i open the app now it is totally broken

_Attach images/videos if possible. These can be helpful in solving the issue._ 
![Screenshot_20210324-143803](https://user-images.githubusercontent.com/81306916/112312122-20a85400-8caf-11eb-8e75-51972a055969.png)
![Screenshot_20210324-143803](https://user-images.githubusercontent.com/81306916/112312176-33bb2400-8caf-11eb-84ec-1a1baf497836.png)

**Comment by dhruvkrishnavaid** [comment]
Hey, open the Vanced MicroG and login with your account there first, then reboot and try to open YouTube Vanced, maybe it might work.

**Comment by MikeKall** [comment]
I have the same issue. I was expecting the last update to solve it but no luck. 

**Variant**
Non root

**YT Vanced Version**
16.16.38

**Vanced MicroG version**
0.2.17.210500

**Android**
MIUI 12.0.8

**Device**
Poco X3
