### ISSUE TITLE
[Bug] replaceme

### ISSUE THREAD

**Issue by luiz7Marcelo** [YTVanced/Vanced#586]
![Screenshot_20210324-172721](https://user-images.githubusercontent.com/81329630/112378942-4ee55e00-8cc6-11eb-87fc-02b918f34f30.jpg)
![Screenshot_20210324-172726](https://user-images.githubusercontent.com/81329630/112378982-5e64a700-8cc6-11eb-8fe8-ba8f4aa3c6df.jpg)

**Bug description**
Replace me with a clear and detailed description of the bug.

**Variant**
Non-Root/Root

**Vanced version**
16.02.35 - Build - 01.47.00

**Android version**
Android 9.0 - Pie

**Device**
Samsung Galaxy S8

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
3. ....

**Expected behavior**
Replace me with a description of what you expected should happen and what happened instead.

_Attach images/videos if possible. These can be helpful in solving the issue._ 
Não consigo entrar na minha conta, não aparece.

**Comment by gghhkm** [comment]
Failure to fill out the issue page correctly.
