### ISSUE TITLE
[Bug] Youtube Vanced doesn't load shorts

### ISSUE THREAD

**Issue by IM-TECHNO** [YTVanced/Vanced#588]
**Bug description**
Shorts cannot change, when I swipe up.. It just stays still

**Variant**
Non-Root

**Vanced version**
16.02.35 - Build - 01.47.00

**Android version**
Android 9.0 - Pie

**Device**
ASUS ZenFone Max Pro M1

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2. Click on any video
3. Scroll down and tap shorts videos
4. Then swipe up, it won't change to next shorts

**Expected behavior**
When swiped, it should changed to the next shorts

**Comment by dhruvkrishnavaid** [comment]
Mmm, it works, at least for me.
Link to screen record: https://gofile.io/d/yfj3sx

**Comment by IM-TECHNO** [comment]
That's exactly what it should.... But it doesn't do that for me

**Comment by dhruvkrishnavaid** [comment]
Can you do a quick screen record? That would be helpful 😃

**Comment by IM-TECHNO** [comment]
Here : https://gofile.io/d/v4bin6

**Comment by dhruvkrishnavaid** [comment]
Hmm, this is weird. Wait for the developers to fix this.
Meanwhile, you can try reinstalling MicroG and Vanced, it might work, I'm not sure :)

**Comment by IM-TECHNO** [comment]
I did ! This worked well

**Comment by dhruvkrishnavaid** [comment]
Good😃
