### ISSUE TITLE
[Idea] Remove video recommendations 

### ISSUE THREAD

**Issue by pietro14** [YTVanced/Vanced#589]
**Description**
Sometimes I end up spending so much time watching videos just because YouTube recommends me interesting videos. So I would like to have the possibility to disable all kind of suggestions in YouTube Vanced, like:

- Home tab recommendations (Picture 1)
- Explore tab recommendations (Picture 2)
- Recommendations while watching videos (Picture 3). In this case, it would be enough to show the video description (like in Picture 4) by default.

I know you can already disable suggestions at the end of a video, but I don’t think it’s enough.

Also, on my PC I can use a browser extension for Chrome called 'Unhook YoutTube'. Maybe you can take inspiration from it.

![imgonline-com-ua-resizePERCFuEI9w1flY0C](https://user-images.githubusercontent.com/41691318/112489167-7992ed80-8d7e-11eb-982e-75165b0f05eb.jpg)
(Picture 1: Home tab recommendations)

![imgonline-com-ua-resizePERCm7h9ldaIA0zL](https://user-images.githubusercontent.com/41691318/112489186-7e57a180-8d7e-11eb-9161-0a0f3dffda16.jpg)
(Picture 2: Explore tab recommendations)

![imgonline-com-ua-resizePERCkegLmxwGu316](https://user-images.githubusercontent.com/41691318/112489212-83b4ec00-8d7e-11eb-9847-4685f754d58a.jpg)
(Picture 3: Recommendations while playing video)

![imgonline-com-ua-resizePERCsy1XytMXfJae](https://user-images.githubusercontent.com/41691318/112489224-87487300-8d7e-11eb-884b-6a8329db7391.jpg)
(Picture 4: Video description while playing video)

**Comment by OJ7** [comment]
Partial duplicate of #334?
