### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by Bohrito** [YTVanced/Vanced#591]
I cant reload the main page (Start page in german not so sure about the english name). If I swipe down at the top of the page it sould reload and show diferent videos. 
While it works when I'm brwosing the Abo/Trend section it dosen't on the main page. Even if I watched a video and go back to the main page it dosen't chanche. 

Workaround if a force stop the app it will realod a new main page after starting it not so if I just close it and reopen it. 

Android version 10 (oxygenos 10.3.5) 

Divice OnePlus 6T 

Venced version 16.02.35

**Comment by LennDoMations** [comment]
Same sh+t here.

**Comment by gghhkm** [comment]
#608
