### ISSUE TITLE
Erro

### ISSUE THREAD

**Issue by RafaMPG** [YTVanced/Vanced#592]
![Screenshot_20210327-012158](https://user-images.githubusercontent.com/81457529/112710418-de923480-8e9f-11eb-885f-70000949008a.png)

**Bug description**
Replace me with a clear and detailed description of the bug.

**Variant**
Non-Root/Root

**Vanced version**
16.02.35 - Build - 01.47.00

**Android version**
Android 9.0 - Pie

**Device**
Samsung Galaxy S8

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
3. ....

**Expected behavior**
Replace me with a description of what you expected should happen and what happened instead.

_Attach images/videos if possible. These can be helpful in solving the issue._

**Comment by gghhkm** [comment]
https://github.com/gghhkm/Vanced-Issue-Center/blob/main/Guides/BrokenVancedPackage.md
