### ISSUE TITLE
[Bug] replaceme

### ISSUE THREAD

**Issue by georgeiojm** [YTVanced/Vanced#593]
**Bug description**
I have a 3 or so more accounts on one email and two things are happening on the newest update on Vanced. One, it's not showing all my accounts. Only one of them. The second thing is it one even log me out of the email it's connected to. It gives me an option to add account. Which I then press sign in, type in the email..however even using a different email, it just sends me to the one that it was connected to. It wasn't like this before I updated. Love the app. Keep up the good work

**Variant**
Non-Root/Root

**Vanced version**
16.02.35 - Build - 01.47.00

**Android version**
Android 9.0 - Pie

**Device**
Samsung Galaxy S8

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
3. ....

**Expected behavior**
Replace me with a description of what you expected should happen and what happened instead.

_Attach images/videos if possible. These can be helpful in solving the issue._

**Comment by gghhkm** [comment]
Multiple accounts are currently not possible in latest.
Use 15.43.32 until next release.
