### ISSUE TITLE
[Bug] picture in picture video sometimes doesn't show 

### ISSUE THREAD

**Issue by YuhiAida** [YTVanced/Vanced#597]
**Bug description**
Some times when you minimize the app the picture in picture frame gets 100% translucent(it still there, you can grab it and move it, the x at the bottom ton can be seen) some times when you move it, it will appear normally. This bug doesn't appear all the time.

**Variant**
Non-Root

**Vanced version**
16.02.35 - Build - 01.47.00

**Android version**
Android 11

**Device**
Xiaomi mi 10t 

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2. Play any video
3. Minimize 

**Expected behavior**
Picture in picture video shows normally 

![Screenshot_2021-03-28-17-03-22-258_com miui home](https://user-images.githubusercontent.com/21134775/112767771-f4fad600-8fee-11eb-924b-9028692649a7.jpg)

![Screenshot_2021-03-28-17-03-28-432_com android systemui](https://user-images.githubusercontent.com/21134775/112767780-fcba7a80-8fee-11eb-99c5-75cab9937e6a.jpg)

**Comment by gghhkm** [comment]
This is either a issue with your ROM or a bug google created, we can't do much about it unfortunately.
You can try something like clearing the cache partition of the device.

**Comment by YuhiAida** [comment]
> This is either a issue with your ROM or a bug google created, we can't do much about it unfortunately.
> You can try something like clearing the cache partition of the device.

It appeared after I update the app to 16.02.35, but I'll check.

**Comment by gghhkm** [comment]
> > This is either a issue with your ROM or a bug google created, we can't do much about it unfortunately.
> > You can try something like clearing the cache partition of the device.
> 
> It appeared after I update the app to 16.02.35, but I'll check.

If it only appears in 16.02.35 then it's most likely googles fault. The next release of Vanced has potental to fix this in that case because it'll be built on a newer Stock youtube depending on if google fixed it.
