### ISSUE TITLE
[Bug] when I open youtube settings, the app automatically opens the Home screen and closes the app

### ISSUE THREAD

**Issue by Jokerr31** [YTVanced/Vanced#599]
**Bug description**
i open youtube vanced settings but automatically turn home screen and bug description *continually stopped*
16.02.35 base ,no problems in previous versions (15.43.32 perfect )
of course first 15.43 install and after 16.02 update
videos open not problem✓

Edit: Clicking on channels does not open but video opened

https://user-images.githubusercontent.com/81597334/112914317-64161e80-9104-11eb-8a28-daa8e80c84db.mp4

**Variant**
Non-Root

**Vanced version**
16.02.35 - Build - 01.47.00

**Android version**
Android 9.0 - Pie

**Device**
General Mobile 8 32GB

**Expected behavior**
Fixed*

_Attach images/videos if possible. These can be helpful in solving the issue._

**Comment by KevinX8** [comment]
whatever you have installed that's not from us, we never made a build with 500 duplicate strings?
