### ISSUE TITLE
[Bug] Video Resume Problem

### ISSUE THREAD

**Issue by durrjunaid** [YTVanced/Vanced#6]
Video plays from start if you close a unfinished video or close Vanced Youtube App. Video doesn't resume from that point where it was closed.

**Comment by X1nto** [comment]
Probably an issue with ROM, which ROM is it? And what version of vanced are you using?

**Comment by durrjunaid** [comment]
I am using latest version of Vanced Youtube and lineage OS v17.1 (Android 10) Rom

**Comment by spicyfoxx** [comment]
Both stock YouTube and Vanced don't record the current play time `every time` you close it so it may start at the beginning for some videos. This is normal behaviour. 
If this issue occurs on `every single` videos, it's a ROM issue.
