### ISSUE TITLE
[Idea] Crope and stretch

### ISSUE THREAD

**Issue by Lobelobel** [YTVanced/Vanced#60]
I would find it very useful to be able to change aspect ratio either by croping and stretching, basically like you can do in VLC for android.

**Comment by JaftheGreat** [comment]
Yes I agree with this.
I just joined the discord to suggest this. I found reports of earlier versions of vanced being able to zoom to fill on tablets like you can on mobile devices nowadays.

To be clear - I have a Z fold 2 would like to be able to zoom in my videos to fill the screen. Similar to the experience you get when watching YouTube on something like an iPhone or Samsung S20 - you can pinch to zoom.

**Comment by Lobelobel** [comment]
> Yes I agree with this.
> I just joined the discord to suggest this. I found reports of earlier versions of vanced being able to zoom to fill on tablets like you can on mobile devices nowadays.
> 
> To be clear - I have a Z fold 2 would like to be able to zoom in my videos to fill the screen. Similar to the experience you get when watching YouTube on something like an iPhone or Samsung S20 - you can pinch to zoom.

Well, funny enough, I also joined discord and came here because I have a Z fold 2 for few days now and find it much better to be able to use the whole screen 😉 but depending on the video or the screen you wanna use I also find it better to be able to stretch rather than to crope the video, that's why I insisted on this point in my fist comment.
Just in case, VLC does a good job for videos that you have on your device but sadly not for online videos.
