### ISSUE TITLE
Vanced can't start

### ISSUE THREAD

**Issue by sombresu** [YTVanced/Vanced#600]
- For MIUI users: I disabled MIUI optimisations

**Phone Specifications:**
- Brand: Xiaomi Poco X3
- Operating System: Miui 12
- Android Version: Android 10
- Vanced Manager Version: Latest

**Please describe the problem you are having in as much detail as possible:**

**Steps to reproduce:**
Start vanced

**Further details:**
Video thumbnails not loaded, only blank screen

![Screenshot_2021-03-30-11-23-47-242_com.vanced.android.youtube.jpg](https://user-images.githubusercontent.com/62043417/112934207-75364e00-914b-11eb-84a2-c9e715b2480a.jpg)

**Comment by Xi-PP** [comment]
1• Uninstall YT Vanced
2• install older version & open
3• wait until it's complete the login process
4• login done = Update to latest

**Comment by sombresu** [comment]
Thank you 😊
