### ISSUE TITLE
[Idea] Buds Pro/Live Auto Switching

### ISSUE THREAD

**Issue by jypixel** [YTVanced/Vanced#601]
**Description**
With stock youtube app, it automatically switch/connects to buds which I am using with my tab s6. This - https://9to5google.com/2021/03/04/galaxy-buds-plus-device-switching-update/
However in vanced, this feature do not work. Is there any way I can use this function with Youtube vanced?

**Comment by nochlab1** [comment]
If doesn't work with latest version of vanced then its most probably a whitelist from samsung

**Comment by jypixel** [comment]
> If doesn't work with latest version of vanced then its most probably a whitelist from samsung

I think so.. then is there no way to make the feature work ?? I don't think samsung will make that feature to work
