### ISSUE TITLE
[Bug] Propagandas

### ISSUE THREAD

**Issue by wellgsouza** [YTVanced/Vanced#602]
**Bug description**
Instalei o aplicativo de vocês mas ainda sim continua com propagandas tanto em clipes de música quanto durante entrevistas. Se elas forem longas tem propaganda durante o decorrer da entrevista.

**Variant**
Non-Root

**Vanced version**
16.02.35 - Build - 01.47.00

**Android version**
Android 10

**Device**
Redmi Note 8

**Steps to Reproduce**
Steps to reproduce the error:
1. Abro o aplicativo;
2. Clico em algum vídeo aleatório ou playlist;
3. Aperto play;
4. Ao acabar o vídeo e ao iniciar outro tem propagandas ou durante alguma entrevista que assisto no se for com mais de 10 minutos de vídeo também tem propaganda durante ela.

**Comment by gghhkm** [comment]
If you're referring to sponsors; turn on "SponsorBlock".
If you're referring to video ads then you have to reinstall Vanced from https://vancedapp.com because video ads are completely removed forever; it's impossible to get them in Vanced.
