### ISSUE TITLE
[Bug] Google accounts are not showing in the latest version of youtube vanced 16.02.35

### ISSUE THREAD

**Issue by gurukiranx** [YTVanced/Vanced#609]
**Bug description**
In the newest version of YT vanced the google accounts which we are logged in are not visible.it only shows add account, even if click and added my google account even after adding it, it shows the same thing add account with + symbol ( This problem is not there in 15.43.32)

**Variant**
Non-Root

**Vanced version**
16.02.35 - Build - 01.47.00

**Android version**
Android 9.0 - Pie

**Device**
Honor 9N

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app.
2. Click on profile photo at the top right.
3. expand account name with down arrow at the top.
4. this shows error "add account", even if i already logged in.

**Expected behavior**
it should show my google accounts.
![Ex3iOXxVoAgh_u3](https://user-images.githubusercontent.com/59090788/113252428-77caac00-92e1-11eb-9171-b5f8482adeca.jpeg)

_Attach images/videos if possible. These can be helpful in solving the issue._

**Comment by AkashRahane** [comment]
Mee too https://github.com/YTVanced/Vanced/issues/656

**Comment by AkashRahane** [comment]
Me too https://github.com/YTVanced/Vanced/issues/656

**Comment by drif13** [comment]
Can't log in my google account for Vanced on two phones OnePlus 3T and OnePlus 8T

**Comment by arfest23** [comment]
Me too

**Comment by gghhkm** [comment]
#396 
Multiple accounts are not supported in latest. wait for the next release, soon.
