### ISSUE TITLE
[Idea] Auto Captions selection

### ISSUE THREAD

**Issue by pirottedamien** [YTVanced/Vanced#61]
Hello,
Youtube always adds captions to videos that aren't in youtube's language configurations, even if I don't want to. I always have to disable it for every video. My youtube is in french, and I always get captions on an english video, but I don't need them. 
This could be like the resolution or playback speed setting, just as simple. I'd really like to see that coming.
Thank you

**Comment by K0media** [comment]
> Hello,
> Youtube always adds captions to videos that aren't in youtube's language configurations, even if I don't want to. I always have to disable it fir every video. My youtube is in french, and I always get captions on an english video, though I don't need them.
> This could be like the resolution or playback speed setting, just as simple. I'd really like to see that coming.
> Thank you

Yeah, I like this one. Hope the devs hear us. 🤷‍♂️
