### ISSUE TITLE
[Bug] can't sign in

### ISSUE THREAD

**Issue by Jaberm92** [YTVanced/Vanced#611]
**Bug description**
I cannot sign in into my account, the issue is happening in my two phones Huawei mate 30 pro and Samsung galaxy s9. I tried to uninstall it and rrinstall it again but it didn't solve the issue

**Variant**
Non-Root/Root

**Vanced version**
16.02.35 - Build - 01.47.00

![Screenshot_20210401_192139_com vanced android youtube](https://user-images.githubusercontent.com/81767746/113324405-b8491a80-931f-11eb-974d-0dce13fdddc9.jpg)

**Device**
Huawei mate 30 pro and Samsung galaxy s9

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2. Click on 'accounts'
3. When I try to sign in the message 'please check your network' appears

_Attach images/videos if possible. These can be helpful in solving the issue._

**Comment by gghhkm** [comment]
#396
