### ISSUE TITLE
[Bug] vanced forced closing after i update my OS

### ISSUE THREAD

**Issue by ooi0330** [YTVanced/Vanced#615]
**Bug description**
forced closing,unable to reach the homepage of youtube vanced 

**Variant**
Non-Root

**Vanced version**
tried every version, all forced closing

**Android version**
Android 11

**Device**
iQOO 3

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2. And has been forced closing

**Expected behavior**
Should be same as normal use like youtube. Open the app and reach the homepage

**Comment by probe7** [comment]
i also faced the same issue

**Comment by KevinX8** [comment]
no logcats or anything provided
