### ISSUE TITLE
[Bug] YT Music 50% Battery Usage in Background

### ISSUE THREAD

**Issue by thzeus** [YTVanced/Vanced#617]
**Bug description**
After the new update of YT Music I have noticed my phone battery not lasting even half a day. Today from a full charge, it has been active 0 minutes but background has drained 50.4%.

**Variant**
Non-Root

**Vanced version**
4.18.50

**Android version**
Android 11

**Device**
Samsung Galaxy S10+

**Steps to Reproduce**
No steps to reproduce.

**Expected behavior**
Not draining as much. I use the Youtube Vanced app and it works correctly, also no problem at MicroG.

I read about not supporting the Music app, but it does interfere for further using it. Out of all Vanced apps, I use this the most.

Thank you and have a great day!

![Screenshot_20210403-181306_Device care](https://user-images.githubusercontent.com/43756096/113482944-94194500-94a9-11eb-9d63-16bf0fe92bfb.jpg)

**Comment by gghhkm** [comment]
https://github.com/YTVanced/Vanced#have-a-vanced-music-bug
