### ISSUE TITLE
[Bug] Vanced not connecting to internet

### ISSUE THREAD

**Issue by gaspir** [YTVanced/Vanced#618]
**Bug description**
When opening the app it says "connect to internet". I have reinstalled both microg and the app to no avail. It was working fine 24h ago for me.

**Variant**
Non-Root

**Vanced version**
16.02.35 - Build - 01.47.00

**Android version**
Android 11.0 (3.1)

**Device**
Samsung Galaxy S10+

**Comment by gghhkm** [comment]
### ***General fix for everything Non-root***
* ` this will fix most nonroot Vanced related issues`
* ` you can consider this the proper Vanced install method.`



**#Preparations for clean install**
1. Remove the microG account from system settings.
2. Uninstall Vanced, Vanced MicroG & Vanced Music.  
3. Reboot. 

**#Installation**
1. Make sure you're using Vanced Manager 2.4.0 or above.
2. Install Vanced MicroG
3. Disable battery optimization for Vanced MicroG ASAP
Use [Don't Kill My App](https://dontkillmyapp.com/) if needed.
4. Install Vanced ***15.40.37***  &/or Music (Note : latest music should work without issue now)
5. Login 
6. Update to latest
