### ISSUE TITLE
[Bug] Unable to update YT Music Vanced

### ISSUE THREAD

**Issue by pmcfarland** [YTVanced/Vanced#619]
There has been an update for YT Music Vanced for some time but I'm unable to update. I have version 4.07.51 installed but the manager lists 4.18.50 as the lastest. When I click update it downloads, asks me to install and then fails shortly thereafter giving the error INSTALL FAILED UPDATE_INCOMPATIBLE: Package.

Other apps update fine and have so for some time. I hardly use YT Music so I never cared too much but figured I should report it.

I uninstalled the existing YT Music Vanced app and went to try installing it fresh but I was stopped by Google's Advanced Protection block of installing from unknown sources.

I'm not sure if this was a bug with Vanced manager/the Vanced music app or if this was the issue with updating all along. As I said I hardly use the app so no loss but wanted to at least document it.

**Comment by pmcfarland** [comment]
Screenshot of current vs new version: https://i.imgur.com/WPSdYJz.jpg

Screenshot of update error message:
https://i.imgur.com/ypP0pdS.jpg

Screenshot of block by Google advanced protection:
https://i.imgur.com/ZBDknqY.jpg

**Comment by gghhkm** [comment]
You got Vanced Manager from https://vancedapp.com or the github correct?
Plz make sure you're using an official version.
