### ISSUE TITLE
Root access not granted

### ISSUE THREAD

**Issue by dr-kaisar** [YTVanced/Vanced#62]
After updating the Vanced Manager app from v1.2 to v1.3, every restart of my device causes automatic uninstallation of Youtube Vanced (Rooted version) app. Also when I tap "Root" in the Vanced Manager, it says that root access not granted without any popup for granting root access. I tried uninstalling the Vanced Manager app, rebooting my device and reinstalling the app but didn't work for me. It still says root access not granted. Not sure where is the problem.

**Comment by KevinX8** [comment]
this repo is for vanced youtube issues only
