### ISSUE TITLE
[Bug]Ghost touch occurs when using background PIP MOD.

### ISSUE THREAD

**Issue by Ken-Kang** [YTVanced/Vanced#620]
**Bug description**
Ghost touch occurs sometimes when using background pip.

It doesn't seem to happen unconditionally at the moment, and it seems to occur occasionally when it is used in pip mode and displayed on other apps. Please check.

**Variant**
Non-Root

**Vanced version**
16.02.35

**Android version**
Android 10

**Device**
LG G8 ThinQ

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2. Use in pip mode
3. run aother app

**Expected behavior**

Currently, it does not occur in the same way, but it has occurred about three times so far, so it is necessary to check (the phenomenon occurs only when running pip mode).

_Attach images/videos if possible. These can be helpful in solving the issue._

**Comment by gghhkm** [comment]
Youtube and Youtube Vanced uses native android PIP which is controlled by your ROM, so there's not much we can do.
There's also the possibility that google broke it for your device, in which case it should be fixed next release as long as google fixed it in the newer Stock builds.
