### ISSUE TITLE
[Bug] YT and Music say I have no Internet connection 

### ISSUE THREAD

**Issue by LuckymanP** [YTVanced/Vanced#625]
**Bug description**
I keep getting the page that says they're is no internet connection

**Variant**
Non-Root/Root

**Vanced version**
16.02.35 - Build - 01.47.00

**Android version**
Android 9.0 - Pie

**Device**
Samsung Galaxy S8

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
3. ....

**Expected behavior**
Replace me with a description of what you expected should happen and what happened instead.

_Attach images/videos if possible. These can be helpful in solving the issue._

**Comment by AinzTheSupremeOne** [comment]
Download Vanced guide from Play Store and you'll find the solution to your problem there https://play.google.com/store/apps/details?id=com.vanced.faq

**Comment by KevinX8** [comment]
microg/bad gms issue
