### ISSUE TITLE
[bug] cant watch live stream 

### ISSUE THREAD

**Issue by kuning174** [YTVanced/Vanced#627]
![Screenshot_2021-04-07-21-45-21-71_7a4090f09f6554852d748ee9fd6f40d3](https://user-images.githubusercontent.com/40780679/113876752-9dc4e480-97ea-11eb-9f46-5716f3c964ca.png)
I use the last version apk and i cant watch live streaming. So I update to the news version and i still cant watch live streaming. 
but i can still watch video expect life streaming
My phone Realme 5 : Android 9
Thanks

**Comment by AinzTheSupremeOne** [comment]
Looks like a network speed issue. You really can't stream a live video with a 32KB/s connection.
