### ISSUE TITLE
Not loading content in Vanced

### ISSUE THREAD

**Issue by brainahc** [YTVanced/Vanced#628]
![Screenshot_2021-04-07-23-07-33-87_7a4090f09f6554852d748ee9fd6f40d3](https://user-images.githubusercontent.com/35502938/113910173-0ea6d500-97c8-11eb-841f-59e12065d1e2.png)

Apps installed successfully. After login it's not showing any video. Before login it was working correctly. 

I have reinstall app 2 times. 
Clean up data 2 times. 
Mobile restart 1 time
Mobile reset 1 time

Screenshot attached please help me.

**Comment by AutumnalAntlers** [comment]
Same issue on my BF's Galaxy S8 running Android 9, but not on my personal phone. Started yesterday too. Eventually times out and says there's no internet; normal YT doesn't suffer the same issue

**Comment by Ra1d7** [comment]
same thing here, it happened after i was in incognito mode and when i reverted back to my account it got stuck on this loading screen, no matter how many times I reinstalled microg and vanced

**Comment by luimu64** [comment]
https://github.com/Vendicated/Vanced/blob/master/Guides/VancedLoadingFix.md

**Comment by AutumnalAntlers** [comment]
That did it for me! I do remember this process from setup, and in retrospect, it was caused by a changed google password. Just didn't know the symptoms I was looking at. Thanks!

**Comment by brainahc** [comment]
> 
> 
> Same issue on my BF's Galaxy S8 running Android 9, but not on my personal phone. Started yesterday too. Eventually times out and says there's no internet; normal YT doesn't suffer the same issue

so is it still there or you got the solution?

**Comment by Azael111** [comment]
Ami me saca antes de que cargue ya reinicie mi teléfono 3  eres y volvi a descargar todo 3 veces
