### ISSUE TITLE
[Bug] replaceme

### ISSUE THREAD

**Issue by Ziyax2687** [YTVanced/Vanced#629]
**Bug description**
Keeps showing a offline screen when I have a perfectly good internet connection which I have tested with normal YouTube.

**Variant**
Root

**Vanced version**
16.02.35 - Build - 01.47.00

**Android version**
MIUI 12.0.6

**Device**
Xiaomi mi 9 lite

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2. That's it

**Expected behavior**
Should display videos that can be watched.

_Attach images/videos if possible. These can be helpful in solving the issue._

**Comment by Puncake99** [comment]
I also have this issue on Oneplus 9 Pro (non root).

**Comment by gghhkm** [comment]
> I also have this issue on Oneplus 9 Pro (non root).

Go to
#396 

Or

1. Use this Discord invitation.
https://discord.gg/rgwbXEaUCb
 2. Use this link.
https://discord.com/channels/328493314485518336/358967876193091584/809525073903616022

**Comment by gghhkm** [comment]
> **Bug description**
> Keeps showing a offline screen when I have a perfectly good internet connection which I have tested with normal YouTube.
> 
> **Variant**
> Root
> 
> **Vanced version**
> 16.02.35 - Build - 01.47.00
> 
> **Android version**
> MIUI 12.0.6
>
> **Device**
> Xiaomi mi 9 lite


Are you sure you're using the Root version? Because something like this has never happened unless the person is using a custom ROM with MicroG from MicroG project or a bad gapps install.

**Comment by KevinX8** [comment]
This is a MicroG/Bad GMS installtion issue
