### ISSUE TITLE
[Bug with fix] Youtube button in the preview player opens original app

### ISSUE THREAD

**Issue by TrianguloY** [YTVanced/Vanced#63]
Do I need to report the bug and the fix in every new version? If there is anything I can do to add it to the official release please tell me.

## BUG
By pressing the Youtube button in the preview player the original youtube app is opened; or, if you don't have the original app installed, it crashes.

This is the button
![screenshot](https://media.discordapp.net/attachments/663170881572438036/665878542382530589/Screenshot_20200112-1200392.png?width=150&height=266)

You can open the preview player from a play store intent or manually setting the finish_on_ended=true flag.
`adb shell am start -d "https://www.youtube.com/watch?v=Y7dpJ0oseIA" --ez finish_on_ended true`

## Fix

Simply apply this patch to the base.apk decompiled package [for the 15.38.35 version]

```diff
diff --git a/smali/pxj.smali b/smali/pxj.smali
--- a/smali/pxj.smali
+++ b/smali/pxj.smali
@@ -57,6 +57,8 @@
     invoke-direct {v0, v1}, Landroid/content/Intent;-><init>(Ljava/lang/String;)V
 
     iget-object v1, p1, Lavzv;->b:Ljava/lang/String;
+	
+	const-string v1, "com.vanced.android.youtube"
 
     .line 5
     invoke-virtual {v0, v1}, Landroid/content/Intent;->setPackage(Ljava/lang/String;)Landroid/content/Intent;
```

**Comment by VancedOfficial** [comment]
Yeah, so I saw your bug report from the previous version. I tested it on the current version before release and I don't have that issue. That's why I didn't do anything about it. Not really sure why it works differently for you then but I'll try and remember to change that value in the next version.

**Comment by TrianguloY** [comment]
Oh, it worked for you without changing anything? That's strange, on my device it surely didn't work (I have the original YouTube app deactivated, can't uninstall because of no-root, and on my case that button crashes that's why I know it doesn't work). 

The fix I provided solves this, it's basically the same fix as the previous version (with a new class due to obfuscation as expected).

It could be nice if others can test on other devices, perhaps it's not always reproducible.
I'm on android 8.1.0 btw.
