### ISSUE TITLE
Background play stops randomly

### ISSUE THREAD

**Issue by GKid94** [YTVanced/Vanced#630]
Videos stop playing randomly in background play

**Comment by AinzTheSupremeOne** [comment]
Your system is killing the app in background. A fix would be to exclude both Vanced and Vanced microG from all kinds of battery optimization. See https://dontkillmyapp.com for instructions.

**Comment by GKid94** [comment]
It only showed me to disable the battery optimization for MicroG and I did that, can you maybe change the notification to say to disable the optimization for both YouTube Vanced and MicroG?

**Comment by gghhkm** [comment]
> It only showed me to disable the battery optimization for MicroG and I did that, can you maybe change the notification to say to disable the optimization for both YouTube Vanced and MicroG?

Disabling battery optimization for YouTube Vanced is usually unneeded and only a few ROM's with kill background play. while ROM's killing MicroG processes is nearly universal across all devices and MicroG is needed for the app to function properly whenever you're logged in.

**Comment by GKid94** [comment]
Ok but YouTube Vanced doesn't close, it just pauses the video often in background play and I don't know why
