### ISSUE TITLE
Vanced is not opening links

### ISSUE THREAD

**Issue by Cartman34** [YTVanced/Vanced#631]
YT Vanced is not opening links I click and chrome is opening it.
Youtube is uninstalled
My phone is Xiaomi Mi 10 5G
My sysem is up to date, vanced apps too.
System is not even asking for which app I want to use, Vanced's defaults and Chrome's defaults was resetted.

To reproduce, share this youtube link on facebook
https://youtube.com/watch?v=rGWF3ZsZPYs

Then click on it from facebook app, it's not opening with YouTube vanced...

Notes : Facebook App seems using its own webkit's browser and Open with YouTube vanced is present in the 3-dots menu.

**Comment by gghhkm** [comment]
We can't do anything about this, sorry.
