### ISSUE TITLE
Login issues

### ISSUE THREAD

**Issue by explodersname** [YTVanced/Vanced#632]
I have signed into my google account but the account is not showing up in YouTube vance's and if I try to login again it says account already on device

**Comment by kerk12** [comment]
I have the exact same problem. Shows the login icon, I do the login, doesn't enable the account. The front page also acts kind of weird. In my case it doesn't load any of the content.

**Comment by D-Schrutt** [comment]
Hello i have the exact same problem, at first when i open the vanced app, i have infinite loading time and it didn't show anything no matter how long i let it load, ( i've let it load for 4hours in a desperate attempt ), after that, i've deleted everything, downloaded everything again and now when i sign in my google account, it doesn't appear and if i try again it says that my account is already registered on the app.

I'm on a Xiaomi Redmi Note 8, non-rooted.

**Comment by Monsi9** [comment]
Me sucede exactamente lo mismo, abro Youtube Vanced y al iniciar sesión con mi cuenta de Google, no muestra nada en la pantalla de inicio, sólo se queda cargando. Eliminé todo y lo volví a descargar e instalar de nueva cuenta y cuando inicio sesión nuevamente, me sucede lo mismo y no muestra nada.

Yo tengo un dispositivo Samsung Galaxy A51, no rooteado.

**Comment by gghhkm** [comment]
Go to
#396 

Or

1. Use this Discord invitation.
https://discord.gg/rgwbXEaUCb
 2. Use this link.
https://discord.com/channels/328493314485518336/358967876193091584/809525073903616022

Multi accounts do not work on latest.
