### ISSUE TITLE
[Bug] replaceme

### ISSUE THREAD

**Issue by furkanb06** [YTVanced/Vanced#633]
**Bug description**
![Screenshot_2021-04-11-14-21-03-46_7a4090f09f6554852d748ee9fd6f40d3](https://user-images.githubusercontent.com/82316884/114302310-31d7ca00-9ad1-11eb-92a9-343c10413d74.jpg)
IM WAITING ALL DAY BUT ITS NOT WORKING

**Variant**
Non-Root/Root

**Vanced version**
16.02.35 - Build - 01.47.00

**Android version**
Android 9.0 - Pie

**Device**
Oppo A5 2020

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
3. ....

**Expected behavior**
Replace me with a description of what you expected should happen and what happened instead.

_Attach images/videos if possible. These can be helpful in solving the issue._

**Comment by gghhkm** [comment]
Go to
#396 

Or

1. Use this Discord invitation.
https://discord.gg/rgwbXEaUCb
 2. Use this link.
https://discord.com/channels/328493314485518336/358967876193091584/809525073903616022
