### ISSUE TITLE
[Idea] Add resizable background player

### ISSUE THREAD

**Issue by Sandryar** [YTVanced/Vanced#635]
**Description**
Add background player that were resizable like were implemented in mx player/vlc player

https://user-images.githubusercontent.com/71545454/114361098-fb1cb500-9b9f-11eb-9c7a-8d2a3deb9c3d.mp4

**Comment by AinzTheSupremeOne** [comment]
Resizable PIP in MX Player/VLC is not actual PIP.  It just uses a overlay to display popup player. (Popup overlays are soon gonna be kill by Google) And I remember Kevin said it's not worth implementing something like it in Vanced.
The actual resizable PIP is not natively supported by Android 10 and under. You need to update to Android 11 to use it.
