### ISSUE TITLE
[Bug] whole screen not viewable

### ISSUE THREAD

**Issue by micheal133** [YTVanced/Vanced#637]
**Bug description**
After hitting the account button in the upper right hand corner of the screen, it does take you to the correct page but does not allow the page to scroll down and see the "settings"  option. Only the top tip of the "data"  icon can be seen. I have found no way to scroll the page down to have access to this part of the screen, even while using a mouse toggle for Fire TV.

**Variant**
Non-Root/ firestick

**Vanced version**
16.02.35 - Build - 01.47.00

**Android version**
Latest version for firestick

**Device**
Firestick

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2. Click on the account photo in the upper right hand corner.
3. Try and scroll down to settings.

![20210413_121609](https://user-images.githubusercontent.com/82428289/114492272-39bf7780-9c53-11eb-9070-6ea37437a4ca.jpg)

**Comment by AinzTheSupremeOne** [comment]
Huh? YouTube Vanced is only for mobile/tablets. There would never be a TV version so please don't report such issues, thank you very much.

**Comment by gghhkm** [comment]
Use this alternative.
https://github.com/yuliskov/SmartTubeNext
