### ISSUE TITLE
[Bug] cant log in google account

### ISSUE THREAD

**Issue by jericho990** [YTVanced/Vanced#639]
**Bug description**
After i sign in in youtube vanced theres no gmail account was sign in and lead me to click add account again
**Variant**
Non-Root/

**Vanced version**
16.02.35 - Build - 01.47.00

**Android version**
Android 8.0 - oreo

**Device**
Oppo a5s

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2. Click on icon of person
3. Add account 
4 click sign 
5after sign process it will lead you to add account again
**Expected behavior**
I expected to log in to my Gmail account because I click to sign in but after the process of sign in it lead me to add an account there's no account was signed in and lead me to back again and again to add account
![Screenshot_2021-04-13-13-12-49-34](https://user-images.githubusercontent.com/82432182/114500087-fc121d00-9c59-11eb-815f-f512e69abba4.jpg)

**Comment by AinzTheSupremeOne** [comment]
Read this. https://github.com/YTVanced/Vanced/issues/396
