### ISSUE TITLE
[Bug] Show/Hide Cast Button

### ISSUE THREAD

**Issue by lD0Ll** [YTVanced/Vanced#64]
_Can't duplicate the edited info. Another user can't hide the cast button with the setting in Layout Settings_

My issue: Cast button is not shown.
Cast Button option in Layout Setting doesn't work.

![Screenshot_2020-10-04-02-21-32-639_com vanced android youtube](https://user-images.githubusercontent.com/38228311/95003494-63cf1780-05e8-11eb-9373-6dd637bcdb0e.jpg)

[logcat.txt](https://github.com/YTVanced/Vanced/files/5322326/logcat.txt)

**Comment by Warcrors** [comment]
Mine can't hide the cast button
