### ISSUE TITLE
[Bug] On chromecast Vanced is hard to operate with chromecast remote

### ISSUE THREAD

**Issue by p10tr3k** [YTVanced/Vanced#641]
**Bug description**
I have just installed Vanced on Chromecast v4. I don't now what button is actually selected. Also moving between buttons seems unordered. So in current state this app is not working well with chromecast remote

**Variant**
Non-Root

**Vanced version**
Latest

**Android version**
Lates on chromecast

**Device**
Chromecast v4

**Comment by adWroc** [comment]
This is not a bug, the application is not designed for the Google TV system.  I think you should try the Smart YouTube TV app

**Comment by gghhkm** [comment]
https://github.com/yuliskov/SmartTubeNext
