### ISSUE TITLE
[Bug] Help and feedback option not working

### ISSUE THREAD

**Issue by GKid94** [YTVanced/Vanced#643]
**Bug description**
The help and feedback option is not working

**Variant**
Non-Root

**Vanced version**
16.02.35

**Android version**
Android 6.0.1

**Device**
Samsung Galaxy A5 2015

**Comment by gghhkm** [comment]
help and feedback was disabled to prevent people from sending Vanced issues to Google, use stock YouTube or Root Vanced.

**Comment by GKid94** [comment]
Ok thx
