### ISSUE TITLE
[Bug] loading loop 

### ISSUE THREAD

**Issue by Assassino14** [YTVanced/Vanced#644]
**Bug description**
When you launch the app, the app loads but it doesn't come to the home page to select videos. In the settings When you launch the app, the app loads but it doesn't come to the home page to select videos. 
**Variant**
Non-Root

**Vanced version**
16.02.35 - Build - 01.47.00

**Android version**
Android 9.0 - Pie

**Device**
Xiaomi mi 9t pro 

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
3. ....

**Expected behavior**
Replace me with a description of what you expected should happen and what happened instead.

_Attach images/videos if possible. These can be helpful in solving the issue._

**Comment by Assassino14** [comment]
See video

**Comment by gghhkm** [comment]
Go to
#396 

Or

1. Use this Discord invitation.
https://discord.gg/rgwbXEaUCb
 2. Use this link.
https://discord.com/channels/328493314485518336/358967876193091584/809525073903616022
