### ISSUE TITLE
[Bug] Youtube Vanced Offline on INFINIX mobile phones

### ISSUE THREAD

**Issue by Jade21st** [YTVanced/Vanced#645]
**Bug description**
as title says Youtube vanced is offline after signing in my account I noticed when clicking profile icon 
there should be displaying my existing google account but none to be found instead it's showing add account
It's working again after signing out.

**Variant**
Non-Root

**Vanced version**
16.02.35 - Build - 01.47.00
and
15.43.32

**Android version**
Android 10 - Android Q

**Device**
Infinix Note 8 (X692)

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
3. ....

**Expected behavior**
I expect to browse videos on youtube or subscription videos on home tab

_Attach images/videos if possible. These can be helpful in solving the issue._

https://user-images.githubusercontent.com/50163007/114797208-3fd56580-9dc5-11eb-9138-75abde66de96.mp4

**Comment by gghhkm** [comment]
#396

**Comment by Vishnu-88** [comment]
All infinx devices have this issue. I think its a bug with XOS. My Infinix Note 11S also have this problem.

**Comment by Xeunyx-Cypher** [comment]
One of my friend got Hot 11 and had this exact issue. Luckily I figured it out. The culprit is a bloatware called Phone Master. Go to Phone Master and then you have to enable auto-start management for Vanced microG there. Then it should work as usual.
Hope this help.

**Comment by Jade21st** [comment]
> @Jade21st
> One of my friend got Hot 11 and had this exact issue. Luckily I figured it out. The culprit is a bloatware called Phone Master. Go to Phone Master and then you have to enable auto-start permission for Vanced microG there. Then it should work as usual.
> Hope this help.

Okay i try that later on

**Comment by ayieko168** [comment]
> @Jade21st
> One of my friend got Hot 11 and had this exact issue. Luckily I figured it out. The culprit is a bloatware called Phone Master. Go to Phone Master and then you have to enable auto-start permission for Vanced microG there. Then it should work as usual.
> Hope this help.

Tried this on Infinix note 8 but still doesn't work. The app works for a while but immediately after exiting the app I still get the same issue once I relaunch the app.

Maybe send a detailed step by step instruction on how to fix this.

I even tried installing a different launcher (Poco Launcher) but I still get this issue.

**Comment by Jade21st** [comment]
> @Jade21st One of my friend got Hot 11 and had this exact issue. Luckily I figured it out. The culprit is a bloatware called Phone Master. Go to Phone Master and then you have to enable auto-start permission for Vanced microG there. Then it should work as usual. Hope this help.

your method finally works i can now get notification and browse videos without reentering the user account.

**Comment by Xeunyx-Cypher** [comment]
> > @Jade21st
> > One of my friend got Hot 11 and had this exact issue. Luckily I figured it out. The culprit is a bloatware called Phone Master. Go to Phone Master and then you have to enable auto-start permission for Vanced microG there. Then it should work as usual.
> > Hope this help.
> 
> Tried this on Infinix note 8 but still doesn't work. The app works for a while but immediately after exiting the app I still get the same issue once I relaunch the app.
> 
> Maybe send a detailed step by step instruction on how to fix this.
> 
> I even tried installing a different launcher (Poco Launcher) but I still get this issue.

1. Go to "Phone Master"
2. There you should be able to find an option called "Auto-start" or something similar. Open that option.
3. Then turn on the permission for Vanced microG there.
4. Now clear data from YouTube Vanced and Vanced microG both.
5. Login again and it should work as usual

**Comment by ayieko168** [comment]
> > 
> > Tried this on Infinix note 8 but still doesn't work. The app works for a while but immediately after exiting the app I still get the same issue once I relaunch the app.
> > 
> > Maybe send a detailed step by step instruction on how to fix this.
> > 
> > I even tried installing a different launcher (Poco Launcher) but I still get this issue.
> 
> 1. Go to "Phone Master"
> 2. There you should be able to find an option called "Auto-start" or something similar. Open that option.
> 3. Then turn on the permission for Vanced microG there.
> 4. Now clear data from YouTube Vanced and Vanced microG both.
> 5. Login again and it should work as usual 

This worked very well for my Infinix phone. Cheers mate👍
