### ISSUE TITLE
[Bug] Cast button

### ISSUE THREAD

**Issue by adWroc** [YTVanced/Vanced#648]
**Bug description**
The cast button is unavailable on the home page and during playback. To send a video to a Chromecast, I have to go to the settings and select the option: watch on TV. Everything works fine in the original YT app

**Variant**
Non-Root:Yes

**Vanced version**
16.02.35 - Build - 01.49.00

**Android version**
Android 10 - OOS 10.3.8.GM21AA

**Device**
Oneplus 7 pro

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2. Icon is missing at the top
3. When opening any video the icon is missing aswell

**Expected behavior**
The Icon should be visible.

**Comment by KevinX8** [comment]
try the hotfix of  16.14.34
