### ISSUE TITLE
[Bug] Screen keeps loading...

### ISSUE THREAD

**Issue by paokaras** [YTVanced/Vanced#649]
**Bug description**
The screen keeps loading and i can't press anything

**Variant**
Non-Root/Root

**Vanced version**
16.02.35 - Build - 01.47.00

**Android version**
Android 9.0 - Pie

**Device**
Samsung Galaxy S21 ultra

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app

**Expected behavior**
See the page

https://user-images.githubusercontent.com/82683287/115090044-77a2f100-9f1c-11eb-8425-ada048169e1e.mp4

_Attach images/videos if possible. These can be helpful in solving the issue._

**Comment by AinzTheSupremeOne** [comment]
Aw jesus christ, why on earth people are ignoring warnings in the manager outright. Read this https://github.com/YTVanced/Vanced/issues/396
