### ISSUE TITLE
[Bug] Install

### ISSUE THREAD

**Issue by Rwf00** [YTVanced/Vanced#650]
**Bug description**
It does not allow me to install any application on the Xiaomi Poco f2 Pro / MIUI 12.2.5

**Variant**
Non-Root

**Vanced version**
16.02.35 - Build - 01.47.00

**Android version**
Android 11

**Device**
Xiaomi Poco f2 pro

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2. Click on 'Install vanced micro g'
3. Intalling.
4. Error, the user block the instalation.
5. Click on 'Advanced'.
6. Msj: 'INSTALL_FAILED_INTERNAL_ERROR: Permission Deneid.

**Expected behavior**
I wanted you to install the app
`

`

_Attach images/videos if possible. These can be helpful in solving the issue._

https://user-images.githubusercontent.com/82687222/115097617-45cc6300-9ef9-11eb-91d2-2af81d99f29b.mp4

**Comment by AinzTheSupremeOne** [comment]
Not a bug in manager but in MIUI. Can you atleast read the warning? 
![IMG_20210417_091409](https://user-images.githubusercontent.com/50095635/115100869-4dbdee80-9f5d-11eb-9132-fcd6a0b95887.jpg)

Solution: just disable MIUI optimization from system settings.
