### ISSUE TITLE
[Idea] vanced

### ISSUE THREAD

**Issue by GaganMorinda** [YTVanced/Vanced#651]
**Description**
Hello dear sir/madam
Please tell us when youtube vanced is releasing for iOS devices. 
Bearing iOS user we also want official YouTube vanced.
Is it possible to have youtube vanced for iOS.
Please make it for iOS devices also.
Thank you for your support.

_Attach images/videos if possible. Also add any links to possible other applications with the said feature already implemented._

**Comment by AinzTheSupremeOne** [comment]
Soon..... But there is no due date of its release yet. You could visit the Discord server (discord.gg/vanced). They might have some intel on it.

**Comment by gghhkm** [comment]
Never lol, the staff are trolls and like to spread misinformation.
Even if Vanced did come to iOS you'd need to jailbreak to use it, and other YouTube mods already exist at that point, like Cercube for example.

**Comment by AinzTheSupremeOne** [comment]
@gghhkm so Chloe being iOS dev was all a lie?

**Comment by AinzTheSupremeOne** [comment]
Bruh

**Comment by gghhkm** [comment]
> @gghhkm so Chloe being iOS dev was all a lie?

Chloee Hemsworth hasn't even been online in the Discord sense Jan 14.
And Xinto said himself that's it's not going to happen, and Kevin has only mentioned it seemingly as a joke.
XFile (the spearhead of everything) hasn't said anything on the matter to my knowledge.

**Comment by AinzTheSupremeOne** [comment]
Guess Chloe was an alt of Hazel.....

**Comment by gghhkm** [comment]
> Guess Chloe was an alt of Hazel.....

LMAO, most likely.

**Comment by gghhkm** [comment]
About what I expected.
![Screenshot_20210417-040718](https://user-images.githubusercontent.com/72711094/115106376-7bda0900-9f32-11eb-8d64-d36c81fef050.jpg)
