### ISSUE TITLE
[Bug] Can't see multiple account list

### ISSUE THREAD

**Issue by AkashRahane** [YTVanced/Vanced#656]
**Bug description**
When I add new account to vanced YouTube it doesn't show the list and can't switch to any other account.

**Variant**
Non-Root

**Vanced version**
16.02.35 - Build - 01.47.00

**Android version**
Android 10

**Device**
OnePlus 7

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2. Tap on user icon on top right corner
3. click on switch account and add the new account details
4. You won't be able to switch and see the added account.
5.  In official YouTube app I can see all the added accounts.

**Expected behavior**
I should see list of account I have added and able to switch whenever required.
![Screenshot_20210418-133121](https://user-images.githubusercontent.com/82751683/115138772-c00cfc80-a04b-11eb-9520-680a70dbfb09.jpg)

**Comment by gghhkm** [comment]
#396
