### ISSUE TITLE
[Bug] account

### ISSUE THREAD

**Issue by arfest23** [YTVanced/Vanced#657]
**Bug description**
Hi, 
I cant log in the app

**Variant**
Non-Root/Root

**Vanced version**
16.02.35 - Build - 01.47.00

**Android version**
Android 9.0 - Pie

**Device**
Samsung Galaxy S8

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
3. ....

**Expected behavior**
Replace me with a description of what you expected should happen and what happened instead.

_Attach images/videos if possible. These can be helpful in solving the issue._

**Comment by MatadorProBr** [comment]
Duplication of issue: https://github.com/YTVanced/Vanced/issues/396 and close this issue

**Comment by KevinX8** [comment]
fixed in 16.14.34
