### ISSUE TITLE
[Bug] UI displays connection issue when app cannot login

### ISSUE THREAD

**Issue by alexander94dmitriev** [YTVanced/Vanced#659]
**Bug description**
Changed password to Google account and it seems that the app does not log you off but instead shows you are logged in, but there's no Internet Connection.

**Variant**
Non-Root
**Vanced version**
16.02.35

**Android version**
Android 11.0

**Device**
Pixel 3a

**Steps to Reproduce**
Steps to reproduce the error:
1. Change the password on Google Account
2. Open YTVanced app

**Expected behavior**
The app should display a proper error ( e.g. unable to login to account).

**Comment by MatadorProBr** [comment]
See https://github.com/YTVanced/Vanced/issues/396

**Comment by ControlAltAndDelete** [comment]
Open MicroG settings and remove the account, and then log back in. That fixed it for me.
