### ISSUE TITLE
Support us feature

### ISSUE THREAD

**Issue by KMohZaid** [YTVanced/Vanced#660]
Add a button in manager app.By clicking on that button we can see ads and support you.I mean if any person need to help developer by seeing ads so they see and help you.I got this in my brain by telegram modified app name "Bgram".

**Comment by KevinX8** [comment]
We don't accept donations and we definitely will never add ads to vanced, if you want to  support us get brave from https://vancedapp.com/brave or purchase adguard premium from https://vancedapp.com/adguard
