### ISSUE TITLE
[Bug] Unable to Add Account

### ISSUE THREAD

**Issue by chievellavore** [YTVanced/Vanced#661]
**Bug description**
I've successfully downloaded the latest MicroG (v.: 0.2.18.210390). Every time I try to add an account, it simply doesn't work. This also happens to my other phones. I've been trying to clear the cache for both YouTube Vanced and MicroG. I also tried uninstalling them both. But nothing happens. 

**Variant**
Non-Root

**Vanced version**
16.02.35 - Build - 01.47.00

**Android version**
Android 10.0

**Device**
Tecno Pouvoir 4 Pro

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2. Click on profile picture at the upper right. 
3. Add Account
4. Sign in
5. Input your email and password

**Expected behavior**
There shouldn't be any changes. The account you input won't work and will still be the same as that of the original. 

_Attach images/videos if possible. These can be helpful in solving the issue._
   
![Screenshot_20210420-194034.png](https://user-images.githubusercontent.com/80460487/115392181-d87b4380-a212-11eb-8f5e-5e7131db0ed7.png)

![Screenshot_20210420-194047_1.png](https://user-images.githubusercontent.com/80460487/115392205-e204ab80-a212-11eb-9c8e-816de296b7d2.png)

![Screenshot_20210420-194135.png](https://user-images.githubusercontent.com/80460487/115392230-e92bb980-a212-11eb-9cbb-7c8029f78944.png)

![Screenshot_20210420-194208.png](https://user-images.githubusercontent.com/80460487/115392265-f2b52180-a212-11eb-8230-2f9186cbbcb6.png)

![Screenshot_20210420-195014.png](https://user-images.githubusercontent.com/80460487/115392300-fea0e380-a212-11eb-90b4-4cfb0b8ef405.png)

![Screenshot_20210420-195123.png](https://user-images.githubusercontent.com/80460487/115392319-03659780-a213-11eb-9c04-589552500bdd.png)

**Comment by MatadorProBr** [comment]
See https://github.com/YTVanced/Vanced/issues/396

**Comment by ControlAltAndDelete** [comment]
You'll have to uninstall MicroG and Vanced and then install them again to get rid of the account.
