### ISSUE TITLE
[Bug] When I update yo android 11 cannot instal ytbe vanced

### ISSUE THREAD

**Issue by danilopezr** [YTVanced/Vanced#662]
**Bug description**
I hace just updated my Smartphone Samsung a50 yo android 11, anda just after that the ayputube Vanced App dissapeared so, througth the manager O tries yo instal microG anda ytbe Vanced, microG installed , but with ytbe Vanced , It appears an error that sais: INSTALL_FAILLED_UPDATE_INCOMPATIBLE
Package con.vanced.android.youtube signaturas o nota match previously installed version;ignoring!
**Variant**
Non-Root

**Vanced version**
16.02.35 - Build - 01.47.00

**Android version**
Android 11

**Device**
Samsung Galaxy A50
![Screenshot_20210420-154300_Vanced Manager](https://user-images.githubusercontent.com/82887991/115408109-e4560e00-a1f0-11eb-85b0-d26b2e6f864e.jpg)

**Comment by gghhkm** [comment]
https://github.com/gghhkm/Vanced-Issue-Center/blob/main/Guides/BrokenVancedPackage.md
