### ISSUE TITLE
[Bug] YouTube Vanced keeps crashing

### ISSUE THREAD

**Issue by GKid94** [YTVanced/Vanced#663]
**Bug description**
YouTube Vanced keeps crashing on background play

**Variant**
Non-Root

**Vanced version**
16.02.35

**Android version**
Android 6.0.1

**Device**
Samsung Galaxy A5 2015

**Comment by KevinX8** [comment]
logcat please?

**Comment by GKid94** [comment]
Logcat?

**Comment by KevinX8** [comment]
https://youtu.be/W6iDw76UpQw

**Comment by KevinX8** [comment]
Also it's 16.02, this version is no longer supported, update

**Comment by GKid94** [comment]
> https://youtu.be/W6iDw76UpQw

My phone is not rooted

**Comment by GKid94** [comment]
> Also it's 16.02, this version is no longer supported, update

I know I updated the app already
