### ISSUE TITLE
[Bug] Google Play Keeps Trying to Update The Root Version

### ISSUE THREAD

**Issue by ControlAltAndDelete** [YTVanced/Vanced#668]
**Bug description**
In the google play store it tells you to update YouTube but sometimes it updates the app by itself effectively destroying vanced.

**Variant**
Root

**Vanced version**
16.02.35 - Build - 01.47.00

**Android version**
Android 7.1.2 - Nougat

**Device**
Amazon Fire HD 8 2017

**Steps to Reproduce**
Steps to reproduce the error:
1. Check the Play Store Updates and it appears /or 1. Not do anything and it auto updates.

**Expected behavior**
For it to not pop up as an update, I don't want to keep uninstalling and installing vanced

**Comment by gghhkm** [comment]
https://github.com/YTVanced/VancedManager/issues/501
