### ISSUE TITLE
[Bug] MIUI 12.0.3 

### ISSUE THREAD

**Issue by MikeKOD** [YTVanced/Vanced#669]
**Bug description**
The omiui optimization Will not disable

**Variant**
Non-Root

**Vanced version**
16.02.35 - Build - 01.47.00

**Android version**
Android 10

**Device**
Xiaomi Redmi Note 8t

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2. The popup of the miui appears to be disabled in the settings
3. Disable It
4. Restate the device
5. Open yt vanced
6. the popup of the miui appears to be disabled in the settings

**Expected behavior**
optimization should remain disabled, but it resets at each reboot

![Screenshot_2021-04-23-08-13-44-864_com android settings](https://user-images.githubusercontent.com/52321149/115829314-23fa4100-a40f-11eb-8c8b-9cfa2d3cd7b4.jpg)
![Screenshot_2021-04-23-08-37-37-778_com android chrome](https://user-images.githubusercontent.com/52321149/115829353-2fe60300-a40f-11eb-8ae1-2d4b5c3f18b5.jpg)

**Comment by gghhkm** [comment]
Not an issue with Vanced but MIUI itself.
MIUI optimization only needs to be disabled during installation.
Also disable battery optimization for MicroG.

**Comment by MikeKOD** [comment]
Ok, but on MIUI 12.0.5, battery optimization can only be disabled for a single app not for the entire ecosystem, so I have to install the app first, disable optimization and disable notifications

**Comment by gghhkm** [comment]
You only have to disable battery optimization for MicroG...

**Comment by MikeKOD** [comment]
Ok!
