### ISSUE TITLE
Can't hide cast button 

### ISSUE THREAD

**Issue by Warcrors** [YTVanced/Vanced#67]
Can't hide the cast button even its off on the settings and did a forced stop.
Nothing works ![Screenshot_20201005_005737_com.vanced.android.youtube.jpg](https://user-images.githubusercontent.com/67160464/95021796-14104080-0628-11eb-9b96-398ca6393e88.jpg)![Screenshot_20201005_005747_com.vanced.android.youtube.jpg](https://user-images.githubusercontent.com/67160464/95021799-17a3c780-0628-11eb-9f13-f044d580602e.jpg)

**Comment by milindgoel15** [comment]
Please update to the latest v16.16.38 if you haven't already. We are closing this issue. Feel free to reopen if you still face any issue.
