### ISSUE TITLE
[Bug] MicroG/YTvanced "there was a problem communicating with Google Servers"

### ISSUE THREAD

**Issue by Nexzar** [YTVanced/Vanced#670]
**Bug description**
I changed my Google password a while ago, after that the YTVanced app stopped working, while I still was logged into the G Acc. 

I logged out and tried to log back in again, then the issue mentioned in the title appeared. I deleted cache and storage and tried again, to no sucess. 

Then i deleted the YTvanced app and reinstalled it over the manager, no success. 

After that, i deleted everything related to the Vanced project (manager etc) and re downloaded and -installed it. No success. Is that a common problem when changing passwords for the G account?

**Variant**
Non-Root

**Vanced version**
16.02.35 - Build - 01.49.00

**Android version**
Android 11

**Device**
OnePlus 8T/KB2000 (Hydrogen OS). 

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2. Click on account icon
3. try to login
4. "sorry cant connect to google servers"

**Expected behavior**
Obvious. 

_Attach images/videos if possible. These can be helpful in solving the issue._
![Screenshot_20210423-122138](https://user-images.githubusercontent.com/83068373/115858359-22407580-a42f-11eb-8e9d-9c4883bf575e.jpg)

**Comment by gghhkm** [comment]
#396
