### ISSUE TITLE
[Idea] Discord rich presence for videos

### ISSUE THREAD

**Issue by Finn1510** [YTVanced/Vanced#671]
**Description**
Discord rich presence for youtube vanced. 
I really like the discord rich presence with Spotify but I mainly use YT + YT music maybe this is something you guys could add ;)
Discord rich presence Docs describe it like this: 
So, what is it?
Rich Presence allows you to leverage the totally overhauled "Now Playing" section in a Discord user's profile to help people play your game together. Rich game data—including duration, score, current boss or map, and so much more—lives inside Discord. You can spectate a friend's game directly from their profile popout, or party up via beautiful chat embeds with real-time information about open party slots and the party's in-game status. No more exchanging usernames and friend codes, or wondering if there's room for you to join. Rich Presence is a living invitation to play together, or to watch your friends kick butt.

_Attach images/videos if possible. Also add any links to possible other applications with the said feature already implemented._
[here](https://github.com/Vatuu/discord-rpc) is a discord rich presence java wrapper

**Comment by KevinX8** [comment]
it's not possible to do it on mobile currently as the SDK only works on pc, wait for them to add support. Spotify has a paid deal with discord to make it work and they don't use the SDK directly.

**Comment by Finn1510** [comment]
thats sad I hope they will add support for that in the future ^^
