### ISSUE TITLE
Help here is a bug

### ISSUE THREAD

**Issue by shimx12** [YTVanced/Vanced#672]
![Screenshot_20210423-211453_Vanced Manager](https://user-images.githubusercontent.com/83073100/115869982-97389d00-a479-11eb-9ad5-eaa2634c723a.jpg)
![Screenshot_20210423-211455_Vanced Manager](https://user-images.githubusercontent.com/83073100/115869996-9b64ba80-a479-11eb-84e4-7e64f52e4a59.jpg)

Can you answer with korean...?

**Comment by gghhkm** [comment]
Good luck

https://github.com/gghhkm/Vanced-Issue-Center/blob/main/Guides/BrokenVancedPackage.md
