### ISSUE TITLE
[Bug] Can't Refresh Recommended Page

### ISSUE THREAD

**Issue by AliZaib654** [YTVanced/Vanced#673]
**Bug description**
After recently updating YouTube Vance's through the Vance's manager it seems as though I am unable to refresh the recommended page by swiping down. Where before the update I was able to do this. I can refresh the page on trending and subscriptions but doesn't work for the recommended page.

**Variant**
Non-Root

**Vanced version**
16.02.35 - Build - 01.47.00

**Android version**
Android 11

**Device**
Samsung Galaxy S10

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2. Click on 'recommended page'
3. swipe down and no refresh occurs
4. Unable to refresh the page any other way

**Expected behavior**
Should refresh the page 

_Attach images/videos if possible. These can be helpful in solving the issue._

**Comment by gghhkm** [comment]
This is a known issue and is already fixed in the Beta to my knowledge.
If you'd like to test it go to https://discord.gg/vanced and go through the steps to first gain access to the hidden channels and then apply for Beta tester.
