### ISSUE TITLE
[Bug] remove the try youtube premium for free screen

### ISSUE THREAD

**Issue by ccgauche** [YTVanced/Vanced#674]
**Bug description**
A screen pops up randomly asking for buying youtube premium. We can skip it but it is inconvenient.

**Variant**
Non-Root/Root

**Vanced version**
16.02.35 - Build - 01.47.00

**Android version**
Android 9.0 - Pie

**Device**
Samsung Galaxy S8

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2. A pop-up will randomly appears time to time

**Expected behavior**
Nothing should show up.

**Comment by noobfletcher1** [comment]
can recreate on Samsung Tab A

**Comment by leodoi3** [comment]
same
