### ISSUE TITLE
[Bug] Slowly and unusual YT Channel account switch

### ISSUE THREAD

**Issue by oti4500** [YTVanced/Vanced#676]
**Bug description**
If I want to switch my YT accounts/channels, write the "Only one concurrent post-auth sign-in allowed.", and later will switch to another my yt account/channel.

**Variant**
Non-Root

**Vanced version**
15.43.32 - Build - 01.47.00

**Android version**
Android 11.0

**Device**
Samsung Galaxy S10

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2. Click on 'account icon'
3. Click to the currently channel/account name
4. Click to the channel/account, what do you want to switch.
5. Write "Only one concurrent post-auth sign-in allowed."
6. Go to home and/or maybe the app restart is required.
7. Open the app
8. and finally switched to another channel/account

**Expected behavior**
Replace me with a description of what you expected should happen and what happened instead.

Video:
https://streamable.com/1fov2e

![Screenshot_20210425-115903](https://user-images.githubusercontent.com/58808646/115989577-577bcd80-a5bf-11eb-9a5f-3f0b49cde612.jpg)
![Screenshot_20210424-164425](https://user-images.githubusercontent.com/58808646/115989578-58acfa80-a5bf-11eb-9758-0455f7ea3768.jpg)
![Screenshot_20210425-120430](https://user-images.githubusercontent.com/58808646/115989588-61053580-a5bf-11eb-8c82-fadc44342159.jpg)

**Comment by KevinX8** [comment]
fixed in 16.14.34
