### ISSUE TITLE
(Bug) Android 11

### ISSUE THREAD

**Issue by ayushhasani2004** [YTVanced/Vanced#677]
After i updated my device to android 11 (miui 12.0.1) 
Device: mi 10i
Whenever i am trying to open any link from video description it shows "youTube cant open this link"
Please solve this issue as it irritates a lot

**Comment by KevinX8** [comment]
I don't see how this is Vanced related? You literally say it's caused by MIUI

**Comment by ayushhasani2004** [comment]
But you can fix it by update as maybe the vanced is not supporting in latest version of miui 😅
