### ISSUE TITLE
[Bug] Community tab is broken, fails to load posts.

### ISSUE THREAD

**Issue by jbciardi** [YTVanced/Vanced#678]
For several versions of the app so far, the community tab has been broken in my app. I have no idea why and I don't think any one else is having the issue. 

**Variant**: Non-Root

**Vanced version** 16.14.34 - Build - 01.50.01

**Android version**: Android 10.0 - Q

**Device**: Oneplus 7t Pro Mclaren 5g model 1925

**Steps to Reproduce Steps to reproduce the error**:
1. Open the app
2. Open any channel.
3. Go to the community tab

**Expected behavior**: The community tab loads posts made by the channel. 
**Actual Behaviour**: Community tab simply does not load. Community posts are also not visible in the home tab as they were in previous versions. 

**Video Showing bug**: https://youtu.be/eoRsAJj7Ix0

**Comment by KevinX8** [comment]
the steps you listed to reproduce do not work for me, community tab always shows correctly, can you provide more detail on how it can possibly be reproduced? Ie settings you enabled etc.

**Comment by KevinX8** [comment]
You enabled community post removal in vanced settings, please disable it if you wanna use the community feature

**Comment by paulscholes0258** [comment]
I also have this problem. 
did anyone can fixed this ???  thanks
![image](https://user-images.githubusercontent.com/47942120/146637269-33f350ab-482a-4218-89ab-5b061b792a37.png)
![image](https://user-images.githubusercontent.com/47942120/146637290-9e656445-4431-4d86-970e-6312efbd8fac.png)
