### ISSUE TITLE
[Idea] Replace download button with...

### ISSUE THREAD

**Issue by FrozenPhoton** [YTVanced/Vanced#679]
We all know the dev is against adding download support for fear of repercussions, but that download button is currently just going to waste.

What if instead of opening the download pop-up when pressed, it opened "https://www.y2mate.com/youtube/[video_id]" in your web browser?

This would be a bit of a middle ground compromise, condensing the steps to download a video outside of the app into one action, while avoiding having any download ability within Vanced itself.

This is my core suggestion, and everything after this should be considered simply daydreaming outloud.

 󠀡󠀡 
 󠀡󠀡 
 󠀡󠀡 
 󠀡󠀡 
If the devs was to be particularly generous, an extension of this would be to also replace the in-app downloads section with a file viewer users could target to a specific folder in which they keep their downloaded videos.

Tapping on the thumbnail could then open the video in VLC or possibly play within the Vanced player.

A further step could be adding a built in browser which can open y2mate and direct the downloads to a specific folder.

The obvious concern with these latter two comsepts is it may be dancing too close to the line of in-app downloads, as well as being much more work to implement compared to the much simpler core idea.  Even so I figured it was worth mentioning.

**Comment by gghhkm** [comment]
The Devs said no.

"We're never gonna endorse one particular download site."
ect.

**Comment by FrozenPhoton** [comment]
> The Devs said no.
> 
> "We're never gonna endorse one particular download site."
> ect.

Does that mean if the site used was user selectable it may be okay?

**Comment by KevinX8** [comment]
vanced has a share menu which you can give the link to another app or site to start the download, not sure why you need more than this

**Comment by gghhkm** [comment]
> vanced has a share menu which you can give the link to another app or site to start the download, not sure why you need more than this

Yeah I suggest you use something like Newpipe and just share to it.

**Comment by FrozenPhoton** [comment]
> vanced has a share menu which you can give the link to another app or site to start the download, not sure why you need more than this

You still have to copy the link, open your browser and go to a download site, and paste the link but remove everything that isn't the video tag.  This is simply just a way of making a useless button have a bit more function, it would act as a one tap shortcut.

**Comment by gghhkm** [comment]
> > vanced has a share menu which you can give the link to another app or site to start the download, not sure why you need more than this
> 
> You still have to copy the link, open your browser and go to a download site, and paste the link but remove everything that isn't the video tag. This is simply just a way of making a useless button have a bit more function, it would act as a one tap shortcut.

Click the share button under the video. 🤨

**Comment by FrozenPhoton** [comment]
> > vanced has a share menu which you can give the link to another app or site to start the download, not sure why you need more than this
> 
> Yeah.
> 
> @FrozenPhoton I suggest you use something like Newpipe and just share to it.

I suppose you could use a third party app like that yeah, idk I'm just trying to think of a way that doesn't require a separate app and something to make the download button not useless, you know?

**Comment by gghhkm** [comment]
> > > vanced has a share menu which you can give the link to another app or site to start the download, not sure why you need more than this
> > 
> > 
> > Yeah.
> > @FrozenPhoton I suggest you use something like Newpipe and just share to it.
> 
> I suppose you could use a third party app like that yeah, idk I'm just trying to think of a way that doesn't require a separate app and something to make the download button not useless, you know?

The download button isn't useless... If you have premium.

**Comment by FrozenPhoton** [comment]
> > > > vanced has a share menu which you can give the link to another app or site to start the download, not sure why you need more than this
> > > 
> > > 
> > > Yeah.
> > > @FrozenPhoton I suggest you use something like Newpipe and just share to it.
> > 
> > 
> > I suppose you could use a third party app like that yeah, idk I'm just trying to think of a way that doesn't require a separate app and something to make the download button not useless, you know?
> 
> The download button isn't useless... If you have premium.

Well you have to admit most of us don't, that's largely why Vanced exsists.  It would be nice to have the option for the majority that doesn't
