### ISSUE TITLE
[Bug] Preferred Resolution Broken

### ISSUE THREAD

**Issue by shreyask21** [YTVanced/Vanced#680]
**Bug description**
The preferred resolution for cellular data and WiFi both are broken (maybe due to changes in stock youtube resolution handlers).  

It defaults to highest possible quality (2160p, 1080p etc) instead of the set preferred resolution. I have tried clearing youtube vanced app data, changing the "video quality preference" to data saver, auto and high quality, no luck.  

**Variant**
Non-Root  

**Vanced version**
16.14.34 - Build - 01.50.01  

**Android version**
Android 11  

**Device**
Pocophone F1  

**Steps to Reproduce**
1. Open Settings > Vanced Settings > Video Settings 
2. Set both WiFi and Cellular preferred resolutions to any resolution 'X' (say 240p, 480p etc) other than the maximum possible resolution
3. Play any video  

**Expected behavior**
After playing the video, the resolution should lock to the set preferred one.  

**Screenshots**  

![Screenshot_20210426-034658.png](https://user-images.githubusercontent.com/30172640/116011431-a159c780-a642-11eb-9a43-9300150a9685.png)

![Screenshot_20210426-031915_1.png](https://user-images.githubusercontent.com/30172640/116011375-4fb13d00-a642-11eb-8741-8d905302c48b.png)

**Comment by Zefferis** [comment]
Experiencing the same issue

**Comment by Cyber-Raj** [comment]
yep, having the same issue on android 10

**Comment by gghhkm** [comment]
This was a known issue well before it even released.
You can thank Google for breaking it.
