### ISSUE TITLE
Closing of app again and again on switch on![Bug] 

### ISSUE THREAD

**Issue by abhigyan27** [YTVanced/Vanced#683]
**Bug description**
App is closing again and again

**Variant**
Non-Root/Root

**Vanced version**
16.14.35 

**Android version**
Android 10.0 - Pie

**Device**
Redmi 9 pro max

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
3. ....

**Expected behavior**
Replace me with a description of what you expected should happen and what happened instead.

_Attach images/videos if possible. These can be helpful in solving the issue._

**Comment by KevinX8** [comment]
more detail required, logcat etc.
