### ISSUE TITLE
[Bug] Sponsorblock segments carrying over videos

### ISSUE THREAD

**Issue by TymanWasTaken** [YTVanced/Vanced#684]
**Bug description**
A segment from one video carried over to another video, with the exact same timing, and when voted to, voted to the actual segment on the actual video

**Variant**
Root

**Vanced version**
16.14.35 - Build - 01.50.01

**Android version**
Android 11

**Device**
Google pixel 4 XL

**Steps to Reproduce**
https://github.com/YTVanced/Vanced/issues/684#issuecomment-827098131

**Expected behavior**
The segment should not show or work

No images, but it acted exactly like it should except for the fact that it was showing on the wrong video

**Comment by caneleex** [comment]
open a new issue in the [SponsorBlock repo](https://github.com/YTVanced/SponsorBlock) with the videos you got this behavior on

**Comment by gghhkm** [comment]
This should be in the [SponsorBlock repo](
https://github.com/YTVanced/SponsorBlock/issues)
Please move to there.

**Comment by TymanWasTaken** [comment]
I just figured out how to reproduce, and it is likely a vanced issue not a sponsorblock one.
1. Open a video with a segment
2. Exit out of the app to the home screen but do not close it
3. Click a notification for a youtube video
4. The segments do not update and carry over to the new video with the same exact timings

**Comment by gghhkm** [comment]
> I just figured out how to reproduce, and it is likely a vanced issue not a sponsorblock one.
> 
> 1. Open a video with a segment
> 2. Exit out of the app to the home screen but do not close it
> 3. Click a notification for a youtube video
> 4. The segments do not update and carry over to the new video with the same exact timings

I couldn't seem to reproduce it.
Tho I am using the root version.
Also please make sure you reinstall the update, a hot fix of the same version number got pushed.

**Comment by TymanWasTaken** [comment]
👍 I will test later once I get more notifications to test with

**Comment by TymanWasTaken** [comment]
Still happens after reinstalling

**Comment by KevinX8** [comment]
fixed in 16.16.38
