### ISSUE TITLE
[Bug] Video quality changing issue!

### ISSUE THREAD

**Issue by AZAR20** [YTVanced/Vanced#685]
**Bug description**
Video quality Automatically change to max quality even after changing the settings fix it.

**Variant**
Non-Root

**Vanced version**
16.14.34 - Build - 01.50.01

**Android version**
Android 10

**Device**
Realme 3 pro

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2. Click on any video
3. Video quality Automatically stuck at maximum quality .I need to change manually for every single video I play 😭. 

**Expected behavior**
Fix Video quality Automatically  in setting .

![Screenshot_2021-04-26-12-28-23-78_7a4090f09f6554852d748ee9fd6f40d3](https://user-images.githubusercontent.com/83203636/116042089-a4c57100-a68b-11eb-9708-f9192cbd6e47.jpg)
![Screenshot_2021-04-26-12-30-23-01_7a4090f09f6554852d748ee9fd6f40d3](https://user-images.githubusercontent.com/83203636/116042103-a8f18e80-a68b-11eb-8cce-9168b6ac9aa0.jpg)

https://user-images.githubusercontent.com/83203636/116043043-c7a45500-a68c-11eb-95cc-029452486e2b.mp4

**Comment by gghhkm** [comment]
Know issue well before the update even released.
Google broke it.
The only reason it was still included in this release is because not everyone has the new trash layout.

**Comment by AZAR20** [comment]
> Know issue well before the update even released.
> Google broke it.
> The only reason it was still included in this release is because not everyone has the new trash layout.

Any possibility can fix this problem?
