### ISSUE TITLE
[Bug] New update via Manager for YT Vanced does not contain the Dutch/Nederlands split apk

### ISSUE THREAD

**Issue by foreveryoungforty** [YTVanced/Vanced#686]
**Bug description**
I just received a push from Vanced Manager 2.5.1 to update to YouTube Vanced 16.14.34, but it lacks my default choice Nederlands (Dutch) as a choice, and therefore does not download that split nl.apk. In manager I see "[] " next to Languages in the installation preferences, and cannot choose Dutch/Nederlands - all other European languages are there , eg. Deutsch (German), Français,.... 
I just visited the Codebucket-mirror site, the nl-apk is also NOT present in the root/non-root directories there.
Can you please add Dutch ? Thank you very much.

FYI. I am your Dutch translator on the Crowdin-site and all my Dutch translations are 100% up-to-date for Vanced and Vanced Manager.

PS. I first posted this as a Vanced Manager issue, but X1nto replied "Its a suggestion for Vanced, not Manager" and closed.

**Variant**
Non-Root

**Vanced version**
16.14.34 - Build - 01.50.01

**Android version**
Android 11

**Device**
Samsung Galaxy S10 (also same issue for Samsung Tablet S6)

**Steps to Reproduce**
Steps to reproduce the error:
Choose language in Vanced Manager

**Expected behavior**
In all earlier releases there was choice for Dutch/Nederlands and the nl.apk was also downloaded and properly installed.

_Attach images/videos if possible. These can be helpful in solving the issue._

**Comment by KevinX8** [comment]
fixed in 16.16.38

**Comment by foreveryoungforty** [comment]
@KevinX8 Great - Thanks a lot !!
