### ISSUE TITLE
[Bug] crashing after account added

### ISSUE THREAD

**Issue by FrederikRichter** [YTVanced/Vanced#687]
[logcat.txt](https://github.com/YTVanced/Vanced/files/6378488/logcat.txt)

**Bug description**
After adding an account in the microg manager or in youtube vanced itself, the app crashes. App does not open after.

**Variant**
Non-Root

**Vanced version**
16.14.34 - Build - 01.50.01

**Android version**
Android 9.0 - Pie
kernel: 3.18.120
build: PKQ1. 190522.001

**Device**
LG-H870

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2. sign in
3. (crashes)

**Expected behavior**
Be signed in

_Attach images/videos if possible. These can be helpful in solving the issue._

**Comment by gghhkm** [comment]
Do a fresh installation of everything.

**Comment by FrederikRichter** [comment]
Still does not work. Uninstalled everything through vanced manager, uninstalled vanced manager and redownloaded everything.

**Comment by gghhkm** [comment]
Get help troubleshooting from the Discord. Https://Discord.gg/Vanced

**Comment by FrederikRichter** [comment]
Google account was bugged, using an other solved the issue. might be worth looking into though. the account used to be a youtube channel.
