### ISSUE TITLE
[Bug] replaceme

### ISSUE THREAD

**Issue by Vishal5292** [YTVanced/Vanced#689]
**Bug description**
After Installing the YouTube Vanced Version 16.14.34 The App is draining battery more than last Update and crashing after 5 to 10 minutes later after opening the app.

**Variant**
Non-Root

**Vanced version**
16.14.34 - Build 01.50.01

**Android version**
Android 10

**Device**
Realme 5

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
3. ....

**Expected behavior**
Before Installing The Update It has consumed 2929mAh for  8hrs and 7 min And After installing New Update it consumed 4509mAh for 8hrs and 29 min.
![Screenshot_2021-04-26-16-36-21-55](https://user-images.githubusercontent.com/83217939/116073997-bcfab780-a6ae-11eb-875f-b8b40d5e700b.jpg)
![Screenshot_2021-04-26-16-36-14-59](https://user-images.githubusercontent.com/83217939/116074004-bf5d1180-a6ae-11eb-814e-7ce7a86af345.jpg)

_Attach images/videos if possible. These can be helpful in solving the issue._

**Comment by KevinX8** [comment]
fixed in the hotfix
