### ISSUE TITLE
[Idea] Replace YouTube custom share dialog with Android standard

### ISSUE THREAD

**Issue by ypcyc** [YTVanced/Vanced#69]
Many Google apps do not follow "Android's guidelines" and have their own "Share dialog" (open with menu).
For me Youtube's custom dialog is frustrating as items inside are always randomised and I have to search needed option each time.
It would be cool if in Vanced version you could replace this custom dialog with Android standard!
On screenshots you can see that Youtubes dialog icons are randomised (I have just clicked, closed the dialog and clicked again, screenshot 1 vs 2). on 3rd screenshot you can see the default sharing menu on Samsung.
![image](https://user-images.githubusercontent.com/1402005/95078491-e73e5500-071d-11eb-802c-c8406e1e7c29.png)

**Comment by ypcyc** [comment]
As my request is completely ignored, is there a way to contribute?
I'm an android developer so I can make the changes myself and commit them later.

**Comment by a8underscore** [comment]
maybe you can join their discord

**Comment by ypcyc** [comment]
Almost all Discord channels are for announcements/"read only", you can't post there.

**Comment by Vendicated** [comment]
> Almost all Discord channels are for announcements/"read only", you can't post there.

What? you can write in about 95% of the channels. There's also a development channel for every open source project and an android, modding and coding channel to discuss the respective topic. You just gotta assign yourself the proper roles

![Screenshot_20210210-193056_Discord](https://user-images.githubusercontent.com/45497981/107554685-94e2d880-6bd6-11eb-9732-2595673fd5aa.png)

![Screenshot_20210210-193243_Discord](https://user-images.githubusercontent.com/45497981/107554853-c5c30d80-6bd6-11eb-8992-fc3b4b632e39.png)

**Comment by ypcyc** [comment]
Don't see a "developer" option. only tester 
![image](https://user-images.githubusercontent.com/1402005/107559218-77b50680-6be4-11eb-8cb9-e64949cd8731.png)

**Comment by ypcyc** [comment]
@Vendicated how to apply for developer role?
