### ISSUE TITLE
Bug 

### ISSUE THREAD

**Issue by boyss180** [YTVanced/Vanced#690]
**Bug description**
Vanced 16.14.34,Video quality cannot customize,no matter what you set,the result seems to be auto

**Variant**
Non-Root/Root

**Vanced version**
16.14.34

**Android version**
Android 11

**Device**
Samsung Galaxy A70

**Comment by roweger** [comment]
Came here to report this exact issue. 
@boyss180 or someone might want to edit the title to make it more descriptive.

**Comment by AlatreonTheGod** [comment]
Why can't i swipe down my newfeeds to refresh it for more vids it just stuck there and doesn't let me refresh it

**Comment by wigra6** [comment]
You are going to find more on the topic here :
[https://github.com/YTVanced/Vanced/issues/697](url)
and
[https://github.com/YTVanced/Vanced/issues/707](url)

**Comment by KevinX8** [comment]
fixed in 16.16.38
