### ISSUE TITLE
[Bug] Draining Battery

### ISSUE THREAD

**Issue by Compr0mzd** [YTVanced/Vanced#691]
**Bug description**
Last version of Vanced 16.14.34 is draining battery. Without any usage of Vanced ( just in background) app is draining lot of battery and phone start getting hot.
Encounter on One Plus 9 Pro 

**Variant**
Non-Root

**Vanced version**
16.14.34

**Android version**
Android 11

**Device**
OnePlus 9 Pro

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2. Watch videos
3. Background the app
4. After 5m the phone get hot and battery drain warning. 

Could be an issue with a background job.

**Comment by AbramTTP** [comment]
I have the same issue for the same app version on Asus ROG Phone 2 (Android 10)

See screenshot from SystemPanel2, it's hungrier than even Brawl Stars given a same time. ![Screenshot_20210427-000109257.png](https://user-images.githubusercontent.com/7013007/116114158-afafee00-a6eb-11eb-934c-33e1459a201b.png)

**Comment by Compr0mzd** [comment]
> I have the same issue for the same app version on Asus ROG Phone 2 (Android 10)
> 
> See screenshot from SystemPanel2, it's hungrier than even Brawl Stars given a same time. ![Screenshot_20210427-000109257.png](https://user-images.githubusercontent.com/7013007/116114158-afafee00-a6eb-11eb-934c-33e1459a201b.png)

20% Battery drain in almost 1h30 to give some numbers as well !

**Comment by WarrenWillingham** [comment]
Tore through my battery today as well.
Caused it to heat up as well
Non-root oneplus 6t
If more info is needed I can provide it. Thank you

**Comment by Grossdm** [comment]
Seems to be draining my battery also.
OnePlus 6T non-root.

**Comment by KevinX8** [comment]
try the latest hotfix that was just pushed (same version), might have reduced it a bit as it removed an issue with chromecast constantly looping in the background

**Comment by Compr0mzd** [comment]
> try the latest hotfix that was just pushed (same version), might have reduced it a bit as it removed an issue with chromecast constantly looping in the background

I reinstalled it via the Vanced Manager didn't saw any update right now. We'll see at usage :D

**Comment by KevinX8** [comment]
> > try the latest hotfix that was just pushed (same version), might have reduced it a bit as it removed an issue with chromecast constantly looping in the background
> 
> I reinstalled it via the Vanced Manager didn't saw any update right now. We'll see at usage :D

yeah it was a hotfix with the same version number so it's not gonna show up as a new build

**Comment by Compr0mzd** [comment]
> > > try the latest hotfix that was just pushed (same version), might have reduced it a bit as it removed an issue with chromecast constantly looping in the background
> > 
> > 
> > I reinstalled it via the Vanced Manager didn't saw any update right now. We'll see at usage :D
> 
> yeah it was a hotfix with the same version number so it's not gonna show up as a new build

Thx i'll test it right now !

**Comment by Grossdm** [comment]
> 
> 
> try the latest hotfix that was just pushed (same version), might have reduced it a bit as it removed an issue with chromecast constantly looping in the background

So use Vanced Manager to reinstall the same (current) version, and request a re-download?

**Comment by KevinX8** [comment]
> > try the latest hotfix that was just pushed (same version), might have reduced it a bit as it removed an issue with chromecast constantly looping in the background
> 
> So use Vanced Manager to reinstall the same (current) version, and request a re-download?

yep

**Comment by KevinX8** [comment]
I have had multiple confirmations that this has indeed fixed battery drain, closing it now

**Comment by Compr0mzd** [comment]
Yep it did fix the issue

**Comment by Fletchett** [comment]
I still have this problem after uninstalling and reinstalling the news version again.

**Comment by WarrenWillingham** [comment]
It seems like it is still wrecking my battery and heating up significantly, though it might be less than yesterday? I'll give it a few more days and then reply back if its still chewing through battery

**Comment by Harmonie666** [comment]
This issue is not solved. Still draining battery and overheating. Right now Vanced consumed over 50% battery. Please check:
https://www.reddit.com/r/Vanced/comments/mzvcc9/vanced_47_battery_drain_after_installing_the/?utm_medium=android_app&utm_source=share

**Comment by Harmonie666** [comment]
Vanced 62% battery consumption. This is the most buzzard thing I've seen. This is the result after reinstalling the latest update. The Hotfix doesn't work.
![Screenshot_20210427-232330382 (1)](https://user-images.githubusercontent.com/73917917/116314731-c3bd2380-a7af-11eb-9636-9e57c546d595.png)

**Comment by milindgoel15** [comment]
fixed with v16.16.38. Update your vanced app and if it still happens for you.

**Comment by Fletchett** [comment]
v16.16.38 does seem to have fixed it, though battery usage still seems slightly higher than v.15.x.x. Just slightly though, nothing crazy like the previous version.

**Comment by WarrenWillingham** [comment]
Hey @Fletchett I had the same observation, make sure that the resolution is standard across versions, it *might* be the difference

**Comment by Harmonie666** [comment]
> v16.16.38 does seem to have fixed it, though battery usage still seems slightly higher than v.15.x.x. Just slightly though, nothing crazy like the previous version.

I agree with you. It's definitely not entirely fixed, but it's better than the Hotfix. Hopefully it won't be a issue anymore in following versions.

**Comment by rsmyst** [comment]
Battery usage has increased once more. It was fine for the first 2 days on the latest update but now it's back to 22%/hr. Unusable. It was sitting squarely at 11% an hour the first few hours. After which it gradually increased and now it's back to a painful discharge. It drains as much battery as playing a full 3d game.

**Comment by milindgoel15** [comment]
Send a logcat with the screenshot of version of vanced u have

**Comment by rsmyst** [comment]
[logcat_05-03-2021_07-49-46.txt](https://github.com/YTVanced/Vanced/files/6412904/logcat_05-03-2021_07-49-46.txt)
I think this is the logcat. Idk how to get the logcat of vanced per se but I enabled logcat reader, granted it the permission through ADB and used vanced for a minute or 2 and then saved it. Is this alright?

**Comment by milindgoel15** [comment]
Ok. I haven't take a look at ur logs yet. You can try forcing VP9 codec in vanced settings and see the drain from 100 to 0. We saw that using vp9 uses less battery for most people.  Give it a try until we see ur logs.

**Comment by rsmyst** [comment]
> Ok. I haven't take a look at ur logs yet. You can try forcing VP9 codec in vanced settings and see the drain from 100 to 0. We saw that using vp9 uses less battery for most people. Give it a try until we see ur logs.

Ok. I will do the same. I have switched to vp9 now. Please do fix it as soon as possible. 
Thanks for such an awesome app again. Good luck.
