### ISSUE TITLE
[Bug] "Home" tab not refreshing OR "Subscriptions" is not scrollable

### ISSUE THREAD

**Issue by astuntas** [YTVanced/Vanced#693]
**Bug description*
Depending on the following setting, one of the functions isn't working. 
The setting: Vanced settings > Layout settings > Comments location (Alpha)

**If "Comments location (Alpha)" is disabled:** 
"Subscriptions" work as it should, are scrollable right and left, and there is an "ALL" button. 
Problem: "Home" screen does not refresh on swipe down

**If "Comments location (Alpha)" is enabled:** 
Problem: "Subscriptions" menu is not scrollable right and left, there is no "ALL" button. 
"Home" screen does refresh properly on swipe down

**Variant**
Non-Root

**Vanced version**
16.14.34 - Build - 01.50.01
But this bus was present with previous versions as well, I just didn't get to report it

**Android version**
Android Q (10)

**Device**
Samsung Galaxy S9+

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2. Go to settings and set "Comments location (Alpha)" to disabled. The "Home" screen does not refresh anymore on swipe down.
3. Go back to settings and set "Comments location (Alpha)" to enabled. The "Home" screen refreshes as it should on swipe down, but "Subscriptions" menu doesn't allow to swipe right and left, and there is no "ALL" button anymore

**Expected behavior**
Comments location shouldn't affect the "Home" refresh behaviour or "Subscriptions" menu layout at all

Screen recording:
https://youtu.be/y7gEfE2bLfs

**Comment by KevinX8** [comment]
The feature is labelled alpha for this very reason, it's likely not possible to fix it due to how it works (spoofs some stuff as a tablet layout

**Comment by astuntas** [comment]
Thats fine, but when it is disabled the "Home" menu should refresh on swipe down, shouldn't it?

**Comment by KevinX8** [comment]
oh that's a bug related to litho adblocking, no fix in sight any time soon

**Comment by shani6** [comment]
The same thing happens to me. 
Please fix it soon!!!

**Comment by astuntas** [comment]
I found a workaround: on Home tab you scroll to the top and it doesn't refresh on swipe down, so you you click on one of the suggestion buttons on top (between the Youtube icon and the first video clip), and then refresh works. It means that you need to make one extra click every time, but its good enough until a proper fix comes out

**Comment by shani6** [comment]
> I found a workaround: on Home tab you scroll to the top and it doesn't refresh on swipe down, so you you click on one of the suggestion buttons on top (between the Youtube icon and the first video clip), and then refresh works. It means that you need to make one extra click every time, but its good enough until a proper fix comes out

where? I can not find

**Comment by shani6** [comment]
> I found a workaround: on Home tab you scroll to the top and it doesn't refresh on swipe down, so you you click on one of the suggestion buttons on top (between the Youtube icon and the first video clip), and then refresh works. It means that you need to make one extra click every time, but its good enough until a proper fix comes out

where is seggestiin button?
I can not find and not understand..
