### ISSUE TITLE
[Bug] Info Cards (or whatever they're called)

### ISSUE THREAD

**Issue by dkonioris** [YTVanced/Vanced#694]
![20210426_224812](https://user-images.githubusercontent.com/83245694/116141579-8722f680-a6e1-11eb-81ff-eb5ad2e2b0a5.jpg)

**Bug description**
In general you can turn off info cards from your youtube account and it has nothing to do with the youtube or youtube vanced app. But in the latest version, even though i have them turned off, they still show up. Is it a bug or did something in the youtube code change?

**Variant**
Non-Root

**Vanced version**
16.14.34 - Build - 01.50.01

**Android version**
Android 10

**Device**
Samsung Galaxy A21s

**Steps to Reproduce**
Steps to reproduce the error: (lol)
1. Open the app
2. Click on a video
3. Wait till an info card pops up even though you've turned the off

**Expected Behavior**
Info Cards should not show up

PS: I am greek

**Comment by KevinX8** [comment]
Did you check stock YouTube aswell?

**Comment by milindgoel15** [comment]
Please check your issue on the latest vanced v16.16.38.  We are closing this issue for now. Feel free to reopen if you still face the same.
