### ISSUE TITLE
[Bug] Cast won't find device "Chromecast"

### ISSUE THREAD

**Issue by Scooterspade** [YTVanced/Vanced#695]
**Bug description**
When casting , it will tell me no device has been found. 

**Variant**
Non-Root

**Vanced version**
16.14.34

**Android version**
Android 11

**Device**
Pixel 5

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2. Click on cast icon 
3. .... Will try and find device but will end up with error saying no device found

**Expected behavior**
Works on YouTube and other cast apps , so it's not related to network issues

**Comment by KevinX8** [comment]
oh come on look at the closed issues first, download the hotfix, just press redownload
