### ISSUE TITLE
[Bug] Youtube vancade resend update 

### ISSUE THREAD

**Issue by jarno9981** [YTVanced/Vanced#696]
**Bug description**
Phone Gets extremeley hot when whatching vidoes on latest youtube vanced i did measure temps around 45 - 50 degrees (1080p vidoe) 10minutes 

**Variant**
Non-Root

**Vanced version**
Latest

**Android version**
Android 11.0 - Q

**Device**
Samsung Galaxy S10+

Battery drain below 
![Screenshot_20210426-223303_Device care](https://user-images.githubusercontent.com/53493418/116146994-71143680-a6df-11eb-8f58-b4173eb9d90d.jpg)

**Comment by KevinX8** [comment]
look at pinned issues
