### ISSUE TITLE
[Idea] Remove YT's "Autoplay" button

### ISSUE THREAD

**Issue by Harmonie666** [YTVanced/Vanced#698]
I would prefer to remove the autoplay button. I never use it, and it happens that I accidentally tap it. Currently it's not possible to remove it from the player.
![Screenshot_20210427-001809586 (1)](https://user-images.githubusercontent.com/73917917/116158071-509fa880-a6ee-11eb-9b56-ea0ab34bbfc7.png)

**Comment by Harmonie666** [comment]
@KevinX8 @VancedOfficial

**Comment by milindgoel15** [comment]
Please don't tag developers
