### ISSUE TITLE
[Bug] Swipe controls don't work in offline videos

### ISSUE THREAD

**Issue by Susko3** [YTVanced/Vanced#70]
Repro steps:

1. Enable swipe controls for brightness and/or volume
1. Download a video for offline viewing (YT Premium required)
1. Turn off WiFi and mobile data
1. Play the video you downloaded
1. Try using swipe controls -> they don't work, up/down swipe doesn't matter
1. Instead of changing volume/brightness the following text appears when swiping down: "No connection" and the swipe down gesture to exit fullscreen is executed

Vanced version: 15.38.35, nonroot

**Comment by ZB4Rty** [comment]
It happened to me too 😿💔

**Comment by Susko3** [comment]
Bug is still present in version 15.43.32 - Build - 01.47.00

**Comment by milindgoel15** [comment]
Fixed with v16.16.38 release. A slight note, make sure you turn off end cards for swipe controls to work on offline videos now.
