### ISSUE TITLE
[Bug] Slide volume and brightness controls don't work anymore

### ISSUE THREAD

**Issue by frenchiveruti** [YTVanced/Vanced#700]
**Bug description**
Replace me with a clear and detailed description of the bug.

**Variant
Non-Root/Root

**Vanced version**
16.02.35 - Build - 01.47.00

**Android version**
Android 9.0 - Pie

**Device**
Samsung Galaxy S8

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
3. ....

**Expected behavior**
Replace me with a description of what you expected should happen and what happened instead.

_Attach images/videos if possible. These can be helpful in solving the issue._

**Comment by frenchiveruti** [comment]
Ok so here I'll post it because github on phone sucks.

On previous version I had this option enabled where I could slide on the sides to lower and raise the volume.
Basicallly the main reason I use vanced.
Now it doesn't work anymore, I disabled and enabled it again and it still does not work.

**Comment by KevinX8** [comment]
It's a know issue, it's caused by the very buggy shorts feature that is currently in beta, just avoid watching them for now or just don't watch them in the shorts/tiktok player

**Comment by frenchiveruti** [comment]
I see, thank you sir. 
I'll disable YouTube shorts then. Great
