### ISSUE TITLE
[Bug] 16.14.34 no longer detects casting device

### ISSUE THREAD

**Issue by JDMorris81** [YTVanced/Vanced#701]
**Bug description**
Installed latest version of Vanced and pressing cast button no longer displays casting device as it did in previous version 
![Screenshot_20210426-173916](https://user-images.githubusercontent.com/72824463/116170836-6ac09300-a6bc-11eb-8e06-03ae090ba58d.jpg)

**Variant**
Non-Root/Root

**Vanced version**
16.14. 34

**Android version**
Android 11 

**Device**
Samsung Galaxy S20 5G

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
3. ....

**Expected behavior**
Replace me with a description of what you expected should happen and what happened instead.

_Attach images/videos if possible. These can be helpful in solving the issue._

**Comment by KevinX8** [comment]
You got pointed to a duplicate but made a new one instead....
