### ISSUE TITLE
[Idea] easier "not interested" button

### ISSUE THREAD

**Issue by dewbus** [YTVanced/Vanced#703]
What if each video thumbnail was split in half, if you tap the left side of the thumbnail it gets register as "not interested" while the right side plays the video as normal.

![Screenshot_20210426-232344](https://user-images.githubusercontent.com/21012719/116180193-7f198580-a6e6-11eb-9c8d-3df769625667.jpg)

Currently to choose "not interested" in video is too many taps.

YouTube's algorithm will keep the same videos on our feed for weeks if not months. 

Apps with similar functionality are tinder, plenty of fish, etc.

**Comment by TrianguloY** [comment]
That will be probably confused for users, even if it's an opt-in issue it's easy to forget (unless it shows a visual indication somehow).

What about being able to swipe left/right to dismiss? I think that's a more common gesture.

**Comment by dewbus** [comment]
> That will be probably confused for users, even if it's an opt-in issue it's easy to forget (unless it shows a visual indication somehow).
> 
> What about being able to swipe left/right to dismiss? I think that's a more common gesture.

I based my decision on what I believe was easier to implement, however I am a novice programmer. I do agree that swipe would be more intuitive for the user.

**Comment by Martin5001** [comment]
And you could show an icon when swiping. Like for example Gmail does for swipe delete gesture.

![20210504_151621](https://user-images.githubusercontent.com/35201200/117009350-ee493800-aceb-11eb-8cc1-013aac8aecc9.jpg)
