### ISSUE TITLE
[bug] YouTube Vanced 16.14.34 build 01.50.01 -  fucked up video quality preferences !

### ISSUE THREAD

**Issue by wigra6** [YTVanced/Vanced#707]
Hi,
I've updated my YouTube Vanced to v.16.14.34 build 01.50.01 and now I lost control over video quality preferences ( -> in app's Settings).
Whatever my choice in this matter is - IT GETS AUTOMATICALLY RESET and YT Vanced TRIES TO PLAY ALL VIDS WITH MAXIMUM AVAILABLE QUALITY (1080p or even higher).

It's a real disaster for someone like me who :
1. uses YT Vanced mainly on Mobile data (metered connection)
2. my internet is terribly slow (max 68KB/s).

Since I can't successfully set the proper video quality (for me - 240p) in Settings - I need to CORRECT IT EACH AND EVERY TIME in settings of just watched video (not always successfully as well due to random resets here too !).  
This is unbelievably annoying, so please..., please work this bug ASAP.

And in the meantime - I would be grateful if someone could send me the link to the previous version of YT Vanced. The last version is unusable for me.

**Comment by fosam** [comment]
Youtube has inroduced an new video quality control under the settings menu, it is called "Video quality preferences"
So you have to adjust your desired preferences there so it won't use higher video qualities.

![Screenshot_20210427-185259](https://user-images.githubusercontent.com/52612348/116283511-3fa57480-a78c-11eb-8f73-0ea9498f5965.jpg)

**Comment by wigra6** [comment]
Just noticed that #697 is dedicated to the same issue.

Worth to mention is that there is NO SUCH ISSUE IN ORIGINAL YT APP !
Despite YT made changes in video quality settings lately - there is no problem with chosing the desired quality once and for all there.
The reset of user chosen values of video quality shows up in YT Vanced ONLY !  
-----
my phone :  Xiaomi Redmi Note 8T
Android 10

BTW
Have got some screenshots, but have no idea how to attach them using my phone (any pc isn't available where I'm right now).

**Comment by KevinX8** [comment]
If you're using the vanced preferred resolution stuff then yes it's broken don't use it for now, it will act exactly the same as stock YouTube after that

**Comment by wigra6** [comment]
@KevinX8  I'm not sure what you mean exactly. Unfortunately, my English isn't the best one !
Then could you please try rewriting your message / be more specific ?
Thanks in advance for your assistance.

**Comment by KevinX8** [comment]
I meant, go to vanced settings > preferred resolution and set everything to auto, now the new menu will function exactly like stock youtube.

**Comment by VancedOfficial** [comment]
Found the issue and it'll be fixed in the next update. In the meantime (like Kevin mentioned above), change your Vanced override qualities to "Auto" to avoid them being set to the highest resolution possible (Google reversed the quality list so searching the max resolution results in the highest resolution always).

**Comment by Fricsion** [comment]
> Google reversed the quality list
that's very inconsistent of google... but ik companies do what companies do...

I hope it will be fixed soon. It was actually a more important feature than ads blocking... I have poor connection and a brutal data caps. Thank you devs!

**Comment by KevinX8** [comment]
fixed in 16.16.38

**Comment by wigra6** [comment]
I've trouble downloading 16.16.38 in Vanced Manager.
Tried 7 or 8 times, but the download never ended with success. 
Error message keep poping up each time.  🥴
