### ISSUE TITLE
[Bug] Vanced exiting with no error message

### ISSUE THREAD

**Issue by davidavida70** [YTVanced/Vanced#708]
**Bug description**
Vanced exits itself, no matter what I am doing

**Variant**
Non-Root

**Vanced version**
16.02.35 - Build - 01.47.00

**Android version**
Android 5

**Device**
Samsung Galaxy A3 2015

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2. Watch some videos
3. Wait

I have a logcat if you want, send a pm in discord Davidavida70#6013

**Comment by milindgoel15** [comment]
Update ur vanced
