### ISSUE TITLE
[Idea]

### ISSUE THREAD

**Issue by revenant19** [YTVanced/Vanced#71]
Hi there devs of vanced, well is not an idea really but when you close the app bit still watchig the vídeo in floting window then, when you open the app again ir brings you back to the start of the videos on "subscriptions" for exaplme, i scroll down to find a video and start to watch it, then i go out and my video still playing but whe  i open it again it start son the top and dont stay on down that i scroll, plis fix this bc it bother a lot have to scroll down all 

again

**Comment by spicyfoxx** [comment]
Is this stock behaviour? If yes, the developers can't do anything about it.

**Comment by revenant19** [comment]
Not really, honestly its hard to explain, i tried to send a vídeo but i cant

**Comment by RadheShyamDasa** [comment]
> Is this stock behaviour? If yes, the developers can't do anything about it.

See my reported bug
