### ISSUE TITLE
[Bug] Battery drain issue still causing issue after hotfix

### ISSUE THREAD

**Issue by will8137** [YTVanced/Vanced#712]
**Bug description**
Updated to the latest version of vanced app and micro g yet battery drain and cpu temps are very high even after hotfix. Related to #691

**Variant**
Non-Root

**Vanced version**
16.14.34

**Android version**
Android 10

**Device**
Samsung Galaxy S9+

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2. Wait and see the cpu overload notification
3. Check battery usage and see vanced taking loads of battery

**Expected behavior**
Vanced working without overloading the cpu

**Comment by Cowh3ad** [comment]
Having similar issues, though I think mine stems from videos always going to highest resolution possible even if I choose a specific resolution in vanced settings and datasaver in youtubes own settings (oneplus 7 pro)

**Comment by Harmonie666** [comment]
Same here. Over 60% battery drain after reinstalling the latest version "Hotfix".

![Screenshot_20210427-232330382 (1)](https://user-images.githubusercontent.com/73917917/116357050-55eb1900-a7fc-11eb-8389-1f6c7a73e438.png)

**Comment by bluemods** [comment]
This is caused by an infinite exception loop with chromecast (I think), causing the app to retry infinitely and spam the stack trace and max load the CPU.

Stack trace here (loops infinitely)

[trace.txt](https://github.com/YTVanced/Vanced/files/6390870/trace.txt)

**Comment by milindgoel15** [comment]
Users with heating and battery drain issues here, send the sha 256 hash value of the Vanced base apk that u used. Also logcats

**Comment by gghhkm** [comment]
Don't forget to join the Open Beta to help debug future builds.
https://discord.gg/vanced

**Comment by Grossdm** [comment]
I'm still having battery drain problems on my OnePlus 6T.  I don't think I can logcat without root (please advise).
I ran `sha256sum -b *` in Termux and got this:
 
    92665e78b82c1ce973bce47b5480b448061a626b159121a6b83c65f0dabc2e89 *black.apk
    1262707db0aea11d55734e2ee0d8727d50868a5e98518da0ea247092a74f5beb *split_config.arm64_v8a.apk
    4660a9de6aa1c3110d8ea3799a9b80ffa5d3a60656e8afbf788d4f306a73fd8f *split_config.en.apk

**Comment by gghhkm** [comment]
> I don't think I can logcat without root (please advise).
https://github.com/gghhkm/Vanced-Issue-Center/blob/main/Guides/CreatingALogcat.md

**Comment by KevinX8** [comment]
Try 16.16.38 and report back

**Comment by rsmyst** [comment]
I've got the same issue on the same device. I thought my battery was acting weird. Turns out it was vanced. Took me a while to figure out that vanced was the cause. 
It keeps defaulting to 2160p and the speed of videos randomly resets as well.
Battery drains about 1.5 times the usual. The usual for me is around 9.5% an hour while screen is on. Vanced increases that to around 25 to even 30% an hour.

**Comment by milindgoel15** [comment]
@rsmyst have you updated your vanced to 16.16.38? if not, please do since you are mentioning bugs from the older release.

**Comment by rsmyst** [comment]
> @rsmyst have you updated your vanced to 16.16.38? if not, please do since you are mentioning bugs from the older release.

Yes I didn't realize there was an update earlier. I have updated now and the issue has disappeared.
