### ISSUE TITLE
[Bug] unable to open links in vanced

### ISSUE THREAD

**Issue by HuzaifaAzhar** [YTVanced/Vanced#713]
**Bug description**
Whenever I press a link in vanced it just says youtube cant open this link.

**Variant**
Non-Root

**Vanced version**
16.14.34 - Build - 01.50.01

**Android version**
Android 11.0 - Android 11

**Device**
Oppo Reno 10X Zoom

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2. Click on any link you find

**Expected behavior**
The link should open in a browser or if it is a youtube link vanced
![Screenshot_2021-04-28-04-25-33-36_7a4090f09f6554852d748ee9fd6f40d3](https://user-images.githubusercontent.com/83317308/116324841-52df3100-a7da-11eb-822b-3900f12cc841.jpg)
 should play that video.

_Attach images/videos if possible. These can be helpful in solving the issue._

**Comment by milindgoel15** [comment]
Disable official YouTube app in your device settings to fix that issue.
