### ISSUE TITLE
[Bug] Shorts not working properly

### ISSUE THREAD

**Issue by HuzaifaAzhar** [YTVanced/Vanced#714]
**Bug description**
When I tap a video in shorts it play the video but when i swipe next it doesnt play the next video instead it plays random videos.

**Variant**
Non-Root

**Vanced version**
16.14.34 - Build - 01.50.01

**Android version**
Android 11.0 - Android 11

**Device**
Oppo Reno 10X Zoom

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2. Click on any short
3. swipe up

**Expected behavior**
Swiping up should play the next short but instead it plays random shorts.

_Attach images/videos if possible. These can be helpful in solving the issue._

**Comment by KevinX8** [comment]
We didn't code shorts, YouTube intended it to be a tiktok clone so playing random videos is intended by YouTube.
