### ISSUE TITLE
[Bug] VANCED Does not respect the device's screen resolution.

### ISSUE THREAD

**Issue by fosam** [YTVanced/Vanced#715]
**Bug description**
The "MAX resolution" option is set to off but Vanced just ignores to follow the device's screen resolution, thus listing resolutions that are higher than the phone's screen resolution, like 1440p and 2160p, while the phone's screen is 1080p.

**Variant**
Non-Root

**Vanced version**
15.43.32 - Build - 01.47.00

**Android version**
Android 10

**Device**
Samsung Galaxy S9

**Steps to Reproduce**
Steps to reproduce the error:
1. Turn off MAX resolution in the settings.
2. Play a video that is higher than your screen's resolution.

**Expected behavior**
When turning MAX resolution off, Vanced must follow the screen resolution of one's device and should only list video qualities that match the device's resolution, not higher, for example 720p video on 720p screen, 1080p video on 1080p screen, not 2160p on 720p screen, and so on...

- Note: _i'm not talking about the new YouTube quality preferences issue, that is something different, but i'm not sure if it could be linked to this_

![Capture 28_04_2021_03_16_08](https://user-images.githubusercontent.com/52612348/116331826-d5fb8980-a7d0-11eb-8974-77a3e8a87022.png)

- **The last 2 resolutions below should have been disabled/hidden.**

![Capture 28_04_2021_03_18_18](https://user-images.githubusercontent.com/52612348/116332004-37235d00-a7d1-11eb-8847-98227a81ae32.png)

**Comment by Fricsion** [comment]
Same issue for me. one video started playing in 2060p resulting in very slow buffering. I even set the default resolution to 144p by the way.

**Comment by gghhkm** [comment]
Most likely just Google not having a limited server side, check stock. Max resolution option is there to try bypassing server side limits.

**Comment by fosam** [comment]
> Same issue for me. one video started playing in 2060p resulting in very slow buffering. I even set the default resolution to 144p by the way.

Playback quality is not an issue on this ticket, i think you have a different issue? i'm mainly discussing screen resolution dependence.

**Comment by fosam** [comment]
> Max resolution option is there to try bypassing server side limits.

But not when it is turned off.

In other words, does YouTube now allow us to to play videos that are higher quality than our devices? if it is the case then i think it is normal that "Max resolution" does not have any effect anymore even if the user wants to stay at 1080p by turning the option off the option, as this is triggered directly by YouTube.

I'm not able to test with stock as i don't have access to it

**Comment by gghhkm** [comment]
> > Max resolution option is there to try bypassing server side limits.
> 
> But not when it is turned off.
> 
> In other words, does YouTube now allow us to to play videos that are higher quality than our devices? 

Google sets resolution caps server side for various reasons, usually per-device hardware but Google is known to change it on a whim, so it's very possible that they could've removed or just not set a resolution cap.
> I'm not able to test with stock as i don't have access to it.

Unfortunately the only way to know for sure is to test stock and see if it's the same or not.

**Comment by fosam** [comment]
I'll check on a Samsung tablet and report back here

**Comment by KevinX8** [comment]
this is a google issue that happens on stock youtube too, please don't blame vanced for google's doings

**Comment by fosam** [comment]
Yes, this happens also on stock.

@KevinX8 I did not blame vanced, i was only poking at the function, maybe it can be removed now as YouTube does not limit the quality based on screen resolution?

**Comment by KevinX8** [comment]
It's server side shit they decided to hastely Push, we're not really looking into fixing Google's fuck ups lol report it on the actual YouTube issue tracker

**Comment by fosam** [comment]
@KevinX8 
Yes, i know, but i think you misunderstood.

I said you guys can now remove "MAX resolution" as it doesn't serve any good regardless if it is ON or OFF because YouTube is now letting the users choose all the qualities they want from 144p to 2160p regardless of what screen resolution the user's device is.

**Comment by KevinX8** [comment]
oh it's likely they'll roll it back tho since it's definitely not mean to be happening, their vision for the future is everyone watching at 480p while premium users watch at 1080p and premium pro at 4k etc.

**Comment by fosam** [comment]
I'll take the premium pro as a joke 😆

But it would be possible to get rid of that option to eliminate the confusion in case YouTube keeps all the quality choices for everyone, wouldn't it?

I'll check a 4K video on a 1080p screen on the next version of stock, if i happen to play the 4K video then i think It is really intended by YouTube and not a mistake.

**Comment by fosam** [comment]
Yes, we will keep an eye on the next stock version as i stated above.
