### ISSUE TITLE
Homepage Update Problems

### ISSUE THREAD

**Issue by DeadKingVapes** [YTVanced/Vanced#718]
Hey Guys,

I cannot Update my Homepage in the YouTube app and i dont Know why.

Can someone Help me?

**Comment by gghhkm** [comment]
The refresh bug is a known issue.
You can follow workarounds to temporarily fix the problem. There are 5 workarounds as reported by user's.
1. If comments are disabled, enable them back again.
2. Try force stopping app and try again.
3. Downgrade back to v15.40. 
4. Disabling general ad removal also fixes as reported by OP
5. Switch on comments location (alpha) from ads settings

Please wait patiently until it gets resolved either by Google itself or Vanced team.
