### ISSUE TITLE
4K and hdr not working correktly

### ISSUE THREAD

**Issue by GitmanHD** [YTVanced/Vanced#72]
### Issues:

-Showing 4k only sometimes at random
**-sometimes black picture**
**-2/4k immense lag**
**-hdr not working sometime**s
-force max res working only after Phone reboot
-delete ads not working at all time
-can´t put MicroG into no Battery saving mode
-videos cant load sometimes
_(exo player v2 is working better but not flawless)_

### Positive Feedback:
-Sponsor Block is a good idea
-blocks most ads effective
-overall good experience
-long term usage with practicly no flaws

### Setup:

P30 lite Emui 10, android 10

### tested versions:

vanced 14.21.54 not frequent issues / vanced 15.38.35 frequent issues

### Suggestions:

-add fixed search menue to repeat search faster
-delete unwanted Youtube Channels from first page (blacklist)
-option to delete youtube premium ads 
-delete blue tutorial pads

hope i could help develop Vanced further!!!
Good Work! Keep it up!

**Comment by milindgoel15** [comment]
please update to the latest v16.16.38 to not face any issue you mentioned above. We are closing this issue. Feel free to reopen if you still face an issue.
