### ISSUE TITLE
[Idea] Reversing the Resolution Update

### ISSUE THREAD

**Issue by dmert2000** [YTVanced/Vanced#721]
**Description**
Last update Vanced had a setting that you can choose the specific resolution you want your videos to start playing, but now you can eaither choose max resolution or data saver option. Please bring back that option to select the specific resolution in the next update
![IMG_20210429_140126](https://user-images.githubusercontent.com/83403032/116540889-6d58fd80-a8f3-11eb-84aa-2b789a3ce989.jpg)

**Comment by KevinX8** [comment]
We didn't push it believe it or not, ask Google on social media to revert it
