### ISSUE TITLE
[Bug]impossible to install youtube vanced on rooted phone

### ISSUE THREAD

**Issue by Ragnarou9** [YTVanced/Vanced#722]
**Bug description**
impossible to install youtube vanced on rooted phone

**Variant**
Root

**Vanced manager version**
02.06.00

**Android version**
Android 5.0 - lollipop

**Device**
Samsung Galaxy note 3
**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2. Click on youtube vanced
3. Click on download
4. vanced manager download all the file.
5. it try to install the app then an error apear .
![Screenshot_2021-04-29-15-46-32](https://user-images.githubusercontent.com/81658398/116574536-1ad90a80-a90e-11eb-958d-75486736f404.png)
![Screenshot_2021-04-29-15-46-38](https://user-images.githubusercontent.com/81658398/116574541-1ca2ce00-a90e-11eb-8595-d1042add6e70.png)
![Screenshot_2021-04-29-15-46-45](https://user-images.githubusercontent.com/81658398/116574546-1dd3fb00-a90e-11eb-8400-ec0d431a8ac1.png)
![Screenshot_2021-04-29-15-46-49](https://user-images.githubusercontent.com/81658398/116574552-1f052800-a90e-11eb-8837-8797db9c1890.png)

_Attach images/videos if possible. These can be helpful in solving the issue._

**Comment by milindgoel15** [comment]
- If u are using SuperSU, switch to magisk.
- If u are already using magisk, reboot device and try again.
