### ISSUE TITLE
[Bug] no internet connection

### ISSUE THREAD

**Issue by gurlal062** [YTVanced/Vanced#724]
**Bug description**
Replace me with a clear and detailed description of the bug. When i open vanced YT its shows no Internet connection but my Internet connection is working

**Variant**
Non-Root

**Vanced version**
16.02.35 - Build - 01.47.00

**Android version**
Android 9.0 - Pie

**Device**
Redmi note 5 pro

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
3. ....

**Expected behavior**
Replace me with a description of what you expected should happen and what happened instead.

_Attach images/videos if possible. These can be helpful in solving the issue._
![Screenshot_2021-04-29-21-10-38-960_com vanced android youtube](https://user-images.githubusercontent.com/83416563/116578771-5e903c00-a92f-11eb-9f37-925bc099749e.jpg)

**Comment by seniorkiller** [comment]
i have the same problem. it seem happen after i turn of my device. before that it work just fine. the only fix i found is to remove vanced microG. but when i turn of my device it happen again

**Comment by milindgoel15** [comment]
Read troubleshooting using our [vanced guide app](https://play.google.com/store/apps/details?id=com.vanced.faq)
