### ISSUE TITLE
[Bug] i search something and shows nothing

### ISSUE THREAD

**Issue by Abonity** [YTVanced/Vanced#725]
**Bug description**
When i search something, in sometimes, shows nothing, and i need to close the app and search again for shows something

**Variant**
Non-Root

**Vanced version**
16.14.34

**Android version**
Android 9.0 - Pie

**Device**
Lenovo Z6 lite

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2. Watch some videos
3. and search something

**Expected behavior**
It was supposed to show the search results

![Screenshot_2021-04-29-18-20-45-2046882958](https://user-images.githubusercontent.com/83374077/116620539-57116880-a918-11eb-9827-f00f1e348a06.png)

**Comment by milindgoel15** [comment]
Please update to latest youtube vanced and check if the issue persist.

**Comment by alexceltare2** [comment]
![Screenshot_20210430-080511](https://user-images.githubusercontent.com/7403035/116660354-d2136700-a98a-11eb-95c4-044237cd9e60.png)
Same problem. Searching or opening does nothing.

**Comment by Abonity** [comment]
> Please update to latest youtube vanced and check if the issue persist.

Its the latest version

**Comment by Abonity** [comment]
> ![Screenshot_20210430-080511](https://user-images.githubusercontent.com/7403035/116660354-d2136700-a98a-11eb-95c4-044237cd9e60.png)
> Same problem. Searching or opening does nothing.

this problem is very annoying

**Comment by milindgoel15** [comment]
please try disabling battery optimization using dontkillmyapp.com. microG was killed by your device resulting in that issue.

**Comment by Abonity** [comment]
it seems that solved

**Comment by alexceltare2** [comment]
The app(16.16.38) as well as MicroG(0.2.18.210500) is up to date. MicroG is also has its battery optimisation feature disabled. The issue is not resolved! Are you guys conspiring for Google or something?

**Comment by milindgoel15** [comment]
> The app(16.16.38) as well as MicroG(0.2.18.210500) is up to date. MicroG is also has its battery optimisation feature disabled. The issue is not resolved! Are you guys conspiring for Google or something?

Disable battery optimization for YouTube Vanced app too and check again. We can't fix device issues!

**Comment by alexceltare2** [comment]
> > The app(16.16.38) as well as MicroG(0.2.18.210500) is up to date. MicroG is also has its battery optimisation feature disabled. The issue is not resolved! Are you guys conspiring for Google or something?
> 
> Disable battery optimization for YouTube Vanced app too and check again. We can't fix device specific issues!

Still nothing. This issue persists for 2 days already.
