### ISSUE TITLE
[Bug] Embedded Youtube link cannot be ooened

### ISSUE THREAD

**Issue by desray2k** [YTVanced/Vanced#726]
**Bug description**
YouTube link in description cannot be opened. 

**Variant**
Non-Root

**Vanced version**
16.14.34 

**Android version**
Android 11

**Device**
Samsung Galaxy Note 10 Plus

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2. Click on any description that has a link embedded. It does not redirect to the YouTube clip or website. 
![Screenshot_20210430-062557](https://user-images.githubusercontent.com/83432731/116627214-45af7700-a97f-11eb-9d17-58b28b9f2900.jpg)

_Attach images/videos if possible. These can be helpful in solving the issue._

**Comment by milindgoel15** [comment]
Disable official YouTube app in your device settings to fix that issue.
