### ISSUE TITLE
[Idea] When I open a video in ad settings, I want a function to turn off the display of videos that appear under it.

### ISSUE THREAD

**Issue by cehnemdark** [YTVanced/Vanced#733]
**Description**
Actually, there is no need for too much detail.  I just want the other videos that appear under the screen where we open one video to be removed, only the opened video and comments to remain.

*You can also put this category in ad settings.

![IMG_20210430_142802](https://user-images.githubusercontent.com/49096330/116692182-a44b1400-a9c4-11eb-9b72-4bc4431b989c.jpg)

_Attach images/videos if possible. Also add any links to possible other applications with the said feature already implemented._

**Comment by milindgoel15** [comment]
Could u elaborate your issue?
