### ISSUE TITLE
[Bug] Brightness goes to 0 when switched orientation from portrait to horizontal after setting it via slider

### ISSUE THREAD

**Issue by ZoonoPL** [YTVanced/Vanced#739]
**Bug description**
 Brightness goes to 0 when switched orientation from portrait to horizontal after setting it via sliding option (see steps below)

**Variant**
Non-Root

**Vanced version**
16.16.38

**Android version**
Android 10.0

**Device**
Huawei P20 Pro

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2. Enable swipe gestures for brightness
2. start playing anything
3. Rotate to horizontal
3. Set brightness to desired value i.e 100%
4. Rotate phone to portrait mode
5. Rotate back to horizontal
6. Brightness should go to very low value instead keeping previously set value

**Expected behavior**
Brightness should be the same as it was set before rotation

**Comment by NicolasPL64** [comment]
Happens to me too, I'll downgrade.

**Comment by Shane9248** [comment]
+1 this.. happening with me as well

**Comment by milindgoel15** [comment]
Refer #752 from now.
