### ISSUE TITLE
[Bug] Small vertical black line on screen

### ISSUE THREAD

**Issue by erinididi** [YTVanced/Vanced#741]
Bug description
On any player on Vanced, portrait, full screen, mini-player, tablet-player, there is a short and thin vertical black line more or less in the middle of the player. 

Variant
Non-Root

Vanced version
16.16.38

Android version
Android 11

Device
Galaxy S10+ (SM-G975U1)

Steps to Reproduce
1. Open app
2. Select a video
3. Vertical bar appears

_Attach images/videos if possible. These can be helpful in solving the issue._
The black bar in different players:
https://imgur.com/a/DpQFL1P

**Comment by gghhkm** [comment]
Try tablet mini player

**Comment by gghhkm** [comment]
check stock

**Comment by repu2x** [comment]
@erinididi has this been fixed yet? I have the same issue

**Comment by milindgoel15** [comment]
**Current solution for a black line in the middle of screen of the video player (and PiP)**

It is found to happen on Samsung devices with OneUI mostly and we have no fix for it(for now).
You can do either of the following for now: 
1) ignore the line if it does not bother you much,
2) downgrade to old versions
