### ISSUE TITLE
[Bug] changing quality isn't working

### ISSUE THREAD

**Issue by dylans709** [YTVanced/Vanced#743]
**Bug description**
The auto select features for video quality are not working and it makes your data burn quickly. Like you can set all the options to the lowest quality and it'll still load the video in like 2K quality and then you have to change it manually down to 480p or whatever or a reasonable quality bit rate
**Variant**
Non-Root

**Vanced version**
16.02.35 - Build - 01.47.00

**Android version**
Android 11

**Device**
LG Velvet 5g

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
3. ....

**Expected behavior**
There should be a master override that checks before loading every single video, and forces that bit rate. Cuz by the time you load the video at that high resolution you've already used crazy amounts of your data.

_Attach images/videos if possible. These can be helpful in solving the issue._

**Comment by KevinX8** [comment]
Update your vanced to 16.16.38
