### ISSUE TITLE
[Bug] App Keeps Minimizing

### ISSUE THREAD

**Issue by Ruthless11042541** [YTVanced/Vanced#745]
**Bug description**
Whenever I open YouTube Vanced, the app minimizes after about two seconds. By that, I mean it completely disappears; it doesn't go into the small view over the home screen. However, the app does not completely crash because I can still see it in my open apps tab. This started happening during the last 3 or 4 updates.

**Variant**
Non-Root

**Vanced version**
16.16.38

**Android version**
Android 10

**Device**
Samsung Galaxy A50

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app. That's all.

**Expected behavior**
The app should stay open, but it just disappears off the screen. It does stay open in the background though.

**Comment by KevinX8** [comment]
Need more information like a logcat

**Comment by TheIronicCurtain** [comment]
Also having this problem, only started after the upgrade. About half a second after opening YT Vanced is opened I'm taken back to the home screen.

 Not sure what logcat is but if you tell me how to get it I can copy it over here

YT Vanced: 16.16.38
Vanced MicroG: 0.2.8.210500
Phone: Moto G Power
Android 10

**Comment by TheIronicCurtain** [comment]
I've already tried: clearing app storage, un- and re-installing the app

**Comment by KevinX8** [comment]
https://youtu.be/W6iDw76UpQw

**Comment by TheIronicCurtain** [comment]
Sorry I was slow, but I've got the logcat.
[logcat.txt](https://github.com/YTVanced/Vanced/files/6475815/logcat.txt)

Worth noting that I recently upgraded to android 11, did not fix the problem

**Comment by milindgoel15** [comment]
@TheIronicCurtain it looks like a device side error to me. the logs says about policy violation but I will confirm it. though I am 100% sure its device OS issue.

**Comment by TheIronicCurtain** [comment]
@milindgoel15 do you have a proposed remedy? YT Vanced was working on my device before the update. Thanks for the assistance!

**Comment by milindgoel15** [comment]
@TheIronicCurtain could u use the [scoop app](https://del.dog/Tacoscoop) to get logs? I wanted to take close look
