### ISSUE TITLE
[Bug] replaceme

### ISSUE THREAD

**Issue by Arsalan911** [YTVanced/Vanced#746]
**Bug description**
Open app swipe controls enables for brightness and volume
Every time i open video in landscape brightness goes to 100percent and then i downgrade to 0 when i back to horizontal and then again try landscape mode brightness goes to 100 percent every time video open in landscape brightness goes to 100

**Variant**
Non-Root/

**Vanced version**
16.16.38

**Android version**
Android 11

**Device**
Redmi note 9s

**Comment by KevinX8** [comment]
Duplicate

**Comment by Arsalan911** [comment]
> Duplicate

What mena duplicate? Plz explain duplicate?

**Comment by Arsalan911** [comment]
What mean duplicate?
