### ISSUE TITLE
[Bug] Refresh rate stays at 120hz when watching videos

### ISSUE THREAD

**Issue by C3H6GH** [YTVanced/Vanced#747]
**Bug description**
Refresh rate doesn't go down to 60hz when watching videos on a 120hz phone. Normal YT app does.
May be causing excessive battery drain.

**Variant**
Non-Root

**Vanced version**
16.16.38

**Android version**
Android 11

**Device**
Xiaomi Poco F3

**Steps to Reproduce**
Steps to reproduce the error:
1. Set phone refresh rate to 120Hz
2. Watch any video in YT Vanced

**Expected behavior**
Refresh rate should switch to 60Hz when watching videos.

**Comment by KevinX8** [comment]
Apps are literally not able to control refresh rate, on MIUI they have a list of apps and what refresh rate the apps should have, on OnePlus you need root to edit that list and I'm not sure on MIUI but you'll have to look it up yourself
