### ISSUE TITLE
[Bug] Brightness keeps getting decreased when i exit out of landscape mode 

### ISSUE THREAD

**Issue by Shane9248** [YTVanced/Vanced#752]
**Bug description**
Whenever i exit a video from landscape mode the brightness keeps getting decreased (to a fixed amount) and i have to manually increase it everytime i am in landscape mode

_Would love to attach a video but the mobile app isn't allowing me to_

**Variant**
Non-Root

**Vanced version**
16.16.38

**Android version**
Android 11

**Device**
Poco X2

**Steps to Reproduce**
Steps to reproduce the error:
1. Open a video in landscape mode
2. The brightness will be set to number 8
3. Swipe to increase brightness 
4. Take the video back to vertical mode
5. Open any video again in landscape mode 
6. Now the brightness will be again at number 8 

**Expected behavior**
The brightness should be the same amount as i set it to be.

**Comment by NicolasPL64** [comment]
+1
How can I downgrade? This version is full of bugs

**Comment by Shane9248** [comment]
> +1
> How can I downgrade? This version is full of bugs

redownload from the manager itself.. u gor option to install any specific version

**Comment by NicolasPL64** [comment]
It doesn't allow me to install it tho. It shows an error message that says something like I have to uninstall the previous updates and I can't do that. The only way would be uninstalling and installing again but I don't want to lose all my config. This app needs a way to export the config file tho

**Comment by Harmonie666** [comment]
Same for me. As you can see here:
http://imgur.com/a/JE0gPVc

**Comment by Harmonie666** [comment]
Another reddit post:

https://www.reddit.com/r/Vanced/comments/n3w1h6/other_the_new_vanced_ver_161638_resets_brightness/?utm_medium=android_app&utm_source=share

**Comment by Shane9248** [comment]
> Same for me. Doing the opposite in my case, with increasing the brightness: 
> http://imgur.com/a/JE0gPVc

yea mine too increases now ever since i re downloaded... just wait it will be fixed.. the devs has said it

**Comment by Shane9248** [comment]
> It doesn't allow me to install it tho. It shows an error message that says something like I have to uninstall the previous updates and I can't do that. The only way would be uninstalling and installing again but I don't want to lose all my config. This app needs a way to export the config file tho

yes.. to downgrade u have to uninstall.. just checked.. just uninstall and install again.. by config u mean vanced settings? it's not that difficult to set the settings again

**Comment by milindgoel15** [comment]
It has been fixed internally so please wait for future updates. Closing this issue for now.
