### ISSUE TITLE
[Bug] YouTube Vanced deletes from itself

### ISSUE THREAD

**Issue by Veroxity** [YTVanced/Vanced#754]
**Bug description**
Well i'm not very sure if it's a bug but sometimes YouTube Vanced sometimes deletes from itself without doing anything (YouTube auto update turned off in play store).

**Variant**
Rooted

**Vanced version**
16.16.38 - Build

**Android version**
Android 11

**Device**
Mi Note 10 Lite

**Steps to Reproduce**
Steps to reproduce the error:
1. I don't think i can reproduce the error, as i said it deletes from itself.

**Expected behavior**
It shouldn't delete YouTube Vanced and Install YouTube.

**Comment by milindgoel15** [comment]
Did u rebooted ur device?

**Comment by Veroxity** [comment]
wdym?

**Comment by milindgoel15** [comment]
When you saw youtube disappeared, did u rebooted your device before it happened? @Veroxity

**Comment by Veroxity** [comment]
No

**Comment by milindgoel15** [comment]
Make sure you turned off auto updates globally in play store general settings and try using detach so ur play store doesn't remove vanced. [Guide for detach can be found here](https://telegra.ph/Troubleshooting-for-vanced-03-19#Detach)

**Comment by Veroxity** [comment]
Well i already turn off auto Updates on YouTube already so i don't think i need to do globally and i guess i'll try the detach

**Comment by milindgoel15** [comment]
Well, we recommend doing globally instead of only yt since many a times, the specific options for users don't work. But you can try what fixes for you
