### ISSUE TITLE
An easy way to queue videos

### ISSUE THREAD

**Issue by reinaldofox** [YTVanced/Vanced#756]
Would it be possible to implement a way to easily queue videos?
Like, when a video is playing you can select and mark others as next.
Just that would be incredible, but if there were a way to access this list to change the positions and remove some, it would be magical.
I know you can create a playlist and select it to play, but I’m talking about something more practical, like a session playlist.

Thanks in advance!

**Comment by milindgoel15** [comment]
Duplicate of #333
