### ISSUE TITLE
[Bug] Vanced auto crashing when ver >15.43.32, cant log in when ver <=15.43.32

### ISSUE THREAD

**Issue by bpersonick** [YTVanced/Vanced#759]
**Bug description**
On logging in wirh valid google credentials app crashes if >15.43.32 or gives cqnt login for <=15.43.32

**Variant**
Non-Root

**Vanced version**
15.x and 16.x

**Android version**
affects android 11, 9, 8, and 7 devices I have
taken from Android 7.0 device becaue its rooted but not bootloader unlocked so I use non-root vanced on it like I do on other affected devices

**Device**
Samsung Galaxy S10, Note 9, Note 8, Tab A 10.1 (2019)

**Steps to Reproduce**
Steps to reproduce the error:
1. Install Micro G, and set up to not be affected by battery optimizer or Data optimizer
2. Install Youtube Vanced  ver > or <= 15.43.32 for the different outcomes
3. Open the app
4. Click on '...'
5. sign in with your correct UN/PW
6. App crashes if > 15.43.32 or App gives cant login issue if <= 15.43.32
7. subsequnt re-open app crashes if > 15.43.32, or works wirhout account if <= 15.43.32

**Expected behavior**
Detailed error to help troubleshoot behavior would be nic3

_Attach images/videos if possible. These can be helpful in solving the issue._

I am headed out and will attach more info later today or tomorrow.

**Comment by milindgoel15** [comment]
Attach logcat

**Comment by bpersonick** [comment]
I could not see a way on mobile to upload a file, only an image, so I uploaded it from the image  uploader but its just a text file.


[logcat_2.txt](https://github.com/YTVanced/Vanced/files/6410789/logcat_2.txt)

**Comment by milindgoel15** [comment]
The logs says about network error. There also happens to be a whitelisting issue. 
- So did u check if official YouTube app works fine? 
- Did u tried reinstalling the latest version in correct order(microG first then Vanced)? 
- Does ur play store say that ur device is certified?(you can check this in play store > about)

**Comment by bpersonick** [comment]
On Sun, May 2, 2021, 1:28 AM Milind Goel ***@***.***> wrote:

> The logs says about network error. There also happens to be a whitelisting
> issue.
>
>    - So did u check if official YouTube app works fine?
>
>   Yes,  My apologies, my original bug noted this and I didn't have time to
post as much info ( I was closed because I pasted the log cat instead of
attaching)

>
>    - Did u tried reinstalling the latest version in correct order(microG
>    first then Vanced)?
>
>   Yes.  --  Again, my apologies, my original bug explained this as well.

  This is affecting multiple devices, and I have followed pinned comments
and vanced guide several times to try to fix them.

>
>    - Does ur play store say that ur device is certified?(you can check
>    this in play store > about)
>
> So I don't see an "about" when I click my account in play store on the
device I am on now.

I clicked "Manage account" and found "Trusted Devices" for that account,
and it shows all of my devices** that have the problems, including the one
I grabbed the logs from and the only working one (which is a rooted BL
Unlocked LGv40ThinQ running an ancient version of Vanced that I installed
through Magisk)

**(except my wife's phone which is on her account so its expected that it
wouldn't show there)


_____________

== Additional Info ==

All of these phones were running vanced since maybe March of 2020,

Several months ago, all of my devices stopped working ( retry connection to
internet).

Down detector showed YouTube having a problem in my area that went away
within a few hours, but I could only use normal app.

On 3 of 5 devices I tried updating the apps through vanced manager but
couldn't get to work and spent time following pinned messages trying to
troubleshoot and asking people for help on discord and Reddit (and just
being told to read the pins)

The two devices I never updated started working again with no further
issues of that sort. (There was a couple times it gave a black screen on
videos so I restarted app/ phone and got it working, and a few very rare
occasions where it would play an ad - I don't recall experiencing that in
the 6 months prior.)

So anyway, I stupidly installed the YouTube Music Vanced on one of the
working devices, YouTube and YouTube Music worked for about an hour than
gave the same internet issue.

So I un-installed YouTube Music, and then vanced worked correctly again for
about 12 hours (give or take) before permanently going into "no internet"
so I Uninstaller vanced and re-installed, and it is now giving the same
issues ad these other devices as described here.
_______

**Comment by milindgoel15** [comment]
![show me the screenshot of this page from your device](https://user-images.githubusercontent.com/45682747/116816102-38aca680-ab7e-11eb-88f5-254f9f2d4c53.png)

**Comment by bpersonick** [comment]
I have 3 of the 4 issue devices here, but only two have cell service, so pardon the need to take one of these photos as a photo from another of the devices to send it to you.

I just did a fresh run through of Uninstalling vanced through vanced manager, removing the microG account, clearing the cache, and app data on micro, and then Uninstaller micro G from vanced manager, then installing the latest Micro G through vanced manager, removing it from battery optimizer and allowing it to use data when data saver is on, then installing the newest Vanced, and adding my Google account, which lead to the same behavior as in the one the log cat came from as it's the only broken device I havent re-done recently, and behavior is the same.

I just wanted to be 100% positive that I'm giving you a full trial on every device I have with me this weekend to be through as possible for you. :)

Galaxy S10:


![Screenshot_20210502-180221_Google Play Store](https://user-images.githubusercontent.com/41927875/116829952-0d718980-ab75-11eb-8209-5298cefc0132.png)

Galaxy Note 9:

![Screenshot_20210502-180407_Google Play Store](https://user-images.githubusercontent.com/41927875/116829986-56c1d900-ab75-11eb-997f-23a47cdc4c43.jpg)

Galaxy Note 8 (No Internet right now!!)

![Uploading 16199950620403931439352977215079.jpg…]()

**Comment by milindgoel15** [comment]
Ok so let's try this other way. If you can, I am ready to personally assist you but we have to use other platform since talking on GitHub is kinda weird. If u are already on telegram, dm me on telegram @MilindGoel15

**Comment by bpersonick** [comment]
Thank you so much, I have messaged you on  Telegram
