### ISSUE TITLE
Random system crashes

### ISSUE THREAD

**Issue by x10102** [YTVanced/Vanced#76]
Sometimes when watching videos on YTvanced, my screen randomly goes black and my phone reboots. This hasn't happened to me with the regular youtube app yet. 

I'm running Resurrection Remix 8.6.1 with NoGravity kernel 1.5.5 on Poco F1

**Comment by milindgoel15** [comment]
more like a rom issue. please check If still happens on the latest version. We are closing this issue for now. Feel free to reopen if it still happens.
