### ISSUE TITLE
[Bug] writing a Comment

### ISSUE THREAD

**Issue by bosaad21** [YTVanced/Vanced#760]
After I wrote a comment and if I select it to copy or delete it.. big black screen will appear and blocked the keyboard as shown in the attached picture.

Device Samsung galaxy s21
Vanced 16.16.38

![Screenshot_20210501-225210](https://user-images.githubusercontent.com/71277632/116793842-df873900-aad1-11eb-9328-c0705a7bfd06.jpg)

**Comment by supernoodled** [comment]
This also happens to me. I believe it happens on every version that includes the new crappy comments where you have to re-enable the old good ones (so v15+?).

There's also an issue where replies to comments will randomly not work with an error, and same with reply to comment edits. It's completely random.

My device: (although I don't think it's needed tbh)
Phone: Galaxy S9 (Exynos)
Android: 10
YouTube Vanced: v16.16.38
Vanced MicroG: v0.2.18.210500

Here's some other screenshots of the highlight text problem:

![Screenshot_20210502-075152](https://user-images.githubusercontent.com/31737227/116805230-e12a1e80-ab1c-11eb-8693-208a5bec75fc.jpg)
![20210502_075208](https://user-images.githubusercontent.com/31737227/116805231-e25b4b80-ab1c-11eb-9a11-6cb7efc20e5d.jpg)

**Comment by gghhkm** [comment]
It's a stock issue, it even does it with gboard just not as bad.
![sscg](https://user-images.githubusercontent.com/72711094/116940928-b3d49200-ac3c-11eb-8d07-77ff7beb1ec3.jpg)
