### ISSUE TITLE
[Bug] Picture in picture mode bug

### ISSUE THREAD

**Issue by ManiaxXD** [YTVanced/Vanced#762]
**Bug description**
Whenever I go to home screen while playing any video picture in picture mode doesn't show up only sound of that video is audible. This started happening after my android 11 update

**Variant**
Non-Root

**Vanced version**
16.16.38 - Build - 01.51.00

**Android version**
Android 11.0 

**Device**
Vivo Z1 pro

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2. Click on any video 
3. Go to the home screen of phone

**Expected behavior**
After going to home screen a pip video should appear instead it shows nothing only sound is audible of that video 

_Attach images/videos if possible. These can be helpful in solving the issue._

**Comment by milindgoel15** [comment]
PIP is controlled by your ROM as youtube uses android native pip. Not vanced issue so please don't report pip related issues
