### ISSUE TITLE
[Bug] can't seem to pull down and refresh content on the home page

### ISSUE THREAD

**Issue by boyss180** [YTVanced/Vanced#763]
**Bug description**
I had the same issue!
Copy from Internet,
After installing the vanced 16.16.38, I can't seem to pull down and refresh content on the home page... pull down and refresh works on Explore, Subscriptions and Library, but  doesn't work on home page even if I exit the app, closing it and even clearing the
cache.Only solution now is go to vanced setting > ad setting > turn off general layout ad removal,it works, but its showing ads on homescreen.

**Variant**
Non-Root/Root

**Vanced version**
16.16.38

**Android version**
Android 11

**Device**
Samsung Galaxy A70

**Comment by milindgoel15** [comment]
Duplicate issue again #252
