### ISSUE TITLE
[Idea] Search feature for Settings / Vanced settings

### ISSUE THREAD

**Issue by shailesh1tripathi** [YTVanced/Vanced#767]
Include an option for  **Search** in settings.
![Settings search feature](https://user-images.githubusercontent.com/83244547/116837236-2c106880-abe7-11eb-9413-b814eb1d7b83.png)
**Consider this scenario:** The user only wants to turn on a _certain notification setting_. The easiest way would be to search for that particular notification item, find it in the results and turn it on. If you don’t have a search and have a very long list of categories, then the user needs to scan through every item inside of the categories to find the desired setting — which is tiresome.

![search](https://user-images.githubusercontent.com/83244547/116901720-e5a72200-ac57-11eb-813f-9cd98b8bf254.png)

Advantages:  1) YT vanced settings currently have 50+ options, a new user may face difficulties while looking for a specific option. 
2) It will save time for finding something specific.
3) Cleaner GUI.
4) In future, YT vanced will have more features causing increased number of options in settings. It will provide more convenience in future.

**Link suggested to get clear idea :** [uxdesign]( https://uxdesign.cc/designing-a-better-settings-page-for-your-app-fcc32fe8c724
)

**Comment by Harmonie666** [comment]
This would definitely be very practical 👍🏻

**Comment by JohnRTitor** [comment]
Don't close this you bot

**Comment by shailesh1tripathi** [comment]
They should add this feature of search, it will enhance Vanced app.

**Comment by shailesh1tripathi** [comment]
They should add this feature of search, it will enhance YT Vanced app.
