### ISSUE TITLE
[Idea] Force AVC as codec

### ISSUE THREAD

**Issue by AronNemeth2001** [YTVanced/Vanced#769]
I have multiple phones (none of them are rooted) and one of them is an Asus ZC520TL which has hardware support for VP9 but only up to 480p/30fps. The problem is, that Youtube insists using VP9 with all videos on that phone, but this means that 60fps vids stutter and  drop a lot of frames on this device because it doesn't actually support hardware playback for them. My other phone (Samsung J6) doesn't support VP9 so youtube just uses AVC and vids play back fine.

Since Vanced has a feature that forces the usage of VP9 regardless of hardware support, wouldn't it be possible to also and a function that forces VP9 off? It could help with phones that have limited VP9 support implemented, like the ZC520Tl i mentioned.

**Comment by gghhkm** [comment]
Click the shit out of about on Vanced settings
