### ISSUE TITLE
Doesn't work unless microG  settings window is  running in the background

### ISSUE THREAD

**Issue by Relected** [YTVanced/Vanced#77]
i use the latest version of everything, i don't have root, and Vanced doesn't work if vanced microG settings is not open at least once
i think its because microG doesn't auto start with Vanced

**Comment by gghhkm** [comment]
Have you tried to exclude microG from battery optimization?

**Comment by Relected** [comment]
> Have you tried to exclude microG from battery optimization?

yes

**Comment by gghhkm** [comment]
https://dontkillmyapp.com
