### ISSUE TITLE
[Bug] Persistent brigtness text

### ISSUE THREAD

**Issue by washichi** [YTVanced/Vanced#771]
**Bug description**
Brightness text overlay doesn't disappear. Also visible when in picture-in-picture mode.
When brightness is adjusted again a new text overlay will show over the persistent one, and fade away. (Expected behavior). 

**Variant**
Non-Root

**Vanced version**
16.02.35 - Build - 01.47.00
[Log](https://gist.github.com/washichi/7f3bc443bfd261577779ed5a9da5352b) 

**Android version**
Android 11

**Device**
OnePlus 7 Pro

**Steps to Reproduce**
Steps to reproduce the error:
[Investigating]

**Expected behavior**
Text overlay should fade out.

![Screenshot_20210503-211406_YouTube_Vanced](https://user-images.githubusercontent.com/9273670/116923036-66fdb500-ac56-11eb-8d68-efeb9f95d869.png)
Persistent brightness text overlay. In front of that the current brightness text overlay, which behaves normal.

**Comment by milindgoel15** [comment]
Update to the latest version (v16.16.38) of vanced before reporting issues. You are using old version
