### ISSUE TITLE
[Idea] Allow hiding pre-premiere items 2: electric boogaloo

### ISSUE THREAD

**Issue by zakius** [YTVanced/Vanced#772]
**Description**
Replace me with a clear and detailed description of the idea.

This annoying *feature" does nothing useful, only pollutes subscriptions feed with videos you can't watch yet so hiding these would be greatly appreciated

also the stale bot is just bad UX

**Comment by TheApexDoctor** [comment]
Dont talk to me or my stale bot ever again.

On a serious note, same. This is one of the more annoying features of premiere. What purpose does it serve, other than to make people come back to the YouTube app even more than they already do?

**Comment by gghhkm** [comment]
Not sure if this is possible, pretty sure that pre-premiere use the same thing as normal videos and in trying to hide pre-premiere it would just end up hiding all of the videos too. @KevinX8 should know for sure.

**Comment by Midnightmadwalk-coder** [comment]
> Not sure if this is possible, pretty sure that pre-premiere use the same thing as normal videos and in trying to hide pre-premiere it would just end up hiding all of the videos too. @KevinX8 should know for sure.

What's the meaning of the idea lol

**Comment by zakius** [comment]
> 
> 
> Not sure if this is possible, pretty sure that pre-premiere use the same thing as normal videos and in trying to hide pre-premiere it would just end up hiding all of the videos too. @KevinX8 should know for sure.

I don't know how much fiddling with the code is possible obviously, but these items have visible marks on them so some metadata is there

**Comment by KevinX8** [comment]
> > 
> > 
> > Not sure if this is possible, pretty sure that pre-premiere use the same thing as normal videos and in trying to hide pre-premiere it would just end up hiding all of the videos too. @KevinX8 should know for sure.
> 
> I don't know how much fiddling with the code is possible obviously, but these items have visible marks on them so some metadata is there

Let me introduce you to litho flattening https://fblitho.com/docs/view-flattening/, it turns everything into a single element 😄

**Comment by zakius** [comment]
doesn't sound like a good sign, at least not like something that can be done in less than a man-day on the UI level
and I'm assuming it's unlikely you'll do it on network level either meaning with the OG app structure it's unfeasible, thanks for letting me know anyway
