### ISSUE TITLE
[Bug] Link not opening in youtube post

### ISSUE THREAD

**Issue by AkashRahane** [YTVanced/Vanced#774]
**Bug description**
When we click on a link provided on YouTube post, it doesn't open it and throws an error "youtube can't open this link".

**Variant**
Non-Root

**Vanced version**
16.16.38

**Android version**
Android 11

**Device**
OnePlus 7

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2. Go on any channels community post which has a link mentioned
3. Click on the link and the error appears.

**Expected behavior**
After clicking on a link from a youtube post it should redirect to the link.

![Screenshot_20210504-205336](https://user-images.githubusercontent.com/82751683/117029206-0df85480-ad1c-11eb-8432-b647dabb2dfb.jpg)

**Comment by Lemmingskiller** [comment]
Have the same issue from the last update , posted a comment on YouTube in the video about the new app icon

**Comment by milindgoel15** [comment]
Disable official YouTube app from your device or change defaults to vanced opening links.

**Comment by milindgoel15** [comment]
Duplicate of #578

**Comment by Viom888** [comment]
I have a Simple Solution
1. Download "Android hidden Settings" app
2. Open the app and search for "default apps settings"
3. Tap "Opening links"
4. Scroll down to YouTube Vanced and tap on it
5. Tap on "Add link" and select all links below

Done 👍🏻
