### ISSUE TITLE
[Bug] Full screen closing immediately 

### ISSUE THREAD

**Issue by Mimicthis** [YTVanced/Vanced#775]
**Bug description**
When I open a video and then do the pull up gesture to open open it in the horizontal full screen it exits from the full screen. 

**Variant**
Non-Root

**Vanced version**
16.02.35 - Build - 01.47.00 Latest

**Android version**
Android 11

**Device**
Samsung Galaxy S10 Plus 

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2. Click on tap on any video
3. No slide your finger up on the video while it in the vertical way and it shall transform into horizontal video and exit immediately. 

**Expected behavior**
When doing the finger up gesture the video shall go from the vertical to horizontal, it does but then goes back fast to vertical mini view.

**Comment by Mimicthis** [comment]
I do not know how to attach a video of the error. Please guide me.

**Comment by Mimicthis** [comment]
[Video link](https://files.fm/u/pmnjg23g3)

**Comment by Mimicthis** [comment]
[![Watch the video](https://files.fm/u/pmnjg23g3)](https://files.fm/u/pmnjg23g3) 
         ^                      ^                  |Video
         |                       |Thumbnail
         |

**Comment by milindgoel15** [comment]
v16.16.38 is the latest version of vanced. For the issue, clear data or try reinstalling. Other than that, we can't do anything about it
