### ISSUE TITLE
[Idea] Use a regular share menu

### ISSUE THREAD

**Issue by derekantrican** [YTVanced/Vanced#776]
When sharing a video from the YouTube app (and YouTube Vanced), the share menu is a custom share menu and for some reason, seems to randomly arrange apps (after the first 7 or so, depending on the apps installed on your phone) in the share menu whenever it is shown. This makes it really difficult to find the app you want to share to when it seems to jump around every time (for instance - I save YouTube videos to Pocket a lot from the Vanced app and I have to scan through the share menu every time to find where the Pocket icon has been placed in the share menu each time).

This feature request is to have YouTube Vanced use a normal share menu that you might typically see (where you can long-press an app to pin it to the top).

**YouTube/YouTube Vanced current share menu** (triggered 3 times in a row on the same video to show the "randomness" of the layout - the top 7 seem to be the same, but the rest are unpredictable after that):

![image](https://i.imgur.com/hgpYWZF.png)

**A typical share menu** (this one taken from Google Keep):

![](https://i.imgur.com/JMOy0ga.png)

**Comment by derekantrican** [comment]
I don't like stalebot

**Comment by derekantrican** [comment]
So is this "won't fix", then?

**Comment by gghhkm** [comment]
It's a Google thing, you'd have to go ask them to change it.

**Comment by dp876** [comment]
I installed vanced today on a amazon kindle tablet. The share menu had the option to pin apps & in vanced it showed the explorer button (trending tab) instead of the shorts button... so it's definitely a google thing...
