### ISSUE TITLE
[Bug] incognito mode

### ISSUE THREAD

**Issue by mahmoudalali2** [YTVanced/Vanced#777]
**Bug description**
when turn on incognito mode, and get out of the app, then reenter it, it keep closing up by itself

**Variant**
Non-Root

**Vanced version**
16.16.38 - Build - 01.51.00

**Android version**
Android 10.0

**Device**
Xiaomi MI 8

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2. Click on 'turn on incognito'
3. Close the app
4. Open the app again

**Expected behavior**
app should work normally, but it tends to keep closing

**Comment by milindgoel15** [comment]
Provide logcat

**Comment by mahmoudalali2** [comment]
> Provide logcat

Sorry, how to do so??

**Comment by milindgoel15** [comment]
[Use this logcat guide](https://telegra.ph/How-to-logs-02-28)

**Comment by mahmoudalali2** [comment]
> [Use this logcat guide](https://telegra.ph/How-to-logs-02-28)

https://pastebin.com/AsRUvaRc
I hope i did it right!

**Comment by mahmoudalali2** [comment]
Thank you for replying,
Yes it still presist, how can i use scoop app?

**Comment by milindgoel15** [comment]
Please read the logcat guide above

**Comment by mahmoudalali2** [comment]
Sorry for the lateness,
I did install the 'scoop' app, and run the adb command, then reproduce the bug, but the scoop app still on 'no crashes yet'.

**Comment by milindgoel15** [comment]
Reinstall vanced and start with fresh download. Hopefully that should fix the issue for you
