### ISSUE TITLE
`Shorts` bottom tab menu can't be disabled

### ISSUE THREAD

**Issue by stagefright5** [YTVanced/Vanced#778]
**Bug description**

There is a new way to open shorts from the bottom nav bar.

![20210505_085559.jpg](https://user-images.githubusercontent.com/15051871/117093930-fb176b80-ad7f-11eb-915f-54ba37ab5cf5.jpg)

**Variant**
Non-Root

**Vanced version**
16.16.38

**Android version**
Android 11

**Device**
Samsung Galaxy M30s

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2. In the bottom nav bar, in place of trends, shorts is there

**Expected behavior**

There should be an option to hide the shirts bottom nav bar menu

**Comment by milindgoel15** [comment]
Not a bug. YouTube is now rolling new changes through server and it's not rolled out to everyone.

**Comment by vrindavan** [comment]
If this is server side, could it mean it can't be removed? @milindgoel15

**Comment by milindgoel15** [comment]
I can't confirm on this. Xfile might be able to remove it just like the create button but that will look really ugly seeing only 3 tabs on bottom. See lesser tabs on bottom half is not a good design according to material design guidelines. And having shorts tab doesn't hurt even.

**Comment by vrindavan** [comment]
To be honest is it not user preference? I think it is useful to many and useless to other half. Many people just open their feed, subs and library. I guess if we have an option to have personalized tabs at bottom it is going to be well and good. Shorts are fun for half and ruined experience for others. That is what I think at least.

**Comment by Ravi-Rajpurohit** [comment]
hoping to see a disable option for the shorts tab.

**Comment by stagefright5** [comment]
@milindgoel15 ,

> [...] that will look really ugly seeing only 3 tabs on bottom. See lesser tabs on bottom half is not a good design according to material design guidelines. And having shorts tab doesn't hurt even. 


First of all, this thing about the guideline is not true. See the below images (and go to this [link](https://material.io/components/bottom-navigation#usage) to read it for yourself)

![Screenshot_20210512-191112_Chrome.jpg](https://user-images.githubusercontent.com/15051871/117985495-5fc16000-b356-11eb-921d-05a20712c388.jpg)

![Screenshot_20210512-191201_Chrome.jpg](https://user-images.githubusercontent.com/15051871/117985529-694ac800-b356-11eb-9eaa-b4ae400330cb.jpg)


Besides that, I don't think anyone who uses the vanced apps, uses it particularly for the beautiful ui.

**Comment by milindgoel15** [comment]
I do know that guidelines says that the minimum tabs should be 3. My point was for people who prefer UI side by side with features. You might not know but there are many people. But leave it.

**Comment by vrindavan** [comment]
Accidentally clicking shorts tab is so bad 😂😶 even if we get tabs sorting in far future, it would be a life saver.

**Comment by vrindavan** [comment]
All closed? 🤔

**Comment by vrindavan** [comment]
@milindgoel15 > I can't confirm on this. Xfile might be able to remove it just like the create button but that will look really ugly seeing only 3 tabs on bottom. See lesser tabs on bottom half is not a good design according to material design guidelines. And having shorts tab doesn't hurt even. 

Did he deny?

**Comment by milindgoel15** [comment]
No, we are just closing issues which are not our priorities now. Also, we have all of this noted already. Don't worry. 
> Did he deny?
