### ISSUE TITLE
Question - mute vanilla youtube app notifications but keep vanced ones

### ISSUE THREAD

**Issue by stephen147** [YTVanced/Vanced#78]
What do I need to do in order to mute notifications from vanilla youtube but keep the ones from vanced.

Under my apps I only have one YouTube app which funnily enough is the vanced logo. 

I cannot see the vanilla app to disable them.

**Comment by ZB4Rty** [comment]
**On a notification**
Touch and hold the notification, and then tap Settings .
Choose your settings:
To turn off all notifications, tap Notifications off.

**Comment by stephen147** [comment]
I should have mentioned that I've tried that. It's grayed out to turn off notifications for YouTube when I do this. Then in the app settings, there's YouTube with vanced logo. So I don't see any way to disable YouTube as they're not a separate app.

I'm using colour os on an oppo reno 5g phone.

**Comment by stephen147** [comment]
Sorted with solution above.
