### ISSUE TITLE
[Bug] calidad de video desaparece, queda en 480p

### ISSUE THREAD

**Issue by Deivid1409** [YTVanced/Vanced#781]
**Bug description**
Cuando abro un video este siempre está en calidad 480p y cuando subo la calidad a 1080p aparece que si se cambio pero se ve que no es así y cuando se intenta cambiar la calidad de nuevo, las opciones de 1080 y 720 ya no están disponibles así que el video queda en 480p

**Variant**
Non-Root

**Vanced version**
16.16. 38

**Android version**
Android 8.1.0

**Device**
Motorola G5s

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2. Click on video
3. Change quality
4. Up quality to 1080
5. See that the change is not made
6. Trying to change the quality again
7. The Qualities of 720 and 1080 no longer appear
8. The video defaults to 480p

**Expected behavior**
I expected the video quality to rise to 1080 but instead the 1080p option disappeared and the video was 480p

_Attach images/videos if possible. These can be helpful in solving the issue._
![Screenshot_20210505-110957](https://user-images.githubusercontent.com/83719050/117174318-353e3880-ad93-11eb-8f88-64114102e263.png)
![Screenshot_20210505-111003](https://user-images.githubusercontent.com/83719050/117174320-366f6580-ad93-11eb-8f49-b757ab07ddd5.png)
![Screenshot_20210505-110934](https://user-images.githubusercontent.com/83719050/117174323-3707fc00-ad93-11eb-920b-3d24b8546fd9.png)
![Screenshot_20210505-110942](https://user-images.githubusercontent.com/83719050/117174326-37a09280-ad93-11eb-9539-74a22f1316fa.png)
![Screenshot_20210505-110949](https://user-images.githubusercontent.com/83719050/117174328-38392900-ad93-11eb-9439-af1be12a5927.png)

**Comment by X1nto** [comment]
We don't speak Spanish
