### ISSUE TITLE
Preferred Video Quality bug

### ISSUE THREAD

**Issue by kamal-tech** [YTVanced/Vanced#783]
As I'm a data restricted guy, so this feature was amazing for me. It helped me save data by not automatically load into full resolution. But after the update 16.14.34 it doesn't work. It now loads video in full resolution. I have to manually lower the resolution in every video I play, it's disturbing. Although youtube also provide this option but it also is useless.

**Comment by milindgoel15** [comment]
Update to v16.16.38
