### ISSUE TITLE
[Idea] Option to Remove Explore tab option from bottom bar

### ISSUE THREAD

**Issue by TheApexDoctor** [YTVanced/Vanced#784]
**Description**
Would love to remove the cancerous discover/explore page from bottom of the app bar. I absolutely hate it, and never actually use it. A toggle/option to disable it would be incredible. Thank you for your work, and i really hope to see this implemented soon!

Reference images:
![Screenshot_20210506-131033](https://user-images.githubusercontent.com/83751499/117256979-2a57d680-ae6d-11eb-981e-54f994e2df0c.jpg)

**_This is from another older app, (InstaMod I think is the name) whereby the implementation can be seen:_**

![Screenshot_20210506-131200](https://user-images.githubusercontent.com/83751499/117256992-2deb5d80-ae6d-11eb-8a63-f0a4363a8178.jpg)
![Screenshot_20210506-131155__01__01](https://user-images.githubusercontent.com/83751499/117256995-2e83f400-ae6d-11eb-9dc1-5ec8296f84e8.jpg)

**Comment by gghhkm** [comment]
#334
