### ISSUE TITLE
[Bug] offline after close app

### ISSUE THREAD

**Issue by kikuKeii** [YTVanced/Vanced#786]
**Bug description**
if I open the app there is a message that you are offline. And to fix it I have to open microG from vanced. It's very troublesome when I click on video links from social media and have to do that.
If this is not a bug how can I fix it? I have done to not-battery optimization for vanced and microG. Or are there any settings for the device I use?

**Variant**
Non-Root

**Vanced version**
16.16.38

**Android version**
Android 10.0

**Device**
Infinitx Note 8

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2. Offline message

https://user-images.githubusercontent.com/60594222/117299358-a882a000-aea2-11eb-8c47-ab53a744ef25.mp4

**Comment by milindgoel15** [comment]
Read vanced [troubleshooting guides](https://telegra.ph/Troubleshooting-for-vanced-03-19#B:-Offline-or-connect-to-internet-error) or previous issues before creating a duplicate again

**Comment by hJDajn99** [comment]
What's the solution?

**Comment by milindgoel15** [comment]
Read the first comment in this issue and your solution is right there in it.

**Comment by Aldmors** [comment]
the solution in the troubleshooting guide does not work for me :( 
My device: ZTE Nubia Z17 Lite

**Comment by milindgoel15** [comment]
You are required to read every solution listed under login issues. If they do not work, there's nothing we can do. Switch to root version or switch ROMs which doesn't kill apps for their own good.

**Comment by Kitty769** [comment]
> Read vanced [troubleshooting guides](https://telegra.ph/Troubleshooting-for-vanced-03-19#B:-Offline-or-connect-to-internet-error) or previous issues before creating a duplicate again

Can't open troubleshoot guides

**Comment by milindgoel15** [comment]
> Can't open troubleshoot guides

open the link in browser.

**Comment by Kitty769** [comment]
> > Can't open troubleshoot guides
> 
> open the link in browser. https://telegra.ph/Troubleshooting-for-vanced-03-19#B:-You-are-Offline-and-connect-to-the-internet-error

still unable to open, it would say that the site can't be reached
![image](https://user-images.githubusercontent.com/95062313/143582397-30aded36-9e85-4519-b90c-3bfb309f08fa.png)

**Comment by milindgoel15** [comment]
> still unable to open, it would say that the site can't be reached

Then your internet provider probably banned telegraph in your region. Try using a VPN. Otherwise I will paste the solution here.
