### ISSUE TITLE
[Idea] Bring back the old, verbose, quality settings

### ISSUE THREAD

**Issue by sam-cross** [YTVanced/Vanced#790]
**Description**
The new YouTube updates have changed the video quality settings from exact resolutions to a very simple choice between 3 options. It's awful.

Is there any way Vanced could get the old quality options back? If so, maybe a toggle could be added in the settings to switch between the two - although I don't see many people using the god awful new implementation.

Thanks for the excellent work guys!

**Comment by domwrap** [comment]
I was directed to Vanced from MKBHD's tweet on this matter yet after install found the same crappy options and couldn't specify resolution as I was led to believe. Have removed Vanced from my device as this was the reason for installing but didn't have what I expected. Hope this can be added and you'll pick up a user and supporter.

**Comment by tomjschwanke** [comment]
I heard setting a preferred resolution in vanced settings overrides the new stuff

**Comment by milindgoel15** [comment]
Use vanced preferred quality options to override the new quality preferences. You need to be on version 16.16.38 to be able to override successfully.
