### ISSUE TITLE
[Bug] When doing superchat, says "Sorry, this link cannot be opened"

### ISSUE THREAD

**Issue by doonoo** [YTVanced/Vanced#792]
**Bug description**
![Screenshot_20210508-002624](https://user-images.githubusercontent.com/18385494/117526589-37231a00-af94-11eb-9c77-146e8281eb59.jpg)

**Variant**
Non-Root

**Vanced version**
16.16.38

**Android version**
Android 10

**Device**
Samsung Galaxy Note S9

**Steps to Reproduce**
Just go to any random live and test out superchat and see if you can replicate the same effect.

**Expected behavior**
My money in that person's chat

_Attach images/videos if possible. These can be helpful in solving the issue._

**Comment by milindgoel15** [comment]
Use official YouTube or root version when you are joining membership or donating to your favorite youtubers.
