### ISSUE TITLE
[Bug] Miniplayer disappears from screen if moved from original position.

### ISSUE THREAD

**Issue by Stagmattica** [YTVanced/Vanced#793]
If I enter my Start screen fron YouTube Vanced, the active playback get shrunk to a Mini Player. However, unlike in previous versions, this miniplayer disappears from the screen when moved anywhere on the screen. Playback continues because the audio is still active but the player is invisible.

Device: Samsung Galaxy A50 (EU)
Android version 11 / OneUI 3.1

If you have any further questions, please feel free to ask them.

**Comment by milindgoel15** [comment]
What miniplayer are u talking about?

**Comment by Stagmattica** [comment]
> 
> 
> What miniplayer are u talking about?

The one that appears if you exit/back out of the app while a video is currently playing.

**Comment by AceMuffins** [comment]
I'm pretty sure they mean the PiP mode. Regardless, I'm having the exact same issue.

Device: Xiaomi Redmi Note 7
Android Version 11, MSM-Xtended (Custom ROM)

**Comment by Stagmattica** [comment]
> 
> 
> I'm pretty sure they mean the PiP mode. Regardless, I'm having the exact same issue.
> 
> Device: Xiaomi Redmi Note 7
> Android Version 11, MSM-Xtended (Custom ROM)

Yes, that's what I meant. Thank you

**Comment by Stagmattica** [comment]
I would also like to add that this never occurred in older versions (updated from 16.02.35 directly to latest, it worked fine in 16.02.35).

**Comment by milindgoel15** [comment]
Pip issues are not related to vanced as YouTube uses native pip. So please don't report pip issues
