### ISSUE TITLE
[Bug] Links 

### ISSUE THREAD

**Issue by GooseTheDuck** [YTVanced/Vanced#796]
**Bug description**
When trying to open youtube.com links youtube vanced isn't an option

**Variant**
Non-Root

**Vanced version**
16.16.38 - Build - 01.51.00

**Android version**
Android 11

**Device**
Samsung Galaxy A21s

**Steps to Reproduce**
Steps to reproduce the error:
1. Try to open a youtube.com (make sure there is no default)
2. A pop-up box appears
3. Youtube vanced isn't an option 

**Expected behavior**
Youtube vanced should be an option.

![Screenshot_20210509-091726_Android System](https://user-images.githubusercontent.com/73031433/117562881-dfc39d80-b0aa-11eb-9cd7-63a6da2f1039.jpg)

**Comment by milindgoel15** [comment]
Please read out [vanced faq](https://play.google.com/store/apps/details?id=com.vanced.faq) before creating issues which are already addressed.

**Comment by GooseTheDuck** [comment]
Oh, Sorry my bad
