### ISSUE TITLE
[Idea] Hide watched video from Recommendations feed

### ISSUE THREAD

**Issue by theblackhole** [YTVanced/Vanced#798]
**Description**
This issue [has been known for a long time](https://support.google.com/youtube/thread/4244145/watched-videos-keep-coming-up-how-can-i-stop-that?hl=en) and I think it's by design: YouTube keeps recommending videos I've already watched. 

Sometimes it's only one or two videos: it's ok, I just ignore it (or to the tedious "hide" > "I've already watched this video").
But there are days when my feed is full of videos I don't care since I've already watched them and it's very frustrating.

Since Google doesn't do anything about it, maybe Vanced could add an option to hide these videos if you can access the "video watched" flag

**Comment by milindgoel15** [comment]
That issue is youtube end to deal with.

**Comment by pl4nty** [comment]
This is pretty trivial to implement with a browser extension on desktop, is there a reason it's out of scope for Vanced?

**Comment by milindgoel15** [comment]
Extensions doesn't work on yt client. They are for browsers
