### ISSUE TITLE
[Bug] YouTube drains battery

### ISSUE THREAD

**Issue by mchoubby** [YTVanced/Vanced#799]
**Bug description**
After using youttube and place it in the background i get a warning from the system that YouTube vanced is draining battery 

**Variant**
Non-Root

**Vanced version**
16.14.34

**Android version**
Android 1

**Device**
Oneplus 7 pro

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2. Use it
3. Open another app or lock on the phone
4. 20 min or 1 hour later i get the message

**Expected behavior**
Should stop using the cpu if not used

![Screenshot_20210509-173901~2](https://user-images.githubusercontent.com/15172350/117584160-d104d700-b0fa-11eb-926c-083c5fa23e6d.jpg)

**Comment by milindgoel15** [comment]
Using old version, use latest v16.16.38 before reporting any issues
