### ISSUE TITLE
[Bug] community Tab doesnt work

### ISSUE THREAD

**Issue by Karam-DEV** [YTVanced/Vanced#80]
This message appears when switching to the "Community" tab.
![Screenshot_2020-10-10-07-05-58-021_com vanced android youtube](https://user-images.githubusercontent.com/60565100/95645379-16aae400-0ac7-11eb-8e09-b9fd4366cd4f.png)

I am using latest version of youtube vanced and microg.
My device is: Mi pad 4

**Comment by milindgoel15** [comment]
Please update to the latest version v16.16.38 if you haven't already. We are closing this issue. If you are still facing issue, feel free to reopen
