### ISSUE TITLE
[Bug] HDR Max Brightness toggle not working

### ISSUE THREAD

**Issue by Shotgat** [YTVanced/Vanced#800]
**Bug description**
HDR videos will increase screen brightness, but toggling the HDR Max Brightness toggle off does not have any effect on HDR videos hijacking brightness, even after force closing and restarting app.

**Variant**
Non-Root

**Vanced version**
16.16.38 - Build - 01.51.00

**Android version**
Android 11

**Device**
Samsung Galaxy S10+ Snapdragon

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2. Navigate to YouTube Vanced Settings > Misc > HDR Max Brightness > toggle it off
3. Play an HDR video

**Expected behavior**
HDR should be disabled/brightness control should not be hijacked by video.

_Attach images/videos if possible. These can be helpful in solving the issue._

**Comment by milindgoel15** [comment]
Using old version, use latest v16.16.38 before reporting any issues

**Comment by Shotgat** [comment]
> 
> 
> Using old version, use latest v16.16.38 before reporting any issues

Sorry, I forgot to edit the version, it actually is the latest version. 16.16.38, can you please reopen

**Comment by milindgoel15** [comment]
Ok known issue

**Comment by milindgoel15** [comment]
It has been fixed internally so please wait for future updates. Closing this issue for now.
