### ISSUE TITLE
Loop button issue

### ISSUE THREAD

**Issue by pAterion** [YTVanced/Vanced#801]
With the new update in Vanced music, I need to click every time to replay the music , in the old version it was automatic for each song once I did it. i don't want to click every time. Now when i download old versions of vanced music or MicroG i stiil need to click everytime to loop botton, not same as before. SM Galaxy J7 Pro - Non Root

**Comment by milindgoel15** [comment]
Update to v4.25.52 if you haven't as it's [working fine](https://imgur.com/a/jK27JEE) as it should. Try clearing out app data and retry. We are closing this issue for now. If you are still facing issues, feel free to reopen and provide screen recording of your issue
