### ISSUE TITLE
[Idea] Not so light text in dark mode (black)

### ISSUE THREAD

**Issue by Xitee1** [YTVanced/Vanced#802]
**Description**
In the dark mode (black) the text is too light. It should be more gray or customizable to better read the texts.

Example:

Without feature:
![Screenshot_20210510-115038_YouTube](https://user-images.githubusercontent.com/59659167/117642368-7d8c9a80-b187-11eb-9d72-d48434986dfb.png)

With this feature (I'm not that good at photo editing, only pay attention to the white text):
![feature implemented](https://user-images.githubusercontent.com/59659167/117642484-9d23c300-b187-11eb-8590-91b8749ef587.png)

I only made a example with the settings, but it should also be implemented for video titles, comments and more.

**Comment by milindgoel15** [comment]
It would look so bad imo.
