### ISSUE TITLE
[Bug] 2160p 60 fps replaced automatically to 480p

### ISSUE THREAD

**Issue by steakhutzeee** [YTVanced/Vanced#804]
**Bug description**
Selecting 2160p 60 fps as preferred resolution does not work. Videos start at that resolution and just drop at 480p soon after. Trying to change res manually but maximum res selectable is 480p. This happens also with standard YouTube app, maybe it's still useful post it here. 

**Variant**
Non-Root

**Vanced version**
v16.16.38

**Android version**
10

**Device**
Xiaomi Mi 9T

**Steps to Reproduce**
Steps to reproduce the error:
1. Select 2160p as preferred resolution
2. Open a video

**Expected behavior**
Reproduce video at 2160p

**Comment by milindgoel15** [comment]
If it happens in YouTube, then it's YouTube issue, not vanced
