### ISSUE TITLE
[Bug] Lossy Audio

### ISSUE THREAD

**Issue by Yonle** [YTVanced/Vanced#808]
# Bug description
Very Lossy audio output in YT Vanced than non-vanced ones

## Variant
Non-Root

## Vanced version
16.02.35 

## Android version
Android 8.1

## Device
Vivo 1820

## Steps to Reproduce
Steps to reproduce the ~~error~~ bug:
1. Open the app
2. Watch Any Video (Or [this](https://youtu.be/SoSL5ujNmqA) one)

## Expected behavior
A lossy audio will happend.

**Comment by milindgoel15** [comment]
Invalid bug report as the OP is using old versions. Closing issue
