### ISSUE TITLE
Vanced (magisk root) disappears after reboot

### ISSUE THREAD

**Issue by BananaKillr** [YTVanced/Vanced#81]
Happens every time I reboot my oneplus 8 (OOS 10). Doesn't revert back to regular Youtube, just gets completely uninstalled.

EDIT: Updated to OOS 11 and now it just crashes after a reboot

**Comment by kodithegreat** [comment]
Same here
Pixel 3XL
Magisk Root
Android 11

**Comment by EL-S** [comment]
Mine is reverting back to regular YouTube on reboot and I have to uninstall and reinstall vanced in the manager.

Mi Mix 2
Magisk Root
Android 9

**Comment by EL-S** [comment]
I'm still having this problem after every single reboot, any one have any solution?

**Comment by milindgoel15** [comment]
The issue has already been fixed. Please use the latest vanced manager if you all aren't using it yet. We are closing this issue. Feel free to reopen if anyone has any queries. 
You all can also refer to #123
