### ISSUE TITLE
[Idea] Autoplay option to repeat(loop) same video.

### ISSUE THREAD

**Issue by nikk16** [YTVanced/Vanced#811]
Using the same **_Autoplay Next Video_** button at the top of the video to repeat the current video instead of the next video by providing an option in the Autoplay menu in settings to pick whether Autoplay plays the **_next_** video or **_repeats_** the same video. Please see the two images below.
.
.
![V01](https://user-images.githubusercontent.com/69586590/118035350-bba4dc80-b388-11eb-8a68-619b44982e6d.png) 

![V02](https://user-images.githubusercontent.com/69586590/118036130-ce6be100-b389-11eb-8286-cd8784850966.png)

**Comment by milindgoel15** [comment]
Use the auto repeat function from vanced Settings > misc dammm

**Comment by nikk16** [comment]
The feature im requesting is a repeat button on the video screen. Usually repeat is not kept on all the time, so need a quick way to turn it on or off. The autoplay settings part is optional in order to use the same button as autoplay. But a separate button is fine too. BTW thanks to the DEVS for making this app.

**Comment by milindgoel15** [comment]
the repeat button when enabled is displayed right in the YT player overlay. please look into settings instead of ignoring them.

**Comment by nikk16** [comment]
Ya sorry, I found it after I posted a reply.
But i would still prefer it being added to the autoplay setting menu.
Thanks anyway.
