### ISSUE TITLE
Connect to the internet

### ISSUE THREAD

**Issue by OmarAlG** [YTVanced/Vanced#812]
**connect to the internet**
When i open YouTube vanced, it says connect to the internet.
I tried uninstalling it many times and install again with no luck.

**Variant**
Non-Root/Root

**Vanced version**
16.16.83 - Build - 01.51.00

**Android version**
Android 11.0 - Pie

**Device**
Samsung Galaxy S21 ultra

**Comment by milindgoel15** [comment]
[Read this for all fixes regarding offline errors](https://telegra.ph/Troubleshooting-for-vanced-03-19)
