### ISSUE TITLE
[Bug] replaceme

### ISSUE THREAD

**Issue by LenaZarou** [YTVanced/Vanced#813]
**Bug description**
The app won't connect to the internet. Everything else in my phone is connected except for vanced YouTube and vanced music

**Variant**
Non-Root/Root

**Vanced version**
16.02.35 - Build - 01.47.00

**Android version**
Android 9.0 - Pie

**Device**
Xiaomi Redmi 8

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
3. ....

**Expected behavior**
Replace me with a description of what you expected should happen and what happened instead.

_Attach images/videos if possible. These can be helpful in solving the issue._

**Comment by milindgoel15** [comment]
Invalid report as the OP is using older version. Please update to latest v16.16.38 before creating any issue on this repository. Check out [vanced troubleshooting](https://telegra.ph/Troubleshooting-for-vanced-03-19) if you have any other trouble
