### ISSUE TITLE
[Idea] Youtube Shorts, Stories For Tablets

### ISSUE THREAD

**Issue by Bulamadim** [YTVanced/Vanced#815]
Youtube hasn't been bringing stories and shorts to tablets for a long time. It comes when the lowest resolution is 580, but the screen becomes smaller. I believe the Vanced makers can fix this.

![PicsArt_05-13-08 29 35](https://user-images.githubusercontent.com/84147300/118163017-20fcda00-b42a-11eb-8831-d49eb0c56b9a.jpg)

**Comment by Bulamadim** [comment]
Why closed? Explain to me...

**Comment by Bulamadim** [comment]
> what are you even asking for, I've never seen it add giant black bars before

I want Youtube Short videos and stories feature to be added for tablets. It is simple to understand ...

**Comment by milindgoel15** [comment]
It is a youtube/Google thing to do, not us. We don't own YouTube, Google own it. Ask them

**Comment by Bulamadim** [comment]
> It is a youtube/Google thing to do, not us. We don't own YouTube, Google own it. Ask them

Is it too difficult to add this to tablets? Also, what does it have to do with buying Youtube? Don't you read the requests here to add them to Vanced?
