### ISSUE TITLE
[Bug] Bluetooth play/pause on headset not working

### ISSUE THREAD

**Issue by padrespeaks** [YTVanced/Vanced#816]
Since a couple of days ago, the Bluetooth operability with my Sony WH-CH700N headset doesn't work with YT Vanced. It also doesn't work with YouTube as well. The device pairs with each of the devices listed below without issue. Moreover, Bluetooth operability with other apps (VLC, podcast addict, etc.) remains working. 

My Bluetooth headset allows for play/pause, scroll forward and back in a playlist. This used to work in YT Vanced, it doesn't work anymore.

Non-Root

**Vanced version**
16.02.35 - Build - 01.47.00

**Android version**
Android 9.0 - Pie

Pixel 5
Samsung Tab A

Steps to reproduce the error:
1. Open YT Vanced
2. Turn headset on
3. Pair to device
4. Load any YT video
5. Press play/pause on headset

Video is supposed to pause and stay paused unless the button is pressed again or play is tapped in app

_Attach images/videos if possible. These can be helpful in solving the issue._

**Comment by AmineDjeghri** [comment]
I have the same issue with the SoundCore life q30

**Comment by gghhkm** [comment]
Update to 16.16.38 first.
Also if it's not working with stock as well then your going to want to take it up with Google.

**Comment by padrespeaks** [comment]
Please reopen.

I have updated all vanced programs to latest, and can repeat the issue. Load vanced, load video, play/pause does not work.

The only way it works is when I press and hold play/pause, and google assistant pops up. if I close the assistant app, then controls work.

I think I his begs further investigation and I'm willing to help with providing any information requested.

**Comment by padrespeaks** [comment]
Downgrading to 15.04.54 solves Bluetooth navigation issue and Chromecast issue.
