### ISSUE TITLE
[Bug] when attempting log in it doesn't do anything 

### ISSUE THREAD

**Issue by Patrickgrims** [YTVanced/Vanced#818]
**Bug description**
When attempting to sign in it shows the "add account" button but when pressed nothing happens, thus not allowing me to sign in

16.16. 38

**Android version**
Android 9.0 - Pie

**Device**
Samsung Galaxy S20 fe

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2. Click on profile bubble at top right corner 
3. Click sign in
4. Click add account 

**Expected behavior**
A box to either enter email address or a list of accounts on the phone

**Comment by milindgoel15** [comment]
Did u install vanced microG?

**Comment by Patrickgrims** [comment]
Ah I should have known I'd missed something. All sorted
