### ISSUE TITLE
[Idea] add 2.25x, 2.5x, 2.75x and 3x playback speed

### ISSUE THREAD

**Issue by SpacEagle17** [YTVanced/Vanced#82]
It would be very useful if this feature would be added, because some videos are quite long or the youtuber is talking very slowly and 2x isn't fast enough. Thanks and vanced is awesome!

**Comment by Vasilich1234** [comment]
I have the same requeste

**Comment by gghhkm** [comment]
#238

**Comment by Isssuemaker** [comment]
Please use this idea

**Comment by Isssuemaker** [comment]
Please increase the playback speed

**Comment by Isssuemaker** [comment]
Please many peoples are requesting this feature

**Comment by notDevagya** [comment]
+1

**Comment by jonandeva** [comment]
Why is this suggestion closed with no discussion? Looks like it's been suggested at least 8 times. 

I was also thinking maybe there could be an advanced YouTube Vanced setting where your could choose what does options are available to you.

**Comment by AbdulMalikDev** [comment]
Please reopen this

**Comment by maddada** [comment]
Really need this feature! 2x is not enough :\

**Comment by debrotam** [comment]
Please reopen this issue and implement this change! Custom playback speeds would be really convenient and useful for a number of users, myself included. @milindgoel15

**Comment by milindgoel15** [comment]
@debrotam We already have this suggestion on our list. Xfilefin had tried to implement this way back but it wouldn't work at that time. Please keep patience until xfilefin finds a way to implement this. It might or might not get implemented so please don't force or beg again and again for this. 

Opening this issue won't speed up any development. After all, we work on vanced as a hobby. Once we have any positive updates on this, we will update here with the new information.
