### ISSUE TITLE
[Bug] No Information and Direct Crash

### ISSUE THREAD

**Issue by Bulamadim** [YTVanced/Vanced#820]
Youtube Vanced closes without any message / information. Normal Youtube did not have this problem.

Non-Root

v16.16.38

Android 7.0 - Nougat

Casper Via A1 (Yes, a little known brand :))

Steps to reproduce the error:
1. Open the app.
2. Wait 5 minutes.
3. Direct no inf. crash...

**Comment by milindgoel15** [comment]
Attach a logcat

**Comment by Bulamadim** [comment]
> Attach a logcat

This is what you are talking about;  I recorded until the vanced crashed...

**Comment by milindgoel15** [comment]
>https://www.mediafire.com/file/tflvmowb0o4o8ue/logcat_05-15-2021_16-38-19.txt/file

27mb logs? Are u insane. Please extract logs from vanced app only. We don't need your whole system bug report.

Use [this guide](https://telegra.ph/Bug-Reports-10-17#How-to-get-logs) if you don't know how to get.

**Comment by Bulamadim** [comment]
> > https://www.mediafire.com/file/tflvmowb0o4o8ue/logcat_05-15-2021_16-38-19.txt/file
> 
> 27mb günlükler? Sen deli misin Lütfen günlükleri yalnızca gelişmiş uygulamadan çıkarın. Tüm sistem hata raporunuza ihtiyacımız yok.
> 
> Nasıl alacağınızı bilmiyorsanız [bu kılavuzu](https://telegra.ph/Bug-Reports-10-17#How-to-get-logs) kullanın .

I understood after I wrote the article, I came to edit what I wrote, you wrote the answer. I'll do it again and filter it to show only the errors ...

**Comment by Bulamadim** [comment]
By the way, could you remove the first link from your message?

**Comment by milindgoel15** [comment]
Could you use the scoop app from the guide given?

**Comment by Bulamadim** [comment]
> Could you use the scoop app from the guide given?

not seeing scoop crashes?  I can't do the 1st method, I don't have my pc.

**Comment by milindgoel15** [comment]
The issue is indeed caused by your device. Tho the error you logs gave doesn't cause crash. Try updating Google play services app if it's on older version. Other than that, we would be needing logs using scoop app

**Comment by Bulamadim** [comment]
OK thanks. I don't like using the old version. And I'll try again with Scoop.

**Comment by Bulamadim** [comment]
> > https://www.mediafire.com/file/tflvmowb0o4o8ue/logcat_05-15-2021_16-38-19.txt/file
Remove this link please...

**Comment by Bulamadim** [comment]
Dude, don't you have an alternative to me other than scoop?

**Comment by gghhkm** [comment]
> Dude, don't you have an alternative to me other than scoop?
> I reinstalled Vanced and MicroG from scratch, it didn't fix...

Use this version of scoop https://f-droid.org/packages/taco.scoop
 it's a fork created by a Vanced member.

Here's how you set up on non-root device's.
https://github.com/TacoTheDank/Scoop/wiki

**Comment by milindgoel15** [comment]
> Dude, don't you have an alternative to me other than scoop?

We have but then you don't have a PC. We cannot tell you solutions when there's no useful logs. The logcat reader app didn't gave much useful logs which could help. Could u tell what link you used to download vanced? And what method of installation?

**Comment by milindgoel15** [comment]
> Use this version of scoop https://f-droid.org/packages/taco.scoop
>  it's a fork created by a Vanced member.
> 
> Here's how you set up on non-root device's.
> https://github.com/TacoTheDank/Scoop/wiki

It's the same I share with everyone lol. Missed the logcat guide of mine?

**Comment by Bulamadim** [comment]
> > Dude, don't you have an alternative to me other than scoop?
> > I reinstalled Vanced and MicroG from scratch, it didn't fix...
> 
> Use this version of scoop https://f-droid.org/packages/taco.scoop
> it's a fork created by a Vanced member.
> 
> Here's how you set up on non-root device's.
> https://github.com/TacoTheDank/Scoop/wiki

Sorry, it didn't work ...

**Comment by Bulamadim** [comment]
> > Dude, don't you have an alternative to me other than scoop?
> 
> We have but then you don't have a PC. We cannot tell you solutions when there's no useful logs. The logcat reader app didn't gave much useful logs which could help. Could u tell what link you used to download vanced? And what method of installation?

Thank you for the help, I understand the challenge of your job... 
 Yes, I don't have a PC, it broke but I installed TWRP before it broke.  Is there anything I can do with TWRP?  
 I downloaded the Manager from the official site, and Vanced and Micro G from it.  
 Soon I will also share logs from other CatLog and MatLog applications.  
 There may be misconceptions because I wrote it from the translation...

**Comment by milindgoel15** [comment]
It's not a job. We are just volunteers here.
> Thank you for the help, I understand the challenge of your job... 

Alright, so as per logs from matlog, could you tell does your device have Google play services or microG core? Because such logs says one of the API (phenotype API is not available on your device which likely caused the crash.  [2021-05-18-22-15-12MatLog.txt](https://github.com/YTVanced/Vanced/files/6508644/2021-05-18-22-15-12MatLog.txt)

**Comment by Bulamadim** [comment]
> It's not a job. We are just volunteers here.
> 
> > Thank you for the help, I understand the challenge of your job...
> 
> Alright, so as per logs from matlog, could you tell does your device have Google play services or microG core? Because such logs says one of the API (phenotype API is not available on your device which likely caused the crash.

I don't really understand what you're saying (like the phenotype api).  Yes, there are Play Services and MicroG.

I think we can't solve my question.  I will try, if I solve it, I will write.

**Comment by milindgoel15** [comment]
>  Yes, there are Play Services and MicroG.

You say that your device have both play services and original microG. By microG, we mean the original microG and not the vanced microG. Could u pls confirm what u have

**Comment by Bulamadim** [comment]
> > Yes, there are Play Services and MicroG.
> 
> You say that your device have both play services and original microG. By microG, we mean the original microG and not the vanced microG. Could u pls confirm what u have

I downloaded MicroG from Vanced Manager so I'm using Vanced MicroG, if I got it...` (if it's wrong, blame the translation 🤐)`

**Comment by milindgoel15** [comment]
Ok it seems like whatever your device have prebuilt, has one of the APIs missing which causing crash or its just microG which doesn't have the necessary api code causing crash. Either way you have to wait for updates on microG. Till then, you can only use old versions.

**Comment by Bulamadim** [comment]
> Ok it seems like whatever your device have prebuilt, has one of the APIs missing which causing crash or its just microG which doesn't have the necessary api code causing crash. Either way you have to wait for updates on microG. Till then, you can only use old versions.
> 
> We are closing this issue. If you have any questions, feel free to ask.

Ok, Thank You...
