### ISSUE TITLE
[Idea] Add a "Layout Setting" to replace new "Shorts" shortcut with the old "Explore" shortcut

### ISSUE THREAD

**Issue by derekantrican** [YTVanced/Vanced#821]
Now with the new YouTube Shorts, the Vanced app has a "Shorts" icon where "Explore" used to be. This is a request for a layout setting to revert this.

![image](https://user-images.githubusercontent.com/1558019/118337946-c4e99280-b4c9-11eb-96b6-2f6376e48092.png)

**Comment by milindgoel15** [comment]
Duplicate of #778
