### ISSUE TITLE
[Bug] Some videos won't play (possibly CDN issue)

### ISSUE THREAD

**Issue by Ashish0804** [YTVanced/Vanced#822]
**Bug description**
Some videos won't play on wifi and require switching to mobile data and vice versa. To be clear i do not mean that all the videos in that timeframe won't play, i simply mean that 1 particular video won't play. 
This issue is related to https://github.com/yt-dlp/yt-dlp/issues/3 imo.

Here's what @pukkandan had to say about that issue (tho keep in mind that i am not 100% this is the same issue):

> This issue is its very nature is not reproducible. It happens when the URL YouTube gives is broken in your local CDN. It will work from other regions. It will also work after some time once the cdn fixes the issue. 
> The ideal solution would be to fetch multiple URLs for each format and then try them one by one

I think somehow when modifying the app, the line that is responsible for trying next urls got removed or bypassed.

I face this issue 1-2 a day but maybe that's because i watch too much yt. Here's a video i faced this issue today as well
https://www.youtube.com/watch?v=KMca2R5EiA4 

**Variant**
Non-Root

**Vanced version**
16.16.38
**Android version**
Android 11

**Device**
Samsung Galaxy S10 Lite

**Steps to Reproduce**
Steps to reproduce the error:
well that's the problem, it can' be reproduced by anyone else but the one facing this issue on that particular video.

**Expected behavior**
The expected behavior is that vanced skips that url and plays the next one.

_Attach images/videos if possible. These can be helpful in solving the issue._

Here are the videos.
[1.mp4 ](https://drive.google.com/file/d/1Bs-x2JJH9THwD8NUdvxUU7klIS8GhOLr/view?usp=sharing)shows that the video doesn't start playing, also shows that rest of the videos play implying nothing is wrong with wifi. When i switch to mobile data, it plays. It also shows i am using latest vanced and microg.
[2.mp4](https://drive.google.com/file/d/1WJ0-dn8RDaNW9D0ULkKwp0RDQTFn8jrn/view?usp=sharing) shows that the video doesn't load on wifi when the buffer loaded with mobile data has been used. It also shows speedtest while the video still doesn't load in popup player. But again loads with mobile data.
Here's the url of video that's not playing https://www.youtube.com/watch?v=xQvTJG7DSR8

**Comment by Ashish0804** [comment]
I have added the videos and link that's not working
also see in the image that the same video is working on desktop with same network again proving the issue lies with vanced

https://imgur.com/DXbgsh9.png

**Comment by milindgoel15** [comment]
Saying that the videos work on desktop and not on vanced doesn't necessarily mean it's a vanced issue. Please don't put your claim without checking it on official YouTube app from play store(we will assume you haven't tried it because you never mentioned it anywhere in ur issue) and vanced is made on top of stock yt code. As far as the issue is concerned, all your videos which you linked plays absolutely fine for us. So what u need to do now is

1. Use official yt app on same phone and test all these videos on that. If it gives the same issue, it's your software problem. If it's not, follow 2

2. Try the same videos on another phone on again both official yt and vanced. If it happens there on both apps, then it's most likely YouTube end issue. If it happens on only vanced just like ur main phone, then report back.

A very important note: the official YouTube app must be of the same version as Vanced is. Otherwise this issue will be closed right away.

**Comment by Ashish0804** [comment]
@milindgoel15 here u go
[3.mp4](https://drive.google.com/file/d/1GnJ9bJ7T-rB26vhi3Cf8sUtOgPbRVtod/view?usp=sharing) shows video working on offcial yt app but not on vanced running on same network and device. 
I asked a friend running latest vanced aswell and it works for him. He is on nonrooted aswell.

**Comment by milindgoel15** [comment]
That's weird. It's either youtube server issue or just a broken installation. Try reinstalling vanced

**Comment by Ashish0804** [comment]
> That's weird. It's either youtube server issue or just a broken installation. Try reinstalling vanced

Reinstalling didn't help. And this is technically youtube server issue but practically it isn't. Vanced should skip the url if its not responding. See the quote in original post. 

Since vanced is not open source, i don't know what changes devs have made and therefore can't suggest a concrete solution.

**Comment by milindgoel15** [comment]
I did check your quoted issue and logs you shared in yt dl repo which says that network is unreachable. This clearly means it's an issue with network.
![5159.png](https://user-images.githubusercontent.com/45682747/118370067-964fe280-b5c3-11eb-9efa-7c9a74a85c2d.png)

If you get us a logcat just when the issue happens, would be great.

**Comment by Ashish0804** [comment]
> This clearly means it's an issue with network.

ofc it's a network issue, but not issue with my wifi. It's something at cdm level from YT. But the point still remains that vanced should skip url after a couple of seconds.

I do not have any way of testing another wifi network. 

Battery optimizations have nothing to do with this.

Also i am more than happy to help, what is logcat? If it's an android app then please provide the link and i'll send the logs.

Do keep in mind tho i am running android 11 and i think there are some restrictions on what network traffic other apps can monitor.

**Comment by milindgoel15** [comment]
[Use this app and get the logcat using the bugreport template](https://play.google.com/store/apps/details?id=com.vanced.faq)

Yea battery optimization probably wouldn't have anything to do with this issue but it doesn't hurt to try?  I mean it's only you with this issue until now so how do we say it's vanced issue for sure? Dev's can't fix something they can't reproduce on their end. Even your friend doesn't have the issue.
