### ISSUE TITLE
[Idea] Remove YouTube analytics on links

### ISSUE THREAD

**Issue by shazgames** [YTVanced/Vanced#823]
**Description**
Whenever I click on external site link, YouTube redirects me firstly on their analytics service links instead site I want to open

**Comment by LaundryHamper** [comment]
It's doing something weird with deep links, too - I use Flynx as my default browser (tragic, I know) and for whatever reason it isn't offered as a link handler for whatever YT is doing when you click something that's meant to be ordinary http. Other browsers are all listed.

**Comment by milindgoel15** [comment]
Refer #1012 from now on as that is better written.
