### ISSUE TITLE
[Bug] I do not receive any notification from Vanced, only official youtube 

### ISSUE THREAD

**Issue by Xyphoseos** [YTVanced/Vanced#827]
This happen only on this phone, all my others work perfectly

**Bug description**
No notification push (yes, yes, I read all issue here, Vanced guide, tried some trick on internet, GSM Statue connected...)

**Variant**
Non-Root

**Vanced version**
16.02.35 - Build - 01.47.00

**Android version**
Android 10

**Device**
Samsung Galaxy A20e

**Comment by milindgoel15** [comment]
Invalid report as the user is using old version. Check [vanced guides](https://play.google.com/store/apps/details?id=com.vanced.faq) for help. Meanwhile we are closing this issue

**Comment by Xyphoseos** [comment]
Which old version ? I dont know about the build written (i did not check) but I am updated on my phone
Im not using an old

**Comment by Xyphoseos** [comment]
As written
Vanced guide ALREADY checked.
