### ISSUE TITLE
[Bug] YouTube Vanced not being consistently paused by pressing play/pause button on bluetooth headphones.

### ISSUE THREAD

**Issue by Flawless1337** [YTVanced/Vanced#828]
**Bug description**
Video will sometimes be paused when the pause button is pressed, other times it does not work. This has to be an defect on your app, because when I use the pause function of my Bluetooth headphones in Spotify it always works. Just thought you guys would like to know and if there's a fix to have a more consistent pausing experience.

**Variant**
Non-Root

**Vanced version**
16.16.38  - Build - 01.51.00

**Android version**
Android 11 

**Device**
Google Pixel 3A 

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2. View multiple videos pausing using the pause function of Bluetooth headphones for a hour or more
3. Count how many times, if any, how many times the pausing using Bluetooth headphones actually worked. 

**Expected behavior**
Videos should be consistently paused when using pause function on Bluetooth headphones.

_Attach images/videos if possible. These can be helpful in solving the issue._

**Comment by milindgoel15** [comment]
Did you check the issue with official YouTube app? Please check there first before reporting here

**Comment by Flawless1337** [comment]
> Did you check the issue with official YouTube app? Please check there first before reporting here
 Yes I have checked in the official YouTube app. The Bluetooth pause consistency appears to be even worse than on Vanced. I assume their is no fix for this issue than am I correct?

**Comment by Flawless1337** [comment]
Ggg

**Comment by milindgoel15** [comment]
It's an issue with YouTube then.

**Comment by Flawless1337** [comment]
> It's an issue with YouTube then.

Alright makes sense, thanks.
