### ISSUE TITLE
[Bug] I do not receive any notification from Vanced, only official youtube

### ISSUE THREAD

**Issue by Xyphoseos** [YTVanced/Vanced#831]
This happen only on this phone, all my others work perfectly

Bug description
No notification push (yes, yes, I read all issue here, Vanced guide ALREADY CHECKED, tried some trick on internet, GSM Statue connected...)

Variant
Non-Root

Vanced version
16.16.38

Android version
Android 10

Device
Samsung Galaxy A20e

**Comment by milindgoel15** [comment]
Please do not create duplicate issues. We know that you still face it and you should reopen the already made issue instead of making a new one. But anyways keep this in mind from next time as GitHub does have an option to reopen issues. 

Now show us the screenshot of both Google device registration and google cloud messaging.

**Comment by Xyphoseos** [comment]
![Screenshot_20210517-164457_Vanced microG](https://user-images.githubusercontent.com/20702083/118508235-49891a80-b72f-11eb-8147-eecd45f38237.jpg)
![Screenshot_20210517-164451_Vanced microG](https://user-images.githubusercontent.com/20702083/118508242-4aba4780-b72f-11eb-8329-10cd152884ba.jpg)

**Comment by milindgoel15** [comment]
Hmm okay. Did you change the pong interval? Disabled battery optimization for microG using dontkillmyapp guide?

**Comment by Xyphoseos** [comment]
Yes ofc

**Comment by milindgoel15** [comment]
If you have done everything including battery optimization, wait for a week till it starts to work for you. Otherwise root version is the only option for you.

**Comment by Xyphoseos** [comment]
This mobile isnt rooted
Cant this be solved by an update of the app ?

**Comment by milindgoel15** [comment]
Thats not our problem
> This mobile isnt rooted

Nope, it can never. It's called Non-Root for reason as it doesn't use Google play services. Notification work on non root except that your os doesn't want you to receive them.
> Cant this be solved by an update of the app ?
