### ISSUE TITLE
[Question] YT Music Crowdin link

### ISSUE THREAD

**Issue by Martin5001** [YTVanced/Vanced#832]
Hi, is there a Crowdin project for YouTube Music too? I'd like to join. (The recently added mods are missing translation. Would love to help with that.)
(And maybe put all the Crowdin links somewhere here on GitHub so we don't have to spam with these questions again?) Thanks :)

**Comment by Harmonie666** [comment]
Translating is a waste of time. Having only english language is perfectly fine. 
If one doesn't even understand basic english, they shouldn't use the internet.

**Comment by Martin5001** [comment]
> If one doesn't even understand basic english, they shouldn't use the internet.

It's not only about understanding. For example I understand it but still don't like having the app in two languages. It just doesn't look good. And I don't think we're here to judge, just give me the link :)

**Comment by milindgoel15** [comment]
We do not provide translation for YouTube music as it is not our main project. Maybe we will do in future, maybe not.

**Comment by Martin5001** [comment]
> We do not provide translation for YouTube music as it is not our main project. Maybe we will do in future, maybe not.

Ok, thanks

**Comment by gghhkm** [comment]
> Translating is a waste of time. Having only english language is perfectly fine.
> If one doesn't even understand basic english, they shouldn't use the internet.

I'm banishing you to China. 😈
