### ISSUE TITLE
[Bug] Subtitles (CC) don't work

### ISSUE THREAD

**Issue by Mimicthis** [YTVanced/Vanced#834]
Hello, the subtitles (CC) have stopped working in all videos. 

**Variant**
Non-Root

**Vanced version**
16.16.38

**Android version**
Android 11

**Device**
Samsung Galaxy S10 Plus 

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2. Click on video
3. Turn on (CC) 
4. It won't show you any (CC) 

**Expected behavior**
The subtitles shall show is they're already there automatically generated or not. 

_Attach images/videos if possible. These can be helpful in solving the issue._

**Comment by milindgoel15** [comment]
Not vanced bug. Videos which doesn't have subtitles in the first place will not generate some special subtitle for you. Subtitles are added by youtubers, not app. Check official YouTube or desktop site before creating such issues here

**Comment by Mimicthis** [comment]
I'm talking about videos that support CC!

**Comment by milindgoel15** [comment]
Send those video links you are referring that has subtitled baked

**Comment by Mimicthis** [comment]
You know what. I've checked they all work now as they should, I had to clear cache of the app. Just a question, why are subtitles coming from the left side, why aren't they in the center?

**Comment by milindgoel15** [comment]
Another YouTube side thingy. When they appear on left, they are basically adapting it to the video parts. For more information, check on Google.
