### ISSUE TITLE
[Bug] root version video stops playing when screen is off for 4\9 minutes

### ISSUE THREAD

**Issue by hareluyagod** [YTVanced/Vanced#838]
**Bug description**
[Bug] video stops playing every time when screen is off for 4\9 minutes, and I tried several other vanced build the bug still goes

**Variant**
Root

**Vanced version**
Latest

**Android version**
Android 10 

**Device**
One plus 7pro

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
3. ....

**Expected behavior**
Replace me with a description of what you expected should happen and what happened instead.

_Attach images/videos if possible. These can be helpful in solving the issue._

**Comment by milindgoel15** [comment]
Disable battery optimization for vanced using [this guide](https://dontkillmyapp.com/oneplus)
