### ISSUE TITLE
[Bug] Setting scrolling behaving oddly 

### ISSUE THREAD

**Issue by Mimicthis** [YTVanced/Vanced#84]
There's a new bug when going into settings, it keeps scrolling to the top and I can't tap on the Vanced settings if I immediately scroll down. I need to wait 2-3 seconds to scroll down, but even then sometimes it scrolls to the top by itself. If you need some more info about this,I'll try to explain more. Tnx!

**Comment by VancedOfficial** [comment]
No need to explain more, I know exactly what you mean and know it's annoying. Unfortunately that bug is also in the official YouTube so it's a problem for them to fix.

**Comment by milindgoel15** [comment]
Please update to the latest v16.16.38 release if you haven't already. We are closing this issue, Feel free to reopen if you still face an issue.
