### ISSUE TITLE
[Bug] Brightness Banner Persists

### ISSUE THREAD

**Issue by arnavjindal** [YTVanced/Vanced#841]
**Bug description**
The Brightness banner doesn't disappears. Occurs very rarely. Have to clear the app from background and open again to fix the issue. This banner still persist even after changing the video or re-opening the same video. Usually happens when opening a video and changing the brightness(through swipe), doing this very rapidly. This has happened to me 3-5 times. 

**Variant**
Non-Root

**Vanced version**
16.16.38

**Android version**
Android 11 

**Device**
OnePlus 8T

**Steps to Reproduce**
Happens randomly. 

**Expected behavior**
Brightness banner should disappear after changing brightness. 

![Screenshot__brightness_banner](https://user-images.githubusercontent.com/26025037/118976772-0333f580-b993-11eb-97d0-7aea1f84a6c4.jpg)

**Comment by washichi** [comment]
Can confirm this bug. 
Issued on older version: https://github.com/YTVanced/Vanced/issues/771
