### ISSUE TITLE
[Idea] YTM is lacking a search function for the library

### ISSUE THREAD

**Issue by Harmonie666** [YTVanced/Vanced#842]
YouTube Music doesn't have a search function for every section of the library. Not in playlists, albums, etc.
None of the sections provide a search feature, if I wanted to search for a specific track, playlists, album, artist, etc within my library.
![Screenshot_20210520-195746254 (1)](https://user-images.githubusercontent.com/73917917/119026792-dc32ef00-b9a5-11eb-8f7a-1dc46c7c3244.png)

My suggestion is that Vanced team could add a search function for every one of these library sections, so the user will be able to find things quicky.

![Screenshot_20210520-195602264 (1)](https://user-images.githubusercontent.com/73917917/119026953-0edce780-b9a6-11eb-8e47-9e8f83ceb237.png)

Thank you for reading, and I hope you will have the possibility and time to implement this idea.

**Comment by milindgoel15** [comment]
It's a youtube thing to add. Ask Google

**Comment by Harmonie666** [comment]
> It's a youtube thing to add. Ask Google

Are you saying it's technically not possible for the Vanced devs? Could you please go in detail, for me to understand it properly?
"Ask Google" like they care about our opinions, or would even consider doing it.

**Comment by milindgoel15** [comment]
YouTube or any of its apps is not open source. You can't code something in the app which doesn't have the code available for it. The change you are requesting has to be added by Google themselves because they have the original code.

**Comment by Harmonie666** [comment]
> YouTube or any of its apps is not open source. You can't code something in the app which doesn't have the code available for it. The change you are requesting has to be added by Google themselves because they have the original code.
> 
> Ofc decompiling is an option but it's not practical in real to implement something natively imo

I was just wondering how the dev Oizaro added several great mods to YTM recently, and why you're saying this idea is not possible. I mean it would be great, if it atleast could be looked into, in terms of decompiling, but if it's too hard to get it done... :/

**Comment by gghhkm** [comment]
> > YouTube or any of its apps is not open source. You can't code something in the app which doesn't have the code available for it. The change you are requesting has to be added by Google themselves because they have the original code.
> > Ofc decompiling is an option but it's not practical in real to implement something natively imo
> 
> I was just wondering how the dev Oizaro added several great mods to YTM recently, and why you're saying this idea is not possible. I mean it would be great, if it atleast could be looked into, in terms of decompiling, but if it's too hard to get it done... :/

Oizaro decompiled and modified a few things that were already there and added a little bit of extra functionality. 
What you're asking for would require the devs to reverse engineer whole sections of the app which is a difficult and tedious process and would require the addition of alot.
Even the main app is barely reverse engineered so going that far for a side project is understandably overboard.

**Comment by Harmonie666** [comment]
Thanks for clarifying that. I just pray that Oizaro finds the motivation to implement more difficult tasks, and features to YTM. I really love the recently added features, and I strongly believe that it shouldn't be seen as "just a side project".
YTM is a decent music streaming service, and IMHO better than most others, such as Spotify, and many more.
The potential is there, and the Vanced version with the features is already superior to the stock YTM app. 
Thanks for sharing your thoughts, and investing your time into these projects 🙏🏻
