### ISSUE TITLE
I am using root vanced version when i finish seeing a video and close the player the playstore automatically opens because i have applocked playstore i can immediately press back button to stay on vanced please solve this issue using latest version device redmi note 6 pro tulip [Bug] replaceme

### ISSUE THREAD

**Issue by SalehAhmedShakib** [YTVanced/Vanced#844]
**Bug description*
I am using root vanced version when i finish seeing a video and close the player the playstore automatically opens because i have applocked playstore i can immediately press back button to dtay on vanced please solve this issue using latest version device redmi note 6 pro tulip

**Variant**
Root

**Vanced version**
16.16.38 - Build - 01.51.00

**Android version**
Android 9.0 - Pie

**Device**
Redmi Note 6 Pro Tulip

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2. Click on a video finish watching it or make it finish
3. Playstore opens automatically

**Expected behavior**
it opens automatically ask permission to open Playstore but when i give it permission to open it doesn't open Playstore 

_Attach images/videos if possible. These can be helpful in solving the issue._

**Comment by milindgoel15** [comment]
That's a device side issue. Unfortunately, we can't fix device side issues. If you could see when the problem started to happen, consider doing basic troubleshooting from that point of time.
