### ISSUE TITLE
[Idea] Optimization

### ISSUE THREAD

**Issue by GKid94** [YTVanced/Vanced#845]
Optimize the app for this phone

Device Info 3.1.3
Date Created 2021-05-21 07:04:32

Device
--------------------------------------------------------
Device Name : Galaxy A5
Model : SM-A500FU
Manufacturer : samsung
Device : a5ulte
Board : MSM8916
Hardware : qcom
Brand : samsung
Build Fingerprint : samsung/a5ultexx/a5ulte:6.0.1/MMB29M/A500FUXXU1CRH1:user/release-keys
USB Host : Not Supported

System
--------------------------------------------------------
Android Version : 6.0.1
Version Name : Marshmallow
Released Date : October 05, 2015
Code Name : Marshmallow
API Level : 23
Security Patch Level : 2017-08-01
Bootloader : A500FUXXU1CRH1
Build Number : MMB29M.A500FUXXU1CRH1
Baseband : A500FUXXU1CRF1
Java VM : 2.1.0
Kernel : 3.10.49-14143416
Language : English (en_US)
OpenGL ES : 3.0
Root Access : No
Root Management Apps : No Apps Detected
SELinux : Enforcing
Google Play Services : 21.18.15 (040306-373409449)
Vulkan : Not Supported
Treble : Not Supported
Seamless Updates : Not Supported

CPU
--------------------------------------------------------
SoC : Qualcomm Snapdragon 410 (28 nm)
4 x Cortex-A53 (1.2 GHz)
Processor : ARMv7 Processor rev 0 (v7l)
CPU Architecture : 4 x 1.19 GHz
Supported ABIs : armeabi-v7a, armeabi
CPU Hardware : Qualcomm Technologies, Inc MSM8916
CPU Type : 32 Bit
CPU Governor : interactive
Cores : 4
CPU Frequency : 200 MHz - 1190 MHz
GPU Renderer : Adreno (TM) 306
GPU Vendor : Qualcomm
GPU Version : OpenGL ES 3.0 V@140.0 AU@ (GIT@Ia10634f51b)

Battery
--------------------------------------------------------
Health : Good
Level : 51%
Status : Discharging
Power Source : Battery
Technology : Li-ion
Temperature : 33 ℃
Voltage : 3667 mV

Network
--------------------------------------------------------
Type : Wi-Fi
IP Address : 192.168.1.101
Gateway : 192.168.1.1
Subnet Mask : 255.255.255.0
DNS1 : 203.0.113.2
DNS2 : 203.0.113.3
Lease Duration : 7 Seconds
Interface : tun0
Link Speed : 72 Mbps
Frequency : 2437 MHz

Display
--------------------------------------------------------
Resolution : 720 x 1280 Pixels
Density : 320 dpi (XHDPI)
Font Scale : 1.0
Physical Size : 4.97 inches
Refresh Rate : 60.0 Hz,
HDR : Unknown
HDR Capabilities : Unknown
Brightness Level : 7%
Brightness Mode : Adaptive
Screen Timeout : 600 Seconds
Orientation : Portrait

Memory
--------------------------------------------------------
Random Access Memory
------------------
Type : LPDDR3 533 MHz
Total : 1892.0MB
Available : 476.0MB
Used : 1427.0MB
Used Percentage : 74%

System Storage
------------------
Total : 2.31GB
Available : 0.11GB
Used : 2.20GB
Used Percentage : 95%

Internal Storage
------------------
Total : 11.54GB
Available : 1.48GB
Used : 10.06GB
Used Percentage : 87%

External Storage
------------------
Total : 14.45GB
Available : 14.25GB
Used : 0.20GB
Used Percentage : 1%

Camera
--------------------------------------------------------
Camera - 0
------------------
Position : Back
Mega Pixels : 12.8 MP
Resolution : 4128x3096
Focal Length : 3.69mm

Camera - 1
------------------
Position : Front
Mega Pixels : 5.0 MP
Resolution : 2576x1932
Focal Length : 1.92mm

Thermal
--------------------------------------------------------
tsens_tz_sensor0 - 58 ℃
tsens_tz_sensor1 - 57 ℃
tsens_tz_sensor2 - 54 ℃
tsens_tz_sensor4 - 60 ℃
tsens_tz_sensor5 - 59 ℃
pm8916_tz - 52.8 ℃
pa_therm0 - 37 ℃
rt5033-fuelgauge - 33.6 ℃
battery - 33.6 ℃

Sensors
--------------------------------------------------------
BMC150 Acceleration Sensor
------------------
Vendor : Bosch Sensortec
Type : ACCELEROMETER
Power : 0.13mA

BMC150 Magnetic Sensor
------------------
Vendor : Bosch Sensortec
Type : MAGNETIC FIELD
Power : 6.0mA

BOSCH Uncalibrated Magnetic Sensor
------------------
Vendor : Bosch Sensortec
Type : MAGNETIC FIELD UNCALIBRATED
Power : 6.0mA

TAOS TMD3782 Prox Sensor
------------------
Vendor : AMS , Inc.
Type : PROXIMITY
Power : 0.75mA

TAOS TMD3782 Light Sensor
------------------
Vendor : AMS , Inc.
Type : LIGHT
Power : 0.75mA

Screen Orientation Sensor
------------------
Vendor : Samsung Electronics
Type : PRIVATE SENSOR
Power : 0.13mA

Samsung Geomagnetic Rotation Vector Sensor
------------------
Vendor : Samsung Electronics.
Type : GEOMAGNETIC ROTATION VECTOR
Power : 6.13mA

Orientation Sensor
------------------
Vendor : Samsung Electronics.
Type : ORIENTATION
Power : 6.13mA

Apps
--------------------------------------------------------
9GAG
com.ninegag.android.app
Version : 6.104.02r23913-bb3d5863f2

AirAttack 2
com.ArtInGames.AirAttack2f
Version : 1.4.2

Antivirus Free
com.bitdefender.antivirus
Version : 3.133.939

Authenticator
com.blizzard.bma
Version : 2.5.0.14

Authenticator
com.azure.authenticator
Version : 6.2105.3004

Authy
com.authy.authy
Version : 24.3.8

Autodesk SketchBook
com.adsk.sketchbook
Version : 5.2.3

Background Eraser
com.handycloset.android.eraser
Version : 2.7.1

Blokada
org.blokada.fyra
Version : 4.11.1

Bounce
com.genico.bounce
Version : 1.1.4

Brave
com.brave.browser
Version : 1.24.85

Chess
com.jetstartgames.chess
Version : 2.7.7

Device Info
com.ytheekshana.deviceinfo
Version : 3.1.3

Discord
com.discord
Version : 73.12

Downloader for Instagram
instasaver.instagram.video.downloader.photo
Version : 1.25.2

Downloader for TikTok
com.downloaderfor.tiktok
Version : 1.77

Google Play services for Instant Apps
com.google.android.instantapps.supervisor
Version : 6.14-release-367282920

Headset Notifier
org.nocrew.tomas.headsetnotifier
Version : 1.1.0

Instagram
com.instagram.android
Version : 188.0.0.35.124

LED Blinker Lite
com.ledblinker
Version : 8.1.3-lite

LightSaber
com.pombingsoft.lightsaber
Version : 3.1

Lite
com.facebook.lite
Version : 251.0.0.4.119

Ludo Club
com.moonfrog.ludo.club
Version : 2.1.5

Meme Generator Free
com.zombodroid.MemeGenerator
Version : 4.6050

Messenger Lite
com.facebook.mlite
Version : 139.0.0.3.118

Microsoft SwiftKey Keyboard
com.touchtype.swiftkey
Version : 7.7.9.3

Moj Telenor
rs.telenor.mymenu
Version : 1.24

Moja mBanka
rs.Raiffeisen.mobile
Version : 18.0.2

Neuralyzer
com.thunkable.android.kechkoindustries.neuralyzer
Version : 2.2

Polish
photo.editor.photoeditor.photoeditorpro
Version : 1.34.88

Radio Uzivo Srbija
net.radioexpert.radio.uzivo
Version : 1.3.6

Shazam
com.shazam.android
Version : 11.25.0-210506

Speedtest
org.zwanoo.android.speedtest
Version : 4.5.36

Start
com.vodafone.smhs
Version : 16.0.1

Steam
com.valvesoftware.android.steam.community
Version : 2.3.12

Streets of Rage
com.sega.streetsofrage.classic
Version : 6.2.0

TikTok
com.zhiliaoapp.musically
Version : 19.5.4

Twilight
com.urbandroid.lux
Version : 12.3

Vanced Manager
com.vanced.manager
Version : 2.6.0 (Crimson)

Vanced microG
com.mgoogle.android.gms
Version : 0.2.18.210500

Viber
com.viber.voip
Version : 15.3.0.2

Wallpaper Changer
de.j4velin.wallpaperChanger
Version : 4.8.15

Weather
ru.yandex.weatherplugin
Version : 11.25

XRecorder
videoeditor.videorecorder.screenrecorder
Version : 1.5.0.1

Yandex.Disk
ru.yandex.disk
Version : 4.86.1

YouCut - Video Editor
com.camerasideas.trimmer
Version : 1.454.1121

YouTube Vanced
com.vanced.android.youtube
Version : 16.16.38

**Comment by milindgoel15** [comment]
Apps can't fix your device issues. If your device lags from using apps, use basic or hardware supported codecs in vanced by using vp9 codec from vanced Settings > codec override. Other than that, there's no option for you other than to upgrade your phone.

**Comment by gghhkm** [comment]
We can't optimize an app we don't have source code too, go ask Google to do it.

**Comment by GKid94** [comment]
> We can't optimize an app we don't have source code to, go ask Google to do it.

Ok
