### ISSUE TITLE
[Bug] Can't play/pause/go-to-next/go-to-previous video using media keys on bluetooth keyboards.

### ISSUE THREAD

**Issue by xhiloh** [YTVanced/Vanced#848]
**Bug description**
When connected to a bluetooth keyboard(e.g., Logitech K780) which has media control keys(play/pause, next song, previous song, volume up, volume down), Youtube Vanced doesn't respond to play/pause, next song and previous song keys, but volume up/down. Other video players such as nPlayer or the official Youtube app on the same device responds to those keys.

**Variant**
Non-Root

**Vanced version**
16.16.38 - Build - 01.51.00

**Android version**
Fire OS 7.3.1.7 (based on Android 9 - Pie)
https://en.wikipedia.org/wiki/Fire_OS

**Device**
Amazon Fire HD 10 (9th Generation)

**Steps to Reproduce**
1. Connect a bluetooth keyboard (e.g., Logitech K780 or Satechi bluetooth media button) which has media control keys (play/pause, next song, previous song) to the device.
2. Open Youtube Vanced and play any video.
3. Press "play/pause", "next song" or "previous song" key on the connected bluetooth keyboard.

**Expected behavior**
Player should change the play/pause status, start playing the next song or playing the previous song according to the pressed key.

**Comment by milindgoel15** [comment]
Fire OS is not a supported platform! Use a real android device.
