### ISSUE TITLE
Vanced Music problems with AndroidAuto

### ISSUE THREAD

**Issue by josemariaaraujo** [YTVanced/Vanced#85]
Can you make Vanced Music compatible with Android Auto?
Youtube Music is compatible, but will only play on premium subscription. Without subscription it is visible to Android Auto but won't allow to play.
Vanced Music isn't visible by Android Auto. There is no icon, and no controls are presented. It will only play the audio if it is launched before and left on the background.

For testing you only need the Android Auto app, it can work in the phone by itself (no connection to car needed), it's just a simpler(=less distracting) interface to android

Thank you for all the good work!

**Comment by ismailiabderrahim** [comment]
you can have the icon of VYTM on Android auto by activating uknown source in Android Auto developper settings, you can look on YT on how to activate this, but it's also useless as VYTM is not working with Android Auto :(

**Comment by X1nto** [comment]
We don't accept yt music reports
