### ISSUE TITLE
Youtube Vanced cannot remember its position

### ISSUE THREAD

**Issue by TheProUser** [YTVanced/Vanced#850]
**Youtube Vanced version:** 
`16.16.38` (latest) 

**Vanced microG version:** 
`0.2.18.210500` (latest) 

**Issue:** 
If Youtube Vanced is killed in the background due to low ram availability, it does not remember where it was previously and restarts from the youtube home page. This issue does not happen if microG is uninstalled and Youtube Vanced perfectly remembers its previous position even if it gets refreshed.

**Comment by milindgoel15** [comment]
That's because your OS killed the process and it revives the whole app from the start. That's an intended behaviour and will happen with any app due to low RAM. Try disabling battery optimization for microG and see if it helps. Other than that, no solution
