### ISSUE TITLE
[Idea] YTM playlists/albums should skip disliked tracks

### ISSUE THREAD

**Issue by Harmonie666** [YTVanced/Vanced#855]
**Description**
If I dislike a track by taping thumbs down, it should be skipped when I play a playlist or album. I'm talking about playlists, that are created by YouTube, or community created ones. This would make the thumbs down button much more useful. Because if I dislike a track, I don't want it to play anymore.

![Screenshot_20210522-171941331 (1)](https://user-images.githubusercontent.com/73917917/119231680-6607c700-bb22-11eb-90b2-bb212584831c.png)

**Comment by jedenastka** [comment]
Vanced Music is not supported:
> Sorry, but we don't provide support for Vanced Music at this time as it is only a side project. Unless your bug breaks the main functionality, it will most likely not be fixed.

**Comment by milindgoel15** [comment]
That's a youtube thing to do. It's server controlled

**Comment by Harmonie666** [comment]
> That's a youtube thing to do as it's server controlled. We do not own youtube or its original code.

Got it. I thought you owned YouTube for a second.
