### ISSUE TITLE
[Idea] GeoLocation Removal

### ISSUE THREAD

**Issue by mhasammujahid** [YTVanced/Vanced#856]
**Description**
The vanced for yt music is blocked for Pakistan. Can you please remove the GeoLocation from yt music vanced app.
![Screenshot_20210523-021447_YouTube Music](https://user-images.githubusercontent.com/84644452/119240949-c0c61080-bb6c-11eb-9f63-1235443ddd44.jpg)

**Comment by milindgoel15** [comment]
It's youtube thing to do. Ask Google
