### ISSUE TITLE
[Idea] Add in-app closed caption preset

### ISSUE THREAD

**Issue by MrExquisite** [YTVanced/Vanced#858]
**Description**
Add an option in the settings to enable/disable closed captions in-app. Currently closed captions are enabled automatically if accessibility is turned on even if Android's subtitle setting is off.
Would work like a preset for the CC button in the video option overlay.

**Comment by milindgoel15** [comment]
Please try [this guide](https://telegra.ph/Vanced-FAQ-08-31#Captions). If it doesn't work for some reason, then google can definitely help you.
