### ISSUE TITLE
[Idea] Volume Booster/Equalizer

### ISSUE THREAD

**Issue by Bulamadim** [YTVanced/Vanced#860]
**Description**
We want Youtube Vanced with volume booster feature and equalizer feature... There are examples in the pictures. It would be better if you do "Ses Yükseltici" in Turkish :) ...
![Setting](https://user-images.githubusercontent.com/84147300/119265336-03303180-bbef-11eb-9163-5803d15a8e8d.jpg)
![2](https://user-images.githubusercontent.com/84147300/119265390-32df3980-bbef-11eb-915f-ae73f9e28ea9.jpg)
![3](https://user-images.githubusercontent.com/84147300/119277506-ce40d080-bc28-11eb-9033-272f94e07edf.jpg)

**Comment by Bulamadim** [comment]
Photos good :)...

**Comment by milindgoel15** [comment]
Refer #1143 from now on.
