### ISSUE TITLE
[Idea] filter and something

### ISSUE THREAD

**Issue by john5521** [YTVanced/Vanced#865]
Thank you for this wonderful app.
I'm using google translate. Please forgive me for bad English.

Description
Filter live chat / comments / search results by mute word and channel
Change member name color in live chat
Filter non-member chats
Disable ad blocking on the specified channel

We would appreciate it if you would consider adding these options. Thank you.

**Comment by milindgoel15** [comment]
First 3 things are those that google should do. It's not vanced thing
4th won't happen. You literally want to defeat the purpose of vanced
