### ISSUE TITLE
[Bug] looping / repeat doesn't work when in background

### ISSUE THREAD

**Issue by khaled-0** [YTVanced/Vanced#869]
**Bug description**
Video repeat doesn't work when in Background. Doesn't matter if it's on button mode or other.
It just continues to next video on finishing.
It also doesn't matter if I'm on a playlist or single video.

Repeating only works if I don't leave the app. 

**Variant**
Root

**Vanced version**
16.16.38

**Android version**
Android 11

**Comment by milindgoel15** [comment]
video repeat function works fine as it should. In order for auto-repeat to work, you need to turn off autoplay. And auto repeat will never work inside any playlist. Play normal video with an auto play-off and auto-repeat on and see the magic happen.
