### ISSUE TITLE
[Idea] Show Updated Time For SponsorBlock

### ISSUE THREAD

**Issue by nochlab1** [YTVanced/Vanced#875]
On SponsorBlock on PC it shows updated time in prentices is it able  to be added
Thanks

![Screenshot (224)_LI](https://user-images.githubusercontent.com/37608994/119600148-71722100-bdb4-11eb-8f17-ed0d1f04cde7.jpg)

**Comment by milindgoel15** [comment]
Sponsorblock related issues should be posted to vanced sponsorblock repo only. Since you have already made it there, there's no point to keep this open.
