### ISSUE TITLE
[Idea] YouTube transcript for supported videos

### ISSUE THREAD

**Issue by KyleBroflowski** [YTVanced/Vanced#877]
On desktop version of youtube.com, we can open the video transcript to see every dialogue on the video with its respective time stamps. 
It will be a great improvement if Vanced had this feature along with selectable text feature on long pressing. I have seen a similar request for selectable text on description and comment box too under the link : [#642](https://github.com/YTVanced/Vanced/issues/642)
 It would be a powerful tool with both these features.

**Comment by milindgoel15** [comment]
YouTube transcript is something Google has to deal with since they have the code for the app, not us.
