### ISSUE TITLE
[Bug] Can't access "members only" videos

### ISSUE THREAD

**Issue by lmkelly** [YTVanced/Vanced#878]
**Bug description**
When a new video is uploaded by a creator exclusively to members of their fan club, the only way to access it is through the notifications tab. When you tap the post notification that's supposed to contain a video it will only display the comments on the post.

**Variant**
Non-Root

**Vanced version**
16.02.35 - Build - 01.47.00

**Android version**
Android 9.0 - Pie

**Device**
Samsung Galaxy S9

**Steps to Reproduce**
Steps to reproduce the error:
1. Create a YouTube channel with a fan club
2. Subscribe to the fan club with another account (or just subscribe to a larger YouTuber's fan club to cut out step 1)
3. Post a video as members only
4. On subscriber account click the post notification

**Expected behavior**
It should show the video thumbnail which will let you click it to go to the members only video

**Comment by milindgoel15** [comment]
Invalid bugreport as OP is using old version. Please use latest versions before reporting any bugs here.
