### ISSUE TITLE
Internet connection problem

### ISSUE THREAD

**Issue by fapoy** [YTVanced/Vanced#88]
it doesn't work, it says connect to the internet even though my internet is working perfectly
![Screenshot_2020-10-12-17-18-58-05_7a4090f09f6554852d748ee9fd6f40d3](https://user-images.githubusercontent.com/72737985/95735724-677d3100-0caf-11eb-8784-0032237d955f.png)

**Comment by Jurrer** [comment]
I have exactly same problem and im looking for help

**Comment by corvino-noa** [comment]
I have exactly same problem

**Comment by ywmail** [comment]
Go to the 'Add Account' page then return to the main page, it will be work again.

**Comment by corvino-noa** [comment]
The app says "This account has already been added to your device". The app doesn't allow you to delete an existing account to add it again.

**Comment by corvino-noa** [comment]
![Inkedsg0BECEQvu4_LI](https://user-images.githubusercontent.com/25188142/95767627-fc078380-0cef-11eb-940d-1676b9bf9c7f.jpg)

**Comment by corvino-noa** [comment]
The app does not open or copy links to "account management" and "more about account settings". Only works for adding a new account.

**Comment by ywmail** [comment]
> The app says "This account has already been added to your device". The app doesn't allow you to delete an existing account to add it again.

Just visiting the 'add account' page is ok, don't need to add your Google account again, after visiting the 'add account' page, all you need to do  is return to the previous page.

**Comment by Jurrer** [comment]
It doesn't help ywmail

**Comment by corvino-noa** [comment]
It doesn't help @ywmail

**Comment by ywmail** [comment]
> It doesn't help ywmail

try clearing data of this app, then add account again.

**Comment by spicyfoxx** [comment]
[Read this for all fixes.](https://telegra.ph/Troubleshooting-for-vanced-03-19)

**Comment by corvino-noa** [comment]
Now videos are included, but the app won't let me log in to my account. @ywmail

**Comment by ywmail** [comment]
![Screenshot_20201013_001753](https://user-images.githubusercontent.com/15505291/95769156-045cc000-0cea-11eb-9625-86ad2e3e7376.jpg)
![Screenshot_20201013_001657](https://user-images.githubusercontent.com/15505291/95769171-0de62800-0cea-11eb-960c-fc046eafe997.jpg)
![Screenshot_20201013_001621](https://user-images.githubusercontent.com/15505291/95769184-12aadc00-0cea-11eb-9e1e-c70cc21c5655.jpg)
![Screenshot_20201013_001536](https://user-images.githubusercontent.com/15505291/95769194-16d6f980-0cea-11eb-95a8-0926b4bca933.jpg)

**Comment by corvino-noa** [comment]
![1](https://user-images.githubusercontent.com/25188142/95773946-6d4c3400-0cfa-11eb-84b9-56bb52f0f2c3.jpg)
![2_0](https://user-images.githubusercontent.com/25188142/95773948-6e7d6100-0cfa-11eb-9f9b-fc485b27bdf6.jpg)
![3_0](https://user-images.githubusercontent.com/25188142/95773957-70dfbb00-0cfa-11eb-8fcc-31e53d3c6e4b.jpg)
![4_0](https://user-images.githubusercontent.com/25188142/95773961-71785180-0cfa-11eb-921b-5633db8f013c.jpg)
![5](https://user-images.githubusercontent.com/25188142/95773966-73421500-0cfa-11eb-8636-b82d66601ae5.jpg)
![4](https://user-images.githubusercontent.com/25188142/95773967-73421500-0cfa-11eb-8ec9-8397c27fc684.jpg)
I deleted all the app data, but the existing account was not lost from the list.

**Comment by corvino-noa** [comment]
@ywmail

**Comment by ywmail** [comment]
> @ywmail

account data is stored in microG app,  clear data in microG or delete the account in system account settings.

**Comment by fapoy** [comment]
it worked, after i deleted all data in vanced and microG applications

**Comment by gghhkm** [comment]
All you have to do is remove the microG account from your device, if that doesn't work go to #support in the discord.
