### ISSUE TITLE
[Bug] Vanced crashes one second after launch

### ISSUE THREAD

**Issue by GalaxyLinus** [YTVanced/Vanced#881]
**Bug description**
I had some Account Issues so I reinstalled Vanced and MicroG, I deleted all Vanced Files via Settings too. When I tried starting the app again, I saw the changelog for a sec and then the app closes again.

*Variant**
Non-Root

**Vanced version**
newest

**Android version**
Android 9.0 - Pie

**Device**
ZTE Blade 10 Smart

**Steps to Reproduce**
Steps to reproduce the error:
1. Reinstall App
2. Open App

PS: If anyone can tell me how to completely reinstall Vanced, pls comment

**Comment by milindgoel15** [comment]
Attach a logcat

**Comment by milindgoel15** [comment]
We are closing this issue. If you are still facing issues, please read [vanced guide](https://play.google.com/store/apps/details?id=com.vanced.faq). If after everything, it still happens, please attach a logcat here.
