### ISSUE TITLE
[Bug] Youtube Vanced is not maximized when I make the gesture of dragging upwards

### ISSUE THREAD

**Issue by pedroaugusto839** [YTVanced/Vanced#882]
**Bug description**
When I make the gesture of dragging upwards to maximize the video it comes back as it was before, with the application vertically and with the video not maximized.

**Variant**
Non-Root

**Vanced version**
16.16.38

**Android version**
Android 10

**Device**
Xiaomi Redmi 9

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2. Enter any video
3. Perform the gesture by pulling your finger upwards to maximize the video and you will see that the app comes back as it was before.

**Expected behavior**
The video is maximized and I can see the video with my phone horizontally.

_Attach images/videos if possible. These can be helpful in solving the issue._
https://youtu.be/TEqcxdecceY

**Comment by milindgoel15** [comment]
ROM issue
