### ISSUE TITLE
[Bug] The Download button seems to not working properly

### ISSUE THREAD

**Issue by wahyuaja123** [YTVanced/Vanced#883]
**Bug description**
I want to download some video, but after i press the 'download' button, there's a popup saying that i should upgrade it to youtube premium, but i never meets that problem before.

**Variant**
Non-Root

**Vanced version**
16.16.38

**Android version**
Android 10 - Q

**Device**
Realme 5 Pro

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
3. ....

**Expected behavior**
Download The Video

![Screenshot_2021-05-28-07-01-09-03_7a4090f09f6554852d748ee9fd6f40d3.jpg](https://user-images.githubusercontent.com/79350759/119911572-bc8e5e80-bf83-11eb-9d0b-65c0487a17b8.jpg)
_Attach images/videos if possible. These can be helpful in solving the issue._

**Comment by milindgoel15** [comment]
VANCED IS NOT YT PREMIUM!

**Comment by wahyuaja123** [comment]
> VANCED IS NOT YT PREMIUM!

umm i know, but i downloaded some videos before and did not face that

**Comment by milindgoel15** [comment]
Not vanced problem. Clear data/reinstall vanced/don't use VPN/blame Google are your only options
