### ISSUE TITLE
[Bug] cannot refreshing at home sector

### ISSUE THREAD

**Issue by parkjm94** [YTVanced/Vanced#884]
**Bug description**
cannot refreshing at home sector.

**Variant**
Non-Root

**Vanced version**
16.16.38 - Build - 01.51.00

**Android version**
Android 10

**Device**
Samsung Galaxy A9 Pro

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2. fulldown refresing at home sector.

**Comment by milindgoel15** [comment]
Duplicate of #252
