### ISSUE TITLE
Notification not showing up

### ISSUE THREAD

**Issue by jackcooper7274** [YTVanced/Vanced#885]
**Bug description**
I don't get notified when someone that I have the notification on upload

**Variant**
Non-Root

**Vanced version**
2.6.0 (crimson)

**Android version**
Android 8.0.0

**Device**
Samsung Galaxy S7

**Comment by milindgoel15** [comment]
2.6.0 is the version of vanced manager, not yt vanced.

To make notification work again, follow [vanced guides](https://play.google.com/store/apps/details?id=com.vanced.faq)
