### ISSUE TITLE
[Question/Bug?] Something forces youtube to update?

### ISSUE THREAD

**Issue by mkikets99** [YTVanced/Vanced#887]
# Description
There is something telling to GP Framework to actually update youtube without "permission"...  
**Why without permission?** Because youtube is updated on my **rooted** phone even if my "_Auto update_" checkbox is off...  

# Question
Is it somewhere in youtube source code? Or it is because **Google want it**?

**Comment by mkikets99** [comment]
What if it is because android and GP see that it is 4 major versions differ
16.16.38 vs 16.20.35

**Comment by milindgoel15** [comment]
Nope

**Comment by mkikets99** [comment]
Ok, I will try somerhing...

On my Samsung first 2 methods from the guide doesn't worked...
I founded something on web, and I need to test it before saying something or writing about it...

**Comment by mkikets99** [comment]
I FOUNDED THE WAY!!!

It's a bit dumb way, but:

In GP Market in Settings section there is an point called "Auto update" (in network section)...
I switched that s##t off and now i free from youtube updates
