### ISSUE TITLE
[Bug]"Skip segment" button broken while chromecasting. 

### ISSUE THREAD

**Issue by krukle** [YTVanced/Vanced#890]
As title states. The skip segment button does nothing while chromecasting.

Im on a Oneplus 5t, build number: lineage_dumpling-userdebug 11 RQ2A.210505.003 b5a96127f4.

**Comment by milindgoel15** [comment]
When casting, it doesn't play from vanced. The point when u start to cast, it opens the TV version of YouTube, not the vanced. Hence, any vanced part won't work there(no ad blocking, no sponsorblock). Ur best option is to use different YouTube client on your Chromecast/tv(such as smarttube or something)

**Comment by krukle** [comment]
I see. Thank you for your quick response!
