### ISSUE TITLE
Well I removed the `contains` statement but I think this was not a so good idea. I divided this *problem* in 4 different cases that may happen :

### ISSUE THREAD

**Issue by Sutiwas031189** [YTVanced/Vanced#892]
Well I removed the `contains` statement but I think this was not a so good idea. I divided this *problem* in 4 different cases that may happen :
1. App was updated
1.1 Value is in SharedPrefs -> the dialog will pop up and value in SharedPrefs will be upated
1.2 Value is not in SharedPrefs -> the statement in the if block evaluates to false so the else block saves VERSION_CODE in SharedPrefs
2. App was not updated
2.1 Value is in SharedPrefs -> however the if statement will evaluate to false since it is a less and not a less or equal so the else block will be run and the value in SharedPrefs be written again although it is useless since the value is already up-to-date
2.2 Value is not in SharedPrefs -> the statement in the if block evaluates to false so the else block saves VERSION_CODE in SharedPrefs

So as you can see there is a problem for the 2.1 situation (which is also the situation that is likely to happen most of the time). 
Using the `contains` statement ensured that no useless SharedPrefs edit is made (because defaultValue would never be thrown)

_Originally posted by @cl-ement05 in https://github.com/YTVanced/VancedManager/pull/562#discussion_r641934320_

**Comment by milindgoel15** [comment]
Are u sure u posted this in correct repo?

**Comment by cl-ement05** [comment]
Hmm. What ?😂

**Comment by milindgoel15** [comment]
Please use the correct repo when creating issues.
