### ISSUE TITLE
[Bug] Video controls never disappear

### ISSUE THREAD

**Issue by pilsnerbeer** [YTVanced/Vanced#893]
**Bug description**
Occasionally, video controls (on any video) such as play/pause forward/back never disappear like they should (after 1-2 seconds). Touching the screen doesn't help in hiding the controls. Only solution is to force close the app and open it again. This doesn't happen always but it occurred to me since day 1 of installing vanced via VancedManager (used to have magisk version)
![Screenshot_20210530-112711_1](https://user-images.githubusercontent.com/36133540/120099202-9fe85700-c13a-11eb-8450-d84c079224d0.jpg)

**Variant**
Root

**Vanced version**
16.16.38 - Build - 01.51.00

**Android version**
Android 10

**Device**
OP5T

**Steps to Reproduce**
Steps to reproduce the error:
1 use app normally
2 at some point you will notice controls are not disappearing

**Expected behavior**
controls should disappear naturally after 1-2 seconds or after tapping the screen

**Comment by milindgoel15** [comment]
Disable accessibility player in yt app settings > accessibility

**Comment by pilsnerbeer** [comment]
@milindgoel15 What made you think I had it enabled? There is no 'X' on the right in the picture.

**Comment by milindgoel15** [comment]
It doesn't mean if you don't have X in player, u can't have any accessibility enabled. There are few instances where some accessibility would be on and yt player still won't show X button.

Hence, you are then required to check every accessibility settings there is. From the inbuilt to android native accessibility tools (such as accessibility menu, sound amplifier, live caption, etc.)
One other way is to clear data and setup vanced fresh

**Comment by pilsnerbeer** [comment]
okay thanks for the help. I have no accessibilities enabled and I cleared app data, so we will see if that helped. I guess it would be good to keep the issue open until then

**Comment by milindgoel15** [comment]
There's no point of reopening the issue when the issue is only on your end(aka user end). Ofc we will keep looking for further queries here(if any)

**Comment by matteoturini** [comment]
I have the issue, all accessibility settings are off.

**Comment by matteoturini** [comment]
Please reopen.

**Comment by matteoturini** [comment]
Huh, cleared data and now it works.
