### ISSUE TITLE
[Bug] SponsorBlock Button stuck under recommendations

### ISSUE THREAD

**Issue by farkasma** [YTVanced/Vanced#895]
**Bug description**
When I swipe up on a video to view the recommendations during the video, the SponsorBlock button is visible under the 'x' of the recommended segment. Doesn't happen when the video ends, end the section automatically appears. 

**Variant**
Root

**Vanced version**
16.16.38

**Android version**
Android 10.0 - Pie

**Device**
Samsung Galaxy J5 2017

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2. Start a video
3. Swipe up

**Expected behavior**
Recommended section should appear, but not the SponsorBlock button.

![Screenshot_20210530-130919448](https://user-images.githubusercontent.com/33036336/120101831-60286c00-c148-11eb-8e0b-b52f89e1130b.jpg)

**Comment by milindgoel15** [comment]
Known
