### ISSUE TITLE
[Bug] Seeing random youtube ads pop up.

### ISSUE THREAD

**Issue by supernoodled** [YTVanced/Vanced#896]
**Bug description**
Ads.
Bug1: Seeing random YouTube ads.
Bug2: Seeing unwanted Wikipedia "context" things, which I also consider ads.

**Variant**
Non-Root, AMOLED Black

**Vanced version**
16.16.38

**Android version**
Android 10

**Device**
Samsung Galaxy S9

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2. Find bug1 randomly while scrolling.
3. Find bug2 randomly depending on video or search terms.

**Expected behavior**
No YouTube ads, and no Wikipedia.

_Attach images/videos if possible. These can be helpful in solving the issue._

Bug1 Examples: 
![20210530_153441](https://user-images.githubusercontent.com/31737227/120108540-7856b600-c15d-11eb-8785-4ba0acd321b5.jpg)
![20210530_151847](https://user-images.githubusercontent.com/31737227/120108541-7987e300-c15d-11eb-805f-e2a5d273ff63.jpg)

Bug2 Examples:
![20210530_153848](https://user-images.githubusercontent.com/31737227/120108553-84427800-c15d-11eb-8137-895f90ed85c4.jpg)

**Comment by milindgoel15** [comment]
Show screenshot of ads settings
