### ISSUE TITLE
[Question] Vanced for Android TV

### ISSUE THREAD

**Issue by Dan-WiiU-Killer** [YTVanced/Vanced#897]
**Description**
Hello, may I ask, is there a Youtube Vanced option specifically designed for Android TV control? I managed to download it to my TV device with a "crutch" and additional file manager (FM) apps, but the interface is designed for mobile devices, this app and Vanced Manager are not displayed in the application menu without FM and without "wi-fi phone mice" application is not convenient to use, although everything works, I'm very surprised.

And yet, is there a special (perhaps even an alpha version) of this application? And if not, can I help with testing it? Thanks for understanding)

**Comment by milindgoel15** [comment]
No

**Comment by Dan-WiiU-Killer** [comment]
"No" means "there is no such version" or "no, we do not have it and we do not plan to do it"?

**Comment by milindgoel15** [comment]
Both means the same thing
