### ISSUE TITLE
[Idea] Whitelist for sponsorblock

### ISSUE THREAD

**Issue by Eggroley** [YTVanced/Vanced#9]
A feature that'll whitelist channels so they aren't affected by sponsorblock. Mainly for channels like InternetHistorian or brutalmoose where sponsors are just extra content.

I know this idea will seem useless or a pain to implement to some as you can turn skip automatically off, but I find enjoyment in the automatic skipping feature and that feature tends to become annoying when it's a sponsor segment I want to watch.

Thanks bye.

**Comment by lunartide** [comment]
Great idea, brutalmoose is another example of a channel with sponsorships that are entertaining content. I'd love an option like this.

**Comment by Eggroley** [comment]
> Great idea, brutalmoose is another example of a channel with sponsorships that are entertaining content. I'd love an option like this.

I love brutalmoose's sponsor segments.

Unfortunately though, this idea hadn't gotten any traction at all. Feels like no ones seen it. Except you of course.

**Comment by VityaSchel** [comment]
Good idea, maybe open this issue on sponsorblock repository?

**Comment by Eggroley** [comment]
> Good idea, maybe open this issue on sponsorblock repository?

Seems to be already implemented.
