### ISSUE TITLE
[Bug] old comments: "read more" opening links unintentionally

### ISSUE THREAD

**Issue by supernoodled** [YTVanced/Vanced#900]
**Bug description**
Old comments: links (or timestamps) on the edge of a comment where it says "read more" will instead go to said link instead of opening up the comment.

**Variant**
Non-Root, AMOLED Black

**Vanced version**
16.16.38

**Android version**
Android 10

**Device**
Samsung Galaxy S9

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app.
2. Enable old comments.
3. Find (or create a comment) with a link or timestamp right at the border of "read more"
4. Click and be linked

**Expected behavior**
Clicking on "read more" opens the comment up normally.

_Attach images/videos if possible. These can be helpful in solving the issue._

Example comment:
![20210530_161029](https://user-images.githubusercontent.com/31737227/120109560-ddaca600-c161-11eb-9eac-38b1b2f304c2.jpg)

Clicking on "read more":
![20210530_160953](https://user-images.githubusercontent.com/31737227/120109571-e7cea480-c161-11eb-93c4-ad932d877a4d.jpg)

Linked:
![20210530_161113](https://user-images.githubusercontent.com/31737227/120109578-ed2bef00-c161-11eb-9391-f63afbe25f56.jpg)

**Comment by milindgoel15** [comment]
Please check if it still happens on v16.20.35 now.

**Comment by dumpeldown** [comment]
Seems to be working correctly now on v16.20.35.

**Comment by milindgoel15** [comment]
Glad to hear that
