### ISSUE TITLE
[BUG] Swipe control wont work after viewing story

### ISSUE THREAD

**Issue by yousefsrour** [YTVanced/Vanced#903]
**Bug description**
Swipe controls wont work after viewing story, must relaunch app to work again

**Variant**
Non-Root

**Vanced version**
16.14.34

**Android version**
Android 11

**Device**
Google pixel 2 xl

**Steps to Reproduce**
Steps to reproduce the error:
1. View video
2. View story under video suggestions
3. Swipe control wont work until app is restarted

**Expected behavior**
Swipe controls should still be working

**Comment by milindgoel15** [comment]
Use latest version first to create bug reports. Closing this issue.
