### ISSUE TITLE
[Question] Virus In YTvanced App.

### ISSUE THREAD

**Issue by damianpeirisx** [YTVanced/Vanced#907]
I downloaded  Vanced Manager from vancedapp.com,and to make sure the app is virus free I scanned vanced manager,micro G and the latest version of YT vanced(16.16.38,Light+dark mode)using Virustotal.com.
The website is showing there's a trojan named "android.android.win32.spynote.e" is injected to the YouTube vanced app.(which has been detected by a virus guard name Maxsecure..I)s this true or is this safe to use under this condition?Why it is showing...?
![20210601_150151](https://user-images.githubusercontent.com/85162004/120301336-5f2f4000-c2ea-11eb-8ebf-4dc05476d993.jpg)

**Comment by milindgoel15** [comment]
It's safe and there's no virus. Don't believe fake and unreliable antivirus engines. It's called false positive
