### ISSUE TITLE
[Bug] Video shows black screen after background play

### ISSUE THREAD

**Issue by thedopestpope** [YTVanced/Vanced#91]
I'm using Vanced 15.40.37 and sometimes but not always when I open the app while a video is playing in the background the video will just show as a blank black screen. Audio still works and I can access all the video controls. If I start a new video everything goes back to normal. Does anyone else have this bug?

**Comment by gghhkm** [comment]
Turn off you screen then back on, fixed it for me when I got it in the past.

**Comment by luimu64** [comment]
I have this same bug but the video doesn't come up at all until cache is wiped.
