### ISSUE TITLE
Don't work 

### ISSUE THREAD

**Issue by aiikillu** [YTVanced/Vanced#910]
Hi, I did the update of YouTube Vanced and the application closes at startup, it's pretty annoying haha. I have a Xiaomi Mi 9T pro. Thanks in advance

**Comment by EvoNeo** [comment]
Had the same problem with my Xiaomi 10T. First just uninstall Vanced MicroG and then uninstall YouTube Vanced. After that go to the Vanced Manager and install MicroG and YouTube Vanced. I hope it work for u too.
EvoNeo

**Comment by milindgoel15** [comment]
We are closing this issue. If you are still facing issues, please read vanced guide](https://play.google.com/store/apps/details?id=com.vanced.faq). If after everything, it still happens, please attach a logcat here.
