### ISSUE TITLE
[Bug] Community posts do not function with old comment location enabled

### ISSUE THREAD

**Issue by enderdrag64** [YTVanced/Vanced#911]
**Bug description**

Community posts no longer work when the old comment location is enabled. They work fine when it is disabled. Interestingly I had to downgrade to 15.40.37 temporarily earlier today and I noticed that this bug wasn't occuring in that version. I also know that this bug does occur on 16.14.34 and 16.16.38
What I mean by community posts not working is that they don't appear on the home page like they are supposed to, and trying to view the Community tab on a specific channel gives you the message "Sorry, Community posts are only available on your computer and the latest version of the YouTube app on mobile phones right now."

**Variant**

Non-Root

**Vanced version**

16.02.35 - Build - 01.49.00

**Android version**

Android 10

**Device**

OnePlus 6

**Steps to Reproduce**

Steps to reproduce the error:
1. Open the app
2. Go to settings -> vanced settings -> layout settings
3. enable "Comments location (Alpha)"
4. Go back to the home page
5. Visit any channel
6. Go to the community tab

**Expected behavior**

The community tab should allow me to see community posts but instead it shows the message I mentioned in the description.

_Attach images/videos if possible. These can be helpful in solving the issue._

Here are two screenshots, with and without the old comment location enabled:

![Screenshot_20210601-234953](https://user-images.githubusercontent.com/33301226/120421494-6844ff00-c334-11eb-8037-09cef6cce180.jpg)
![Screenshot_20210601-235019](https://user-images.githubusercontent.com/33301226/120421498-69762c00-c334-11eb-9712-75a3b3da6f6a.jpg)

**Comment by milindgoel15** [comment]
About this, xfilefin(dev of vanced) said that it won't work now. The old comments layout was done in a compromise to several features which will break now.
