### ISSUE TITLE
[Idea] Minimize YouTube Kids Shenanigans

### ISSUE THREAD

**Issue by oSumAtrIX** [YTVanced/Vanced#913]
**Description**
YouTube decided to disable miniplayer video playback on videos marked for kids. Although I even had to once verify myself that I am over 18 years old, YouTube still thinks, that they should treat me as if I were a child. Vanced could most certainly add a toggle to enable miniplayer playback and remove other youtube kids shenanigans. As long as the youtube api also allows, enable the button to add the video to playlists as well.

**Comment by milindgoel15** [comment]
It's server sided, not client. The video which is marked as kids is an option which youtubers checks when publishing their videos. You have to tell those youtubers to stop marking them as made for kids or tell YouTube to remove this from their code. Vanced won't do anything about this.

**Comment by oSumAtrIX** [comment]
Please note, that the miniplayer is a clientside feature and is not a server side limitation. The issue is to minimize, not completely remove youtube kids. The miniplayer is disabled for youtube kids videos. Vanced can remove that limitation on the client

**Comment by oSumAtrIX** [comment]
> It's server sided, not client

I have created a playlist with a youtube kids video, which per rule should've not been possible, thus confirming there is not any server side check being done. This means, that the client side restriction on disabling the "add to playlist" button can be disabled in the vanced client.

https://www.youtube.com/watch?v=6dKi71IeG6o&list=PLUe3wdrAaq2qYvhvLY-vRwrySdnuWQeiq&index=2&t=7s

**Comment by milindgoel15** [comment]
Oh so we just forgot to tell you. Yes, it's not server sided. We just have to find the code for it firstly then yes it can be fixed. This will probably come with next future vanced release.

**Comment by gthrow** [comment]
Why is this issue still closed if you're planning on adding this feature?

**Comment by KevinX8** [comment]
The feature was already added

**Comment by oSumAtrIX** [comment]
> The feature was already added

While the miniplayer feature has been implemented, adding videos marked for kids to playlist has not been. https://github.com/YTVanced/Vanced/issues/913#issuecomment-860325040

**Comment by milindgoel15** [comment]
Yea we know already
