### ISSUE TITLE
[Bug] When i start a video and put it in the backround,from notification it appears 00:00 from the time of the video. 

### ISSUE THREAD

**Issue by LMarius** [YTVanced/Vanced#915]
**Bug description**
[Bug] When i start a video and put it in the backround,from notification it appears 00:00 from the length of the video. 

**Variant**
Non-Root

**Vanced version**
16.02.35 - Build - 01.47.00 and some older versions

**Android version**
Android 10 -?

**Device**
Samsung Galaxy A20e

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2. Open a video(u need playback in backround enabled)
3. Put it in backround and swipe down on the notification(show more option) and u will see 00:00 from the length of the video.

**Expected behavior**
Before seeing the bug,i thinked that it will appear normal at the nottifications,but couldn t skip on the video

![Screenshot_20210604-222302_One UI Home](https://user-images.githubusercontent.com/85368976/120856100-fe249800-c587-11eb-9b9f-d4c2853b972e.jpg)

**Comment by milindgoel15** [comment]
Closed issue as user is using old version. Note that on latest v16.16.38, seekbar won't work as it's stock yt bug. Wait for future updates

**Comment by LMarius** [comment]
I found right now how to fix this,press pause and resume and all will be fine. U need to do this every time this will happen
