### ISSUE TITLE
When Open YT Vanced, closes automatically[Bug] replaceme

### ISSUE THREAD

**Issue by vDavid015** [YTVanced/Vanced#917]
**Bug description**
Replace me with a clear and detailed description of the bug.

**Variant**
Non-Root/Root

**Vanced version**
16.02.35 - Build - 01.47.00

**Android version**
Android 9.0 - Pie

**Device**
Motorola One Action

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2. Closes app  [](https://youtu.be/7cZChZjhdJg) automatically

**Expected behavior**
Replace me with a description of what you expected should happen and what happened instead.

_Attach images/videos if possible. These can be helpful in solving the issue._

https://youtu.be/7cZChZjhdJg

**Comment by milindgoel15** [comment]
Closing issue as user is using old version. Please use latest version if you are reporting bugs here. And do attach logcats with it.

**Comment by vDavid015** [comment]
I have latest version

**Comment by milindgoel15** [comment]
U write v16.02, this ain't latest
