### ISSUE TITLE
[Bug] Notifications don't  work in work profile 

### ISSUE THREAD

**Issue by BossDaily** [YTVanced/Vanced#918]
**Bug description**
Basically, notifications don't work if the app is installed in the work profile. IT says "Tap here to enter Work profile" but it never shows when I tap it. And other work profile apps don't say that, other apps show notifications normally. I use an app called Shelter to make the work profile. This might not be important since I legit don't get this issue with any other app. I even have "Show notification content" enabled in notification settings which means it should show the notification content of the app with out me tapping or entering work profile but it doesn't.

**Variant**
Non-Root

**Vanced version**
16.02.35 - Build - 01.47.00

**Android version**
Android 9.0 - Pie

**Device**
Samsung Galaxy S8

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app (Installed on a work profile) (I use "shelter" for my work profile) 
2. Click on either open a YT video, or wait for a notification and you will see that the notification doesn't show 
3. Tap it and the notification will still not show it will just take you to the video

**Expected behavior**
I expected to see a normal notification for a video or a comment but that doesn't happen, it just says "tap to enter work profile to see the notification" but even when I tap it or even when I am in work profile it still doesn't show 

_Attach images/videos if possible. These can be helpful in solving the issue._

**Comment by milindgoel15** [comment]
Use root version.
