### ISSUE TITLE
[Bug] Watch history fails to update - Not related to Adblocking.

### ISSUE THREAD

**Issue by vernilla** [YTVanced/Vanced#919]
**Bug description**
Watch history fails to save viewed videos. This functionality works on stock. This is NOT related to AdAway. I previously discussed this issue on Telegram, and it was fixed for a couple days, but then it randomly stopped working again.

The fix was to uninstall, reboot, and reinstall. I am unsure when it stopped working again as I mainly use History when I want to show my partner something I watched.

Curiously, this time, I used Titanium to back up my app data as I'm tired of constantly having to redo my settings, and while history DID work before I restored the backup, it again stopped working after. I'm not sure if a setting in the app is causing this or what, but I never had this issue on my last phone.

**Variant**
Root

**Vanced version**
16.16.38 - Build - 01.51.00 (and earlier versions, as well)

**Android version**
Android 11

**Device**
OnePlus 7T

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app 
2a. Change settings? Unsure.
2. View a video
3. Check history

**Expected behavior**
Video should be in history. It is not. This has nothing to do with adblocking.

**Comment by milindgoel15** [comment]
If it's not related to ad-blocking, it's probably related to the backup method you used and files it messed up. Still this type of issue is user end problem and hence, you should clean install your ROM. And better if you clean install vanced and start from scratch.

I suggest you to use swift backup for backing up your app and data. I personally use it to only restore data but works.

**Comment by vernilla** [comment]
Please re-read this ticket. This issue wasn't *caused* by backing up, it's something that continues to happen after some time. I noted that restoring the backup caused it to happen immediately, but this is not the actual cause of the issue. I thought it would be helpful to point it out, but you seemed to think I was saying I caused the issue in the first place, which is very much not the case.

This ROM is pretty fresh and I refuse to go through the headache of reflashing and setting everything back up, man. I have a ton of medical appointments this month and I just want my history to work.

**Comment by vernilla** [comment]
It's Stories. I just went through and tested every single setting, reloading the app every time I changed a setting.

As soon as I disabled Stories, the history broke.

I just woke up. Don't tell me this is user error, thanks.

**Comment by vernilla** [comment]
Other layout settings seem to also cause it, but Stories is consistent where the others are not. I recorded a video of this.

**Comment by milindgoel15** [comment]
Consider [checking this](https://imgur.com/a/rEPMSYV). Ik things can work for one, and maybe not for other person but it doesn't hurt anyone to try to install without using external app or mod. I have been using root version for 2 years with custom ROM with adaway and all. Never heard anyone saying disabling stories breaks history for them
>As soon as I disabled Stories, the history broke.



Yes, it can. Backing up app/data from third party apps can sometimes breaks some things for people. For you, it breaks your history cuz it broke stories for you. For others, it can break other thing. 

>Curiously, this time, I used Titanium to back up my app data as I'm tired of constantly having to redo my settings, and while history DID work before I restored the backup, it again stopped working after. 

I would personally check by reinstalling without using external mod or app if I were you. 
>This issue wasn't caused by backing up, it's something that continues to happen after some time

No, there's no setting for it. Infact, root version can only have this issue if you modify your hosts or some external app affecting it which in your case is the backup app you used.
>I'm not sure if a setting in the app is causing this or what

I didn't say you are doing it intentionally 🤷‍♂️
>This issue wasn't caused by backing up, it's something that continues to happen after some time


I offered you a solution (tho not as permanent solution) but it's worth to try instead of not trying at all. Trying it or not is your choice.
>This ROM is pretty fresh and I refuse to go through the headache of reflashing and setting everything back up, man.

Ofc I understand but there's nothing we can do about it.
> I have a ton of medical appointments this month and I just want my history to work.

**Comment by milindgoel15** [comment]
If you are not ready to try without external mod, then there's nothing we can do. It only takes about max 20 mins to reflash and setup vanced without external mod

**Comment by vernilla** [comment]
I feel like you're not understanding what I'm saying. I used Titanium ONCE. Just once. And now you're hooked on it like I've been using it every time.

I'm uploading a 7 minute video of this for you.

**Comment by milindgoel15** [comment]
Umm please explain your third line.

![Screenshot_20210606-165147_Telegram_X.png](https://user-images.githubusercontent.com/45682747/120922587-aac95b80-c6e7-11eb-8183-d9f973b6bcf3.png)

**Comment by vernilla** [comment]
What is there to explain? Nothing I said there is any different than anything I said here, dude. Are you even reading what I'm writing? I am referring there to the SINGLE TIME I used Titanium after no one replied to me on the issue earlier in the night. Scroll up, man.

**Comment by milindgoel15** [comment]
Ok I will wait for your recording. Lemme see

**Comment by vernilla** [comment]
https://youtu.be/mW32CkqOtpg

Took it a million years. Do you want to walk me through providing my debug logs now, or? :/

**Comment by vernilla** [comment]
You may want to wait for HD to process on that, but I'm sure you knew that. It *just* finished SD processing.

I'm getting some coffee now. Guh.

**Comment by milindgoel15** [comment]
Ok I saw it already. I want some answers and i expect to answer it directly what I ask. Not all previous statements.

You wrote on telegram that that you initially used Titanium backup to backup app to restore it later cuz u didn't wanted to do every thing every time u flash ROMs (_please I expect you here to direct answer, don't go back to your first statement where u said it was just one time_), ok the question arises, before you restored that backup, were all the settings working? When you change any settings, does history used to broke? 

This question goes to the time where u stopped using adaway for good but before you planned to use titanium so please answer accordingly.

**Comment by vernilla** [comment]
> Ok I saw it already. I want some answers and i expect to answer it directly what I ask. Not all previous statements.
>
> You wrote on telegram that that you initially used Titanium backup to backup app to restore it later cuz u didn't wanted to do every thing every time u flash ROMs (please I expect you here to direct answer, don't go back to your first statement where u said it was just one time), ok the question arises, before you restored that backup, were all the settings working? When you change any settings, does history used to broke?
>
> This question goes to the time where u stopped using adaway for good but before you planned to use titanium so please answer accordingly.
>
> I will ask next question based on what u answer to this.

I'm not a child and I *really* don't appreciate the accusatory tone you used here, whether you edited it or not.

You are REALLY hung up on that Titanium thing. Go through the Telegram channel and read EVERYTHING I'VE EVER WRITTEN THERE and you will understand when and why I used Titanium *one time*. I'm not freaking lying to you, dude, and I'm not sure why you're hellbent on thinking I am. Go read everything I've ever written on Telegram and Discord (Verne#2821) asking for support on this issue. It's not much; it won't take you long.

Simple. English. 
I tried Titanium. I wanted to see if it would be possible to use Titanium. I tried Titanium. Redoing my settings a lot is annoying. I tried Titanium once. I wanted to see if using Titanium would make it not annoying. 
I found out that Titanium restores the bad setting. The bad setting is Stories. The bad setting might also be other layout settings. 
I did not use Titanium again after this. 
I noticed my history was broken twice. Both times happened before I used Titanium. I did not use Titanium either time it happened. I asked for help on Telegram the second time. No one helped me. 
I used Titanium. It broke a third time. The third time was when I used Titanium. I mentioned Titanium on Telegram. No one helped me. I left the Telegram.
I mentioned Titanium on Discord. No one helped me. 
I made this ticket. You told me it was my fault. I still had not done anything with the app since I used Titanium. I used Titanium ONE TIME.
I cleared the data. I checked the settings one by one. I reached Stories. It broke. 
I told you this. You accused me of lying, or being stupid, or something. Really not clear on that. I made you a video.

I used. Titanium. ONCE. in all of this. And you just. Won't. Let it go. Goddamn, I thought I was providing helpful information for debugging, but you came into this expecting that it would be user error no matter what. I'm trying to get some debugging logs your way so this can be fixed, because *yeah*! Sometimes an issue will happen for one user and not another! Logs can tell you maybe *why*!

That's! Why! I! Made! This! Bug report!!!

Ugh.

I've been fasting for two days, I'm stressed, I just woke up, I have a ton of appointments this week and this month, and I'm just trying to submit a bug report so that an issue I'm facing can be hopefully fixed. I'm trying to be helpful, I'm trying to not make everyone hold my hand and do things for me like most people on the Telegram seem to want. I get it, you deal with difficult people. I get it. I really do. But you came at me with just. Such passive aggression.

Like. I'm sorry for getting snippy, but holy hell. Can you understand why I'm frustrated?

Hit me up on Discord.

**Comment by milindgoel15** [comment]
Sorry, I apologise for everything. If you could forgive me, please do. 

About your issue, I personally prefer tg but ok for you I will come on discord. So how to ping you there?
