### ISSUE TITLE
[Idea] hiding verified comments

### ISSUE THREAD

**Issue by UnitedDugout27** [YTVanced/Vanced#920]
![Screenshot_20210605-094517.png](https://user-images.githubusercontent.com/77062086/120893758-e6c6c880-c5e2-11eb-88e0-2535fa2232fb.png)

Within the past year, YouTube has unfairly given YouTube channels that are verified the top comment spots. You can see this happening in any fairly popular video. This screenshot above illustrates the issue I'm describing. I would love to see a feature that completely hides comments from all verified YouTube channels.

**Comment by UnitedDugout27** [comment]
?

**Comment by milindgoel15** [comment]
I would say unnecessary/illogical request imo. But ask Google for it

**Comment by UnitedDugout27** [comment]
We both know Google will never do that... I am not the only one that wants this feature.
I hope you consider implementing this down the line.
