### ISSUE TITLE
Installation error (Non-Redmi Device)

### ISSUE THREAD

**Issue by yograjsingh-cmd** [YTVanced/Vanced#921]
![Screenshot_20210606-090431_Vanced_Manager](https://user-images.githubusercontent.com/84258191/120911817-d4fb2900-c6a7-11eb-8bff-103b7c9f8e5a.png)

**Comment by milindgoel15** [comment]
- If you are rooted with magisk, make sure you have the latest of it. After checking that, reboot device (MANDATORY)

- If you are rooted with SuperSU, switch over to magisk.
