### ISSUE TITLE
Loading/Opening Screen

### ISSUE THREAD

**Issue by WeMayNeverKnow** [YTVanced/Vanced#922]
**Description**
Set the loading screen of the app by the theme installed.
For now the loading screen color of yt vanced is blinding white it would be nice if this is black since my installed theme is black (amoled one)

**Comment by milindgoel15** [comment]
Change app theme to system theme or set to dark mode. If you are on android 9 or below, then there's nothing we can do. Use better theme engine to override splash color


![Screenshot_20210606-143241_YouTube.png](https://user-images.githubusercontent.com/45682747/120918833-1d304080-c6d4-11eb-892a-98e0008f5589.png)
