### ISSUE TITLE
Youtube vanced App not starting! Crashing immediately after the launch. 

### ISSUE THREAD

**Issue by Karangg** [YTVanced/Vanced#925]
The app started crashing from the past few hours and the crash happens immediately after launching the app. 

**Variant**
Non-Root

**Vanced version**
16.02.35 - Build - 01.47.00

**Android version**
Android 10 - Pie

**Device**
Realme x2 pro

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2. Automatically gets closed! I.e. Gets crashed immediately 

https://user-images.githubusercontent.com/85457029/120937092-1bdd3300-c729-11eb-8658-b5c25cbd318b.mp4

**Comment by bibek-maharjan** [comment]
I am also having the same issue.

**Comment by milindgoel15** [comment]
Invalid issue as user is using old version. Please use latest v16.16.38 when reporting issues and attach a logcat with it.

**Comment by Karangg** [comment]
![Screenshot_2021-06-07-10-30-56-04_664cadb1c148e0d90475ca0f494fbf83](https://user-images.githubusercontent.com/85457029/120961645-d433c700-c77b-11eb-8b45-d6ea54a85661.jpg)

My mistake of not changing the version given in the default template for creating an issue. But i have the letest version of vanced as you can see in the above screenshot.

**Comment by milindgoel15** [comment]
Ok attach logcats

**Comment by Karangg** [comment]
Is their any simple method to get logcats i searched online and there i got a method that needs downloading android studio and some bunch of things its overwhelming since I'm not a devoloper and never used these softwares before.
Can you Tell me a relatively easy method to get logcats

**Comment by milindgoel15** [comment]
You can use this [guide](https://telegra.ph/Bug-Reports-10-17). its simple enough for beginners

**Comment by Karangg** [comment]
[logcat.txt](https://github.com/YTVanced/Vanced/files/6607836/logcat.txt)

**Comment by milindgoel15** [comment]
Have you installed vanced microG? The logs does say it can't able to find microG on your device.

> Following the process, here's the .txt file.

**Comment by Karangg** [comment]
Yeah i have and here's the screenshot of the manager where it is updated it well
![Screenshot_2021-06-07-23-31-58-30_664cadb1c148e0d90475ca0f494fbf83](https://user-images.githubusercontent.com/85457029/121067483-bcdef300-c7e8-11eb-97d1-d2e1efe1738d.jpg)

**Comment by milindgoel15** [comment]
Uh ok. So the log has apparently an network error issue in the stack trace. We have no fix for this as we don't know what is causing this. Wait for future updates. Till then, please revert back to an old version of vanced for now.
