### ISSUE TITLE
Download Title Formatting

### ISSUE THREAD

**Issue by sid-g12** [YTVanced/Vanced#926]
![Screenshot_20210607-034609](https://user-images.githubusercontent.com/51516637/120941956-4d62f800-c743-11eb-99c6-54eda857f492.jpg)

The titles in the downloaded videos tab in the dark mode is black, making it practically unreadable. Don't know if the issue is present in light/black theme. Screenshot attached

**Comment by sid-g12** [comment]
Also, it is off center, looping around

**Comment by milindgoel15** [comment]
Check for override dark mode theme settings in your device dev options. If it's on, disable it. If it's not, clear data or try reinstall
