### ISSUE TITLE
[Idea] Toggle for previous YTM font

### ISSUE THREAD

**Issue by Harmonie666** [YTVanced/Vanced#927]
**Description**
Several users have noticed that YTM has gotten a change to it's modern font, which has alot of unnecessary spacing between the letters. It's also difficult to read.

https://www.reddit.com/r/YoutubeMusic/comments/ntquk0/random_observation_did_they_adjust_the_font_or/?utm_medium=android_app&utm_source=share

This represents another unnecessary change, as the previous font was just perfectly fine, and easy to go with.
I'm asking the Vanced devs to replace this new font, with the previous one, by adding a toggle to enable the previous font (with less spacing between Letters), or by removing the new font completely. The new font has just been added very recently, and it appears on most regions of the app.
This new font with more spacing between the letters is really bad for UI and UX.
![Screenshot_20210607-004538988 (1).png](https://user-images.githubusercontent.com/73917917/120942835-ba6a9380-c72b-11eb-8f27-746e474545b0.png)![Screenshot_20210607-005018506 (1).png](https://user-images.githubusercontent.com/73917917/120942839-bdfe1a80-c72b-11eb-97ef-59ad59b2a7f4.png)![Screenshot_20210607-003625913 (1).png](https://user-images.githubusercontent.com/73917917/120942842-c191a180-c72b-11eb-8244-ba37883eacc1.png)
![Screenshot_20210607-005415018 (1).png](https://user-images.githubusercontent.com/73917917/120942869-e4bc5100-c72b-11eb-9ccf-7f1c081e04d6.png)![Screenshot_20210607-005330938 (1).png](https://user-images.githubusercontent.com/73917917/120942872-e71eab00-c72b-11eb-81d9-38e506106d6f.png)![Screenshot_20210607-005901963 (1).png](https://user-images.githubusercontent.com/73917917/120942876-e84fd800-c72b-11eb-8ee8-886a354cc48f.png)

**Comment by milindgoel15** [comment]
Not sure if the font is hard-coded. If it is, nothing can be done. I will ask oizaro and let you know.

**Comment by milindgoel15** [comment]
Update: I just confirmed it with oizaro. It's hard coded so nothing can be done.

**Comment by Harmonie666** [comment]
> Update: I just confirmed it with oizaro. It's hard coded so nothing can be done.

Gotcha. Thanks for checking.
