### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by justtrynawatchvideos** [YTVanced/Vanced#929]
**Bug description**
First, I opened the app normally and it said I wasn't connected to the internet and nothing would load. I tried wifi and data and neither worked. Then I signed out of my accounts and opened the app and it worked normally. I tried signing in on my Google account and then it just kept loading and nothing changed. At some point, when I did all this again, I just saw the same content as if I was signed out. When I tried signing in again, it said I already was without my content. I tried following the troubleshoot question of it loading infinitely and nothing changed. However, when i Google a video and went through the Google app, the video would open in Vanced normally. I couldn't use the app otherwise. Please advise!

**Variant**
Non-Root

**Vanced version**
2.6.0 Crimson

**Android version**
Android 11

**Device**
Samsung Galaxy S10

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app

Or 

1. Sign out of accounts
2. Normal seeming app without my personal content
3. sign in account again
4. Infinite load OR seeing what it looks like without a signed in account. 

**Expected behavior**
Normal working app

![Screenshot_20210607-010105](https://user-images.githubusercontent.com/85473503/120962077-05d17180-c72d-11eb-984c-23472410aa70.jpg)
![Screenshot_20210607-010307](https://user-images.githubusercontent.com/85473503/120962079-066a0800-c72d-11eb-9fdb-8c27d8c9b58c.jpg)

**Comment by milindgoel15** [comment]
Please stop using old versions. Use latest v16.16.38.
