### ISSUE TITLE
[Idea] 

### ISSUE THREAD

**Issue by Gurnoors7** [YTVanced/Vanced#932]
Can you download videos or music from yt music?? I think you can't... that's why it would be a great idea if you added this feature!! It would be great if we could download videos and songs from yt vanced and yt music as well!!

**Comment by milindgoel15** [comment]
Nope, don't ever ask again

**Comment by Gurnoors7** [comment]
> Nope, don't ever ask again

I know that I can't... that's why I suggested it... if you read the whole description you will find out 😊
