### ISSUE TITLE
[Bug]I am using youtube vanced since many months. And i love it above all. But there is a bug tht i wld like to report.....as many might be facing it too. The thing is, whenevr i play videos, i used to pause it using my bluetooth earphones. But lately, tht function is missing or rather i wld say tht its masked somehow....to explain it better - whenvr i play a video, and i pause it using my bluetooth it wont work, but whenever i physically pause it on my smartphone and then play it, then im able to use this plwy/pause feature on bluetooth earphone. Furthermore, if i play another video, then bluetooth play/pause is vanished. I ll hv to manually do it on phone and then only i can use it over bluetooth.   Is there a fix for this bug? Wld it be included in the next version???

### ISSUE THREAD

**Issue by adyy462** [YTVanced/Vanced#937]
**Bug description**
Replace me with a clear and detailed description of the bug.

**Variant**
Non-Root/Root

**Vanced version**
Replace me with the exact version of vanced you are using. It is mandatory to report issues from the latest available versions only. For example, v16.16.38

**Android version**
Replace me with the version of Android your device have. For example, Android 11 

**Device**
Replace with the name of the device on which you faced the bug. For example, Samsung Galaxy S8

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
3. ....

**Expected behavior**
Replace me with a description of what you expected should happen and what happened instead.

_Attach images or videos or logcats in case of crashes if possible. These can be helpful in solving the issue._

**Comment by Iammethe24** [comment]
God that's a long title, why not put all those text on the "bug description" part?

**Comment by milindgoel15** [comment]
Oh god

**Comment by milindgoel15** [comment]
The bug u are facing is known. It's a stock yt bug and an upcoming update will fix it. Wait for updates!

**Comment by adyy462** [comment]
> God that's a long title, why not put all those text on the "bug description" part?

Srry...Im new to discord man.... Used discord for the first time. I jst wanted to tk this issue to the concerned....didnt think or read b4 i typed, as to whr i was typing .....anyways.....its nice to see a reply.

**Comment by adyy462** [comment]
> God that's a long title, why not put all those text on the "bug description" part?

At the very least it caught ur attention....😋

**Comment by milindgoel15** [comment]
We do not reply issues like the way you made. I gave the solution because it was just another duplicate issue of which a fix will come in future release. Next time, we will straight close such issues without replying. Don't think we gave you some sort of special attention or that.

**Comment by milindgoel15** [comment]
fixed with v16.20, Kindly update to that version

**Comment by adyy462** [comment]
This was the first time ever that i ever used discord, or let alone
messaging someone. I had no idea how, whr to type or let alone hw to
address  my issue to the concerned party. I get it tht thr might be so many
duplicate issues like it, but i did not knw that, evry1 is nt upto the
mark, u see. It felt very rude to read ur words. I never mail to anyone or
any app for tht matter, but i did coz i love vanced and i want it to
improve. Anyways, thanks.... 😒

**Comment by Fusseldieb** [comment]
> This was the first time ever that i ever used discord

t-this isn't even discord dude.
