### ISSUE TITLE
[Bug] Application minimizes on startup

### ISSUE THREAD

**Issue by Actticus** [YTVanced/Vanced#938]
**Bug description**
When I start app, it is minimize in tray (not crushing/closing)
**Variant**
Non-Root/

**Vanced version**
v16.16.38

**Android version**
Android 10

**Device**
Xiaomi Redmi Note 8 Pro

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2. Do nothing
3. It is closing

**Expected behavior**
Expected that I can use app. In additional on previous version (I don't remember number of version) today stop working normal, with error in YouTube "No internet connection". v16.16.38 was installed by v2.3.0 manager.

Screen record:
https://drive.google.com/file/d/1XyyCRULFpO1FZcHpFRw8jTc0L_yUFFUO/view?usp=sharing

**Comment by milindgoel15** [comment]
Attach logcat

**Comment by Actticus** [comment]
> Attach logcat

From manager?

**Comment by milindgoel15** [comment]
No, check [vanced FAQ](https://play.google.com/store/apps/details?id=com.vanced.faq) for guide on how to get logcat.

**Comment by Actticus** [comment]
[logcat.txt](https://github.com/YTVanced/Vanced/files/6618472/logcat.txt)

**Comment by Actticus** [comment]
logcat.txt

https://hastebin.com/ehihasaput.yaml

**Comment by Actticus** [comment]
Do you have any solution?

**Comment by milindgoel15** [comment]
> Do you find any solution?

Oh sorry I haven't check your log. I tried opening it on my phone but can't due to performance issues with this log. By the time, please use any old version which works for you. If we find something, we will tell. Otherwise there are also some reports where few users are facing crashes and logs only say that they have network connection error. So we are also confused with it. Probably next vanced update will fix it hopefully

**Comment by Actticus** [comment]
> > Do you find any solution?
> 
> Oh sorry I haven't checked your log. I tried opening it on my phone but can't due to performance issues with this log. By the time, please use any old version which works for you. If we find something, we will tell. Otherwise there are also some reports where few users are facing crashes and logs only say that they have network connection error. So we are also confused with it. Probably next vanced update will fix it hopefully

Ok, thank you
