### ISSUE TITLE
[Bug] YTVanced randomly opens Google Play after video playback

### ISSUE THREAD

**Issue by fragpit** [YTVanced/Vanced#942]
**Bug description**
YTVanced on Android randomly opens Google Play after video playback

**Variant**
Non-Root

**Vanced version**
v16.16.38

**Android version**
Android 10, OxygenOS 10.3.11

**Device**
OnePlus 6

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2. Watch some video for one minute or more
3. Push Home button at Vanced app
3. Google Play opens

**Expected behavior**
Google Play won't open. 

https://user-images.githubusercontent.com/11692482/121296076-b5a70a80-c8f8-11eb-903b-28f980ff67d8.mp4

**Comment by milindgoel15** [comment]
We are not sure what is causing this. But it seems to be affecting only few people on non root version. A temporary fix would be to update official YouTube present on your device and disable it after. Other than that, no fix for this
