### ISSUE TITLE
Slide up gesture doesn't work properly

### ISSUE THREAD

**Issue by Mimicthis** [YTVanced/Vanced#944]
Slide up gesture so the video would go to the horizontal way doesn't work properly. I slide up the video and then it goes back immediately to the vertical view. After second try it works. While pressing the square icon to do this it doesn't do that. It works properly on the basic YouTube app.

**Comment by milindgoel15** [comment]
Clear data and try again. If it still happens, try reinstall. Otherwise ROM issue

**Comment by Mimicthis** [comment]
I've dibd both. It's an app issue.

**Comment by Mimicthis** [comment]
It doesn't work.
