### ISSUE TITLE
[Bug] my phone can't access Youtube.com and Youtube App having used Vanced App

### ISSUE THREAD

**Issue by hareluyagod** [YTVanced/Vanced#945]
**Bug description**
I can't open the Youtube.com web page on my phone in the web browser app , and videos can't be loaded in the Youtube App either. I tried deleting the vanced app and reinstalling it and so on , still the Youtube App keeps loading forever and accessing Youtube.com shows webpage not available. I guess it's because of the Vanced App.
I've tried root version and non-root version it just won't work.

**Variant**
Non-Root version and Root version

**Vanced version**
newest

**Android version**
Android 10

**Device**
[图片] one plus 7pro

[图片]

_Attach images or videos or logcats in case of crashes if possible. These can be helpful in solving the issue._

**Comment by milindgoel15** [comment]
Don't report device issues here. Vanced team can only help you if you have issues on vanced. Your issue isn't our problem to deal with.
