### ISSUE TITLE
[Idea] Completly disable Shorts

### ISSUE THREAD

**Issue by leodoi3** [YTVanced/Vanced#947]
**Description**
Please remove the shorts tab from the homepage and completely disable the feature. I feel my brain rotting even more every time I open youtube now. My history is filled with bullshit videos that I shouldn't even be spending my time watching in the first place.

_Attach images/videos if possible. Also add any links to possible other applications with the said feature already implemented._

**Comment by milindgoel15** [comment]
Duplicate of #334
