### ISSUE TITLE
[Bug] App crashes when a Notification is pushed

### ISSUE THREAD

**Issue by seffparker** [YTVanced/Vanced#949]
**Bug description**
When a status bar notification is pushed from the app (like the media controls when the app is minimized), the app crashes with the following error:
```
android.app.RemoteServiceException: Bad notification(tag=null, id=2) posted from package com.google.android.youtube, 
crashing app(uid=10014, pid=30654): Couldn't create icon: StatusBarIcon(icon=Icon(typ=RESOURCE 
pkg=com.google.android.youtube id=0x7f0807ec) visible user=0 )
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1973)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:224)
	at android.app.ActivityThread.main(ActivityThread.java:7562)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
(truncated)
```

**Variant**
Root

**Vanced version**
v16.16.38

**Android version**
Android 10

**Device**
Xiaomi POCOPHONE F1 / MIUI 12.0.3.0

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2. Enable background playback
3. Disable PIP
3. Start to play something
4. Minimize the app or turn the screen off
5. The app crashes with the above error

**Expected behaviour**
The app should continue to play in background with the media controls in status bar

**Workaround**
Disable/Disallow all notifications for the app at Android level (app permissions)

**What tried but didn't work**
1. Tried both Black and Dark variant of Vanced
2. Tired both Light and Dark theme of Android

**Comment by milindgoel15** [comment]
It doesn't crash here atleast. We will see if anyone else can reproduce this and find fix for it.

**Comment by sudo-nautilus** [comment]
I appreciate you for the perfect bug report.
You must try non root varient and try to reproduce the issue

**Comment by sudo-nautilus** [comment]
+ mine isn't crashing at all

**Comment by Iammethe24** [comment]
Can't reproduce

**Comment by seffparker** [comment]
Does your `/data/app/com.google.andorid.youtube-XXXXXXXX/` has any other .apk than the `base.apk`? I suspect the referred icon resources are bundled within the dpi split.

**Comment by milindgoel15** [comment]
![Screenshot_20210611-104542_MiXplorer.png](https://user-images.githubusercontent.com/45682747/121634455-30f7f000-caa2-11eb-87e4-7721740105e3.png)

**Comment by seffparker** [comment]
Thanks @milindgoel15 

Closing this issue since it is specific to my installation.

**Comment by milindgoel15** [comment]
Did reinstallation help?

**Comment by seffparker** [comment]
I have re-installed the splits. Now base and all split APKs are present, but still FC when notification is pushed with the same error message. Works everything when notification is disabled.

I suspect the issue is with the MIUI 12.0.3.0 since it started when I upgraded MIUI (and Vanced together)

**Comment by seffparker** [comment]
May be, even the stock YouTube might crash in my device when the notification is pushed. But I don't know a way to test without YouTube Premium for background playback.

**Comment by seffparker** [comment]
btw, why this app installs the DPI as `split_config.xxxhdpi.apk` when all other APK uses `split_config.xxhdpi.apk`?

**Comment by milindgoel15** [comment]
DPI apk is chosen by the system, the manager only sees what dpi ur system is using and installs the required one for it.
Now I am not sure that if we don't install dpi apk, apps will still work as they would with dpi apk. I will confirm this

**Comment by seffparker** [comment]
Yes, but in my device only this app has the `xxxhdpi`:
```
# dumpsys package | grep -i xxxhdpi
    splits=[base, config.arm64_v8a, config.en, config.xxxhdpi]
          class loader context: PCL[];PCL[/data/app/com.google.android.youtube-Akuqnb3DwWvaGxj10iRrJQ==/base.apk:
/data/app/com.google.android.youtube-Akuqnb3DwWvaGxj10iRrJQ==/split_config.arm64_v8a.apk:
/data/app/com.google.android.youtube-Akuqnb3DwWvaGxj10iRrJQ==/split_config.en.apk:/data/app/com.google.android.youtube-Akuqnb3DwWvaGxj10iRrJQ==/split_config.xxxhdpi.apk]
```
All other apps are `xxhdpi`:
```
# dumpsys package | grep -wc xxhdpi
33
```
That is why I confused.

**Comment by KevinX8** [comment]
We decided to only upload xxxhdpi for root as the amount of root users is very small and the difference in resource usage also very small, apps will always just fallback to whatever the closest available dpi apk is there so it shouldn't matter that it's xxxhdpi.

**Comment by seffparker** [comment]
I have updated to Vanced version 16.29.39 and issue with the notification is resolved. The device and ROM version is still the same, only the Vanced version is changed.

So, the issue was must be with the previous version of stock or Vanced apk.
