### ISSUE TITLE
[Bug] Not play in background

### ISSUE THREAD

**Issue by Klefo0** [YTVanced/Vanced#951]
**Bug description**
App often doesn't play in background when screen go off

**Variant**
Non-Root

**Vanced version**
V16.16.38

**Android version**
 Android 7.1.1

**Device**
Oppo A83

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2. Click on one video
3. Turn off screen let the app play in background
4. Turn on screen
5. Turn off again and let it play in background

**Expected behavior**
When turn off screen in the second time, let the app play for 5 to 15 seconds, then turn on screen again, now turn off the app will play in background properly

_Attach images or videos or logcats in case of crashes if possible. These can be helpful in solving the issue._

**Comment by milindgoel15** [comment]
Disable battery optimization. It's device side issue

**Comment by Klefo0** [comment]
I have config to YTVanced not doze or background freeze or optimize battery, but it still happening, the notification still on how matter what i have done
