### ISSUE TITLE
YT vanced troubleshooting

### ISSUE THREAD

**Issue by Amit70791** [YTVanced/Vanced#954]
Hello team
I want to inform you that, i m facing trouble while opening YT vanced, app is getting open and suddenly getting crashed,  i tried many ways to fix this but still problem is same i uninstalled the application then i install, but it's not working
Please find the problem and fix i

**Comment by milindgoel15** [comment]
Attach logcat

**Comment by Amit70791** [comment]
> Attach logcat. If you can't, switch to an older version which works for you.

I can't attach any logcat or SC because it is not opening even for a second
What should I do??

**Comment by milindgoel15** [comment]
That's where you take the logcat of it using PC with adb installed or if you are rooted, using catlog.

Check [vanced guides](https://play.google.com/store/apps/details?id=com.vanced.faq) to know how to get logs.

> I can't attach any logcat or SC because it is not opening even for a second
> What should I do??

**Comment by milindgoel15** [comment]
Closing this issue because the op failed to provide logcat. If you are still facing this issue, please provide logcats.
