### ISSUE TITLE
[Idea] LiveTL implementation to YT Vanced

### ISSUE THREAD

**Issue by Kinuseka** [YTVanced/Vanced#955]
**Suggestion:**

**Why is this suggestion relevant?**
We have shown before that youtube vanced is capable of adding external features (Like the sponsor block), I am suggesting that they should add LiveTL as a way to translate live streams in realtime. As LiveTL is fully opensource, Iam sure you will be able to get some agreements with them.

**Further details:**
LiveTL should be implemented the same way as the default captions do like:
```
Japanese(auto)
LiveTL(English)
```

**Comment by milindgoel15** [comment]
It doesn't mean vanced is capable of adding some things, it can add almost anything in it. Weird logic lmao

If it's possible, vanced will do it(which I will confirm and report back here). Otherwise you have to just ask Google.

**Comment by Kinuseka** [comment]
The mindset is purely hypothetical. Saying X is working then Y might be possible is an optimistic way to think that it might be possible even if you think that it could be impossible. 

Same applies to my logic:

Vanced had added so many UI, API's and other quality of life changes that even adding this feature could be even possible and might be even beneficial. I would see it more as a toggleable feature, same as the Sponsor Block. Live TL has its own feature as well that could potentially increase the performance of the app, their feature known as the **Hyperchat** as claimed by their site: "Reduces CPU usage by 80%" and thus lengthening battery life usage.

**Comment by Kinuseka** [comment]
Worth noting that LiveTL is crowdsourced (similar to Sponsor Block) so it doesnt require any complex algorithm.

**Comment by KevinX8** [comment]
The problem with these web based extensions and trying to port them to an app is just how different things are on the app, all the UI elements are done in Facebook litho and obfuscated to shit, sponsorblock in comparison is not very UI heavy and the bulk of the code is just messing with the video player timeline. Adding the main feature of the translations sounds maybe possible by messing with the closed caption code and overriding what it shows but it sounds extremely difficult to do. The hyperchat feature sounds basically impossible to implement too.
