### ISSUE TITLE
Overlay autorepeat

### ISSUE THREAD

**Issue by Saphiriel** [YTVanced/Vanced#96]
Hello.

The autorepeat function blocks the overlay on a new repeat and keeps it open.

Tried accessibility to auto turn off but it doesnt work.

**Comment by VancedOfficial** [comment]
I have no idea what you mean, could you be a little more specific as to what happens? Give step by step instructions of how to reproduce the issue and tell what happened and what you think should've happened. Take pictures or even video if possible.

**Comment by Saphiriel** [comment]
Hello.

The autorepeat function of vanced keeps the controls overlay active after a video repeat. This happens on android, to be more specific on a few phones i tested.

The controls don't go away and i have to touch it for it to disappear.

**Comment by VancedOfficial** [comment]
I can't reproduce the issue, doesn't happen to me. Also don't think auto repeat has anything to do with it.

**Comment by Saphiriel** [comment]
This happens
