### ISSUE TITLE
[Idea] Reinstate 'Tap to seek' feature. Latest release removed Tap to seek. 

### ISSUE THREAD

**Issue by Harmonie666** [YTVanced/Vanced#962]
The devs have decided on removing Tap to seek, and I feel like this must be a terrible dream. 
I'm asking the devs kindly to put all necessary time and work into releasing a next Vanced update with Tap to seek reinstated. Removing Tap to seek is a huge mistake, and all efforts need to be put in place to reinstate it.
It's torture if we are forced to drag to seek. Please correct YouTube's mistakes, and make Vanced great again! 🙏🏻
https://user-images.githubusercontent.com/73917917/121818523-0d8e9a00-cc88-11eb-97bb-37e8648b2290.mp4

**Comment by KevinX8** [comment]
Ok if 1 million people want the feature back it will be added back, vote with 👍

**Comment by Harmonie666** [comment]
> Ok if 1 million people want the feature back it will be added back, vote with 👍 

If you count all the complaint topics in the YT/Google forum, and all the miserable experience without Tap to seek.
I can't believe you are taking this so lightly. I'm extremely disappointed to read this by a fellow YT android user.

**Comment by VancedOfficial** [comment]
> > Ok if 1 million people want the feature back it will be added back, vote with 👍
> 
> If you count all the complaint topics in the YT/Google forum, and all the miserable user experience without Tap to seek.
> I can't believe you are taking this so lightly. I'm extremely disappointed to read this by a fellow YT android user.

What are you even talking about? It was a short experiment by Google and they removed it themselves. We didn't remove it, Google did. We just added the toggle to remove it when Google forced it upon us and people didn't like it.

**Comment by Oizaro** [comment]
Just to be clear: this is one of feature that I've fixed on this version (I help the team to stabilize 16.20 before release).

At the moment there are 2 problems that prevents the re-adding:

1) The discordant opinions of users about the usefulness of this feature.
2) The possible continuous change of the google code, that could always broke the fix.

If both of these options doesn't fail, we will likely add it again on the next version.

**Comment by Harmonie666** [comment]
> > > Ok if 1 million people want the feature back it will be added back, vote with 👍
> > 
> > If you count all the complaint topics in the YT/Google forum, and all the miserable user experience without Tap to seek.
> > I can't believe you are taking this so lightly. I'm extremely disappointed to read this by a fellow YT android user.
> 
> What are you even talking about? It was a short experiment by Google and they removed it themselves. We didn't remove it, Google did. We just added the toggle to remove it when Google forced it upon us and people didn't like it.

https://www.reddit.com/r/Vanced/comments/nz28ts/why_did_you_remove_tap_to_seek_feature_please/h1n9jv4?utm_medium=android_app&utm_source=share&context=3
I'm talking about this redditors comment, saying that: 
_it technically could be restored (it was on the betas) with a lot of work but the team decided it wasn't worth the effort of maintaining it_

**Comment by KevinX8** [comment]
> > > > Ok if 1 million people want the feature back it will be added back, vote with 👍
> > > 
> > > 
> > > If you count all the complaint topics in the YT/Google forum, and all the miserable user experience without Tap to seek.
> > > I can't believe you are taking this so lightly. I'm extremely disappointed to read this by a fellow YT android user.
> > 
> > 
> > What are you even talking about? It was a short experiment by Google and they removed it themselves. We didn't remove it, Google did. We just added the toggle to remove it when Google forced it upon us and people didn't like it.
> 
> https://www.reddit.com/r/Vanced/comments/nz28ts/why_did_you_remove_tap_to_seek_feature_please/h1n9jv4?utm_medium=android_app&utm_source=share&context=3
> I'm talking about this redditors comment, saying that:
> _it technically could be restored (it was on the betas) with a lot of work but the team decided it wasn't worth the effort of maintaining it_

yes we decided it wasn't worth the time and effort to keep adding the feature back in each update?

**Comment by Harmonie666** [comment]
Out of all the features and functionalities in YouTube's Android version, this is one if not THE most valuable function. Besides of being able to view a video of course. Removing this is a huge downgrade for UX. I never said that you devs removed it, I know that this is YT's mistake. When they removed this functionality from the stock YT app, that was the day I came to Vanced, and I was so relieved and happy to find out that Vanced corrected such a huge mistake. But now I'm just speechless and shocked, that you guys even dared to release a update where Tap to seek is non-existent, instead of deciding on putting all efforts to keeping Tap to seek. No offence.

**Comment by milindgoel15** [comment]
>But now I'm just speechless and shocked, that you guys even dared to release a update where Tap to seek is non-existent, instead of deciding on putting all efforts to keeping Tap to seek. No offence.

now that's rude tbh, just do one thing, if its so easy for u to complain and bitch about it, try building it yourself. You literally have no right to decide what vanced team should or shouldn't do

**Comment by VancedOfficial** [comment]
> @VancedOfficial
> Out of all the features and functionalities in YouTube's Android version, this is one if not THE most valuable function. Besides of being able to view a video of course. Removing this is a huge downgrade for UX. I never said that you devs removed it, I know that this is YT's mistake. When they removed this functionality from the stock YT app, that was the day I came to Vanced, and I was so relieved and happy to find out that Vanced corrected such a huge mistake. But now I'm just speechless and shocked, that you guys even dared to release a update where Tap to seek is non-existent, instead of deciding on putting all efforts to keeping Tap to seek. No offence.

The feature I've been talking about has been tapping the seekbar when controls aren't visible (that red dot on the seekbar isn't visible). Google added a feature where you could click the seekbar without having the controls visible and that caused accidental seeking when trying to click buttons near the seekbar.

I didn't even realise that the tapping doesn't work anymore when the controls are visible (that red dot is visible or video is paused).

The latter one might be worth readding, the former one not.

**Comment by Harmonie666** [comment]
> >But now I'm just speechless and shocked, that you guys even dared to release a update where Tap to seek is non-existent, instead of deciding on putting all efforts to keeping Tap to seek. No offence.
> 
> now that's rude tbh, just do one thing, if its so easy for u to complain and bitch about it, try building it yourself. You literally have no right to decide what vanced team should or shouldn't do

I don't want to argue. As you can see in the first post I'm kindly asking the relevant people to reinstate Tap to seek. Sharing my honest thoughts isn't bitching around. I'm not commanding you on doing anything. I thought you would value my feedback.

**Comment by milindgoel15** [comment]
ur last comment speaks the opposite to what u said 
> But now I'm just speechless and shocked, **that you guys even dared to release a update where Tap to seek is non-existent**, instead of deciding on putting all efforts to keeping Tap to seek. No offence.

**Comment by Harmonie666** [comment]
> ur last comment speaks the opposite to what u said 
> > But now I'm just speechless and shocked, **_that you guys even dared to release a update where Tap to seek is non-existent_**, instead of deciding on putting all efforts to keeping Tap to seek. No offence.

It's how I see it. Just sharing with you my disappointment, as a fellow Android and YouTube user. It's not intended to be offensive.

**Comment by milindgoel15** [comment]
The "Tap to seek" feature was an experiment made by Google for which YouTube Vanced added a toggle for it with **an original idea to turn it off**, not to turn it on. However, Google eventually removed it due to the fact that it had resulted in accidental touches by various users from all over the world, which the Vanced team wholeheartedly agrees with. 

As of, v16.20 build, the feature was broken completely in the very initial vanced beta but was eventually patched to make it work by oizaro so that the toggle could be used to enable "tap to seek". The feature was removed from the public release because the vanced team doesn't want to bother fixing such an issue with every youtube version as google broke it again with the next v16.22 build. 
 
For future vanced builds, we will eventually keep an eye on this and see if any future youtube versions don't break it. If our patcher does work, the feature will likely come back as a toggleable feature(again). But we can not give any promises regarding it as it's time-consuming and ain't worth fixing. If it doesn't patch in the end, you all have to live with it or ask google to bring it back for you.

Regarding your rude behavior and the disappointment you felt from the sudden change, we cannot do anything about it as google is the one who killed it so you are supposed to complain there. Please do not bring your personal issues in vanced forums. Vanced is a free & personal project and no one is making you pay to use it nor we want it. We are closing this issue with this.

**Comment by KevinX8** [comment]
it's been added back in the hotfix @Harmonie666

**Comment by Harmonie666** [comment]
I wonder what kind of Boomers complained about accidentally taping to seek. Never happened to me, and never crossed my mind.

Below you find one of many complaint topics, from stock YT users. I complained and asked that Tap to seek should be added back aswell. But Google never reverts their changes, so it's hopeless with them:

https://support.google.com/youtube/thread/77038657/cannot-fast-forward-by-video-progress-line?hl=en

**Comment by Harmonie666** [comment]
> it's been added back in the hotfix @Harmonie666, your bad dream is over

You are THE MAN. Forgive me if I came across as rude. Again, it truly wasn't my intention.

**Comment by Harmonie666** [comment]
https://www.reddit.com/r/Vanced/comments/o3x5l2/question_is_it_me_or_you_all_have_the_same_issue/?utm_medium=android_app&utm_source=share

**Comment by Harmonie666** [comment]
Just wanted to let you guys know, that the German translation for Tap to seek is wrong.

![Screenshot_20210621-193502280 (1).png](https://user-images.githubusercontent.com/73917917/122804266-fd9a3a00-d2c7-11eb-8c0a-f697b03c0a43.png)

It should say "Suchleiste antippen".
"antippen" is the correct word, because you are not clicking on your phone.

**Comment by Harmonie666** [comment]
> Just wanted to let you guys know, that the German translation for Tap to seek is wrong.
> 
> ![Screenshot_20210621-193502280 (1).png](https://user-images.githubusercontent.com/73917917/122804266-fd9a3a00-d2c7-11eb-8c0a-f697b03c0a43.png)
> 
> It should say "Suchleiste antippen".
> "antippen" is the correct word, because you are not clicking on your phone.

@VancedOfficial Just FYI.

**Comment by milindgoel15** [comment]
Xfilefin doesn't maintain the translation. The translations are done and maintained by users. If you would like to fix such translation, start doing it on [crowdin](crowdin.com/project/vanced).
