### ISSUE TITLE
[Bug] Links Not Opening

### ISSUE THREAD

**Issue by bwinnirmal** [YTVanced/Vanced#963]
**Bug description**
Cant Able To Open Links Whenever Ill Click On Links In The Discription It Will show Error Youtube Cant Able To Open Links.

**Variant**
Non-Root

**Vanced version**

16.20.35

**Android version**

Android 11 

**Device**
Realme 6 Pro

Screen Shot

https://ibb.co/nPKbBvT

**Comment by milindgoel15** [comment]
Duplicate of #774
