### ISSUE TITLE
16.16.38 casting issue still exists in 16.20.35

### ISSUE THREAD

**Issue by JDMorris81** [YTVanced/Vanced#968]
**Bug description**
When attempting to cast, a message comes up prompting to update play services. 

**Variant**
Non-Root

**Vanced version**
v16.20.35

**Android version**
Android 11 

**Device**
Galaxy S20 5G

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2. Click on 'cast icon'
3. Select casting device

**Expected behavior**
Vanced should connect with selected casting device. 

_Attach images or videos or logcats in case of crashes if possible. These can be helpful in solving the issue._

**Comment by KevinX8** [comment]
The issue is not related to Vanced it's microg, please move it to the Vanced microg repo
