### ISSUE TITLE
[Bug] video buffer setting crash

### ISSUE THREAD

**Issue by Damo7784** [YTVanced/Vanced#969]
Setting the max amount of preloaded video time too high causes the app to crash, and even after a reinstall it does not work and can't be opened. Could a cap be added so that it prevents you from setting it to a value that crashes the app?

**Comment by KevinX8** [comment]
Um we didn't even know there was a cap, what is it? I've tried insanely large values before without issue

**Comment by Damo7784** [comment]
I just put in a ton of 9's so that it would load as much as possible in advanced, can't remember the exact value. If it helps I have a galaxy note10, 8gb ram.Sent from my Galaxy
-------- Original message --------From: KevinX8 ***@***.***> Date: 14/06/2021  23:31  (GMT+00:00) To: YTVanced/Vanced ***@***.***> Cc: Damo7784 ***@***.***>, Author ***@***.***> Subject: Re: [YTVanced/Vanced] [Bug] video buffer setting crash (#969) 
Um we didn't even know there was a cap, what is it? I've tried insanely large values before without issue

**Comment by Damo7784** [comment]
Also I now get an app crash popup everything it tries to send a notification from YouTube.

**Comment by Damo7784** [comment]
@KevinX8
Even after a redownload of the app on the most recent update I still can't open it, is there a way to reset my settings on the app without having access to it?

**Comment by milindgoel15** [comment]
Clear data from app settings
