### ISSUE TITLE
[idea]Add Newpipe into vanced

### ISSUE THREAD

**Issue by stralpt** [YTVanced/Vanced#97]
Add newpipe into vanced and get ability to save a videos,audios (.m4a) and/playlists into gallery.

Especially for Vanced Music it could be cool,it can download a songs ✌✌👍👍

**Comment by X1nto** [comment]
will be added in previous update ✌✌👍👍

**Comment by stralpt** [comment]
> will be added in previous update ✌✌👍👍

Saňskuy you'rè the best

**Comment by stralpt** [comment]
> will be added in previous update ✌✌👍👍

Wait what?,previous or next update?

**Comment by X1nto** [comment]
> > will be added in previous update ✌✌👍👍
> 
> Wait what?,previous or next update?

Never. It was a joke

**Comment by stralpt** [comment]
> > > will be added in previous update ✌✌👍👍
> > 
> > 
> > Wait what?,previous or next update?
> 
> Never. It was a joke

Fuck you men,hope you infected by covid19 virus,norovirus and blackdeath, from your skin till your bones.

**Comment by X1nto** [comment]
> > > > will be added in previous update ✌✌👍👍
> > > 
> > > 
> > > Wait what?,previous or next update?
> > 
> > Never. It was a joke
> 
> Fuck you men,hope you infected by covid19 virus,norovirus and blackdeath, from your skin till your bones.

Same

**Comment by stralpt** [comment]
> > > > > will be added in previous update ✌✌👍👍
> > > > 
> > > > 
> > > > Wait what?,previous or next update?
> > > 
> > > 
> > > Never. It was a joke
> > 
> > 
> > Fuck you men,hope you infected by covid19 virus,norovirus and blackdeath, from your skin till your bones.
> 
> Same

Never, it just a freaking jokes

**Comment by X1nto** [comment]
> > > > > > will be added in previous update ✌✌👍👍
> > > > > 
> > > > > 
> > > > > Wait what?,previous or next update?
> > > > 
> > > > 
> > > > Never. It was a joke
> > > 
> > > 
> > > Fuck you men,hope you infected by covid19 virus,norovirus and blackdeath, from your skin till your bones.
> > 
> > Same
> 
> Never, it just a freaking jokes

The thing you asked will never be added because it's an absurd. First of all it would be extremely hard to do it because vanced is not compiled from source, and second download feature will never be added as it led many mods to close

**Comment by stralpt** [comment]
Okay,it's bloody ridiculous,im just thinking of cool thing but it going absurd.
Maybe i just use vanced and newpipe on their original way LOL
