### ISSUE TITLE
[Idea] permanent 'videos only' option in subscription feed

### ISSUE THREAD

**Issue by dph121** [YTVanced/Vanced#970]
Currently, the subscriptions tab defaults to a mix of videos and posts. It is possible to hide posts temporarily by scrolling to the right in the banner beneath the icons of channels you are subscribed to, clicking 'settings' and selecting 'videos only', but this resets every time the subscription feed is reloaded (after a search, after closing the app, etc.). I would like the ability to enable this filter permanently.

A similar feature exists in Vanced to filter out stories (in-app user icon > settings > vanced settings > layout settings > Youtube Stories (experimental)). Such a toggle option could be added in the same menu for filtering out posts.

Thanks in advance for considering this addition.

**Comment by milindgoel15** [comment]
It stays to videos only for me. Even after reloading or restarting the app. Problem is on your end

**Comment by Isssuemaker** [comment]
Just block community post from vanced settings and you will get video only
