### ISSUE TITLE
[Bug] replaceme

### ISSUE THREAD

**Issue by Xieli77** [YTVanced/Vanced#973]
**Bug description**
Autoplay next video button not working 

**Variant**
Non-Root

**Vanced version**
16.20. 35

**Android version**
11
 **Device**
Galaxy s10+
**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
3. ....

**Expected behavior**
After finishing the current video the next video should've automatically start to play after the countdown. But it just stops. There's a option and i have to manually press the play now button.

**Comment by milindgoel15** [comment]
Enable auto Play from yt player itself back again

**Comment by milindgoel15** [comment]
Try reinstalling vanced and use stock settings.

**Comment by Xieli77** [comment]
😃Its working! Thnakyou😄👌😍
