### ISSUE TITLE
[Idea] Toggle to remove fundraisers from videos.

### ISSUE THREAD

**Issue by supernoodled** [YTVanced/Vanced#975]
**Description**
Add a toggle to remove fundraisers from videos. 
I don't want to donate to your fundraiser.

![20210615_205736](https://user-images.githubusercontent.com/31737227/122115419-6131ec80-ce1c-11eb-9f04-246ff94af90d.jpg)

**Comment by milindgoel15** [comment]
It's not our fundraiser. It's those channels you subscribed them to. 🤦‍♂️🤦‍♂️ If you can't support your favourite creators even, don't use YouTube at all.
