### ISSUE TITLE
[Bug] replaceme

### ISSUE THREAD

**Issue by Mimicthis** [YTVanced/Vanced#976]
**Bug description**
I'm so sorry but this is a real bug. 
When doing a slide up gesture to get the video to the full screen, it exits immediately and I have to re-enter the fullscreen view. Only when I press the square icon does it work without closing immediately,reverting to the vertical view. 

**Variant**
Non-Root

**Vanced version**
16.20.35

**Android version**
Android 11 

**Device**
Samsung Galaxy S10 Plus 

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2. Click on any video
3. Now your holding your phone vertically 
4. Slide up your finger on the video to get it to full screen 
5. It shall exit immediately from the full-screen and you need to do that to enter it again. 

**Expected behavior**
1. Click on a video
2. Video opens in a normal top horizontal view
3. Slide up gesture works and the video doesn't revert to the original size, instead it stays in the full size.

**Comment by milindgoel15** [comment]
ROM issue. We can't do anything about this. I will confirm this with xfile for sure but it's pretty much ROM related anyway.

**Comment by milindgoel15** [comment]
Your device software(in your case it's oneUI)

**Comment by Mimicthis** [comment]
But regular YouTube also does that.

**Comment by milindgoel15** [comment]
> But regular YouTube also does that.

that's why it's a ROM(oneui) bug and your manufacturer has to provide a fix for you, not us or even youtube.
