### ISSUE TITLE
[Bug] YT Music album art issue with device files

### ISSUE THREAD

**Issue by Fabiofdez** [YTVanced/Vanced#977]
**Bug description**
Not sure whether this is widespread, but recently I've been experiencing a bug in YT Music Vanced where the album art for all device files disappears, as in the album art is just black and appears empty. I've made sure it's isolated to YT Music Vanced because other media players have no such issue. The only way to temporarily fix it is clearing all app data, as that also clears permissions and requires permission to regain access to device files, but once the app is again closed and reopened the issue returns, to no avail. I've reverted to 4.07.51 and it seems the issue doesn't occur in that version. I've also tried disabling app optimizations, as well as revoking and re-adding storage permissions, but the only thing that seems to momentarily help is, like previously explained, clearing all app data. 

**Variant**
Non-Root

**Vanced version**
I'm on the latest version 4.30.51, and the issue occurs as far back as 4.24.51.

**Android version**
Android 11 

**Device**
Samsung Galaxy Note 20 Ultra

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app, click on library
2. Click on any section; Playlists, albums, songs etc
3. Click into device files section, album art may initially appear if it's the first time accessing them
4. If the app is closed and reopened and the above steps are repeated to access device files, the album art is no longer there.

**Expected behavior**
It's expected that device files' album art appears just as in every media player, and it continues to appear always, even if the app is closed and reopened.

**Comment by milindgoel15** [comment]
YouTube music vanced/youtube music is different code than other offline music players. They have connection with each other. If you want to compare vanced music with anyone, compare it with official yt music not some other player with whole different code.
