### ISSUE TITLE
[Bug] Comments on Youtube Vanced are non-existent

### ISSUE THREAD

**Issue by xXRealXxx** [YTVanced/Vanced#978]
**Bug description**
Since the last few updates comments are invisible for me and there's no way to bring them back. No comments button or anything. If I scroll down I just get more recommended videos. 

**Variant**
Non-Root

**Vanced version**
v16.20.35

**Android version**
Android 9

**Device**
Huawei P20 lite

**Steps to Reproduce**
Just open any video. 

**Expected behavior**
Comments being visible instead of them dissappearing into the void.

[Screenshot](https://imgur.com/a/8w2nC51)

**Comment by milindgoel15** [comment]
Don't enable stuff you don't know what they do. Either turn off comments removal or clear data and start fresh with this(recommended)

**Comment by xXRealXxx** [comment]
I didn't enable any settings that I didn't know what they do. Everything is self-explanatory in settings (at least for me). 
Turns out comment removal was turned on by DEFAULT in the ad settings. Why is that even in the ad settings in the first place?

**Comment by VancedOfficial** [comment]
> I didn't enable any settings that I didn't know what they do. Everything is self-explanatory in the settings (at least for me).
> Turns out comment removal was turned on by DEFAULT in the ad settings. Why is that even in the ad settings in the first place?

The only thing turned on by default there is the ad removal, so you did turn comment removal on yourself. It's in there because all the settings there go through the same removal method (Litho stuff). It was first for just ad settings and we just haven't gotten around to change the name.

**Comment by xXRealXxx** [comment]
Perhaps I accidentally turned it on. 
Anyway, hopefully this will help someone who is confused about this.
