### ISSUE TITLE
Bug on audio 

### ISSUE THREAD

**Issue by Sanjay2802** [YTVanced/Vanced#979]
YOUTUBE VANCED 

**Bug description**
GETTING AUDIO BUG , SOME EXTRA NOISE IS COMING WHEN PLAYING IN EARPHONE ,WHEN I CLEAR CACHE IT WORKS FINE FOR THAT TIME THEN WHEN I PLAY AGAIN THE PROBLEM CONTINUES

**Variant**
Non-Root

**Vanced version**
 v16.20.35

**Android version**
 Android 11 

**Device**
OnePlus 7

**Expected behavior**
Finding bug on the latest version but other previous versions are fine

**Comment by milindgoel15** [comment]
define "extra noise" lol. Also before reporting any issues, check your issues on the same version of official youtube as vanced is. Then report back with more descriptive information.

**Comment by Sanjay2802** [comment]
It's working well on YouTube official, even on previous versions of YouTube VANCED , the problem is with latest version

**Comment by milindgoel15** [comment]
So in which year you are going to define the audio bug u are getting? 2121?

**Comment by Sanjay2802** [comment]
Yoo bro it's 16.20.35 only , mistakenly typed

**Comment by milindgoel15** [comment]
Closing this issue because the OP failed to provide the necessary information. If you have any useful information other than saying extra noise/audio bug, please send. Otherwise wait for future updates.
