### ISSUE TITLE
Vanced is not working but the usual youtube is working and my app is up to date it is "you are offline"

### ISSUE THREAD

**Issue by MrNoOne456** [YTVanced/Vanced#98]
My internet and everything is good its just the vanced what is not working it was working like 2 hours ago it just stopped working after that iits just saying "you're offline" 
My device : poco f1 / pocophone f1
My rom : miui 10.3.7.0
Android version : 9
Chipset : SD845
![Screenshot_2020-10-18-20-44-55-291_com vanced android youtube](https://user-images.githubusercontent.com/67577744/96373089-d95dea80-1187-11eb-9bb3-9b0be2749f70.png)

**Comment by Macdom** [comment]
Go to google settings and remove your account, then re-add it
