### ISSUE TITLE
[Bug] There's a button (add to a playlist) in youtube. Touch this button makes video add to my recent playlist. And plus, popup message button shows to change playlist.  This  change playlist popup button does not synchronized quickly..  This happens in original youtube app too. It's slight but little bit annoying when a video get into wrong playlist.    / Non Root

### ISSUE THREAD

**Issue by pgunter123** [YTVanced/Vanced#981]
**Bug description**
Replace me with a clear and detailed description of the bug.

**Variant**
Non-Root/Root

**Vanced version**
Replace me with the exact version of vanced you are using. It is mandatory to report issues from the latest available versions only. For example, v16.16.38

**Android version**
Replace me with the version of Android your device have. For example, Android 11 

**Device**
Replace with the name of the device on which you faced the bug. For example, Samsung Galaxy S8

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
3. ....

**Expected behavior**
Replace me with a description of what you expected should happen and what happened instead.

_Attach images or videos or logcats in case of crashes if possible. These can be helpful in solving the issue._

**Comment by milindgoel15** [comment]
Ask Google to fix this issue for you. It's stock bug and hence not our problem to deal with.

**Comment by pgunter123** [comment]
> Ask Google to fix this issue for you. It's stock bug and hence not our problem to deal with.

sorry
