### ISSUE TITLE
[Bug] replaceme

### ISSUE THREAD

**Issue by Ksanbah** [YTVanced/Vanced#984]
**Bug description**
The App has been hanging and crashing. 

**Variant**
Non-Root

**Vanced version**
v16.20.35

**Android version**
Android 11 

**Device**
Oppo Reno 3

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2. Click on 'a random video'
3. ....

**Expected behavior**
The video will either play or the video will hang and crash. 

_Attach images or videos or logcats in case of crashes if possible. These can be helpful in solving the issue._ :-  https://drive.google.com/file/d/1bACDt_o_bByR6oiTpwEeBU3K_KDd5Qbg/view?usp=drivesdk

**Comment by milindgoel15** [comment]
Issue with your ROM. Try clean install. And I see that you have setup vanced on work profile too. Use it on main only and check it lags again or not.

**Comment by Ksanbah** [comment]
Thanks
