### ISSUE TITLE
[Bug] Unable to swipe/scroll to see all my subscriptions

### ISSUE THREAD

**Issue by VyzerMusic** [YTVanced/Vanced#985]
**Bug description**
On the subscription page, at the top where it shows all the channels I am subscribed to, I am unable to swipe/scroll through them. 

**Variant**
Non-Root

**Vanced version**
v16.20.35

**Android version**
10

**Device**
Huawei Y9 Prime

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2. Click on "subscriptions" tab
3. Attempt scrolling to the left to see more subscriptions

**Expected behavior**
Being able to scroll/see all the channels I'm subscribed to
[Gif of bug](https://imgur.com/a/DKT3TRC)

**Comment by milindgoel15** [comment]
Clear data and try again.

**Comment by VyzerMusic** [comment]
Through process of elimination, I figured out that the "Comments Location" is what's causing the problem, so hopefully it can be fixed soon since I prefer the comment section to be on the bottom.

**Comment by milindgoel15** [comment]
Oh hmm the comments location is itself experimental feature and many other things breaks with it. Not sure if xfile will keep it in the future or if he can fix it. So wait for future updates.

**Comment by VyzerMusic** [comment]
Alright, thank you for your response, hope everything works out
