### ISSUE TITLE
Enable the button to add youtube kids to playlists

### ISSUE THREAD

**Issue by oSumAtrIX** [YTVanced/Vanced#986]
> It's server sided, not client

I have created a playlist with a youtube kids video, which per rule should've not been possible, thus confirming there is not any server side check being done. This means, that the client side restriction on disabling the "add to playlist" button can be disabled in the vanced client.

https://www.youtube.com/watch?v=6dKi71IeG6o&list=PLUe3wdrAaq2qYvhvLY-vRwrySdnuWQeiq

_Originally posted by @oSumAtrIX in https://github.com/YTVanced/Vanced/issues/913#issuecomment-860325040_

**Comment by milindgoel15** [comment]
Closing this issue cuz why create duplicate lol
