### ISSUE TITLE
YT Vanced video and whole app studders/lags when going through comments

### ISSUE THREAD

**Issue by XKlarity** [YTVanced/Vanced#995]
A lot of the time, when I am watching a video and going through comments the whole app starts to studder and lag so I have to force close vanced and restart it. It only started happening recently and never did this before. I think it might be a memory leak but im not sure how to check though.

**Comment by dmack6464** [comment]
I'm having a similar issue on my s9

**Comment by milindgoel15** [comment]
Probably something to do with microG. No fix for it.
