### ISSUE TITLE
[Idea] Save Youtube watch history even if s.youtube.com is blocked

### ISSUE THREAD

**Issue by FBIAgent05** [YTVanced/Vanced#997]
**Description**
Ability to save Youtube watch history locally even if s.youtube.com is blocked

Newpipe already has this feature

![Screenshot_20210622_212908.jpg](https://user-images.githubusercontent.com/74946397/122933129-eda25900-d3a0-11eb-9d7c-df17e3696026.jpg)

**Comment by milindgoel15** [comment]
YouTube is totally server dependent app(guess you forgot about it?), not local.
