### ISSUE TITLE
[Idea] Add ability to filter out videos by title and/or type

### ISSUE THREAD

**Issue by jrddupont** [YTVanced/Vanced#998]
I would like to be able to filter out videos from my subscription (and home) feed depending on configured criteria:  

Words in the title   
Words in channel name  
If the video is a premiere    
If the video is a live broadcast   
Etc  
  
Basically I know that I never want to see a premiere, and I don't want to see prozd eating food, so being able to filter out certain content would be extremely useful

**Comment by milindgoel15** [comment]
Ask Google

**Comment by jrddupont** [comment]
Not sure I understand, is it already a feature somewhere?
